== Azure MySQL Database Server SSL connection is disabled
// Azure MySQL Database Server SSL connection disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| cc96a6d0-3251-4bf9-aaa4-349c34810721

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/MySQLServerSSLEnforcementEnabled.py[CKV_AZURE_28]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|ARM, Terraform, Bicep, TerraformPlan

|=== 



=== Description 


SSL connectivity provides a new layer of security by connecting a database server to client applications using Secure Sockets Layer (SSL).
Enforcing SSL connections between a database server and client applications helps protect against _man-in-the-middle_ attacks.
This is achieved by encrypting the data stream between the server and application.
We recommend you set *Enforce SSL connection* to *Enable* on MYSQL Server databases.
////
=== Fix - Runtime


* Azure Portal To change the policy using the Azure Portal, follow these steps:* 



. Log in to the Azure Portal at https://portal.azure.com.

. Navigate to * Azure Database* for * MySQL server*.

. For each database:  a) Click * Connection security*.
+
b) Navigate to *SSL Settings **section.
+
c) To * Enforce SSL connection* click * ENABLED*.


* CLI Command* 


To set MYSQL Databases to Enforce SSL connection, use the following command:
----
az mysql server update
--resource-group & lt;resourceGroupName>
--name & lt;serverName>
--ssl-enforcement Enabled
----
////
=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_mysql_server
* *Arguments:* ssl_enforcement_enabled


[source,go]
----
resource "azurerm_mysql_server" "example" {
    ...
 +  ssl_enforcement_enabled             = true
}
----

