== Azure PostgreSQL database server with SSL connection disabled
// Azure PostgreSQL Database Server SSL connection disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| bf4ad407-076c-40b9-a8fa-a0c80352a744

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/PostgreSQLServerSSLEnforcementEnabled.py[CKV_AZURE_29]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|ARM, Terraform, Bicep, TerraformPlan

|=== 



=== Description 


*SSL connectivity* provides a new layer of security by connecting a database server to client applications using a Secure Sockets Layer (SSL).
Enforcing SSL connections between a database server and client applications helps protect against _man-in-the-middle_ attacks.
This is achieved by encrypting the data stream between the server and application.
We recommend you set *Enforce SSL connection* to** Enable** on PostgreSQL Server databases.
////
=== Fix - Runtime


* Azure Portal To change the policy using the Azure Portal, follow these steps:* 



. Log in to the Azure Portal at https://portal.azure.com.

. Navigate to * Azure Database* for * PostgreSQL server*.

. For each database:  a) Click * Connection security*.
+
b) Navigate to *SSL Settings **section.
+
c) To * Enforce SSL connection* click * ENABLED*.


* CLI Command* 


To set * Enforce SSL Connection* for  a* PostgreSQL Database**, use the following command:
----
az postgres server update
--resource-group & lt;resourceGroupName>
--name & lt;serverName>
--ssl-enforcement Enabled
----
////
=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_postgresql_server
* *Arguments:* ssl_enforcement_enabled


[source,go]
----
resource "azurerm_postgresql_server" "example" {
    ...
 +  ssl_enforcement_enabled             = true
}
----

