== zure container container group is not deployed into a virtual network
// Azure Container group not deployed into a virtual network


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| dd2feacf-8890-43e9-ab55-651bf3ae1c03

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/AzureContainerGroupDeployedIntoVirtualNetwork.py[CKV_AZURE_98]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan

|=== 



=== Description 


A virtual network is a logical network in Azure that is isolated from other networks.
When you deploy a container group into a virtual network, you can control the inbound and outbound network traffic to and from your container group using network security groups (NSGs) and service endpoints.
This can help to improve the security of your container group and protect it from unauthorized access or attacks.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_container_group
* *Arguments:* network_profile_id


[source,go]
----
resource "azurerm_container_group" "example" {
              ...
              
  +           network_profile_id = "network_profile_id"    
            }
----

