== Azure Event Grid domain public network access is enabled
// Azure Event Grid domain public network access enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 58c7b0ec-3c69-4879-bdab-35dd49536d7b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/EventgridDomainNetworkAccess.py[CKV_AZURE_106]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan

|=== 



=== Description 


By ensuring that your Azure Event Grid domain is not public, you can help protect your data from unauthorized access or tampering.
Public Azure Event Grid domains are accessible over the internet, which can make them vulnerable to external threats such as hackers or malware.
By making it private, you can help ensure that only authorized users can access the data.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_eventgrid_domain
* *Arguments:* public_network_access_enabled


[source,go]
----
resource "azurerm_eventgrid_domain" "example" {
              ...
+             public_network_access_enabled = false
              }
----

