== Prisma Cloud container images

Prisma Cloud images are built from the https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?gti-tabs=unauthenticated[RedHat Universal Base Image 8 Minimal] (UBI8-minimal) which is designed for applications that contain their own dependencies. With an active subscription or a valid license key, you can retrieve the images from a cloud registry.
This option simplifies a lot of workflows, especially the install flow.

CAUTION: All builds, including private builds, are published to the registry.
Private builds temporarily address specific customer issues.
Unless you've been asked to use a private build by a Prisma Cloud representative during the course of a support case, you should only pull officially published builds.

You can optionally manage Prisma Cloud images in your own registry.
You can push the Prisma Cloud images to your own private registry, and manage them from there as you see fit.
ifdef::compute_edition[]
The Console image is delivered as a _.tar.gz_ file in the release tarball.
endif::compute_edition[]
The Defender image can be downloaded from Console, under *Manage > System > Utilities*, or from the Prisma Cloud API.

There are two different methods for accessing images in the cloud registry:

* Basic authorization.
* URL authorization.

ifdef::compute_edition[]
The length of time that images are available on the cloud registry complies with our standard xref:../welcome/support_lifecycle.adoc[n-1 support lifecycle].
endif::compute_edition[]


[.task]
=== Retrieving Prisma Cloud images using basic auth

Authenticate using _docker login_ or _podman login_, then retrieve the Prisma Cloud images using _docker pull_ or _podman pull_.
For basic authorization, the registry is accessible at _registry.twistlock.com_.

[IMPORTANT]
====
Image names contain a version string.
The version string must be formatted as X_Y_Z, where X is the major version, Y is the minor version, and Z is the patch number.
For example, 19.07.363 should be formatted as 19_07_363.
For example:

registry.twistlock.com/twistlock/defender:defender_19_07_363.
====

*Prerequisites:*

* You have your Prisma Cloud access token.

[.procedure]
. Authenticate with the registry.
+
  $ docker (or podman) login registry.twistlock.com
  Username:
  Password:
+
Where *Username* can be any string, and *Password* must be your access token.

ifdef::compute_edition[]
. Pull the Console image from the Prisma Cloud registry.

  $ docker (or podman) pull registry.twistlock.com/twistlock/console:console_<VERSION>

endif::compute_edition[]

. Pull the Defender image from the Prisma Cloud registry.

  $ docker (or podman) pull registry.twistlock.com/twistlock/defender:defender_<VERSION>


[.task]
=== Retrieving Prisma Cloud images using URL auth

Retrieve Prisma Cloud images with a single command by embedding your access token into the registry URL.
For URL authorization, the registry is accessible at _registry-auth.twistlock.com_.

By embedding your access token into the registry URL, you only need to run _docker pull_ or _podman pull_.
The _docker login_ or _podman login_ command isn't required.

The format for the registry URL is: `registry-auth.twistlock.com/tw_<ACCESS-TOKEN>/<IMAGE>:<TAG>`

[IMPORTANT]
====
Image names contain a version string.
The version string must be formatted as X_Y_Z, where X is the major version, Y is the minor version, and Z is the patch number.
For example, 19.07.363 should be formatted as 19_07_363.
For example:

registry.twistlock.com/twistlock/defender:defender_19_07_363.
====

*Prerequisites:*

* You have a Prisma Cloud access token.
* The Docker or Podman client requires that repository names be lowercase.
Therefore, all characters in your access token must be lowercase.
To convert your access token to lowercase characters, use the following command:
+
  $ echo <ACCESS-TOKEN> | tr '[:upper:]' '[:lower:]'

[.procedure]
ifdef::compute_edition[]
. Pull the Console image from the Prisma Cloud registry.

  $ docker (or podman) pull \
    registry-auth.twistlock.com/tw_<ACCESS-TOKEN>/twistlock/console:console_<VERION>

endif::compute_edition[]

. Pull the Defender image from the Prisma Cloud registry.

  $ docker (or podman) pull \
    registry-auth.twistlock.com/tw_<ACCESS-TOKEN>/twistlock/defender:defender_<VERSION>
