[#id073438e9-b6f0-4567-8363-52df1b4fb07a]
== Onboard Your Alibaba Cloud Account
To begin monitoring the resources on your cloud infrastructure, connect your Alibaba cloud accounts to Prisma® Cloud.

Use Prisma® Cloud for monitoring your Alibaba Cloud infrastructure in Mainland China and International regions.

To begin monitoring the resources on your cloud infrastructure, you must first create a role on Alibaba Cloud and then connect your Alibaba cloud account to Prisma Cloud. When you add your cloud account to Prisma Cloud, the API integration between your cloud infrastructure provider and Prisma Cloud is established and you can begin monitoring the resources and identify potential security risks in your infrastructure.

* xref:set-up-your-alibaba-account.adoc#idee726cec-b150-4834-b1f3-1c41e7ade8a8[Set Up Your Alibaba Account]

* xref:add-alibaba-cloud-account-to-prisma-cloud.adoc#id41bb9b8b-8f8e-4822-9874-6537a06fb07c[Add an Alibaba Cloud Account on Prisma Cloud]

* xref:alibaba-apis-ingested-by-prisma-cloud.adoc#idb176ea47-8238-4153-826d-d193868e86e9[Alibaba APIs Ingested by Prisma Cloud]




