[#id-june2023]
== Features Introduced in June 2023

Learn about the new Compute capabilities on Prisma™ Cloud Enterprise Edition (SaaS) in June 2023.

The host, container, and serverless capabilities on the *Compute* tab are being upgraded starting on June 18, 2023. When upgraded, the version will be 30.02.xxx.

//TBD: This release includes fixes, and there are no new features in this release.

* xref:#new-features-prisma-cloud-compute[New Features in Prisma Cloud Compute]
* xref:#api-changes[API Changes]
//* xref:#id-backward-compatibility[Backward Compatibility for New Features]
* xref:#end-of-support[End of Support Notifications]
* See also xref:prisma-cloud-compute-known-issues.adoc[Known Issues]

[#new-features-prisma-cloud-compute]
=== New Features in Prisma Cloud Compute

[cols="50%a,50%a"]
|===
|Feature
|Description

[#enhancements]
2+|*Enhancements*

//CWP-34539
|*Support custom compliance checks*
|Added support for custom compliance checks on clusters running `containerd` runtime.

//CWP-44813
|*Added Support for Managed Identities in Azure*
|Added support for Azure Managed Identities to authenticate any Azure resources that support AD authentication without adding keys in Prisma Console.
To use this authentication method, add an Azure role with required permissions to scan the resources under *Manage > Cloud accounts*.

2+|*Support for New Operating Systems*

//CWP-48511
|*Windows Server 2016*
|Reinstating the support for Defenders on Windows 2016. For details on the extended support from Microsoft, see https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2016

//RLP-104114
|*Added new NAT gateway IP addresses*
|Prisma Cloud is adding new NAT IP addresses for the Compute SaaS Console Region in GCP. The egress IPs for connections from The Compute SaaS Console to the internet in us-east 1 (South Carolina) are:
`34.139.64.150` and `34.139.249.192`.

Make sure to add these IP addresses to your allow list.
These IP addresses will be added to the https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/get-started-with-prisma-cloud/enable-access-prisma-cloud-console#id7cb1c15c-a2fa-4072-b074-063158eeec08_idcb6d3cd4-d1bf-450a-b0ec-41c23a4d4280[documentation].

2+|*New Features in Agentless Security*

//CWP-46871
|*Encrypted volumes support in GCP with hub mode*
|This feature adds the capability to scan encrypted volumes in GCP with agentless scanning when using hub mode.

2+|*New Features in Host Security*

//CWP-47766
|*Containerd and CRI - ADD support for some docker compliance checks*
|

|*Change in the format of runtime events information used in notification webhooks*
|Replaced the `aggregated` and `rest` macros with the following macros:

* `aggregatedAlerts`: Returns the aggregated audit events in `JSON` format. It represents the same data as the old `aggregated` macro but in `JSON` format instead of text.

* `dropped`: Returns the number of alerts that were dropped after the aggregation buffer has reached its limit.

This change fixes an issue where some of the aggregated alerts were missing fields like `ContainerID`, `Namespace`, and `User`.

The `aggregated` and `rest` macros are still available but are being deprecated after the two upcoming releases following our deprecation notice policy.
For existing settings of alert providers, you must edit the alert structure and use the new macros.

|===

[#api-changes]
=== API Changes
[cols="49%a,51%a"]
|===
|CHANGE
|DESCRIPTION


//CWP-48536
|*Add Backward Compatibility to api/v1/cloud/discovery/entities*
|The *api/vVERSION/cloud/discovery/entities* API endpoint is now available as a supported and backward-compatible route to view the cloud discovered entities.

//CWP-45206
|*Monitor the status of an OnDemand and Regular registry scan*
|The new API endpoint *api/vVERSION/registry/progress* is available to view the progress of onDemand and regular ongoing registry scans. Set the request parameter *onDemand* to true to view progress of an ongoing on-demand scan. By default, *onDemand* is set to false and shows the progress of a regular scan.

|===

[#breaking-api-changes]
=== Breaking Changes in API
[cols="49%a,51%a"]
|===
|CHANGE
|DESCRIPTION


//CWP-48451
|*Defender APIs modified to support the containerd runtime*
|The following APIs have been enhanced to include support for the containerd runtime in addition to the existing Docker and CRI-O runtimes: 

* POST, `/api/vVERSION/defenders/daemonset.yaml`

* POST, `/api/vVERSION/defenders/helm/twistlock-defender-helm.tar.gz`

The `cri` boolean parameter (in the `common.DaemonSetOptions` schema) in the above endpoints has been replaced by the `common.ContainerRuntime` schema in the 30.02 release, as shown below:

*Old (30.01 and earlier releases)* 

[source,json]
----
"cri": {
"description": "Indicates that Defender uses CRI instead of docker.\n",
"type": "boolean"
}
----

*New (in release 30.02)*
[source,json]
----
"containerRuntime": 
{
    "$ref": "#/components/schemas/common.ContainerRuntime"
},

"common.ContainerRuntime": 
{
    "description": "Represents the supported container runtime types",
    "enum": [
                [
                    "docker",
                    "containerd",
                    "crio"
                ]
            ],

    "type": "string"
}
----

This change is applicable from the 30.02 release and is backward compatible. 

IMPORTANT: You must update existing scripts that use either of the two endpoints when you upgrade to 30.02 or a future release.

|===

[#end-of-support]
=== End of Support Notifications

[cols="50%a,50%a"]
|===
2+|Notices

//CWP-43837
|*Upcoming deprecation of macros used for runtime events webhooks*
|Following our deprecation policy, the `aggregated` and `rest` macros will be deprecated.
For the existing webhook alerts, you can edit the custom JSON body and replace `#aggregated` macro with `#aggregatedAlerts` and `#rest` macro with `#dropped`.

|===
