[#idbcabf073-287c-4563-9c1f-382e65422ff9]
== Look Ahead — Planned Updates on Prisma Cloud Compute

// Review any deprecation notices and new features planned in the next Prisma Cloud Compute release.

See xref:prisma-cloud-compute-release-information.adoc#id79d9af81-3080-471d-9cd1-afe25c775be3[Prisma Cloud Compute Release Information] for the latest features of the host, container, and serverless capabilities that are available on the *Compute* tab on Prisma Cloud.

The details and functionality listed below are a preview of what is planned in the next Compute update planned for June 16, 2023; the changes listed herein and the actual release date is subject to change.

=== Deprecation Notices

Review the list of all deprecation notices in Prisma Cloud Compute.

* *Upcoming deprecation of macros used for runtime events webhooks*
Following our deprecation policy, the `aggregated` and `rest` macros will be deprecated.

=== Coming Fixes

* Fixed an issue with the Defenders and agentless scans detecting an incorrect Kubernetes version.
The Kubernetes version in the scan results on Prisma Console now matches the Kubernetes version that is installed on the host.

//=== Breaking Changes

//Be aware of the following breaking changes with the upgrade to 30.02.XXX:

//=== Changes in Existing Behavior

//* On pre-existing compliance rules, newly-added compliance checks are set to ignore, regardless of severity.
//* Vulnerability discovery dates are no longer updated upon upgrade.
//+
//When your Compute console is upgraded from 21.08 to 22.01, the vulnerability discovery dates will be updated.
//However, on subsequent upgrades from 22.01, vulnerability discovery dates will be preserved.

=== Enhancements

[cols="50%a,50%a"]
|===
//CWP-XXXXX
|Feature
|Description

2+|*Operating Systems Support*

//CWP-48511
|*Windows Server 2016*
|Reinstating the support for Defenders on Windows 2016. For details on the extended support from Microsoft, see https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2016

//RLP-104114
|*Added new NAT gateway IP addresses*
|Prisma Cloud is adding new NAT IP addresses for the Compute SaaS Console Region in GCP. The egress IPs for connections from The Compute SaaS Console to the internet in us-east 1 (South Carolina) are:
`34.139.64.150`
`34.139.249.192`

Make sure to add these IP addresses to your allow list.
These IP addresses will be added to the https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/get-started-with-prisma-cloud/enable-access-prisma-cloud-console#id7cb1c15c-a2fa-4072-b074-063158eeec08_idcb6d3cd4-d1bf-450a-b0ec-41c23a4d4280[documentation].

//CWP-44813
|*Added Support for Service Principals in Azure*
|

2+|*Agentless Security*

//CWP-46871
|*Encrypted volumes support in GCP with hub mode*
|This feature adds the capability to scan encrypted volumes in GCP with agentless scanning when using hub mode.

2+|*Host Security*

//CWP-47766
|*Containerd and CRI - ADD support for some docker compliance checks*
|

//CWP-34539
|*Support custom compliance checks*
|

|*Change in the format of runtime events information used in notification webhooks*
|Replaced the `aggregated` and `rest`` macros with the following macros:

* `aggregatedAlerts`: Returns the aggregated audit events in json format. It represents the same data as the old `aggregated` macro, but in JSON format instead of text.

* `dropped`: Returns the number of alerts that were dropped after the aggregation buffer has reached its limit.

This change fixes an issue where some of the aggregated alerts were missing fields like `ContainerID`, `Namespace`, and `User`.

The `aggregated` and `rest` macros are still available but are being deprecated after the two upcoming releases following our deprecation notice policy.
For existing settings of alert providers, you must edit the alert structure and use the new macros.

2+|*API Changes*

//CWP-48536
|*Add Backward Compatibility to api/v1/cloud/discovery/entities*
|The *api/vVERSION/cloud/discovery/entities* API endpoint is now available as a supported and backward compatible route to view the cloud discovered entities.

//CWP-45206
|*Monitor the status of an OnDemand and Regular registry scan*
|The new API endpoint *api/vVERSION/registry/progress* is available to view the progress of onDemand and regular ongoing registry scans. Set the request parameter *onDemand* to true to view progress of an ongoing on-demand scan. By default, *onDemand* is set to false and shows the progress of a regular scan.

2+|*Breaking API Changes*

//CWP-48451
|*Defender APIs modified to support the containerd runtime*
|The following APIs have been enhanced to include support for the containerd runtime in addition to the existing Docker and CRI-O runtimes: 

* POST, `/api/vVERSION/defenders/daemonset.yaml`

* POST, `/api/vVERSION/defenders/helm/twistlock-defender-helm.tar.gz`

The `cri` boolean parameter (in the `common.DaemonSetOptions` schema) in the above endpoints has been replaced by the `common.ContainerRuntime` schema in the 30.02 release, as shown below:

Older schema (30.01 and earlier releases) 

[source,json]
----
"cri": {
"description": "Indicates that Defender uses CRI instead of docker.\n",
"type": "boolean"
}
----

New schema (in release 30.02)
[source,json]
----
"containerRuntime": 
{
    "$ref": "#/components/schemas/common.ContainerRuntime"
},

"common.ContainerRuntime": 
{
    "description": "Represents the supported container runtime types",
    "enum": [
                [
                    "docker",
                    "containerd",
                    "crio"
                ]
            ],

    "type": "string"
}
----

This change is applicable from the 30.02 release and is backward compatible. 

IMPORTANT: You must update existing scripts that use either of the two endpoints when you upgrade to 30.02 or a future release.

//2+|*Serverless Security*

//CWP-45046
//|*Serverless scan for GCP fails when TLS proxy is enabled*
//|

|===
