[#idbcabf073-287c-4563-9c1f-382e65422ff9]
== Look Ahead — Planned Updates on Prisma Cloud Compute

// Review any deprecation notices and new features planned in the next Prisma Cloud Compute release.

See xref:prisma-cloud-compute-release-information.adoc#id79d9af81-3080-471d-9cd1-afe25c775be3[Prisma Cloud Compute Release Information] for the latest features of the host, container, and serverless capabilities that are available on the *Compute* tab on Prisma Cloud.

The details and functionality listed below are a preview of what is planned in the next Compute update planned for July xx, 2023; the changes listed herein and the actual release date, are subject to change.

=== Deprecation Notices

=== Changes in Existing Behavior

=== Breaking Changes

//CWP-49402 - Document GCP org policy exclusion mechanism
* TBD

=== Enhancements

[cols="50%a,50%a"]
|===
|Feature
|Description

//CWP-44490
|Registry scan scale - support over 100k images
|TBD

//CWP-43053
|Enhance the Syslog to include the same fields as the API
|TBD
