[#id311f617e-5159-4b1b-8cfa-29183c6e4a74]
== Prisma Cloud Compute Known Issues

Review the list of known and addressed issues and deprecation notice for the Compute capabilities on Prisma Cloud Enterprise Edition.

The following table lists the known and addressed issues on Compute capabilities on Prisma Cloud Enterprise Edition.

[NOTE]
====
The list of addressed issues are not cumulative; only the issues that are fixed with the last published release are included here.
====

[cols="47%a,53%a"]
|===
|Issue ID
|Description

//CWP-XXXXX
|tt:[Fixed in 30.02.XXX]
|

|===

See xref:#id91fda67c-c690-4e25-9760-f37ddbe5ee90[Breaking Changes and Deprecation Notices] 


[#id91fda67c-c690-4e25-9760-f37ddbe5ee90]
=== Deprecation Notices

Review the list of all deprecation notices in Prisma Cloud Compute.


[#idadd68235-e3f7-4084-96b2-c164d7568154]
=== Breaking Changes

Be aware of the following breaking changes with the upgrade to 30.02.XXX:

[#idae19e2ea-0196-458f-a5d2-a8d32761a45e]
=== Changes in Existing Behavior

* On pre-existing compliance rules, newly-added compliance checks are set to ignore, regardless of severity.
* Vulnerability discovery dates are no longer updated upon upgrade.
+
When your Compute console is upgraded from 21.08 to 22.01, the vulnerability discovery dates will be updated. However, on subsequent upgrades from 22.01, vulnerability discovery dates will be preserved.
