== App Configuration Using Local Authentication
// Ensure 'local_auth_enabled' is set to 'False' in Azure App Configuration

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ad67bb80-8e39-495e-9d31-06be93efdb12

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/AppConfigLocalAuth.py[CKV_AZURE_184]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

=== Description

Authentication plays a pivotal role in securing Azure App Configuration resources. Azure provides two primary authentication schemes: Azure Active Directory (Azure AD) credentials and access keys. Azure AD credentials offer enhanced security features and are easier to manage, making them the recommended choice by Microsoft over access keys.

This policy ensures that `local_auth_enabled` attribute in Azure App Configuration resources is set to `False`. Setting this attribute to `True` would enable local authentication with access keys, potentially making the resource more susceptible to unauthorized access.

=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_app_configuration

*Arguments:* 
- local_auth_enabled

[source,terraform]
----
resource "azurerm_app_configuration" "example" {
  name                = "example-app-configuration"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
  # ... other configurations ...

+ local_auth_enabled = false  // Ensure local authentication is disabled
}
----
