== Web PubSub Without Managed Identities
// Ensure Web PubSub uses managed identities to access Azure resources

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0327b3ff-cca3-40dc-89ac-77fd32c4ec3b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/PubsubSpecifyIdentity.py[CKV_AZURE_176]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Managed Identities provides an identity for applications, allowing them to access other Azure resources. It is a secure alternative to using secrets or keys. With Managed Identities, credentials are outside of your code, reducing the risk of them being compromised.

Azure Web PubSub is a real-time web messaging service. For enhanced security, it's recommended to use Azure Managed Identities when Web PubSub accesses other Azure services.

This policy checks to ensure that Azure Web PubSub is configured to use Managed Identities.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_web_pubsub
* *Arguments:* identity

[source,terraform]
----
resource "azurerm_web_pubsub" "example" {
  name                = "example-webpubsub"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
+ identity {
+   type = "SystemAssigned"  # or "UserAssigned" based on the requirement
+ }

  tags = {
    Environment = "production"
  }
}
----

Note: The provided example sets the identity to "SystemAssigned". Depending on organizational requirements, "UserAssigned" can be chosen. Ensure that the chosen identity type aligns with security and operational needs.
