== Dockerfile certificate validation is disabled with the pip '--trusted-host' option


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 1837455a-4c58-4f3c-bf4b-8dddf10e94f6

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunPipTrustedHost.yaml[CKV2_DOCKER_4]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Description 


This policy checks that your Dockerfile does not usepip or pip3 with the `--trusted-host option`.

The `--trusted-host` option in pip is used to mark a particular host as trusted, even if it doesn't have valid or any SSL.

By marking a host as trusted with `--trusted-host`, you're telling pip not to enforce SSL verification for that particular domain. As with the examples for curl and wget, this leaves you vulnerable to man-in-the-middle (MitM) attacks where attackers can intercept or alter the traffic between pip and the trusted host.


=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- RUN pip install somepackage --trusted-host pypi.example.com
+ RUN pip install somepackage
----

