== Dockerfile APT package manager is configured to allow unauthenticated packages

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| f539f6d1-6bdd-4da3-afd6-5bc5213db8b3

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunAptGetAllowUnauthenticated.yaml[CKV2_DOCKER_8]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Utilizing the `--allow-unauthenticated` or `--force-yes` option with the APT package manager (`apt-get`) in Dockerfiles poses a security concern. These flags allow the installation of packages without verifying their authenticity, effectively bypassing the signature verification process.

Without proper signature verification, there's a heightened risk of installing tampered or malicious packages. This can introduce vulnerabilities or malicious software into your Docker images, potentially compromising the container's security and the integrity of applications running within.

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- RUN apt-get update && apt-get install -y --allow-unauthenticated somepackage
+ RUN apt-get update && apt-get install -y somepackage
----
