== Dockerfile sets YUM configuration to disable SSL verification

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2dbf44db-cf61-4b1f-8728-df525f1e39a4

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunYumConfigManagerSslVerify.yaml[CKV2_DOCKER_15]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Using the command `yum-config-manager --save --setopt=sslverify=false` in Dockerfiles is insecure. This command configures YUM (Yellowdog Updater Modified) to bypass SSL certificate verification when interacting with repositories.

Disabling SSL verification for YUM can put the container and its underlying applications at risk of man-in-the-middle (MitM) attacks. In such scenarios, unauthorized individuals can intercept, modify, or listen in on the traffic between the YUM package manager and the repository servers. This can lead to the installation of malicious or compromised packages, introducing vulnerabilities into the Docker image.

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- RUN yum-config-manager --save --setopt=sslverify=false
+ RUN yum-config-manager --save --setopt=sslverify=true
----
