== Dockerfile configuration disables strict SSL for NPM

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0af43489-24b7-4498-a413-0a2ab7c82553

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/EnvNpmConfigStrictSsl.yaml[CKV2_DOCKER_12]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Setting the `npm_config_strict_ssl` environment variable to `false` within Dockerfiles is insecure. By doing so, you are instructing NPM (Node Package Manager) to bypass SSL certificate verification when interacting with registries or other network-based operations.

Disabling strict SSL for NPM can leave the container and its underlying applications susceptible to man-in-the-middle (MitM) attacks. In these attacks, malicious actors can intercept, modify, or eavesdrop on the traffic between the Node.js application and the NPM registry or other servers, leading to potential code injections or data leaks.

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- ENV npm_config_strict_ssl=false
+ ENV npm_config_strict_ssl=true
----
