== Dockerfile RPM package manager is configured to skip package signature checks

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ef703177-17a5-4316-b195-5a97fbd8bee9

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunRpmNoSignature.yaml[CKV2_DOCKER_10]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Employing the `--nosignature` option with the RPM Package Manager (`rpm`) in Dockerfiles presents a substantial security risk. This flag directs RPM to bypass package signature verification during installations.

Neglecting the package signature check opens the door for the potential installation of tampered or malicious packages. This can result in malicious software or vulnerable versions being incorporated into the container image, which could critically jeopardize the container's security and the overall integrity of the applications it houses.

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- RUN rpm -i --nosignature somepackage.rpm
+ RUN rpm -i somepackage.rpm
----
