== Default service accounts are actively used

=== Policy Details 

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID 
| 51515bb4-26e1-4860-8f9e-a31e76f25740

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/kubernetes/DefaultServiceAccount.py[CKV_K8S_41]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|===


=== Description 


Every Kubernetes installation has a service account called _default_ that is associated with every running pod.
Similarly, to enable pods to make calls to the internal API Server endpoint, there is a *ClusterIP* service called _Kubernetes_.
This combination makes it possible for internal processes to call the API endpoint.
We recommend that users create their own user-managed service accounts and grant the appropriate roles to each service account.

=== Fix - Buildtime


*Kubernetes* 




*Option 1* 


* *Resource:* ServiceAccount
* *Arguments:* If service name is set to default, *automountServiceAccountToken* should be set to false in order to opt out of automounting API credentials for a service account.


[source,default service]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
+ automountServiceAccountToken: false
----


[source, non-default service]
----
apiVersion: v1
kind: ServiceAccount
metadata:
+ name: <service name>
----


*Option 2* 


* *Resource:* RoleBinding / ClusterRoleBinding
* *Arguments:* *RoleBinding* grants the permissions defined in a role to a user or set of users within a specific namespace.

*ClusterRoleBinding* grants that access cluster-wide.
To avoid activating  the default service account, it should not be used as a subject in *RoleBinding* or *ClusterRoleBinding* resources.


[source,RoleBinding]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <name>
subjects:
-- kind: ServiceAccount
-  name: default
----

[source,ClusterRoleBinding]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <name>
subjects:
-- kind: ServiceAccount
-  name: default
----
