== CPU limits are not set
// CPU limits not set

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e6f3690e-f808-4aea-811a-2a581128355b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/CPULimits.py[CKV_K8S_11]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes,Terraform,Helm,Kustomize

|=== 



=== Description 


Kubernetes allows administrators to set CPU quotas in namespaces, as hard limits for resource usage.
Containers cannot use more CPU than the configured limit.
Provided the system has CPU time free, a container is guaranteed to be allocated as much CPU as it requests.
CPU quotas are used to ensure adequate utilization of shared resources.
A system without managed quotas could eventually collapse due to  inadequate resources for the tasks it bares.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Container
* *Arguments:* resources:limits:cpu (Optional)

Defines the CPU limit for the container.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
  containers:
  - name: <container name>
    image: <image>
    resources:
      limits:
+       cpu: <cpu limit>
----
