== Default namespace is used
// Default namespace used


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6e7d5188-5797-407a-a993-d98b58c59203

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/DefaultNamespace.py[CKV_K8S_21]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


In Kubernetes, the cluster comes out of the box with a namespace called "`default.`" Other namespaces Kubernetes includes are: default, kube-system and kube-public.
Some Kubernetes tooling is set up out of the box to use this namespace and you can't delete it.
We recommend that you do not use the default namespace in large production systems.
Using this space can result in accidental disruption with other services.
Instead, we recommend you create alternate namespaces and use them to run additional required services.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Pod / Deployment / DaemonSet / StatefulSet / ReplicaSet / ReplicationController / Job / CronJob
* *Arguments:* namespace (Optional)  

Defines the used namespace.
Default to default.


[source,yaml]
----
apiVersion: <apiVersion>
kind: <kind>
metadata:
  name: <name>
+ namespace: <your namespace>
- namespace: default
----

