== The API server does not make use of strong cryptographic ciphers


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4a0e3798-0949-43e5-8340-650cbc468179

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/ApiServerStrongCryptographicCiphers.py[CKV_K8S_105]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Kubernetes,Helm,Kustomize

|=== 

////
Bridgecrew
Prisma Cloud
* The API server does not make use of strong cryptographic ciphers* 



=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4a0e3798-0949-43e5-8340-650cbc468179

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/ApiServerStrongCryptographicCiphers.py [CKV_K8S_105]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Kubernetes,Helm,Kustomize

|=== 
////


=== Description 


Ensure that the API server is configured to only use strong cryptographic ciphers.
TLS ciphers have had a number of known vulnerabilities and weaknesses, which can reduce the protection provided by them.
By default Kubernetes supports a number of TLS ciphersuites including some that have security concerns, weakening the protection provided.

=== Fix - Buildtime


*Kubernetes* 


* *Kind:* Pod


[source,yaml]
----
{
 "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
+   - kube-apiserver
+   - --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver-should-pass
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: k8s
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: certs
    - mountPath: /etc/pki
      name: pki
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: k8s
  - hostPath:
      path: /etc/ssl/certs
    name: certs
  - hostPath:
      path: /etc/pki
    name: pki",
}
----

