== The --streaming-connection-idle-timeout argument is set to 0
// '-streaming-connection-idle-timeout' argument set to 0

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 87d48757-cb0e-4662-b1a4-063eb0ecc807

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/KubeletStreamingConnectionIdleTimeout.py[CKV_K8S_143]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes,Helm,Kustomize

|=== 



=== Description 


Do not disable timeouts on streaming connections.
Setting idle timeouts ensures that you are protected against Denial-of-Service attacks, inactive connections and running out of ephemeral ports.
By default, --streaming-connection-idle-timeout is set to 4 hours which might be too high for your environment.
Setting this as appropriate would addition ally ensure that such streaming connections are timed out after serving legitimate use cases.

=== Fix - Buildtime


*Kubernetes* 


* *Kind:* Pod


[source,yaml]
----
{
 "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kubelet
    tier: control-plane
  name: kubelet
  namespace: kube-system
spec:
  containers:
  - command:
+   - kubelet
+   - --streaming-connection-idle-timeout=1
    image: gcr.io/google_containers/kubelet-amd64:v1.6.0
    ...",
}
----

