== The --root-ca-file argument for controller managers is not set appropriately
// 'The '--root-ca-file' argument for controller managers not set appropriately


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| aa9d1111-eb5b-4549-8ea7-3d57d9d59f93

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/KubeControllerManagerRootCAFile.py[CKV_K8S_111]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Kubernetes,Helm,Kustomize

|=== 



=== Description 


Allow pods to verify the API server's serving certificate before establishing connections.
Processes running within pods that need to contact the API server must verify the API server's serving certificate.
Failing to do so could be a subject to man-in-the-middle attacks.
Providing the root certificate for the API server's serving certificate to the controller manager with the --root-ca-file argument allows the controller manager to inject the trusted bundle into pods so that they can verify TLS connections to the API server.

=== Fix - Buildtime


*Kubernetes* 


* *Kind:* Pod


[source,yaml]
----
{
 "  apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    labels:
      component: kube-controller-manager
      tier: control-plane
    name: kube-controller-manager
    namespace: kube-system
  spec:
    containers:
    - command:
      - kube-controller-manager
+     -  --root-ca-file=private.pem
      image: gcr.io/google_containers/kube-controller-manager-amd64:v1.6.0",
}
----
