[#idb92a9405-31ce-42f3-9ed0-19ef216544fb]
== Onboard Your AWS Account

Monitor your AWS Organization or account on Prisma™ Cloud to automatically remediate issues and gain visibility in to your adherence to compliance standards.

To connect your AWS Organizations (only supported on public AWS) or AWS accounts on the public AWS, AWS China, AWS GovCloud account to Prisma™ Cloud, you must complete some tasks on the AWS management console and some on Prisma Cloud. The onboarding workflow enables you to create a Prisma Cloud role with either read-only access to your traffic flow logs or with limited read-write access to remediate incidents. With the correct permissions, Prisma Cloud can successfully connect to and access your AWS accounts.

[NOTE]
====
In addition to scanning your AWS resources against Prisma Cloud policies for compliance and governance issues, you can also scan objects in AWS S3 buckets for data security issues. The data security capabilities include predefined data policies and associated data classification profiles such as PII, Financial, or Healthcare & Intellectual Property that scan your objects stored in the S3 bucket to identify exposure—how sensitive information is kept private, or exposed or shared externally, or allows unauthorized access.
====

* xref:add-aws-cloud-account-to-prisma-cloud.adoc#id8cd84221-0914-4a29-a7db-cc4d64312e56[Add AWS Cloud Account to Prisma Cloud]

* xref:add-aws-organization-to-prisma-cloud.adoc#idafad1015-aa36-473e-8d6a-a526c16d2c4f[Add AWS Organization to Prisma Cloud]

* xref:add-aws-member-accounts-to-prisma-cloud.adoc#id333e8bbf-ae4d-443b-8365-95971069045a[Add AWS Member Accounts to Prisma Cloud]

* xref:update-an-onboarded-aws-account.adoc#idece1e97f-31e4-4862-bc93-da79383b0392[Update an Onboarded AWS Account]

* xref:enable-dns-logs-ingestion.adoc[Configure DNS Logs Ingestion]

* xref:enable-flow-logs-for-amazon-s3.adoc#ide9d218ce-4d1a-4567-8f46-4aa7582062bf[Configure Flow Logs]

* xref:ingest-audit-logs-using-eventbridge.adoc[Ingest Audit Logs Using Amazon EventBridge]

* xref:configure-vulnerability-findings.adoc[Configure Vulnerability Findings]

* xref:automate-aws-onboarding.adoc[Automate AWS Cloud Accounts Onboarding]

* xref:set-up-your-prisma-cloud-role-for-aws-manual.adoc#ide7b46e67-8e1f-400f-b763-48bbe41bbe2c[Set Up the Prisma Cloud Role for AWS Manually]

* xref:prisma-cloud-on-aws-china.adoc#idac03878f-174f-4fd8-b4c7-aa943b589588[Prisma Cloud on AWS China]

* xref:aws-apis-ingested-by-prisma-cloud.adoc#ideb858cbe-4c77-4d20-9149-ba331212fe36[AWS APIs Ingested by Prisma Cloud]