[#idac03878f-174f-4fd8-b4c7-aa943b589588]
== Prisma Cloud on AWS China
//Review what is supported on Prisma Cloud on AWS China

To use Prisma Cloud to monitor and protect your deployments in the China regions of Ningxia and Beijing, you require a Prisma Cloud instance in China.

The Prisma Cloud instance in China  (app.cn) supports your AWS China, Azure China & Alibaba China deployments. 
For getting started with the configuration. For getting started with the configuration, see  xref:add-aws-cloud-account-to-prisma-cloud.adoc#id8cd84221-0914-4a29-a7db-cc4d64312e56[Add an AWS Cloud Account on Prisma Cloud], xref:../onboard-your-alibaba-account/add-alibaba-cloud-account-to-prisma-cloud.adoc[Add an Alibaba account], or xref:../onboard-your-azure-account/add-azure-china-tenant-on-prisma-cloud.adoc[Add an Azure China account]. 

Review the following sections to know what is not currently supported and available for the AWS China deployments:

* Prisma Cloud Compute, which enables you to secure containers and serverless functions is not available on the Prisma Cloud instance in China.

* Prisma Cloud Data Security, which enables you to discover and classify data stored in AWS S3 buckets and protect accidental exposure, misuse, or sharing of sensitive data is not available on the Prisma Cloud instance in China.

* Prisma Cloud does not support the following services:
+
** Amazon GuardDuty

** Amazon Translate

** Amazon QLDB

** AWS DataSync

** AWS Inspector

** AWS Organization

* AWS does not support the https://www.amazonaws.cn/en/about-aws/regional-product-services/[these services].
