[#idac03878f-174f-4fd8-b4c7-aa943b589588]
== Prisma Cloud on AWS China
Review what is supported on Prisma Cloud on AWS China

To use Prisma Cloud to monitor or monitor and protect your deployments in the AWS China regions of Ningxia and Beijing, you require a Prisma Cloud instance in China. See xref:add-aws-cloud-account-to-prisma-cloud.adoc#id8cd84221-0914-4a29-a7db-cc4d64312e56[Add an AWS Cloud Account on Prisma Cloud] for getting started with the configuration logs for your resources.

Review the following sections to know what is not currently supported and available for the AWS China deployments:

* Prisma Cloud Compute, which enables you to secure containers and serverless functions is not available on the Prisma Cloud instance in China.

* Prisma Cloud Data Security, which enables you to discover and classify data stored in AWS S3 buckets and protect accidental exposure, misuse, or sharing of sensitive data is not available on the Prisma Cloud instance in China.

* Prisma Cloud does not support the following services:
+
** Amazon GuardDuty

** Amazon Translate

** Amazon QLDB

** AWS DataSync

** AWS Inspector

** AWS Organization
+

+++<draft-comment>The following 2 services are supported on the Prisma Cloud stack in China, so we’ve removed them from the above list: AWS CloudTrail and AWS VPC Flow Logs. Also removed AWS Glue, AWS WAF, and Amazon Route53 on May 10, 2022 based on email from Felix</draft-comment>+++

* AWS does not support the following services:
+
** Amazon AppStream

** Amazon CloudSearch

** Amazon Data Pipeline

** Amazon Simple Email Service

** AWS WAFv2

** Resource and alert attribution




