== Gitlab project commits are not signed
// Gitlab project commits not signed


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| d2106a3f-81c8-4ee9-919b-b519dcedc59d

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gitlab/RejectUnsignedCommits.py[CKV_GLB_4]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 


In GitLab, administrators can turn on the capability to require signed commits for a project.
When you enable required commit signing on a branch, contributors and bots can only push commits that have been signed and verified to the branch.
If a collaborator pushes an unsigned commit to a branch that requires commit signatures, the collaborator will need to rebase the commit to include a verified signature, then force push the rewritten commit to the branch.

=== Fix - Buildtime


*Terraform* 


* Resource: gitlab_project
* Attribute: prevent_secrets


[source,go]
----
resource "gitlab_project" "example-two" {
...
  push_rules {
    ...
+    reject_unsigned_commits        = true
  }
}
----

