== AWS DocumentDB logging is not enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0c7e0ca3-8c29-43a8-831b-b561ffb5d996

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/DocDBLogging.py[CKV_AWS_85]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


The events recorded by the AWS DocumentDB audit logs include: successful and failed authentication attempts, creating indexes or dropping a collection in a database within the DocumentDB cluster.
AWS CloudWatch logs are a service that monitors, stores and accesses your log files from a variety of sources within your AWS account.
When logging is enabled information such as Data Definition Language, authentication, authorization, and user management events are sent to AWS CloudWatch logs.
This information can be used to analyze, monitor and archive your Amazon DocumentDB auditing events for security and compliance requirements.

////
=== Fix - Runtime


* AWS Console* 



. Log in to the AWS Management Console at [https://console.aws.amazon.com/].

. Open the https://console.aws.amazon.com/docdb [Amazon DocumentDB].

. In the navigation pane, choose * Clusters*.

. Specify the cluster that you want to modify by choosing the button to the left of the cluster's name.

. Choose * Actions*, then click * Modify*.

. In the Modify Cluster: & lt;cluster-name>+++ pane.
+++& lt;/cluster-name>

. Go to*  Log Exports** and enable exporting audit or profiler logs.


* CLI Command* 


Use the modify-db-cluster operation to modify the specified cluster using the AWS CLI.


[source,shell]
----
{
 "aws docdb modify-db-cluster \\
   --db-cluster-identifier sample-cluster \\
   --cloudwatch-logs-export-configuration '{"EnableLogTypes":["audit"]}'",
}
----
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_docdb_cluster
* *Arguments:* enabled_cloudwatch_logs_exports - (Optional) List of log types to export to cloudwatch.
If omitted, no logs will be exported.
The following log types are supported: audit, profiler.


[source,go]
----
{
 "resource "aws_docdb_cluster" "docdb" {
  cluster_identifier      = "my-docdb-cluster"
  ...
+ enabled_cloudwatch_logs_exports  = ["audit", "profiler"]
}

",
 
}
----
