== GitLab CI/CD accesses cloud provider using insecure long-term credentials  

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|96e27870-7fe7-47f9-b13d-298d2404c013 

|Severity
|Medium
// add severity level .

|Category
|Credential Hygiene
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description 

Long-term credentials intended to be used by GitLab CI/CD to authenticate to a cloud provider account are stored on GitLab as variables. This increases the impact of credential theft, since stolen credentials can be used long after a pipeline run is complete.

=== Recommended Solution - Buildtime

Since September 2022, GitLab supports the OIDC (OpenID Connect) authentication protocol to replace long-term credentials with short-lived access tokens.
Using OIDC, the GitLab CI/CD pipeline  can request a short-lived token directly from the cloud provider, which expires after a short time period.
In addition, OIDC allows more granular control over how secrets can be used. For example, it is possible to filter access to tokens when the request originates in specific protected branches or projects.

For more information about using OIDC in GitLab refer to https://docs.gitlab.com/ee/ci/cloud_services/.










