== GitLab deploy keys assigned with write permissions

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|abc95060-72ee-4a73-b191-a12a79abe185 

|Severity
|Low
// add severity level

|Category
|Pipeline Based Access Controls (PBAC)
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description

Deploy keys created on GitLab projects are assigned with **write** permissions. An attacker who obtains access to a deploy key with write permissions has excessive abilities on the project, such as editing the code of its repository.  

=== Recommended Solution - Buildtime

To minimize the risk of a stolen deploy key to be used by an attacker, it is recommended to reduce the level of permissions of all deploy keys to **read-only** when write permissions are not necessary for the proper flow of the pipeline.
To achieve this, edit each deploy key and remove its write permissions.

To create and delete deploy keys using the console, refer to the instructions on the GitLab documentation:
https://docs.gitlab.com/ee/user/project/deploy_keys/#project-deploy-keys.

To create and delete deploy keys using the API, refer to the GitLab API documentation:
https://docs.gitlab.com/ee/api/deploy_keys.html#update-deploy-key.

