== Forking of GitLab private repository is allowed

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|224fba7d-cd53-4858-9743-3591716297be

|Severity
|Medium
// add severity level

|Category
|Data Protection 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description 

Misconfiguration of private repositories may allow sensitive code to be inadvertently/intentionally leaked.
A user account can fork the repository to another workspace, leading to leakage of code.
It can also lead to the creation of pull requests from the forked repository to the original repository. This can lead to the execution of malicious code on the CI, even by users with **read-only** permissions on the original repository.

=== Recommended Solution - Buildtime

When not required, disable the forking of private repositories.

To restrict forking of a private repository:
 
. Browse to project **Settings**.
. Under **Visibility**, select **Project Features**.
. Disable the **Fork** setting under the **Permissions** section.












