== Secrets found in NPM dependency download URL in GitLab repository 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|30193801-9ad9-4b19-baff-6cec2b8755cd 

|Severity
|High
// add severity level

|Category
|Dependency Chains
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description 

Including secrets in a NPM dependency download URL, which is found in the package-lock.json file, can allow an attacker who has gained access to the repository to gain unauthorized access to the package or to resources that are protected by the secret.

The attacker could potentially use these secrets to impersonate the owner of the secret and to perform actions on their behalf, such as pushing malicious code which could reach the production environment. 

=== Recommended Solution - Buildtime

Remove the URLs that contain secrets from the `package-lock.json` file.

Also, check the `.npmrc` file, and if it contains configurations to download a package using plain-text credentials, remove the configuration.

Use an alternative method for authentication to provide access to a private registry:
 
. Execute `npm uninstall <package>` to remove the existing package.
. Create an `.npmrc`` file that contains authentication configurations using the following https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow[guide].
. Execute `npm install`` using the package name instead of a URL to reinstall the package.















