== MWAA environment is publicly accessible

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 369e3a34-26a8-4ac2-92ba-2b779349c877

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/AWS_private_MWAA_environment.yaml[CKV2_AWS_66]

|Severity
| HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 

=== Description 

Managed Workflows for Apache Airflow (MWAA) is a managed orchestration service that makes it easier to execute Apache Airflow workflows in the cloud. Ensuring the environment is not publicly accessible helps in preventing unauthorized access. Public accessibility may expose sensitive information or make the environment susceptible to threats.

We recommend setting the MWAA environment's `webserver_access_mode` attribute to `PRIVATE_ONLY` to ensure that the environment remains inaccessible to the public. If the `webserver_access_mode` attribute does not exist or is set to any other value, it indicates that the environment may be publicly accessible.

=== Fix - Buildtime

*Terraform* 

* *Resource:* aws_mwaa_environment
* *Arguments:* webserver_access_mode

[source,go]
----
resource "aws_mwaa_environment" "example" {
  //... [Other resource configurations]

  + webserver_access_mode = "PRIVATE_ONLY"
}
----
