== AWS CloudFront web distribution using insecure TLS version


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 45e37556-3d26-4cdb-8780-5b7fc5f60e01

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/CloudFrontTLS12.py[CKV_AWS_174]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


This policy identifies AWS CloudFront web distributions which are configured with TLS versions for HTTPS communication between viewers and CloudFront.
As a best practice, use TLSv1.1_2016 or later as the minimum protocol version in your CloudFront distribution security policies

////
=== Fix - Runtime


* AWS Console* 



. Sign in to the AWS console

. Navigate to CloudFront Distributions Dashboard

. Click on the reported distribution

. On 'General' tab, Click on 'Edit' button

. On 'Edit Distribution' page, Set 'Security Policy' to TLSv1.1_2016 or later as per your requirement.

. Click on 'Yes, Edit'
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_cloudfront_distribution
* *Arguments:* minimum_protocol_version


[source,go]
----
resource "aws_cloudfront_distribution" "pass" {
...

  viewer_certificate {
    cloudfront_default_certificate = false
    minimum_protocol_version = "TLSv1.2_2018"
  }
}
----
