== AWS Application Load Balancer (ALB) not configured with AWS Web Application Firewall v2 (AWS WAFv2)


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7759063b-44f6-41ab-92fa-950f85f4a357

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/ALBProtectedByWAF.yaml[CKV2_AWS_28]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


AWS WAF is a web application firewall service that helps protect your web applications from common web exploits that could affect your application's availability, integrity, or confidentiality.
By attaching AWS WAF to your public-facing ALBs, you can create rules that block or allow traffic based on the characteristics of the traffic, such as the IP address, the HTTP method, or the values of specific headers.
This can help to protect your application from common web exploits such as SQL injection attacks, cross-site scripting attacks, and other types of malicious traffic.

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "aws_lb" "lb_good_1" {
  internal= false
}


resource "aws_wafregional_web_acl_association" "foo" {
  resource_arn = aws_lb.lb_good_1.arn
  web_acl_id = aws_wafregional_web_acl.foo.id
}
----
