== `+aws+` command

The `+aws+` command provides a range of capabilities for interacting
with the AWS roles. It allows the definition of flexible policy files
that map specific users or processing units to specific AWS roles with
corresponding privileges.

Examples:

 apoctl aws create -f ./policy.yaml

=== `+create+` subcommand

The `+create+` subcommand creates a role in AWS given the required privileges,
associate the role with the OAuth definition of the current namespace and
configures the right Microsegmentation policies so that processing units or users
that are protected by Microsegmentation policies can retrieve an ephemeral token
that gives them access to the specific resources.

Examples:

 apoctl aws create -f ./policy.yaml

=== `+delete+` subcommand

The `+delete+` subcommand deletes the AWS role provided together with all
the associated policies and Microsegmentation token scope policies. It
is assumed that the objects have been created with the `+create+` subcommand.

Examples:

 apoctl aws delete --awsrole=myrole

=== `+list-accesses+` subcommand

The `+list-accesses+` subcommand will list all the API accesses of a
Microsegmentation-protected object, such as a processing unit or an
SSH session towards specific AWS resources.

Examples:

 apoctl aws list-accesses -id <pu ID>
