== AWS IAM policy documents do not allow * (asterisk) as a statement's action


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 663ffb0a-4219-41ba-b72c-53aa9c694f5b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/data/aws/StarActionPolicyDocument.py[CKV_AWS_49]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,Serverless,TerraformPlan

|=== 



=== Description 


The Action element describes the specific action or actions that will be allowed or denied.
Statements must include either an Action or NotAction element.
Each AWS service has its own set of actions that describe tasks that can be performed with that service.
Specify a value using a namespace that identifies a service, for example, iam, ec2 sqs, sns, s3, followed by the name of the action to be allowed or denied.
The name must match an action that is supported by the service.
We recommend you do not allow "*" (all resource) statements as part of action elements.
This level of access could potentially grant unwanted and unregulated access to anyone given this policy document setting.
We recommend you to write a refined policy describing the specific action allowed or required by the specific policy holder.

////
=== Fix - Runtime


* AWS Console* 



. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the https://console.aws.amazon.com/iam/ [Amazon IAM console].

. In the navigation pane, choose * Policies*.

. In the list of policies, choose the policy name of the policy to edit.
+
You can use the Filter menu and the search box to filter the list of policies.

. Choose the * Permissions * tab, then choose * Edit Policy*.

. Identify any Action statements permitting actions access to all resources ("*").

. On the Review page, review the policy Summary, then click * Save Changes*.
////

=== Fix - Buildtime


*Terraform* 


* *Arguments:* statement
* *Attribute*: action 

Example fix:


[source,go]
----
resource "aws_iam_policy" "example" {
   # ... other configuration ...
   policy = <<POLICY
 {
   "Version": "2012-10-17",
   "Statement": {
     "Effect": "Allow",
-    "Action": "*",
     "Resource": "*"
   }
----
