== AWS RDS database instance is publicly accessible


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 1bb6005a-dca6-40e2-b0a6-24da968c0808

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/RDSPubliclyAccessible.py[CKV_AWS_17]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Ensure that all your public AWS Application Load Balancer are integrated with the Web Application Firewall (AWS WAF) service to protect against application-layer attacks.
An Application Load Balancer functions at the application layer, the seventh layer of the Open Systems Interconnection (OSI) model.
After the load balancer receives a request, it evaluates the listener rules in priority order to determine which rule to apply, and then selects a target from the target group for the rule action.
You can configure listener rules to route requests to different target groups based on the content of the application traffic.
Routing is performed independently for each target group, even when a target is registered with multiple target groups.

=== Fix - Runtime


*AWS Console* 


To change the policy using the AWS Console, follow these steps:

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the https://console.aws.amazon.com/rds[Amazon RDS console].

. On the navigation pane, click *Snapshots*.

. Select the _snapshot_ to encrypt.

. Navigate to *Snapshot Actions*, select *Copy Snapshot*.

. Select your *Destination Region*, then enter your *New DB Snapshot Identifier*.

. Set *Enable Encryption* to *Yes*.

. Select your *Master Key* from the list, then select *Copy Snapshot*.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_db_instance
* *Arguments:* publicly_accessible


[source,go]
----
resource "aws_db_instance" "default" {
  ...
+ publicly_accessible   = false
}
----


*CloudFormation* 


* *Resource:* AWS::RDS::DBInstance
* *Arguments:* Properties.PubliclyAccessible


[source,yaml]
----
Type: 'AWS::RDS::DBInstance'
    Properties:
      ...
+     PubliclyAccessible: false
----
