== Alibaba Cloud Security group allow internet traffic to RDP port (3389)


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6c534f38-cc2c-4ebb-86a5-2e5d3114d376

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/SecurityGroupUnrestrictedIngress3389.py[CKV_ALI_3]

|Severity
|HIGH

|Subtype
|Build
//, Run

|Frameworks
|Terraform

|=== 



=== Description 


Allowing internet traffic to the RDP (Remote Desktop Protocol) port (3389) in Alibaba Cloud Security groups can pose several risks, such as unauthorized access and malware attacks. This policy restricts security groups to allow only authorized traffic to access your network.
////
=== Fix - Runtime


Alibaba Cloud Portal



. Log in to Alibaba Cloud Portal

. Go to Elastic Compute Service

. In the left-side navigation pane, choose Network & Security > Security Groups

. Select the reported security group and then click Add Rules in the Actions column

. In Inbound tab, Select the rule having 'Action' as Allow, 'Authorization Object' as 0.0.0.0/0 and 'Port Range' value as 3389, Click Modify in the Actions column

. Replace the value 0.0.0.0/0 with specific IP address range.

. Click on 'OK'
////

=== Fix - Buildtime


*Terraform* 

To configure Security group rules to restrict internet traffic to the RDP (Remote Desktop Protocol) port (3389) in your Alibaba Cloud Security groups, add the following code to your Terraform file during buildtime. 


[source,go]
----
resource "alicloud_security_group_rule" "allow_all_vncserver" {
  type              = "ingress"
  ip_protocol       = "tcp"
  nic_type          = "internet"
  policy            = "accept"
  port_range        = "5900/5900"
  security_group_id = alicloud_security_group.default.id
  cidr_ip           = "0.0.0.0/0"
}
Footer
© 2022 GitHub, Inc.
Footer navigation
----

