== Alibaba Cloud RDS instance does not use SSL


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 20f83821-cc13-405f-a437-5926c6ef9919

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RDSInstanceSSL.py[CKV_ALI_20]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 


If an Alibaba Cloud RDS instance is not using SSL (Secure Sockets Layer) to encrypt data transmissions, there are several potential risks such as data interception, data tampering and compliance violations. By implementing SSL, you can help protect your data by encrypting the data during transmission between the RDS instance instance and the client. This ensures that only authorized users with the correct keys can access and decrypt the data.

=== Fix - Buildtime


*Terraform* 

To configure an Alibaba Cloud RDS instance to use SSL, add the following code to your Terraform file during buildtime.




[source,go]
----
resource "alicloud_db_instance" "pass" {
  engine              = "MySQL"
  engine_version      = "5.6"
  ssl_action          = "Open"
  instance_storage    = "30"
  instance_type       = "mysql.n2.small.25"
  parameters = [{
    name  = "innodb_large_prefix"
    value = "ON"
    }, {
    name  = "connect_timeout"
    value = "50"
  }]
}
----

