== Microsegmentation Console

//'''
//
//title: Microsegmentation Console
//type: single
//url: "/5.0/start/install-console/"
//weight: 10
//menu:
//  5.0:
//    parent: "start"
//    identifier: "install-console"
//on-prem-only: true
//aliases: [
//  "/control-plane/",
//  "/control-plane/small-deployments/",
//  "/control-plane/large-deployments/",
//  "/control-plane/multi-region/"
//]
//
//'''

The Microsegmentation Console consists of microservices and databases.

Each microservice exposes a xref:../../microseg-console-api/microseg-console-api.adoc[REST API], gathered to a single endpoint by an API gateway.
This API endpoint can be consumed by any client like:

* the xref:../../concepts/console.adoc[web interface]
* the xref:../../concepts/enforcer.adoc[enforcers]
* xref:../../concepts/console.adoc[apoctl] command line

Databases are used to store different kinds of data:

* _MongoDB_: a document-oriented database used to store objects like policies, namespaces, and enforcers, as well as reports like flow logs, DNS logs, and events.
* _VictoriaMetrics_: a time-series database to store metrics like accepted and rejected flows for a given namespace.
* _Redis_: a key-value store used for caching.

The web interface is a client consuming the xref:../../microseg-console-api/microseg-console-api.adoc[REST API] exposed by the Microsegmentation Console.
It is loaded by and runs in your web browser.
