= Multi-region deployments

== Overview

Deploying the Aporeto control plane across multiple regions ensures that your core services stay up after your region goes down. If your region goes down, Aporeto fails over to a different region. The clusters all have access to the same MongoDB, ensuring no interruption in the core services.

However, each cluster has its own time-series database. You won’t be able to access the flow logs, events, or reports of the original cluster from the failover cluster. Likewise, after restoring operations in the original cluster, you’ll have a gap in your flow logs, events, and reports.

== Requirements

* Two Kubernetes clusters in different regions
* Pod-to-pod communication across clusters on the following ports:
* 27017/27018/27019 tcp
* 53/udp
* 53/tcp
* Voila installed on a VM or workstation

WARNING: If your Kubernetes clusters are on EKS, you must deactivate SNAT.

== Context

Cluster names are arbitrary. We will refer to them using the following names.

* First cluster Kubernetes context identified as *_test-active_*
* Second cluster Kubernetes context identified as *_test-passive_*
