= Multi-region deployments

== Overview

Deploying the Aporeto control plane across multiple regions ensures that your core services stay up after your region goes down. If your region goes down, Aporeto fails over to a different region. The clusters all have access to the same MongoDB, ensuring no interruption in the core services.

However, each cluster has its own time-series database. You won’t be able to access the flow logs, events, or reports of the original cluster from the failover cluster. Likewise, after restoring operations in the original cluster, you’ll have a gap in your flow logs, events, and reports.

In order to achieve multi region availability, you can deploy two or more control plane to separated regional Kubernetes cluster in a active/passive fashion (only one control plane will be able to server requests at any time).

Main idea is to have a DNS record, let say `https://api.aporeto.com` handled by a load balancer that updates the record to point to either `https://api.active.aporeto.com` or `https://api.passive.aporeto.com` plaform. Then a job `auto-maintenance` will make sure that only the platform that is pointed by the global record is active. The other will return a `423` return code which means maintenance mode.

=== Limitations

The other databases storing caches, reports metrics will not be replicated across the cluster. Thus, flow logs, events, or reports of the one cluster will not be accessible from the other cluster after failover.

WARNING: Please note that https://www.mongodb.com/atlas/database[MongoDB Atlas Database] is not supported as shard/user creation is only allowed through their REST API respectively.

== Requirements

* Two Kubernetes clusters in different regions
* Bring your own MongoDB database (BYODB) that will be used by all control planes
* Voila installed on a VM or workstation

== Configure your clusters

The very first step is to create two Kubernetes cluster retrieve their kubeconfig file and merge them if needed as:

```bash
KUBECONFIG=./foo.yaml:./bar.yaml kubectl config view --merge --flatten > clusters.yaml
```

Export that file as `KUBECONFIG` with `export KUBECONFIG=/path/to/clusters.yaml` and follow the install https://docs.paloaltonetworks.com/prisma/prisma-cloud/5-0/prisma-cloud-admin-microsegmentation/start/install-console/deploy[documentation] but do not proceed with the installation yet.

A voila environment can support several `zone` aka target cluster for the multi region deployment model described in this document. This goes with a tool called `mz` for multi zone.

In the following example we will add a zone called passive.

NOTE: When adding a new zone and if no zone existed before the current voila environment will automaticaly create a zone called `default`.

=== Configure zones

Use the `mz` commmand to configure zones in the control plane

```bash
mz -a <name> <context> <namespace>
```
where
- `<name>` is the zone name
- `<context>` is the Kubernetes context to use
- `<namespace>` is the namespace to create/use

**example:**
```bash
mz -a passive bar aporeto-svcs
```
`mz list-zones` output would look like:
```bash
[DEFAULT] zone (active):

* Kubernetes context: foo
* Kubernetes namespace: aporeto-svcs
* Voila configuration folder: /voila-env/./conf.d/DEFAULT

[PASSIVE] zone:

* Kubernetes context: bar
* Kubernetes namespace: aporeto-svcs
* Voila configuration folder: /voila-env/./conf.d/PASSIVE
```
If you need to adjust the zones informations context or namespace, you can edit the `aporeto.yaml` file and change the he following section.
```bash
> vi aporeto.yaml
...
zones:
- name: default
  k8s_context: foo
  k8s_namespace: aporeto-svcs
- name: passive
  k8s_context: bar
  k8s_namespace: aporeto-svcs
```
