== Onebox

Onebox provides a quick, simple way to install both Console and Defender onto a single host.
It provides a fully functional, self-contained environment that is suitable for evaluating Prisma Cloud.


[.task]
=== Install Prisma Cloud

Install Onebox with the _twistlock.sh_ install script.

*Prerequisites:*

* Your host meets the minimum xref:../system_requirements.adoc[system requirements].
* You have a license key.
* Port 8083 is open.
Port 8083 (HTTPS) serves the Console UI.
You can configure alternative ports in _twistlock.cfg_ before installing.
* Port 8084 is open.
Console and Defender communicate with each other on this port.

[.procedure]
. xref:../../welcome/releases.adoc#download[Download] the latest Prisma Cloud release to the host where you'll install Onebox.

. Extract the tarball.
All files must be in the same directory when you run the install.
+
  $ mkdir twistlock
  $ tar -xzf prisma_cloud_compute_<VERSION>.tar.gz -C twistlock/

. Configure Prisma Cloud for your environment.
+
Open _twistlock.cfg_ and review the default settings.
The default settings are acceptable for most environments.
+
NOTE: If your Docker socket is in a custom location, update _twistlock.cfg_ before continuing.
By default, Prisma Cloud expects to find the Docker socket in _/var/run/docker.sock_.
If it's not located there on your host, open _twistlock.cfg_ in an editor, find the DOCKER_SOCKET variable, and update the path.

. Install Prisma Cloud.

  $ sudo ./twistlock.sh -s onebox
+
[horizontal]
`-s`:: Agree to EULA.
`-z`:: (Optional) Print additional debug messages.
Useful for troubleshooting install issues.
`onebox`:: Install both Console and Defender on the same host, which is the recommended configuration.
Specify `console` to install just Console.

. Verify that Prisma Cloud is installed and running:
+
  $ docker ps --format "table {{.ID}}\t{{.Status}}\t{{.Names}}"
  CONTAINER ID        STATUS              NAMES
  764ecb72207e        Up 5 minutes        twistlock_defender_<VERSION>
  be5e385fea32        Up 5 minutes        twistlock_console


[.task]
=== Configure Console

Create your first admin user and enter your license key.

[.procedure]
. Open Prisma Cloud Console.
In a browser window, navigate to 'https://<CONSOLE>:8083', where <CONSOLE> is the IP address or DNS name of the host where Console runs.

. Create your first admin user.
+
Consider using _admin_ as the username.
It's a convenient choice because _admin_ is the default user for many of Prisma Cloud's utilities, including twistcli.

. Enter your license key.


[.task]
=== Uninstall

Use the _twistlock.sh_ script to uninstall Prisma Cloud from your host.
The script stops and removes all Prisma Cloud containers, removes all Prisma Cloud images, and deletes the _/var/lib/twistlock_ directory, which contains your logs, certificates, and database.

[.procedure]
. Uninstall Prisma Cloud.

  $ sudo ./twistlock.sh -u

. Verify that all Prisma Cloud containers have been stopped and removed from your host.

  $ docker ps -a

. Verify that all Prisma Cloud images have been removed from your host.

  $ docker images


=== What's next?

xref:../deploy-defender/container/container.adoc[Install Defender] on each additional host you want to protect.
