== Deletion protection disabled for load balancer


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9be5d82a-e667-49a5-bb21-c36ebec22f66

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/SSMSessionManagerDocumentLogging.py[CKV_AWS_113]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


This policy identifies Elastic Load Balancers v2 (ELBv2) which are configured with deletion protection feature disabled.
Enabling delete protection for these ELBs prevents irreversible data loss resulting from accidental or malicious operations.
For more details refer: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#deletion-protection

////
=== Fix - Runtime


AWS Console



. Log in to the AWS console

. In the console, select the specific region from the region drop-down on the top right corner, for which the alert is generated

. Go to the EC2 Dashboard, and select 'Load Balancers'

. Click on the reported Load Balancer

. On the Description tab, choose 'Edit attributes'

. On the Edit load balancer attributes page, select 'Enable' for 'Delete Protection'

. Click on 'Save' to save your changes
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_lb
* *Arguments:* enable_deletion_protection


[source,go]
----
resource "aws_lb" "test_success" {
  ...
+ enable_deletion_protection = true
}
----
