== Dynamodb point in time recovery is not enabled for global tables


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 09745d74-a2aa-4802-a022-33eced685a47

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/DynamoDBGlobalTableRecovery.py[CKV_AWS_165]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Enabling point-in-time recovery (PITR) for Amazon DynamoDB global tables can help to protect against data loss due to accidental write or delete operations, or due to data corruption.
With PITR enabled, you can restore a global table to any point in time within the specified recovery window (typically up to 35 days).
This can be helpful if you need to undo unintended changes or recover from data corruption.

=== Fix - Buildtime


*CloudFormation* 


* *Resource:*  AWS::DynamoDB::GlobalTable
* *Arguments:* Properties.DistributionConfig.Logging/Bucket


[source,yaml]
----
Resources:
  MyCloudFrontDistribution:
    Type: AWS::DynamoDB::GlobalTable
    Properties: 
            ...
      Replicas: 
+       - PointInTimeRecoverySpecification: 
+           - PointInTimeRecoveryEnabled
----
