== GuardDuty is not enabled to specific org/region


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| f22347f8-2814-45a4-af73-b2cc4991aacf

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/GuardDutyIsEnabled.yaml[CKV2_AWS_3]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


GuardDuty is a security service provided by Amazon Web Services (AWS) that uses machine learning and threat intelligence to detect potential threats to your AWS accounts and workloads.
Enabling GuardDuty in specific regions or within your organization can help you to identify and respond to potential threats more quickly and effectively.
This can help to reduce the risk of security breaches and protect your data and systems from malicious activity.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_guardduty_detector, aws_guardduty_organization_configuration
* *Arguments:* _auto_enable_ of aws_guardduty_organization_configuration


[source,go]
----
resource "aws_guardduty_detector" "ok" {
  enable = true
}

resource "aws_guardduty_organization_configuration" "example" {
  auto_enable = true
  detector_id = aws_guardduty_detector.ok.id
}
----
