== DocDB does not have audit logs enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 3d19b0c1-6479-47dc-b5c1-f9137fb90683

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/DocDBAuditLogs.py[CKV_AWS_104]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Enabling audit logs for Amazon DocumentDB (DocDB) can help you to monitor and track activity within your DocDB cluster.
Audit logs provide a record of database activity, including details about the activity itself (e.g., which database was accessed, what type of operation was performed), as well as information about the user or application that initiated the activity.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_docdb_cluster_parameter_group
* *Arguments:*  parameter.audit_logs


[source,go]
----
resource "aws_docdb_cluster_parameter_group" "test" {
     ...
+  parameter {
+    name  = "audit_logs"
+    value = "enabled"
  }
}
----


*CloudFormation* 


* *Resource:* AWS::DocDB::DBClusterParameterGroup
* *Arguments:*  Parameters.audit_logs


[source,yaml]
----
Resources:
    DocDBParameterGroupEnabled:
        Type: "AWS::DocDB::DBClusterParameterGroup"
        Properties:
        ...
+       Parameters: 
+       audit_logs: "enabled"
            ...
----
