== AWS GuardDuty detector is enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4c78b025-0101-42d4-8028-3585a62c66f9

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/GuarddutyDetectorEnabled.py[CKV_AWS_238]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 


Enabling the AWS GuardDuty detector can help protect your Amazon Web Services (AWS) resources from various types of threats, such as malware, data breaches, and unauthorized access.
GuardDuty is a threat detection service that uses machine learning and other techniques to analyze data from various sources (such as VPC Flow Logs, AWS CloudTrail logs, and DNS logs) and identify potential security threats.
By ensuring that the GuardDuty detector is enabled, you can take advantage of this service and receive alerts when potential threats are detected.
This can help you take timely action to address any security issues and prevent security incidents from occurring.

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "aws_guardduty_detector" "pass" {
  enable = true
  tags   = { test = "Fail" }
}
----
