== AWS SageMaker notebook instance not configured with data encryption at rest using KMS key


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| f2c2c424-6fc9-4f99-8efb-4cb09810be97

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/SagemakerNotebookEncryption.py[CKV_AWS_22]

|Severity
|HIGH

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Amazon SageMaker enables you to pass a KMS key to SageMaker notebooks, securing the following resources:

* Storage volume
* Processing jobs
* Training jobs
* Hyperparameter tuning jobs
* Batch transform jobs
* Endpoints

By applying encryption at-rest you ensure that the data stored on your AWS SageMaker notebook instances meet regulatory requirements and protect your SageMaker data at rest.

////

=== Fix - Runtime

* AWS Console* 

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the https://console.aws.amazon.com/sagemaker/ [Amazon SageMaker console].

. Select Notebook instances, then click * Create Notebook Instance*.

. On the Create Notebook Instance page, provide the required information.

. The * Encryption key* lets you encrypt data on the ML storage volume attached to the notebook instance using an AWS Key Management Service (AWS KMS) key.
+
If you plan to store sensitive information on the ML storage volume, consider encrypting the information.


* CLI Command* 


To create a SageMaker notebook instance:


[source,shell]
----
{
 "  create-notebook-instance
--notebook-instance-name & lt;value>
--instance-type & lt;value>
--kms-key-id & lt;value>",
}
----

////



=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_sagemaker_notebook_instance
* *Attribute*: kms_key_id - (Optional) The AWS Key Management Service (AWS KMS) key that Amazon SageMaker uses to encrypt the model artifacts at rest using Amazon S3 server-side encryption.


[source,go]
----
resource "aws_sagemaker_notebook_instance" "example" {
  ...
  name          = "my-notebook-instance"
+ kms_key_id    = <value>
  ...
}
----
