== Related Documentation

Refer to the following documentation on the https://docs.paloaltonetworks.com[Technical Documentation portal] or https://docs.paloaltonetworks.com/search.html[search] the documentation for more information on our products:

* *Prisma Cloud Administrator's Guide (Compute)* --
Provides the concepts and workflows to get the most out of the Compute service in Prisma Cloud Enterprise Edition.
The http://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-guide-compute/[Prisma Cloud Administrator’s Guide (Compute)] also takes you through the initial onboarding and basic set up for securing your hosts, containers, and serverless functions.

* *Prisma Cloud Compute Edition Administrator's Guide* --
Provides the concepts and workflows to get the most out of the Prisma Cloud Compute Edition, the self-hosted version of Prisma Cloud's workload protection solution.
The http://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-admin/[Prisma Cloud Administrator’s Guide (Compute)] also takes you through the initial onboarding and basic set up for securing your hosts, containers, and serverless functions.*

* *Prisma Cloud Administrator's Guide* --
Provides the concepts and workflows to get the most out of the Prisma Cloud service.
The https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin.html[Prisma Cloud Administrator’s Guide] also takes you through the initial onboarding and basic set up for securing your public cloud deployments.

* *Prisma Cloud RQL Reference* -- 
Describes how to use the https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-rql-reference.html[Resource Query Language (RQL)] investigate incidents and then create policies based on the findings.

* *Prisma Cloud Code Security Administrator's Guide* --
Use the https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-code-security.html[Code Security Guide] to scan and secure your Iac templates and identify misconfiguration before you go from code to cloud.