== Alibaba Cloud RAM password policy does not have an uppercase character


*Policy Details* 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a3e8df44-208d-4962-be8a-43ff7f8841e0

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RAMPasswordPolicyUppcaseLetter.py[CKV_ALI_19]

|Severity
|MEDIUM

|Subtype
|Build, Run

|Frameworks
|Terraform

|=== 



*Description* 


This policy identifies Alibaba Cloud accounts that do not have an uppercase character in the password policy.
As a security best practice, configure a strong password policy for secure access to the Alibaba Cloud console.

=== Fix - Runtime


*Alibaba Cloud Portal* 



. Log in to Alibaba Cloud Portal

. Go to Resource Access Management (RAM) service

. In the left-side navigation pane, click on 'Settings'

. In the 'Security Settings' tab, In the 'Password Strength Settings' Section, Click on 'Edit Password Rule'

. In the 'Required Elements in Password' field, select 'Upper-Case Letter'

. Click on 'OK'

. Click on 'Close'

=== Fix - Buildtime


*Terraform* 




[source,go]
----
{
  "codes": [
    {
      "code": "resource "alicloud_ram_account_password_policy" "pass" {
  minimum_password_length      = 14
  require_lowercase_characters = false
  require_uppercase_characters = true
  require_numbers              = false
  require_symbols              = true
  hard_expiry                  = true
  max_password_age             = 14
  password_reuse_prevention    = 5
  max_login_attempts           = 3
}",
      "language": "go"
    }
  ]
}
----
