== Permissions Required for OCI Tenant on Prisma Cloud

In order to monitor your OCI resources, Prisma Cloud requires access to an OCI tenant that enables authentication between Prisma Cloud and OCI.

You must have administrator access to an OCI tenant to enable read permission for Prisma Cloud.

Prisma Cloud uses the Terraform file to create a group and add a user to the group. It also creates a policy and applies the policy to that group. Prisma Cloud needs read permissions for all the supported services.

[NOTE]
====
OCI has a limit of 50 policy statements that can be added to a single IAM policy, but Prisma Cloud supports over 100 policy statements. To successfully ingest all of the OCI APIs, you do not need to request a https://docs.oracle.com/en-us/iaas/Content/General/Concepts/servicelimits.htm[service limit increase] from OCI on the policy statements. However, you must update your existing Terraform file as outlined in xref:../../connect-cloud-accounts/onboard-your-oci-account/update-oci-permissions.adoc[Update Permissions on an Onboarded OCI Account].
====