[#authentication]
== Authentication

Prisma Cloud provides broad enterprise identity support.
It can integrate with a number of identity providers, including Active Directory, OpenLDAP, Ping, Okta, Shibboleth, Azure AD, and Google G Suite, so you can implement single sign-on for the Prisma Cloud Console.
Prisma Cloud supports simultaneous integration with multiple identity providers.
For example, you might want to integrate with both Okta and GitHub to support users that login from both platforms.

Prisma Cloud ships with prebuilt roles to provide least privilege access to your DevOps and security teams.
Use assigned collections to precisely control what data teams can view or use built-in multi-tenancy to securely isolate entire business units or geographies within the same Console.

Pluggable cryptography lets you bring your own certificates, not just for TLS, but also for smart card authentication to Console.

A credentials store providers a single secure location to store service accounts for integration with the various cloud providers.
Define them once in the credentials store, and then reuse them throughout Console for your various integrations.
