= JFrog Artifactory
:nofooter:
:numbered:
:imagesdir: troubleshooting/registry/images
:source-highlighter: highlightjs
:toc: macro
:toclevels: 2
:toc-title:

toc::[]


== Overview
// <Related Technology>
If you have deployed a Defender to scan an Artifactory registry, there are several caveats to look out for.
// Give a brief description on what the underlying technology is. For example - Does this relate to aws? or is this a daemonset install issue? Or gcr registry scanning? etc. 

== Error messages
// How would the issue appear? If a user wanted to confirm if this issue applied to him, what does he need to look for? Provide step by step procedure
1. x509 error
If you find that your images are not able to be scanned because of an error like the following: 

```
Failed to pull image docker-local/sampleimage:v1.0.0dev-1, error API error (500): Get https://myconsole.twistlock.com/v2/: x509: certificate signed by unknown authority
```
This most likely means that you have a self-signed certificate that the underlying docker daemon on the defender host does not trust. This can also happen if you have set up Artifactory as an insecure registry.

== Steps to confirm the issue

// Anything in logs or on host that the customer would need to check to confirm if it's the same issue?
If you go to the host that the Prisma Cloud Defender is running on and try to pull your Artifactory images, you should receive the same error

== Troubleshooting steps
You will need to add your trusted self-signed cert to the docker daemon. Specify the URL of the insecure registry on the machine where the registry scanning Defender runs, then restart the Docker service.
For more information, see the https://docs.docker.com/registry/insecure/[Docker documentation].

=== Additional information
//  (e.g. Does the troubleshooting differ in HA?)
If you do not have a host that is able to access the underlying docker daemon, you will need to find other ways to get your host to trust the Artifactory instance. Please consult the Artifactory documentation for these steps.

=== Prisma Cloud version: Any version
