== Azure Kubernetes Cluster (AKS) Nodes Do Not Use Scale Sets
// Ensure Azure Kubernetes Cluster (AKS) nodes use scale sets.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 40487b20-8a44-4eca-83a2-9c4b122962e2

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/AKSPoolTypeIsScaleSet.py[CKV_AZURE_169]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

For Azure Kubernetes Service (AKS), it's recommended to use Virtual Machine Scale Sets instead of Availability Sets for nodes in the cluster. Scale Sets provide high availability to your applications, and enable you to centrally manage, configure, and update a large number of VMs. 

This policy ensures that AKS nodes are configured to use Virtual Machine Scale Sets and not Availability Sets.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_kubernetes_cluster
* *Arguments:* default_node_pool/type

[source,terraform]
----
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  default_node_pool {
    name       = "default"
+   type       = "VirtualMachineScaleSets"
  }

  tags = {
    Environment = "dev"
  }
}
----
