== Azure AKS cluster network policies are not enforced
// Azure Kubernetes Service (AKS) cluster network policies not enforced


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 61623d0c-5208-48b2-b320-1d6eb284e61d

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/arm/checks/resource/AKSNetworkPolicy.py[CKV_AZURE_7]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|ARM,Terraform,Bicep,TerraformPlan

|=== 



=== Description 


Network policy options in AKS include two ways to implement a network policy.
You can choose between Azure Network Policies or Calico Network Policies.
In both cases, the underlying controlling layer is based on Linux IPTables to enforce the specified policies.
Policies are translated into sets of allowed and disallowed IP pairs.
These pairs are then programmed as IPTable rules.
The principle of least privilege should be applied to how traffic can flow between pods in an AKS cluster.
We recommend you select a preferred network policy framework and enforce granular usage-based policies on the architecture and business logic of you applications.

=== Fix - Buildtime


*Terraform* 


*Resource*: azurerm_kubernetes_cluster *Argument*: network_policy


[source,go]
----
resource "azurerm_kubernetes_cluster" "example" {
...
  network_profile {
+    network_policy="azure"
  }
...
}
----
