== AKS does not use disk encryption set
// Azure Kubernetes Service (AKS) does not use disk encryption set


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2b3fa957-1875-4d35-b4b1-2355f04f6ab1

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/AKSUsesDiskEncryptionSet.py[CKV_AZURE_117]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Disk encryption is a security measure that encrypts the data on a disk to protect it from unauthorized access or tampering.
When disk encryption is enabled for AKS, it encrypts the data on the disks that are used by the nodes in your cluster.
This can help to protect your data from being accessed or modified by unauthorized users, even if the disks are physically stolen or the data is accessed from an unauthorized location.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_kubernetes_cluster
* *Arguments:* disk_encryption_set_id


[source,go]
----
resource "azurerm_kubernetes_cluster" "example" {
              ...
 +            disk_encryption_set_id = "someId"
            }
----
