== Fine Tune Your Configuration Settings

After integrating your code repositories, you can modify your configuration to specify how Prisma Cloud  scans your code. This includes:
After the integration of the code repository with Prisma Cloud, you can further configure your code scans through multiple options. 
* Exclude paths from Code Security scans.
* Enable Code Reviews. 
* Enable Pull Request Bot Comments.
* Enable Notifications.
* Enable Tagging Bot.

Go to *Settings > Code Configuration* to configure your integrated repository.
+
//TODO: image::[width=800]

[.task]
=== Exclude Paths from Code Security scans

Configure your code security scan by adding rules to an integrated repository. New rules are scanned only for a single associated repository. You can however configure multiple repositories with an associated rule. 
By default, Prisma Cloud scans all paths in all repositories.

You can exclude paths from scanning by adding a rule to exclude paths. Before you begin adding rules, disable the default configuration for all repositories. 

[.procedure]
. Enable repositories you want to scan.
.. Select specific repositories From Repositories.
+
//TODO: image::[width=800]

. Enter paths to exclude from the repository.

.. Type paths to exclude within the selected repository.
+
Use comma (,) to list more than one file or path. 
+
In this example, On Enter Paths, type ‘ test, _test, \/test\/’ this will exclude any path or file with the specified context. 
+
//TODO: image::[width=800]


. Add rule.

.. Click *Add Rule*.
+
//TODO: image::[width=800]

.. Click *Save* to exclude the path from the scan. 

[.task]
=== Enable Code Reviews
Enable code review configuration to code repository to receive error notifications for each new pull request (PR)  that Prisma Cloud scans. With the error notifications, code reviews also offer options to fix or suppress the error identified.  

By default, the Code Reviews is enabled.

In addition, by default, Prisma Cloud scans all paths in all repositories. Before you begin adding rules, disable the default configuration for all repositories. 
You can further configure Code Reviews. 

[.procedure]
. Enable repositories you want to scan.
+
//TODO: image::[width=800]

. Select the fail severity of the policy.
+
The fail severity lies between High, Medium and Low.
+
//TODO: image::[width=800]
+	
You can optionally specify policies to exclude during the scan.
+
NOTE: Once you have specified your repository, the policies are automatically listed. 

. Add rule.
.. Click *Add Rule*
+
//TODO: image::[width=800]

.. Click *Save* to add code review configuration. 
+
//TODO: image::[width=800]

[.task]
=== Enable Pull Request Bot Comments

Enable Pull Request Bot Comments in code repository to receive policy violations notifications as a comment in a pull request. You can configure the repository for which you choose to receive comments and also set the threshold of policy severity notifications. 
By default, the Pull Request Bot Comments is enabled.
In addition, by default, Prisma Cloud scans all paths in all repositories. Before you begin adding rules, disable the default configuration for all repositories. 
You can further configure Pull Request Bot Comments . 

[.procedure]

. Enable repositories you want to scan.
+
//TODO: image::[width=800]

. Select the threshold of the policy severity. 
+
The severity lies between High, Medium and Low.
+
//TODO: image::[width=800]
+	
You can optionally specify policies to exclude during the scan. 
+
//TODO: image::[width=800]


. Add rule

.. Click *Add rule* and then select *Save* to add code review configuration. 
+
//TODO: image::[width=800]

[.task]
=== Enable Notifications

Enable notifications for your external integrations to receive notifications for code security scans. Prisma Cloud supports notification configuration only on Microsoft Teams, Slack, Splunk, and Webhooks.
By default, Notifications is disabled. 
Before you enable notifications,  set up the integration.  
After you have set up your integration, disable the default configuration for all repositories, as by default Prisma Cloud scans all paths in all repositories. 
You can further configure Notifications. 

[.procedure]

. Enable repositories you want to scan.
+
//TODO: image::[width=800]

. Select the name or ID of the integration.
+
//TODO: image::[width=800] 

. Select the threshold of the policy severity. 
+
The severity lies between High, Medium and Low.
+
//TODO: image::[width=800]
+
You can optionally specify policies to exclude during the scan. 
+
//TODO: image::[width=800]

. Add rule
.. Click *Add rule* and then select *Save* to add notification configuration to an integration.
+
//TODO: image::[width=800]

[.task]

=== Enable Tagging Bot

Enable Tagging bot to be notified when a PR is committed to the default branch with a new IaC code. You can add traceability tags  to your repositories that help locate runtime resources based on a specific IaC code and also trace the difference between cloud and code repositories. The tagging of a repository can be done manually, automatically (using Yor), or by using Prisma Cloud Tagging bot (Via Yor).
The yor_trace tag is a unique identifier indicating the git commit in combination with the specific IaC resource, it has initial support for Terraform, CloudFormation, and Serverless, Yor adds tags to IaC configurations that carry over to running cloud resource tags, for more details on yor, see here
By default, Tagging Bot is disabled. 

You can exclude paths from scanning. Before you begin, disable the default configuration for all repositories. 

[.procedure]

. Enable repositories you want to scan.

.. Select specific repositories *From Repositories*.
+
//TODO: image::[width=800]

. Enter paths to exclude from the repository.

.. Type paths to exclude within the selected repository.
+
Use comma (,) to list more than one file or path. 
+
In this example, On Enter Paths, type ‘ test, _test’  this will exclude any path or file with the specified context.
+
//TODO: image::[width=800]

. Save to exclude the path from the scan. 

.. Click *Save*
+
//TODO: image::[width=800]

