== Monitor and Fix Issues in Your Scans

The scan results for all your integrated repositories are viewed on *Code* page.On *Code* page you can review the results for each repositories and choose to either fix the result or suppress the scan result.

=== Get familiar with Reviewing Scan Results

To locate a specific Code scan result, you can Browse, Search or Filter.

==== Browse Source List

The repositories catalog on *Settings > Repositories* lists all the environments that you can scan using Prisma Cloud Code Security. It includes Version Control Systems/Code Repositories, CI/CD pipelines and Integrated Development Environments (IDEs).

* You can navigate between your repositories from the
* Code Reviews from repositories are grouped by the path of a folder.
* Each entry within a path is for an error found in a specific resource for a specific file, as indicated in the entry's header.

//TODO:In the example below, the file name is providers.tf and the string after :: is the resource name.
+
//TODO: image::[width=800]


==== Search for a Code Review Source

To search for a specific source, or a specific source type, enter the  name or part of its name. For example, if you enter "github" in the search, only Github repositories will be shown.

//TODO: image::[width=800]

==== Filter Errors within a Code Review Source

You can filter for specific errors within a Code Review source based on: Category, Severity, Tags or Status.

//TODO: image::[width=800]

===== Status
Filter by status:

* Errors - errors that have not been Fixed or Suppressed.
* Suppressed - errors that have been Suppressed.
* Passed - errors that have been fixed and not detected again in later runs.
+
The example below shows an issue that has been suppressed by the user.
+
//TODO: image::[width=800]
The example below an issue that had previously failed, was fixed and passed in the most recent scan.
+
//TODO: image::[width=800]

===== Category
Filter for errors based on a specific category, such as IAM, Monitoring or Networking.

===== Severity
Filter for errors based on severity: Critical, High, Medium, and Low.

===== Tags
Filter based on tagged individual key-value pairs, if defined.

===== Filter by User
As shown in the image below, you can filter within the default branch of a VCS-based source based on the user.

=== View Scan from Pull Requests
In the case of scans from Code Repositories , you can view scans from the default branch or from Pull Requests (if enabled in Code Repository settings).
In the example below, the source is a Bitbucket repo integrated with Prisma Cloud DevSecOps.
Select View PR Scans to see Code Reviews from Pull Requests.

NOTE: To see Code Reviews for every PR (and not only the default branch), you must enable Code Reviews in the Code Repository settings.
When enabled, View PR Scans will appear.

==== Navigate to a Specific PR

When viewing PR scans, you can drop down a list of PRs or search for a specific PR.

//TODO: image::[width=800]

The name of the PR currently displayed is highlighted in bold.
The number of errors in a PR appears next to its name.

==== Select a Commit or View Latest

* Within a PR, you can view the latest commit, or select a commit from a list of those available.
* By default, the newest commit is shown. You can navigate to older commits.

//TODO: image::[width=800]

==== Manual Fix for Commit

In some cases, no automated Fix is available. In these cases the details of a manual Fix will appear upon selecting Submit.

* Manual fixes appear only for a PR which is the most recent Commit.
* You can find the most recent Commit by selecting View Latest.
* After applying a manual fix, you will be redirected to Github opens to the relevant code. Select Mark as Fixed,
* When you press Fix Manually - Github opens to the code where the Policy violation is located and then you press Mark as Fixed.
* Return to Default Branch.
* When viewing PRs, you can return to the default branch by selecting View.

=== View Scan from CI/CD System Run

CI/CD scans are listed from the newest to oldest, showing the Prisma Cloud Code Security scan ID and the timing of the scan. Suppression can be performed on the newest (i.e., to specify this error type for this resource in future runs). For others, you can view the error and its guidelines but cannot Suppress.
If the specific CI system in use supports scans of differing branches (as opposed to the entire default branch) and is configured to do so, you can navigate to the different branches by pressing the arrow that will appear for navigating and selecting a specific scan.
If the default branch scanned is not named, the display will show "No Name".

//TODO: image::[width=800]


