== Hardcoded passwords are being used

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| b0926f36-4512-4c0b-a5fe-84fc29d6a16e

|Checkov ID 
|CKV3_SAST_152

|Severity
|HIGH

|Subtype
|Build

|Language
|python

|CWEs
|https://cwe.mitre.org/data/definitions/798.html[CWE-798: Use of Hard-coded Credentials]

|OWASP Categories
|https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/[A07:2021 - Identification and Authentication Failures]

|=== 

=== Description

The SAST policy detects the use of hardcoded passwords as default arguments in certain Flask or FastAPI routes or functions. This is considered a security vulnerability because hardcoded passwords can be easily obtained by attackers, compromising the authentication system.

Vulnerable code example:

[source,python]
----
@app.route('/login')
def login(password='admin'):
    if password == GLOBAL_DICT.get('admin'):
        # do something
    # do something else
----

In the above code, the `login` function has a default password argument of 'admin'. This means that if a real password is not supplied when calling the function, it falls back to the hardcoded password 'admin'. An attacker could potentially discover this password and gain unauthorized access.

=== Fix - Buildtime

To fix this issue, it is recommended to remove the hardcoded password and implement a secure authentication mechanism. One possible approach is to use a secure password storage mechanism, such as hashing the passwords and comparing the hashes instead of plaintext.

Secure code example:

[source,python]
----
@app.route('/login')
def login(password=None):
    if password and password == GLOBAL_DICT.get('admin'):
        # do something
    # do something else
----

In the fixed code, the default password argument has been changed to `None`, indicating that if no password is provided, it will not automatically fall back to a hardcoded value. Additionally, the code now checks if the `password` variable is not empty before comparing it with the stored password in `GLOBAL_DICT`. This ensures that only valid passwords are accepted.

By implementing these changes, the code no longer relies on hardcoded passwords and provides a more secure authentication mechanism.
    