
== Improper Check or Handling of Exceptional Conditions

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 60798fd8-d648-41b5-be49-64cf321beac7

|Checkov ID 
|CKV3_SAST_166

|Severity
|LOW

|Subtype
|Build

|Language
|python

|CWEs
|https://cwe.mitre.org/data/definitions/703.html[CWE-703: Improper Check or Handling of Exceptional Conditions]

|OWASP Categories
|

|=== 

=== Description

This policy detects instances where there is improper check or handling of exceptional conditions. It looks for code that uses a try-except block and immediately continues execution inside the except block, without properly addressing or handling the exceptional condition.

Vulnerable code example:

[source,python]
----
try:
  # Some code that may raise an exception
except Exception:
  continue
----

The above code is vulnerable because it captures all exceptions using a broad "Exception" class and simply continues execution without any proper handling or logging of the exception. This can result in unhandled exceptions and unexpected behavior in the application.

=== Fix - Buildtime

To fix this issue, it is important to appropriately handle the exceptional condition. This involves:

- Identifying the specific exception(s) that may be raised within the try block.
- Implementing appropriate error handling or recovery logic within the except block.
- Properly logging or reporting the exception for debugging purposes.

Secure code example:

[source,python]
----
try:
  # Some code that may raise an exception
except SpecificException as e:
  # Handle the specific exception
  log_error(e)
  # Take necessary actions to recover from the exception
----

In the secure code example, the specific exception type (e.g., "SpecificException") is caught in the except block, allowing for proper handling and recovery. The example also includes logging the error for debugging purposes, and taking necessary actions to recover from the exception, instead of simply continuing execution. This ensures that exceptional conditions are properly addressed and the application can maintain its expected behavior.
    