== HTML Autoescape Mechanism Should Not Be Globally Disabled

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ec8af148-ad66-4002-a5c5-5d639b61eda0

|Checkov ID 
|CKV3_SAST_60

|Severity
|MEDIUM

|Subtype
|Build

|Language
|Python

|CWEs
|https://cwe.mitre.org/data/definitions/80.html[CWE-80: Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)]

|OWASP Categories
|https://owasp.org/www-project-top-ten/2017/A3_2017-Cross-Site_Scripting_(XSS)[A03:2021 - Injection]

|=== 

=== Description

The autoescaping mechanism in Jinja2 is a critical component to prevent Cross-Site Scripting (XSS) attacks. By default, Jinja2 sets autoescaping to `True`, ensuring that all variable content gets escaped. Disabling this mechanism globally can lead to vulnerabilities where untrusted data gets rendered as-is, potentially leading to XSS vulnerabilities.

Example of vulnerable configuration:

[source,python]
----
from jinja2 import Environment

# Vulnerable configuration with autoescaping disabled
env = Environment(autoescape=False)
----

=== Fix - Buildtime

To mitigate potential XSS risks:

1. Ensure that the autoescape mechanism is not disabled globally.
2. If autoescaping needs to be turned off for specific use cases, do so cautiously and locally. Always validate and sanitize untrusted input.
3. Regularly review and audit the configurations and templates to ensure best security practices are being followed.

The following shows the recommended approach:

[source,python]
----
from jinja2 import Environment

# Safe configuration with autoescaping enabled
env = Environment(autoescape=True)
----

Autoescaping plays a pivotal role in ensuring web application security. Ensure to maintain it enabled to protect against potential XSS attacks.
