
== Insecure active debug code

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a26c6363-95f2-478f-b50d-12b41b96057b

|Checkov ID 
|CKV3_SAST_96

|Severity
|MEDIUM

|Subtype
|Build

|Language
|python

|CWEs
|https://cwe.mitre.org/data/definitions/489.html[CWE-489: Active Debug Code]


|=== 

=== Description

This policy detects Flask applications with the `debug=True` flag enabled. Enabling this flag in production can lead to information disclosure and is considered a security misconfiguration.

Vulnerable code example:

[source,python]
----
app = flask.Flask(__name__)
app.run(host='0.0.0.0', port=5000, debug=True)
----

In the above code, the `debug=True` flag is enabled when running the Flask application. This means that detailed error messages and debugging information will be displayed to the user, potentially leaking sensitive information.

=== Fix - Buildtime

To fix this issue, you should avoid enabling the `debug` flag in production. Instead, consider using Flask configuration variables or setting `debug` using system environment variables.

Secure code example:

[source,python]
----
app = flask.Flask(__name__)
app.config['DEBUG'] = False
app.run(host='0.0.0.0', port=5000)
----

In the secure version of the code, the `DEBUG` configuration variable is set to `False` to disable the debug mode. This ensures that sensitive information is not leaked to the user.

By disabling the debug mode, the secure code version prevents the detailed error messages and debugging information from being displayed to the user, protecting sensitive information.
    