
== Use of Insufficiently Random Values

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ea91c03b-70c6-4837-844d-e36e43520e00

|Checkov ID 
|CKV3_SAST_167

|Severity
|LOW

|Subtype
|Build

|Language
|python

|CWEs
|https://cwe.mitre.org/data/definitions/330.html[CWE-330: Use of Insufficiently Random Values]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects the use of insufficiently random values in Python code. It specifically looks for the usage of the `random` module's non-secure pseudo-random number generator functions.

Vulnerable code example:

[source,python]
----
import random

password = "secret_" + str(random.randint(1, 100))
----

The above code is vulnerable because it uses the `random.randint` function from the `random` module, which is a non-secure pseudo-random number generator. This type of generator is not suitable for security or cryptographic purposes as it can be easily predicted or brute-forced.

=== Fix - Buildtime

To fix the vulnerability, you should use the `random.SystemRandom()` function instead, which is based on the underlying operating system's random source and provides a more secure random number generator.

Secure code example:

[source,python]
----
import random

password = "secret_" + str(random.SystemRandom().randint(1, 100))
----

The above code is no longer vulnerable because it uses the `random.SystemRandom().randint` function, which uses the operating system's random source to generate more secure random numbers.
    