== Dynamic code execution (vulnerable to injection attacks)

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 152a5fba-69ab-4048-8e92-adf4abc626e9

|Checkov ID 
|CKV3_SAST_87

|Severity
|HIGH

|Subtype
|Build

|Language
|python

|CWEs
a|https://cwe.mitre.org/data/definitions/95.html[CWE-95: Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')]

https://cwe.mitre.org/data/definitions/20.html[CWE-20: Improper Input Validation]

|OWASP Categories
|https://owasp.org/Top10/A03_2021-Injection/[A03:2021 – Injection]

|=== 

=== Description

This policy detects dynamic code execution vulnerabilities in Python code. 

Vulnerable code example:

[source,python]
----
user_input = request.args.get('input')
result = eval(user_input)
----

The above code is vulnerable because it directly passes user input to the `eval()` function, which can execute arbitrary code. This can lead to an injection attack where an attacker can execute malicious code and gain unauthorized access or manipulate the application.

=== Fix - Buildtime

To fix the issue, you should avoid using the `eval()` function with user input. Instead, you should validate and sanitize the input before using it. 

Secure code example:

[source,python]
----
user_input = request.args.get('input')
# Validate and sanitize the user input
if set(user_input).issubset('abcdefghijklmnopqrstuvwxyz'):
    result = eval(user_input)
else:
    result = "Invalid input"
----
    