
== Writing unvalidated input into JSON

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e7c0ba71-2715-4dc8-a8f4-8e9753b56632

|Checkov ID 
|CKV3_SAST_82

|Severity
|MEDIUM

|Subtype
|Build

|Language
|python

|CWEs
a|https://cwe.mitre.org/data/definitions/20.html[CWE-20: Improper Input Validation]

https://cwe.mitre.org/data/definitions/74.html[CWE-74: Improper Neutralization of Special Elements in Output Used by a Downstream Component]

https://cwe.mitre.org/data/definitions/116.html[CWE-116: Improper Encoding or Escaping of Output]

|OWASP Categories
|https://owasp.org/Top10/A03_2021-Injection/[A03:2021 - Injection]

|=== 

=== Description

This policy detects instances where unvalidated user input is written into a JSON object. Writing unvalidated input into JSON can enable attackers to inject malicious elements, potentially leading to security breaches, data corruption, and unauthorized access.

Vulnerable code example:

[source,python]
----
import json

user_input = input("Enter your name: ")
data = {'name': user_input}

json.dump(data)
----

=== Fix - Buildtime

To fix this issue, you should validate and sanitize any user input before writing it into a JSON object. This involves ensuring that the input follows expected format and does not contain any malicious elements.

Secure code example:

[source,python]
----
import json

user_input = input("Enter your name: ")
sanitized_input = user_input.strip()  # Sanitize input by removing leading/trailing white spaces

data = {'name': sanitized_input}

json.dump(data)
----
    