== Improper access control

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7498a565-2b24-420e-a2c8-8b2c38f5fc95

|Checkov ID 
|CKV3_SAST_97

|Severity
|HIGH

|Subtype
|Build

|Language
|python

|CWEs
|https://cwe.mitre.org/data/definitions/284.html[CWE-284: Improper Access Control]

|OWASP Categories
|

|=== 

=== Description

This policy detects the use of vulnerable functions in Python code that can lead to improper access control. The specific vulnerable functions it looks for are `wsgiref.handlers.CGIHandler` and `twisted.web.twcgi.CGIDirectory`.

Vulnerable code example:

[source,python]
----
import wsgiref.handlers

def some_function():
    handler = wsgiref.handlers.CGIHandler()  # This code violates the policy
    # Rest of the code
----

The above code is vulnerable because it uses the `wsgiref.handlers.CGIHandler` function, which is susceptible to improper access control issues.

=== Fix - Buildtime

To fix the issue, you should avoid using the vulnerable functions and instead use secure alternatives or implement proper access control mechanisms.

Secure code example:

[source,python]
----
import http.server

def some_function():
    handler = http.server.SimpleHTTPRequestHandler()  # This code is no longer vulnerable
    # Rest of the code
----

The above code is no longer vulnerable because it uses the secure `http.server.SimpleHTTPRequestHandler` function instead of the vulnerable `wsgiref.handlers.CGIHandler`. This ensures proper access control and reduces the risk of security implications.
    