== None attributes accessed

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 81669e48-ce4c-4fde-a94c-61fb0f1442f2

|Checkov ID 
|CKV3_SAST_73

|Severity
|MEDIUM

|Subtype
|Build

|Language
|Python

|CWEs
|https://cwe.mitre.org/data/definitions/476.html[CWE-476: NULL Pointer Dereference]


|=== 

=== Description

In Python, `None` represents the absence of a value or a null pointer. Attempting to access an attribute of a `None` object will result in an `AttributeError`. If not handled correctly, this error can lead to unexpected behaviors in your code, and potentially expose sensitive debugging information that can be leveraged by attackers to better understand your application's internals.

For instance:

[source,python]
----
# Vulnerable usage
if user is None:
    print(user.username)
----

This code will raise an `AttributeError` when trying to access the `username` attribute of a `None` object, leading to unexpected application behavior.

=== Fix - Buildtime

To mitigate this vulnerability:

1. Always check if an object is `None` before attempting to access its attributes.
2. Utilize appropriate error handling mechanisms to ensure that `AttributeError` or any other unexpected errors do not propagate sensitive information to the end-user.
3. Ensure thorough code reviews are done to catch instances where `None` values might be improperly accessed.

A safer approach:

[source,python]
----
# Recommended code snippet
if user:
    print(user.username)
else:
    print("User not found.")
----

By being diligent in checking for `None` before accessing attributes and employing robust error handling, you can prevent potential crashes, ensure a smoother user experience, and prevent exposure of sensitive information.
