== CSRF protections disabled

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 466b43de-09e9-41f4-957d-66b689ae77f8

|Checkov ID 
|CKV3_SAST_56

|Severity
|HIGH

|Subtype
|Build

|Language
|Python

|CWEs
|https://cwe.mitre.org/data/definitions/352.html[CWE-352: Cross-Site Request Forgery (CSRF)]

|OWASP Categories
|https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[A01:2021 - Broken Access Control]

|=== 

=== Description

Cross-Site Request Forgery (CSRF) is an attack that forces a victim to execute unwanted actions on a web application they are authenticated with. By disabling CSRF protections, applications expose themselves to a serious security risk. This policy has identified instances where CSRF protections are disabled or not correctly implemented.

When CSRF protections are disabled, it can lead to:

1. Unauthorized actions performed on behalf of an authenticated user.
2. Data breaches.
3. Account hijacking.
4. Exploitation of the trust a user has with a specific site.

In the analyzed codebase, instances were detected where the CSRF protections were explicitly turned off. Such configurations increase the application's vulnerability to CSRF attacks.

For example, avoiding practices like:

[source,python]
----
# Disabling CSRF protection in Flask-WTF
class MyForm(flask_wtf.FlaskForm):
    class Meta:
        csrf = False
----

=== Fix - Buildtime

To ensure the security of your application:

1. Always enable CSRF protections in web applications, especially in forms, API endpoints, and other user-facing components.
2. Never turn off CSRF protections in configurations or use decorators that bypass them.
3. Regularly update and review libraries that handle CSRF protections to follow best security practices.

For instance, implementing CSRF protection in a Flask application:

[source,python]
----
from flask_wtf.csrf import CSRFProtect

app = flask.Flask(__name__)
csrf = CSRFProtect(app)
----

This approach ensures that CSRF tokens are generated and checked on every request, safeguarding against potential attacks. Ensure that all parts of your application use and enforce CSRF tokens and that protections are not mistakenly disabled.
