
== Uncontrolled Resource Consumption

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 49979d08-acc0-488f-aeee-323bde47c742

|Checkov ID 
|CKV3_SAST_91

|Severity
|MEDIUM

|Subtype
|Build

|Language
|python

|CWEs
|https://cwe.mitre.org/data/definitions/400.html[CWE-400: Uncontrolled Resource Consumption]

|=== 

=== Description

This SAST policy detects uncontrolled resource consumption vulnerabilities in Python code. It specifically looks for instances where the `requests` library is used without a timeout parameter, or with a default timeout value set to `None`. This can cause the program to hang indefinitely if the request takes an unexpectedly long time to complete.

Vulnerable code example:

[source,python]
----
import requests

response = requests.get('https://api.example.com/data')
----

In the above example, the `requests.get()` function is called without specifying a timeout. This means that if the request takes a long time to complete or encounters an error, the program will wait indefinitely without timing out.

=== Fix - Buildtime

To fix this issue, you should always include a reasonable timeout value when making requests. This ensures that the program doesn't hang indefinitely and can handle unexpected delays. Here's an example of how to securely make the request:

Secure code example:

[source,python]
----
import requests

response = requests.get('https://api.example.com/data', timeout=5)
----

In the secure code example, a timeout value of 5 seconds is specified for the `requests.get()` function call. This means that if the request takes longer than 5 seconds to complete, an exception will be raised and the program will continue executing.
    