== Insecure use of no password or weak password when connecting to a database

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| eedadf8a-2ce2-404a-8859-5ce77756031f

|Checkov ID 
|CKV3_SAST_71

|Severity
|CRITICAL

|Subtype
|Build

|Language
|Python

|CWEs
|https://cwe.mitre.org/data/definitions/521.html[CWE-521: Weak Password Requirements]

|OWASP Categories
|https://owasp.org/www-project-top-ten/2017/A7_2017-Identification_and_Authentication_Failures[A7:2021 - Identification and Authentication Failures]

|=== 

=== Description

Database connections should always be secured with robust authentication mechanisms. When connecting to databases, applications must use strong and unique passwords to prevent unauthorized access. Our analysis detected database connections that either misuse a password or use an empty password. This practice is highly insecure and can expose sensitive data to potential attackers.

For example:

[source,python]
----
# Vulnerable code snippet
import mysql.connector

connection = mysql.connector.connection.MySQLConnection(user='admin', password='')
----

=== Fix - Buildtime

To remediate this issue:

1. Always use strong, unique passwords when connecting to databases. Do not rely on default or easily guessable passwords.
2. Do not hard-code database passwords in your source code. Use environment variables, secrets management tools, or encrypted configuration files to handle database credentials.
3. Periodically rotate database passwords to minimize risks associated with password leaks or breaches.

A safer approach:

[source,python]
----
# Recommended code snippet
import os
import mysql.connector

# Get database password from an environment variable or secure config
DB_PASSWORD = os.environ.get('DB_PASSWORD')

connection = mysql.connector.connection.MySQLConnection(user='admin', password=DB_PASSWORD)
----

Ensuring strong authentication for database connections is a fundamental step in maintaining the security of both the application and the underlying data.
