== Encryption algorithms used with an insecure mode or padding

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7e0e8097-68a8-4ab7-b5ba-c01fc77cec9d

|Checkov ID 
|CKV3_SAST_59

|Severity
|HIGH

|Subtype
|Build

|Language
|Python

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
|https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration[A02:2021 - Cryptographic Failures]

|=== 

=== Description

Ensuring robust encryption is crucial to maintain data confidentiality. This policy highlights instances where vulnerable encryption algorithms are employed. Specifically, the use of algorithms like RC2 and DES is discouraged due to their inherent vulnerabilities and diminishing strength against modern computational power.

For example:

[source,python]
----
# Vulnerable usage of Cryptodome's ARC2
from Cryptodome.Cipher import ARC2
cipher = ARC2.new(YOUR_KEY)

# Vulnerable usage of DES
from Crypto.Cipher import DES
cipher = DES.new(YOUR_KEY)
----

=== Fix - Buildtime

To prevent potential cryptographic vulnerabilities:

1. Refrain from using deprecated or insecure cryptographic algorithms, such as RC2 and DES.
2. Migrate to secure algorithms like AES, which offers superior encryption strength and is widely adopted as an industry standard.
3. Regularly audit and update cryptographic libraries and methods to align with updated security practices and recommendations.

Here's how you can transition to a more secure encryption algorithm:

[source,python]
----
# Recommended usage of AES
from Cryptodome.Cipher import AES
cipher = AES.new(YOUR_KEY)
----

Properly employing encryption is paramount for ensuring the integrity and confidentiality of data. Stay vigilant and regularly update cryptographic practices in accordance with modern security standards.
