== Weak SSL/TLS protocol used

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4f408359-5568-4013-b8ba-e2c92562ad29

|Checkov ID 
|CKV3_SAST_68

|Severity
|HIGH

|Subtype
|Build

|Language
|Python

|CWEs
a|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Inadequate Encryption Strength]

https://cwe.mitre.org/data/definitions/326.html[CWE-326: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
a|https://owasp.org/www-project-top-ten/2017/A2_2017-Security_Misconfiguration[A2:2021 - Cryptographic Failures]

https://owasp.org/www-project-top-ten/2017/A7_2017-Identification_and_Authentication_Failures[A7:2021 - Identification and Authentication Failures]

|=== 

=== Description

Robust encryption and decryption mechanisms are critical to ensuring data confidentiality and preventing unauthorized access. However, the use of insecure or outdated encryption algorithms can jeopardize these security goals. Specifically, the use of insecure TLS protocol versions exposes encrypted data to several risks and vulnerabilities.

In the codebase under scrutiny, configurations using insecure or deprecated encryption algorithms have been observed. These practices compromise the security of encrypted data, potentially making it susceptible to decryption by malicious actors.

For instance:

[source,python]
----
# Utilizing cryptography with insecure configurations
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
vector = b'0' * 16
cipher = Cipher(algorithms.AES(b'YourKey'), modes.CBC(vector))
cipher.encryptor()
----

=== Fix - Buildtime

To ensure that encryption remains secure:

1. Shift to using secure and updated encryption algorithms.
2. Do not use insecure configurations such as ECB mode or insecure initial vector patterns.
3. Frequently review and update your encryption configurations to align with modern security best practices.

A recommended configuration:

[source,python]
----
# Use cryptography with AES in a more secure configuration
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
vector = os.urandom(16)  # Generate a random initialization vector
cipher = Cipher(algorithms.AES(b'YourKey'), modes.CBC(vector))
cipher.encryptor()
----

Always ensure the confidentiality and security of encrypted data by adopting up-to-date encryption methodologies and algorithms.
