== Improper logger configuration

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| dea8b4c8-bf5b-4d0a-977b-66c5058526e5

|Checkov ID 
|CKV3_SAST_57

|Severity
|MEDIUM

|Subtype
|Build

|Language
|Python

|CWEs
a|https://cwe.mitre.org/data/definitions/117.html[CWE-117: Improper Output Neutralization for Logs]

https://cwe.mitre.org/data/definitions/532.html[CWE-532: Insertion of Sensitive Information into Log File]

|OWASP Categories
|https://owasp.org/www-project-top-ten/A09_2017-Using_Components_with_Known_Vulnerabilities[A09:2021 - Security Logging and Monitoring Failures]

|=== 

=== Description

Loggers, when configured improperly, can pose several security risks. These risks include the unintentional logging of sensitive data, uncontrolled log data growth which might be exploited for a Denial of Service (DoS) attack, and even log forging. A logger, essentially, is a double-edged sword, which, if used properly, can serve as an invaluable tool for monitoring and diagnosing issues but, if misused, can lead to security vulnerabilities.

When logging configurations are mismanaged:

1. Sensitive information can be unintentionally logged, exposing passwords, API keys, or PII.
2. Log forging can occur, where attackers insert malicious log entries.
3. Logs can be disabled, preventing the capture of critical security events.

The observed codebase shows instances where loggers are potentially misconfigured or utilized in a way that could introduce security vulnerabilities.

For example, care should be taken with:

[source,python]
----
# Avoid disabling logging entirely
logging.disable()

# Be cautious when configuring basic logging without proper format and level
logging.basicConfig()
----

=== Fix - Buildtime

To maintain secure and effective logging:

1. Always define a logging format that doesn't expose sensitive information.
2. Ensure the logging level is set to an appropriate level for the environment (e.g., `DEBUG` might be suitable for development, but not production).
3. Avoid disabling logging entirely; it's crucial for detecting and responding to security incidents.
4. Regularly review logging configurations and custom logging classes, handlers, or filters to ensure they align with security best practices.

For a robust logging configuration in a Python application:

[source,python]
----
import logging

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# Create and configure a logger instance
logger = logging.getLogger(__name__)
----

This setup ensures that logs include essential metadata and don't inadvertently expose sensitive information. Properly configured logs are a critical component of a robust security posture.
