== Windows hosts

//'''
//
//title: Windows hosts
//type: single
//url: "/saas/start/enforcer/windows/"
//weight: 50
//menu:
//  saas:
//    parent: "deploy-enforcer"
//    identifier: "windows-enforcer"
//canonical: https://docs.aporeto.com/saas/start/enforcer/windows/
//
//'''

=== About Windows host installs

To deploy the enforcer to a Windows host, use one of the following procedures.

* *<<_cloud-install,Cloud install>>*: uses a short-lived token from AWS, GCP, or Azure to install, register, and connect the enforcer to the Microsegmentation Console.
Many of our customers complete this procedure once and make an image of the machine that has the enforcer installed.
* *<<_on-premise-install,On-Premise install>>*: requires a xref:../../concepts/app-cred-token.adoc[Microsegmentation token] to install.
Once installed, the enforcer uses a least-privilege xref:../../concepts/app-cred-token.adoc[app credential] to register and connect to the Microsegmentation Console.

[.task]
[#__cloud-install]
=== Cloud install

[.procedure]
. Ensure that you meet the following prerequisites.
+
[cols="1,1a"]
|===
|Entity |Requirement

|Target host
|
* xref:../reqs.adoc[Meets the system requirements]
* Set up to synchronize time with authoritative sources: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[AWS], https://cloud.google.com/compute/docs/instances/configure-ntp[GCP], https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync[Azure]
* Can connect to `+*.aporeto.com+`, `+*.prismacloud.io+`, and `+*.network.prismacloud.io+`

|Local host
|
* xref:../install-apoctl.adoc[`apoctl` installed]

|Privileges
|
* `namespace.administrator` privileges in the target Microsegmentation namespace
* Administrator access to the target instance

| Cloud credentials
|
* _AWS_: https://aws.amazon.com/blogs/security/easily-replace-or-attach-an-iam-role-to-an-existing-ec2-instance-by-using-the-ec2-console/[an IAM role attached to the target host] with read-only access to tags (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policy-structure.html[`ec2:DescribeTags`])
* _GCP_: https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[GCP service account attached to the target host]
* _Azure_: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vmss[target host assigned a managed identity]
|===

. Construct a xref:../../concepts/tags-and-identity.adoc[Microsegmentation tag] that identifies your cloud account, project, tenant, or organization.
The tag must begin with `@auth:` followed by a key-value pair.
Refer to the table below for some common examples.
+
[cols="1,1,1,1"]
|===
| Cloud provider | Value | Microsegmentation tag syntax | Microsegmentation tag example

|AWS
|AWS account ID^1^                    | `@auth:account=<AWS_ACCOUNT_ID>`    | `@auth:account=942613894219`

|GCP
|GCP project ID
|`@auth:projectid=<GCP_PROJECT_ID>`
|`@auth:projectid=acme-dev`

|Azure
|Microsoft tenant ID^2^
|`@auth:tenantid=<TENANT_ID>`
|`@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7`

|GCP and Azure
|Name of organization
|`@auth:organization=<ORGANIZATION>`
|`@auth:organization=acme`
|===
+
* ^1^ You can find your AWS account ID under *My security credentials* in the AWS Management Console.
* ^2^ To learn how to find your tenant ID, refer to the https://techcommunity.microsoft.com/t5/Office-365/How-do-you-find-the-tenant-ID/td-p/89018[Microsoft documentation].

. On your local host, set a `CLOUD_ID_TAG` environment variable containing the Microsegmentation tag you've constructed to identify authorized enforcers.
If the target virtual machine is hosted on AWS, also set an `AWS_IAM_ROLE` environment variable containing the name of the IAM role attached to the instance prepended with `@auth:rolename=`.
See below for examples.
+
* Windows local host:
+
AWS
+
[,powershell]
----
$env:CLOUD_ID_TAG="@auth:account=942613894219"
$env:AWS_IAM_ROLE="@auth:rolename=aporeto"
----
+
GCP
+
[,powershell]
----
$env:CLOUD_ID_TAG="@auth:projectid=acme-dev"
----
+
Azure
+
[,powershell]
----
$env:CLOUD_ID_TAG="@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7"
----
+
* macOS/Linux local host:
+
AWS
+
[,console]
----
export CLOUD_ID_TAG="@auth:account=942613894219"
export AWS_IAM_ROLE="@auth:rolename=aporeto"
----
+
GCP
+
[,console]
----
export CLOUD_ID_TAG="@auth:projectid=acme-dev"
----
+
Azure
+
[,console]
----
export CLOUD_ID_TAG="@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7"
----

. Set a `TARGET_NS` environment variable containing the Microsegmentation namespace of this enforcer.
It should be a grandchild namespace.
+
Windows
+
[,powershell,subs="+attributes"]
----
$env:TARGET_NS="/{parent-ns}/{child-ns}/vm1"
----
+
macOS/Linux
+
[,console,subs="+attributes"]
----
export TARGET_NS=/{parent-ns}/{child-ns}/vm1
----

. Use one of the following commands to create an API authorization that allows the enforcer to access the Microsegmentation Console.
Select the tab that corresponds to the cloud provider of the target host and whether or not you are using the optional mapping.
+
* Windows local host
+
AWS
+
[,powershell]
----
Set-Content -Path enf-api-auth.yml -Value @"
APIVersion: 0
label: ec2-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $($env:TARGET_NS)
     authorizedSubnets: []
     name: Authorize EC2 enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=awssecuritytoken"
         - "$($env:AWS_IAM_ROLE)"
         - "$($env:CLOUD_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f enf-api-auth.yml }
----
+
GCP
+
[,powershell]
----
Set-Content -Path enf-api-auth.yml -Value @"
APIVersion: 0
label: gcp-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $($env:TARGET_NS)
     authorizedSubnets: []
     name: Authorize GCP enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=gcpidentitytoken"
         - "$($env:CLOUD_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f enf-api-auth.yml }
----
+
Azure
+
[,powershell]
----
Set-Content -Path enf-api-auth.yml -Value @"
APIVersion: 0
label: azure-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $($env:TARGET_NS)
     authorizedSubnets: []
     name: Authorize Azure enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=azureidentitytoken"
         - "$($env:CLOUD_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f enf-api-auth.yml }
----
+
* macOS/Linux local host:
+
AWS
+
[,console]
----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: ec2-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $TARGET_NS
     authorizedSubnets: []
     name: Authorize EC2 enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=awssecuritytoken"
         - "$AWS_IAM_ROLE"
         - "$CLOUD_ID_TAG"
EOF
----
+
GCP
+
[,console]
----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: gcp-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $TARGET_NS
     authorizedSubnets: []
     name: Authorize GCP enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=gcpidentitytoken"
         - "$CLOUD_ID_TAG"
EOF
----
+
Azure
+
[,console]
----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: azure-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $TARGET_NS
     authorizedSubnets: []
     name: Authorize Azure enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=azureidentitytoken"
         - "$CLOUD_ID_TAG"
EOF
----

. Retrieve the URL of your Microsegmentation Console API.
+
Windows
+
[,powershell]
----
echo $Env:MICROSEG_API
----
+
macOS/Linux
+
[,console]
----
echo $MICROSEG_API
----

. Access the target host, such as via https://www.microsoft.com/en-us/p/microsoft-remote-desktop/9wzdncrfj3ps?activetab=pivot:overviewtab[Microsoft Remote Desktop].

. Set a `MICROSEG_API` environment variable containing the URL of your Microsegmentation Console API that you just echoed on your local host.
+
[,powershell,subs="+attributes"]
----
$env:MICROSEG_API="https://{ctrl-plane-api-url}"
----

. Confirm that the host can connect to the Microsegmentation Console API and trusts its certificate.
+
[,powershell]
----
Invoke-WebRequest -URI $($env:MICROSEG_API)
----

. Set a `TARGET_NS` environment variable containing the Microsegmentation namespace of this enforcer.
It should be a grandchild namespace.
+
[,console,subs="+attributes"]
----
$env:TARGET_NS="/{parent-ns}/{child-ns}/vm1"
----

. Download the `apoctl` MSI to the target host and execute it in quiet mode.
+
[,powershell,subs="+attributes"]
----
curl {download-url}{version}/apoctl/windows/apoctl.msi -o apoctl.msi; `
if ($?) {. .\apoctl.msi /quiet}
if ($?) {$env:PATH+="C:\Program Files\Apoctl;"}
----

. Use the following command to install the enforcer.
+
[,powershell,subs="+attributes"]
----
 apoctl enforcer install windows --auth-mode cloud `
                                 --namespace $($env:TARGET_NS) `
                                 --api $($env:MICROSEG_API) `
                                 --repo {repo-url}{version}/windows/prisma-enforcer.msi
----
+
[TIP]
====
Refer to <<_enforcer-configuration-options,Enforcer configuration options>> if you wish to modify the enforcer's default settings.
You can also run `apoctl enforcer install windows -h` to review its flags.
You can find more information about the `enforcer install windows` command in the xref:../../apoctl/apoctl.adoc[`apoctl` reference page].
====

. Open the {console-web-interface}, select *{agent-enforcer}* under *Manage*, and navigate to the enforcer's namespace.
You should find your enforcer listed with a status of *connected*.
Click the enforcer and review its metadata.

. Select {platform-app-dep-map} in the side navigation menu.
You should see your host as a processing unit, with a dashed green line to a `Somewhere` external network.
Your host is in discovery mode.

. Return to your Remote Desktop session.

. Uninstall `apoctl`, remove the `apoctl.msi` file, and remove the `.apoctl` directory.
+
[,powershell]
----
 Start-Process msiexec.exe -ArgumentList '/x apoctl.msi /quiet' -Wait ; `
 if($?) {rm 'apoctl.msi'} ; `
 if($?) {rm '.apoctl' -r -fo}
----

. Refer to xref:../../secure/hosts.adoc[Securing host communications] to learn how to allow the desired traffic and disable discovery mode.

[.task]
[#_on-premise-install]
=== On-premise install

[.procedure]
. Make sure you meet the following prerequisites.
+
[cols="1,3a"]
|===
| Entity | Requirement

|Target host(s)
|
* xref:../reqs.adoc[Meets the system requirements]
* https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings[Set up to synchronize time with authoritative sources]
* https://curl.haxx.se/[curl] installed
* Can connect to the Microsegmentation Console API without TLS interception
* Can connect to `+*.aporeto.com+`, `+*.prismacloud.io+`, and `+*.network.prismacloud.io+`

|Local host
|
* xref:../install-apoctl.adoc[`apoctl` installed]

|Privileges
|
* `namespace.administrator` privileges in the Microsegmentation namespace of the target host
* Administrator access to the target host
|===

. From your local host, generate a short-lived Microsegmentation token that the enforcer can exchange for an app credential.
You can set a variety of restrictions on this token.
If you're in a hurry, just copy and paste the minimally restricted example below.
The other tabs illustrate optional additional restrictions, such as requiring the enforcer to register in a specified namespace or make its request from a specific subnet.
+
* macOS/Linux local host
+
Minimally restricted example
+
[,console]
----
apoctl auth appcred --path ~/.apoctl/default.creds \
                    --restrict-role @auth:role=enforcer \
                    --restrict-role @auth:role=enforcer-installer \
                    --validity 60m
----
+
Fully restricted example
+
[,console,subs="+attributes"]
----
apoctl auth appcred --path ~/.apoctl/default.creds \
                    --restrict-role @auth:role=enforcer \
                    --restrict-role @auth:role=enforcer-installer \
                    --validity 60m \
                    --restrict-namespace /{parent-ns}/{child-ns}/vm1 \
                    --restrict-network 10.0.0.0/8
----
+
Syntax
+
[,console]
----
apoctl auth appcred --path <app-credential-file> \
                    --restrict-role @auth:role=enforcer \
                                    @auth:role=enforcer-installer \
                    --validity <golang-duration> \
                    [--restrict-namespace <namespace>] \
                    [--restrict-network <cidr>]
----
+
* Windows local host
+
Minimally restricted example
+
[,powershell]
----
apoctl auth appcred --path '.apoctl/default.creds' `
                    --restrict-role @auth:role=enforcer `
                    --restrict-role @auth:role=enforcer-installer `
                    --validity 60m
----
+
Fully restricted example
+
[,powershell,subs="+attributes"]
----
apoctl auth appcred --path '.apoctl/default.creds' `
                    --restrict-role @auth:role=enforcer `
                    --restrict-role @auth:role=enforcer-installer `
                    --validity 60m `
                    --restrict-namespace /{parent-ns}/{child-ns}/vm1 `
                    --restrict-network 10.0.0.0/8
----
+
Syntax
+
[,powershell]
----
apoctl auth appcred --path <app-credential-file> `
                    --restrict-role @auth:role=enforcer `
                                    @auth:role=enforcer-installer `
                    --validity <golang-duration> `
                    [--restrict-namespace <namespace>] `
                    [--restrict-network <cidr>]
----

. Retrieve the URL of your Microsegmentation Console API.
+
macOS/Linux
+
[,console]
----
echo $MICROSEG_API
----
+
Windows
+
[,powershell]
----
echo $Env:MICROSEG_API
----

. Access the target host, such as via https://www.microsoft.com/en-us/p/microsoft-remote-desktop/9wzdncrfj3ps?activetab=pivot:overviewtab[Microsoft Remote Desktop].

. Set a `TOKEN` environment variable containing the token you just generated.
We've truncated the example token value below for readability.
+
[,powershell]
----
$env:TOKEN="eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsbSI6IkNlcnRpZmljYXRlIiwiZGF0YSI6eyJjb21tb25O...."
----

. Set a `MICROSEG_API` environment variable containing the URL of your Microsegmentation Console API.
You can copy and paste this value from your local host terminal where you just echoed it.
+
[,powershell,subs="+attributes"]
----
$env:MICROSEG_API="https://{ctrl-plane-api-url}"
----

. Confirm that the host can connect to the Microsegmentation Console API and trusts its certificate.
+
[,powershell]
----
Invoke-WebRequest -URI $($env:MICROSEG_API)
----

. Set a `TARGET_NS` environment variable containing the Microsegmentation namespace of this enforcer.
It should be a grandchild namespace.
+
[,powershell,subs="+attributes"]
----
$env:TARGET_NS="/{parent-ns}/{child-ns}/vm1"
----

. Download the `apoctl` MSI to the target host and execute it in quiet mode.
+
[,powershell,subs="+attributes"]
----
curl {download-url}{version}/apoctl/windows/apoctl.msi -o apoctl.msi; `
if ($?) {. .\apoctl.msi /quiet}
if ($?) {$env:PATH+="C:\Program Files\Apoctl;"}
----

. Use the following command to install the enforcer.
+
[,powershell,subs="+attributes"]
----
 apoctl enforcer install windows --token $($env:TOKEN) `
                                 --auth-mode appcred `
                                 --namespace $($env:TARGET_NS) `
                                 --api $($env:MICROSEG_API) `
                                 --repo {repo-url}{version}/windows/prisma-enforcer.msi
----
+
[TIP]
====
Refer to <<_enforcer-configuration-options,Enforcer configuration options>> if you wish to modify the enforcer's default settings.
You can also run `apoctl enforcer install windows -h` to review its flags.
You can find more information about the `enforcer install windows` command in the xref:../../apoctl/apoctl.adoc[`apoctl` reference page].
====

. Open the {console-web-interface}, select *{agent-enforcer}* under *Manage*, and navigate to the enforcer's namespace.
You should find your enforcer listed with a status of *connected*.
Click the enforcer and review its metadata.

. Select {platform-app-dep-map} in the side navigation menu.
You should see your host as a processing unit, with a dashed green line to a `Somewhere` external network.
Your host is in discovery mode.

. Return to your Remote Desktop session.

. Uninstall `apoctl`, remove the `apoctl.msi` file, remove the `.apoctl` directory, and clear the `TOKEN` variable.
+
[,powershell]
----
 Start-Process msiexec.exe -ArgumentList '/x apoctl.msi /quiet' -Wait ; `
 if($?) {rm 'apoctl.msi'} `
 if($?) {$env:TOKEN=""} ; `
 if($?) {rm '.apoctl' -r -fo}
----

. Refer to xref:../../secure/hosts.adoc[Securing host communications] to learn how to allow the desired traffic and disable discovery mode.

[#_enforcer-configuration-options]
=== Enforcer configuration options

The enforcer exposes the following configuration options at startup.
To modify the configuration of a running enforcer, you must restart it.
To modify the enforcer's tags, you have to also delete the enforcer object from the Microsegmentation Console.

You can modify the default configuration by passing the flags with `apoctl enforcer install linux` as the value of `--raw-flags`.
Example: `apoctl enforcer install linux --raw-flags "--log-level=debug --log-format=human --log-to-console=true"`

[cols="1,2"]
|===
| enforcer flag | Description

| `--activate-control-plane-pus`
| Pass this flag if you wish to recognize the Microsegmentation Console as a processing unit, allowing its communications to be monitored and controlled. By default, the enforcer ignores them.

| `--api`
| The URL of the Microsegmentation Console API.

| `--api-cacert`
| Path to CA certificate.

| `--api-skip-verify`
| Disables check on certificate signature as trusted.

| `--appcreds`
| Path to application credentials.

| `--application-proxy-port`
| Start of the port range for ports used by the enforcer application proxy. Defaults to 20992. You may adjust this if you experience conflicts.

| `--cloud-probe-timeout`
| The enforcer can determine if it is running in a cloud environment, such as AWS, GCP, or Azure. This is the maximum amount of time to wait for these internal probes to complete. Defaults to two seconds: `2s`

| `--disable-dns-proxy`
| Pass this flag to disable the enforcer DNS proxy, which allows policies to be written based on FQDN, in cases where an exact IP address may be unpredictable.

| `--dns-server-address`
| DNS server address or CIDR that is observed by the enforcer DNS proxy. Defaults to `0.0.0.0/0`.

| `--enable-ebpf`
| (*Beta*) Pass this flag to gain performance improvements by using extended Berkeley Packet Filter (eBPF) on systems that support it.

| `--enable-ipv6`
| (*Beta*) The enforcer ignores IPv6 communications by default. If you have IPv6 enabled and wish to monitor and control these connections, pass this flag.

| `--log-level`
| Quantity of logs that the enforcer should generate. Defaults to `info`. Alternatively, you can set it to `debug`, `trace`, or `warn`.

| `--log-to-console`
| Controls whether the enforcer's logs are written to stdout. Boolean that defaults to `false`.

| `--namespace`
| The Microsegmentation namespace the enforcer should register in.

| `--tag`
| Microsegmentation tag for this enforcer

| `--token`
| Microsegmentation token for the enforcer to use to register to the Microsegmentation Console.

| `--working-dir`
| A persistent working directory with write, read, and execute permissions. Files such as logs are stored here. Defaults to `%PROGRAMDATA%\enforcerd`
|===
