== Instances with scheduled reboots are not rescheduled or manually rebooted


=== Description 


AWS periodically schedules system maintenance that requires an EC2 instance to be rebooted or migrated.
These events are scheduled and will occur automatically.
We recommend you reschedule the event at a time convenient to you, or you manually reboot an instance and forego the scheduled event.
EBS-backed instances can safely be rebooted.
Instance reboots at the default scheduled time are likely to cause some type of availability blip, depending on the particular instance.

[WARNING]
====
Stopping or rebooting an instance-store-backed EC2 instance will cause the contents of the volume to be lost. Instance store volumes must be migrated to a new instance prior to being stopped.
====
See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-instances-status-check_sched.html#types-of-scheduled-events[the AWS docs] for a full description of the different types of scheduled maintenance.

=== Fix - Runtime


*AWS Console* 


*Viewing Scheduled Events*

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Navigate to the https://console.aws.amazon.com/ec2/[Amazon EC2 console].

. Choose *Events* from the navigation pane to view instances with scheduled events.
+
*Rescheduling Events* To choose a new time for a scheduled event, perform the following steps.
+
Note that not all event types can be rescheduled.

. Navigate to the https://console.aws.amazon.com/ec2/[Amazon EC2 console].

. Choose *Events* from the navigation pane to view instances with scheduled events.

. Filter and select one or more instances.

. Choose *Actions* \-> *Schedule event*

. Select a new date and time prior to the event deadline, and click *Save*.
+
*Rebooting an Instance* You can reboot an instance to remove the scheduled event.
+
Note that only EBS-backed instances can be rebooted without data loss.

. Navigate to the https://console.aws.amazon.com/ec2/[AWS EC2 console].

. Navigate to the *Instances* page.

. Select the instance to reboot.

. Select *Actions* \-> *Instance state* \-> *Reboot instance*.


*CLI Command* 


s
View instances with `instance-reboot` or `system-reboot` events (add the `--region` argument if needed):


[source,shell]
----
{
  "codes": [
    {
      "code": "aws ec2 describe-instance-status
--filters Name=event.code,Values=instance-reboot,system-reboot",
      "language": "shell"
    }
  ]
}
----
Schedule an event:


[source,shell]
----
{
  "codes": [
    {
      "code": "aws ec2 modify-instance-event-start-time
--instance-id i-1234567890abcdef0
--instance-event-id instance-event-0d59937288b749b32
--not-before 2019-03-25T10:00:00.000",
      "language": "shell"
    }
  ]
}
----
Reboot an instance (warning: ensure data on non-EBS storage is backed up or migrated): `aws ec2 reboot-instances --instance-ids i-1234567890abcdef0`
