== Neptune storage is not securely encrypted


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8244ecf5-3dad-400a-ba71-3b5162ede0f7

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/NeptuneClusterStorageEncrypted.py[CKV_AWS_44]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Amazon Neptune is a fully managed graph database service for building and running applications that work with connected datasets.
Neptune supports graph query languages such as Apache TinkerPop Gremlin and W3C's SPARQL.
Neptune also supports recommendation engines, fraud detection, knowledge graphs, drug discovery, and network security.
Encryption of Neptune storage protects data and metadata against unauthorized access.
It also fulfils compliance requirements for data-at-rest encryption of production file systems.
Encryption for an existing database cannot be added or changed after it is created.

////
=== Fix - Runtime


* AWS Console* 


To change the policy using the AWS Console, follow these steps:

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the * https://console.aws.amazon.com/neptune/ [Amazon Neptune console]*.

. To start the Launch DB instance wizard, click * Launch DB Instance*.

. To customize the settings for your Neptune DB cluster, navigate to the * Specify DB details* page.

. To enable encryption for a new Neptune DB instance, navigate to the * Enable encryption* section on the Neptune console and click * Yes*.


* CLI Command* 


To creates a new Amazon Neptune DB cluster:


[source,shell]
----
{
  "codes": [
    {
      "code": "  create-db-cluster
\t--db-cluster-identifier & lt;value>
\t--engine & lt;value>
\t--storage-encrypted true",
      "language": "shell"
    }
  ]
}
----
////

=== Fix - Buildtime


*Terraform* 


* *Resources:* aws_neptune_cluster
* *Arguments*: storage_encrypted - (Optional) Specifies whether the Neptune cluster is encrypted.
The default is false if not specified.


[source,go]
----
{
  "codes": [
    {
      "code": "resource "aws_neptune_cluster" "example" {
  ...
  cluster_identifier                  = "neptune-cluster-demo"
+ storage_encrypted                   = true
  ...
}",
      "language": "go",
      "name": "aws_neptune_cluster"
    }
  ]
}
----


*CloudFormation* 


* *Resources:* AWS::Neptune::DBCluster
* *Arguments*: Proprties.StorageEncrypted


[source,yaml]
----
{
  "codes": [
    {
      "code": "Type: "AWS::Neptune::DBCluster"
    Properties:
      ...
+     StorageEncrypted: true",
      "language": "yaml"
    }
  ]
}
----
