== Cloud Identity Inventory

Prisma Cloud surfaces detailed information on IAM access in your cloud environment to give you greater visibility. AWS users can currently access the following IAM access data in Prisma Cloud:

[cols="30%a,70%a"]
|===

|Role

|Trust relationships -  Lists resources or services assigned to a role, includes last access permission data

Policies - Lists policies attached to the role and last access information

Trusted Entities - User, Role, SAML Provider, OIDC Provider, Lambda function, ECS, IDP - No Link 

Granted Policies - Managed and Inline

|Group

|Group membership -  Lists users assigned to the group and last access information for users 

Policies - Lists policies associated with the group and last access information

Granted Policies - Managed and Inline

|Policy

|Role specific - Lists roles associated with a policy and last access data 

Group specific - Lists groups associated with a policy and last access information 

Resource specific - Lists resources (users) directly attached to the policy and last access data

|===