[#id20a580e1-91ce-46c7-b89d-57e04b41ced0]
== Prisma Cloud IAM Security

//Learn about how Prisma Cloud enables Cloud Infrastructure Entitlement Management (CIEM).

Prisma Cloud IAM Security is the Cloud Infrastructure Entitlement Management (CIEM) offering that helps you address the security challenges of managing IAM in cloud environments. Prisma Cloud IAM security capabilities automatically calculate effective permissions across cloud service providers, detect overly permissive access, and suggest corrections to reach least privilege entitlements. It includes out-of-the-box (default) policies that govern IAM best practices to help you identify risky permissions and get to the ideal set of privileges for your deployment.

Because Prisma Cloud can correlate identity information with configuration data, it gives you the depth of visibility and control. For example, if you use the AWS S3 storage service, the Prisma Cloud Data Security module can discover and identify sensitive data, the CSPM capability can calculate true Internet exposure, and the CIEM capability can provide granular insights into exactly who has access to the data and make appropriate recommendations to enforce least-privilege access.

* xref:what-is-prisma-cloud-iam-security.adoc[What is Prisma Cloud IAM Security]
* xref:enable-iam-security.adoc[Enable IAM Security]
* xref:investigate-iam-incidents-on-prisma-cloud.adoc[Investigate IAM Incidents on Prisma Cloud]
* xref:create-an-iam-policy.adoc[Create an IAM Policy]
* xref:integrate-prisma-cloud-with-idp-services.adoc[Integrate Prisma Cloud with IdP Services]
* xref:remediate-alerts-for-iam-security.adoc[Remediate Alerts for IAM Security]
* xref:context-used-to-calculate-effective-permissions.adoc[Context Used to Calculate Effective Permissions]