== Prisma Cloud Host, Container, Virtual Machine, and Serverless Function Support

Prisma Cloud supports the full stack and lifecycle of your cloud native
workloads. With Prisma Cloud, you can protect mixed workload environments.
Whether you're running standalone hosts, containers, serverless
functions, or any combination of the above, Prisma Cloud allows you to
manage your environment with a single interface across the entirety of
the lifecycle -- from development to runtime.

Prisma Cloud protects the hosts you're working with, whether you are using
a linux variant or using Windows Server 2016, and the applications they
run.

Prisma Cloud can also protect your serverless functions and applications on
AWS Fargate. As you look to move beyond using containers and identify
workloads that can be run as functions, Prisma Cloud can protect and report
on these functions alongside your other workloads regardless of cloud
service provider. Finally, Prisma Cloud supports the Docker and OCI
compatible container runtimes, as well as any functions you may run
across any platform.
