== Upcoming breaking changes in the H1Y21 release

This article outlines important upcoming changes to the API in the next release of Prisma Cloud Compute.

The current release is 20.12 (code-named Galileo).

The next release (code-named Hamilton) is scheduled to ship in H1Y21.


=== Compliance stats

A new compliance dashboard will be introduced.
It will simplify compliance visibility across regulations, CIS benchmarks, and policy rules.

As a result of this enhancement, the endpoint that provides the compliance statistics for the dashboard will change to include new metrics and data.
The impacted endpoint is `/api/v1/stats/compliance`.
It will add the following data:

* Compliance rate by each regulation, CIS benchmark, and policy rule.
* Trend of failed compliance checks over time.
* List of all compliance checks with their compliance rate.

The data currently provided by this endpoint will no longer be available.

In addition, a new endpoint will be added: `api/v1/stats/compliance/download`.
This endpoint will let you get a list of all compliance checks in CSV format.


=== Serverless scaninng scope settings

The mechanism for specifying the serverless scanning scope will be improved.
You will be able to set scopes per account rather than specifying a scope for each region in the account.

As a result of this enhancement, the ServerlessScanSpecification schema will change as follows:

* Region and Pattern will be removed.
* Multiple credential IDs will be supported.

In addition, the method for `POST api/v1/settings/serverless-scan` will change from POST to PUT to align with the way PUT works for other similar endpoints in the product.
The current POST method completely replaces all scanning scopes.
In the next release, the PUT method will be used to replace all scanning scopes.
A new POST method will be added.
The POST method will let you add a single serverless scan spec without sending an aggregated list of all specs each time you add a new spec.


=== Custom rules

The route path for `api/v1/policies/runtime/custom-rules` will change to `api/v1/custom-rules`.


=== twistcli output file

The schema of the JSON output file exported from twistcli images scanning will be stabilized.
The purpose of this enhancement is to ensure backward compatibility of the schema in future releases.

Some new fields will be added to the schema and some existing fields will be adjusted as follows:

* `results.vulnerabilities.riskFactors` - Will change from key:value array to strings array
* `results.vulnerabilities.publishedDays` - Will change from the number of days since published date to the published date itself.
The new name of the field will be `publishedDate`.
* `results.vulnerabilities.discoveredDays` - Will change from the number of days since discovered date to the discovered date itself.
The new name of the field will be `discoveredDate`.
