== Security Group attached to application load balancer instance allows inbound traffic from all to TCP 27018 (MongoDB)


*Description* 


TCP port 27018 is used by the MongoDB Database, a free and open-source cross-platform document-oriented NoSQL database.
We recommend all Mongo DBs should be protected with an access control mechanism to prevent data theft and data loss.
Allowing unrestricted MongoDB Database access can increase opportunities for malicious activity such as hacking, denial-of-service (DoS) attacks, and loss of data.

=== Fix - Runtime


*AWS Console* 



. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the http://console.aws.amazon.com/ec2/[Amazon EC2 console].

. In navigation on the left, select *Load Balancers*.

. Select the desired _load balancer_.

. Navigate to the *Security* section.

. Select the *Description* tab and take note of the security groups associated with the _load balancer_.

. In navigation on the left, select *Security Groups*.

. Search and select the _security groups_ from the previous step.

. Click the *Inbound* tab.

. To remove any references to TCP port 27018 (MongoDB), click *Edit*.
