== Get Started with OIDC 

Enable https://openid.net/developers/how-connect-works/[OpenID Connect (OIDC)] to allow administrators to configure their tenant, and allow users to sign in with their Identity Provider (IdP) credentials.

To avoid the risk of account lockout, we recommend enabling a couple of administrative users with both local authentication credentials on Prisma Cloud and SSO access so that they can log in to the administrative console and modify the SSO configuration if needed. Ensure that administrators have activated their Palo Alto Networks Customer Support Portal (CSP) account using the Welcome to Palo Alto Networks Support email and set a password to access the portal.

=== Prisma Cloud Steps 

Complete the steps below on the Prisma Cloud Console and your IdP to set up OIDC:

. Log in to Prisma Cloud using an account with System Admin privileges to configure SSO and redirect login requests to the IdP’s login page. Complete the following steps on your Prisma Cloud tenant:
.. Copy the Audience URI, for Prisma Cloud, which users need to access from the IdP.
.. Log in to Prisma Cloud and select menu:Settings[Access Control > SSO].
.. Copy the *Audience URI * value. This is a read-only field in the format that uniquely identifies your instance of Prisma Cloud. This value is required to configure OIDC on your IdP.
. Complete the setup on the IdP (Okta, Azure AD) as described in the next section.
. Add callback URI previously created on Prisma Cloud to the IdP.
. After set up is complete you will be able to login using your email address and authentication will be completed on your IdP. 


