== Get Started with OIDC 

https://openid.net/developers/how-connect-works/[OpenID Connect (OIDC)] is an open security protocol for authentication based on the OAuth 2.0 framework. Unlike SAML based SSO authentication, OIDC uses a Service Provider to authenticate users, allowing for faster set up and login times. OIDC offer a simplified, flexible method to authenticate human and machine identities and offers authentication support for applications and APIs.

Enable OIDC to allow users to log in to the Prisma Cloud administrative console using only their email and Prisma ID. Authentication is then completed on your Identity Provider (IdP) of choice. 

To avoid the risk of account lockout, we recommend enabling a couple of administrative users with both local authentication credentials on Prisma Cloud and SSO access so that they can log in to the administrative console and modify the SSO configuration if needed. Ensure that administrators have activated their Palo Alto Networks Customer Support Portal (CSP) account using the Welcome to Palo Alto Networks Support email and set a password to access the portal.

Administrative users accessing the Prisma cloud API cannot use OIDC and must authenticate using the the email address and password registered with Prisma Cloud.

=== First Steps 

Let's take a high level look at the steps you need to complete to set up OIDC:

. Log in to Prisma Cloud using an account with System Admin privileges to configure SSO and redirect login requests to the IdP’s login page. Complete the following steps on your Prisma Cloud tenant:

.. Start by making some choices on whether you would like to add Add Administrative Users On Prisma Cloud or add users on the fly with JIT Provisioning.
+
If you want to enable JIT provisioning for users, xref:../create-prisma-cloud-roles.adoc#id6d0b3093-c30c-41c4-8757-2efbdf7970c8[Create Prisma Cloud Roles] before you continue to the next step. When you configure SSO on the IdP, you must attach this role to the user‘s profile so that the user has the appropriate permissions and can monitor the assigned cloud accounts on Prisma Cloud.

.. Copy the Audience URI, for Prisma Cloud, which users need to access from the IdP.
+
... Log in to Prisma Cloud and select menu:Settings[Access Control > SSO].

... Copy the *Audience URI * value. This is a read-only field in the format that uniquely identifies your instance of Prisma Cloud. This value is required to configure OIDC on your IdP.
. Complete the setup on the IdP (Okta, Azure AD) as described in the next section.
. After set up is complete you will be able to login using your email address and authentication will be completed on your IdP. 


