== Set up OIDC on Okta

Create a New App (OIDC - OpenID Connect)


 

Application Type: Select Web application


Assignments / Controlled Access

Set according to the organization policy and Save application.

 

Create Prisma Cloud Config 

 

Config element

Where to find

How to apply

Client ID

General → Client Credentials

Use value of Client ID 

Client Secret

Generate a New Secret

Generate a new Client Secret and use value, be sure to note expiration (to create a scheduled refresh)

Issuer

Use “issuer” value from response to https://<okta tenant>/.well-known/openid-configuration

https://<okta tenant>

Auth URI

Use “authorization_endpoint” from response to https://<okta tenant>/.well-known/openid-configuration

 https://<okta tenant>/oauth2/v1/authorize

Token URI

Use “token endpoint” from response to https://<okta tenant>/.well-known/openid-configuration 

  https://<okta tenant>/oauth2/v1/token

JWK Set URI

Use “jwks uri” from response to https://<okta tenant>/.well-known/openid-configuration 

https://<okta tenant>/oauth2/v1/keys

Some of this data is available via: https://${tenant}/.well-known/openid-configuration (eg. https://panw-test.oktapreview.com/.well-known/openid-configuration)

 

After creating on Prisma Cloud side add callback URI to the IdP


 

