== Set up OIDC on Azure

Process of adding an OpenID application from the gallery
In the Azure portal, select Azure Active Directory.

The Azure Active Directory button
Go to Enterprise applications > All applications.

The Enterprise applications blade
 

Select New application on the top of the dialog box.

 

The New application button
Create Prisma Cloud Config

Some of this data is also available via:  https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

Config element

Where to find

How to apply

Config element

Where to find

How to apply

Client ID

AAD Registered Application → Overview

Use value of Application (client) ID under Essentials section

Client Secret

AAD Registered Application → Secrets and Certificates

Generate a new Client Secret and use value, be sure to note expiration (to create a scheduled refresh)

Issuer

 

https://login.microsoftonline.com/

Auth URI

 

https://login.microsoftonline.com/common/oauth2/v2.0/authorize 

Token URI

 

https://login.microsoftonline.com/common/oauth2/v2.0/token 

JWK Set URI

 

https://login.microsoftonline.com/common/discovery/keys

After creating on Prisma Cloud side add callback URI to the IdP

 


 