== Overview
:toc:
:toclevels:
:toc-title:

toc::[]


Prisma Cloud Compute's Console and Defender base image is the https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?gti-tabs=unauthenticated[RedHat Universal Base Image 8 Minimal].
We use the UBI8-minimal image to keep our image sizes as small as possible, still retain functionality and support OpenSCAP scanning.
https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image[RedHat states] the minimal image is designed for applications that contain their own dependencies which is the case for Prisma Cloud Compute.


== Methodology

Every release of Prisma Cloud Compute we perform an SCAP scan of the Console and Defender images and post the results here.
This process is based upon the U.S. Air Force's Platform 1 https://repo1.dso.mil/ironbank-tools/ironbank-pipeline/-/blob/master/stages/scanning/oscap-compliance-run.sh["Repo One" OpenSCAP scan] of the Prisma Cloud Compute images.
We then compare the scan results to https://ironbank.dso.mil/about[IronBank's] latest approved UBI8-minimal scan findings, any discrepancies are addressed or justified and the results are posted here.

The scanning process is as follows:

. Build RedHat Enterprise Linux server
. Install openscap-utils package
. Pull the latest SCAP content from the https://github.com/ComplianceAsCode/content/releases[Compliance as Code] GitHub repository.
. Scan the Console and Defender images
+
  oscap-podman <imageID> xccdf eval \
  --fetch-remote-resources \
  --profile xccdf_org.ssgproject.content_profile_stig \
  --report scan_report_name.html scap-security-guide-*latest*/ssg-rhel8-ds.xml

. Compare findings against the IronBank daily issued https://ironbank.dso.mil/repomap/redhat/ubi[UBI8-minimal image.]


== Scan results by release

[cols="1,3", options="header"]
|===
|Release
|Notes

|21.04.439
|xref:v21_04_439/scan_results_21_04_439.adoc[Scan results]
for the second update to the https://docs.prismacloudcompute.com/docs/releases/release-information/latest.html[21.04 (21.04.439)] release.

|21.04.421
|xref:v21_04_421/scan_results_21_04_421.adoc[Scan results]
for the first update to the https://docs.prismacloudcompute.com/docs/releases/release-information/latest.html[21.04 (21.04.421)] release.

|21.04.412
|xref:v21_04_412/scan_results_21_04_412.adoc[Scan results]
for the "Hamilton" major release https://docs.prismacloudcompute.com/docs/releases/release-information/release-notes-21-04.html[21.04 (21.04.412)].

|20.12.541
|xref:v20_12_541/scan_results_20_12_541.adoc[Scan results]
for the second update to the https://docs.twistlock.com/docs/releases/release-information/release-notes-20-12.html[20.12 (20.12.531)] release.

|===
