== AWS S3 bucket ACL grants READ permission to everyone


*Policy Details* 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4a060a93-6f25-418d-9f08-472f62d5ba3c

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/S3PublicACLRead.py[CKV_AWS_20]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 

Bridgecrew
Prisma Cloud
*AWS S3 bucket ACL grants READ permission to everyone* 



*Policy Details* 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4a060a93-6f25-418d-9f08-472f62d5ba3c

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/S3PublicACLRead.py[CKV_AWS_20]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



*Description* 


Unprotected S3 buckets are one of the major causes of data theft and intrusions.
An S3 bucket that allows *READ* access to everyone can provide attackers the ability to read object data within the bucket, which can lead to the exposure of sensitive data.
The only S3 buckets that should be globally accessible for unauthenticated users or for *Any AWS Authenticate Users* are those used for hosting static websites.
Bucket ACL helps manage access to S3 bucket data.
We recommend AWS S3 buckets are not publicly accessible for *READ* actions to protect S3 data from unauthorized users and exposing sensitive data to public access.

=== Fix - Runtime


*Procedure* 


S3 buckets should be protected by using the bucket ACL and bucket policies.
If you want to share data with other users via S3 buckets create pre-signed URLs with a short expiration duration.
To generate a pre-signed URL for the file _samplefile.zip_, use the following command:
[,bash]
----
aws s3 presign --expires-in 36000 s3://sharedfolder/samplefile.zip
----
To generate pre-signed URLS for every object in an S3 bucket, use the following command:
[,bash]
----
while read line; do aws s3 presign --expires-in 36000 s3://sharedfolder/$line; done
----

[NOTE]
====
For all automation-related work use the bucket policy and grant access to the required roles.
====

=== Fix - Buildtime


*Terraform* 


* *Resources:* aws_s3_bucket.data
* *Arguments:* acl


[source,text]
----
{
  "codes": [
    {
      "code": "resource "aws_s3_bucket" "data" {
\t...
  bucket        = "${local.resource_prefix.value}-data"
-  acl           = "public-read"
+  acl           = "private"
}",
      "language": "text",
      "name": "Terraform"
    }
  ]
}
----


*CloudFormation* 


* *Resources:* AWS::S3::Bucket.data
* *Arguments:* Properties.AccessControl


[source,yaml]
----
{
  "codes": [
    {
      "code": "Type: AWS::S3::Bucket
    Properties:
    \t...
-     AccessControl: PublicReadWrite / PublicRead",
      "language": "yaml"
    }
  ]
}
----
