== Dockerfile YUM package manager is configured to skip GPG signature checks

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6e520622-3985-4d86-b123-cfede1b01224

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunYumNoGpgCheck.yaml[CKV2_DOCKER_9]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Using the `--nogpgcheck` option with the YUM package manager (`yum`) in Dockerfiles introduces security risks. This flag instructs YUM to bypass GPG signature verification when installing packages.

By skipping the GPG signature check, the container could be exposed to tampered or malicious packages. This bypass can result in the inclusion of compromised software or vulnerable versions in the container image, potentially undermining the container's security and the integrity of applications contained within.

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- RUN yum install -y --nogpgcheck somepackage
+ RUN yum install -y somepackage
----
