== Dockerfile APK package manager is configured to allow untrusted repositories

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| TBD

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunApkAllowUntrusted.yaml[CKV2_DOCKER_7]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Using the `--allow-untrusted` option with the APK package manager (`apk`) in Dockerfiles is a significant security risk. This flag tells APK to skip the signature verification process for packages, allowing the installation of packages that have not been cryptographically signed.

By bypassing the signature verification, you expose your Docker containers to potential threats like tampered packages, which can lead to the inclusion of malicious code or vulnerable software versions in your container images. 

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- RUN apk add --no-cache --allow-untrusted somepackage
+ RUN apk add --no-cache somepackage
----
