== Dockerfile certificate validation is disabled with curl


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ed24003d-5c3e-4bfc-8188-ac86c802b173

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunUnsafeCurl.yaml[CKV2_DOCKER_2]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Description 


This policy checks for the use of either the --insecure option or the -k shorthand with `curl`. Both these flags tell curl to skip verifying the server's certificate when making a request over HTTPS.

Bypasses SSL Verification: By using either --insecure or -k, you're telling curl to not validate the SSL certificate of the server it's connecting to. This makes the request vulnerable to man-in-the-middle (MitM) attacks, where an attacker can intercept and possibly modify the traffic between curl and the server.


=== Fix - Buildtime

*Docker*

Don't use the --insecure flag.

[source,dockerfile]
----
- RUN curl --insecure https://example.com/somepackage.tar.gz | tar xz
+ RUN curl https://example.com/somepackage.tar.gz | tar xz
----

