== Dockerfile APT package manager is configured to force package installations without prompts or verifications

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 50051b94-5c09-4f3b-bf19-b82f9d8ae6b6

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/RunAptGetForceYes.yaml[CKV2_DOCKER_11]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Using the `--force-yes` option with the APT package manager (`apt-get`) in Dockerfiles is perilous. This flag forces APT to acknowledge all prompts and can potentially permit unauthenticated packages, which significantly jeopardizes the integrity of the installed software.

When `--force-yes` is enabled, the automated acceptance of prompts can allow potentially malicious or compromised packages to be installed without any user intervention or verification. This can lead to the embedding of malicious software or insecure versions into your Docker images.

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- RUN apt-get update && apt-get install -y --force-yes somepackage
+ RUN apt-get update && apt-get install -y somepackage
----
