== Dockerfile Node.js certificate validation is disabled with the NODE_TLS_REJECT_UNAUTHORIZED environment variable

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6d10d320-0324-4e22-aa7f-d632718b72a2

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/dockerfile/checks/graph_checks/EnvNodeTlsRejectUnauthorized.yaml[CKV2_DOCKER_6]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Docker

|=== 

=== Description 

Setting the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0` within Dockerfiles for Node.js applications is a security risk. This setting instructs Node.js to bypass SSL/TLS certificate verification for outgoing HTTPS requests.

By disabling SSL/TLS certificate verification, Node.js applications are exposed to potential man-in-the-middle (MitM) attacks. Attackers can intercept, modify, or eavesdrop on the traffic between the Node.js application and an external server, potentially leading to data breaches or the injection of malicious code.

=== Fix - Buildtime

*Docker*

[source,dockerfile]
----
- ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npm install somepackage
----
