== Getting started

// The articles here to show you how to:
//
// * Install and deploy Prisma Cloud.
// * Configure and use Prisma Cloud features and functions.
// * Apply Prisma Cloud to secure your container and cloud-native computing environments.

Welcome to the Prisma Cloud product documentation site.
Start exploring how our technology can secure your environment.

[.section]
=== Preinstall check
Ensure your environment meets the minimum xref:../install/system-requirements.adoc[system requirements].

[.section]
=== Install the software

ifdef::compute_edition[]
Download the xref:../welcome/releases.adoc[latest Prisma Cloud release] to your Prisma Cloud Console server or cluster controller.
Then xref:../install/getting-started.adoc[install] Prisma Cloud using one of the dedicated guides.
endif::compute_edition[]

ifdef::prisma_cloud[]
Deploy Defenders to secure your environment.
endif::prisma_cloud[]

ifdef::compute_edition[]
[.section]
=== Register your license key
Open a browser and navigate to the Prisma Cloud Console.
Create an initial admin user, then enter your license key.

Your Prisma Cloud Console is available on \https://<consoleServer>:8083
endif::compute_edition[]

[.section]
=== Install a test application
Use your own app or check out the https://microservices-demo.github.io/[Sock Shop].

[.section]
=== Explore Prisma Cloud's core features
The following articles will get you started with Prisma Cloud's core features:

* xref:../vulnerability-management/registry-scanning/registry-scanning.adoc[Scan and monitor Docker registries]
* xref:../vulnerability-management/scan-reports.adoc[Review image scan reports]
* xref:../compliance/manage-compliance.adoc[Create compliance rules]
* xref:../vulnerability-management/vuln-management-rules.adoc[Create vulnerability rules]
* xref:../runtime-defense/runtime-defense.adoc[Learn about runtime protection]
* xref:../waas/waas.adoc[Set up a cloud native application firewall]
* xref:../firewalls/cnns-saas.adoc[Set up connection monitoring]
