== Email alerts

Prisma Cloud can send email alerts when your policies are violated.
Audits in *Monitor > Events* are the result of a policy violation.
Prisma Cloud can be configured to notify the appropriate party by email when an entire policy, or even specific rules, are violated.

ifdef::prisma_cloud[]
 
NOTE: Because Prisma Cloud Enterprise Edition Compute Console is hosted on Google Cloud Platform, outbound connections to port 25 from Console are blocked.
All other ports are available, including ports 587 and 465.
For more information, see https://cloud.google.com/compute/docs/tutorials/sending-mail[here].

endif::prisma_cloud[]

// == Configuring alerts
//
// Reusable content fragment.
include::frag_config_rate.adoc[leveloffset=0]


=== Sending email alerts

// Reusable content fragment.
:email_alerts:
include::frag_send_alerts.adoc[leveloffset=0]


[.task]
=== Create a new alert profile

[.procedure]
. In *Manage > Alerts*, click *Add profile*.

. Enter a *Profile name*.

. In *Provider*, select *Email*.

. Click *Next*.

// Reusable content fragment.
include::frag_config_triggers.adoc[leveloffset=0]

[.task]
=== Configure the channel

[.procedure]
. In *SMTP address*, specify the hostname for your outgoing email server.

. In *Port*, specify the port for email submissions.

. In *Credential*, create the credentials required to access the email account that sends alerts.
This isn't a required field.

.. Click *Add new*.

.. Select *Basic authentication*.

.. Enter a username and password.

. If you're using SMTPS (your SMTP connection is secured by SSL), set *SSL* to *On*.

. Set up your recipients.

.. Click *Add recipient*, and enter an email address.
Every email alert profile must have at least one recipient, even if you're using alert labels.

.. (Optional) Specify recipients using xref:../audit/annotate_audits.adoc[alert labels].

. Click *Next*.

. Review the *Summary* and test the configuration by selecting *Send test alert*.

. Click *Save*.
