== Gitlab project defined in Terraform requires fewer than 2 approvals
// Gitlab project merge request requires less than 2 approvals


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| befd7267-1709-4aa3-8f73-c7311610da34

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gitlab/RequireTwoApprovalsToMerge.py[CKV_GLB_1]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 


In GitLab, administrators can require that all merge requests receive a specific number of approving reviews before someone merges the pull request into a protected branch.
It is also possible to require approving reviews from people with write permissions in the repository or from a designated code owner.
If a collaborator attempts to merge a pull request with pending or rejected reviews into the protected branch, the collaborator will receive an error message.

=== Fix - Buildtime


*Terraform* 


* Resource: gitlab_project
* Attribute: approvals_before_merge


[source,go]
----
resource "gitlab_project" "example" {
...
+  approvals_before_merge = 2
...
}
----

