[#id6e80b7a7-43a3-4f93-baf6-45604a8fe54f]
== Network Query
Use Network Query to find real-time network security risks on your resources deployed in public cloud environments.

When you onboard your cloud accounts to Prisma Cloud, it monitors network configuration and traffic logs to and from your assets deployed on the cloud environment. You can then use this data to find previously unidentified network security risks:

* xref:#id6bb1af97-1d55-4881-9fa0-41b20f921556[Flow Log-based Network Query]: Query for incidents and threats that are based on flow logs.

* xref:#id5e6ea463-5c9b-4e3f-9af8-bc84916b7ecd[Configuration-based Network Query]: Query for true exposures that are based on configuration.




[#id6bb1af97-1d55-4881-9fa0-41b20f921556]
=== Flow Log-based Network Query
Prisma Cloud provides the userinput:[network from vpc.flow_record] network query that is based on networking logs, such as VPC flow logs, which you can use to detect when services, applications, or databases are exposed to the Internet and fix risky configuration issues, or to search for assets that are receiving traffic and connections from suspicious IP addresses to prevent data exfiltration attempts before it is too late.

When you use the userinput:[network from vpc.flow_record where cloud.account=] RQL, the following are the list of resources for which you can visualize flow log information on Prisma Cloud:

[cols="50%a,50%a"]
|===
|Cloud Account
|Resources that Support Flow Logs


|*AWS*
|* AWS ElastiCache

* AWS ELB

* AWS Lambda

* AWS NAT Gateway

* AWS RDS

* AWS Redshift

* Container Management

* Database

* Email

* FTP

* FTP Client

* HTTP

* Kerberos Server

* KVP Store

* LDAP

* Message Queue

* Nagios Monitoring Server

* Possible Cryptocurrency Miner

* SSH

* System Management

* Telnet

* Web Proxy

* Web Server

* VM Instance


|*Azure*
|* Azure ELB

* Container Management

* Database

* Email

* FTP

* Generic

* HTTP

* Kerberos Server

* KVP Store

* LDAP

* Message Queue

* Nagios Monitoring Server

* SSH

* System Management

* Telnet

* Web Proxy

* Web Server

* VM Instance


|*GCP*
|* Google Kubernetes Engine (GKE) node

* VM Instance

|===

[NOTE]
====
Network flow log queries are supported on AWS, Azure, and GCP cloud environments.
====
Also see:

* xref:network-flow-log-query-attributes.adoc#id96c19819-a48e-40a6-843c-2ad88d8a7fb3[Network Flow Log Query Attributes]

* xref:network-flow-log-query-examples.adoc#id76bff997-dacb-4a4c-94f9-48507035b498[Network Flow Log Query Examples]




[#id5e6ea463-5c9b-4e3f-9af8-bc84916b7ecd]
=== Configuration-based Network Query
Prisma Cloud also provides the userinput:[config from network where] network query that is based on network configuration, which you can use to identify overly-exposed resources by providing end-to-end network path visibility from any source, such as AWS EC2 virtual machine, DB instance, or Lambda application to any destination, such as the Internet, another VPC, or on-premises networks. This visibility in to the associations between security groups and compute instances help you identify network security risks before they become incidents. Prisma Cloud does not send traffic or read network logs for performing network path analysis.

When you use the userinput:[config from network where=] RQL, the following are the list of resources for which you can query network exposure on Prisma Cloud:

[cols="50%a,50%a"]
|===
|Cloud Account
|Resources that Support Network Exposure


|*AWS*
|* VPC

* Internet Gateway

* Subnet

* NACL

* NAT Gateway

* EC2

* ENI

* EIP

* Security Group

* VPC Service Endpoint/PrivateLink

* Route Table

* Transit Gateway and Route Table

* VPC Peering


|*Azure*
|* Virtual Machine (VM)

* Virtual Machine Scale Set (flexible VMSS, uniform VMSS)

* Network Interface (NIC)

* Subnet

* Public IP Addresses (PIP, PIP prefixes, shared PIP)

* User Define Route (effective UDR)

* Virtual Network (Vnet)

* NAT Gateway

* Loadbalancer (NLB, ALB)

* Application Security Group (ASG)

* Network Security Group (NSG)

* PaaS Services (PgSQL)

|===

[NOTE]
====
Network exposure queries are currently supported only on AWS and Azure cloud environments and are currently not available in the Government and China regions.
====
Also see:

* xref:network-query-attributes.adoc#id192IH0E0GW5[Network Exposure Query Attributes]

* xref:network-query-examples.adoc#id192IH0G0XVC[Network Exposure Query Examples]




