== 3.14.10

//'''
//
//title: 3.14.10
//type: list
//url: "/3.14/release-notes/3.14.10/"
//menu:
//  3.14:
//    parent: "release-notes"
//    identifier: 3.14.10
//    weight: 14
//
//'''

February 25, 2021

=== What's new

==== Outbound DSCP markings preserved

We now support differentiated services code point (DSCP) markings on outbound communications, allowing you to provide different levels of quality of service (QoS) depending on the traffic.
You must place the outbound packet modification rules in a custom chain named `POST-CUSTOM-QOS` in the `MANGLE` table.

==== Namespace mapping for processing units after startup

You can now map processing units that have already started to a different namespace.

. Create or modify the namespace mapping.
. Manually delete the processing units to be mapped.
. The enforcer recreates the processing unit in the desired namespace.

=== Resolved issues

* *CNS-1154*: The enforcer recovers more gracefully from synchronization errors in Kubernetes deployments with large quantities of pods and namespaces.
* *CNS-1266*: The enforcer monitors and controls ICMP traffic on Red Hat Enterprise Linux 6 distributions despite the absence of xref:../start/enforcer/reqs.adoc#_kernel-modules[the `net/netfilter/xt_bpf.ko` module].
* *CNS-1326*: Windows enforcers report non-TCP flows rejected by Aporeto's default *Reject all* policy to the control plane.

=== Known issues

* *APO-146*: RHEL 8 and RHEL CoreOS 8 (used by OpenShift 4) have deprecated `iptables` in favor of `nftables`.
Before installing Aporeto in these environments, you must enable `iptables`, such as via the following commands:
+
[,console]
----
modprobe ip_tables
modprobe iptable_nat
----

* *CNS-153*: When using relative time values with `apoctl`, the values must be in relation to Pacific Standard Time (PST).
For example, if you are in France and want to retrieve the last five minues of flow logs, you could use `-9h5m`.
Another workaround for this issue is to use absolute time values.
* *CNS-614*: The prebuilt CentOS 7.0 images distributed by OpenStack prefixed with `CentOS-7-x86_64-GenericCloud-2014` do not include the `xt_cgroups.ko` kernel module xref:../start/enforcer/reqs.adoc#_kernel-modules[required by the enforcer].
* *CNS-121*: When multiple clients attempt to connect to the same HTTP service on a Windows host, some may experience timeouts.
* *CNS-126*: After decommissioning an enforcer, you may find some of its iptables rules still in place.
* *CNS-1252*: Under rare circumstances, you may see some dropped traffic to Docker processing units.
Looking in the *Event Logs* in the control plane, you observe the following error messages `Unable to find client` or `Unable to uneforcer name is a required attribute`.
Restart the enforcer to resolve this issue.
* *CNS-1343*: The enforcer fails to program external networks that use the `!` operator on Red Hat Enterprise Linux 6.
* *CNS-1356*: You must use an enforcer profile to manually add the URL of the Microsegmentation Console API to as an excluded network for Red Hat Enterprise Linux 6 hosts.
Failing to do so before installing the enforcer causes a complete lack of access to the host.
* *CNS-1373*: Enforcers on Red Hat Enterprise Linux 6 fail to start if passed tags that contain spaces.
For example, `ENFORCERD_OPTS="--tag key='value1 value2'"` throws the error `unknown command "value2" for "enforcerd"`.

=== Deprecation notices

A future release will remove support for the following.
Please plan accordingly.

* *App integrations*: 5.0 will not include the Clair vulnerability scanner or any other app integrations.
* *CoreOS, Oracle Enterprise Linux (OEL), and Red Hat Enterprise Linux (RHEL) 6*: upgrade to CoreOS/OEL/RHEL 7 or later.
* *Custom resource definitions*: Aporeto won't create https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resource definitions (CRDs)] in Kubernetes/OpenShift.
* *Enforcer as standalone container*: you must install the 5.0 enforcer as a Linux/Windows service or Kubernetes/OpenShift `DaemonSet`.
* *Enforcer audit logging capabilities*: due to a lack of adoption.
* *Host services*: migrate to external networks and network policies.
* *`kubenet` support*: migrate to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/[CNI plugins] if necessary.
For example, GKE clusters use `kubenet` by default.
Pass the `--enable-network-policy` flag to modify GKE clusters to use CNI plugins instead.
* *xref:../start/control-plane/multi-region.adoc[Multi-region control planes]*: migrate to xref:../scale/multi-ctrl-plane.adoc[federated control planes].
* *Namespace editor and namespace auditor roles*: migrate users to equivalent roles.
For example, migrate users with the *Namespace editor* role to *Namespace administrator*.
* *Namespace mapping for enforcers*: 5.0 removes support. If you require this, contact us.
* *xref:../secure/ssh/ssh.adoc[SSH controls]*: ignored by the 5.0 enforcer.
