== Actively used Bitbucket repository lacks branch protection rules

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|a622694d-a6fd-436c-ac67-9dd727ff4e92

|Severity
|Medium

|Category
|Flow Control Mechanism
// add category 

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Bitbucket

|=== 


=== Description 

An actively used repository^*^ does not have any protected branch settings configured.
Protected branch settings are recommended to enforce stronger controls around the conditions that enable pushing code to important branches within a sensitive repository. 

Protected branch settings define whether collaborators can delete or force push to the branch. They also set requirements for any pushes to the branch, such as passing status checks or a linear commit history. Lack of protected branch settings can allow collaborators to inadvertently/intentionally push code, which introduces security risks to production.

^*^An actively used repository has at least two contributors, over 50 commits, and was updated in the last 90 days.

=== Recommended Solution - Buildtime

It is recommended that protected branch settings be configured on the repository. This ensures that code going through the pipeline meets the relevant security requirements, and it minimizes the risk of insecure/malicious code being pushed directly to production bound branches.

Branches used to push code further down the pipeline (for example those that trigger a build), and branches used as libraries in other code sources, are those that should be chosen for protection.

For additional information on configuring protected branch settings in Bitbucket, refer to: https://support.atlassian.com/bitbucket-cloud/docs/use-branch-permissions/.
 