== BitBucket access key has a weak SSH signature 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|8ed1dc72-a741-4157-be1d-7e5d426c5d61 

|Severity
|Low
// add severity level

|Category
|Identity and Access Management
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Bitbucket

|=== 

=== Description 

Repository access keys created with weak signature algorithms can allow attackers to perform a man-in-the-middle- attack and compromise the integrity and confidentiality of the communications with the version control system. 

An access key created with the deprecated **ssh-dss** algorithm is in use in the Bitbucket organization. This algorithm was deprecated in **OpenSSH 7.0**. For more on access keys refer to http://www.openssh.com/legacy.html.

=== Recommended Solution - Buildtime

Revoke all **ssh-dss keys** in use. Instead, use any of the following supported **OpenSSH** key types:

* ecdsa
* ecdsa-sk
* ed25519
* ed25519-sk
* rsa

To replace an access key:
 
. Create a new private key on the server intended to use it, using one of the recommended algorithms.
. Create a new access key using the matching public key in the same repository that the current key was created on.
. Direct the server to use the new access key.
. Delete the older access key from the Bitbucket repository.

==== Create and delete access keys

* Create and delete access keys through the console: Browse to the **Deploy Keys** tab under the repository **Settings**.

* Create and delete access keys through the API: Refer to the Bitbucket API documentation:https://developer.atlassian.com/cloud/bitbucket/rest/api-group-deployments/#api-repositories-workspace-repo-slug-deploy-keys-post.
