[#scanning-modes]
== Agentless Scanning Modes

The following modes are available for agentless scanning in Prisma Cloud.

* *Same Account Mode*: Scan hosts of the cloud account using the same cloud account. This mode spins up temporary scanning instances in the account.

* *Hub Account Mode* Scan hosts of the cloud account (the target) using another cloud account (the hub). This mode spins up temporary scanning instances in the hub rather than in the target(s).

=== AWS

When you click the *Download* button, multiple permission templates are downloaded as JSON files.
These templates support the various permissions required by each of the cloud accounts for each of the scanning modes.

==== Same Account Mode

To scan accounts using this mode, download and apply the permission template that ends in `_target_user_permissions.json` to the AWS cloud account.

==== Hub Account Mode

You first configure and select a cloud account to serve as the hub account.
You apply permissions templates from the hub account in Prisma Cloud to the hub account in AWS, and apply permissions templates from both the hub account and the target account in Prisma Cloud to the target account in AWS.

===== Hub Account

To use an account as a hub account, first add it to Cloud Accounts, downloading and applying the permission template that ends in  `_hub_user_permissions.json` to that hub account in AWS.

===== Target Account

Download and apply the permission template that ends in  `_hub_target_user_permissions.json` to that target account in AWS..

=== Azure

Download and apply the permission template to the Azure cloud account: there is no option for Hub Account Mode in Aure.
Note that Prisma Cloud creates a dedicated `PCC` resource group to allow for easier cost calculations.

=== GCP

When you click the *Download* button, multiple permission templates are downloaded as JINJA files.
These templates support the various permissions required by each of the cloud accounts for each of the scanning modes.

==== Same Account Mode

To scan accounts using this mode, download and apply the permission template that ends in `_target_user_permissions.yaml.jinja` to the GCP project.

==== Hub Account Mode

You first configure and select an cloud account to serve as the hub account.
You apply permissions templates from the hub account in Prisma Cloud to the hub project in GCP, and apply permissions templates from both the hub account and the target account in Prisma Cloud to the target project in GCP.

===== Hub Account/Project

To use an account as a hub account, first add it to Cloud Accounts, downloading and applying the permission template that ends in `_hub_user_permissions.yaml.jinja` to that hub project in GCP.

To also allow that hub account to scan its own hosts, also apply the permission template that ends in `_target_user_permissions.yaml.jinja` to that hub project in GCP.
Otherwise, disable Agentless scanning for that hub account in Cloud Accounts.

==== Target Account/Project

Download and apply the permission templates that end in `_hub_target_user_permissions.yaml.jinja` and `_hub_target_access_permissions.yaml.jinja` to the target project in GCP.