:toc: macro
[#defender-types]
== Defender Types

toc::[]

To take advantage of the agent-based security features of Prisma Cloud, you must deploy Defenders. Defenders enforce the policies you set in the Prisma Cloud console.

ifdef::compute_edition[]

Before you deploy Defenders in your environment, ensure you have xref:../deploy-console/deploy-console.adoc[deployed the Prisma Cloud console].

endif::compute_edition[]

Generally, you should deploy Defenders whenever you can. It offers the most features, it can simultaneously protect both containers and host, and nothing needs to be embedded inside your containers for Defenders to protect them.
Specific types of assets require specific Defender types to protect them, to ensure optimal deployment into the environment, and to fully support for automated workflows.

You must decide how to deploy the Defenders based on the type of asset you want to protect.

* Single Container Defenders: xref:./container/container.adoc[Deploy a single Defender to a single container].

* Single Host Defenders: xref:./host/host.adoc[Deploy a single Defender to a single bare-metal or virtual host].

* Orchestrator Defenders: xref:./orchestrator/orchestrator.adoc[Deploy Defenders on an entire cluster at the orchestration level].

* Serverless Defenders: xref:./serverless/serverless.adoc[Deploy a single Defender to protect serverless functions at runtime].

* App-embedded Defenders: xref:./app-embedded/app-embedded.adoc[Deploy a single Defender to protect containers that run on container-on-demand services].

To avoid manually deploying Defenders on each container, VM, or host, you can use xref:./host/auto-defend-host.adoc[auto-Defend] to deploy Defenders automatically on AWS, Azure, or GCP. You can also xref:./orchestrator/install_cluster_container_defender.adoc[deploy container Defenders automatically in an entire cluster using kubeconfig].

You can deploy an orchestrator Defender to protect assets in these orchestrators.

* xref:./orchestrator/install_amazon_ecs.adoc[ECS]
* xref:./orchestrator/orchestrator.adoc[Kubernetes]
* xref:./orchestrator/install-gke.adoc[GKE]
* xref:./orchestrator/install-gke-autopilot.adoc[GKE Autopilot]
* xref:./orchestrator/openshift.adoc[Openshift]
* xref:./orchestrator/install_tas_defender.adoc[Tanzu Application Service]

=== Connectivity

Defender must be able to communicate with Prisma Cloud over the network because it pulls policies down and sends data (alerts, events, etc) back to the Prisma Cloud console.

ifdef::compute_edition[]
In simple environments, where your hosts run on the same subnet, you can connect to Console using the host's IP address or hostname.
In more complex environments, where your setup runs in the cloud, it can be more difficult to determine how Defender connects to Console.
When setting up Defender, use whichever address routes over your configuration and lets Defender connect to Console.

For example, Console might run in one Virtual Private Cloud (VPC) in AWS, and your containers might run in another VPC.
Each VPC might have a different RFC1918 address space, and communication between VPCs might be limited to specific ports in a security group.
Use whichever address lets Defender connect to Console.
It might be a publicly exposed IP address, a hostname registered with a DNS, or a private address NAT'ed to the actual IP address assigned to Console.
For more information about setting up name resolution in complex networks, see
xref:../../deployment_patterns/best_practices_dns_cert_mgmt.adoc#[Best practices for for DNS and certificate management].
endif::compute_edition[]


