== Pull request reviews are not required in GitHub before merging to the default branch

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|68fb2614-60c8-48aa-9aa1-4a0c7c02db44

|Severity
|Medium
// add severity level

|Category
|Flow Control Mechanism
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 


=== Description 

User accounts granted with “wWrite” permissions on an actively used repository* can directly push code directly to the default branch without requiring reviews, not required for pull request reviews before the code is merged.
User accounts with "write" permissions on an actively used repository can push code directly to the default branch without requiring pull request reviews before the code is merged, potentially allowing malicious code to flow through the pipeline to production systems.
Attackers compromising such a user account can directly push code to the default branch, which is likely to flow through the pipeline and be used in production systems.

* An actively used repository is defined as having at least two contributors, over 50 commits, and has been updated in the last 90 days.

=== Recommended Solution - Buildtime

It is recommended to restrict direct pushes to the default branch, and to require pull request approvals to ensure the code is reviewed before merged.
To configure require required pull request reviews:
1. Open a repository> click on ‘Settings’.Browse to the repository settings.
2. Under ‘Branches’, Click ‘add branch protection rule’ .edit the rule that applies to the default branch.
3. Check the “Require a pull request reviews before merging”.
4. Select required request approvals from the options that are displayed.
Recommended: check the ‘Require review from Code Owners’ that is displayed when executing step 3 above. setting.

