== Force push to default branch is allowed in GitHub

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|23fa11d9-6b95-4278-b1b4-a99f96e52b11

|Severity
|Low
// add severity level

|Category
|Data Protection
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 


=== Description 

User accounts with **write** permissions can force push to a default branch of an actively used repository^*^ and overwrite the commit history. If the repository is not stored on another source, a malicious user account can permanently delete the entire git history of the repository.

^*^An actively used repository has at least two contributors, over 50 commits, and was updated in the last 90 days.


=== Recommended Solution - Buildtime

To restrict force push on the default branch:

. Browse to the repository **Settings**.

. Under **Branches**, edit the rule that applies to the repository default branch.

. Uncheck the **Allow force pushes** setting.

