== Possible command injection detected in GitHub user event

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|20c27e7f-c302-4fe1-9186-c31131e95f63 

|Severity
|Critical
// add severity level

|Category
|Input Validation
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Prisma CLoud has identified an attempt to carry out a command injection attack against a CI/CD pipeline.

Pipelines are vulnerable to command injection attacks, in which malicious commands and scripts are passed through user controlled inputs such as pull request title, commit description and so on. These inputs are referenced by the pipeline configuration file and executed in the pipeline job.

When a pipeline job runs, the poisoned controlled inputs can be interpreted as code  and executed on the runner, allowing attackers to run code in the context of the pipeline. Insufficient PBAC (Pipeline Based Access Controls) may enable the attackers to carry out their attack with wide scope of permissions and gain unauthorized access to systems.

=== Recommended Solution - Buildtime

Verify whether there is an actual attempt to inject code. Validate your findings with the responsible user.

For more information refer to https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks

To prevent a command injection attack, validate all user controlled inputs and ensure that they do not contain malicious commands or scripts.

It is recommended to use an action that processes user input as an argument, instead of an inline script. Another approach would be to set the value of the expression to an intermediate environment variable.

Insufficient Pipeline Based Access Controls (PBAC) may enable attackers to carry out their attack with a wide scope of permissions. Therefore define the scope of permissions that the runner requires according to the principle of _least privilege_.



