== Reviews in GitHub may no longer be required before merging

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|a8260c96-4296-46ba-9874-1c9e1278d895

|Severity
|High
// add severity level

|Category
|Flow Control Mechanism
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Removing code reviews from protected branches eliminates an essential security measure designed to prevent unreviewed code that may contain security bugs and/or malicious commits being pushed to repository branches.

=== Recommended Solution - Buildtime

Verify the reason for removing required reviews.
Consider adding a branch protection rule with the **Require a pull request before merging** setting enabled, and selecting at least 1 reviewer in the **Require approvals** field.  

For more information refer to: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule
