== Network Configuration Queries

Prisma Cloud provides the userinput:[config from network where] network query that is based on network configuration, which you can use to identify overly-exposed resources by providing end-to-end network path visibility from any source, such as AWS EC2 virtual machine, DB instance, or Lambda application to any destination, such as the internet, another VPC, or on-premises networks. This visibility in to the associations between security groups and compute instances help you identify network security risks before they become incidents. Prisma Cloud does not send traffic or read network logs for performing network path analysis.

When you use the userinput:[config from network where=] RQL, the following are the list of resources for which you can query network exposure on Prisma Cloud:

[cols="50%a,50%a"]
|===
|Cloud Services
|Resources that Support Network Exposure


|*AWS*
|* Network (VPC)
* Internet Gateway
* Subnet
* NACL
* NAT Gateway
* EC2
* ENI
* EIP
* Security Group
* VPC Service Endpoint/PrivateLink
* Route Table
* Transit Gateway and Route Table
* VPC Peering


|*Azure*
|* Virtual Machine (VM)
* Virtual Machine Scale Set (flexible VMSS, uniform VMSS)
* Network Interface (NIC)
* Subnet
* Public IP Addresses (PIP, PIP prefixes, shared PIP)
* User Define Route (effective UDR)
* Virtual Network (Vnet)
* NAT Gateway
* Loadbalancer (NLB, ALB)
* Application Security Group (ASG)
* Network Security Group (NSG)
* PaaS Services (PgSQL)


|*GCP*
|* Subnet
* VPC Firewall
* Hierarchical Firewall Rules
* BackendService
* FirewallPolicy
* LB ForwardingRule
* VM
* InstanceGroup
* VPC
* NetworkEndpointGroup
* TargetHttpProxy
* TargetHttpsProxy
* TargetInstance
* TargetPool
* TargetSslProxy
* TargetTcpProxy
* URLMap

|===

[NOTE]
====
Network exposure queries are currently supported only on AWS, Azure, and GCP cloud environments and are currently not available in the Government and China regions.
====