== policy/services

=== ClaimMapping

Allows you to map a claim in a token to an HTTP header. This can be
useful when offloading authentication and authorization to Segment. Some
applications may expect to receive information in the HTTP header.

==== Example

[source,json]
----
{
  "claimName": "email",
  "targetHTTPHeader": "X-Username"
}
----

==== Attributes

===== `claimName` [`required`,`format=^[a-zA-Z0-9-_/*#&@\+\$~:]+$`]

Type: `string`

The name of the claim to map to the HTTP header. header.

===== `targetHTTPHeader` [`required`,`format=^[a-zA-Z0-9-_/*#&@\+\$~:]+$`]

Type: `string`

The HTTP header that will be the destination of the mapped claim.

=== Endpoint

Represents an HTTP endpoint.

==== Example

[source,json]
----
{
  "public": false
}
----

==== Attributes

===== `URI`

Type: `string`

URI of the exposed API.

===== `allowedScopes`

Type: `[][]string`

The scopes authorized to access the API.

===== `methods`

Type: `[]string`

Methods exposed to access the API.

===== `public`

Type: `boolean`

If `true`, the API is public.

===== `scopes` [`read_only`]

_This attribute is deprecated_.

Type: `[]string`

Use `allowedScopes`.

=== HTTPResourceSpec

Describes an HTTP resource exposed by one or more services.

==== Example

[source,json]
----
{
  "name": "the name",
  "propagate": false,
  "protected": false
}
----

==== Relations

===== `GET /httpresourcespecs`

Retrieves the list of HTTP resource specifications.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.
* `propagated` (`boolean`): Also retrieve the objects that propagate
down.
* `archived` (`boolean`): Also retrieve the objects that have been
archived.

===== `POST /httpresourcespecs`

Creates a new HTTP resource specification.

===== `DELETE /httpresourcespecs/:id`

Deletes the HTTP resource with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /httpresourcespecs/:id`

Retrieves the HTTP resource with the given ID.

Parameters:

* `archived` (`boolean`): Also retrieve the objects that have been
archived.

===== `PUT /httpresourcespecs/:id`

Updates the HTTP resource with the given ID.

===== `GET /services/:id/httpresourcespecs`

Retrieves the HTTP Resource exposed by this service.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `description` [`max_length=1024`]

Type: `string`

Description of the object.

===== `endpoints`

Type: link:#endpoint[`endpoint`]

A list of API endpoints that are exposed for the service.

===== `metadata` [`creation_only`]

Type: `[]string`

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` [`required`,`max_length=256`]

Type: `string`

Name of the entity.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `propagate`

Type: `boolean`

Propagates the policy to all of its children.

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== Service

Defines a generic service object at layer 4 or layer 7 that encapsulates
the description of a micro-service. A service exposes APIs and can be
implemented through third party entities (such as a cloud provider) or
through processing units.

==== Example

[source,json]
----
{
  "OIDCProviderURL": "https://accounts.google.com",
  "OIDCScopes": [
    "email",
    "profile"
  ],
  "TLSType": "Aporeto",
  "authorizationType": "None",
  "disabled": false,
  "exposedAPIs": [
    [
      "package=p1"
    ]
  ],
  "exposedPort": 443,
  "exposedServiceIsTLS": false,
  "external": false,
  "name": "the name",
  "port": 443,
  "protected": false,
  "publicApplicationPort": 443,
  "selectors": [
    [
      "$identity=processingunit"
    ]
  ],
  "type": "HTTP"
}
----

==== Relations

===== `GET /services`

Retrieves the list of services.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.
* `archived` (`boolean`): Also retrieve the objects that have been
archived.

===== `POST /services`

Creates a new service.

===== `DELETE /services/:id`

Deletes the service with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /services/:id`

Retrieves the service with the given ID.

Parameters:

* `archived` (`boolean`): Also retrieve the objects that have been
archived.

===== `PUT /services/:id`

Updates the service with the given ID.

===== `GET /infrastructurepolicies/:id/services`

Returns the list of services affected by an infrastructure policy.

Parameters:

* `mode` (`enum(subject | object)`): Matching mode.

===== `GET /networkaccesspolicies/:id/services`

Returns the list of services affected by a network policy.

Parameters:

* `mode` (`enum(subject | object)`): Matching mode.

===== `GET /processingunits/:id/services`

Retrieves the services used by a processing unit.

===== `GET /servicedependencies/:id/services`

Returns the list of external services that are targets of service
dependency.

===== `GET /services/:id/httpresourcespecs`

Retrieves the HTTP Resource exposed by this service.

===== `GET /services/:id/processingunits`

Retrieves the processing units that implement this service.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `IPs`

Type: `[]string`

The list of IP addresses where the service can be accessed. This is an
optional attribute and is only required if no host names are provided.
The system will automatically resolve IP addresses from host names
otherwise.

===== `JWTSigningCertificate`

Type: `string`

PEM-encoded certificate that will be used to validate the user’s JSON
web token (JWT) in HTTP requests. This is an optional field, needed only
if the `authorizationType` is set to `JWT`.

===== `MTLSCertificateAuthority`

Type: `string`

PEM-encoded certificate authority to use to verify client certificates.
This only applies if `authorizationType` is set to `MTLS`. If it is not
set, Segment’s public signing certificate authority will be used.

===== `OIDCCallbackURL`

Type: `string`

This is an advanced setting. Optional OIDC callback URL. If you don’t
set it, Segment will autodiscover it. It will be
`+https://<hosts[0]|IPs[0]>/aporeto/oidc/callback+`.

===== `OIDCClientID`

Type: `string`

OIDC Client ID. Only has effect if the `authorizationType` is set to
`OIDC`.

===== `OIDCClientSecret`

Type: `string`

OIDC Client Secret. Only has effect if the `authorizationType` is set to
`OIDC`.

===== `OIDCProviderURL`

Type: `string`

OIDC discovery endpoint. Only has effect if the `authorizationType` is
set to `OIDC`.

===== `OIDCScopes`

Type: `[]string`

Configures the scopes you want to request from the OIDC provider. Only
has effect if `authorizationType` is set to `OIDC`.

===== `TLSCertificate`

Type: `string`

PEM-encoded certificate to expose to the clients for TLS. Only has
effect and required if `TLSType` is set to `External`.

===== `TLSCertificateKey`

Type: `string`

PEM-encoded certificate key associated with `TLSCertificate`. Only has
effect and required if `TLSType` is set to `External`.

===== `TLSType`

Type: `enum(Aporeto | LetsEncrypt | External | None)`

Set how to provide a server certificate to the service.

* `Aporeto`: Generate a certificate issued from the Segment public CA.
* `LetsEncrypt`: Issue a certificate from Let’s Encrypt.
* `External`: : Let you define your own certificate and key to use.
* `None`: : TLS is disabled (not recommended).

Default value:

[source,json]
----
"Aporeto"
----

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `authorizationType`

Type: `enum(None | JWT | OIDC | MTLS)`

Defines the user authorization type that should be used.

* `None` (default): No authorization.
* `JWT`: Configures a simple JWT verification from the HTTP
`Authorization` header.
* `OIDC`: Configures OIDC authorization. You must then set
`OIDCClientID`,`OIDCClientSecret`, `OIDCProviderURL`.
* `MTLS`: Configures client certificate authorization. Then you can
optionally use `MTLSCertificateAuthority`, otherwise Segment’s public
signing certificate will be used.

Default value:

[source,json]
----
"None"
----

===== `claimsToHTTPHeaderMappings`

Type: link:#claimmapping[`claimmapping`]

Defines a list of mappings between claims and HTTP headers. When these
mappings are defined, the defender will copy the values of the claims to
the corresponding HTTP headers.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `description` [`max_length=1024`]

Type: `string`

Description of the object.

===== `disabled`

Type: `boolean`

Defines if the property is disabled.

===== `endpoints` [`read_only`]

Type: link:#endpoint[`endpoint`]

Resolves the API endpoints that the service is exposing. Only valid
during policy rendering.

===== `exposedAPIs`

Type: `[][]string`

Contains a tag expression that will determine which APIs a service is
exposing. The APIs can be defined as the `RESTAPISpec` or similar
specifications for other layer 7 protocols.

===== `exposedPort` [`required`,`max_value=65535.000000`]

Type: `integer`

The port that the service can be accessed on. Note that this is
different from the `port` attribute that describes the port that the
service is actually listening on. For example if a load balancer is
used, the `exposedPort` is the port that the load balancer is listening
for the service, whereas the port that the implementation is listening
can be different.

===== `exposedServiceIsTLS`

Type: `boolean`

Indicates that the exposed service is TLS. This means that the defender
has to initiate a TLS session in order to forward traffic to the
service.

Default value:

[source,json]
----
false
----

===== `external`

Type: `boolean`

Indicates if this is an external service.

Default value:

[source,json]
----
false
----

===== `hosts`

Type: `[]string`

The host names that the service can be accessed on.

===== `metadata` [`creation_only`]

Type: `[]string`

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` [`required`,`max_length=256`]

Type: `string`

Name of the entity.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `port` [`max_value=65535.000000`]

Type: `integer`

The port that the implementation of the service is listening to. It can
be different than `exposedPort`. This is needed for port mapping use
cases where there are private and public ports.

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `publicApplicationPort` [`max_value=65535.000000`]

Type: `integer`

A new virtual port that the service can be accessed on, using HTTPS.
Since the defender transparently inserts TLS in the application path,
you might want to declare a new port where the defender listens for TLS.
However, the application does not need to be modified and the defender
will map the traffic to the correct application port. This useful when
an application is being accessed from a public network.

===== `redirectURLOnAuthorizationFailure`

Type: `string`

If this is set, the user will be redirected to that URL in case of any
authorization failure, allowing you to provide a nice message to the
user. The query parameter `?failure_message=<message>` will be added to
that URL explaining the possible reasons of the failure.

===== `selectors`

Type: `[][]string`

A tag or tag expression that identifies the processing unit that
implements this particular service.

===== `trustedCertificateAuthorities`

Type: `string`

PEM-encoded certificate authorities to trust when additional hops are
needed. It must be set if the service must reach a service marked as
`external` or must go through an additional TLS termination point like a
layer 7 load balancer.

===== `type`

Type: `enum(HTTP | TCP | KubernetesSecrets | VaultSecrets)`

Type of service.

Default value:

[source,json]
----
"HTTP"
----

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== ServiceDependency

Allows you to define a service dependency where a set of processing
units as defined by their tags require access to specific services.

==== Example

[source,json]
----
{
  "disabled": false,
  "fallback": false,
  "name": "the name",
  "propagate": false,
  "protected": false
}
----

==== Relations

===== `GET /servicedependencies`

Retrieves the list of service dependencies.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.
* `propagated` (`boolean`): Also retrieve the objects that propagate
down.

===== `POST /servicedependencies`

Creates a new service dependency.

===== `DELETE /servicedependencies/:id`

Deletes the object with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /servicedependencies/:id`

Retrieves the object with the given ID.

===== `PUT /servicedependencies/:id`

Updates the object with the given ID.

===== `GET /servicedependencies/:id/processingunits`

Returns the list of processing units that depend on an service.

===== `GET /servicedependencies/:id/services`

Returns the list of external services that are targets of service
dependency.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `activeDuration` [`format=^[0-9]+[smh]$`]

Type: `string`

Defines for how long the policy will be active according to the
`activeSchedule`.

===== `activeSchedule`

Type: `string`

Defines when the policy should be active using the cron notation. The
policy will be active for the given `activeDuration`.

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `description` [`max_length=1024`]

Type: `string`

Description of the object.

===== `disabled`

Type: `boolean`

Defines if the property is disabled.

===== `fallback`

Type: `boolean`

Indicates that this is fallback policy. It will only be applied if no
other policies have been resolved. If the policy is also propagated it
will become a fallback for children namespaces.

===== `metadata` [`creation_only`]

Type: `[]string`

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` [`required`,`max_length=256`]

Type: `string`

Name of the entity.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `object`

Type: `[][]string`

Object of the service dependency.

===== `propagate`

Type: `boolean`

Propagates the policy to all of its children.

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `subject`

Type: `[][]string`

Subject of the service dependency.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== TokenScopePolicy

Defines a set of policies that allow customization of the authorization
tokens issued by Segment Console. This allows Segment generated tokens
to be used by external applications.

==== Example

[source,json]
----
{
  "disabled": false,
  "fallback": false,
  "name": "the name",
  "propagate": false,
  "protected": false
}
----

==== Relations

===== `GET /tokenscopepolicies`

Retrieves the list of token scope policies.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.
* `propagated` (`boolean`): Also retrieve the objects that propagate
down.

===== `POST /tokenscopepolicies`

Creates a new token scope policy.

===== `DELETE /tokenscopepolicies/:id`

Deletes the object with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /tokenscopepolicies/:id`

Retrieves the object with the given ID.

===== `PUT /tokenscopepolicies/:id`

Updates the object with the given ID.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `activeDuration` [`format=^[0-9]+[smh]$`]

Type: `string`

Defines for how long the policy will be active according to the
`activeSchedule`.

===== `activeSchedule`

Type: `string`

Defines when the policy should be active using the cron notation. The
policy will be active for the given `activeDuration`.

===== `allowedAudiences`

Type: `[]string`

A list of audience values that are allowed when issuing a service token.
An empty list will allow any audience values.

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `assignedAudience`

Type: `string`

The audience that should be assigned to a request if the caller is not
requesting any specific audience.

===== `assignedScopes`

Type: `[]string`

The list of scopes that the policy will assign.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `description` [`max_length=1024`]

Type: `string`

Description of the object.

===== `disabled`

Type: `boolean`

Defines if the property is disabled.

===== `expirationTime`

Type: `time`

If set the policy will be automatically deleted after the given time.

===== `fallback`

Type: `boolean`

Indicates that this is fallback policy. It will only be applied if no
other policies have been resolved. If the policy is also propagated it
will become a fallback for children namespaces.

===== `inheritedClaimKeys`

Type: `[]string`

A list of claim keys that should be inherited from the claims of the
caller to the assigned token. In this case, some of the caller claims
will be propagated to resolved token.

===== `metadata` [`creation_only`]

Type: `[]string`

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` [`required`,`max_length=256`]

Type: `string`

Name of the entity.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `propagate`

Type: `boolean`

Propagates the policy to all of its children.

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `subject`

Type: `[][]string`

Defines the selection criteria that this policy must match on identity
and scope request information.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.
