== core/enforcer

=== CounterReport

Post a new counter tracing report.

==== Example

[source,json]
----
{
  "AckInUnknownState": 0,
  "AckInvalidFormat": 0,
  "AckRejected": 0,
  "AckSigValidationFailed": 0,
  "AckTCPNoTCPAuthOption": 0,
  "ConnectionsProcessed": 0,
  "ContextIDNotFound": 0,
  "DroppedExternalService": 0,
  "InvalidConnState": 0,
  "InvalidNetState": 0,
  "InvalidProtocol": 0,
  "InvalidSynAck": 0,
  "MarkNotFound": 0,
  "NetSynNotSeen": 0,
  "NoConnFound": 0,
  "NonPUTraffic": 0,
  "OutOfOrderSynAck": 0,
  "PortNotFound": 0,
  "RejectPacket": 0,
  "ServicePostprocessorFailed": 0,
  "ServicePreprocessorFailed": 0,
  "SynAckBadClaims": 0,
  "SynAckClaimsMisMatch": 0,
  "SynAckDroppedExternalService": 0,
  "SynAckInvalidFormat": 0,
  "SynAckMissingClaims": 0,
  "SynAckMissingToken": 0,
  "SynAckNoTCPAuthOption": 0,
  "SynAckRejected": 0,
  "SynDroppedInvalidFormat": 0,
  "SynDroppedInvalidToken": 0,
  "SynDroppedNoClaims": 0,
  "SynDroppedTCPOption": 0,
  "SynRejectPacket": 0,
  "SynUnexpectedPacket": 0,
  "TCPAuthNotFound": 0,
  "UDPAckInvalidSignature": 0,
  "UDPConnectionsProcessed": 0,
  "UDPDropContextNotFound": 0,
  "UDPDropFin": 0,
  "UDPDropInNfQueue": 0,
  "UDPDropNoConnection": 0,
  "UDPDropPacket": 0,
  "UDPDropQueueFull": 0,
  "UDPDropSynAck": 0,
  "UDPInvalidNetState": 0,
  "UDPPostProcessingFailed": 0,
  "UDPPreProcessingFailed": 0,
  "UDPRejected": 0,
  "UDPSynAckDropBadClaims": 0,
  "UDPSynAckMissingClaims": 0,
  "UDPSynAckPolicy": 0,
  "UDPSynDrop": 0,
  "UDPSynDropPolicy": 0,
  "UDPSynInvalidToken": 0,
  "UDPSynMissingClaims": 0,
  "UnknownError": 0,
  "connectionsAnalyzed": 0,
  "connectionsDropped": 0,
  "connectionsExpired": 0,
  "droppedPackets": 0,
  "encryptionFailures": 0,
  "enforcerID": "xxxx-xxx-xxxx",
  "enforcerNamespace": "/my/namespace",
  "externalNetworkConnections": 0,
  "policyDrops": 0,
  "processingUnitID": "xxx-xxx-xxx",
  "processingUnitNamespace": "/my/namespace",
  "timestamp": "2018-06-14T23:10:46.420397985Z",
  "tokenDrops": 0
}
----

==== Relations

===== `POST /counterreports`

Create a counter report.

==== Attributes

===== `AckInUnknownState`

Type: `integer`

Counter for sending FIN ACK received in unknown connection state.

Default value:

[source,json]
----
0
----

===== `AckInvalidFormat`

Type: `integer`

Counter for ACK packet dropped because of invalid format.

Default value:

[source,json]
----
0
----

===== `AckRejected`

Type: `integer`

Counter for ACK packets rejected as per policy.

Default value:

[source,json]
----
0
----

===== `AckSigValidationFailed`

Type: `integer`

Counter for ACK packet dropped because signature validation failed.

Default value:

[source,json]
----
0
----

===== `AckTCPNoTCPAuthOption`

Type: `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `ConnectionsProcessed`

Type: `integer`

Counter for connections processed.

Default value:

[source,json]
----
0
----

===== `ContextIDNotFound`

Type: `integer`

Counter for unable to find ContextID.

Default value:

[source,json]
----
0
----

===== `DroppedExternalService`

Type: `integer`

Counter for no ACLs found for external services. Dropping application
SYN packet.

Default value:

[source,json]
----
0
----

===== `InvalidConnState`

Type: `integer`

Counter for invalid connection state.

Default value:

[source,json]
----
0
----

===== `InvalidNetState`

Type: `integer`

Counter for invalid net state.

Default value:

[source,json]
----
0
----

===== `InvalidProtocol`

Type: `integer`

Counter for invalid protocol.

Default value:

[source,json]
----
0
----

===== `InvalidSynAck`

Type: `integer`

Counter for processing unit is already dead - drop SYN ACK packet.

Default value:

[source,json]
----
0
----

===== `MarkNotFound`

Type: `integer`

Counter for processing unit mark not found.

Default value:

[source,json]
----
0
----

===== `NetSynNotSeen`

Type: `integer`

Counter for network SYN packet was not seen.

Default value:

[source,json]
----
0
----

===== `NoConnFound`

Type: `integer`

Counter for no context or connection found.

Default value:

[source,json]
----
0
----

===== `NonPUTraffic`

Type: `integer`

Counter for traffic that belongs to a non-processing unit process.

Default value:

[source,json]
----
0
----

===== `OutOfOrderSynAck`

Type: `integer`

Counter for SYN ACK for flow with processed FIN ACK.

Default value:

[source,json]
----
0
----

===== `PortNotFound`

Type: `integer`

Counter for port not found.

Default value:

[source,json]
----
0
----

===== `RejectPacket`

Type: `integer`

Counter for reject the packet as per policy.

Default value:

[source,json]
----
0
----

===== `ServicePostprocessorFailed`

Type: `integer`

Counter for post service processing failed for network packet.

Default value:

[source,json]
----
0
----

===== `ServicePreprocessorFailed`

Type: `integer`

Counter for network packets that failed preprocessing.

Default value:

[source,json]
----
0
----

===== `SynAckBadClaims`

Type: `integer`

Counter for SYN ACK packet dropped because of bad claims.

Default value:

[source,json]
----
0
----

===== `SynAckClaimsMisMatch`

Type: `integer`

Counter for SYN ACK packet dropped because of encryption mismatch.

Default value:

[source,json]
----
0
----

===== `SynAckDroppedExternalService`

Type: `integer`

Counter for SYN ACK from external service dropped.

Default value:

[source,json]
----
0
----

===== `SynAckInvalidFormat`

Type: `integer`

Counter for SYN ACK packet dropped because of invalid format.

Default value:

[source,json]
----
0
----

===== `SynAckMissingClaims`

Type: `integer`

Counter for SYN ACK packet dropped because of no claims.

Default value:

[source,json]
----
0
----

===== `SynAckMissingToken`

Type: `integer`

Counter for SYN ACK packet dropped because of missing token.

Default value:

[source,json]
----
0
----

===== `SynAckNoTCPAuthOption`

Type: `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `SynAckRejected`

Type: `integer`

Counter for dropping because of reject rule on transmitter.

Default value:

[source,json]
----
0
----

===== `SynDroppedInvalidFormat`

Type: `integer`

Counter for SYN packet dropped because of invalid format.

Default value:

[source,json]
----
0
----

===== `SynDroppedInvalidToken`

Type: `integer`

Counter for SYN packet dropped because of invalid token.

Default value:

[source,json]
----
0
----

===== `SynDroppedNoClaims`

Type: `integer`

Counter for SYN packet dropped because of no claims.

Default value:

[source,json]
----
0
----

===== `SynDroppedTCPOption`

Type: `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `SynRejectPacket`

Type: `integer`

Counter for SYN packet dropped due to policy.

Default value:

[source,json]
----
0
----

===== `SynUnexpectedPacket`

Type: `integer`

Counter for received SYN packet from unknown processing unit.

Default value:

[source,json]
----
0
----

===== `TCPAuthNotFound`

Type: `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `UDPAckInvalidSignature`

Type: `integer`

Counter for UDP ACK packet dropped due to an invalid signature.

Default value:

[source,json]
----
0
----

===== `UDPConnectionsProcessed`

Type: `integer`

Counter for number of processed UDP connections.

Default value:

[source,json]
----
0
----

===== `UDPDropContextNotFound`

Type: `integer`

Counter for dropped UDP data packets with no context.

Default value:

[source,json]
----
0
----

===== `UDPDropFin`

Type: `integer`

Counter for dropped UDP FIN handshake packets.

Default value:

[source,json]
----
0
----

===== `UDPDropInNfQueue`

Type: `integer`

Counter for dropped UDP in NfQueue.

Default value:

[source,json]
----
0
----

===== `UDPDropNoConnection`

Type: `integer`

Counter for dropped UDP data packets with no connection.

Default value:

[source,json]
----
0
----

===== `UDPDropPacket`

Type: `integer`

Counter for dropped UDP data packets.

Default value:

[source,json]
----
0
----

===== `UDPDropQueueFull`

Type: `integer`

Counter for dropped UDP Queue Full.

Default value:

[source,json]
----
0
----

===== `UDPDropSynAck`

Type: `integer`

Counter for dropped UDP SYN ACK handshake packets.

Default value:

[source,json]
----
0
----

===== `UDPInvalidNetState`

Type: `integer`

Counter for UDP packets received in invalid network state.

Default value:

[source,json]
----
0
----

===== `UDPPostProcessingFailed`

Type: `integer`

Counter for UDP packets failing postprocessing.

Default value:

[source,json]
----
0
----

===== `UDPPreProcessingFailed`

Type: `integer`

Counter for UDP packets failing preprocessing.

Default value:

[source,json]
----
0
----

===== `UDPRejected`

Type: `integer`

Counter for UDP packets dropped due to policy.

Default value:

[source,json]
----
0
----

===== `UDPSynAckDropBadClaims`

Type: `integer`

Counter for UDP SYN ACK packets dropped due to bad claims.

Default value:

[source,json]
----
0
----

===== `UDPSynAckMissingClaims`

Type: `integer`

Counter for UDP SYN ACK packets dropped due to missing claims.

Default value:

[source,json]
----
0
----

===== `UDPSynAckPolicy`

Type: `integer`

Counter for UDP SYN ACK packets dropped due to bad claims.

Default value:

[source,json]
----
0
----

===== `UDPSynDrop`

Type: `integer`

Counter for dropped UDP SYN transmits.

Default value:

[source,json]
----
0
----

===== `UDPSynDropPolicy`

Type: `integer`

Counter for dropped UDP SYN policy.

Default value:

[source,json]
----
0
----

===== `UDPSynInvalidToken`

Type: `integer`

Counter for dropped UDP FIN handshake packets.

Default value:

[source,json]
----
0
----

===== `UDPSynMissingClaims`

Type: `integer`

Counter for UDP SYN packet dropped due to missing claims.

Default value:

[source,json]
----
0
----

===== `UnknownError`

Type: `integer`

Counter for unknown error.

Default value:

[source,json]
----
0
----

===== `connectionsAnalyzed`

Type: `integer`

Non-zero counter indicates analyzed connections for unencrypted,
encrypted, and packets from endpoint applications with the TCP Fast Open
option set. These are not dropped counter.

Default value:

[source,json]
----
0
----

===== `connectionsDropped`

Type: `integer`

Non-zero counter indicates dropped connections because of invalid state,
non-processing unit traffic, or out of order packets.

Default value:

[source,json]
----
0
----

===== `connectionsExpired`

Type: `integer`

Non-zero counter indicates expired connections because of response not
being received within a certain amount of time after the request is
made.

Default value:

[source,json]
----
0
----

===== `droppedPackets`

Type: `integer`

Non-zero counter indicates dropped packets that did not hit any of our
iptables rules and queue drops.

Default value:

[source,json]
----
0
----

===== `encryptionFailures`

Type: `integer`

Non-zero counter indicates encryption processing failures of data
packets.

Default value:

[source,json]
----
0
----

===== `enforcerID` [`required`]

Type: `string`

Identifier of the defender sending the report.

===== `enforcerNamespace` [`required`]

Type: `string`

Namespace of the defender sending the report.

===== `externalNetworkConnections`

Type: `integer`

Non-zero counter indicates connections going to and from external
networks. These may be drops or allowed counters.

Default value:

[source,json]
----
0
----

===== `policyDrops`

Type: `integer`

Non-zero counter indicates packets dropped due to a reject policy.

Default value:

[source,json]
----
0
----

===== `processingUnitID`

Type: `string`

PUID is the ID of the processing unit reporting the counter.

===== `processingUnitNamespace`

Type: `string`

Namespace of the processing unit reporting the counter.

===== `timestamp`

Type: `time`

Timestamp is the date of the report.

===== `tokenDrops`

Type: `integer`

Non-zero counter indicates packets rejected due to anything related to
token creation/parsing failures.

Default value:

[source,json]
----
0
----

=== Enforcer

Contains all parameters associated with a registered defender. The
object is mainly maintained by the defenders themselves. Users can read
the object in order to understand the current status of the defenders.

==== Example

[source,json]
----
{
  "FQDN": "server1.domain.com",
  "certificateRequest": "-----BEGIN CERTIFICATE REQUEST-----
MIICvDCCAaQCAQAwdzELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFV0YWgxDzANBgNV
BAcMBkxpbmRvbjEWMBQGA1UECgwNRGlnaUNlcnQgSW5jLjERMA8GA1UECwwIRGln
aUNlcnQxHTAbBgNVBAMMFGV4YW1wbGUuZGlnaWNlcnQuY29tMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8+To7d+2kPWeBv/orU3LVbJwDrSQbeKamCmo
wp5bqDxIwV20zqRb7APUOKYoVEFFOEQs6T6gImnIolhbiH6m4zgZ/CPvWBOkZc+c
1Po2EmvBz+AD5sBdT5kzGQA6NbWyZGldxRthNLOs1efOhdnWFuhI162qmcflgpiI
WDuwq4C9f+YkeJhNn9dF5+owm8cOQmDrV8NNdiTqin8q3qYAHHJRW28glJUCZkTZ
wIaSR6crBQ8TbYNE0dc+Caa3DOIkz1EOsHWzTx+n0zKfqcbgXi4DJx+C1bjptYPR
BPZL8DAeWuA8ebudVT44yEp82G96/Ggcf7F33xMxe0yc+Xa6owIDAQABoAAwDQYJ
KoZIhvcNAQEFBQADggEBAB0kcrFccSmFDmxox0Ne01UIqSsDqHgL+XmHTXJwre6D
hJSZwbvEtOK0G3+dr4Fs11WuUNt5qcLsx5a8uk4G6AKHMzuhLsJ7XZjgmQXGECpY
Q4mC3yT3ZoCGpIXbw+iP3lmEEXgaQL0Tx5LFl/okKbKYwIqNiyKWOMj7ZR/wxWg/
ZDGRs55xuoeLDJ/ZRFf9bI+IaCUd1YrfYcHIl3G87Av+r49YVwqRDT0VDV7uLgqn
29XI1PpVUNCPQGn9p/eX6Qo7vpDaPybRtA2R7XLKjQaF9oXWeCUqy1hvJac9QFO2
97Ob1alpHPoZ7mWiEuJwjBPii6a9M9G30nUo39lBi1w=
-----END CERTIFICATE REQUEST-----",
  "collectInfo": false,
  "enforcementStatus": "Inactive",
  "lastCollectionID": "xxx-xxx-xxx-xxx -",
  "logLevel": "Info",
  "logLevelDuration": "10s",
  "machineID": "3F23E8DF-C56D-45CF-89B8-A867F3956409",
  "name": "the name",
  "operationalStatus": "Registered",
  "protected": false,
  "updateAvailable": false
}
----

==== Relations

===== `GET /enforcers`

Retrieves the list of defenders.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `POST /enforcers`

Creates a new defender.

===== `DELETE /enforcers/:id`

Deletes the defender with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /enforcers/:id`

Retrieves the defender with the given ID.

===== `PUT /enforcers/:id`

Updates the defender with the given ID.

===== `GET /auditprofilemappingpolicies/:id/enforcers`

Returns the list of defenders that are affected by this mapping.

===== `GET /enforcerprofilemappingpolicies/:id/enforcers`

Returns the list of defenders affected by a defender profile mapping.

===== `GET /hostservicemappingpolicies/:id/enforcers`

Returns the list of defenders that are affected by this mapping.

===== `GET /enforcers/:id/auditprofiles`

Returns a list of the audit profiles that must be applied to this
defender.

===== `GET /enforcers/:id/debugbundles`

Retrieves the list of debug bundles.

===== `POST /enforcers/:id/debugbundles`

Uploads a debug bundle.

===== `GET /enforcers/:id/enforcerprofiles`

Returns the defender profile that must be used by a defender.

===== `POST /enforcers/:id/enforcerrefreshes`

Sends a defender refresh command.

===== `GET /enforcers/:id/hostservices`

Returns a list of the host services policies that apply to this
defender.

Parameters:

* `appliedServices` (`boolean`): Valid when retrieved for a given
defender and returns the applied services.
* `setServices` (`boolean`): Instructs the backend to cache the services
that were resolved. services.

===== `GET /enforcers/:id/poke`

Sends a poke empty object. This is used to ensure a defender is up and
running.

Parameters:

* `cpuload` (`float`): Deprecated.
* `enforcementStatus` (`enum(Failed | Inactive | Active)`): If set,
changes the enforcement status of the defender alongside with the poke.
* `forceFullPoke` (`boolean`): If set, it will trigger a full poke
(slower).
* `memory` (`integer`): Deprecated.
* `processes` (`integer`): Deprecated.
* `sessionClose` (`boolean`): If set, terminates a session for a
defender.
* `sessionID` (`string`): If set, sends the current session ID of a
defender.
* `status` (`enum(Registered | Connected | Disconnected)`): If set,
changes the status of the defender alongside with the poke.
* `ts` (`time`): time of report. If not set, local server time will be
used.
* `version` (`string`): If set, version of the current running defender.
* `zhash` (`integer`): Can be set to help backend target the correct
shard where the defender is stored.

===== `GET /enforcers/:id/trustedcas`

Returns the list of certificate authorities that should be trusted by
this defender.

Parameters:

* `type` (`enum(Any | X509 | SSH)`): Type of certificate to get.

==== Attributes

===== `FQDN` [`required`,`creation_only`]

Type: `string`

Contains the fully qualified domain name (FQDN) of the server where the
defender is running.

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `certificate` [`autogenerated`,`read_only`]

Type: `string`

The certificate of the defender.

===== `certificateRequest`

Type: `string`

If not empty during a create or update operation, the provided
certificate signing request (CSR) will be validated and signed by
Segment Console, providing a renewed certificate.

===== `collectInfo`

Type: `boolean`

Indicates to the defender whether or not it needs to collect
information.

===== `collectedInfo`

_This attribute is deprecated_.

Type: `map[string]string`

Represents the latest information collected by the defender.

===== `controller` [`autogenerated`,`read_only`]

Type: `string`

The Segment Console identifier managing this object. This property is
mostly useful when federating multiple Segment Consoles.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `currentVersion`

Type: `string`

The version number of the installed defender binary.

===== `description` [`max_length=1024`]

Type: `string`

Description of the object.

===== `enforcementStatus`

Type: `enum(Inactive | Active | Failed)`

Status of the enforcement for host services.

Default value:

[source,json]
----
"Inactive"
----

===== `lastCollectionID`

Type: `string`

Identifies the last collection.

===== `lastCollectionTime`

Type: `time`

Identifies when the information was collected.

===== `lastSyncTime`

Type: `time`

The time and date of the last heartbeat.

===== `localCA` [`autogenerated`]

Type: `string`

Contains the initial chain of trust for the defender. This value is only
given when you retrieve a single defender.

===== `logLevel`

Type: `enum(Info | Debug | Warn | Error | Trace)`

Log level of the defender.

Default value:

[source,json]
----
"Info"
----

===== `logLevelDuration`

Type: `string`

Determines the duration of which the log level will be active, using
https://golang.org/pkg/time/#example_Duration[Golang duration syntax].

Default value:

[source,json]
----
"10s"
----

===== `machineID`

Type: `string`

A unique identifier for every machine as detected by the defender. It is
based on hardware information such as the SMBIOS UUID, MAC addresses of
interfaces, or cloud provider IDs.

===== `metadata` [`creation_only`]

Type: `[]string`

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` [`required`,`max_length=256`]

Type: `string`

Name of the entity.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `operationalStatus`

Type: `enum(Registered | Connected | Disconnected | Initialized)`

The status of the defender.

Default value:

[source,json]
----
"Registered"
----

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `publicToken` [`autogenerated`,`read_only`]

Type: `string`

The public token of the server that will be included in the datapath and
is signed by the private certificate authority.

===== `startTime`

Type: `time`

The time and date on which this defender was started. The defender
reports this and the value is preserved across disconnects.

===== `subnets`

Type: `[]string`

Local subnets of this defender.

===== `unreachable` [`autogenerated`,`read_only`]

Type: `boolean`

Segment Console sets this value to `true` if it hasn’t heard from the
defender in the last five minutes.

===== `updateAvailable`

Type: `boolean`

If `true`, the defender version is outdated and should be updated.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== EnforcerLog

A defender log represents the log collected by an defender. Each
defender log can have partial or complete data. The collectionID is used
to aggregate the multipart data into one.

==== Example

[source,json]
----
{
  "collectionID": "xxx-xxx-xxx-xxx",
  "enforcerID": "xxx-xxx-xxx-xxx",
  "protected": false
}
----

==== Relations

===== `GET /enforcerlog`

Retrieves the list of enforcerlogs.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `POST /enforcerlog`

Creates a new enforcerlog.

===== `GET /enforcerlog/:id`

Retrieves the enforcerlog with the given ID.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `collectionID` [`required`]

Type: `string`

CollectionID is the ID of the defender log. CollectionID is used to
aggregate the multipart data.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `data`

Type: `string`

Represents the data collected by the defender.

===== `enforcerID` [`required`]

Type: `string`

ID of the defender.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `page`

Type: `integer`

Number assigned to each log in the increasing order.

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `title`

Type: `string`

Title of the log.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== EnforcerReport

Post a new defender statistics report.

==== Example

[source,json]
----
{
  "CPULoad": 10,
  "ID": "xxx-xxx-xxx-xxx",
  "memory": 10000,
  "name": "aporeto-enforcerd-xxx",
  "namespace": "/my/ns",
  "processes": 10,
  "timestamp": "2018-06-14T23:10:46.420397985Z"
}
----

==== Relations

===== `POST /enforcerreports`

Create a defender statistics report.

==== Attributes

===== `CPULoad`

Type: `float`

Total CPU utilization of the defender as a percentage of vCPUs.

===== `ID` [`required`]

Type: `string`

ID of the defender.

===== `memory`

Type: `integer`

Total resident memory used by the defender in bytes.

===== `name` [`required`]

Type: `string`

Name of the defender.

===== `namespace` [`required`]

Type: `string`

Namespace of the defender.

===== `processes`

Type: `integer`

Number of active processes of the defender.

===== `timestamp` [`required`]

Type: `time`

Date of the report.

=== EnforcerTraceReport

Post a new defender trace that determines how packets are.

==== Example

[source,json]
----
{
  "enforcerID": "5c6cce207ddf1fc159a104bf",
  "enforcerNamespace": "/acme/prod",
  "namespace": "/acme/prod/database",
  "puID": "5c6ccd947ddf1fc159a104b7"
}
----

==== Relations

===== `POST /enforcertracereports`

Create a defender trace report.

==== Attributes

===== `enforcerID` [`required`]

Type: `string`

ID of the defender where the trace was collected.

===== `enforcerNamespace` [`required`]

Type: `string`

Namespace of the defender where the trace was collected.

===== `namespace` [`required`]

Type: `string`

Namespace of the processing unit where the trace was collected.

===== `puID` [`required`]

Type: `string`

ID of the processing unit where the trace was collected.

=== PacketReport

Post a new packet tracing report.

==== Example

[source,json]
----
{
  "destinationPort": 11000,
  "encrypt": false,
  "enforcerID": "xxxx-xxx-xxxx",
  "enforcerNamespace": "/my/namespace",
  "event": "Rcv",
  "mark": 123123,
  "namespace": "/my/namespace",
  "packetID": 12333,
  "protocol": 6,
  "puID": "xxx-xxx-xxx",
  "rawPacket": "abcd",
  "sourcePort": 80,
  "timestamp": "2018-06-14T23:10:46.420397985Z",
  "triremePacket": true
}
----

==== Relations

===== `POST /packetreports`

Create a packet trace report.

==== Attributes

===== `TCPFlags`

Type: `integer`

Flags are the TCP flags of the packet.

===== `claims`

Type: `[]string`

Claims is the list of claims detected for the packet.

===== `destinationIP`

Type: `string`

The destination IP address of the packet.

===== `destinationPort` [`max_value=65536.000000`]

Type: `integer`

The destination port of a TCP or UDP packet.

===== `dropReason`

Type: `string`

If `event` is set to `Dropped`, contains the reason that the packet was
dropped. Otherwise empty.

===== `encrypt`

Type: `boolean`

Set to `true` if the packet was encrypted.

===== `enforcerID` [`required`]

Type: `string`

Identifier of the defender sending the report.

===== `enforcerNamespace` [`required`]

Type: `string`

Namespace of the defender sending the report.

===== `event` [`required`]

Type: `enum(Received | Transmitted | Dropped)`

The event that triggered the report.

===== `mark`

Type: `integer`

Mark is the mark value of the packet.

===== `namespace` [`required`]

Type: `string`

Namespace of the processing unit reporting the packet.

===== `packetID`

Type: `integer`

The ID of the IP header of the reported packet.

===== `protocol` [`max_value=255.000000`]

Type: `integer`

Protocol number.

===== `puID`

Type: `string`

The ID of the processing unit reporting the packet.

===== `rawPacket`

Type: `string`

The first 64 bytes of the packet.

Default value:

[source,json]
----
"abcd"
----

===== `sourceIP`

Type: `string`

The source IP address of the packet.

===== `sourcePort` [`max_value=65536.000000`]

Type: `integer`

The source port of the packet.

===== `timestamp` [`required`]

Type: `time`

The time-date stamp of the report.

===== `triremePacket`

Type: `boolean`

Set to `true` if the packet arrived with the Trireme options (default).

Default value:

[source,json]
----
true
----

=== PingPair

Represents a pair of ping probes.

==== Attributes

===== `request`

Type: link:#pingprobe[`pingprobe`]

Contains the request probe information.

===== `response`

Type: link:#pingprobe[`pingprobe`]

Contains the response probe information.

=== PingProbe

Represents the result of a unique ping probe. They are aggregated into a
PingResult.

==== Example

[source,json]
----
{
  "applicationListening": false,
  "claimsType": [
    "Transmitted"
  ],
  "enforcerID": "xxx-xxx-xxx-xxx",
  "enforcerNamespace": "/my/ns",
  "excludedNetworks": false,
  "isServer": false,
  "payloadSizeType": [
    "Transmitted"
  ],
  "pingID": "xxx-xxx-xxx-xxx",
  "remoteEndpointType": [
    "External"
  ],
  "remoteNamespaceType": [
    "Plain"
  ],
  "targetTCPNetworks": false,
  "type": [
    "Request"
  ]
}
----

==== Relations

===== `GET /pingprobes/:id`

Retrieves a ping result.

===== `POST /processingunits/:id/pingprobes`

Create a ping probe.

==== Attributes

===== `ACLPolicyAction`

Type: `string`

Action of the ACL policy.

===== `ACLPolicyID`

Type: `string`

ID of the ACL policy.

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `RTT`

Type: `string`

Time taken for a single request-response to complete.

===== `applicationListening`

Type: `boolean`

If true, application responded to the request.

===== `claims`

Type: `[]string`

Claims of the processing unit.

===== `claimsType` [`required`]

Type: `enum(Transmitted | Received)`

Type of claims reported.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `enforcerID` [`required`]

Type: `string`

ID of the defender.

===== `enforcerNamespace` [`required`]

Type: `string`

Namespace of the defender.

===== `enforcerVersion`

Type: `string`

Semantic version of the defender.

===== `error`

Type: `string`

A non-empty error indicates a failure.

===== `excludedNetworks`

Type: `boolean`

If true, destination IP is in `excludedNetworks`.

===== `fourTuple`

Type: `string`

Four tuple in the format sip:dip:spt:dpt.

===== `isServer`

Type: `boolean`

If true, the report was generated by the server.

===== `iterationIndex`

Type: `integer`

Holds the iteration number this probe is attached to.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `payloadSize`

Type: `integer`

Size of the payload attached to the packet.

===== `payloadSizeType` [`required`]

Type: `enum(Transmitted | Received)`

Type of the payload size.

===== `peerCertExpiry`

Type: `string`

Represents the expiry of the peer certificate.

===== `peerCertIssuer`

Type: `string`

Represents the issuer of the peer certificate.

===== `peerCertSubject`

Type: `string`

Represents the subject of the peer certificate.

===== `pingID` [`required`]

Type: `string`

PingID unique to a single ping control.

===== `policyAction`

Type: `string`

Action of the policy.

===== `policyID`

Type: `string`

ID of the policy.

===== `policyNamespace`

Type: `string`

ID of the policy.

===== `processingUnitID`

Type: `string`

ID of the reporting processing unit.

===== `protocol`

Type: `integer`

Protocol used for the communication.

===== `remoteController`

Type: `string`

Controller of the remote endpoint.

===== `remoteEndpointType` [`required`]

Type: `enum(ProcessingUnit | External)`

Represents the remote endpoint type.

===== `remoteNamespace`

Type: `string`

Namespace of the remote processing unit.

===== `remoteNamespaceType` [`required`]

Type: `enum(Plain | Hash)`

Type of the namespace reported.

===== `remoteProcessingUnitID`

Type: `string`

ID of the remote processing unit.

===== `seqNum`

Type: `integer`

Sequence number of the TCP packet. number.

===== `serviceID`

Type: `string`

ID of the service If the service type is a proxy.

===== `serviceType` [`autogenerated`,`read_only`]

Type: `string`

Type of the service.

===== `targetTCPNetworks`

Type: `boolean`

If true, destination IP is in `targetTCPNetworks`.

===== `type` [`required`]

Type: `enum(Request | Response)`

Type of the report.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== PingRequest

Initiates a ping request for defender debugging.

==== Example

[source,json]
----
{
  "iterations": 1,
  "refreshID": "xxxx-xxxx-xxxx"
}
----

==== Relations

===== `POST /pingrequests`

Initiate a new the ping request.

==== Attributes

===== `iterations` [`min_value=1.000000`,`max_value=20.000000`]

Type: `integer`

Number of probes that will be triggered.

Default value:

[source,json]
----
1
----

===== `pingID` [`autogenerated`,`read_only`]

Type: `string`

Unique ID generated for each ping request.

===== `refreshID` [`required`]

Type: `string`

Contains the refresh ID set by processing unit refresh event.

=== PingResult

Represents the results of a ping request.

==== Relations

===== `GET /pingresults`

Retrieves a ping result.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `errors` [`autogenerated`,`read_only`]

Type: `[]string`

May contain a list of errors that have happened during the collection.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `pingID` [`autogenerated`,`read_only`]

Type: `string`

Contains the Ping ID.

===== `pingPairs`

Type: link:#pingpair[`pingpair`]

Contains the result of aggregated ping pairs.

===== `refreshID` [`autogenerated`,`read_only`]

Type: `string`

Contains the refresh ID set by processing unit refresh event.

===== `remoteProbes`

Type: link:#remotepingprobe[`remotepingprobe`]

Contains information about missing probes in the result. This field will
be populated in the ping probe is managed by a remote controller
(federation) or is stored in a namespace you don’t have any permissions
on.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== RemotePingProbe

Represents information about a remote ping probe that is governed by a
different set of permissions.

==== Attributes

===== `controllerID` [`autogenerated`,`read_only`]

Type: `string`

The controller ID that manages the ping report.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

The namespace where the ping report is stored. Only applicable when the
remote controller is empty.

===== `namespaceType` [`autogenerated`,`read_only`]

Type: `enum(Plain | Hash)`

Type of the namespace reported. It can be hash or plain, depending on
various factors.

===== `probeID` [`autogenerated`,`read_only`]

Type: `string`

The ID of the probe. Only applicable when the remote controller is
empty.

=== TraceMode

Represents the tracing mode to apply to a processing unit.

==== Example

[source,json]
----
{
  "IPTables": false,
  "applicationConnections": false,
  "interval": "10s",
  "networkConnections": false
}
----

==== Attributes

===== `IPTables`

Type: `boolean`

Instructs the defenders to provide an iptables trace for a processing
unit.

===== `applicationConnections`

Type: `boolean`

Instructs the defender to send records for all application-initiated
connections.

===== `interval`

Type: `string`

Determines the length of the time interval that the trace must be
enabled, using https://golang.org/pkg/time/#example_Duration[Golang
duration syntax].

Default value:

[source,json]
----
"10s"
----

===== `networkConnections`

Type: `boolean`

Instructs the defender to send records for all network-initiated
connections.

=== TraceRecord

Represents a single trace record from the defender.

==== Example

[source,json]
----
{
  "TTL": 64,
  "chain": "PREROUTING",
  "destinationIP": "10.1.1.30",
  "destinationInterface": "en0",
  "destinationPort": 80,
  "length": 98,
  "packetID": 10,
  "protocol": 80,
  "ruleID": 10,
  "sourceIP": "10.1.1.30",
  "sourceInterface": "en0",
  "sourcePort": 80,
  "tableName": "raw",
  "timestamp": "2018-06-14T23:10:46.420397985Z"
}
----

==== Attributes

===== `TTL` [`required`,`max_value=255.000000`]

Type: `integer`

The time to live (TTL) value of the packet.

===== `chain` [`required`]

Type: `string`

Chain that the trace was collected from.

===== `destinationIP` [`required`]

Type: `string`

The destination IP.

===== `destinationInterface`

Type: `string`

The destination interface of the packet.

===== `destinationPort` [`required`,`min_value=1.000000`,`max_value=65536.000000`]

Type: `integer`

The destination UPD or TCP port of the packet.

===== `length` [`required`,`max_value=65536.000000`]

Type: `integer`

Length of the observed packet.

===== `packetID` [`required`]

Type: `integer`

The IP packet header ID.

===== `protocol` [`required`,`max_value=65536.000000`]

Type: `integer`

The protocol of the packet.

===== `ruleID` [`required`]

Type: `integer`

Priority index of the iptables entry that was hit.

===== `sourceIP` [`required`]

Type: `string`

Source IP of the packet.

===== `sourceInterface`

Type: `string`

Source interface of the packet.

===== `sourcePort` [`required`,`min_value=1.000000`,`max_value=65536.000000`]

Type: `integer`

Source TCP or UDP port of the packet.

===== `tableName` [`required`]

Type: `string`

The iptables name that the trace collected.

===== `timestamp` [`required`]

Type: `time`

The time-date stamp of the report.
