== policy/hooks

=== HookPolicy

Allows you to define hooks to the write operations in squall. Hooks are
sent to an external Rufus server that will do the processing and
eventually return a modified version of the object before we save it.

==== Example

[source,json]
----
{
  "certificateAuthority": "-----BEGIN CERTIFICATE-----
MIIBbjCCARSgAwIBAgIRANRbvVzTzBZOvMCb8BiKCLowCgYIKoZIzj0EAwIwJjEN
MAsGA1UEChMEQWNtZTEVMBMGA1UEAxMMQWNtZSBSb290IENBMB4XDTE4MDExNTE4
NDgwN1oXDTI3MTEyNDE4NDgwN1owJjENMAsGA1UEChMEQWNtZTEVMBMGA1UEAxMM
QWNtZSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJ/80HR51+vau
7XH7zS7b8ABA0e/TdBOg1NznbnXdXil1tDvWloWuH5+/bbaiEg54wksJHFXaukw8
jhTLU7zT56MjMCEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wCgYI
KoZIzj0EAwIDSAAwRQIhALwAZh2KLFFC1qfb5CqFHExlXS0PUltax9PvQCN9P0vl
AiBl7/st9u/JpERjJgirxJxOgKNlV6pq9ti75EfQtZZcQA==
-----END CERTIFICATE-----",
  "clientCertificate": "-----BEGIN CERTIFICATE-----
MIIBczCCARigAwIBAgIRALD3Vz81Pq10g7n4eAkOsCYwCgYIKoZIzj0EAwIwJjEN
MAsGA1UEChMEQWNtZTEVMBMGA1UEAxMMQWNtZSBSb290IENBMB4XDTE4MDExNzA2
NTM1MloXDTI3MTEyNjA2NTM1MlowGDEWMBQGA1UEAxMNY2xhaXJlLWNsaWVudDBZ
MBMGByqGSM49AgEGCCqGSM49AwEHA0IABOmzPJj+t25T148eQH5gVrZ7nHwckF5O
evJQ3CjSEMesjZ/u7cW8IBfXlxZKHxl91IEbbB3svci4c8pycUNZ2kujNTAzMA4G
A1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA
MAoGCCqGSM49BAMCA0kAMEYCIQCjAAmkQpTua0HR4q6jnePaFBp/JMXwTXTxzbV6
peGbBQIhAP+1OR8GFnn2PlacwHqWXHwkvy6CLPVikvgtwEdB6jH8
-----END CERTIFICATE-----",
  "clientCertificateKey": "-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGOXJI/123456789oamOu4tQAIKFdbyvkIJg9GME0mHzoAoGCCqGSM49
AwEHoUQDQgAE6bM8mP123456789AfmBWtnucfByQXk568lDcKNIQx6yNn+7txbwg
F9eXFkofGX3UgRtsHe123456789xQ1naSw==
-----END EC PRIVATE KEY-----",
  "continueOnError": false,
  "disabled": false,
  "endpoint": "https://hooks.hookserver.com/remoteprocessors",
  "endpointType": "URL",
  "fallback": false,
  "mode": "Pre",
  "name": "the name",
  "propagate": false,
  "propagationHidden": false,
  "protected": false,
  "selectors": [
    [
      "automation:name=myautomation"
    ]
  ],
  "subject": [
    [
      "$identity=processingunit"
    ]
  ]
}
----

==== Relations

===== `GET /hookpolicies`

Retrieves the list of hooks.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.
* `propagated` (`boolean`): Also retrieve the objects that propagate
down.

===== `POST /hookpolicies`

Creates a new hook.

===== `DELETE /hookpolicies/:id`

Deletes the hook with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /hookpolicies/:id`

Retrieves the hook with the given ID.

===== `PUT /hookpolicies/:id`

Updates the hook with the given ID.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `certificateAuthority`

Type: `string`

Contains the PEM block of the certificate authority used by the remote
endpoint.

===== `clientCertificate`

Type: `string`

Contains the client certificate that will be used to connect to the
remote endpoint. If provided, the private key associated with this
certificate must also be configured.

===== `clientCertificateKey`

Type: `string`

Contains the key associated with the `clientCertificate`. It must be
provided only when `clientCertificate` has been configured.

===== `continueOnError`

Type: `boolean`

If set to `true` and `mode` is in `Pre`, the request will be honored
even if calling the hook fails.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `description` [`max_length=1024`]

Type: `string`

Description of the object.

===== `disabled`

Type: `boolean`

Defines if the property is disabled.

===== `endpoint`

Type: `string`

Contains the full address of the remote processor endpoint.

===== `endpointType`

Type: `enum(URL | Automation)`

Defines the type of endpoint for the hook.

Default value:

[source,json]
----
"URL"
----

===== `expirationTime`

Type: `time`

If set the hook will be automatically deleted after the given time.

===== `fallback`

Type: `boolean`

Indicates that this is fallback policy. It will only be applied if no
other policies have been resolved. If the policy is also propagated it
will become a fallback for children namespaces.

===== `metadata` [`creation_only`]

Type: `[]string`

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `mode`

Type: `enum(Both | Post | Pre)`

Defines the type of hook.

Default value:

[source,json]
----
"Pre"
----

===== `name` [`required`,`max_length=256`]

Type: `string`

Name of the entity.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `propagate`

Type: `boolean`

Propagates the policy to all of its children.

===== `propagationHidden`

Type: `boolean`

If set to `true` while the policy is propagating, it won’t be visible to
children namespace, but still used for policy resolution.

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `selectors`

Type: `[][]string`

A tag or tag expression that identifies the automation that must be run
in case no endpoint is provided.

===== `subject`

Type: `[][]string`

Contains the tag expression that an object must match in order to
trigger the hook.

===== `triggerOperations`

Type: `[]string`

Select on which operation(s) you want to the hook to trigger. An empty
list. Only means all operations. You can only set any combination of
`create`, `update` or `delete`. Any other value will trigger a
validation error.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.

=== RemoteProcessor

Hook to integrate a Segment service.

==== Example

[source,json]
----
{
  "claims": [
    "@auth:realm=certificate",
    "@auth:commonname=john"
  ],
  "input": "{
  \"name\": \"hello\",
  \"description\": \"hello\",
}",
  "mode": "Pre",
  "namespace": "/my/namespace",
  "operation": "create",
  "targetIdentity": "processingunit"
}
----

==== Relations

===== `POST /remoteprocessors`

This should be be here.

==== Attributes

===== `claims` [`required`]

Type: `[]string`

Represents the claims of the currently managed object.

===== `input` [`required`]

Type: `json.RawMessage`

Represents data received from the service.

===== `mode`

Type: `enum(Post | Pre)`

Defines the hook’s type.

===== `namespace` [`required`]

Type: `string`

Represents the current namespace.

===== `operation` [`required`]

Type: `elemental.Operation`

Defines the operation that is currently handled by the service.

===== `output` [`autogenerated`,`read_only`]

Type: `_elemental_identifiable`

Returns `OutputData` filled with the processor information.

===== `requestID`

Type: `string`

Gives the ID of the request coming from the main server.

===== `targetIdentity` [`required`]

Type: `string`

Represents the identity name of the managed object.
