== visualization/depmaps

=== DependencyMap

Returns a data structure representing the graph of all processing units
and their connections in a particular namespace, in a given time window.
To pass the time window you can use the query parameters
`startAbsolute`, `endAbsolute`, `startRelative`, `endRelative`.

For example:

`/dependencymaps?startAbsolute=1489132800000&endAbsolute=1489219200000`.

==== Relations

===== `GET /dependencymaps`

Retrieves the dependency map of a namespace.

Parameters:

* `tag` (`string`): Only show objects with the given tags in the
dependency map.
* `view` (`string`): Set the view query for grouping the dependency map.
* `viewSuggestions` (`boolean`): Also return the view suggestions.
* `endAbsolute` (`time`): Set the absolute end of the time window.
* `endRelative` (`duration`): Set the relative end of the time window.
* `startAbsolute` (`time`): Set the absolute start of the time window.
* `startRelative` (`duration`): Set the relative start of the time
window.
* `flowOffset` (`duration`): Deprecated. This does not do anything
anymore.
* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

Mandatory Parameters

(`endRelative`) or (`startRelative`) or (`startRelative` and
`endRelative`) or (`startRelative` and `endAbsolute`) or
(`startAbsolute` and `endRelative`) or (`startAbsolute` and
`endAbsolute`)

==== Attributes

===== `edges` [`read_only`]

Type: link:#graphedge[`+map[string]graphedge+`]

The edges of the map.

===== `groups` [`read_only`]

Type: link:#graphgroup[`+map[string]graphgroup+`]

Provides information about the group values.

===== `nodes` [`read_only`]

Type: link:#graphnode[`+map[string]graphnode+`]

Refers to the nodes of the map.

===== `viewSuggestions` [`read_only`]

Type: `[]string`

Provides suggested views based on relevant tags.

=== GraphEdge

Represents an edge from the dependency map.

==== Example

[source,json]
----
{
  "acceptedFlows": false,
  "destinationType": "ProcessingUnit",
  "encrypted": false,
  "observedAcceptedFlows": false,
  "observedEncrypted": false,
  "observedRejectedFlows": false,
  "rejectedFlows": false,
  "sourceType": "ProcessingUnit"
}
----

==== Relations

===== `GET /graphedges`

Retrieves the graph edges.

Parameters:

* `endAbsolute` (`time`): Set the absolute end of the time window.
* `endRelative` (`duration`): Set the relative end of the time window.
* `startAbsolute` (`time`): Set the absolute start of the time window.
* `startRelative` (`duration`): Set the relative start of the time
window.
* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

Mandatory Parameters

(`endRelative`) or (`startRelative`) or (`startRelative` and
`endRelative`) or (`startRelative` and `endAbsolute`) or
(`startAbsolute` and `endRelative`) or (`startAbsolute` and
`endAbsolute`)

==== Attributes

===== `acceptedFlows`

Type: `boolean`

Number of accepted flows in the edge.

===== `destinationController`

Type: `string`

Name of the remote destination controller if different than the current
one.

===== `destinationID`

Type: `string`

ID of the destination `GraphNode` of the edge.

===== `destinationType`

Type:
`enum(ProcessingUnit | ExternalNetwork | Namespace | Node | RemoteController)`

Type of the destination `GraphNode` of the edge.

===== `encrypted`

Type: `boolean`

The number of encrypted flows in the edge.

===== `firstSeen`

Type: `time`

Contains the date when the edge was first seen.

===== `flowID`

Type: `string`

Identifier of the edge.

===== `lastSeen`

Type: `time`

Contains the date when the edge was last seen.

===== `namespace`

Type: `string`

Namespace of the object that reported the flow.

===== `observedAcceptedFlows`

Type: `boolean`

Number of accepted observed flows.

===== `observedEncrypted`

Type: `boolean`

Number of encrypted observed flows.

===== `observedRejectedFlows`

Type: `boolean`

Number of rejected observed flows.

===== `rejectedFlows`

Type: `boolean`

Number of rejected flows in the edge.

===== `remoteNamespace`

Type: `string`

Namespace of the object that was targeted by the flow.

===== `sourceController`

Type: `string`

Name of the remote source controller if different than the current one.

===== `sourceID`

Type: `string`

ID of the source `GraphNode` of the edge.

===== `sourceType`

Type:
`enum(ProcessingUnit | ExternalNetwork | Namespace | Node | RemoteController)`

Type of the source `GraphNode` of the edge.

=== GraphGroup

Represents an group of nodes from the dependency map.

==== Attributes

===== `ID`

Type: `string`

Identifier of the group.

===== `color`

Type: `string`

Color to use for the group.

===== `match`

Type: `[][]string`

List of tags that were used to create this group.

===== `name`

Type: `string`

Name of the group.

===== `parentID`

Type: `string`

ID of the parent group, if any.

=== GraphNode

Represents an node from the dependency map.

==== Example

[source,json]
----
{
  "type": "Docker",
  "unreachable": false
}
----

==== Relations

===== `GET /graphnodes`

Retrieves the pu nodes.

Parameters:

* `endAbsolute` (`time`): Set the absolute end of the time window.
* `endRelative` (`duration`): Set the relative end of the time window.
* `startAbsolute` (`time`): Set the absolute start of the time window.
* `startRelative` (`duration`): Set the relative start of the time
window.
* `archived` (`boolean`): Also retrieve the objects that have been
archived.
* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

Mandatory Parameters

(`endRelative`) or (`startRelative`) or (`startRelative` and
`endRelative`) or (`startRelative` and `endAbsolute`) or
(`startAbsolute` and `endRelative`) or (`startAbsolute` and
`endAbsolute`)

==== Attributes

===== `ID`

Type: `string`

Identifier of object represented by the node.

===== `enforcementStatus`

Type: `string`

Enforcement status of processing unit represented by the node.

===== `firstSeen`

Type: `time`

Contains the date when the edge was first seen.

===== `groupID`

Type: `string`

ID of the group the node is eventually part of.

===== `images`

Type: `[]string`

List of images.

===== `lastSeen`

Type: `time`

Contains the date when the edge was last seen.

===== `name`

Type: `string`

Name of object represented by the node.

===== `namespace`

Type: `string`

Namespace of object represented by the node.

===== `status`

Type: `string`

Status of object represented by the node.

===== `tags`

Type: `[]string`

Tags of object represented by the node.

===== `type`

Type:
`enum(Docker | ExternalNetwork | Volume | Claim | Node | Namespace | RemoteController)`

Type of object represented by the node.

===== `unreachable`

Type: `boolean`

If `true` the node is marked as unreachable.

===== `vulnerabilityLevel`

Type: `string`

Tags of object represented by the node.

=== IPInfo

Provides information about IP address resolution.

==== Relations

===== `GET /ipinfos`

Returns information about an IP address given as parameters.

Parameters:

* `ip` (`string`): List of IPs to resolve.

Mandatory Parameters

`ip`

==== Attributes

===== `IP` [`autogenerated`,`read_only`]

Type: `string`

The IP address.

===== `error` [`autogenerated`,`read_only`]

Type: `string`

Error that occurred during resolution.

===== `records` [`autogenerated`,`read_only`]

Type: `map[string]string`

List of DNS records associated with the IP address.

=== PolicyGraph

Returns a data structure representing the policy graph of all selected
processing units and their possible connectivity based on the current
policies associated with the namespace. Users can define a selector of
processing units in which they are interested or define the identity
tags of a virtual processing unit that is not yet activated.

==== Example

[source,json]
----
{
  "policyType": "Authorization",
  "selectors": [
    [
      "$identity=processingunit"
    ]
  ]
}
----

==== Relations

===== `POST /policygraphs`

Retrieve a policy graph.

Parameters:

* `view` (`string`): Set the view query for grouping the dependency map.

==== Attributes

===== `PUIdentity`

Type: `[]string`

The set of tags that a future-activated processing unit will have for
which the user wants to evaluate policies and understand its
connectivity options.

===== `dependencyMap`

Type: link:#dependencymap[`dependencymap`]

Contains the output of the policy evaluation. It is the same type of
dependency map as created by other APIs.

===== `policyType`

Type: `enum(Authorization | Infrastructure | Combined)`

Identifies the type of policy that should be analyzed: `Authorization`
(default), `Infrastructure`, or `Combined`.

Default value:

[source,json]
----
"Authorization"
----

===== `selectors`

Type: `[][]string`

Contains the tag expression that a processing unit must match in order
to evaluate policy for it.

=== SuggestedPolicy

Allows you to obtain network policy suggestions.

==== Relations

===== `GET /suggestedpolicies`

Retrieves a list of network policy suggestions.

Parameters:

* `filterAction` (`enum(include | exclude)`): Action to take with the
filter tags.
* `filterTags` (`string`): Tags to filter in the policy suggestions.
* `endAbsolute` (`time`): Set the absolute end of the time window.
* `endRelative` (`duration`): Set the relative end of the time window.
* `startAbsolute` (`time`): Set the absolute start of the time window.
* `startRelative` (`duration`): Set the relative start of the time
window.
* `flowOffset` (`duration`): Deprecated. This does not do anything
anymore.

Mandatory Parameters

(`endRelative`) or (`startRelative`) or (`startRelative` and
`endRelative`) or (`startRelative` and `endAbsolute`) or
(`startAbsolute` and `endRelative`) or (`startAbsolute` and
`endAbsolute`)

==== Attributes

===== `networkAccessPolicies`

Type: link:#networkaccesspolicy[`networkaccesspolicy`]

List of suggested network policies.
