== policy/access

=== AccessReport

Represents any access made by the user.

==== Example

[source,json]
----
{
  "action": "Accept",
  "enforcerID": "xxx-xxx-xxx",
  "enforcerNamespace": "/my/namespace",
  "processingUnitID": "xxx-xxx-xxx-xxx",
  "processingUnitName": "pu1",
  "processingUnitNamespace": "/my/ns",
  "type": "SSHLogin"
}
----

==== Relations

===== `POST /accessreports`

Create an access report.

==== Attributes

===== `action` [`required`]

Type: `enum(Accept | Reject)`

Action applied to the access.

===== `claimHash`

Type: `string`

Hash of the claims used to communicate.

===== `enforcerID` [`required`]

Type: `string`

Identifier of the defender.

===== `enforcerNamespace` [`required`]

Type: `string`

Namespace of the defender.

===== `processingUnitID`

Type: `string`

ID of the processing unit of the report.

===== `processingUnitName`

Type: `string`

Name of the processing unit of the report.

===== `processingUnitNamespace`

Type: `string`

Namespace of the processing unit of the report.

===== `reason`

Type: `string`

This field is only set if `action` is set to `Reject`. It specifies the
reason for the rejection.

===== `timestamp`

Type: `time`

Date of the report.

===== `type` [`required`]

Type: `enum(SSHLogin | SSHLogout | SudoEnter | SudoExit)`

Type of the report.

=== UserAccessPolicy

The defender policy that controls user access.

==== Example

[source,json]
----
{
  "disabled": false,
  "name": "the name",
  "propagate": false,
  "protected": false
}
----

==== Relations

===== `GET /useraccesspolicies`

Retrieves the list of user access policies.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.
* `propagated` (`boolean`): Also retrieve the objects that propagate
down.

===== `POST /useraccesspolicies`

Creates a new defender policy.

===== `DELETE /useraccesspolicies/:id`

Deletes the policy with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /useraccesspolicies/:id`

Retrieves the policy with the given ID.

Parameters:

* `propagated` (`boolean`): Also retrieve the objects that propagate
down.

===== `PUT /useraccesspolicies/:id`

Updates the policy with the given ID.

==== Attributes

===== `ID` [`identifier`,`autogenerated`,`read_only`]

Type: `string`

Identifier of the object.

===== `activeDuration` [`format=^[0-9]+[smh]$`]

Type: `string`

Defines for how long the policy will be active according to the
`activeSchedule`.

===== `activeSchedule`

Type: `string`

Defines when the policy should be active using the cron notation. The
policy will be active for the given `activeDuration`.

===== `allowedSudoUsers`

Type: `[]string`

Indicates the list of user who can use `sudo` commands.

===== `annotations`

Type: `map[string][]string`

Stores additional information about an entity.

===== `associatedTags`

Type: `[]string`

List of tags attached to an entity.

===== `createTime` [`autogenerated`,`read_only`]

Type: `time`

Creation date of the object.

===== `description` [`max_length=1024`]

Type: `string`

Description of the object.

===== `disabled`

Type: `boolean`

Defines if the property is disabled.

===== `expirationTime`

Type: `time`

If set the policy will be automatically deleted after the given time.

===== `metadata` [`creation_only`]

Type: `[]string`

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` [`required`,`max_length=256`]

Type: `string`

Name of the entity.

===== `namespace` [`autogenerated`,`read_only`]

Type: `string`

Namespace tag attached to an entity.

===== `normalizedTags` [`autogenerated`,`read_only`]

Type: `[]string`

Contains the list of normalized tags of the entities.

===== `object`

Type: `[][]string`

Contains the tag expression matching the defenders the subject is
allowed to connect to.

===== `propagate`

Type: `boolean`

Propagates the policy to all of its children.

===== `protected`

Type: `boolean`

Defines if the object is protected.

===== `subject`

Type: `[][]string`

Contains the tag expression the tags need to match for the policy to
apply.

===== `updateTime` [`autogenerated`,`read_only`]

Type: `time`

Last update date of the object.
