== policy/dns

=== DNSLookupReport

A DNS lookup report is used to report a DNS lookup that is happening on
behalf of a processing unit. If the DNS server is on the standard UDP
port 53 then the defender can proxy the DNS traffic and make a report.
The report indicate whether or not the lookup was successful.

==== Example

[source,json]
----
{
  "action": "Accept",
  "enforcerNamespace": "/my/namespace",
  "processingUnitID": "xxx-xxx-xxx",
  "processingUnitNamespace": "/my/namespace",
  "resolvedName": "www.google.com",
  "sourceIP": "10.0.0.1",
  "value": 1
}
----

==== Relations

===== `POST /dnslookupreports`

Create a DNS Lookup report.

==== Attributes

===== `action` [`required`]

Type: `enum(Accept | Reject)`

Action of the DNS request.

===== `enforcerID`

Type: `string`

ID of the defender.

===== `enforcerNamespace` [`required`]

Type: `string`

Namespace of the defender.

===== `processingUnitID` [`required`]

Type: `string`

ID of the PU.

===== `processingUnitNamespace` [`required`]

Type: `string`

Namespace of the PU.

===== `reason`

Type: `string`

This field is only set when the lookup fails. It specifies the reason
for the failure.

===== `resolvedName` [`required`]

Type: `string`

name used for DNS resolution.

===== `sourceIP` [`required`]

Type: `string`

Type of the source.

===== `timestamp`

Type: `time`

Time and date of the log.

===== `value` [`required`]

Type: `integer`

Number of times the client saw this activity.
