== Create and Manage Dashboards

Track, visualize, share the metrics that matter most to you and your team with Prisma Cloud custom dashboards. Add Widgets with visual representations in various formats such as line and bar graphs and pie charts are available to track key metrics such as assets with the most urgent alerts and vulnerabilities, resource compliance trend charts and top risks to remediate. Share custom dashboards with your management team to quantify your progress in firming up your security posture. 

[.task]
[#createdashboards]
=== Create New Dashboards

Follow the steps below to create your customized dashboard:

[.procedure]
. Select *Dashboards* from the top navigation bar of the Prisma Cloud administrative console. 

. Choose *Add Dashboards* to create your custom dashboard.

. Give you new dashboard a unique identifier in the *Add Dashboard* drop-down. Click *Add New Dashboard* to complete dashboard creation.

. Select your new dashboard from the Dashboards top navigation panel. Select *Add Widgets* to drag and drop widgets from the *Add Widgets* bar to your custom dashboard. You can also use the search bar to filter your search to locate the widgets with the attributes required for your custom dashboard.  

. Select the menu icon located adjacent to your dashboard name to copy or delete any dashboard. 

[.task]
[#managewidgets]  
=== Manage Widgets

After you have added any widget to your dashboard you have multiple options to fine-tune the visualization of the data. Move your cursor to the top middle portion of any widget to re-position it as needed. You can also edit, duplicate or delete graphics in the widget, as described below:

[.procedure]
. Select the *Toggle Table* icon to convert the data visualization in a widget to a table. You can also choose the *Full Screen* button to expand widget dimensions to the maximum size. 

. You can edit the views in any widget once you have added them to your custom dashboard. Follow these steps to edit a widget:

. Select the *Edit* button from the Widget menu. The editable options vary from widget to widget and may include chart name, chart variable such as number of vulnerabilities listed, data source for compliance trends over time etc.

. Select the *Clone* button from the Widget menu to duplicate the widget. This generates a cloned widget.

. Choose the *Delete* button from the Widget menu to delete any widget from a dashboard. 

[#managedashboards] 
=== Manage Dashboards

TBD section on managing dashboards. 