== Prisma Cloud Reports

Keep your stakeholders updated on your progress in securing your cloud environment, by sharing timely information on the status of your cloud assets, with Prisma Cloud *Reports*. Easily discover, create, and share reports on data such as compliance and configuration status, risk assessment, resources with open alerts, operationalization overview, and more from one centralized location. You can create a new report and access previously created reports from the top navigation panel on the Prisma Cloud administrative console. 


=== Reports At a Glance

Focus in and share the metrics that matter most to you and your team. Learn more about the various types of *Reports* you can currently generate in Prisma Cloud in the table below. 

[cols="30%a,70%a"]
|===

|*Report Type*
|*Description*

|Compliance  
|Create reports based on a cloud compliance standard for immediate viewing or download, or schedule recurring reports to monitor compliance over time.  


|Alerts 
|Two types of alerts reports are available:

* Cloud Security Assessment report: A PDF report that summarizes the risks from open alerts in monitored cloud accounts for any given cloud. 
* Business Unit report: A .csv file that lists all resources with open alerts trigerred by policies based on a compliance standard. Generate the report on an on-demand basis or set up a recurring schedule. 


|Cloud Security
|A comprehensive report that captures your progress in operationalizing Prisma Cloud. Also included is an extensive Metrics Overview capturing key data points such as, anomalous threats detected, vulnerabilities trends and regulatory compliance achieved.  

|Command Center
|Share Command Center reports with stakeholders to keep them abreast of the security and compliance status of your cloud assets, as displayed on the Command Center dashboard. 
*\\add new xref*

|CloudLens 360
|Reports within CloudLens 360 help you identify the immediate threats found at the attack surface.
*\\add new xref* 
//Add more details from Meghna 

|===

=== Next Steps

* xref:create-and-manage-reports.adoc[Create a Custom Report]
* xref:create-and-manage-reports.adoc#manage[Manage Generated Reports]
* .CSV Reports *TBD*
