:topic_type: task
[#kubernetes-credentials]
[.task]
== Kubernetes Credentials

Kubernetes stores cluster authentication information in a YAML file known as kubeconfig.
The kubeconfig file grants access to clients, such as kubectl, to run commands against the cluster.
By default, kubeconfig is stored in _$HOME/.kube/config_.

Prisma Cloud uses the kubeconfig credential to deploy and upgrade Defender DaemonSets directly from the xref:../../install/install_defender/install_cluster_container_defender.adoc[Console UI].
If you plan to manage DaemonSets from the command line with kubectl, you don't need to create this type of credential.

The user or service account in your kubeconfig must have permissions to create and delete the following resources:

* ClusterRole
* ClusterRoleBinding
* DaemonSet
* Secret
* ServiceAccount

// https://github.com/twistlock/twistlock/issues/14707
NOTE: Prisma Cloud doesn't currently support kubeconfig credentials for Google Kubernetes Engine (GKE) or AWS Elastic Kubernetes Service(EKS).
The kubeconfig for these clusters require an external binary for authentication (specifically the Google Cloud SDK and aws-iam-authenticator, respectively), and Prisma Cloud Console doesn't ship with these binaries.

[.procedure]
. Open Console, and go to *Manage > Authentication > Credentials Store*.

. Click *Add credential*, and enter the following values:

.. In *Name*, enter a label to identify the credential.

.. In *Type* , select *Kubeconfig*.

.. In *Kubeconfig*, paste the contents of your _kubeconfig_ file.
