== Alibaba Cloud RAM password policy does not expire in 90 days


*Policy Details* 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 00a4e900-ca63-470f-9607-b7ad5cdd3ab3

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RAMPasswordPolicyExpiration.py[CKV_ALI_16]

|Severity
|LOW

|Subtype
|Build, Run

|Frameworks
|Terraform

|=== 



*Description* 


This policy identifies Alibaba Cloud accounts for which do not have password expiration set to 90 days or less.
As a best practice, change your password every 90 days or sooner to ensure secure access to the Alibaba Cloud console.

=== Fix - Runtime


*Alibaba Cloud Portal* 



. Log in to Alibaba Cloud Portal

. Go to Resource Access Management (RAM) service

. In the left-side navigation pane, click on 'Settings'

. In the 'Security Settings' tab, In the 'Password Strength Settings' Section, Click on 'Edit Password Rule'

. In the 'Password Validity Period' field, enter 90 or less based on your requirement.

. Click on 'OK'

. Click on 'Close'

=== Fix - Buildtime


*Terraform* 




[source,go]
----
{
  "codes": [
    {
      "code": "TBD",
      "language": "go"
    }
  ]
}
----
