== The twistcli tool

The twistcli tool is a command-line control and configuration tool. It
ships with your Prisma Cloud release and can be found in the Prisma Cloud
release tarball. Support is provided for both Linux and MacOs.

The twistcli tool provides a number of functions:

- Scanning images for vulnerabilities and compliance issues. This is
    useful when you're building custom tooling, or when you're using a
    CI tool for which Prisma Cloud does not provide a native plugin.
- Deploying (installing and uninstalling) Console and Defender across
    all environments.
- Downloading the latest threat data from the Intelligence Stream for
    transfer to an air-gapped environment.
- Packaging log files and other relevant data from your environment
    and optionally uploading that data so that Prisma Cloud Support can
    help debug issues.
- Interacting with Serverless and Fargate artifacts to automatically
    produce the artifacts necessary to run workloads in Serverless or
    Fargate.

For more information about twistcli, see the support article
https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-guide-compute/latest/tools/twistcli.html[here].
