== AWS RDS cluster not configured with IAM authentication


*Policy Details* 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 252430b3-1996-496c-9257-ad054cd24a5f

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/RDSClusterIAMAuthentication.py[CKV_AWS_162]

|Severity
|MEDIUM

|Subtype
|Build, Run

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



*Description* 


IAM authentication uses AWS Identity and Access Management (IAM) to authenticate users and applications that connect to your RDS database.
This can be more secure than traditional password-based authentication, as it allows you to use IAM policies and multi-factor authentication to control access to your database.

=== Fix - Buildtime


*Terraform* 


* *Resources:* aws_rds_cluster
* *Arguments:* iam_database_authentication_enabled


[source,go]
----
{
  "codes": [
    {
      "code": "resource "aws_rds_cluster" "enabled" {
\t...
+ iam_database_authentication_enabled = true
}",
      "language": "go",
      "name": "aws_s3_bucket.test.tf"
    }
  ]
}
----


*CloudFormation* 


* *Resources:* AWS::RDS::DBCluster
* *Arguments:* Properties.EnableIAMDatabaseAuthentication


[source,yaml]
----
{
  "codes": [
    {
      "code": "Resources:
  Enabled:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      ...
+     EnableIAMDatabaseAuthentication: true",
      "language": "yaml"
    }
  ]
}
----
