== Azure Service Bus Without Managed Identity Provider
// Ensure that Managed identity provider is enabled for Azure Service Bus.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| fac9bc8b-785e-4c70-b3cc-03fa0efe158d

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureServicebusIdentityProviderEnabled.py[CKV_AZURE_202]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Service Bus is a comprehensive messaging service on Azure, offering robust resilience and failover capabilities. For enhanced security, Azure Service Bus supports managed identities.

Managed identities for Azure resources provide Azure services with a managed identity in Azure AD. You can use this identity to authenticate to services that support Azure AD authentication, without needing credentials in your code.

This policy ensures that the Azure Service Bus uses a managed identity provider for authentication and authorization. This increases the security by leveraging Azure AD's identity services and eliminating the need to manage secrets or other credentials manually.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_servicebus_namespace

*Arguments:* 
- identity

[source,terraform]
----
resource "azurerm_servicebus_namespace" "example" {
  name                = "example-namespace"
  # ... other configurations ...

+ identity {
+   type = "SystemAssigned"
+ }

  # ... other configurations ...
}
----

