== Azure Service Bus with Local Authentication Enabled
// Ensure Azure Service Bus Local Authentication is disabled.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 06857b33-0c83-4769-8f92-dad77fbd6d76

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureServicebusLocalAuthDisabled.py[CKV_AZURE_203]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Service Bus is a messaging service on Azure that supports robust resilience and failover capabilities. To enhance security, it is recommended to disable local authentication and leverage centralized authentication methods such as Azure AD.

Local authentication can potentially allow users with access to the local machine to authenticate, which might not be in line with the enterprise's security policies. This policy ensures that local authentication is disabled for the Azure Service Bus, enforcing the use of more secure authentication methods.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_servicebus_namespace

*Arguments:* 
- local_auth_enabled

[source,terraform]
----
resource "azurerm_servicebus_namespace" "example" {
  name                = "example-namespace"
  # ... other configurations ...

+ local_auth_enabled = false

  # ... other configurations ...
}
----

