== Azure CosmosDB does not have Local Authentication disabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 1bd00a0d-831d-4145-a986-59999733b079

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/CosmosDBLocalAuthDisabled.py[CKV_AZURE_140]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description

Disabling local authentication for Azure CosmosDB can help improve the security of your database.
Local authentication allows users to access the database using a local account and password, rather than an Azure Active Directory (Azure AD) account.
By disabling local authentication, you can ensure that all users must authenticate using an Azure AD account.
This can help prevent unauthorized access to the database, and can also help protect against potential security threats such as data breaches or unauthorized access.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_cosmosdb_account
* *Arguments:* local_authentication_disabled


[source,go]
----
resource "azurerm_cosmosdb_account" "pass" {
  name                          = "pike-sql"
  location                      = "uksouth"
  resource_group_name           = "pike"
  offer_type                    = "Standard"
  kind                          = "GlobalDocumentDB"
  local_authentication_disabled = true
  enable_free_tier              = true

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }
----

