== Java


*Description* 


Java is a programming language and computing platform first released by Sun Microsystems in 1995.
It has since evolved to power a large share of today's digital world, providing one of the most reliable platforms upon which many services and applications are built.
New, innovative products and digital services designed for the future continue to rely on Java today.


*Package Managers* 




*Maven Maven is used for project build automation using Java.* 


It helps you map out the structure of a particular software and its different dependencies.
It uses an XML file to describe the project you are building, the dependencies of the software with regards to third-party modules and parts, the build order, and the needed plugins.
There are also pre-defined targets for tasks such as packaging and compiling.
Files:  `pom.xml`


*Gradle Gradle is a fully-open source build automation system that uses the concepts you see on Apache Maven and Apache Ant.* 


It uses a domain-specific language based on the programming language Groovy, differentiating it from Apache Maven - which uses XML for its project configuration.
It also determines the order of tasks run by using a directed acyclic graph.
Files:  `build.gradle` `gradle.properties` `build.gradle.kts`


....
{
    "data": {
        "0-0": "Maven",
        "h-0": "Package manager",
        "h-1": "Scan",
        "h-2": "Fix",
        "h-3": "Dependency tree",
        "h-4": "Licenses",
        "1-0": "Gradle",
        "0-1": "\u2714\ufe0f",
        "1-1": "\u2714\ufe0f",
        "1-2": "\u2714\ufe0f",
        "0-2": "\u2714\ufe0f",
        "0-3": "\u2714\ufe0f",
        "1-3": "\u2714\ufe0f",
        "1-4": "\u2714\ufe0f",
        "0-4": "\u2714\ufe0f"
    },
    "cols": 5,
    "rows": 2
}
....
