== Protecting Kubernetes hosts

//'''
//
//title: Protecting Kubernetes hosts
//type: single
//url: "/3.14/secure/secure-hosts/k8s/"
//weight: 20
//menu:
//  3.14:
//    parent: "secure-hosts"
//    identifier: "protect-k8s-host"
//canonical: https://docs.aporeto.com/saas/secure/secure-hosts/k8s/
//aliases: [
//  "../setup/secure-hosts/k8s/"
//]
//
//'''

=== About protecting Kubernetes hosts

In order to enable host protection for the hosts, we will apply a set of policies that will do the following:

* Instruct the enforcers to control incoming/outgoing traffic to the host processes.
* Enable SSH access to the host.
* Enable communication between the master hosts and the kubelet.
* Enable communication between the kubelet (the hosts) and all processing units.

[#_prerequisites]
=== Prerequisites

Before you continue, ensure that you have:

* Installed the Aporeto enforcer xref:../../start/enforcer/k8s.adoc[as a DaemonSet] or xref:../../start/enforcer/linux.adoc[as a service].
* xref:../../start/apoctl/apoctl.adoc[Installed `apoctl`].

=== Configure apoctl and namespace

The `apoctl` utility must be installed.
Configure the namespace to be the base Aporeto namespace of your Kubernetes cluster in Aporeto.
If you have followed the installation instructions as mentioned in <<_prerequisites,Prerequisites>>, you have to update your `APOCTL_NAMESPACE` variable like this:

[,console]
----
export APOCTL_NAMESPACE="${APOCTL_NAMESPACE}/${CLUSTER}"
----

=== Create basic network policies

The moment we activate host services *all* traffic to the hosts will be blocked.
It is very important that you create the right policies *before* enabling the host services.

[TIP]
====
We recommend that you take some time to review the policies and understand them before you proceed.
All policies are very wide open on purpose.
Test them all like this first before you start to narrow them down.
====

[WARNING]
====
If you do not configure the policies first, you might bring down your cluster and lock yourself out!
====

Use the following policy configuration.
Create a file called `networkpolicy.yaml` with the following contents:

[,yaml]
----
label: k8s-node-network-access
data:
  externalnetworks:
  - name: all-tcp
    description: TCP Traffic - All Ports
    associatedTags:
    - ext:name=all-tcp
    entries:
    - 0.0.0.0/0
    ports:
    - '1:65535'
    protocols:
    - tcp

  - name: all-udp
    description: UDP Traffic - All Ports
    associatedTags:
    - ext:name=all-udp
    entries:
    - 0.0.0.0/0
    ports:
    - '1:65535'
    protocols:
    - udp

  - name: metadata-server-tcp
    description: Metadata Server (TCP) - used in GCP and AWS
    associatedTags:
    - ext:name=metadata-server-tcp
    entries:
    - 169.254.169.254/32
    ports:
    - '1:65535'
    protocols:
    - tcp

  - name: metadata-server-udp
    description: Metadata Server (UDP) - used in GCP and AWS
    associatedTags:
    - ext:name=metadata-server-udp
    entries:
    - 169.254.169.254/32
    ports:
    - '1:65535'
    protocols:
    - udp

  networkaccesspolicies:
  - name: allow-host-egress-all
    description: Allow all outgoing traffic from Kubernetes nodes
    action: Allow
    logsEnabled: true
    subject:
    - - hs:name=host
    object:
    - - ext:name=metadata-server-tcp
    - - ext:name=metadata-server-udp
    - - ext:name=all-tcp
    - - ext:name=all-udp

  - name: allow-kubelet-egress-pus
    description: Allow outgoing traffic from the Kubelet on Kubernetes nodes to PUs
    action: Allow
    logsEnabled: true
    propagate: true
    subject:
    - - hs:name=kubelet
    # unfortunately right now, egress traffic from host services will look like as it is coming from the host
    - - hs:name=host
    object:
    - - $identity=processingunit

  - name: allow-host-ingress-metadata
    description: Allow Incoming access from the Metadata Server (AWS or GCP)
    action: Allow
    logsEnabled: true
    subject:
    - - ext:name=metadata-server-tcp
    object:
    - - hs:name=host

  - name: allow-ssh-ingress-all
    description: Allow Incoming SSH access
    action: Allow
    logsEnabled: true
    subject:
    - - ext:name=all-tcp
    object:
    - - hs:name=ssh

  - name: allow-kubelet-ingress-all
    action: Allow
    description: Allow all incoming traffic to the Kubelet
    logsEnabled: true
    subject:
    - - hs:name=host
    - - ext:name=all-tcp
    object:
    - - hs:name=kubelet
----

Import the external networks and network policy definitions from the `networkpolicy.yaml` file using the following command line:

[,console]
----
apoctl api import --file ./networkpolicy.yaml
----

Verify that the external networks and network policies are correctly configured in your base Kubernetes namespace:

[,console]
----
apoctl api list externalnetworks
apoctl api list networkaccesspolicies
----

=== Create and map host services

A host service in the Aporeto system will instruct the enforcers to protect the Kubernetes hosts.
Use the following configuration to setup the host services and associate them with your Kubernetes hosts.

Create a file called `hostservice.yaml` with the following contents:

[,yaml]
----
label: k8s-node-host-services
data:
  hostservicemappingpolicies:
  - name: host-kubelet-and-ssh
    description: Apply full host mode, kubelet and SSH to all enforcers on Kubernetes nodes
    subject:
    - - $namespace={{ .Aporeto.Namespace }}
    object:
    - - hs:name=host
    - - hs:name=ssh
    - - hs:name=kubelet

  hostservices:
  - name: host
    description: Full Host Mode (fallback - everything else on/from a host)
    hostModeEnabled: true
    associatedTags:
    - hs:name=host

  - name: ssh
    description: SSH Service
    associatedTags:
    - hs:name=ssh
    services:
    - tcp/22

  - name: kubelet
    description: The Kubelet Service
    associatedTags:
    - hs:name=kubelet
    services:
    # healthz port
    - tcp/10248
    # main kubelet port
    - tcp/10250
    # readonly port
    - tcp/10255
----

Import the host service definitions and the host service mappings by using the following command line:

[,console]
----
apoctl api import \
   --set namespace=$APOCTL_NAMESPACE \
   --file=./hostservice.yaml
----

Validate the configuration:

[,console]
----
apoctl api list hostservices
apoctl api list hostservicemappingpolicies
----

At this point we can also validate that the enforcers have been associated with this policy.
We will take the first enforcer in the namespace and list its associated host services.

[,console]
----
apoctl api list hostservices in enforcer \
    $(apoctl api list enforcers -c ID -c operationalStatus -o table | grep Connected | awk '{print $1}')
----

If no enforcer is returned or the configuration of the host services does not match the installation above, then something went wrong during your configuration.

=== Validate installation

If you go to the Aporeto web interface you should see in your base Kubernetes namespace several new processing units.
The ones that start with `host` refer to the host protection.
The ones that start with `ssh` refer to the SSH service that is independently managed.
And last but not least, the ones that start with `kubelet` refer to the kubelet service that is also independently managed.

[TIP]
====
You can start narrowing down your policies now depending on your security posture requirements.
====
