== Read-Only filesystem for containers not used
//Read-Only filesystem for containers is not used
//suggest: Container root filesystem mutable


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| db181537-e359-4a4e-8baa-a6d33e3df6ad

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/ReadOnlyFilesystem.py[CKV_K8S_22]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes,Terraform,Helm,Kustomize

|=== 



=== Description 


A read-only root filesystem helps to enforce an immutable infrastructure strategy.
The container should only write on mounted volumes that can persist, even if the container exits.
Using an immutable root filesystem and a verified boot mechanism prevents against attackers from "owning" the machine through permanent local changes.
An immutable root filesystem can also prevent malicious binaries from writing to the host system.

=== Fix - Buildtime


*Kubernetes* 


* *Resources:* Container
* *Arguments:* readOnlyRootFilesystem (Optional)  Defines whether a container is able to write into the root filesystem.
Default to false.


[source,yaml]
----
{
  "codes": [
    {
      "code": "apiVersion: v1
kind: Pod
metadata:
  name: &lt;Pod name>
spec:
  containers:
  - name: &lt;container name>
    image: &lt;image>
    securityContext:
+      readOnlyRootFilesystem: true",
      "language": "yaml"
    }
  ]
}
----
