== CPU request is not set
// CPU request not set

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 662c96ca-8714-4f6f-bf63-9277daafc075

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/kubernetes/CPURequests.py[CKV_K8S_10]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


When specifying the resource request for containers in a pod, the scheduler uses this information to decide which node to place the pod on.
When setting resource limit for a container, the kubelet enforces those limits so that the running container is not allowed to use more of that resource than the limit you set.
If a container is created in a namespace that has a default CPU limit, and the container does not specify its own CPU limit, then the container is assigned the default CPU limit.
Kubernetes assigns a default CPU request under certain conditions.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Container
* *Arguments:* resources:requests:cpu (Optional)  Defines the CPU request size for the container.


[source,yaml]
----
{
  "codes": [
    {
      "code": "apiVersion: v1
kind: Pod
metadata:
  name: &lt;name>
spec:
  containers:
  - name: &lt;container name>
    image: &lt;image>
    resources:
      requests:
+       cpu: &lt;cpu request>",
      "language": "yaml"
    }
  ]
}
----
