== Containers do not run with a high UID


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 1e4d1db0-70d8-4dad-ae2f-f9ce1b06b107

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/RootContainersHighUID.py[CKV_K8S_40]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Helm, Kustomize

|=== 



=== Description 


Linux namespaces provide isolation for running processes and limits access to system resources.
To prevent privilege-escalation attacks from within a container, we recommend that you configure your container's applications to run as unprivileged users.
The mapped user is assigned a range of UIDs which function within the namespace as normal UIDs from 0 to 65536, but have no privileges on the host machine itself.
If a process attempts to escalate privilege outside of the namespace, the process is running as an unprivileged high-number UID on the host, not mapped to a real user.
This means the process has no privileges on the host system and cannot be attacked by this method.
This check will trigger below UID 10,000 as common linux distributions will assign UID 1000 to the first non-root, non system user and 1000 users should provide a reasonable buffer.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Pod / Deployment / DaemonSet / StatefulSet / ReplicaSet / ReplicationController / Job / CronJob
* *Arguments:* runAsUser (Optional)  Specifies the User ID that processes within the container and/or pod run with.


[source,yaml]
----
{
  "codes": [
    {
      "code": "apiVersion: v1
kind: Pod
metadata:
  name: &lt;name>
spec:
  containers:
  - name: &lt;container name>
    image: &lt;image>
    securityContext:
+     runAsUser: &lt;UID higher then 10000>",
      "language": "yaml",
      "name": "Pod"
    },
    {
      "code": "apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: &lt;name>
spec:
  schedule: &lt;>
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: &lt;container name>
            image: &lt;image>
    \t    securityContext:
+             runAsUser: &lt;UID higher then 10000>",
      "language": "yaml",
      "name": "CronJob"
    },
    {
      "code": "apiVersion: &lt;>
kind: &lt;kind>
metadata:
  name: &lt;name>
spec:
  template:
    spec:
      containers:
      - name: &lt;container name>
        image: &lt;image>
    \tsecurityContext:
          runAsUser: &lt;UID higher then 10000>",
      "language": "yaml",
      "name": "Other"
    }
  ]
}
----
