== Dynatrace token


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a4e5aa1e-94ba-4aa1-ab46-1f137b10110c

|Checkov ID 
|CKV_SECRET_39

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


To be authenticated to use the Dynatrace API, you need a valid access token or a valid personal access token.
Access to the API is fine-grained, meaning that you also need the proper scopes assigned to the token.
See the description of each request to find out which scopes are required to use it.
Dynatrace uses a unique token format consisting of three components separated by dots (.).
`dt0c01.ST2EY72KQINMH574WMNVI7YN.G3DFPBEJYMODIDAEX454M7YWBUVEFOWKPRVMWFASS64NFH52PX6BNDVFFM572RZM`
The part of a token composed of the prefix and public portion is a token identifier.
For example dt0c01.ST2EY72KQINMH574WMNVI7YN.
Token identifier can be safely displayed in the UI and can be used for logging purposes.

=== Fix - Buildtime


*Dynatrace To execute this request, you need an access token with Write API tokens (apiTokens.write) scope: Managed	`+https://{your-domain}/e/{your-environment-id}/api/v2/apiTokens/{id}+` SaaS: `+https://{your-environment-id}.live.dynatrace.com/api/v2/apiTokens/{id}+` Environment: `+ActiveGate	https://{your-activegate-domain}/e/{your-environment-id}/api/v2/apiTokens/{id}+`* 


