== Hex High Entropy String


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a9c6ddac-78da-4928-a3e7-8662bb33f2c5

|Checkov ID 
|CKV_SECRET_19

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


Password Entropy is a concept used to assign a numerical score to how unpredictable a password is or the likelihood of highly random data in a string of characters.
The policy calculates entropy levels using a Shannon Entropy calculator.
The entropy levels of keys are important, as the more or less information required to determine unknown key variables can alter how difficult it is to crack.
If a high-entropy string is detected, the string is printed to the screen.
This check scans the branch and evaluates the entropy for both the hexadecimal character set for every blob of text.

=== Fix - Buildtime


*Multiple Services* 



.  Revoke the exposed secret.
+
Start by understanding what services were impacted and refer to the corresponding API documentation to learn how to revoke and rotate the secret.

.  Clean the git history.
+
Go under the settings section of your GitHub project and chose the change visibility button at the bottom.

.  Check any relevant access logs to ensure the key was not utilized during the compromised period.
