== PlanetScale Token


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| d671864e-5c7b-423b-bfe2-2ede45e8d18a

|Checkov ID 
|CKV_SECRET_58

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


PlanetScale offers a managed database platform that is designed for developers and developer workflows.
The PlanetScale CLI allows developers to create development branches, open deploy requests, and make non-blocking schema changes directly from a terminal.
PlanetScale provides the ability to create service tokens for your PlanetScale organization via the CLI or directly in the UI.
Service tokens are not recommended for connecting to production databases.
Instead, connect securely to your database using PlanetScale connection strings.

=== Fix - Buildtime


*PlanetScale* 



. Go to the service tokens page for your organization: app.planetscale.com

. Click on the service token ID for the service token you would like to delete.

. Click on the "Delete service token" button in the upper right hand corner.

. Confirm deletion by clicking the "Delete" button in the pop-up modal.

. Deleting a service token will sever any database connections that use the given service token.
