== SonarQube Token


=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
|TBD

|Checkov Check ID
|CKV_SECRET_86

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|===



=== Description

A SonarQube token is a unique identifier used to authenticate with the SonarQube server, typically for analysis purposes or when using web APIs. It's a safer and more convenient way to authenticate compared to using a username and password, as it can be easily revoked if compromised. Tokens are created and managed from your SonarQube account settings.


=== Fix - Buildtime


*SonarQube*

To revoke a SonarQube token, follow these steps:

1. Log in to your SonarQube instance.
2. Click on your avatar in the upper-right corner of the screen and then click on 'My Account'.
3. Navigate to the 'Security' tab.
4. Here you'll see a list of your existing tokens. Find the token that you want to revoke and click on the 'Revoke' button next to it.
+
Once you revoke a token, the action cannot be undone, and any applications using that token will no longer be able to authenticate with the SonarQube server.
