== Google Cloud Keys


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9d1b426e-4498-4660-a34f-8a43beb0a2b7

|Checkov ID 
|CKV_SECRET_45

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


The Google Cloud API key can be used to authenticate to an API.
The API key associates the request with a Google Cloud project for billing and quota purposes.
Because API keys do not identify the caller, they are generally used for accessing public data or resources.
Many Google Cloud APIs do not accept API keys for authentication.
When you use Google Cloud API keys in your applications, ensure that they are kept secure during both storage and transmission.
Publicly exposing your API keys can lead to unexpected charges on your account.

=== Fix - Buildtime


*Google Cloud* 



. Navigate to APIs & Services console at https://console.cloud.google.com/apis/credentials.

. In the main navigation panel, select Credentials to access the list of the API keys created for the selected Google Cloud Platform (GCP) project.
+
3.On the Credentials page, in the API Keys section, select the API key that you want to delete, and choose DELETE button from the console top menu to remove the selected key from your GCP project.

. Inside the Delete credential confirmation box, choose DELETE to confirm the removal action.
+
The selected API key will be deleted immediately and permanently.
