== NPM Token

Token

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 46bfa5d5-df04-4390-85ce-f312d62677f4

|Checkov ID 
|CKV_SECRET_12

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


The NPM access token can be used to authenticate to npm when using the API or the npm command-line interface (CLI).
An access token is a hexadecimal string that you can use to authenticate, and which gives you the right to install and/or publish your modules.

=== Fix - Buildtime


*NPM* 



.  Revoke Secret.

. To see a list of your tokens, on the command line, run:

----
npm token list
----

. In the tokens table, find and copy the ID of the token you want to delete.
On the command line, run the following command, replacing 123456 with the ID of the token you want to delete:

----
npm token delete 123456
npm will report Removed 1 token
----

. To confirm that the token has been removed, run:

----
npm token list
----

.  Clean the git history.
Go under the settings section of your GitHub project and chose the change visibility button at the bottom.
