== Helm charts

If you installed Prisma Cloud into your Kubernetes or OpenShift cluster with Helm charts, you can upgrade with the _helm upgrade_ command.

First upgrade Console.
Console will then automatically upgrade all deployed Defenders for you.

If you've disabled Defender auto-upgrade or if Console fails to upgrade one or more Defenders, manually upgrade your Defenders.

NOTE: You must manually upgrade App-Embedded Defenders.


ifdef::compute_edition[]
[.task]
=== Upgrading Console

Generate an updated Helm chart for Console, and then upgrade to it.

[.procedure]
. xref:../welcome/releases.adoc#download[Download] the latest recommended release.

. Create an updated Console Helm chart.

  $ <PLATFORM>/twistcli console export kubernetes \
    --service-type LoadBalancer \
    --helm

. Install the updated chart.

  $ helm upgrade twistlock-console \
    --namespace twistlock \
    --recreate-pods \
   ./twistlock-console-helm.tar.gz

. Go to *Manage > Defenders > Manage* and validate that Console has upgraded your Defenders.
endif::compute_edition[]
