[#_cb_advanced]
== Advanced

* *Identify supply chain dependencies.*
The supply chain capability on Code Security is a code-centric view of infrastructure and application security that visualizes a supply chain graph, starting with the IaC templates, the services, deployed cloud workload resources (including associated permissions), and the runtime configuration on these resources. Prisma Cloud’s supply chain graph is a real-time auto-discovery of potentially misconfigured infrastructure and application files, sorted into a concise data model that you can use to prioritize and search. The graph identifies infrastructure, image, open source, and secrets, and combines that data to identify risk chains. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-code-security/scan-monitor/supply-chain-security[Learn more about supply chain security].

* *Trace a deployment of a cloud resource with tags.*
Do you ever wonder which Infrastructure as Code template was used to deploy a cloud resource? Tags can help you trace the link for your resources deployed from code-to-cloud infrastructure. Detect drift within your code base and locate the specific resource within a commit that identifies teams and resource owners to help triage a fix in the most timely and cost-effective way. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-code-security/scan-monitor/iac-tag-and-trace[Learn more about IaC Tag and Trace].
