[#_run_advanced]
== Advanced

* *Safeguard your web applications and APIs from attacks with layer 7 firewall protection.*
Prisma Cloud’s Web Application and API Security (WAAS) is a web application and API firewall designed for HTTP-based web applications deployed directly on hosts as containers, application-embedded, or serverless functions. Your web applications running on hosts, containers, or serverless are protected against the most critical OWASP top 10 risks, including injection flaws, broken authentication, broken access control, security misconfigurations, etc. In addition, you can enable many other security features like access control, file upload control, bot protection, DoS protection, and more. The overall outcome is that you will be protected against vulnerabilities like Log4j. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/waas/waas-intro[Learn more about Prisma Cloud’s Web Application and API Security protections].

* *Automatically correct misconfigurations.*
With complex multi-cloud environments, the security operations team wants to have automated solutions to resolve security violations, such as misconfigured security groups, to be addressed immediately and effectively. Prisma Cloud can automatically resolve policy violations within the Prisma Cloud console. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-alerts/configure-prisma-cloud-to-automatically-remediate-alerts[Learn more about Prisma Cloud auto-remediation capabilities].
