[#_run_intermediate]
== Intermediate

* *Monitor the runtime behavior of your applications.*
Applications run across the cloud continuum. Regardless of where they are deployed (hosts, containers, serverless functions, etc.), the application’s runtime behavior should be monitored for abnormal behaviors. The security operations team needs to identify those planned behaviors quickly and prevent any other un-predictive anomalous behavior. Prisma Cloud secures runtime environments using predictive and threat-based protection without adding overhead. Threat-based protection includes capabilities like detecting when malware is added to a container or when a container connects to a botnet. Prisma Cloud automatically creates runtime models based on observed processes, networking, and file system behaviors. These runtime models can be adjusted to further refine the monitoring and effect policy responses when events are encountered. In addition, Prisma Cloud captures the forensic details, which provide the history of events that led up to and followed an incident for threat hunting and lifecycle analysis. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/runtime_defense/runtime_defense_containers[Learn more about Prisma Cloud runtime defense].

* *Identify anomalous network and user activities.*
The dynamic, distributed nature of cloud environments often creates alerts that lack context at a volume that can overwhelm security operations teams. Attempting to correlate logs, API metadata, and signature-driven alerts can quickly flood teams with false positives instead of actionable insight. Prisma Cloud employs advanced machine learning to identify the normal network behavior of each customer’s cloud environment to detect anomalies. Users who access cloud environments can pose a significant threat if not continuously monitored for unusual activities that could signal possible credential or account compromise. Prisma Cloud continuously monitors and learns each user's activities to identify what’s normal and alerts on behaviors that deviate from that baseline. Prisma Cloud provides a comprehensive policy to detect malicious network and user activities. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/prisma-cloud-policies/prisma-cloud-threat-detection[Learn more about Prisma Cloud’s threat detection].

* *Prioritize risk management and incident responses.*
As alerts start to arrive from Prisma Cloud, it is critical to categorize what is important to avoid alert fatigue. The ATT&CK Explorer and Top Incidents & Risks (view by MITRE ATT&CK) give an excellent overview and categorization of your alerts to easily address any possible issues, including both incidents that map to MITRE as well as misconfiguration risks that could be addressed to make your cloud infrastructure less prone to specific MITRE ATT&CK tactics. The MITRE ATT&CK framework’s curated knowledge base and model for cyber adversary behavior is available for your security operations team to easily track down possible incidents and wade through audits/noise to find what is important in your environment. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/runtime_defense/attack[Learn more about Prisma Cloud’s ATT&CK Explorer and Top Incidents & Risks (view by MITRE ATT&CK)].
