== Azure SignalR Service not Using Paid SKU for its SLA
// Ensure that SignalR uses a Paid Sku for its SLA.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5a2a53dc-38b2-4649-99d5-c117052fcaf7

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/SignalRSKUSLA.py[CKV_AZURE_196]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

=== Description

Azure SignalR Service is a managed service that allows for real-time communication using the SignalR library. The Service Level Agreement (SLA) is crucial for ensuring uptime and reliability for critical applications.

Using the "Free_F1" SKU tier does not provide a business-level SLA, which can be a significant concern for applications requiring high availability and immediate support from Azure.

This policy ensures that SignalR Service instances do not use the free tier, hence ensuring a better SLA.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_signalr_service

*Arguments:* 
- sku

[source,terraform]
----
resource "azurerm_signalr_service" "example" {
  name                = "example-signalr"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

+ sku {
+   name = "Standard_S1" # or any other paid SKU
+   capacity = 1
+ }

  # ... other configurations ...
}
----

