== Azure Cognitive Search Without SLA Index Updates
// Ensure that Azure Cognitive Search maintains SLA for index updates.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6134bd00-982b-4d83-a444-0296cef1e2e1

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureSearchSLAIndex.py[CKV_AZURE_208]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

=== Description

Azure Cognitive Search provides fully managed cloud search service capabilities, such as indexing and querying. Indexing involves loading content into the service to make it searchable, whereas querying is the process of searching for that content. The performance and resilience of these processes are enhanced by configuring multiple replicas. Replicas enable queries and index updates to be load balanced across different replicas, ensuring efficient performance and high availability.

To ensure consistent performance and high availability for search index updates, it's important to have an adequate number of replicas. According to Azure's Service Level Agreement (SLA), a minimum of 3 replicas is required to guarantee the SLA for search index updates. 

This policy checks and ensures that the Azure Cognitive Search service has at least 3 replicas configured, guaranteeing that the SLA for search index updates is maintained.

=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_search_service

*Arguments:* 
- replica_count

[source,terraform]
----
resource "azurerm_search_service" "example" {
  name                = "example-search-service"
  # ... other configurations ...

+ replica_count = 3

  # ... other configurations ...
}
----
