== Azure Service Bus Doesn't Use Double Encryption
// Ensure that Azure Service Bus uses double encryption.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4d477575-ab03-4ad2-a406-2b13c91e89b9

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureServicebusDoubleEncryptionEnabled.py[CKV_AZURE_199]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Service Bus is a fully managed enterprise message broker with message queues and publish-subscribe topics. It offers secure and reliable communication between disparate applications. Ensuring that the Service Bus uses double encryption ensures that your data is encrypted at rest and in transit, providing an additional layer of protection against unauthorized access.

This policy checks that Azure Service Bus namespaces have double encryption enabled.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_servicebus_namespace

*Arguments:* 
- customer_managed_key/[0]/infrastructure_encryption_enabled

[source,terraform]
----
resource "azurerm_servicebus_namespace" "example" {
  name                = "example-servicebus-namespace"
  # ... other configurations ...

  customer_managed_key {
+   infrastructure_encryption_enabled = true
    # ... other configurations ...
  }

  # ... other configurations ...
}
----

