== Web PubSub Without SLA SKU
// Ensure Web PubSub uses a SKU with an SLA

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 774008d3-1c0a-4a30-af0d-fbfc79560ead

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/PubsubSKUSLA.py[CKV_AZURE_175]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

=== Description

Azure Web PubSub is a real-time web messaging service that allows you to build real-time applications using WebSockets and other WebSub-compatible protocols. The service's tier or SKU determines its pricing, features, and SLA. The "Free_F1" SKU does not come with an SLA. To ensure service availability and support, it's recommended to use a SKU that provides an SLA.

This policy ensures that the Azure Web PubSub service is not using the "Free_F1" SKU, which lacks an SLA.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_web_pubsub
* *Arguments:* sku

[source,terraform]
----
resource "azurerm_web_pubsub" "example" {
  name                = "example-webpubsub"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
+ sku                 = "Standard_S1"  # or any other SKU with SLA
  
  tags = {
    Environment = "production"
  }
}
----
