== Windows VM Without Automatic Updates
// Ensure Windows VM enables automatic updates

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4e336f38-10ea-46d5-a643-9b5c01156dbc

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/WinVMAutomaticUpdates.py[CKV_AZURE_177]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

=== Description

Automatic updates are crucial for maintaining the security and performance of systems. Regular updates address vulnerabilities that might be exploited, provide enhancements, and deliver crucial security patches. For Windows Virtual Machines (VMs) and Virtual Machine Scale Sets in Azure, enabling automatic updates ensures that these instances remain up-to-date with the latest patches from Microsoft.

This policy checks to ensure that Windows VMs and VM Scale Sets are configured to have automatic updates enabled.

=== Fix - Buildtime

*Terraform*

*Resources:* 
- azurerm_windows_virtual_machine
- azurerm_windows_virtual_machine_scale_set

*Argument:* 
- enable_automatic_updates

[source,terraform]
----
resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-vm"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
  # ... other configurations ...

+ enable_automatic_updates = true
}

resource "azurerm_windows_virtual_machine_scale_set" "example" {
  name                = "example-vmss"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
  # ... other configurations ...

+ enable_automatic_updates = true
}
----

Note: It's recommended to enable automatic updates on all Windows VM and VM Scale Set instances in Azure to ensure they receive the latest security patches and updates from Microsoft.
