== Azure Service Bus Doesn't Use Customer-Managed Key Encryption
// Ensure that Azure Service Bus uses a customer-managed key to encrypt data.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4802ae23-097f-49c9-a96e-331da5ba85bb

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/AzureServicebusHasCMK.py[CKV_AZURE_201]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Service Bus is a cloud messaging service used to connect applications, services, and devices running on Azure with on-premises software. It facilitates asynchronous, decoupled communication among decoupled components in the cloud, on-premises, or in a hybrid solution.

This policy ensures that the Azure Service Bus data is encrypted using a customer-managed key (CMK) stored in Azure Key Vault. Utilizing a CMK offers enhanced control and transparency over the key lifecycle, and ensures that you, as the customer, maintain control of the encryption keys.

=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_servicebus_namespace

*Arguments:* 
- customer_managed_key

[source,terraform]
----
resource "azurerm_servicebus_namespace" "example" {
  name                = "example-namespace"
  # ... other configurations ...

+ customer_managed_key {
+   key_vault_key_id = "azure key vault key id here"
  }

  # ... other configurations ...
}
----

