== Azure Container Registry (ACR) Doesn't Have a Retention Policy Set
// Ensures that Azure Container Registry (ACR) has a retention policy set to clean up untagged manifests.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| d242ebda-2743-4f06-bcfa-86e60a472be4

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/ACREnableRetentionPolicy.py[CKV_AZURE_167]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

=== Description

Azure Container Registry retention policies help to manage image storage by automatically deleting untagged manifests. Enabling this policy ensures efficient usage of storage and removes potential vulnerabilities associated with stale or unused images.

This policy checks if the retention policy is enabled for Azure Container Registry, ensuring that untagged manifests are automatically deleted.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_container_registry
* *Arguments:* retention_policy

[source,terraform]
----
resource "azurerm_container_registry" "example" {
  name                     = "exampleContainerRegistry"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  sku                      = "Premium"
  admin_enabled            = false

+ retention_policy {
+    enabled = true
+    days    = 7
+  }
}
----
