== Vulnerability Scanning not enabled for Azure Container Registry
// Enable vulnerability scanning for container images in Azure Container Registry

=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID 
| 6d9f45e7-531c-4987-a837-7b40cb96646f

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/ACRContainerScanEnabled.py[CKV_AZURE_163]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|===

=== Description

Vulnerability scanning for container images is a critical security feature that helps to identify software flaws in your container images. It is highly recommended to enable this feature in Azure Container Registry to identify and fix vulnerabilities before they can be exploited.

This policy checks whether the Azure Container Registry has vulnerability scanning enabled by requiring a SKU of `Standard` or `Premium`.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_container_registry
* *Arguments:* sku

[source,terraform]
----
resource "azurerm_container_registry" "example" {
  name                     = "exampleContainerRegistry"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
+ sku                      = "Standard"
  admin_enabled            = false
}
----

// Note: Vulnerability scanning is only available for 'Standard' or 'Premium' SKUs.
