== Azure Storage account not configured with SAS expiration policy
// Ensure storage account is configured with SAS expiration policy

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8527f09d-effd-40b7-a897-14dc1558270a

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/graph_checks/azure/AzureStorageAccConfig_SAS_expirePolicy.yaml[CKV_AZURE_230]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

=== Description

Azure Storage accounts offer robust cloud data storage solutions. A Shared Access Signature (SAS) provides delegated access to resources in the storage account. It's essential to ensure that SAS tokens have an expiration policy set to minimize the risk of unauthorized access due to token leakage.

This policy ensures that the Azure Storage account is configured with a SAS expiration policy. It checks for the presence and configuration of the `sas_policy` and its `expiration_period` attribute within the `azurerm_storage_account` resource. The policy verifies that the expiration period length is greater than zero, indicating that an expiration policy is in place.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_storage_account
* *Arguments:* sas_policy, sas_policy.expiration_period

[source,go]
----
resource "azurerm_storage_account" "example" {
  name                     = "examplestoracc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  
  # ... other configurations ...

+ sas_policy {
+   expiration_period = 30
+ }
}
----
