== PostgreSQL server enables geo-redundant backups
// PostgreSQL server geo-redundant backup disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 28bac534-b4d1-464d-8ad9-3ed011d53f32

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/PostgressSQLGeoBackupEnabled.py[CKV_AZURE_102]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Azure PostgreSQL allows you to choose between locally redundant or geo-redundant backup storage in the General Purpose and Memory Optimized tiers.
When the backups are stored in geo-redundant backup storage, they are not only stored within the region in which your server is hosted, but are also replicated to a paired data center.
This provides better protection and ability to restore your server in a different region in the event of a disaster.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_postgresql_server
* *Arguments:* geo_redundant_backup_enabled - (Optional) Turn Geo-redundant server backups on/off.


[source,go]
----
{
 "resource "azurerm_postgresql_server" "example" {
  ...
+ geo_redundant_backup_enabled = true
}

",
}
----
