== Azure Microsoft Defender for Cloud is set to Off for Container Registries


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| be240ec3-9d49-4f6b-a40c-fd1bf1bf0783

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/AzureDefenderOnContainerRegistry.py[CKV_AZURE_86]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Azure Defender is a cloud workload protection service that utilizes and agent-based deployment to analyze signals from Azure network fabric and the service control plane, to detect threats across all Azure resources.
It can also analyze non-Azure resources, utilizing Azure Arc, including those on-premises and in both AWS and GCP (once they've been onboarded).
Azure Defender for container registries includes a vulnerability scanner to scan the images in Azure Resource Manager-based Azure Container Registry registries and provide deeper visibility image vulnerabilities.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_security_center_subscription_pricing
* *Arguments:* resource_type - (Required) The resource type this setting affects.

Ensure that `ContainerRegistry` is declared to pass this check.


[source,go]
----
resource "azurerm_security_center_subscription_pricing" "example" {
  tier          = "Standard"
  resource_type = "AppServices,ContainerRegistry,KeyVaults,KubernetesService,SqlServers,SqlServerVirtualMachines,StorageAccounts,VirtualMachines,ARM,DNS"
}
----
