== Weak authentication service in use in Jenkins 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|5dcaa867-09ea-4e42-aab5-42886cd7713a

|Severity
|Medium
// add severity level

|Category
|Identity and Access Management
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Jenkins

|=== 

=== Description 

Jenkins provides built-in methods for authentication of users, such as a Jenkins’ own user database, or a Unix user/group database. 
These methods lack basic security controls, such as enforcing a password policy, controls against Brute Force attacks, and requiring 2FA,  which are essential to assure the immunity of the system.

These weak authentication methods might expose the organization to a wide variety of authentication-based attacks.

=== Recommended Solution - Buildtime

Implement a secure authentication mechanism which provides security controls that meet the industry best practices, such as integrating with the organization’s SSO solution. For more on secure authentication mechanisms refer to https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html.










