== Secrets found in console output of a Jenkins pipeline   

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|76ca0afe-abd9-413a-8468-13d8d522ce45

|Severity
|Medium
// add severity level

|Category
|Credential Hygiene
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Jenkins

|=== 

=== Description 

Secrets exposed in build log files can be used by an attacker that has taken over an account with access to the system, in order to move laterally in the organization. 

Exposed secrets can be caused by not using the relevant feature to protect credentials or by printing credentials in a way that bypasses the feature’s ability to detect credentials.


=== Recommended Solution - Buildtime

When exposed credentials are found it is recommended to:

* Rotate all exposed credentials.
* Make sure credentials are accessed using the **Credential Binding** plugin.
* The Credential Binding masking feature has limitations, hence some exposed credentials should be resolved by modifying the Jenkins file to prevent exposure.
* Consider using the **Mask Passwords** plugin to manually configure secrets that should be masked.





