== A log metric filter and alarm does not exist for Security Group changes


=== Description 


Real-time monitoring of API calls can be achieved by directing CloudTrail Logs to CloudWatch Logs and establishing corresponding metric filters and alarms.
Security Groups are a stateful packet filter that controls ingress and egress traffic within a VPC.
Monitoring changes to a security group will help ensure that resources and services are not unintentionally exposed.
We recommend you establish a log metric filter and alarm to detect changes to a Security Group.

=== Fix - Runtime


*Procedure* 


To setup the metric filter, alarm, SNS topic, and subscription, follow these steps and commands:

. Determine the CloudTrail log group name to monitor.
+
[,bash]
----
aws cloudtrail describe-trails
----
Look for the field *_CloudWatchLogsLogGroupArn_*.
Your log group name comes after the _log-group_ field.
For example:
arn:aws:logs:us-west-2:123456789012:log-group:**aws-cloudtrail-logs-123456789012-68a4172e**:*
If you don't see the field *CloudWatchLogsLogGroupArn* in your output, your CloudTrail is not setup to ship logs to CloudTrail.
Please follow the https://docs.aws.amazon.com/awscloudtrail/latest/userguide/send-cloudtrail-events-to-cloudwatch-logs.html[AWS Documentation] for sending CloudTrail events to CloudWatch logs.

. Create a metric filter based on filter pattern provided which checks for security groups changes and the +++&lt;cloudtrail_log_group_name>+++taken from step 1.+++&lt;/cloudtrail_log_group_name>+++
[,bash]
----
aws logs put-metric-filter
--log-group-name &lt;cloudtrail_log_group_name>
--filter-name &lt;security_group_changes_metric>
--metric-transformationsmetricName= &lt;security_group_changes_metric>,
metricNamespace='CISBenchmark',metricValue=1
--filter-pattern '{($.eventName = AuthorizeSecurityGroupIngress) ||
($.eventName = AuthorizeSecurityGroupEgress) ||
($.eventName = RevokeSecurityGroupIngress) ||
($.eventName = RevokeSecurityGroupEgress) ||
($.eventName = CreateSecurityGroup) ||
($.eventName = DeleteSecurityGroup) }'
----
+
[NOTE]
====
You can choose your own metricName and metricNamespace strings. Using the same metric Namespace for all Foundations Benchmark metrics will group them together.
====

. Create an SNS topic that the alarm will notify.
[,bash]
----
aws sns create-topic --name &lt;sns_topic_name>
----
+
[NOTE]
====
You can execute this command once and then re-use the same topic for all monitoring alarms.
====

. Create an SNS subscription to the topic created in Step 2.
[,bash]
----
aws sns subscribe
--topic-arn &lt;sns_topic_arn>
--protocol &lt;protocol_for_sns>
--notification-endpoint &lt;sns_subscription_endpoints>
----
+
[NOTE]
====
You can execute this command once and then re-use the SNS subscription for all monitoring alarms.
====

. Create an alarm that is associated with the CloudWatch Logs Metric Filter created in Step 1 and an SNS topic created in Step 2.
[,bash]
----
aws cloudwatch put-metric-alarm
--alarm-name &lt;security_group_changes_alarm>
--metric-name &lt;security_group_changes_metric>
--statistic Sum
--period 300
--threshold 1
--comparison-operator GreaterThanOrEqualToThreshold
--evaluation-periods 1
--namespace 'CISBenchmark'
--alarm-actions &lt;sns_topic_arn>
----

=== Fix - Buildtime
Resource: aws_cloudwatch_log_metric_filter, aws_cloudwatch_metric_alarm


[source,go]
----
{
  "codes": [
    {
      "code": "resource "aws_sns_topic" "trail-unauthorised" {
  name="Unauthorised"
  kms_master_key_id = "alias/aws/sns"
}

resource "aws_sns_topic_subscription" "sms" {
  topic_arn = aws_sns_topic.trail-unauthorised.arn
  protocol  = "sms"
  endpoint=var.endpoint
}

resource "aws_cloudwatch_metric_alarm" "sg" {
  alarm_name          = "security_group_changes_alarm"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 1
  metric_name         = "security_group_changes_metric"
  namespace           = "CISBenchmark"
  period              = 300
  statistic           = "Sum"
  threshold           = 1
  alarm_actions       = [aws_sns_topic.trail-unauthorised.arn]
}

resource "aws_cloudwatch_log_metric_filter" "sg" {
  name           = "security_group_changes_metric"
  pattern        = &lt;&lt;PATTERN
{($.eventName = AuthorizeSecurityGroupIngress) ||
($.eventName = AuthorizeSecurityGroupEgress) ||
($.eventName = RevokeSecurityGroupIngress) ||
($.eventName = RevokeSecurityGroupEgress) ||
($.eventName = CreateSecurityGroup) ||
($.eventName = DeleteSecurityGroup) }
  PATTERN
  log_group_name = var.log_group_name

  metric_transformation {
    name      = "security_group_changes_metric"
    namespace = "CISBenchmark"
    value     = "1"
  }
}",
      "language": "go",
      "name": "aws_cloudwatch_metric_alarm.sg.tf"
    }
  ]
}
----
