== Prisma Cloud Compute certificates

This document summarizes all the certificates used by Prisma Cloud Compute. For each certificate, you can learn more about its functionallity, signing CA, and your customization options.

NOTE: Customizing certificates is only allowed for Prisma Cloud Compute Edition.

[cols="10%, 10%, 10%a, 20%a, 15%, 20%, 15%", options="header"]
|===
|Category  |Certificate  |Functionallity  |Default CA  |Certificate customizion  |CA customizion  |Prisma Cloud edition

|Console TLS communication
|Console Web and API certificate
|
|Console CA
|Customize under *Manage > Authentication > System certificates > TLS certificate for Console > Concatenate public cert and private key*
|Your organization CA
|Compute edition

|Docker role-based access control
|Client certificates
|
|Console CA
|Customize your own certificates for your clients.

Explicit list of trusted certificates can be defined under *Manage > Authentication > System certificates > Client certificates > Explicit certificate trust list*
|Customize under *Manage > Authentication > System certificates > Client certificates > CA certificate*
|?

|Authentication to Console using certificates
|Disabled by default. Enable Console authentication of the clients by providing a CA certificate.
|
|
|
|Disabled by default. Define under *Manage > Authentication > System certificates > Certificate-based authentication to Console > CA certificate*
|?

|Admission control
|Admission certificate (admission-cert.pem)
|
|Defender CA (defender-ca.pem)
|No
|No
|?

|Console-Defender communication
|Defender server certificate (Console side)
|
|Defender CA (defender-ca.pem)
|No
|No
|?

|Console-Defender communication
|Defender client certificate (Defender side)
|
|Defender CA (defender-ca.pem)
|No
|No
|?

|===

=== Console TLS communication certificates
https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-08/prisma-cloud-compute-edition-admin/configure/custom_certs_console_access.html

HTTP Public Key Pinning (HPKP) was a security feature that used to tell a web client to associate a specific cryptographic public key with a certain web server to decrease the risk of MITM attacks with forged certificates.
Deprecated: This feature is no longer recommended: https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning

=== Docker role-based access control certificates
https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-08/prisma-cloud-compute-edition-admin/authentication/use_custom_certs_for_auth.html

=== Authentication to Console using certificates
https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-08/prisma-cloud-compute-edition-admin/authentication/use_custom_certs_for_auth.html

=== Admission control certificates

=== Console-Defender communication certificates
