== CloudTrail S3 bucket access logging is not enabled


*Description* 


S3 Bucket Access Logging generates a log that contains access records for each request made to your S3 bucket.
An access log record contains details about the request, including: the request type, the resources specified in the request worked, and the time and date the request was processed.
Enabling S3 bucket logging on target S3 buckets, you can capture all events which may affect objects within target buckets.
Configuring logs to be placed in a separate bucket allows access to log information which can be useful in security and incident response workflows.
We recommend you enable bucket access logging on the CloudTrail S3 bucket.

=== Fix - Runtime


*AWS Console* 


To enable S3 bucket logging using the AWS Management Console, follow these steps:

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the *https://console.aws.amazon.com/s3/[Amazon S3 console]*.

. Navigate to *All Buckets* and select the target _S3 bucket_.

. At the top right of the console, click *Properties*.

. Under *Bucket: +++&lt;s3_bucket_for_cloudtrail>+++*, select **Logging**.+++&lt;/s3_bucket_for_cloudtrail>+++

. Configure bucket logging:   a) Select *Enabled*.
+
b) From the list, select _Target Bucket_.
+
c) Enter a _Target Prefix_.
