[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.7.1 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>


[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Access to Alerts for Deleted Assets*
//RLP-103383, RLP-103463
|The ability to view resolved alerts for assets that have been deleted in cloud accounts onboarded to Prisma Cloud will be available for up to 90 days after asset deletion. After 90 days, these alerts will be permanently deleted from Prisma Cloud.

This change will be in effect starting July 1, 2023.
Before July 1, if you want to export all resolved alerts older than 90 days for assets that have been deleted on the cloud account, use this API endpoint https://pan.dev/prisma-cloud/api/cspm/get-alerts-v-2/ .

|===

[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents rrent Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.7.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION


2+|*Policy Updates—RQL*

|*AWS Application Load Balancer (ALB) is not using the latest predefined security policy*
//RLP-102409

|*Changes—* The policy description and recommendation steps have been updated. The policy RQL has been updated to check for the latest security policy userinput:[ELBSecurityPolicy-TLS13-1-2-2021-06] 

*Updated Description—* Identifies Application Load Balancers (ALBs) are not using the latest predefined security policy. A security policy is a combination of protocols and ciphers. The protocol establishes a secure connection between a client and a server and ensures that all data passed between the client and your load balancer is private. A cipher is an encryption algorithm that uses encryption keys to create a coded message. So it is recommended to use the latest predefined security policy which uses only secured protocol and ciphers.

We recommend using ELBSecurityPolicy-TLS13-1-2-2021-06 policy to meet compliance and security standards that require disabling certain TLS protocol versions or to support legacy clients that require deprecated ciphers.

*Severity—* Low

*Policy Type—* Config

*Current RQL—*

----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-elbv2-describe-load-balancers' AND json.rule = type equals application and listeners[?any(protocol equals HTTPS and sslPolicy exists and (sslPolicy does not contain ELBSecurityPolicy-FS-1-2-Res-2020-10 and sslPolicy does not contain ELBSecurityPolicy-TLS-1-2-Ext-2018-06))] exists
----

*Updated RQL—*

----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-elbv2-describe-load-balancers' AND json.rule = type equals application and listeners[?any(protocol equals HTTPS and sslPolicy exists and (sslPolicy does not contain ELBSecurityPolicy-TLS13-1-2-2021-06))] exists
----

*Impact—* Medium. New alerts will be generated in case ALB is not configured to use the latest security policy. Existing alerts for resources that are already using the latest security policy will be resolved as *Policy_updated*.


|*AWS EC2 instance that is reachable from untrust internet source to ports with high risk*
//RLP-104593

|*Changes—* Policy RQL is updated to check and report EC2 instance which are in active state.

*Severity—* High

*Policy Type—* Config

*Current RQL—*

----
config from network where source.network = UNTRUST_INTERNET and dest.resource.type = 'Instance' and dest.cloud.type = 'AWS' and protocol.ports in ( 'tcp/20:21', 'tcp/23', 'tcp/25', 'tcp/110', 'tcp/135', 'tcp/143', 'tcp/445', 'tcp/1433:1434', 'tcp/3000', 'tcp/3306', 'tcp/4333', 'tcp/5000', 'tcp/5432', 'tcp/5500', 'tcp/5601', 'tcp/8080', 'tcp/8088', 'tcp/8888', 'tcp/9200', 'tcp/9300' )
----

*Updated RQL—*

----
config from network where source.network = UNTRUST_INTERNET and dest.resource.type = 'Instance' and dest.cloud.type = 'AWS' and dest.resource.state = 'Active' and protocol.ports in ( 'tcp/20:21', 'tcp/23', 'tcp/25', 'tcp/110', 'tcp/135', 'tcp/143', 'tcp/445', 'tcp/1433:1434', 'tcp/3000', 'tcp/3306', 'tcp/4333', 'tcp/5000', 'tcp/5432', 'tcp/5500', 'tcp/5601', 'tcp/8080', 'tcp/8088', 'tcp/8888', 'tcp/9200', 'tcp/9300' )
----

*Impact—* Low. Alerts will be resolved for EC2 instances which are in inactive state.


|*Azure SQL Server ADS Vulnerability Assessment is disabled*
//RLP-101283

|*Changes—* The policy description and recommendation steps have been updated. The policy RQL has been updated according to new express configuration to check if ADS vulnerability assessment is disabled. 

*Updated Decsription—* Identifies Azure SQL Server which has ADS Vulnerability Assessment setting disabled. Advanced Data Security - Vulnerability Assessment service scans SQL databases for known security vulnerabilities and highlight deviations from best practices, such as misconfigurations, excessive permissions, and unprotected sensitive data. It is recommended to enable ADS - VA service.


*Severity—* Medium

*Policy Type—* Config

*Current RQL—*

----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-sql-server-list' AND json.rule = vulnerabilityAssessments[*].properties.storageContainerPath does not exist
----

*Updated RQL—*

----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-sql-server-list' AND json.rule = vulnerabilityAssessments[*].type does not exist 
----

*Impact—* Medium. New alerts will be generated if vulnerability assessment is disabled. Existing alerts will be resolved as will be resolved as *Policy_updated* when vulnerabilityAssessments[*].properties.storageContainerPath does not exist.

|===

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*AWS CloudHSM*
//RLP-104097

|*aws-cloudhsm-cluster*

Additional permission required:
 
* screen:[cloudhsm:DescribeClusters] 

You must manually add the permission or update the CFT template to enable it.

[NOTE]
====
Not supported in AWS China.
====

|*Amazon VPC*
//RLP-104781

|*aws-ec2-vpc-endpoint-service-permission*

Additional permission required:
 
* screen:[ec2:DescribeVpcEndpointServicePermissions] 

The Security Audit role includes the permission. 


|*Google Cloud Translation*
//RLP-104280

|*gcloud-translation-glossary*

Additional permissions required:
 
* screen:[cloudtranslate.locations.list] 
* screen:[cloudtranslate.glossaries.list]

The Viewer role includes the permissions.

|*OCI Compute*
//RLP-104045

|*oci-compute-image*

Additional permissions required:
 
* screen:[INSTANCE_IMAGE_INSPECT] 
* screen:[INSTANCE_IMAGE_READ]

You must update the Terraform template to enable the permissions.

|tt:[Update] *OCI Compute Instance*
//RLP-104280

|*oci-compute-instance*

The resource JSON for this API has been updated to include a new field *vnicIds*.

Additional permission required:

* screen:[VNIC_ATTACHMENT_READ]

You must update the Terraform template to enable the permission.

|===

[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|tt:[Prisma Cloud CSPM REST API for Cloud Accounts]
//RLP-100481

The following endpoints are deprecated for the AWS, GCP, and Azure cloud types:

* https://pan.dev/prisma-cloud/api/cspm/add-cloud-account/[POST /cloud/{cloud_type}]
* https://pan.dev/prisma-cloud/api/cspm/update-cloud-account/[PUT /cloud/{cloud_type}/{id}]
* https://pan.dev/prisma-cloud/api/cspm/get-cloud-account-status/[POST /cloud/status/{cloud_type}]

[NOTE]
====
You can continue to use the above endpoints for the Alibaba and OCI cloud accounts.
====

|23.6.1

|23.8.3

|* *AWS*
+
** https://pan.dev/prisma-cloud/api/cspm/add-aws-cloud-account/[POST /cas/v1/aws_account]
** https://pan.dev/prisma-cloud/api/cspm/update-aws-cloud-account/[PUT /cas/v1/aws_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-aws-cloud-account-status/[POST /cas/v1/cloud_account/status/aws]

* *Azure*
+
** https://pan.dev/prisma-cloud/api/cspm/add-azure-cloud-account/[POST /cas/v1/azure_account]
** https://pan.dev/prisma-cloud/api/cspm/update-azure-cloud-account/[PUT /cas/v1/azure_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-azure-cloud-account-status/[POST /cas/v1/cloud_account/status/azure]

* *GCP*
+
** https://pan.dev/prisma-cloud/api/cspm/add-gcp-cloud-account/[POST /cas/v1/gcp_account]
** https://pan.dev/prisma-cloud/api/cspm/update-gcp-cloud-account/[PUT/cas/v1/gcp_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-gcp-cloud-account-status/[POST /cas/v1/cloud_account/status/gcp]



|tt:[Prisma Cloud CSPM REST API for Alerts]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

| -
| -
| NA

|===
