[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.4.1 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>


[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Simplified Onboarding of AWS, Azure, and GCP Cloud Accounts*
//RLP-96371

|Beginning with the 23.4.2 release, Prisma Cloud will provide a simplified onboarding experience to adapt to your security priorities in a streamlined manner with support for CSPM, CWPP, Data Security, and Identity Security grouped as Foundational and/or Advanced capabilities (with a few enabled by default). The updated onboarding workflow provides a Faster First Time to Value (FTTV) by allowing you to onboard your AWS, Azure, or GCP cloud accounts and selecting the security capabilities in fewer clicks.

|*Changes to Policy Severity Level*
//RLP-90803

|Beginning with the 23.4.1 release, Prisma Cloud will make changes to our system default policies to help you identify the critical alerts and ensure that you can address them efficiently. The severity levels of the system default policies will be modified as part of the planned update. For more information, see the https://docs.paloaltonetworks.com/content/dam/techdocs/en_US/pdf/prisma/prisma-cloud/prerelease/policy-severity-level-changes.csv[list of policies] that are affected.

*Impact-* You may see:

* Changes in the severity of existing alerts
* Changes in your overall compliance status due to the modified severity of alerts
* Decrease or increase in the number of alerts, based on how your alert rules are set up according to the *Policy Severity* filter
* If you have configured your alert rules to send notifications to external integrations such as ServiceNow, this shift in the number of alerts may result in sending notifications for the modified alert.

If you have any questions, contact your Customer Success Representative.


|*S3 Flow Logs with Hourly Partition*
//RLP-76433

|If you are using S3 to ingest AWS flow logs with the 24 hour partition, you are required to switch to the hourly partition by April 15, 2023.

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/enable-flow-logs-for-amazon-s3[Configure Flow Logs] with the hourly partition and enable the additional fields required.


|*Update for Google Compute APIs*
//RLP-95461

|Beginning with the 23.4.1 release, Prisma Cloud will provide global region support, as well as a backend update to the resource ID for *gcloud-compute-url-maps*, *gcloud-compute-target-http-proxies*, and *gcloud-compute-target-https-proxies* APIs. As a result, all resources for these APIs will be deleted and then regenerated on the management console.

Existing alerts corresponding to these resources will be resolved as Resource_Updated, and new alerts will be generated against policy violations if any.

*Impact*—You may notice a reduced alert count. However, once the resources for *gcloud-compute-url-maps*, *gcloud-compute-target-http-proxies*, and *gcloud-compute-target-https-proxies* resume ingesting data, the alert count will return to the original numbers.

|===


[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the current Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.4.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

No Policy Updates for 23.4.1.


[#api-ingestions]
=== API Ingestions

The following API ingestion updates are planned for Prisma Cloud in 23.4.1:

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*Azure Virtual WAN*
//RLP-95728

|*azure-vpn-server-configurations*

Additional permission required:

* screen:[Microsoft.Network/vpnServerConfigurations/read]

The Reader role includes the permission.

|*Azure Virtual WAN*
//RLP-95723

|*azure-p2s-vpn-gateway*

Additional permission required:

* screen:[Microsoft.Network/p2sVpnGateways/read]

The Reader role includes the permission.


|*Google Certificate Authority Service*
//RLP-95648

|*gcloud-certificate-authority-certificate-template*

Additional permissions required:

* screen:[privateca.locations.list]
* screen:[privateca.certificateTemplates.list]
* screen:[privateca.certificateTemplates.getIamPolicy]

The Viewer role includes the permissions.


|*Google Traffic Director Network Service*
//RLP-95651

|*gcloud-traffic-director-network-service-gateway*

Additional permissions required:

* screen:[networkservices.locations.list]
* screen:[networkservices.gateways.list]

The Viewer role includes the permissions.


|*Google Traffic Director Network Service*
//RLP-95650

|*gcloud-traffic-director-network-service-mesh*

Additional permissions required:

* screen:[networkservices.locations.list]
* screen:[networkservices.meshes.list]
* screen:[networkservices.meshes.getIamPolicy]

The Viewer role includes the permissions.

|===

[#deprecation-notices]
=== Deprecation Notices

[cols="50%a,50%a"]
|===
2+|Deprecation Notice

|tt:[End of Support for AWS Classic EC2 Service]
//RLP-96041, Added in 23.3.2.
|The userinput:[aws-ec2-classic-instance] API is planned for deprecation at the end of April 2023. As AWS has announced the depreciation of the resource type, Prisma Cloud will no longer ingest the userinput:[aws-ec2-classic-instance] API. For more information, see https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/[Retiring EC2-Classic Networking].


|tt:[Prisma Cloud Data Security v1, v2 APIs]
|In the 23.4.1 release, the following Prisma Cloud Data Security APIs (v1, v2) for AWS cloud account onboarding, data settings, data profiles, snippets, and data patterns will be deprecated and new APIs (v3) will be added:

*Deprecating Cloud Accounts Endpoints*

* Add Data Security Config (AWS Org) - userinput:[POST /dlp/api/config/v2]
* Update Data Security Config (AWS Org) - userinput:[PUT /dlp/api/config/v2]
* Check Data Security Preconditions (AWS Org) - userinput:[POST  /dlp/api/v1/config/awsorg/status]
* Get Data Security Config (AWS Org) - userinput:[GET /dlp/api/config/v2/:accountId]

*New Cloud Accounts Endpoints*

* userinput:[POST /config/v3/account]
* userinput:[PUT /config/v3/account/{{accountId}}]
* userinput:[GET config/v3/account/awsorg/{{accountId}}/status]
* userinput:[GET /config/v3/account/awsorg/{{accountId}}]

*Deprecating Data Security Settings Endpoints*

* List Data Resources - userinput:[GET /dlp/api/v1/resource-inventory/resources]
* Update Data Scan Config - userinput:[PUT /dlp/api/config/v2/resource]
* List Data Patterns - userinput:[PUT /dlp/api/v1/dss-api/data-pattern]
* Add Data Pattern - userinput:[POST  /dlp/api/v1/dss-api/data-pattern]
* Clone Data Pattern - userinput:[POST /dlp/api/v1/dss-api/data-pattern/clone]
* Get Data Pattern Details - userinput:[GET /dlp/api/v1/dss-api/data-pattern/id/:patternId]
* Get Data Pattern By Name - userinput:[GET /dlp/api/v1/dss-api/data-pattern/name]
* Update Data Pattern - userinput:[PUT /dlp/api/v1/dss-api/data-pattern/:patternId]
* Delete Data Pattern - userinput:[DELETE /dlp/api/v1/dss-api/data-pattern/:patternId]
* List Data Profiles - userinput:[GET /dlp/api/v1/dss-api/data-profile]
* Add Data Profile - userinput:[POST /dlp/api/v1/dss-api/data-profile]
* Update Data Profile Status - userinput:[PUT /dlp/api/v1/dss-api/data-profile]
* Get Data Profile Details - userinput:[GET /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Update Data Profile - userinput:[PUT /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Clone Data Profile - userinput:[POST /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Delete Data Profile - userinput:[DELETE /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Get Snippet Configuration - userinput:[GET /dlp/api/v1/dss-api/snippets]
* Update Snippet Configuration - userinput:[POST /dlp/api/v1/dss-api/snippets]

*New Data Security Settings Endpoints*

* userinput:[GET /config/v3/resources]
* userinput:[PUT /config/v3/resource/configure]
* userinput:[GET /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api/data-pattern/clone/dssTenantId/{dssTenantId}]
* userinput:[GET /config/v3/dss-api/data-pattern/name/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api]
* userinput:[PUT /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}/pattern-id/{patternId}]
* userinput:[DELETE /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}/pattern-id/{patternId}]
* userinput:[GET /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}]
* userinput:[PUT /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}]
* userinput:[GET /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[PUT /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[POST /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[DELETE /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[GET /config/v3/dss-api/snippets/dssTenantId/{dssTenantId}"]
* userinput:[POST /config/v3/dss-api/snippets/dssTenantId/{dssTenantId}]


|tt:[Prisma Cloud CSPM REST API for Alerts]
|Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

|===
