[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.8.1 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<iam-policy-update>>
* <<api-ingestions>>
* <<deprecation-notices>>


[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Credit Requirements Updates*
//RLP-106498
| Starting August 2023, Prisma Cloud Enterprise Edition will reduce the number of credits required. The details are as follows:

* Visibility, Compliance, and Governance (for CSPM use cases) will only require 1 credit per virtual machine (AWS EC2s, Azure Virtual Machines and Virtual Machine Scale Sets, Google Cloud Google Compute Engine (GCE), Oracle Cloud (OCI) Compute, Alibaba Cloud ECS). 
Load Balancers, NAT gateways, Databases and Data Warehouse cloud resources will no longer require credits.

* IAM Security (for CIEM use cases) will only require 0.25 credit per virtual machine. 
Load Balancers, NAT gateways, Databases and Data Warehouse cloud resources will no longer require credits.

* Host Security credit requirements reduce from 1 to 0.5 credit per Host Defender.

* Container Security credit requirements reduce from 7 to  5 credits per Container Defender.

* Web Application and API Security credit requirements reduce from 30 to 2 credits per Defender performing inline protection.

These details will be reflected in the Prisma Cloud Enterprise Edition licensing guide in August.

|*Code Security has a New Name*
//RLP-106732
|Cloud Application Security is the new name for the combination of the Cloud Code Security capabilities and the newly introduced CI/CD Security module. CI/CD Security is available as a standard a-la-carte option or as an add-on with the Prisma Cloud Runtime Security Foundations or Advanced bundles.


|*New Policies for Cloud Code Security*
//RLP-107182
|Starting with the 23.8.1 release, 125 new Config policies of subtype Build that enable the detection of CI/CD security risks  will be enabled by default and available on the *Policies* page. With the release, the Code Security capabilties are being renamed as Application Security, and also will introduce CI/CD Security.

These new policies will not generate any alerts until you enable  the new *CI/CD Security* capability on "Settings > Application Security Configuration". When you subscribe the CI/CD Security capability, when it becomes available, the alerts will display on "Application Security > CI/CD Risks".

|===

[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents rrent Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.8.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION

2+|*Policy Updates—RQL*

|*GCP VPC Flow logs for the subnet is set to Off*
//RLP-107254
|*Changes—* The policy RQL will be updated to exclude checking for proxy-only subnets in the policy as VPC flow logs are not supported for proxy-only subnets.

*Severity—* Informational

*Policy Type—* Config

*Current RQL—*

----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-compute-networks-subnets-list' AND json.rule = purpose does not contain INTERNAL_HTTPS_LOAD_BALANCER and (enableFlowLogs is false or enableFlowLogs does not exist)
----

*Updated RQL—*

----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-compute-networks-subnets-list' AND json.rule = purpose does not contain INTERNAL_HTTPS_LOAD_BALANCER and purpose does not contain "REGIONAL_MANAGED_PROXY" and (enableFlowLogs is false or enableFlowLogs does not exist)
----

*Impact—* Low. Alerts generated for proxy-only subnets will be resolved as *Policy_updated*.


|===

[#iam-policy-update]
=== IAM Policy Updates
//RLP-106743

Prisma Cloud will update the following policy as follows:

[cols="20%a,20%a,30%a,30%a"]
|===
|CURRENT POLICY NAME
|UPDATED POLICY NAME
|CURRENT RQL
|UPDATED RQL

|*EC2 with IAM role attached has s3:GetObject permission*
|*EC2 with IAM role attached has s3:GetObject and s3:ListBucket permissions*
|----
config from iam where dest.cloud.type = 'AWS' AND action.name IN ('s3:ListBucket') AND source.cloud.service.name = 'ec2' AND source.cloud.resource.type = 'instance'
----
|----
config from iam where dest.cloud.type = 'AWS' AND action.name CONTAINS ALL ('s3:ListBucket', 's3:GetObject') AND source.cloud.service.name = 'ec2' AND source.cloud.resource.type = 'instance'
----
|===

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*AWS Cost Explorer*
//RLP-106974	
|*aws-costexplorer-cost-and-usage*

Additional permission required:

* screen:[ce:GetCostAndUsage]

You must manually add the permission or update the CFT template to enable the permission.


|*Amazon ElastiCache*
//RLP-106980	
|*aws-elasticache-user*

Additional permission required:

* screen:[elasticache:DescribeUsers]

The Security Audit role includes the permission.

|*Amazon Macie*
//RLP-106977
|*aws-macie2-administrator-account*

Additional permission required:

* screen:[macie2:ListOrganizationAdminAccounts]

You must manually add the permission or update the CFT template to enable the permission.

|tt:[Update] *Amazon Simple Email Service*
//RLP-106954
|*aws-ses-identities*

Additional permission required:

* screen:[ses:GetIdentityVerificationAttributes]

|tt:[Update] *Amazon VPC*
//RLP-105853
|*aws-ec2-describe-flow-logs*

The resource JSON for this API will be updated to include the screen:[DeliverLogStatus] field.

|*Google Firebase App Distribution*
//RLP-104282	
|*gcloud-firebase-app-distribution-tester*

Additional permissions required:

* screen:[resourcemanager.projects.get]
* screen:[firebaseappdistro.testers.list]

The Viewer role includes the permissions.

|*Google Cloud Identity Platform*
//RLP-105411
|*gcloud-identity-platform-tenant-configuration*

Additional permissions required:

* screen:[identitytoolkit.tenants.list]
* screen:[identitytoolkit.tenants.getIamPolicy]

The Viewer role includes the permissions.

|*Google Cloud Identity Platform*
//RLP-106906
|*gcloud-identity-platform-project-user-account*

Additional permission required:

* screen:[firebaseauth.users.get]

The Viewer role includes the permission.

|*Google Cloud Identity Platform*
//RLP-106907
|*gcloud-identity-platform-tenant-user-account*

Additional permissions required:

* screen:[identitytoolkit.tenants.list]
* screen:[firebaseauth.users.get]

The Viewer role includes the permissions.


|*Google Cloud Identity Platform*
//RLP-106908	
|*gcloud-identity-platform-project-configuration*

Additional permission required:

* screen:[firebaseauth.configs.get]

The Viewer role includes the permission.



|===

[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|tt:[Prisma Cloud CSPM REST API for Cloud Accounts]
//RLP-100481

The following endpoints are deprecated for the AWS, GCP, and Azure cloud types:

* https://pan.dev/prisma-cloud/api/cspm/add-cloud-account/[POST /cloud/{cloud_type}]
* https://pan.dev/prisma-cloud/api/cspm/update-cloud-account/[PUT /cloud/{cloud_type}/{id}]
* https://pan.dev/prisma-cloud/api/cspm/get-cloud-account-status/[POST /cloud/status/{cloud_type}]

[NOTE]
====
You can continue to use the above endpoints for the Alibaba and OCI cloud accounts.
====

|23.6.1

|23.8.3

|* *AWS*
+
** https://pan.dev/prisma-cloud/api/cspm/add-aws-cloud-account/[POST /cas/v1/aws_account]
** https://pan.dev/prisma-cloud/api/cspm/update-aws-cloud-account/[PUT /cas/v1/aws_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-aws-cloud-account-status/[POST /cas/v1/cloud_account/status/aws]

* *Azure*
+
** https://pan.dev/prisma-cloud/api/cspm/add-azure-cloud-account/[POST /cas/v1/azure_account]
** https://pan.dev/prisma-cloud/api/cspm/update-azure-cloud-account/[PUT /cas/v1/azure_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-azure-cloud-account-status/[POST /cas/v1/cloud_account/status/azure]

* *GCP*
+
** https://pan.dev/prisma-cloud/api/cspm/add-gcp-cloud-account/[POST /cas/v1/gcp_account]
** https://pan.dev/prisma-cloud/api/cspm/update-gcp-cloud-account/[PUT/cas/v1/gcp_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-gcp-cloud-account-status/[POST /cas/v1/cloud_account/status/gcp]



|tt:[Prisma Cloud CSPM REST API for Alerts]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

| -
| -
| NA

|===
