[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.5.1 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

//* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>



[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the current Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.5.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION

2+|*Policy Updates-RQL*

|*Azure VM instance in running state that is internet reachable with unrestricted access (0.0.0.0/0) other than HTTP/HTTPS port*
//RLP-96676

|*Changes—* The policy name and the RQL is updated to report instance configured with HTTP (80) and HTTP (443) port and instance which are in active state only. 

*Current Name—* Azure VM instance in running state that is internet reachable with unrestricted access (0.0.0.0/0) other than HTTP/HTTPS port
*Updated Name—* Azure Virtual Machine in running state that is internet reachable with unrestricted access (0.0.0.0/0)

*Updated Description—* Identifies azure VM instances in running state that are internet reachable with unrestricted access (0.0.0.0/0). VM instances with unrestricted access to the internet may enable bad actors to use brute force on a system to gain unauthorised access to the entire network. As a best practice, restrict traffic from unknown IP addresses and limit the access to known hosts, services, or specific entities.

*Current RQL—*

----
config from network where source.network = '0.0.0.0/0' and address.match.criteria = 'full_match' and dest.resource.type = 'Instance' and dest.cloud.type = 'AZURE' and protocol.ports in ( 'tcp/0:79', 'tcp/81:442', 'tcp/444:65535' ) and dest.resource.state = 'Active'
----

*Updated RQL—*

----
config from network where source.network = '0.0.0.0/0' and address.match.criteria = 'full_match' and dest.resource.type = 'Instance' and dest.cloud.type = 'AZURE' and dest.resource.state = 'Active'
----

*Impact—* Medium. New alerts will be generated when instance is exposed to internet and configured where HTTP / HTTPS port.

|*GCP Kubernetes Engine Clusters have Master authorized networks disabled*
//RLP-89949
|*Changes—* The policy RQL is updated to reflect the latest CSP behavior.

*Current RQL—*

----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-container-describe-clusters' AND json.rule = status equals RUNNING and (masterAuthorizedNetworksConfig.[*] is empty or masterAuthorizedNetworksConfig.enabled equals "false")
----

*Updated RQL—*

----
config from cloud.resource where cloud.type = 'gcp' AND api.name = 'gcloud-container-describe-clusters' AND json.rule = status equals RUNNING and masterAuthorizedNetworksConfig.enabled does not equal "true"
----

*Impact—* Medium. New alerts will be generated for the failing resources. This includes resources where Master authorized networks was previously enabled but are now configured as disabled.

2+|*Policy Deletions*

|*GCP Policies*
//RLP-98183, RLP-98182, RLP-88162
|The following policies will be deleted because GCP has deprecated basic authentication, Kubernetes dashboard, and Istio for GKE.

* GCP Kubernetes Engine Clusters Basic Authentication is set to Enabled
* GCP Kubernetes Engine Clusters web UI/Dashboard is set to Enabled
* GCP Kubernetes cluster istioConfig not enabled

*Impact*— Low. Previously generated alerts will be resolved as *Policy_Deleted*. The out-of-the-box compliance mappings for the above policies will be removed and can affect the compliance score.


|===


[#api-ingestions]
=== API Ingestions

The following API ingestion updates are planned for Prisma Cloud in 23.5.1:

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*AWS IoT Analytics* 
//RLP-98201

|*aws-iot-analytics-datastore* 

Additional permissions required:
 
* screen:[iotanalytics:ListDatastores] 
* screen:[iotanalytics:ListTagsForResource]

You must manually add the permissions or update the CFT template to enable them.

[NOTE]
====
Not supported in AWS Gov.
====

|*AWS IoT Analytics* 
//RLP-98194

|*aws-iot-analytics-channel* 

Additional permissions required:
 
* screen:[iotanalytics:ListChannels] 
* screen:[iotanalytics:ListTagsForResource] 

You must manually add the permissions or update the CFT template to enable them.

[NOTE]
====
Not supported in AWS Gov.
====

|*AWS Security Hub* 
//RLP-98203
|*aws-securityhub-enabled-standards* 

Additional permission required:
 
* screen:[securityhub:GetEnabledStandards] 

The Security Audit role includes the permission. 

|*Azure Compute* 
//RLP-96386
|*azure-compute-gallery* 

Additional permission required:
 
* screen:[Microsoft.Compute/galleries/read]

The Reader role includes the permission. 

|*Azure Managed Identity* 
//RLP-96260
|*azure-managed-identity-user-assigned-identities* 

Additional permission required:
 
* screen:[Microsoft.ManagedIdentity/userAssignedIdentities/read]

The Reader role includes the permission. 


|*Azure Compute* 
//RLP-95730
|*azure-compute-gallery-image* 

Additional permissions required:
 
* screen:[Microsoft.Compute/galleries/read] 
* screen:[Microsoft.Compute/galleries/images/read]

The Reader role includes the permissions. 


|*Google Hybrid Connectivity*
//RLP-98575
|*gcloud-hybrid-connectivity-global-hub*

Additional permissions required:

* screen:[networkconnectivity.hubs.list]
* screen:[networkconnectivity.hubs.getIamPolicy]

The Viewer role includes the permissions.


|*Google Hybrid Connectivity*
//RLP-98576
|*gcloud-hybrid-connectivity-spoke*

Additional permissions required:

* screen:[networkconnectivity.locations.list]
* screen:[networkconnectivity.spokes.list]
* screen:[networkconnectivity.spokes.getIamPolicy]

The Viewer role includes the permissions.

|*Google Serverless VPC Access* 
//RLP-97256

|*gcloud-serverless-vpc-access-connector* 

Additional permissions required:
 
* screen:[vpcaccess.locations.list] 
* screen:[vpcaccess.connectors.list]

The Viewer role includes the permissions. 


|*Google Stackdriver Logging*
//RLP-98574
|*gcloud-logging-default-sink-exclusion*

Additional permission required:

* screen:[logging.exclusions.list]

The Viewer role includes the permission.

|*OCI Service Mesh* 
//RLP-97903

|*oci-service-mesh-virtualservice-routetable* 

Additional permissions required:
 
* screen:[MESH_VIRTUAL_SERVICE_ROUTE?_TABLE_LIST] 
* screen:[MESH_VIRTUAL_SERVICE_ROUTE?_TABLE_READ]

You must update the Terraform template to enable the permissions.


|*OCI Service Mesh* 
//RLP-97898
|*oci-service-mesh-virtualservice* 

Additional permissions required:
 
* screen:[MESH_VIRTUAL_SERVICE?_LIST] 
* screen:[MESH_VIRTUAL_SERVICE?_READ]

You must update the Terraform template to enable the permissions.

|===

[#deprecation-notices]
=== Deprecation Notices

[cols="50%a,50%a"]
|===
2+|Deprecation Notice

|tt:[Prisma Cloud CSPM REST API for Alerts]
|Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

|===
