[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.7.1 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>


[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

There are no change in behavior for Prisma Cloud release 23.7.1.

|===


[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents rrent Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.7.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

There are no policy updates for Prisma Cloud release 23.7.1.

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*Amazon VPC*
//RLP-104781

|*aws-ec2-vpc-endpoint-service-permission*

Additional permission required:
 
* screen:[ec2:DescribeVpcEndpointServicePermissions] 

The Security Audit role includes the permission. 

|*AWS CloudHSM*
//RLP-104097

|*aws-cloudhsm-cluster*

Additional permission required:
 
* screen:[cloudhsm:DescribeClusters] 

The are no roles that include the permission. 

|*Azure Managed Services*
//RLP-104617

|*azure-managed-service-marketplace-registration-definitions*

Additional permission required:
 
* screen:[Microsoft.ManagedServices/marketplaceRegistrationDefinitions/read] 

The Reader role includes the permission.

|*Google Cloud Translation*
//RLP-104281

|*gcloud-translation-model*

Additional permissions required:
 
* screen:[cloudtranslate.locations.list] 
* screen:[automl.models.list]

The Viewer role includes the permissions.

|*Google Cloud Translation*
//RLP-104280

|*gcloud-translation-glossary*

Additional permissions required:
 
* screen:[cloudtranslate.locations.list] 
* screen:[cloudtranslate.glossaries.list]

The Viewer role includes the permissions.

|*Google Cloud Translation*
//RLP-104275

|*gcloud-translation-native-dataset*

Additional permissions required:
 
* screen:[cloudtranslate.locations.list] 
* screen:[automl.datasets.list]

The Viewer role includes the permissions.
+
[NOTE]
====
Legacy Datasets are not ingested as part of this API.
====

|*OCI Compute*
//RLP-104045

|*oci-compute-image*

Additional permissions required:
 
* screen:[INSTANCE_IMAGE_INSPECT] 
* screen:[INSTANCE_IMAGE_READ]

You must update the Terraform template to enable the permissions.

|tt:[Update] *OCI Compute Instance*
//RLP-104280

|*oci-compute-instance*

The resource JSON for this API has been updated to include a new field vnicIds.

Additional permission required:

* screen:[VNIC_ATTACHMENT_READ]

You must update the Terraform template to enable the permission.

|===

[#deprecation-notices]
=== Deprecation Notices

[cols="35%a,10%a,10%a,45%a"]
|===

|*Deprecated Endpoints or Parameters*
|*Deprecated Release*
|*Sunset Release*
|*Replacement Endpoints*

|tt:[Prisma Cloud CSPM REST API for Cloud Accounts]
//RLP-100481

The following endpoints are deprecated for the AWS, GCP, and Azure cloud types:

* https://pan.dev/prisma-cloud/api/cspm/add-cloud-account/[POST /cloud/{cloud_type}]
* https://pan.dev/prisma-cloud/api/cspm/update-cloud-account/[PUT /cloud/{cloud_type}/{id}]
* https://pan.dev/prisma-cloud/api/cspm/get-cloud-account-status/[POST /cloud/status/{cloud_type}]

[NOTE]
====
You can continue to use the above endpoints for the Alibaba and OCI cloud accounts.
====

|23.6.1

|23.8.3

|* *AWS*
+
** https://pan.dev/prisma-cloud/api/cspm/add-aws-cloud-account/[POST /cas/v1/aws_account]
** https://pan.dev/prisma-cloud/api/cspm/update-aws-cloud-account/[PUT /cas/v1/aws_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-aws-cloud-account-status/[POST /cas/v1/cloud_account/status/aws]

* *Azure*
+
** https://pan.dev/prisma-cloud/api/cspm/add-azure-cloud-account/[POST /cas/v1/azure_account]
** https://pan.dev/prisma-cloud/api/cspm/update-azure-cloud-account/[PUT /cas/v1/azure_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-azure-cloud-account-status/[POST /cas/v1/cloud_account/status/azure]

* *GCP*
+
** https://pan.dev/prisma-cloud/api/cspm/add-gcp-cloud-account/[POST /cas/v1/gcp_account]
** https://pan.dev/prisma-cloud/api/cspm/update-gcp-cloud-account/[PUT/cas/v1/gcp_account/{id}]
** https://pan.dev/prisma-cloud/api/cspm/get-gcp-cloud-account-status/[POST /cas/v1/cloud_account/status/gcp]



|tt:[Prisma Cloud CSPM REST API for Alerts]
//RLP-25031, RLP-25937

Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

| -
| -
| NA

|===
