[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.4.2 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

* <<changes-in-existing-behavior>>
* <<add-ip-address>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>


[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Simplified Onboarding of AWS, Azure, and GCP Cloud Accounts*
//RLP-96371

|Beginning with the 23.4.2 release, Prisma Cloud will provide a simplified onboarding experience to adapt to your security priorities in a streamlined manner with support for CSPM, CWPP, Data Security, and Identity Security grouped as Foundational and/or Advanced capabilities (with a few enabled by default). The updated onboarding workflow provides a Faster First Time to Value (FTTV) by allowing you to onboard your AWS, Azure, or GCP cloud accounts and selecting the security capabilities in fewer clicks.

|tt:[Enhancement] *Auto-Enable Default Policies in Enterprise Settings*
//RLP-97518

|Beginning with the 23.4.2 release, Prisma Cloud will make changes to the Auto-Enable Default Policies severity selected under Enterprise Settings to help you identify the critical alerts and ensure that you can address them efficiently. For the default policies, critical and high severity levels will be selected as part of the planned update. 

*Impact—*

* If you had previously selected Medium severity, it will now also include Critical.
* If you had previously selected High and Medium severities, it will now also include Critical.
* If you had previously selected Critical severity, it will be retained.
* If you don't select any option, Critical severity is still added.

|*Rate Limit Exception for GCP APIs*
//RLP-73146
|Beginning with the 23.4.2 release, API calls from Prisma Cloud will use quota from the onboarded GCP Projects instead of the GCP Project where the service account is created. This change will enable Prisma Cloud to ingest resource metadata across multiple projects without exceeding the GCP API rate limits. 

To ensure continuous insights into all your GCP resources, perform the following tasks:

* Grant either a new permission userinput:[serviceusage.services.use] or add a new role *Service Usage Consumer* userinput:[(roles/serviceusage.serviceUsageConsumer)] to the service account that Prisma Cloud uses to access GCP APIs.

* tt:[Optional] Enable the following GCP services on each target project from which Prisma Cloud gets resource metadata.

** screen:[appengine.googleapis.com]
** screen:[recommender.googleapis.com]
** screen:[sqladmin.googleapis.com]
** screen:[apikeys.googleapis.com]
** screen:[iam.googleapis.com]
** screen:[cloudresourcemanager.googleapis.com]
** screen:[orgpolicy.googleapis.com] 
** screen:[cloudasset.googleapis.com]
** screen:[accessapproval.googleapis.com] 
** screen:[essentialcontacts.googleapis.com]

[NOTE]
====
If you use a Terraform template, the permissions to the GCP service account will be updated automatically.
====

*Impact*—If the above tasks are not completed, rate limit exception errors may occur for Prisma Cloud's authorized API calls to GCP.


|*S3 Flow Logs with Hourly Partition*
//RLP-76433

|If you are using S3 to ingest AWS flow logs with the 24 hour partition, you are required to switch to the hourly partition by April 15, 2023.

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-your-aws-account/enable-flow-logs-for-amazon-s3[Configure Flow Logs] with the hourly partition and enable the additional fields required.

|*Update for Google Compute APIs*
//RLP-47280

|Beginning in the 23.4.2 release, Prisma Cloud will provide global region support, as well as a backend update to the resource ID for *gcloud-compute-internal-lb-backend-service* API. As a result, all resources for these APIs will be deleted and then regenerated on the management console.

Existing alerts corresponding to these resources will be resolved as Resource_Updated, and new alerts will be generated against policy violations if any.

*Impact*—You may notice a reduced alert count. However, once the resources for *gcloud-compute-internal-lb-backend-service* resume ingesting data, the alert count will return to the original numbers.


|===


[#add-ip-address]
=== Addition of New IP Addresses
//RLP-96660, TLDO-466
Beginning with the 23.4.2 release, Prisma Cloud will add the following NAT IP addresses to the existing list. Make sure to review the list and update the IP addresses in your allow lists.

[cols="50%a,50%a"]
|===
|*Prisma Cloud URL (AWS Region)*
|*Source IP Address to Allow*


|http://app.prismacloud.io/[app.prismacloud.io]

us-east-1 (N.Virginia)

|3.210.133.47

34.235.13.250

44.207.239.90

|http://app2.prismacloud.io/[app2.prismacloud.io]

us-east-2 (Ohio)

|18.116.185.157

18.223.154.151

3.136.199.10

|http://app3.prismacloud.io/[app3.prismacloud.io]

us-west-2 (Oregon)

|44.233.39.196

52.12.85.11

54.70.207.107

|http://app4.prismacloud.io/[app4.prismacloud.io]

us-west-1 (N.California)

|184.72.47.199

54.193.251.180

54.241.31.130

*Compute SaaS Console Region (GCP)*
New egress IPs (from console to the internet) in us-west 1 (Oregon)

* 35.230.69.118
* 34.82.138.152

|http://app.ind.prismacloud.io/[app.ind.prismacloud.io]

(India) 

|13.126.142.108

3.108.78.191

65.0.233.228

|http://app.sg.prismacloud.io/[app.sg.prismacloud.io]

ap-southeast-1 (Singapore)

|13.251.200.128

18.136.72.0

18.139.106.36

|http://app.anz.prismacloud.io/[app.anz.prismacloud.io]

ap-southeast-2 (Sydney)

|13.55.65.214

3.104.84.8

54.66.162.181

|http://app.jp.prismacloud.io/[app.jp.prismacloud.io]

ap-northeast-1 (Tokyo)

|18.178.170.193

18.182.113.156

3.114.23.157

|http://app.ca.prismacloud.io/[app.ca.prismacloud.io]

ca-central-1 (Canada - Central)

|3.97.19.141

3.97.195.202

3.97.251.220

|http://app.eu.prismacloud.io/[app.eu.prismacloud.io]

eu-central-1 (Frankfurt)

|18.184.42.114

3.73.209.143

3.75.34.63

|http://app2.eu.prismacloud.io/[app2.eu.prismacloud.io]

eu-west-1 (Ireland)

|52.208.88.215

54.170.230.172

54.72.135.50

|http://app.uk.prismacloud.io/[app.uk.prismacloud.io]

eu-west2 (London)

|13.42.159.205

3.8.248.150

35.176.28.215

|http://app.fr.prismacloud.io/[app.fr.prismacloud.io]

eu-west-3 (Paris)

|13.36.26.86

13.37.138.49

13.37.20.19

|===



[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the current Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.4.2.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

No Policy Updates for 23.4.2.


[#api-ingestions]
=== API Ingestions

The following API ingestion updates are planned for Prisma Cloud in 23.4.2:

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*Amazon Firewall Manager*
//RLP-97013
|*aws-fms-admin-account*

Additional permission required:

* screen:[fms:GetAdminAccount]

You must manually add the permission or update the CFT template to enable them.

|*Amazon Firewall Manager*
//RLP-97037
|*aws-fms-compliance-status*

Additional permissions required:

* screen:[fms:ListPolicies]
* screen:[fms:ListComplianceStatus]

The Security Audit role includes the permissions.


|*Amazon Firewall Manager*
//RLP-95502
|*aws-fms-policy*

Additional permissions required:

* screen:[fms:GetAdminAccount]
* screen:[fms:ListPolicies]
* screen:[fms:GetPolicy]

The Security Audit role only includes the * screen:[fms:ListPolicies] permission.

[NOTE]
====
You must manually add the permission or update the CFT template to enable screen:[fms:GetPolicy] and screen:[fms:GetAdminAccount] .
====

|tt:[Update] *Amazon RDS*
//RLP-97823
|*aws-rds-db-cluster*

This API is updated to include a new field screen:[dBclusterParameterGroupArn] in the resource JSON.


|*Azure CDN*
//RLP-96258
|*azure-frontdoor-standardpremium-origin-groups*

Additional permissions required:

* screen:[Microsoft.Cdn/profiles/read]
* screen:[Microsoft.Cdn/profiles/origingroups/read]

The Reader role includes the permissions.

|*Azure CDN*
//RLP-96252
|*azure-frontdoor-standardpremium-security-policies*

Additional permissions required:

* screen:[Microsoft.Cdn/profiles/read]
* screen:[Microsoft.Cdn/profiles/securitypolicies/read]

The Reader role includes the permissions.

|tt:[Update] *Azure Event Hubs*
//RLP-93890

|*azure-event-hub-namespace*

This API is updated to include the following new fields in the resource JSON:

* screen:[MinimumTlsVersion]
* screen:[disableLocalAuth]

|tt:[Update] *Azure Service Bus*
//RLP-93891

|*azure-service-bus-namespace*

This API is updated to include a new field screen:[MinimumTlsVersion] in the resource JSON.

|*Google Cloud Function*
//RLP-96702
|*gcloud-cloud-function-v2*

Additional permissions required:

* screen:[cloudfunctions.locations.list]
* screen:[cloudfunctions.functions.list]
* screen:[cloudfunctions.functions.getIamPolicy]

The Viewer role includes the permissions.


|*Google Cloud Memorystore for Memcached*
//RLP-96697
|*gcloud-memorystore-memcached-instance*

Additional permissions required:

* screen:[memcache.locations.list]
* screen:[memcache.instances.list]

The Viewer role includes the permissions.


|*OCI Database*
//RLP-95386
|*oci-database-autonomous-database*

Additional permission required:

* screen:[AUTONOMOUS_DATABASE_INSPECT]

You must download and execute the Terraform template from the console to enable the permission.


|*OCI Database*
//RLP-95388
|*oci-database-db-home*

Additional permission required:

* screen:[DB_HOME_INSPECT]

You must download and execute the Terraform template from the console to enable the permission.

|*OCI Database*
//RLP-95399
|*oci-database-db-home-patch*

Additional permission required:

* screen:[DB_HOME_INSPECT]

You must download and execute the Terraform template from the console to enable the permission.

|*OCI Database*
//RLP-95402
|*oci-database-db-system-patch*

Additional permission required:

* screen:[DB_SYSTEM_INSPECT]

You must download and execute the Terraform template from the console to enable the permission.

|*OCI DataLabeling*
//RLP-91477
|*oci-datalabeling-dataset*

Additional permissions required:

* screen:[DATA_LABELING_DATASET_INSPECT]
* screen:[DATA_LABELING_DATASET_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI File Storage*
//RLP-91466
|*oci-file-storage-mount-target*

Additional permissions required:

* screen:[COMPARTMENT_INSPECT]
* screen:[MOUNT_TARGET_INSPECT]
* screen:[MOUNT_TARGET_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI JMS*
//RLP-91469
|*oci-jms-fleet*

Additional permissions required:

* screen:[FLEET_INSPECT]
* screen:[FLEET_READ]

You must download and execute the Terraform template from the console to enable the permissions.


|*OCI Service Mesh*
//RLP-93739
|*oci-service-mesh-access-policy*

Additional permissions required:

* screen:[MESH_ACCESS​_POLICY_LIST]
* screen:[MESH_ACCESS​_POLICY_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI Service Mesh*
//RLP-93736
|*oci-service-mesh-virtual-deployment*

Additional permissions required:

* screen:[MESH_VIRTUAL​_DEPLOYMENT_LIST]
* screen:[MESH_VIRTUAL​_DEPLOYMENT_READ]
* screen:[MESH_VIRTUAL_DEPLOYMENT​_PROXY_CONFIG_READ]
* screen:[MESH_PROXY_DETAILS_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI Service Mesh*
//RLP-93733
|*oci-service-mesh-meshes*

Additional permissions required:

* screen:[SERVICE_MESH_LIST]
* screen:[SERVICE_MESH_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI Speech*
//RLP-92726
|*oci-speech-transcription-job*

Additional permissions required:

* screen:[AI_SERVICE_SPEECH_TRANSCRIPTION_JOB_INSPECT]
* screen:[AI_SERVICE_SPEECH_TRANSCRIPTION_JOB_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI Vision*
//RLP-92722
|*oci-vision-model*

Additional permissions required:

* screen:[AI_SERVICE_VISION_MODEL_INSPECT]
* screen:[AI_SERVICE_VISION_MODEL_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI Vision*
//RLP-92718
|*oci-vision-project*

Additional permissions required:

* screen:[AI_SERVICE_VISION_PROJECT_INSPECT]
* screen:[AI_SERVICE_VISION_PROJECT_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|===

[#deprecation-notices]
=== Deprecation Notices

[cols="50%a,50%a"]
|===
2+|Deprecation Notice

|tt:[Prisma Cloud Data Security v1, v2 APIs]
//RLP-96733
|In the 23.4.2 release, the following Prisma Cloud Data Security APIs (v1, v2) for AWS cloud account onboarding, data settings, data profiles, snippets, and data patterns will be deprecated and new APIs (v3) will be added:

*Deprecating Cloud Accounts Endpoints*

* Add Data Security Config (AWS Org) - userinput:[POST /dlp/api/config/v2]
* Update Data Security Config (AWS Org) - userinput:[PUT /dlp/api/config/v2]
* Check Data Security Preconditions (AWS Org) - userinput:[POST  /dlp/api/v1/config/awsorg/status]
* Get Data Security Config (AWS Org) - userinput:[GET /dlp/api/config/v2/:accountId]

*New Cloud Accounts Endpoints*

* userinput:[POST /config/v3/account]
* userinput:[PUT /config/v3/account/{{accountId}}]
* userinput:[GET config/v3/account/awsorg/{{accountId}}/status]
* userinput:[GET /config/v3/account/awsorg/{{accountId}}]

*Deprecating Data Security Settings Endpoints*

* List Data Resources - userinput:[GET /dlp/api/v1/resource-inventory/resources]
* Update Data Scan Config - userinput:[PUT /dlp/api/config/v2/resource]
* List Data Patterns - userinput:[PUT /dlp/api/v1/dss-api/data-pattern]
* Add Data Pattern - userinput:[POST  /dlp/api/v1/dss-api/data-pattern]
* Clone Data Pattern - userinput:[POST /dlp/api/v1/dss-api/data-pattern/clone]
* Get Data Pattern Details - userinput:[GET /dlp/api/v1/dss-api/data-pattern/id/:patternId]
* Get Data Pattern By Name - userinput:[GET /dlp/api/v1/dss-api/data-pattern/name]
* Update Data Pattern - userinput:[PUT /dlp/api/v1/dss-api/data-pattern/:patternId]
* Delete Data Pattern - userinput:[DELETE /dlp/api/v1/dss-api/data-pattern/:patternId]
* List Data Profiles - userinput:[GET /dlp/api/v1/dss-api/data-profile]
* Add Data Profile - userinput:[POST /dlp/api/v1/dss-api/data-profile]
* Update Data Profile Status - userinput:[PUT /dlp/api/v1/dss-api/data-profile]
* Get Data Profile Details - userinput:[GET /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Update Data Profile - userinput:[PUT /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Clone Data Profile - userinput:[POST /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Delete Data Profile - userinput:[DELETE /dlp/api/v1/dss-api/data-profile/id/:profileId]
* Get Snippet Configuration - userinput:[GET /dlp/api/v1/dss-api/snippets]
* Update Snippet Configuration - userinput:[POST /dlp/api/v1/dss-api/snippets]

*New Data Security Settings Endpoints*

* userinput:[GET /config/v3/resources]
* userinput:[PUT /config/v3/resource/configure]
* userinput:[GET /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api/data-pattern/clone/dssTenantId/{dssTenantId}]
* userinput:[GET /config/v3/dss-api/data-pattern/name/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api]
* userinput:[PUT /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}/pattern-id/{patternId}]
* userinput:[DELETE /config/v3/dss-api/data-pattern/dssTenantId/{dssTenantId}/pattern-id/{patternId}]
* userinput:[GET /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}]
* userinput:[POST /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}]
* userinput:[PUT /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}]
* userinput:[GET /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[PUT /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[POST /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[DELETE /config/v3/dss-api/data-profile/dssTenantId/{dssTenantId}/id/{profileId}]
* userinput:[GET /config/v3/dss-api/snippets/dssTenantId/{dssTenantId}"]
* userinput:[POST /config/v3/dss-api/snippets/dssTenantId/{dssTenantId}]


|tt:[End of Support for AWS Classic EC2 Service]
//RLP-96041, Added in 23.3.2.
|The userinput:[aws-ec2-classic-instance] API is planned for deprecation at the end of April 2023. As AWS has announced the depreciation of the resource type, Prisma Cloud will no longer ingest the userinput:[aws-ec2-classic-instance] API. For more information, see https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/[Retiring EC2-Classic Networking].


|tt:[Prisma Cloud CSPM REST API for Alerts]
|Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

|===
