[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.6.1 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>


[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Rate Limit on POST /login Endpoint*
//RLP-102319- placeholder description

|Starting with 23.6.2, the https://pan.dev/prisma-cloud/api/cspm/app-login/[POST /login] endpoint will enforce rate limiting (HTTP Response Code 429).

|*S3 Flow Logs with Hourly Partition*
//RLP-76433

|If you currently ingest AWS flow logs using S3 with the 24-hour partition, you need to change it to the hourly partition before June 1, 2023.

To make this change, https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/configure-flow-logs[Configure Flow Logs] to use the hourly partition and enable the required additional fields.

*Impact*— VPC Flow logs with partitions set to *Every 24 hours (default)* will be disabled. As a result, you will no longer be able to monitor or receive alerts for these logs.


|*Access to Alerts for Deleted Assets*
//RLP-103383
|The ability to view resolved alerts for assets that have been deleted in cloud accounts onboarded to Prisma Cloud will be available for up to 90 days after asset deletion. 

This change will be in effect starting July 1, 2023.
Before July 1, if you want to export all resolved alerts older than 90 days for assets that have been deleted on the cloud account, use this API endpoint https://pan.dev/prisma-cloud/api/cspm/get-alerts-v-2/ .
|===


[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the current Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.6.1.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION


2+|*Policy Updates—RQL*

|*AWS S3 bucket policy overly permissive to any principal*
//RLP-99453

|*Changes—* The Policy RQL will be updated to consider *Block Public Access* settings configuration at account and bucket Level.

*Severity—* Medium. 

*Impact—* Medium. Based on the Block Public Access settings at account and bucket Level, some alerts might get resolved.


|*AWS S3 bucket publicly writable*
//RLP-99357

|*Changes—* The Policy RQL will be updated to also check for *Authenticated Users* access.

*Severity—* High. 

*Impact—* Low. New alerts may be generated if Authenticated Users have _Write_ permissions.


|*GCP Log metric filter and alert does not exist for VPC network route delete and insert*
//RLP-102099

|*Changes—* The Policy RQL will be updated to verify if _resource type_ is present in the Log metric filter.

*Severity—* Informational. 

*Current RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ( $.X.filter does not contain "resource.type =" or $.X.filter does not contain "resource.type=" ) and ( $.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=" ) and $.X.filter contains "gce_route" and ( $.X.filter contains "protoPayload.methodName:" or $.X.filter contains "protoPayload.methodName :" ) and ( $.X.filter does not contain "protoPayload.methodName!:" and $.X.filter does not contain "protoPayload.methodName !:" ) and $.X.filter contains "compute.routes.delete" and $.X.filter contains "compute.routes.insert"'; show X; count(X) less than 1
----

*Updated RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ( $.X.filter contains "resource.type =" or $.X.filter contains "resource.type=" ) and ( $.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=" ) and $.X.filter contains "gce_route" and ( $.X.filter contains "protoPayload.methodName:" or $.X.filter contains "protoPayload.methodName :" ) and ( $.X.filter does not contain "protoPayload.methodName!:" and $.X.filter does not contain "protoPayload.methodName !:" ) and $.X.filter contains "compute.routes.delete" and $.X.filter contains "compute.routes.insert"'; show X; count(X) less than 1
----

*Impact—* Low. New alerts will be generated against the policy violations.


|*GCP Log metric filter and alert does not exist for VPC network route changes*
//RLP-102098

|*Changes—* The Policy RQL will be updated to verify if _resource type_ is present in the Log metric filter.

*Severity—* Informational. 

*Current RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ($.X.filter does not contain "resource.type =" or $.X.filter does not contain "resource.type=") and ($.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=") and $.X.filter contains "gce_route" and ($.X.filter contains "jsonPayload.event_subtype=" or $.X.filter contains "jsonPayload.event_subtype =") and ($.X.filter does not contain "jsonPayload.event_subtype!=" and $.X.filter does not contain "jsonPayload.event_subtype !=") and $.X.filter contains "compute.routes.delete" and $.X.filter contains "compute.routes.insert"'; show X; count(X) less than 1
----

*Updated RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ($.X.filter contains "resource.type =" or $.X.filter contains "resource.type=") and ($.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=") and $.X.filter contains "gce_route" and ($.X.filter contains "jsonPayload.event_subtype=" or $.X.filter contains "jsonPayload.event_subtype =") and ($.X.filter does not contain "jsonPayload.event_subtype!=" and $.X.filter does not contain "jsonPayload.event_subtype !=") and $.X.filter contains "compute.routes.delete" and $.X.filter contains "compute.routes.insert"'; show X; count(X) less than 1
----

*Impact—* Low. New alerts will be generated against the policy violations.


|*GCP Log metric filter and alert does not exist for VPC network route patch and insert*
//RLP-102097

|*Changes—* The Policy RQL will be updated to verify if _resource type_ is present in the Log metric filter.

*Severity—* Informational. 

*Current RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ( $.X.filter does not contain "resource.type =" or $.X.filter does not contain "resource.type=" ) and ( $.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=" ) and $.X.filter contains "gce_route" and ( $.X.filter contains "protoPayload.methodName=" or $.X.filter contains "protoPayload.methodName =" ) and ( $.X.filter does not contain "protoPayload.methodName!=" and $.X.filter does not contain "protoPayload.methodName !=" ) and $.X.filter contains "beta.compute.routes.patch" and $.X.filter contains "beta.compute.routes.insert"'; show X; count(X) less than 1
----

*Updated RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ( $.X.filter contains "resource.type =" or $.X.filter contains "resource.type=" ) and ( $.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=" ) and $.X.filter contains "gce_route" and ( $.X.filter contains "protoPayload.methodName=" or $.X.filter contains "protoPayload.methodName =" ) and ( $.X.filter does not contain "protoPayload.methodName!=" and $.X.filter does not contain "protoPayload.methodName !=" ) and $.X.filter contains "beta.compute.routes.patch" and $.X.filter contains "beta.compute.routes.insert"'; show X; count(X) less than 1
----

*Impact—* Low. New alerts will be generated against the policy violations.


|*GCP Log metric filter and alert does not exist for VPC network changes*
//RLP-102096

|*Changes—* The Policy RQL will be updated to verify if _resource type_ is present in the Log metric filter.

*Severity—* Informational. 

*Current RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ($.X.filter does not contain "resource.type =" or $.X.filter does not contain "resource.type=") and ($.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=") and $.X.filter contains "gce_network" and ($.X.filter contains "jsonPayload.event_subtype=" or $.X.filter contains "jsonPayload.event_subtype =") and ($.X.filter does not contain "jsonPayload.event_subtype!=" and $.X.filter does not contain "jsonPayload.event_subtype !=") and $.X.filter contains "compute.networks.insert" and $.X.filter contains "compute.networks.patch" and $.X.filter contains "compute.networks.delete" and $.X.filter contains "compute.networks.removePeering" and $.X.filter contains "compute.networks.addPeering"'; show X; count(X) less than 1
----

*Updated RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ($.X.filter contains "resource.type =" or $.X.filter contains "resource.type=") and ($.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=") and $.X.filter contains "gce_network" and ($.X.filter contains "jsonPayload.event_subtype=" or $.X.filter contains "jsonPayload.event_subtype =") and ($.X.filter does not contain "jsonPayload.event_subtype!=" and $.X.filter does not contain "jsonPayload.event_subtype !=") and $.X.filter contains "compute.networks.insert" and $.X.filter contains "compute.networks.patch" and $.X.filter contains "compute.networks.delete" and $.X.filter contains "compute.networks.removePeering" and $.X.filter contains "compute.networks.addPeering"'; show X; count(X) less than 1
----

*Impact—* Low. New alerts will be generated against the policy violations.


|*GCP Log metric filter and alert does not exist for Cloud Storage IAM permission changes*
//RLP-97474

|*Changes—* The Policy RQL will be updated to verify if _resource type_ is present in the Log metric filter.

*Severity—* Informational. 

*Current RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ($.X.filter does not contain "resource.type =" or $.X.filter does not contain "resource.type=") and ($.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=") and $.X.filter contains "gcs_bucket" and ($.X.filter contains "protoPayload.methodName=" or $.X.filter contains "protoPayload.methodName =") and ($.X.filter does not contain "protoPayload.methodName!=" and $.X.filter does not contain "protoPayload.methodName !=") and $.X.filter contains "storage.setIamPermissions"'; show X; count(X) less than 1
----

*Updated RQL—*

----
config from cloud.resource where api.name = 'gcloud-logging-metric' as X; config from cloud.resource where api.name = 'gcloud-monitoring-policies-list' as Y; filter '$.Y.conditions[*].metricThresholdFilter contains $.X.name and ($.X.filter contains "resource.type =" or $.X.filter contains "resource.type=") and ($.X.filter does not contain "resource.type !=" and $.X.filter does not contain "resource.type!=") and $.X.filter contains "gcs_bucket" and ($.X.filter contains "protoPayload.methodName=" or $.X.filter contains "protoPayload.methodName =") and ($.X.filter does not contain "protoPayload.methodName!=" and $.X.filter does not contain "protoPayload.methodName !=") and $.X.filter contains "storage.setIamPermissions"'; show X; count(X) less than 1
----

*Impact—* Low. New alerts will be generated against the policy violations.


|===



[#api-ingestions]
=== API Ingestions

The following API ingestion updates are planned for Prisma Cloud in 23.6.1:

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*Amazon DAX*
//RLP-101730

|*aws-dax-parameter-group*

Additional permissions required:
 
* screen:[dax:DescribeParameterGroups] 
* screen:[dax:DescribeParameters] 

The Security Audit role includes the permissions. 

|*AWS Shield*
//RLP-101729

|*aws-shield-drt-access*

Additional permission required:
 
* screen:[shield:DescribeDRTAccess] 

The Security Audit role includes the permission. 

|*Amazon API Gateway* 
//RLP-101726

|*aws-apigatewayv2-stage* 

Additional permission required:
 
* screen:[apigateway:GET]

The Security Audit role includes the permission.  

|*Google Cloud DNS*
//RLP-101664
|*gcloud-dns-resource-record-set*

Additional permissions required:
 
* screen:[dns.managedZones.list] 
* screen:[dns.resourceRecordSets.list] 

The Viewer role includes the permissions. 

|*Google Vertex AI*
//RLP-101663
|*gcloud-vertex-ai-notebook-instance-schedule*

Additional permissions required:
 
* screen:[notebooks.locations.list] 
* screen:[notebooks.schedules.list] 

The Viewer role includes the permissions. 

|*Google Dataplex*
//RLP-101662
|*gcloud-dataplex-lake-zone-action*

Additional permissions required:
 
* screen:[dataplex.locations.list] 
* screen:[dataplex.lakes.list] 
* screen:[dataplex.zones.list] 
* screen:[dataplex.zoneActions.list] 

The Viewer role includes the permissions. 


|*Google Dataplex*
//RLP-80424
|*gcloud-dataplex-lake-action*

Additional permissions required:
 
* screen:[dataplex.locations.list] 
* screen:[dataplex.lakes.list] 
* screen:[dataplex.lakeActions.list] 

The Viewer role includes the permissions. 


|*OCI Service Mesh*
//RLP-97905

|*oci-service-mesh-ingressgateway-routetable*

Additional permissions required:
 
* screen:[MESH_INGRESS_GATEWAY_ROUTE​_TABLE_LIST] 
* screen:[MESH_INGRESS_GATEWAY_ROUTE​_TABLE_READ] 

You must update the Terraform template to enable the permissions.

|*OCI Service Mesh*
//RLP-97900

|*oci-service-mesh-ingressgateway*

Additional permissions required:
 
* screen:[MESH_INGRESS_GATEWAY​_LIST] 
* screen:[MESH_INGRESS_GATEWAY​_READ] 

You must update the Terraform template to enable the permissions.

|*OCI Database*
//RLP-96143

|*oci-database-db-node*

Additional permissions required:
 
* screen:[DB_SYSTEM_INSPECT] 
* screen:[DB_NODE_INSPECT] 
* screen:[DB_NODE_QUERY] 

You must update the Terraform template to enable the permissions.


|===

[#deprecation-notices]
=== Deprecation Notices

[cols="50%a,50%a"]
|===
2+|Deprecation Notice

|tt:[Prisma Cloud CSPM REST API for Alerts]
|Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

|===
