[#ida01a4ab4-6a2c-429d-95be-86d8ac88a7b4]
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud release.

Read this section to learn about what is planned in the 23.5.2 release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

*Note that the details and functionality listed below are a preview and the actual release date is subject to change.*

* <<changes-in-existing-behavior>>
* <<new-policies>>
* <<policy-updates>>
* <<api-ingestions>>
* <<deprecation-notices>>


[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|Placeholder for RLP-99600
//RLP-99600
|*azure-defender-for-cloud-secure-score API Ingestion*

|===


[#new-policies]
=== New Policies

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.

==== Access the Look Ahead for New Policies

To learn about the new policies that will be added in the next release:


. Find the Prisma Cloud policies folder on GitHub.
+
The folder contains RQL based Config, Network, and Audit Event policies in JSON format. https://github.com/PaloAltoNetworks/prisma-cloud-policies[View the GitHub repo].

. Select the branch for which you want to review policy updates.
+
The *Master* branch represents the current Prisma Cloud release that is generally available. You can switch to a previous release or the next release branch, to review the policies that were published previously or are planned for the upcoming release.
+
Because Prisma Cloud typically has 2 releases in a month, the release naming convention in GitHub is PCS-<year>.<month>.<release-chronology, 1 or 2>. For example, PCS-23.5.2.

. Review the updates.
+
Use the changelog.md file for a cumulative list of all policies that are added to a specific release. The policies are grouped by new policies and updated policies.
+
Use the *policies* folder to review the JSON for each policy that is added or updated as listed in the changelog. The filename for each policy matches the policy name listed in the changelog. Within each policy file, the JSON field names are described aptly to help you easily identify the characteristic it represents. The JSON field named searchModel.query provides the RQL for the policy.


[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION


2+|*Policy Updates-RQL*

|*AWS S3 bucket is not configured with MFA Delete*
//RLP-94746

|*Changes—* The policy RQL will be updated to check if you have disabled the userinput[bucketLifecycleConfiguration] rules.

*Current RQL—*

----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-s3api-get-bucket-acl' AND json.rule = '(versioningConfiguration.status equals Enabled and (versioningConfiguration.mfaDeleteEnabled does not exist or versioningConfiguration.mfaDeleteEnabled equals false))'
----

*Updated RQL—*

----
config from cloud.resource where cloud.type = 'aws' AND api.name = 'aws-s3api-get-bucket-acl' AND json.rule = versioningConfiguration.status equals Enabled and (versioningConfiguration.mfaDeleteEnabled does not exist or versioningConfiguration.mfaDeleteEnabled is false) AND (bucketLifecycleConfiguration does not exist or bucketLifecycleConfiguration.rules[*].status equals Disabled)
----

*Impact—* Medium. Existing alerts will resolve as *Policy_Updated* for AWS S3 buckets that have bucketlifecycle configuration enabled.

|===

[#api-ingestions]
=== API Ingestions

The following API ingestion updates are planned for Prisma Cloud in 23.5.2:

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|tt:[Update] *Amazon Translate* 
//RLP-100604
|*aws-translate-terminology*

This API will be updated to remove the userinput:[CreatedAt] field in the resource JSON.

|*AWS Serverless Application Repository* 
//RLP-99954
|*aws-serverlessrepo-application* 

Additional permissions required:
 
* screen:[serverlessrepo:GetApplicationPolicy] 
* screen:[serverlessrepo:ListApplications]

The Security Audit role includes the permissions. 


|*AWS Transfer Family* 
//RLP-99911
|*aws-transfer-family-user* 

Additional permissions required:
 
* screen:[transfer:ListUsers] 
* screen:[transfer:DescribeUser] 
* screen:[SecurityAudit Policy] 

The Security Audit role includes the permissions. 

|*Amazon API Gateway* 
//RLP-99869
|*aws-apigatewayv2-api* 

Additional permission required:
 
* screen:[apigateway:GET] 

The Security Audit role includes the permission. 

|*Google Traffic Director Network Service* 
//RLP-96711
|*gcloud-traffic-director-network-service-tls-route* 

Additional permission required:
 
* screen:[networkservices.tlsRoutes.list] 

The Viewer role includes the permission. 

[NOTE]
====
This API will list only Global Resources.
====

|*Google Traffic Director Network Service* 
//RLP-96710
|*gcloud-traffic-director-network-service-tcp-route* 

Additional permission required:
 
* screen:[networkservices.tcpRoutes.list] 

The Viewer role includes the permission. 

[NOTE]
====
This API will list only Global Resources.
====


|*Google Traffic Director Network Service* 
//RLP-96694
|*gcloud-traffic-director-network-service-grpc-route* 

Additional permission required:
 
* screen:[networkservices.grpcRoutes.list] 

The Viewer role includes the permission. 

[NOTE]
====
This API will list only Global Resources.
====


|*Google Traffic Director Network Service* 
//RLP-96687
|*gcloud-traffic-director-network-service-http-route* 

Additional permission required:
 
* screen:[networkservices.httpRoutes.list] 

The Viewer role includes the permission. 

[NOTE]
====
This API will list only Global Resources.
====


|*OCI Database* 
//RLP-96143
|*oci-database-db-node* 

Additional permissions required:
 
* screen:[DB_SYSTEM_INSPECT] 
* screen:[DB_NODE_INSPECT] 
* screen:[DB_NODE_QUERY]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI Service Mesh* 
//RLP-97905
|*oci-service-mesh-ingressgateway-routetable* 

Additional permissions required:
 
* screen:[MESH_INGRESS_GATEWAY_ROUTE?_TABLE_LIST] 
* screen:[MESH_INGRESS_GATEWAY_ROUTE?_TABLE_READ]

You must download and execute the Terraform template from the console to enable the permissions.

|*OCI Service Mesh* 
//RLP-97900
|*oci-service-mesh-ingressgateway* 

Additional permissions required:
 
* screen:[MESH_INGRESS_GATEWAY?_LIST] 
* screen:[MESH_INGRESS_GATEWAY?_READ]

You must download and execute the Terraform template from the console to enable the permissions.


|===

[#deprecation-notices]
=== Deprecation Notices

[cols="50%a,50%a"]
|===
2+|Deprecation Notice

|tt:[Prisma Cloud CSPM REST API for Alerts]
|Some Alert API request parameters and response object properties are now deprecated.

Query parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[GET /v2/alert] 
*  userinput:[GET /alert/policy] 

Request body parameter varname:[risk.grade] is deprecated for the following requests:

*  userinput:[POST /alert] 
*  userinput:[POST /v2/alert] 
*  userinput:[POST /alert/policy] 

Response object property varname:[riskDetail] is deprecated for the following requests:

*  userinput:[GET /alert] 
*  userinput:[POST /alert] 
*  userinput:[GET /alert/policy] 
*  userinput:[POST /alert/policy] 
*  userinput:[GET /alert/{id}] 
*  userinput:[GET /v2/alert] 
*  userinput:[POST /v2/alert] 

Response object property varname:[risk.grade.options] is deprecated for the following request:

* userinput:[GET /filter/alert/suggest]

|===
