[[id50a63347-4291-4210-99fa-f51de04106be]]Make sure you have created a stack in your AWS account.

. From your AWS account, copy and paste *Role ARN* and click *Next*.

. *Configure Data Security* to scan all your resources or you can choose to customize what you want to scan.
+
* When you select Scan All, Prisma Cloud will Forward scan and Backward scan all eligible objects. The forward scan inspects any new or modified files, and the backward scan is retrospective, which means that it inspects files that exist in the storage bucket. The xref:../prisma-cloud-data-security/monitor-data-security-scan-prisma-cloud/supported-file-extensions.adoc[type] of files that you want to scan within your storage bucket will determine how many Prisma Cloud credits are used for Data Security.

* When you select Custom Scan, Prisma Cloud will Forward scan and/or Backward scan eligible objects in selected resources.

. You can choose to *Add New* or *Select existing* CloudTrail, SNS Topic, or Buckets for Log Files. The consumption of Prisma Cloud license credits depends on the file size in the selected objects and whether you enable forward and backward scans.
+
[NOTE]
====
CloudTrail buckets are not scanned. You can choose buckets with objects containing ELB access logs, S3 access logs, and VPC flow logs for scanning.
====

. Follow the steps to *Configure Forward Scan*:
+
* *Download Template* locally. The template is a .zip file that contains shell script, CFTs, and configuration files.

* Login to your Amazon CloudShell account, upload the .zip file you downloaded in the above step, and run the following command that will create a Bucket, SNS Topic, and CloudTrail:
+
----
sh pcds_forward_scan_setup.sh -f config.txt 
----

* Wait for the CREATE_COMPLETE status.

* Once the above command runs successfully in AWS, click *Validate Setup* on Prisma Cloud.

. Irrespective of whether the script gets validated or not you can continue to onboard and configure data security for your AWS account. If validation fails, see xref:../prisma-cloud-data-security/troubleshoot-data-security-errors.adoc[troubleshoot data security errors] and set up AWS CloudTrail & SNS manually to resolve it.

. Click *Next*.
