:topic_type: task

[.task]
== CyberArk Enterprise Password Vault 

You can integrate Prisma Cloud with CyberArk Enterprise Password Vault (EPV). 
To retrieve passwords from the vault, Prisma Cloud uses the CyberArk Central Credential Provider (CCP) web service.
Prisma Cloud supports CyberArk CCP version 12.1.0 with Digital Vault version 12.2.0.
To integrate with CyberArk EPV, first configure Prisma Cloud to access CyberArk Enterprise Password Vault, then create rules to inject the relevant secrets into the relevant containers.

[.procedure]
. In Console, go to *Manage > Authentication > Secrets*.

. Click *Add store*.

.. Enter a name for the vault.
This name is used when you create rules to inject secrets into specific containers.

.. For *Secret type*, select *CyberArk Enterprise Password Vault*.

.. In *Settings*, fill out the form as follows:
... Address: the address and port of the Central Credential Provider web service.
... Application ID: The application ID that Prisma Cloud should use to issue each password request. To configure this for CCP 12.1, see https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-CP/12.1/en/Content/Common/Adding-Applications.htm?tocpath=Administration%7CManage%20applications[here].
... CA certificate (Optional): for an application configured to authenticate using a client certificate, the certificate of the CA that signed the CyberArk server's certificate in PEM format. For more information about this authentication method for CCP 12.1 see https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-CP/12.1/en/Content/CP%20and%20ASCP/Application-Authentication-Methods-general.htm?tocpath=Administration%7CManage%20applications%7CApplication%20authentication%7CApplication%20authentication%20methods[here].
... Client certificate (Optional): for an application configured to authenticate using a client certificate, the client certificate in PEM format.

.. Click *Add*.
+
After clicking *Add*, Prisma Cloud tries conecting to your vault.
If it is successful, the dialog closes, and an entry is added to the table.
Otherwise, any connection errors are displayed directly in the configuration dialog.
+
Next, xref:../../secrets/inject_secrets.adoc#[inject a secret into a container].
