== GitHub repository defined in Terraform is not Private


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| f620ff53-e5d6-45a1-b68b-83bc35f7e946

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/github/PrivateRepo.py[CKV_GIT_1]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


When you create a  Cloud repository, you specify whether it's private or public, but you can also change this setting at any time.
If your repository is public, anyone can access and fork it.
If your repository is private, you can specify who exactly can access your repository and whether they can fork it.

=== Fix - Buildtime


*GitHub *Warning: This may break references to the repository** 

* On GitHub.com, navigate to the repository.
* In the menu bar under the repository name click on Settings
* In the "Danger Zone" section, click on "Change repository visibility"
* Choose private

*Terraform*


[source,go]
----
resource "github_repository" "example" {
  name        = "example"
  description = "My awesome codebase"

+ visibility = "private"

  template {
    owner                = "github"
    repository           = "terraform-template-module"
    include_all_branches = true
  }
}
----