== Alibaba Cloud RAM password policy does not have a symbol


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e53d9690-7b9b-4934-b6e7-c30599f60792

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RAMPasswordPolicySymbol.py[CKV_ALI_15]

|Severity
|MEDIUM

|Subtype
|Build
// , Run

|Frameworks
|Terraform

|=== 



=== Description 



Including a symbol in a password is important as it adds complexity and makes it harder for attackers to guess or crack the password using automated tools. Using only uppercase or lowercase characters, or a number in a password, makes it easier for attackers to perform a brute-force attack, where they try all possible combinations until they find the correct one. By including symbols, the number of possible combinations increases, making it more challenging for attackers to guess or crack the password. To mitigate this risk and prevent unauthorized access to an account, enforce a policy requiring passwords to include a symbol for Alibaba Cloud RAM accounts (account). This policy identifies accounts that do not include a symbol in their password policy.

////
=== Fix - Runtime


Alibaba Cloud Portal



. Log in to Alibaba Cloud Portal

. Go to Resource Access Management (RAM) service

. In the left-side navigation pane, click on 'Settings'

. In the 'Security Settings' tab, In the 'Password Strength Settings' Section, Click on 'Edit Password Rule'

. In the 'Required Elements in Password' field, select 'Symbols'

. Click on 'OK'

. Click on 'Close'
////

=== Fix - Buildtime


*Terraform* 
To identify accounts with passwords that do not include a symbol, add the following code to your Terraform file during buildtime.



[source,go]
----
resource "alicloud_ram_account_password_policy" "pass" {
  minimum_password_length      = 14
  require_lowercase_characters = false
  require_uppercase_characters = false
  require_numbers              = false
  require_symbols              = true
  hard_expiry                  = true
  max_password_age             = 14
  password_reuse_prevention    = 5
  max_login_attempts           = 3
}
----

