== Aporeto enforcer

//'''
//
//title: Aporeto enforcer
//type: single
//url: "/3.14/reference/components/enforcer/"
//weight: 20
//menu:
//  3.14:
//    parent: "components"
//    identifier: "enforcer-config"
//
//'''

=== Configuring the enforcer

To modify the default configuration of an enforcer, you can define an enforcer profile and map it to the designated enforcers.
The tags of each Aporeto enforcer must match only one profile.
Otherwise, the enforcer will refuse to start.

=== Default enforcer profile

Your account comes with a default enforcer profile and enforcer profile mapping policy.
It matches all enforcer instances unless a more specific one is available.

In the majority of the cases, you should not need to create your own unless you need to use advanced features like:

* Secure selected system daemons
* Protect a host (see xref:../../secure/secure-hosts/secure-hosts.adoc[Protect hosts])
* Enable advanced audit rules
* Ignore some processing units
* Change very advanced networking configuration
