== Linux hosts

//---
//title: Linux hosts
//type: single
//url: "/3.14/start/enforcer/linux/"
//weight: 30
//menu:
//  3.14:
//    parent: "enforcer"
//    identifier: "linux"
//canonical: https://docs.aporeto.com/saas/start/enforcer/linux/
//
//---

=== About Linux host installs

To deploy Aporeto to a Linux host not orchestrated by Kubernetes or OpenShift, use one of the following procedures.

* <<_quick-install,Quick install>>: the fastest way to install an enforcer on any Linux host.
+
Appropriate for those just getting started with Aporeto.
You can also use it for on-premise hosts in production.
  
* <<_production-cloud-install,Production cloud install>>: recommended for production instances hosted on AWS, GCP, or Azure.
+
The enforcer uses short-lived tokens from the cloud provider to authenticate to the Aporeto control plane.

* <<_advanced-on-premise-install,Advanced on-premise install>>: more secure than the quick install. 
+
The enforcer exchanges a restricted token for an app credential.
It uses least privilege credentials to access the control plane, which won't allow it to re-register itself if it goes down for more than twenty-four hours.

[#_quick-install]
=== Quick install

==== Prerequisites

[cols="1,3a"]
|===
|Entity |Requirement

|Target host(s)
|
* xref:reqs.adoc[Meet the system requirements]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[Set up to synchronize time with authoritative sources]
* https://curl.haxx.se/[curl] installed

|Local host
|
* xref:../apoctl/apoctl.adoc[`apoctl` installed]
* SSH access to target host(s)

|Privileges
|
* `namespace.editor` privileges in Aporeto
* User account(s) on target host(s) can `sudo` to gain root privileges without entering a password
|===

==== 1. Install the enforcer

You can deploy the enforcer to one or more remote hosts using a single command.
We recommend deploying the enforcer as a service for maximum functionality and security.
If the target host uses a read-only file system like CoreOS or you need to integrate with an alternative orchestrator, deploy the enforcer as a container instead.

*Syntax*:

Service:

----
apoctl protect linux-remote \
  <USER-NAME>@<IP-OR-FQDN> [ <USER-NAME>@<IP-OR-FQDN> ] \
  --key <PRIVATE-KEY> [ --key <PRIVATE-KEY> ]
----

Container:

----
apoctl protect linux-remote --docker \
  <USER-NAME>@<IP-OR-FQDN> [ <USER-NAME>@<IP-OR-FQDN> ] \
  --key <PRIVATE-KEY> [ --key <PRIVATE-KEY> ]
----

*Example*:

Service:

----
apoctl protect linux-remote \
  ubuntu@ec2-54-244-176-140.us-west-2.compute.amazonaws.com \
  --key private-key.pem
----

Container:

----
apoctl protect linux-remote --docker \
  ubuntu@ec2-54-244-176-140.us-west-2.compute.amazonaws.com \
  --key private-key.pem
----

For more information about the `protect` command, refer to the xref:../../reference/cli.adoc[`apoctl` reference page]

==== 2. Verify the install

include::snippet-enforcer-complete.adoc[]

[#_production-cloud-install]
=== Production cloud install

==== Prerequisites

[cols="1,3a"]
|===
|Entity |Requirement

|Target host(s)
|
* xref:reqs.adoc[Meets the system requirements]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[Set up to synchronize time with authoritative sources]
* https://curl.haxx.se/[curl] installed

|Local host
|
* xref:../apoctl/apoctl.adoc[`apoctl` installed]
* SSH access to target host(s)

|Privileges
|
* `namespace.editor` privileges in Aporeto
* User account(s) on target host(s) can `sudo` to gain root privileges without entering a password

|Cloud credentials
|
* _AWS_: https://aws.amazon.com/blogs/security/easily-replace-or-attach-an-iam-role-to-an-existing-ec2-instance-by-using-the-ec2-console/[an IAM role attached to the target host] with read-only access to tags (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policy-structure.html[`ec2:DescribeTags`])
* _GCP_: https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[GCP service account attached to the target host]
* _Azure_: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vmss[target host assigned a managed identity]
|===

==== 1. Set environment variables on your local host

Construct an xref:../../concepts/key-concepts.adoc#_tags-and-identity[Aporeto tag] that includes metadata from the cloud instance to identify enforcers authorized to register with Aporeto.
The tag must begin with `@auth:` followed by a key-value pair.
Refer to the table below for some common examples.

|===
|Cloud provider |Value |Aporeto tag syntax |Aporeto tag example

|AWS            | AWS account ID^1^                    | `@auth:account=<AWS_ACCOUNT_ID>`    | `@auth:account=942613894219`

|GCP            | GCP project ID                     | `@auth:projectid=<GCP_PROJECT_ID>`  | `@auth:projectid=acme-dev`

|Azure          | Microsoft tenant ID^2^ | `@auth:tenantid=<TENANT_ID>`        | `@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7`

|GCP and Azure  | Name of organization               | `@auth:organization=<ORGANIZATION>` | `@auth:organization=acme`

^1^You can find your AWS account ID under **My security credentials** in the AWS Management Console.

^2^To learn how to find your tenant ID, refer to the [Microsoft documentation](https://techcommunity.microsoft.com/t5/Office-365/How-do-you-find-the-tenant-ID/td-p/89018).
|===

On your `apoctl` host, set two environment variables.

* `CLOUD_ID_TAG` containing the Aporeto tag you've constructed to identify authorized enforcers.
* `AWS_IAM_ROLE` (AWS only) containing the name of the IAM role attached to the instance prepended with `@auth:rolename=`.

For example commands, select the tab that corresponds to the cloud provider of the target host.

AWS:

----
export CLOUD_ID_TAG="@auth:account=942613894219"
export AWS_IAM_ROLE="@auth:rolename=aporeto"
----

GCP:

----
export CLOUD_ID_TAG="@auth:projectid=acme-dev"
----

Azure:

----
export CLOUD_ID_TAG="@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7"
----

==== 2. Create an API authorization

Create an API authorization that allows the Aporeto enforcer to access the Aporeto control plane.
For the command, select the tab that corresponds to the cloud provider of the target host.

AWS:

----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: ec2-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $APOCTL_NAMESPACE
     authorizedSubnets: []
     name: Authorize EC2 enforcer to access Aporeto control plane
     propagate: true
     subject:
       - - "@auth:realm=awssecuritytoken"
         - "$AWS_IAM_ROLE"
         - "$CLOUD_ID_TAG"
EOF
----

GCP:

----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: gcp-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $APOCTL_NAMESPACE
     authorizedSubnets: []
     name: Authorize GCP enforcer to access Aporeto control plane
     propagate: true
     subject:
       - - "@auth:realm=gcpidentitytoken"
         - "$CLOUD_ID_TAG"
EOF
----

Azure:

----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: azure-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $APOCTL_NAMESPACE
     authorizedSubnets: []
     name: Authorize Azure enforcer to access Aporeto control plane
     propagate: true
     subject:
       - - "@auth:realm=azureidentitytoken"
         - "$CLOUD_ID_TAG"
EOF
----

==== 3. Create a namespace mapping (optional)

Once an enforcer registers, you cannot change its namespace.
If you don't want the enforcers to register in your current namespace, complete this step to map them into a child instead.
Set the following environment variables.

* `CHILD_NAMESPACE`: the name of the target child namespace. 
It may or may not exist.
* `ENFORCER_ID_TAG`: an Aporeto tag that uniquely identifies the enforcer(s) to be mapped. 
Note that all enforcers with the designated tag will be mapped.

For example commands, select the tab that corresponds to the cloud provider of the target host and the operating system of your local host.

AWS:

----
export CHILD_NAMESPACE=ec2
export ENFORCER_ID_TAG="@cloud:aws:type=ec2"
----

GCP:

----
export CHILD_NAMESPACE=central-usa
export ENFORCER_ID_TAG="@cloud:gcp:zone=us-central1-a"
----

Azure:

----
export CHILD_NAMESPACE=central-usa
export ENFORCER_ID_TAG="@cloud:azure:location=centralus"
----

If it does not already exist, create the child namespace.

  apoctl api create ns -k name $CHILD_NAMESPACE

Create the namespace mapping.
For the command, select the tab that corresponds to the cloud provider of the target host.

AWS:

----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: ec2-namespace-map
data:
 namespacemappingpolicies:
   - mappedNamespace: $APOCTL_NAMESPACE/$CHILD_NAMESPACE
     metadata: []
     name: Map $ENFORCER_ID_TAG instance to $APOCTL_NAMESPACE/$CHILD_NAMESPACE namespace
     subject:
       - - "\$identity=enforcer"
         - "$ENFORCER_ID_TAG"
EOF
----

GCP:

----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: gcp-namespace-map
data:
 namespacemappingpolicies:
   - mappedNamespace: $APOCTL_NAMESPACE/$CHILD_NAMESPACE
     metadata: []
     name: Map $ENFORCER_ID_TAG instance to $APOCTL_NAMESPACE/$CHILD_NAMESPACE namespace
     subject:
       - - "\$identity=enforcer"
         - "$ENFORCER_ID_TAG"
EOF
----

Azure:

----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: azure-namespace-map
data:
 namespacemappingpolicies:
   - mappedNamespace: $APOCTL_NAMESPACE/$CHILD_NAMESPACE
     metadata: []
     name: Map $ENFORCER_ID_TAG instance to $APOCTL_NAMESPACE/$CHILD_NAMESPACE namespace
     subject:
       - - "\$identity=enforcer"
         - "$ENFORCER_ID_TAG"
EOF
----

==== 4. Install the enforcer

You can deploy the enforcer to one or more remote hosts using a single command.
We recommend deploying the enforcer as a service for maximum functionality and security.
If the target host uses a read-only file system like CoreOS or you need to integrate with an alternative orchestrator, deploy the enforcer as a container instead.

*Syntax*:

Service:

----
apoctl protect linux-remote --cloud-auth \
  <USER-NAME>@<IP-OR-FQDN> [ <USER-NAME>@<IP-OR-FQDN> ] \
  --key <PRIVATE-KEY> [ --key <PRIVATE-KEY> ]
----

Container:

----
apoctl protect linux-remote --docker --cloud-auth \
  <USER-NAME>@<IP-OR-FQDN> [ <USER-NAME>@<IP-OR-FQDN> ] \
  --key <PRIVATE-KEY> [ --key <PRIVATE-KEY> ]
----

*Example*:

Service:

----
apoctl protect linux-remote --cloud-auth \
  ubuntu@ec2-54-244-176-140.us-west-2.compute.amazonaws.com \
  --key private-key.pem
----

Container:

----
apoctl protect linux-remote --docker --cloud-auth \
  ubuntu@ec2-54-244-176-140.us-west-2.compute.amazonaws.com \
  --key private-key.pem
----

For more information about the `protect` command, refer to the xref:../../reference/cli.adoc[`apoctl` reference page].

==== 5. Verify the install

include::snippet-enforcer-complete.adoc[]

[#_advanced-on-premise-install]
=== Advanced on-premise install

==== Prerequisites

[cols="1,3a"]
|===
|Entity |Requirement

|Target host(s)
|
* xref:reqs.adoc[Meet the system requirements]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[Set up to synchronize time with authoritative sources]

|Local host
|
* xref:../apoctl/apoctl.adoc[`apoctl` installed]

|Privileges
|
* `namespace.editor` privileges in Aporeto
* Root privileges on target host(s)
|===

==== 1. Create an app credential

From the `apoctl` host, create an app credential with the `enforcer` role.

  apoctl appcred create enforcerd --role @auth:role=enforcer > enforcerd.creds

==== 2. Generate a token from the app credential

Use the app credential to generate an enforcer registration token with the desired restrictions.
At a minimum, we recommend restricting the length of its validity and role.
You can also require the enforcer to register in a specified namespace or make its request from a specific subnet.

Syntax:

----
apoctl auth appcred --path enforcerd.creds \
  --restrict-role @auth:role=enforcer \
  --validity <golang-duration> \
  [--restrict-namespace <namespace>] \
  [--restrict-network <cidr>]
----

Fully restricted example:

----
apoctl auth appcred --path enforcerd.creds \
  --restrict-namespace /acme/team-a/dev \
  --restrict-role @auth:role=enforcer \
  --restrict-network 10.0.0.0/8 \
  --validity 10m
----

Minimally restricted example:

----
apoctl auth appcred --path enforcerd.creds \
  --restrict-role @auth:role=enforcer --validity 10m
----

This should return a base64-encoded token.
Copy the value.

==== 3. Store the enforcer token on the target host

Access the target host, such as via SSH.
Set an environment variable called `TOKEN` containing the value copied in the previous step.

  export TOKEN=<paste-token-value>

==== 4. Install the enforcer

===== About installing the enforcer

You can install the enforcer as either of the following.

* <<_sysd-advanced,Service>>: recommended for maximum functionality and security on all distributions except those with read-only file systems such as CoreOS.

* <<_container-advanced,Privileged container>>: recommended for distributions with read-only file systems such as CoreOS and integration with alternative orchestrators.

[#_sysd-advanced]
===== Installing the enforcer as a service

Use the command that corresponds to the operating system of the target host to download and install the enforcer.

Ubuntu:

[,console,subs="+attributes"]
----
curl -sSL https://download.aporeto.com/aporeto-packages.gpg | sudo apt-key add -
echo "deb [arch=$(dpkg --print-architecture)] \
{repo-url}{version}/ubuntu/$(lsb_release -cs) aporeto main" \
| sudo tee /etc/apt/sources.list.d/aporeto.list
sudo apt update
sudo apt install -y enforcerd
----

Debian:

[,console,subs="+attributes"]
----
sudo apt install -y apt-transport-https
curl -sSL https://download.aporeto.com/aporeto-packages.gpg | sudo apt-key add -
echo "deb [arch=$(dpkg --print-architecture)] \
{repo-url}{version}/debian/$(lsb_release -cs) aporeto main" \
| sudo tee /etc/apt/sources.list.d/aporeto.list
sudo apt update
sudo apt install -y enforcerd
----

Centos: 

[,console,subs="+attributes"]
----
cat << EOF | sudo tee /etc/yum.repos.d/Aporeto.repo
[Aporeto]
name=aporeto
baseurl={repo-url}{version}/centos/\$releasever/
gpgkey=https://download.aporeto.com/aporeto-packages.gpg
gpgcheck=1
repo_gpgcheck=1
enabled=1
EOF
sudo yum install -y enforcerd
----

Red Hat:

[,console,subs="+attributes"]
----
cat << EOF | sudo tee /etc/yum.repos.d/Aporeto.repo
[Aporeto]
name=aporeto
baseurl={repo-url}{version}/redhat/\$releasever/
gpgkey=https://download.aporeto.com/aporeto-packages.gpg
gpgcheck=1
repo_gpgcheck=1
enabled=1
EOF
sudo yum install -y enforcerd
----

Amazon Linux 2:

[,console,subs="+attributes"]
----
cat << EOF | sudo tee /etc/yum.repos.d/Aporeto.repo
[Aporeto]
name=aporeto
baseurl={repo-url}{version}/nodist/yum/
gpgkey=https://download.aporeto.com/aporeto-packages.gpg
gpgcheck=1
repo_gpgcheck=1
enabled=1
EOF
sudo yum install -y enforcerd
----

Amazon Linux AMI:

[,console,subs="+attributes"]
----
cat << EOF | sudo tee /etc/yum.repos.d/Aporeto.repo
[Aporeto]
name=aporeto
baseurl={repo-url}{version}/nodist/yum/
gpgkey=https://download.aporeto.com/aporeto-packages.gpg
gpgcheck=1
repo_gpgcheck=1
enabled=1
EOF
sudo yum install -y enforcerd-initd
----

You can configure the enforcer to store its app credential only in memory and not on disk. While more secure, this option requires someone to manually reprovision enforcer with a token following a reboot of the host.
You can also configure the enforcer to store its app credential on disk, ensuring that it can reconnect to the Aporeto control plane after a reboot without manual intervention.

Issue the command that corresponds to your desired configuration and the init system of the target host.

* Store app credential on disk
+
systemd:
+
----
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_COMPRESSED_TAGS=1" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_PERSIST_CREDENTIALS=true" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_API=https://{ctrl-plane-api-url}" | sudo tee -a /etc/enforcerd.conf
sudo systemctl enable --now enforcerd
sudo systemctl status enforcerd
----
+
upstart:
+
----
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_COMPRESSED_TAGS=1" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_PERSIST_CREDENTIALS=true" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_API=https://{ctrl-plane-api-url}" | sudo tee -a /etc/enforcerd.conf
sudo start enforcerd
sudo status enforcerd
----
+
initd:
+
----
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_COMPRESSED_TAGS=1" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_PERSIST_CREDENTIALS=true" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_API=https://{ctrl-plane-api-url}" | sudo tee -a /etc/enforcerd.conf
sudo /etc/init.d/enforcerd start
sudo /etc/init.d/enforcerd status
----

* Store app credential only in memory
+
systemd:
+
----
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_COMPRESSED_TAGS=1" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_API=https://{ctrl-plane-api-url}" | sudo tee -a /etc/enforcerd.conf
sudo systemctl enable --now enforcerd
sudo systemctl status enforcerd
----
+
upstart:
+
----
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_COMPRESSED_TAGS=1" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_API=https://{ctrl-plane-api-url}" | sudo tee -a /etc/enforcerd.conf
sudo start enforcerd
sudo status enforcerd
----
+
initd:
+
----
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_COMPRESSED_TAGS=1" | sudo tee -a /etc/enforcerd.conf
echo "ENFORCERD_API=https://{ctrl-plane-api-url}" | sudo tee -a /etc/enforcerd.conf
sudo /etc/init.d/enforcerd start
sudo /etc/init.d/enforcerd status
----

[TIP]
====
* If you would like to control and monitor IPv6 connections, add `ENFORCERD_ENABLE_IPV6=1` to `/etc/enforcerd.conf`.
* For versions of `systemctl` prior to 220, you may need to start and enable the service in two commands.
* Use the `initd` command for Amazon Linux AMI.
====

include::snippet-enforcer-complete.adoc[]

[#_container-advanced]
===== Installing the enforcer as a container

You can configure the enforcer to store its app credential only in memory and not on disk.
While more secure, this option requires someone to manually reprovision enforcer with a token following a reboot of the host.

You can also configure the enforcer to store its app credential on disk, ensuring that it can reconnect to the Aporeto control plane after a reboot without manual intervention.

Issue the command that corresponds to your desired configuration.

Store app credential on disk:

[,console,subs="+attributes"]
----
    sudo mkdir -p /var/lib/aporeto
    sudo modprobe nf_conntrack; \
      sudo modprobe nf_conntrack_ipv4; \
      sudo modprobe nf_conntrack_ipv6; \
      sudo modprobe ip6table_nat; \
      sudo modprobe ip6_tables; \
      sudo modprobe ip6table_mangle;
    sudo docker run \
      -d \
      --name=enforcerd \
      --privileged=true \
      --net=host \
      --pid=host \
      --restart=always \
      -v /lib/modules:/lib/modules \
      -v /var/run:/var/run:rw \
      -v /sys:/sys \
      -v /var/lib/aporeto:/var/lib/aporeto \
      -v /usr/share/aporeto:/usr/share/aporeto \
      -e ENFORCERD_TOKEN=$TOKEN \
      -e ENFORCERD_COMPRESSED_TAGS=1 \
      -e ENFORCERD_PERSIST_CREDENTIALS=true \
      -e ENFORCERD_API=https://{ctrl-plane-api-url} \
      {gcr-docker-next}/enforcerd:{version-container}
    sudo docker ps --filter 'name = enforcerd'
----

Store app credential only in memory:

[,console,subs="+attributes"]
----
    sudo mkdir -p /var/lib/aporeto
    sudo modprobe nf_conntrack; \
      sudo modprobe nf_conntrack_ipv4; \
      sudo modprobe nf_conntrack_ipv6; \
      sudo modprobe ip6table_nat; \
      sudo modprobe ip6_tables; \
      sudo modprobe ip6table_mangle;
    sudo docker run \
      -d \
      --name=enforcerd \
      --privileged=true \
      --net=host \
      --pid=host \
      --restart=always \
      -v /lib/modules:/lib/modules \
      -v /var/run:/var/run:rw \
      -v /sys:/sys \
      -v /var/lib/aporeto:/var/lib/aporeto \
      -v /usr/share/aporeto:/usr/share/aporeto \
      -e ENFORCERD_TOKEN=$TOKEN \
      -e ENFORCERD_COMPRESSED_TAGS=1 \
      -e ENFORCERD_API=https://{ctrl-plane-api-url} \
      {gcr-docker-next}/enforcerd:{version-container}
    sudo docker ps --filter 'name = enforcerd'
----

TIP: If you would like to control and monitor IPv6 connections, add `-e ENFORCERD_ENABLE_IPV6=1`

include::snippet-enforcer-complete.adoc[]
