[#id1a00f264-c963-45c9-b227-89f89ebd4418]
== Prisma Cloud Microsegmentation Release Information

Review this section to learn about all the exciting new features in the Prisma Cloud Identity-Based Segmentation module and any known issues.

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin[Prisma™ Cloud] is an API-based integration that provides security at all stages of the software delivery process. It provides visibility in to your resources deployed across different environments, and checks your adherence to compliance standards and security best practices for your assets at runtime, and IaC templates and images even before the resources are deployed.

Identity-Based Microsegmentation is a module on Prisma Cloud that helps you see how applications communicate, enforce identity-based defenses on hosts and containers, and stop lateral movement of threats. It reduces risk for cloud native applications, for Security teams who can reduce risk without changing the network, and for devOps and cloud infrastructure teams who can embrace the cloud without worrying about security slowing down rapid release cycles.

To view the current operational status of Palo Alto Networks cloud services, see https://status.paloaltonetworks.com/[https://status.paloaltonetworks.com/].

To stay informed on identity-based microsegmentation on Prisma Cloud, make sure you review the following information:
