== GitHub merge requests should require at least 2 approvals


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 362c7490-7e2d-453b-b1f0-288c1eb059c2

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/github/checks/disallow_force_pushes.py[CKV_GITHUB_5]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|VCS

|=== 



=== Description 


In GitHub, repository administrators can require that all pull requests receive a specific number of approving reviews before someone merges the pull request into a protected branch.
It is also possible to require approving reviews from people with write permissions in the repository or from a designated code owner.
If a collaborator attempts to merge a pull request with pending or rejected reviews into the protected branch, the collaborator will receive an error message.

=== Fix - Buildtime


*Terraform* 


* *Resource:* github_branch_protection, github_branch_protection_v3
* *Attribute:* required_approving_review_count

[source,hcl]
----
resource "github_branch_protection_v3" "example" {

...
required_pull_request_reviews {

...
}
}
----

