[#id96b40db7-7792-42fc-b13e-18f2b8a46c7b]
== Prisma™ Cloud Release Information

Review the Prisma Cloud release notes to learn about all the exciting new features and known issues.

https://docs.prismacloud.io[Prisma™ Cloud] is an API-based integration that provides security at all stages of the software delivery process. It provides visibility in to your resources deployed across different environments, and checks your adherence to compliance standards and security best practices for your assets at runtime, and the IaC templates, and images even before the resources are deployed.

Prisma Cloud monitors your resources deployed on the Public cloud environments—AWS, Microsoft Azure, Google Cloud Platform, Oracle Cloud Infrastructure, and Alibaba Cloud—for cloud security and compliance risks. As the service automatically discovers new resources that are deployed in your cloud environment, it enables you to implement policy guardrails to ensure resource configurations adhere to industry standards and integrate configuration change alerts into DevOps and SecOps workflows to automatically resolve issues. This capability streamlines the process of identifying issues, detecting and responding to a list of prioritized risks to maintain an agile development process and operational efficiency.

Prisma Cloud Code Security module identifies vulnerabilities, misconfigurations and compliance violations inInfrastructure as Code ( IaC) templates, container images and git repositories.

On Prisma Cloud Enterprise Edition, the Compute tab comprises the Cloud Workload Protection (CWP) capabilities that help you secure your host, containers, and serverless deployments across public cloud, private cloud and on-premises environments, throughout the application lifecycle. It combines runtime protection with vulnerability management
and compliance to secure cloud native workloads across build, deploy and run stages of the lifecycle.

The current Compute version is 31.01.123. It will be upgraded to 31.02.133 on October 8, 2023.


To view the current operational status of Palo Alto Networks cloud services, see https://status.paloaltonetworks.com/[https://status.paloaltonetworks.com/].

Before you begin using Prisma Cloud, make sure you review the following information:

* xref:../prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-2023.adoc[Features Introduced in 2023]
* xref:../prisma-cloud-release-info/classic-releases/classic-releases.adoc[Classic Releases]
* xref:../limited-ga-features-prisma-cloud/lga-features.adoc[LGA Features]
* xref:../look-ahead-planned-updates-prisma-cloud/look-ahead-updates.adoc[Look Ahead—Planned Updates on Prisma Cloud]
* xref:../known-issues/known-fixed-issues.adoc[Known Issues on Prisma Cloud]

