== Licensing

You must procure a license for each resource that Prisma Cloud protects and renew the license before the expiry term.
// Licenses are valid for one year, after which they can be renewed.

Licensing on Prisma Cloud uses a metering system based on credits used, and both Prisma Cloud Enterprise Edition (SaaS) and Prisma Cloud Compute Edition (self-hosted) are licensed with the same credits metering system.

Prisma Cloud Compute protects your hosts, containers, and serverless functions using a security agent called Defender, and using an agentless method.
The number of credits you consume directly correlates with the type and mix of Defenders you deploy and the agentless security option.

Prisma Cloud also offers twistcli, a command-line configuration tool for which there is no additional credit usage. The credit usage is for the resources that are being protected using an agent or an agentless method.


[cols="2,1,1a", options="header"]
|===

|Resource
|Credits per resource
|What's counted?

|Hosts that don’t run containers
|1 credit
|Host Defender

|Hosts that are being scanned by Agentless scanning
|1 credit
|Host Agentless scan

|Hosts that run containers
|7 credits
|Container Defender

|Hosts that run applications
|7 credits
|Tanzu Application Service Defender

|On-demand containers (such as AWS Fargate, Google Cloud Run)
|1 credits
|App-Embedded Defender

|Serverless functions (such as AWS Lambda, Azure Functions, Google Cloud Functions)
|1 credits per 6 defended functions
|Defended functions:

* Functions (only latest version) with a Serverless Defender - including Runtime & WAAS
* Functions scanned for vulnerabilities and compliance (only latest version)

|Web Application and API Security (WAAS)
|30 credits per Defender agent associated with protected web-application nodes (container/pod/host/AppID)  
|
* Host Defender
* Container Defender
* App-Embedded Defender
|===



=== Defender types

The type of Defender you deploy depends on the resource you’re securing.

* *Host Defender* -- Secures legacy hosts (Linux or Windows) that don’t run containers.

* *Container Defender* -- Secures hosts (Linux or Windows) that run containers.
These types of hosts have a container runtime installed, such as Docker Engine or CRI-O.
Container Defender protects both the underlying host and any containers it runs, and the license (7 credits) includes coverage for both.
A container host consumes 7 credits whether it runs one container or a hundred containers.

* *Container Defender - App Embedded* -- Secures containers which are run by a managed service, where the service provider maintains all infrastructure required to run the container, including the underlying host and container runtime.
For this type of deployment, a Container App Embedded Defender is embedded into each container to be secured.

* *Serverless Defender* -- Secures serverless functions.
For this type of deployment, a Serverless Defender is embedded into each function to be secured.


=== Workload fluctuation

Prisma Cloud Compute Defenders are licensed on the honor system.
License limits are not 'hard-enforced'.
If you exceed your license count, Palo Alto Networks will notify you with a prominent banner at the top of the Prisma Cloud UI, but will neither disable any security functions nor prevent the deployment of additional Defenders.
Protection is only disabled when your license expires.

Credit consumption is measured using a 30 day rolling average.
To determine if you’re within your licensed coverage, the rolling average is compared to the number of credits in your license.

Prisma Cloud samples the number of protected nodes hourly, then creates a daily average based on these samples.
The preceding 30 daily averages are averaged to determine the credit consumption.
If there is less than 30 days of data available, the average is calculated using the days available.

*Example*: Assume you've licensed 700 credits to cover 100 container hosts, and usage fluctuates from week to week:

Nov 1-7: Lower demand, uses 90 nodes (630 credits)
Nov 8-15: Uses 100 nodes (700 credits)
Nov 16-22: Uses 100 nodes (700 credits)
Nov 23-30: High demand, uses 110 nodes (770 credits)

Even though you used 770 credits for a short period of time, you're still properly licensed because the 30 day rolling average is 700:

(630 + 700 + 700 + 770) / 4 = 700 credits


=== Example scenarios

For hosts and containers, the number of credits you need to procure depends on the number of Defenders you intend to deploy.

*Example*: Assume you have a Kubernetes cluster with 100 nodes (hosts).
You deploy a Container Defender to each node.
You would procure a license with 700 credits:

100 container hosts * 7 credits per container host = 700 credits

Serverless functions are licensed based on the number of defended functions, and averaged over the period of a month.
Every 6 defended functions count as 1 credit.
A defended function is either (a) a function with a Serverless Defender embedded or (b) a function scanned for vulnerabilities and compliance.

*Example*: Assume you have 180 functions, 180 functions are scanned for vulnerabilities and compliance while only 80 functions are defended in runtime (i.e., have a Serverless Defender embedded).
Since we count each function only once:

180 defended functions / 6 credits per defended function = 30 credits

*Example*: Assume you have a web application running over 50 containers in a 5 node cluster.
The containers running the images protected by WAAS rules are running on 2 out of the 5 nodes.
You would procure a license with 60 credits.

2 Defenders protected nodes with WAAS protected containers * 30 credits per Defender = 60 credits
