== Support lifecycle

Because the container ecosystem is rapidly evolving, understanding supportability policies is an important part of keeping your environment supportable and secure.
This article describes not only the support policy for Prisma Cloud itself, but also for other software you may integrate it with.

ifdef::compute_edition[]
You can always find the most up to date information on available releases on the xref:../welcome/releases.adoc[Releases] page.
endif::compute_edition[]

=== Definitions

Major Releases (X.Y.z)::
Include significant new features and changes.
These are also known as 'milestones' and include significant new functionality; they are released approximately every four months and include all applicable fixes made in previous releases.
These are known by versions such as "20.12" and "21.04".

Maintenance Releases (x.y.Z)::
Also known as 'updates', these are released to correct specific problems in previous releases.
They incorporate all applicable defect corrections made in prior Maintenance Releases.
These are known by versions such as "21.04 Update 2".

End of Life (EOL)::
Versions that are no longer supported by Prisma Cloud.
Updating to a later version is recommended.

Support::
Includes not only resolution of technical issues through interactive assistance, but also fixes delivered in maintenance releases to correct problems.


=== Prisma Cloud supportability policy

Prisma Cloud has an 'n-2' support policy that means the current release ('n') and the previous two releases ('n-1' and 'n-2') receive support.

Note that in some cases, resolution of a problem in the n-1 or n-2 version may require upgrading to a current build.
Prisma Cloud will make commercially reasonable efforts to work with customers that require porting fixes back to the n-1 or n-2 versions, but sometimes architectural changes are significant enough between versions that this is practically impossible without making the n-1 or n-2 versions essentially the same as the n version.


=== Third party software

Customers use a diverse set of technologies in the environments that Prisma Cloud Compute protects, including host operating systems, orchestrators, registries, and container runtimes.
As the vendors and projects responsible for these technologies evolve them, newly introduced versions and deprecated older versions can impact the scope of what Prisma Cloud supports.
For example, Prisma Cloud cannot effectively support third-party software that the vendor (or project) itself no longer supports.
Conversely, as new versions of 3rd party software are released, Prisma Cloud must comprehensively test them to be able to provide official support for them.

For each major and maintenance release of Prisma Cloud Compute, we begin testing by evaluating the versions of 3rd party software we list as officially supported in our xref:../install/system_requirements.adoc[system requirements].
When new supported versions of this software are available, we perform our testing for the release using them.
For example, if Red Hat were to release a new version of OpenShift before we begin testing an upcoming Prisma Cloud release, we'll include that new OpenShift release in our testing.
If the new version of OpenShift is released after we've begun our testing, we'll instead do this validation in the subsequent Prisma Cloud release.
Depending on where we are in the development cycle, this next release may be a maintenance release or the next major release.
Typically, new 3rd party releases can be supported with no or minor changes in Prisma Cloud.
However, there may be circumstances where a new version of 3rd party software introduces significant breaking changes that require more significant work within Prisma Cloud to maintain compatibility.
In these cases, we'll update the system requirements page to clearly note this and will communicate a roadmap for supporting this software in a later release of Prisma Cloud.

While Prisma Cloud does not actively prevent interoperability with unsupported software, with each release we evaluate the versions of software supported by vendors and projects.
As older versions are deprecated, Prisma Cloud support will similarly deprecate support for them as well.
