[.task, #upgrade-defender]
== Upgrade the Single Container Defenders

The Console user interface lets you upgrade all Defenders in a single shot.
This method minimizes the effort required to upgrade all your deployed Defenders.

Alternatively, you can select which Defenders to upgrade.
Use this method when you have different maintenance windows for different deployments.
For example, you might have an open window on Tuesday to upgrade thirty Defenders in your development environment, but no available window until Saturday to upgrade the remaining twenty Defenders in your production environment.
In order to give you sufficient time to upgrade your environment, older versions of Defender can coexist with the latest version of Defender and the latest version of Console.

*Prerequisites:* You have already upgraded Console.

[.procedure]
. Open Console.

. On the left menu bar, go to *Manage > Defender > Manage* and click *Defenders* to see a list of all your deployed stand-alone Container Defenders.

. Upgrade your stand-alone Defenders.
You can either:
+
* Upgrade all Defenders at the same time by clicking *Upgrade all*.
* Upgrade a subset of your Defenders by clicking the individual *Actions > Upgrade* button in the row that corresponds to the Defender you want to upgrade.
+
NOTE: The *Restart* and *Decommission* buttons are not available for DaemonSet Defenders.
They are only available for stand-alone Defenders.
