:topic_type: task
[.task]
[#custom-compliance-standard]
== Create a Custom Compliance Standard

// Create a custom compliance standard that reflects your company’s rules and regulations.

You can create your own custom compliance standards that are tailored to your own business needs, standards, and organizational policies. When defining a custom compliance standard, you can add requirements and sections. A custom compliance standard that has a minimum of one requirement and one section can be associated with policies that check for adherence to your standards.

You can create an all new standard or clone an existing compliance standard and edit it.

[.procedure]
. Clone an existing compliance standard to customize.

.. On Prisma Cloud, select *Compliance > Standards*.

.. Hover over the standard you want to clone, and click *Clone*.
+
When you clone, it creates a new standard with the same name with Copy in the prefix. You can then edit the cloned compliance standard to include the requirements, sections, and policies you need.

. Create a compliance standard from scratch.

.. On Prisma Cloud, select *Compliance > Standards > + Add New*.

.. Enter a name and description for the new standard and select *Save*.

.. Add requirements to your custom compliance standard.

... Select the custom compliance standard you just added and click *+ Add New*.

... Enter a requirement, name and a description and select *Save*.

.. Add sections to your custom compliance standard after adding the requirement.

... Select the requirement for which you are adding the section and click *+ Add New*.

... Enter a name for the *Section* a *Description* and select *Save*.
+
Although you have added the custom standard to Prisma Cloud, it is not listed on the Compliance Standards table on *Compliance > Overview* until you add at least one policy to it.

.. Add policies to your custom compliance standard.
+
You must associate Prisma Cloud Default policies or your custom policies to the compliance standard to monitor your cloud resources for adherence to the internal guidelines or benchmarks that matter to you. The RQL in the policy specifies the check for the resource configuration, anomaly or event.

... Select *Policies*.
+
Filter the policies you want to associate with the standard. You can filter by cloud type, policy type and policy severity, to find the rules you want to attach.

... Select the policy rule to edit, on *3 Compliance Standards* select *+* and associate the policy with the custom compliance standard.

... *Confirm* your changes.
