:topic_type: task
[.task]
[#new-compliance-report]
== Add a New Compliance Report

Monitor your single or multi-cloud environment for adherence to mandated compliance standards, with Prisma Cloud's compliance reporting tools. xref:../reports/create-and-manage-reports.adoc#compliance[Create reports] based on a cloud compliance standard for immediate viewing or download, or schedule recurring reports to continue monitoring compliance over time. Each report provides you with a consolidated view of cloud account compliance with a selected standard. The report lists resources and accounts currently monitored against the standard, and details their compliance status. Cloud resources are tracked for compliance against every section of a given standard and detailed findings for each section are included along with remediation for non-compliant sections.

[.procedure]
. Log in to Prisma Cloud.

. Select *Cloud Security > Compliance > Create Compliance Report* and select a standard from the standards list below the dashboard.

. Enter the following required information.

.. Enter a descriptive *Name* for the report.

.. Select the *Cloud Type* for the report.

.. Select the *Date* for the report.

.. Select report frequency, *One Time* or *Recurring*.
+
If you select *Recurring* specify how often and when you want the report to run.

. Enter the following optional information.

.. The *Account Groups* that the report should include.

.. The *Cloud Accounts* that the report should include.

.. The *Cloud Regions* that the report should include.

.. *Email Address(es)* to which you would like to send the scheduled report. Select the Custom Email Template checkbox if you wish to use a pre-selected notification template.

. Select *Save Report*.


[#id0800bded-7633-40c6-836f-16d29fdf89a7]
=== View and Manage Reports

Compliance reports once generated, automatically run at the scheduled time. Select *Reports > Compliance* to view a list of all available xref:../reports/create-and-manage-reports.adoc#compliance[compliance reports].

