== Jenkins provides full access to authenticated user accounts

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|cf160533-dcc2-4031-a915-ac3321e2f061 

|Severity
|High
// add severity level

|Category
|Identity and Access Management
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Jenkins

|=== 

=== Description 

Jenkins is configured to allow full access to all authenticated users. Any user that successfully logs in to the system is granted full administrative permissions, such as accessing secrets, creating, modifying, and deleting pipelines, and managing users.
This permission model puts the system at risk, as an attacker who gains control of a user account can control the entire system.

=== Recommended Solution - Buildtime

Implement RBAC on the Jenkins instance to create a granular permission model.
To achieve this, we recommended setting low-level permissions for users and groups on specific projects according to business requirements through the **Matrix Authorization Strategy** plugin.

For more information refer to https://plugins.jenkins.io/matrix-auth/.
