== Force push to default branch is allowed in GitLab

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|aa2db709-8a9e-4da2-9915-a8322aff5eaa

|Severity
|Low
// add severity level

|Category
|Data Protection
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 


=== Description 

User accounts with **write** permissions can force push to a default branch of an actively used repository^*^ and overwrite the commit history. If the repository is not stored on another source, a malicious user account can permanently delete the entire git history of the repository.

^*^An actively used repository has at least two contributors, over 50 commits, and was updated in the last 90 days.

=== Recommended Solution - Buildtime

To restrict force push on the default branch:
 
. Browse to the repository **Settings**.
. Under **Protected Branches**, add/edit the rule that applies to the repository default branch.
. Uncheck the **Allowed to force pushe** setting.

