== Merge request approvals in GitLab not required for default branch

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|9fbedb87-693a-4efa-a5f2-beda393b8588 

|Severity
|Medium
// add severity level

|Category
|Flow Control Mechanisms
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description 

Users granted with write permissions on an actively used repository^*^ can push code directly to the default branch without requiring merge reviews. An attacker who gains control of a user with **write** permissions can push malicious code to the default branch. This code is likely to flow through the pipeline and be used in production systems.

^*^An actively used repository has at least two contributors, over 50 commits, and was updated in the last 90 days.


=== Recommended Solution - Buildtime

 
. Require merge request approvals:

.. Browse to the **General** page under project **Settings**.
.. Expand **Merge request approvals** and configure an approval rule requiring at least 2 reviewers in order to merge.

. Review the **Approval** settings to add restrictions according to your needs. We recommend preventing **approval by author**.
