==  Secrets found in GitLab webhook URL

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|64fa0a5d-95ed-44b1-9642-ebe6968bc601 

|Severity
|High
// add severity level

|Category
|Credential Hygiene
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description 

Including secrets in a webhook URL comes with risks:

* Actors who can access webhooks through the API will be able to access secrets
* Third party systems logging webhook URLs could gain access to the secrets included in the URL
* When part of an unencrypted HTTP request, a webhook URL exposes the secret to anyone with access to the traffic such as cache servers and firewalls
* Placing secrets in a webhook URL makes it more difficult to rotate them 

An attacker could use these secrets to gain unauthorized access to services that are used to authenticate the webhook against. 

=== Recommended Solution - Buildtime

To secure your webhook recipient’s service from unauthorized access, remove secrets from webhook URLs, and use alternative
methods to authenticate against 3rd party systems.

For example, you can use a GitLab secret token in the webhook mechanism by including it in the request header. This ensures that the secret is not exposed in the URL.

For more information refer to: https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#configure-a-webhook-in-gitlab.  
