== Throttling is not enabled in GitLab

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|ecc6abc1-4e6a-4ed9-a8c8-3d45481fd874  

|Severity
|Low
// add severity level

|Category
|System Configuration
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description 

Throttling limits the number of requests performed by a user in a certain period. GitLab offers a throttling mechanism to limit the number of requests sent to its API on its self-managed instances.
An attacker with access to an unlimited self-managed GitLab instance can abuse its API to find sensitive files, check the accessibility of administrative pages or overload the instance resources.

Throttling was not enabled on this instance.

=== Recommended Solution - Buildtime

GitLab self-managed instances offer three options to limit requests:

* Unauthenticated requests
* Authenticated API requests
* Authenticated web requests

There are two options for setting limits:

==== Modify settings through the console:
 
. In the **Admin Area**, access **Settings**.
. Under **Network** scroll to **User and IP Rate Limits**. 
. Configure the three settings (see above) with the organization’s required limits.
+
For more information refer to https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html#user-and-ip-rate-limits.

==== Modify settings through the API:
 
. Follow the instructions on the GitLab API documentation: documentation: https://docs.gitlab.com/ee/api/settings.html#change-application-settings 
. Set the **throttle_* settings** according to environment requirements.
----
NOTE:
* Bypassing throttling settings: If required, add a custom header to requests via predefined services to bypass throttling settings. Refer to: https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html#use-an-http-header-to-bypass-rate-limiting

* Allow specific users to bypass the rate limiter. Refer to: https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html#allow-specific-users-to-bypass-authenticated-request-rate-limiting

* GitLab allows setting a throttle to _dry run mode_ which logs a message to the auth.log when it hits the limit, while letting the request continue as normal. Refer to: https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html#try-out-throttling-settings-before-enforcing-them
----



