== Unrotated GitLab deploy keys

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|0c472248-1cb2-4338-ab7d-213653326577

|Severity
|Low
// add severity level

|Category
|Identity and Access Management
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description 


Deploy keys created on GitLab projects were not rotated for more than 180 days. An attacker that obtains access to a deploy key has direct access to the repository code, and in cases where the key is assigned with **write** permissions, it grants the ability to edit the code. As long as a deploy key exists, it increases the potential of a leaked key being valid when used by an attacker.

=== Recommended Solution - Buildtime

To minimize the risk of a stolen deploy key being used by an attacker, it is recommended to rotate deploy keys within a maximum period of 180 days after creating the key.

To achieve this, for each deploy key:
 
. Create a new private key on the server intended to use it.
. Create a new deploy key using the matching public key, in the same project that the current key was created on.
. Direct the server to use the new key instead of the key in use.
. Delete the older deploy key from the GitLab project.

There are two options for creating and deploying keys:

* Create and delete deploy keys using the console. Refer to the instructions on the GitLab documentation: https://docs.gitlab.com/ee/user/project/deploy_keys/.

* Create and delete deploy keys using the API. Refer to the GitLab API documentation: https://docs.gitlab.com/ee/api/deploy_keys.html.










