== Federating identity with AWS

//'''
//
//title: Federating identity with AWS
//type: single
//url: "/3.14/setup/federation/"
//weight: 50
//menu:
//  3.14:
//    parent: "setup"
//    identifier: "federation"
//canonical: https://docs.aporeto.com/3.14/setup/federation/
//
//'''

=== About federating identity with AWS

Aporeto can provide your applications with shortlived https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html[AWS security tokens] on demand via https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_oidc.html[web identity federation].
Using Aporeto as an OpenID Connect (OIDC) identity provider for your applications:

* Makes it easy to obtain shortlived https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html[AWS security tokens].
* Eliminates the need for storing, passing, or rotating long-lived credentials.
* Allows you to use https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html[IAM roles] for your applications instead of individual AWS accounts.

To enable applications to obtain AWS credentials from Aporeto, complete the following steps.

=== Prerequisites

*Local host*:

* https://stedolan.github.io/jq/download/[jq installed]
* https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html[AWS command line interface installed] and https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html[configured]

*Enforcer host*:

* Enforcer installed using the xref:../start/enforcer/linux.adoc#_production-cloud-install[production cloud] procedure
* https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html[AWS command line interface installed]

[.task]
=== Setting environment variables

[.procedure]
. On your local host, set an `AUDIENCE` environment variable containing a value that https://tools.ietf.org/html/rfc7519#section-4.1.3[identifies the applications allowed to access the third party resource].
Applications that don't provide the correct audience get rejected.
You can use any string value.
+
[,console]
----
export AUDIENCE=i-deserve-a-token
----

. Set a `NAMESPACE` environment variable containing the namespace of the applications that will request credentials.
+
[,console]
----
export NAMESPACE=/acme/team-a
----

. Use the following command to retrieve the ID of the namespace and set it in a `NAMESPACE_ID` environment variable.
+
[,console]
----
export NAMESPACE_ID=$(apoctl api get namespace $NAMESPACE | jq --raw-output '.ID')
----

. Set your AWS account ID in an `AWS_ACCOUNT_ID` environment variable.
+
[,console]
----
export AWS_ACCOUNT_ID=523089932348
----
+
[TIP]
====
You can find your AWS account ID under *My Security Credentials* in the AWS Management Console.
====

=== Enabling JSON web token signing

Issue the following command to enable JSON web token (JWT) signing in the namespace of the processing units.

[,console]
----
apoctl api update namespace $NAMESPACE_ID -k JWTCertificateType RSA
----

[TIP]
====
For maximum interoperability, we set the algorithm to RSA above.
To use the more secure ECDSA algorithm, replace `RSA` with `EC`.
Both options use 256-bit keys.
For more information about the algorithms, refer to https://tools.ietf.org/html/rfc7518#section-3[RFC-7518].
====

[.task]
=== Adding Aporeto as an AWS identity provider

[.procedure]
. Open the https://console.aws.amazon.com/iam/home#/providers[AWS IAM Identity Providers page].
. Click *Create Provider*.
. Select *OpenID Connect* as the *Provider Type*.
. Return to your terminal and issue the following command to obtain the URL of your Aporeto identity provider.
Copy the returned value to your clipboard.
+
[,console]
----
apoctl api list oauthinfo in namespace $NAMESPACE_ID | jq --raw-output '.[].issuer'
----

. Return to the AWS Management Console and paste the URL of your Aporeto identity provider into the *Provider URL* box.
. Select the audience that should be allowed.
+
[TIP]
====
If you don't remember the value you're using for audience, type `echo $AUDIENCE` in your terminal.
====

. Click *Next Step*.
. Click *Create*.
. Return to your terminal and use the following command to create a JSON file containing the IAM policy for your Aporeto identity provider.
+
[,console,subs="+attributes"]
----
 cat >> idp_iam_policy.json <<EOL
 {
   "Version":"2012-10-17",
   "Statement":[
     {
       "Effect":"Allow",
       "Principal":{
         "Federated":"arn:aws:iam::$AWS_ACCOUNT_ID:oidc-provider/{ctrl-plane-api-url}/v/1/namespaces/$NAMESPACE_ID/oauthinfo"
       },
       "Action":"sts:AssumeRoleWithWebIdentity",
       "Condition":{
         "StringEquals":{
           "{ctrl-plane-api-url}/v/1/namespaces/$NAMESPACE_ID/oauthinfo:aud":"$AUDIENCE"
         }
       }
     }
   ]
 }
 EOL
 cat idp_iam_policy.json
----

. Use the following command to pass the policy file to AWS and create the IAM role.
+
[,console]
----
aws iam create-role --role-name aporeto-idp --assume-role-policy-document file://idp_iam_policy.json
----
+
AWS should return a JSON object containing the role.

=== Creating a token scope policy

Use the following command to create a token scope policy.

[,console]
----
cat <<EOF | apoctl api create tokenscopepolicy -n $NAMESPACE -f -
name: aws-tokens
description: AWS token scopes and claims
propagate: true
assignedAudience: "i-deserve-a-token"
assignedScopes:
- "@awsrole=arn:aws:iam::$AWS_ACCOUNT_ID:role/aporeto-idp"
subject:
- - "@auth:account=$AWS_ACCOUNT_ID"
EOF
----

[.task]
=== Verifying the setup

[.procedure]
. SSH into a host equipped with an enforcer in the namespace.
+
[,console]
----
ssh -i "private-key.pem" ubuntu@ec2-54-186-168-240.us-west-2.compute.amazonaws.com
----

. Ensure your AWS CLI credentials are cleared.
+
[,console]
----
aws configure
----

. Clear the following values.
+
[,console]
----
AWS Access Key ID [None]:
AWS Secret Access Key [None]:
----

. You must set your region.
An example follows.
+
[,console]
----
Default region name [None]: us-west-2
----

. Check to see what your caller identity is.
+
[,console]
----
aws sts get-caller-identity
----
+
It should return the name of the IAM role that you attached to your EC2 instance.
An example follows.
+
----
{
  "UserId": "AROAIBVRWYRACESUSAFPK:i-0b23fc41ae2742d67",
  "Account": "523089932348",
  "Arn": "arn:aws:sts::523089932348:assumed-role/aporeto/i-0b53fc41af2742d67"
}
----

. Start a bash session wrapped by the Aporeto enforcer.
Aporeto recognizes the bash session as a processing unit, allowing you to request an Aporeto token from the enforcer.
+
[,console]
----
enforcerd run /bin/bash
----

. Request an Aporeto token from the enforcer, save it in a file, and verify the result.
+
[,console]
----
curl -o aporeto-jwt http://169.254.254.1/token -H "X-Aporeto-Metadata: secrets"
cat aporeto-jwt
----

. Close the bash session.
+
[,console]
----
exit
----

. Set an `AWS_WEB_IDENTITY_TOKEN_FILE` environment variable containing the name of the file.
+
[,console]
----
export AWS_WEB_IDENTITY_TOKEN_FILE=aporeto-jwt
echo $AWS_WEB_IDENTITY_TOKEN_FILE
----

. Set an `AWS_ROLE_ARN` environment variable containing the name of the IAM role you created earlier.
+
[,console]
----
export AWS_ROLE_ARN="arn:aws:iam::523089932348:role/aporeto-idp"
echo $AWS_ROLE_ARN
----

. Check your identity again.
+
[,console]
----
aws sts get-caller-identity
----
+
It should return something like the following.
+
----
{
  "UserId": "AROA5PHZTVM2UXG4ECDIE:botocore-session-1582845857",
  "Account": "523089932348",
  "Arn": "arn:aws:sts::523089932348:assumed-role/aporeto-idp/botocore-session-1582845857"
}
----
+
Congratulations! You've succeeded in exchanging an Aporeto token for an AWS security token.

=== Next steps

To learn more about the xref:../develop/enforcer-api.adoc#_token[`token` endpoint], check out the xref:../develop/enforcer-api.adoc[Enforcer API] reference documentation .
