== CircleCI accesses cloud provider using insecure long-term credentials

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|c478f0b1-2b42-46af-a959-e58df53137ff 

|Severity
|Medium
// add severity level

|Category
|Credential Hygiene
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|CircleCi

|=== 


=== Description 

CircleCI uses long-term credentials to authenticate cloud service providers when running pipeline jobs. These credentials are stored as environment variables in CircleCI. 
Attackers who gain access to a user with write permissions can expose these secrets, allowing them long term access to the cloud service provider. 

=== Recommended Solution - Buildtime

Replace long-term credentials with short-lived access tokens, using the **OpenID Connect** (OIDC) authentication protocol. 
Through OIDC, the CircleCI job requests a short lived access token directly from the cloud service provider. For more information on OIDC in CircleCI refer to https://circleci.com/docs/2.0/openid-connect-tokens/.
