== 20.09 Update 1 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|20.09.365

|Code name
|Fermat, 20.09 update 1

|Release date
|26 October 2020

|Type
|Maintenance release

|SHA-256 digest
|3c44d166d0316ac509b2eb315d3f22934f1654034e3cf195f86255540f88233a
|===

// Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic download (e.g., curl, wget) of the release directly from our CDN:
//
// LINK


=== Improvements, fixes, and performance enhancements

// #23420, #24132
* Adds support for running any minor version of Defender within a major release.
In other words, given a major version of Console, Prisma Cloud supports all minor versions of Defender.
For example, if you're running Prisma Cloud Compute Edition 20.09.345, and you upgrade Console to 20.09.365, then all deployed Defenders that are still on version 20.09.345 can continue to interoperate with Console 20.09.365 in a supported configuration.

// #23206, #24085, #24390, #24316, #23702
* Adds support for Istio 1.6.
Deprecates support for Istio 1.4 and 1.5.
Includes various Istio bug fixes.
You must upgrade Defenders to 20.09.365 for Istio 1.6 support (previous 20.09.345 Defenders don't support Istio 1.6).

// #24197 
* Fixes an issue where you could not view docker or kubectl logs for some container that were launched or restarted in environments protected by Defender.
This fix is in Defender, so Defender must be explicitly upgraded to 20.09.365.
Also, any pods/containers that have this logging issue should be restarted after Defender is upgraded.

// #24109
* Fixes an issue with a misaligned icon in a policy dialog.

// #24270
* [Intelligence Stream] Re-adds links to Node.js vulnerabilities.

// #23994, #24158, #24103
* Fixes Defender runtime issues.

// #23957
* Fixes an issue where container processes could be incorrectly classified as interactive in runtime models.

// #23910
* Fixes vulnerabilities in Prisma Cloud Compute components.

// #23869
* Fixes how errors are handled when calling the API.

// #23737
* Fixes an issue where restoring from a backup file with twistcli didn't work due to a permissions misconfiguration.

// #23595, #23594
* Fixes an issue with false positive vulnerabilities for Apache Tomcat 7 and 8.

// #23562
* Fixes an issue where setting a validating admission webhook on Kubernetes 1.19 cluster failed because of a certificate issue.
Moves domain names from the Common Name field in the X.509 certificate to the Subject Alternative Name extension.

// #23442 
* Fixes an issue with a missing path to runC for Kubernetes on DC/OS.

// #24275
* Fixes an issue where App-Embedded Defender failed to initialize because it couldn't fetch GCP metadata.

// #23095
* Embeds the list of Prisma Cloud Compute open source software components and licenses in the Defender image.

// #22943
* Fixes an issue in WAAS where network controls were not applied in app list order.

// #22370
* Fixes an issue with how App-Embedded Fargate Defender uses LD_PRELOAD.
Previously, Prisma Cloud completely overrode LD_PRELOAD.
Now, any values set in LD_PRELOAD are retained.
