== 21.08 Update 1 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|To be announced

|Code name
|Iverson, 21.08 update 1

|Release date
|TBD

|Type
|Maintenance release

|SHA-256 digest
|TBD
|===

// Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic download (e.g., curl, wget) of the release directly from our CDN:
//
// LINK


=== Improvements, fixes, and performance enhancements

// #30726
* Adds support for OpenShift 4.8.

// #32066
* Creates new permissions for the image analysis sandbox that lets users analyze images and read results.
By default, these permissions are assigned to Admins and Operators.
In this update, the permission is also now assigned to DevOps Users, so that you don't have to grant privileged roles (Admin, Operator) for users that need to work with image sandbox analysis.
Auditor and DevSecOps roles will get read-only access to review results only.
For SaaS customers, use the Prisma Cloud permission group that maps to the DevOps role in Compute to grant access to use the image analysis sandbox.

// #30788
* Fixes an issue where Defender can't be installed on K3S because it cannot find the containerd socket path.

// #32503
* Fixes false positives for Java vulnerabilities.

// #32596
* Handles errors gracefully when compiling Rego scripts for admission control (Open Policy Agent) feature.

// #31927
* Adds support for Podman 1.6.4 on RHEL7.

// #32638
* Emits the following info to syslog for each vulnerability found in CI scans when verbose scans are enabled:
** Path to the vulnerable package.
** Layer time and instruction for the layer that contains the vulnerability.

// #31857
* [WAAS] Updates WAAS certificate management to alert users about TLS certificate expiration 30 days in advance, rather than 7 days.

// #31827
* [WAAS] Fixes false positives in WAAS app firewall protections.

// #31090
* [WAAS] Lets you individually configure the SameSite and Secure attributes for Prisma Cloud session cookies.

// #32582
* [SaaS] Adds search to the integrations drop-down.
Integrations are specified when setting up Compute alerts.

// #32256
* Fixes UI strings.

// #32871
* Validates support for Istio 1.11.
Istio 1.11 is supported on all 21.08 releases.


=== Known issues

// #31803
* Auto-deploy for Host Defender on GCP fails with an authorization error.
