== 19.11 Update 2 Release Notes

This section provides a snapshot of the fixes in Prisma(TM) Cloud Compute Edition 19.11 Update 2 (19.11.512).

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|19.11.512

|Code name
|Dirac, 19.11 update 2

|Release date
|27 January 2020

|Type
|Maintenance release

|SHA-256 digest
|ef421363aed98efca47d4427d9e9b0a379f355953356e00c9fe6603ed47c4701
|===


=== Improvements, fixes, and performance enhancements

// #18316
* Adds support for Node.js 10 to Serverless Defender.
Support for Node.js 8 has been deprecated.
// #18317
* Fixes an issue with the Fargate Defender sidecar container overriding the tmp directories of other containers in the task.
Two tmp directories are impacted: /tmp and /var/tmp.
This update fixes the issue for /var/tmp.
The next major release will fix the issue for /tmp.
// #17969
* Improves how syslog events are handled when Console can't connect to the syslog server due to network errors and the like.
// #16276
* Fixes the scanner to more gracefully handle the case when malware feed isn't available (for example, you've deployed to an environment with no outside network connection).
When the malware feed can't be accessed, the scanner prints a message to the log, and continues.
// #17994
* [Prisma Cloud Enterprise Edition] Fixes an issue where the access token wasn't published in the Compute Console.
It's now available under Compute > Manage > System > Intelligence.
// #18415
* Fixes security issues.
