== 21.04 Update 1 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|TBD-upcoming release

|Code name
|Hamilton

|Release date
|Upcoming release

|Type
|Maintenance release

|SHA-256 digest
|TBD-upcoming release
|===


=== Improvements, fixes, and performance enhancements

//#28824
* Adds support for Kubernetes resource labels discovery in CRI-O runtime.
//#28101
* Adds support for Podman 3.
//#29346
* Fixes an issue with applying custom rules to WAAS policy.
//#29268
* Exposes the proxy read timeout configuration for WAAS.
//#29263
* Fixes an issue with twistcli IaC Scan for a large number of resources (<1000).
//#29256
* Changes default effect from “Disable” to “Allow” for user defined Bots in WAAS policy.
//#29195
* Fixes an issue with Intelligence Stream update for tenant projects that are hosted on machines with low resources.
//#29180
* Fixes an issue with OAuth in OpenShift 4.6.
//#28862
* Fixes an issue with UI response time for page load on Defend > Images > Registry Settings.
//#28784
* Fixes an issue with filesystem monitoring on pods that use NFS volumes with root squashing enabled. With this fix, NFS volumes with root squashing enabled are skipped to avoid errors.
//#27983
* Fixes an issue with the missing content-encoding header when WAAS is enabled.
