== 21.04 Update 2 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|21.04.439

|Code name
|Hamilton, 21.04 update 2

|Release date
|24 June 2021

|Type
|Maintenance release

|SHA-256 digest
|82569f2911e9abc6bb07333d5128a8575052671e7b64e31473d561dd001623df
|===

// Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic download (e.g., curl, wget) of the release directly from our CDN:
//
// LINK


=== Improvements, fixes, and performance enhancements

// #29736
* [Enterprise Edition - SaaS] Fixes an issue with downloading the OpenAPI file from Console.

// #29192
* [Enterprise Edition - SaaS] Fixes an issue with Console hanging when loading Prisma Cloud credentials in credentials store when there are a large number of credentials.

// #29541
* [WAAS] Fixes a race condition in the WAAS proxy when Advanced Threat Protection is enabled and there are multiple instances of WAAS running on the same host.

// #29716
* Fixes an issue where, after upgrade, existing WAAS rules with user defined bots cannot be edited then saved.

// #29516
* Fixes an issue where there are duplicates of system-provided custom runtime rules.

// #29501
* Adds information about detected applications in twistcli image scan output.

// #29497
* Adds the `/api/v1/authenticate` endpoint in OpenAPI spec file.

// #29222
* Enhances syslog support to emit CI scan results to syslog.

// #29197
* Updates the scanning methodology for TAS blobstore to scan all configured blobstores, even if one is misconfigured. Previously scanning would terminate as soon as misconfigured blobstore was encountered, even if the remaining unscanned blobstores were properly configured.

// #29124
* Adds a retry during Defender startup if there's a network error when initially accessing the cloud provider's metadata service.

// #25824
* Improves how vulnerabilities are reported for Red Hat CoreOS (RHCOS).
RHCOS is based on specific versions of Red Hat Enterprise Linux (RHEL).
Prisma Cloud now reports the underlying version of RHEL when a RHCOS host is scanned.


=== Security advisories

* Remediates https://security.paloaltonetworks.com/CVE-2021-3043[CVE-2021-3043].
