== 20.04 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|20.04.163

|Code name
|Euler

|Release date
|7 April 2020

|Type
|Major release

|SHA-256 digest
|0c017b4b36d51d4515bafbc63fcd10d607b26cc9c863b589318d64dc540a338e
|===


=== New features

// #16122
* Provides a new mechanism to automatically protect serverless functions with Serverless Defender directly from Console or the API.

// #15682
* Streamlines operations by automatically upgrading all Container Defenders, Defender DaemonSets, and Host Defenders when Console is upgraded.
(Serverless Defenders can be upgraded by way of the new auto-protect feature. App Embedded Defenders must still be manually upgraded).

// #13998
* Consolidates all CI policy in Console (previously, policy was partially specified in the Jenkins plugin or twistcli).

// #16481
* Extends and improves the Trusted Images feature with trust groups, which let you capture related images in entities that can then be used in policy rules.

// #14651
* Adds the ability to tag vulnerability findings, filter views based on tags, and set policy based on tags.

// #14574
* Extends Prisma Cloud support for registries, with support for Harbor registries, Nexus Registry webhooks, certificate-based authentication for Docker v2 registries, and jFrog Artifactory virtual repositories.

// #12372
* Adds the ability to scan VM images, specifically Amazon Machine Images (AMIs).

// #6933
* Integrates the Open Policy Agent into Prisma Cloud Compute so that you can specify admission control logic using the Rego language.

// #16420, #18494, 
* Maps Prisma Cloud roles to Prisma Cloud Compute roles for better control over what users and groups can see and do in the Compute tab.

// #19319
* Automatically maps Prisma Cloud API access keys to the corresponding Compute role.
Previously, an administrator would manually need to create the mapping.

// #17608
* Collects AWS tags for VM instances, and lets you create collections based on these tags.

// #12198
* Enhances the Vulnerability Explorer UI to better allow security and risk teams to quickly prioritize risk across any cloud native environment.

// #18333
* Adds the ability to append a custom string to all Console and Defender syslog messages.
Useful when you want to be able to identify syslog messages from different Prisma Cloud deployments (where a deployment consists of one Console and all the Defenders connected to it).

// #17820, #15587
* Aligns UI look and feel with the rest of the Prisma Cloud product, along with other UI/UX improvements.

// #17617
* Improves the Jenkins plugin UI, including a better interface for viewing vulnerabilities.

// #17617
* Eliminates Jenkins plugin dependencies on the "Dashboard View" and "Static Analysis Utilities" plugins.

// #17617
* Adds a `project` parameter to the pipeline to scan resources in specific projects only

// #17407
* [Prisma Cloud Enterprise Edition] Introduces a unified integrated navigation bar for accessing the Compute tab, and navigating through Compute pages.

// #17404, #12439
* Adds support for deep linking to Console's pages so that you can copy links from your browser's nav bar to share and return to specific pages in the Console UI.

// #16804
* Lets you quickly clear out column filters by clicking *Clear all filters*.

// #16803
* Adds filters for registry scan results (registry, repo), users (name, role) and groups (name, role).

// #16759
* Adds the notion of capabilities to runtime profiles to better model container images that have one or more aspects that can't be modeled strictly by process, file system, and network rules.

// #1290
* Adds the ability to monitor your environment for raw sockets, which can indicate suspicious activity.

// #16464
* Extends twistcli to scan infrastructure as code (IaC) files, such as CloudFormation, Terraform, and Kubernetes YAML files, for compliance issues.

// #16395
* Adds native support for Demisto as a sink for Compute alerts and events.

// #16381
* Improves readability and formatting of twistcli's scan report output.

// #16303
* Adds VMware Photon OS as a supported host OS.

// #15458
* Fortifies Python vulnerability data in our Intelligence Stream.

// #15335
* Adds a new dedicated vulnerability policy for serverless functions.

// #15199, #15198
* Adds support for custom runtime rule, custom compliance rules, Kuberneres audit rules, CNNF, and assigned collections to tenant Projects.

// #15172
* Adds support for certificate-based authentication for the Twistlock for Pivotal tile (now Twistlock for VMware Tanzu tile).

// #15021
* Disables Console's unencrypted HTTP listener by default for better out-of-the-box security.

// #14782
* Extends runtime protection on file systems with controls for preventing existing files from being modified.

// #14677, #11830
* Adds new user roles for better control over what users can do in Prisma Cloud Compute.
The new roles are Vulnerability Manager and DevSecOps User.
The DevSecOps role has read only access to all pages under *Monitor* and *Radar*.

// #14342
* Enhances runtime process monitoring capabilities.

// #14124
* Enhances malware detection capabilities.

// #13987
* Updates base image for Console and Defender containers to Red Hat Universal Base Image (UBI) 8.

// #13567
* Improves runtime system to properly capture and model initial startup events.

// #13532
* Improves Container Radar layout so that network traffic flows from left to right.

// #13189
* Extends support for Kubernetes labels, including labels defined and applied at runtime and namespace labels.

// #13176
* Brings feature parity for Docker-less environments, including registry scanning, twistcli scanning, and Jenkins plugin scanning.

// #10672
* Adds support for downloading backup files from the Console UI or the API.

// #1291
* Adds the capability to rotate Console's self-signed certificates (valid for 3 years) a month before expiration.

// #18170
* Adds the ability to minimize the scan progress bar, while still monitoring scan progress.

// No GH issue
* Updates support for the Microsoft Edge browser.
Prisma Cloud only supports the new Microsoft Edge Chromium-based browser (version 80.0.361 and later).


=== Breaking Changes

// #19319
* [Prisma Cloud Enterprise Edition] Any previously created API access keys that were manually mapped to a Compute role will be deleted.
These keys are found in the Compute tab in *Manage > Authentication > Prisma Cloud Access Key Mapping*.
In 20.04, API access keys created in Prisma Cloud are automatically mapped to their corresponding Compute role.

// #13998
* Existing CI policies defined with twistcli parameters, such as `--vulnerability-threshold`, `--compliance-threshold`, etc, have been deprecated.
All those parameters are now centrally defined in Console in a new dedicated CI policy page.
If you try to pass these parameters to twistcli version 20.04.163, twistcli will exit with an error: `Incorrect Usage: flag provided but not defined`.
When upgrading to 20.04, you must fix how twistcli is called in your pipeline (remove deprecated policy params) and re-implement your policy in Console's new CI policy engine.


// #17617
* Due to restructuring the Jenkins plugin:
** All CI scan reports in Console will be deleted when you upgrade.
** The name and artifact ID of the  Jenkins plugin has changed from Twistlock to Prisma Cloud.
When upgrading, install the new plugin and remove the old one.
** All global plugin configurations will be lost.
After upgrading, re-enter them.
** All non-pipeline build project build steps will be lost.
After upgrading, re-enter them.
** Update your pipeline scripts.
Pipeline function names have changed from twistlockScanXXX to prismaCloudScanXXX.

// #18722
* When upgrading, all container/host profiles will be deleted, and Radar will be cleared.
Updated profiles and Radar view will be populated immediately after upgrading.

// #18522
* When upgrading, CNNF rules will be migrated to the new 20.04 format.
Note that 19.11 let you define rules that wouldn't work.
The migration logic tries to fix broken rules when they're upgraded.
Review all rules after upgrading.
Rules are upgraded as follows:

[cols="1,1a,2a", options="header"]
|===

|Rule type
|Migration behavior
|Details

|Source to multiple entities
|Stays the same.
|Source -> Entity_1 {vbar} effect:allow

Source -> Entity_2 {vbar} effect:allow

Source -> Entity_x {vbar} effect:allow

Source -> all other entities {vbar} effect: alert/deny based on existing rule

|Source to only subnets
|Stays the same.
|Source -> Subnet_1 {vbar} effect:allow

Source -> Subnet_2 {vbar} effect:allow

Source -> Subnet_x {vbar} effect:allow

Source -> all other subnets {vbar} effect: alert/deny based on existing rule

|Source to mix of subnets and entities
|Different behavior.
These types of rules didn't work in 19.11.
When migrating to 20.04, only keep entities, drop subnets, and set effect to alert.
|Source -> Entity_1 {vbar} effect:allow

Source -> Entity_2 {vbar} effect:allow

Source -> Entity_x {vbar} effect:allow

Source -> all other entities {vbar} alert (since we remove all subnet rules)

|Fallback rule
|Different behavior
|If only entity -> entity rules are defined add:

All other entities -> all other entities + learning {vbar} effect: allert

If only entity -> subnet rules are defined add:

All other entities -> subnet {vbar} effect: alert

|===

// #15021
* The default Prisma Cloud Compute configuration now disables the HTTP listener.
If you retain your previous configuration when upgrading, the HTTP port will be open.
If not, HTTP connections will be blocked by default.

// #14677
* The Defender Manager role has changed.
It now only allows access to *Manage > Defenders*.

// #13998
* The API for evaluating functions has changed to support evaluating multiple functions.

//#12439
* The following API endpoints have been deprecated:
+
** /containers/filters
** /hosts/filters
** /scans/filters
** /profiles/container/filters
** /audits/mgmt/filters
** /audits/incidents/filters

// #18610
* Default expiration of access tokens was reduced from 24 hours to 30 minutes.


=== Known issues

* The exit code from twistcli always returns 0, regardless of your policy's failure criteria.
This causes problems when using twistcli to fail builds based on twistcli's exit code.


=== Deprecated this release

* Support for system calls in runtime models and policy has been deprecated.

* Dashboard portlets (graphs) in the Jenkins plugin have been deprecated.


=== Deprecated next release

// #19682
* Prisma Cloud High Availability (HA) will be deprecated in the next release of Prisma Cloud (second half of 2020).
For your HA needs, use a container orchestrator, such as Kubernetes, to run and manage the Console container.
