== 22.01 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|21.01.XXX

|Code name
|Joule

|Release date
|January 24, 2022

|Type
|Major release

|SHA-256 Digest
|XXX
|===

// Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic download (e.g., curl, wget) of the release directly from our CDN:
//
// LINK


// TEMPLATE FOR RELEASE NOTES
//
// ==== User-friendly feature name
//
// // #issue-num
//
// * Description (elevator pitch) 
// * Feature overview  (1-2 sentences)
// * What's the use case/need/why this is exciting (1-2 sentences)
// * Where to enable/configure it (1 sentence)


=== New features in the core platform

In addition to familiarizing yourself with the new features and enhancements in this release, review the minimum  https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-01/prisma-cloud-compute-edition-admin/install/system_requirements.html[System Requirements] for versions that are tested and supported on 22.01. 

==== User-friendly feature name

#issue-num

* Description (elevator pitch) 
* Feature overview  (1-2 sentences)
* What's the use case/need/why this is exciting (1-2 sentences)
* Where to enable/configure it (1 sentence)
* Screenshot

==== One more new feature


=== New features in container security


==== Kubernetes auditing for EKS and AKS 

* Kubernetes auditing is now supported also for AWS EKS clusters as well as Azure AKS clusters 
* The settings configuraton was enhanced and now allows add kubernetes auditing setting records for each of cloud providers  
* >>>Screenshot

==== Kubernetes auditing cluster filter  

* Kubernetes auditing policy rules now allows to configure the rules using a cluster filter
* This allows cusotmers to granuluazlie their rules to the relevant specific clusters while the ingestions can be done for a wider range of clusters   
* >>>Screenshot

==== CIS benchamrks extended support   

* The list of supported CIS benchamrks was extended to cover:
   ** CIS openshift v1.1.0 support 
   ** Updated support for latest CIS Docker bencmark 1.3.1 
   ** Updated support for latest CIS Kuberntes 1.20 (CIS v1.1.) 
* >>>Screenshot

==== Compliance for containerd containers  

* All CRI runtime compliance checks are now applicable also for containerd containers 
* >>>Screenshot

==== Alerts integration with Splunk

* You can now send alerts from Prisma Cloud Compute edition Console to Splunk. 
     ** This helps consolidate alert notifications from Prisma Cloud into Splunk so that your operations team can review and take action on the alerts.
     ** This is in addition to the existing Prisma Cloud Enterprise edition integration with Splunk.
     ** The Alert integration with Splunk is done via the Splunk HTTP Event Collector, using the _json source type.

==== Protecting Runtime events from PII/sensitive information:

* Prisma Cloud Compute Runtime events may include sensitive information that's found in commands run inside protected workloads. Now you can filter this sensitive information and ensure that it is not included in the Runtime findings (including Forensics, Incidents, audits, etc.).
     ** PII sanitization is important for protecting user privacy as well as ensuring that logs comply with relevant regulations (PCI, GDPR, HIPAA, amongst others).
     ** There are two options to scrub your sensitive Runtime data in Prisma Cloud Compute:
          *** Default scrubbing configuration: automatically scrub secrets from runtime events. This configuration will be *enabled* by default when upgrading the Console.
          *** Customize your own regex to detect and scrub sensitive information, in addition to the existing capabilities in WAAS.
     ** Head to Manage > General to see the options that are now available.
    
==== Immediate vulnerability alerts

* You can now choose to send alerts immediately when new vulnerabilities are detected, in addition to the existing vulnerability alerting mechanism. 
* Immediate alerts can be sent in one of the following scenarios:
     ** Deploying a new image/host with vulnerabilities
     ** Detecting new vulnerabilities when re-scanning an existing image/host
     
     
==== Defend your containers running on AKS Windows containerd nodes

* Extend the Azure Kubernetes Service (AKS) to support containers running on Windows nodes with containerd runtime:

     ** You can now install the Prisma Cloud Windows container defender on your AKS Windows containerd nodes.
     ** By installing the Defender you will be able to view the running containers and images on the Radar and leverage Prisma Cloud Runtime Defense capabilities on the running containers.
     ** Vulnerabilities and Compliance scanning are not supported yet

==== User-friendly feature name

#issue-num

* Description (elevator pitch) 
* Feature overview  (1-2 sentences)
* What's the use case/need/why this is exciting (1-2 sentences)
* Where to enable/configure it (1 sentence)
* Screenshot


=== New features in host security

==== User-friendly feature name

#issue-num

* Description (elevator pitch) 
* Feature overview  (1-2 sentences)
* What's the use case/need/why this is exciting (1-2 sentences)
* Where to enable/configure it (1 sentence)
* Screenshot

=== New features in shift left security

==== User-friendly feature name

#issue-num

* Description (elevator pitch) 
* Feature overview  (1-2 sentences)
* What's the use case/need/why this is exciting (1-2 sentences)
* Where to enable/configure it (1 sentence)
* Screenshot


=== New features in WAAS

==== WAAS Dashboard
// #26681
* A new WAAS dashboard name *WAAS explorer* is now available under *Monitor* -> *WAAS*.
* WAAS dashboard provides and overview of protection coverage, web application and API security posture, usage stats and insights

==== WAAS Event IDs
// #29280
* An Event ID will be assigned to all new WAAS events so that they can be referenced by end users and searched within the Event Monitor. 
* End users will be able to view event IDs as part of WAAS's block pages and in a new HTTP response header (X-Prisma-Event-Id).

==== Custom Rules - Extended Functionality
// #28252
* The "Allow" effect is now available for custom rules. When allowed, requests override actions set by other protections (application firewall, bot protection, API protection, etc.).
* The following transformation functions are available to users creating custom rules - `lowercase`, `compressWhitespace`, `removeWhitespace`, `urlQueryDecode`, `urlPathDecode`, `unicodeDecode`, `htmlEntityDecode`, `base64Decode`, `replaceComments`, `removeCommentSymbols`, `removeTags`.


==== gRPC Support

// #24614
* WAAS now supports inspection of gRPC messages

==== Scanning for Unprotected Web Applications and APIs
// #29018
* Support scanning for unprotected web applications and APIs on hosts

// #30268
* A new option lets users disable the scanning for unprotected web applications and APIs 

==== API Observations

// #25823
* JSON body content is now added to the learning model 
* Schemes will be presented as part of the observations and will be available for export in an Open API specification V3 JSON. 




==== Additional new functionality

==== User-friendly feature name

#issue-num

* Description (elevator pitch) 
* Feature overview  (1-2 sentences)
* What's the use case/need/why this is exciting (1-2 sentences)
* Where to enable/configure it (1 sentence)
* Screenshot


=== DISA STIG scan findings and justifications



=== Breaking changes

Be aware of the following breaking changes when upgrading to 22.01:

// #issueID
* Starting in 22.01, 
** x
** y
** z

// #33194
* The required permissions for the Serverless Radar, Serverless Scanning and Serverless Auto-Defend were slightly adjusted to support scanning and auto-defending KMS encrypted functions.

=== Breaking changes in the API

// #issueID
The following endpoint has been deprecated in 22.01:


=== Known issues

// #issueID
* description here.
one sentence in each line 



=== Deprecated this release

* Swarm is no longer supported.

// #issueID
* Removes support for Kubernetes dynamic audit configuration, which was deprecated in Kubernetes 1.19.
+
 more sentences to describe, as needed.

// #issueID
* description here.
one sentence in each line


=== Upcoming deprecations

// #issueID
* description here.
one sentence in each line

