== App credentials and tokens

//'''
//
//title: App credentials and tokens
//type: single
//url: "/5.0/concepts/app-cred-token/"
//weight: 15
//menu:
//  5.0:
//    parent: "concepts"
//    identifier: "app-cred-token"
//canonical: https://docs.aporeto.com/saas/concepts/app-cred-token/
//
//'''

[#_app-credentials]
=== App credentials

Each Microsegmentation Console has its own private certificate authority (CA) capable of issuing X.509 certificates to authorized clients upon request.
It uses public-private key cryptography to ensure that private keys never travel the wire.
Authorized clients can use X.509 certificates issued by the Microsegmentation Console CA to access the Microsegmentation Console API.
We call these app credentials.
They allow the client:

* Access to the authorized namespace and its children
* Read-write permissions as per Microsegmentation role

App credentials expire ten years from the date of issuance.
They require a mutual TLS connection to the Microsegmentation Console.
TLS-intercepting https://tools.ietf.org/html/rfc3234[middleboxes] must be configured to exclude communications between the client and the Microsegmentation Console.

=== Microsegmentation tokens

The Microsegmentation Console also issues and accepts Microsegmentation tokens (https://jwt.io/[JSON web tokens]) for authentication.
You can set various restrictions such as limited permissions and short validity to reduce risk from man-in-the-middle attacks.
