== Cloud KMS cryptokey is anonymously or publicly accessible

=== Fix - Runtime


*GCP Console* 


To change the policy using the GCP Console, follow these steps:

. Log in to the https://console.cloud.google.com[GCP Console].

. Navigate to https://console.cloud.google.com/security/kms/keyrings[Key Management].

. On the *Key Rings* details page, select your _key ring_ where your cryptokey is stored.

. Select your cryptokey from the _Key ring details_ page.

. Expand the _Info Panel_ by selecting *Show Info Panel*.

. To remove a specific role assignment, select *allUsers* or *allAuthenticatedUsers*, and then click *Remove member*.


*CLI Command* 


To remove access to *allUsers* and *allAuthenticatedUsers*, use the following command:


[source,shell]
----
{
  "codes": [
    {
      "code": "gcloud kms keys remove-iam-policy-binding KEY-NAME \\
    --keyring KEY-RING \\
    --location LOCATION \\
    --member PRINCIPAL \\
    --role roles/ROLE-NAME",
      "language": "shell"
    }
  ]
}
----
Replace *KEY-NAME* with the name of the public cryptokey.
Replace *KEY-RING* with the name of the key ring.
Replace *LOCATION* with the location of the key ring.
Replace *PRINCIPAL* with either *allUsers* or *allAuthenticatedUsers* depending on your Checkov error.
Replace *ROLE-NAME* with the name of the role to remove.

=== Fix - Buildtime


*Terraform* 


* *Resources:* google_kms_crypto_key_iam_member
* *Field*: member
* *Resources:* google_kms_crypto_key_iam_binding
* *Field*: members


[source,go]
----
{
  "codes": [
    {
      "code": " //Option 1
resource "google_kms_crypto_key_iam_member" "crypto_key" {
  crypto_key_id = google_kms_crypto_key.key.id
  role          = "roles/cloudkms.cryptoKeyEncrypter"

-  member        = "allUsers"
-  member        = "allAuthenticatedUsers"
}

//Option 2
resource "google_kms_crypto_key_iam_binding" "crypto_key" {
  crypto_key_id = google_kms_crypto_key.key.id
  role          = "roles/cloudkms.cryptoKeyEncrypter"

  members = [
-    "allUsers",
-    "allAuthenticatedUsers"
  ]
}",
      "language": "go"
    }
  ]
}
----
