== Sign up

//'''
//
//title: Sign up
//type: single
//url: "/saas/start/sign-up/"
//weight: 10
//menu:
//  saas:
//    parent: "start"
//saas-only: true
//
//'''

Prisma Cloud offers Microsegmentation in limited general availability (GA).
Some customers have it enabled by default, others must request it from their sales representative.

Once enabled for your tenant, you can activate Microsegmentation as follows.

. Click *Subscription* at the bottom of the left navigation menu.
. Select *Microsegmentation* under *Add-On Features* and click *Learn More*.
. Click *Try Now* to begin your free thirty-day trial.
. A new *Microsegmentation* option appears in the left navigation menu.
Expand *Microsegmentation* to explore the web interface.

[NOTE]
====
If you connect to the network through a https://tools.ietf.org/html/rfc3234[middlebox], such as a proxy or firewall, you may need to add `+*.network.prismacloud.io+` and `+*.aporeto.com+` to its allow list.
====

Users in the *System Admin* permission group have full privileges in all Microsegmentation namespaces.
Other users can view the *Microsegmentation* menu, but have no ability to make any changes.
To enable users not in the *System Admin* permission group to perform actions in Microsegmentation, refer to link:../configure/users.adoc[Add users].
