== NPM package lock file verifies integrity with weak hash algorithm (BitBucket)

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|d33fddc8-aeb0-4f41-8ab6-6099b68ddd50 

|Severity
|Low
// add severity level

|Category
|Dependency Chains
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Bitbucket

|=== 


=== Description 

Old versions of **package-lock.json** files that use _SHA-1_ to verify the integrity of downloaded dependencies are vulnerable to collision attacks in which two inputs can produce the same output, meaning that attackers can create a malicious package with the same hash of a legitimate package, bypassing the integrity validation.  

An attacker who has gained access to a maintainer account could manipulate or trick a pipeline that uses **npm ci** to securely install a package and verify the dependencies’ integrity by replacing a legitimate package with a malicious version that has the same hash, thereby introducing malicious code which could potentially reach production.

NOTE: Due to vulnerabilities, SHA-1 was deprecated by NIST in 2011 by NIST.

=== Recommended Solution - Buildtime

Update the SHA-1 hash to SHA-512 in the package-lock.json file:

 

. Open the local repository.
. Ensure npm CLI is updated to the latest version: run `+npm install -g npm@latest+`.
. Delete the **node_modules** folder (if it exists).
. Delete the **package-lock.json** file.
. Run `npm i`.
