== Pull request reviews in BitBucket not required before merging code to default branch 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|4720540d-7c36-4456-a782-1e0c2be13663 

|Severity
|Medium
// add severity level

|Category
|Flow Control Mechanisms
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Bitbucket

|=== 

=== Description 

Compromised user accounts with **write** permissions on an actively used repository^*^ can directly push and merge code to the default branch without requiring pull request reviews, allowing malicious code to flow through the pipeline to production systems.

^*^An actively used repository has at least two contributors, over 50 commits, and was updated in the last 90 days.

=== Recommended Solution - Buildtime

We recommend preventing the option to directly push code to the default branch by requiring pull request approvals, ensuring that the code is reviewed before merging:
 
. Open the default branch settings editor: Select repository **Settings** > **Branch permissions** > edit the rule that applies to the default branch.

. Configure the following rules: 

.. Check the **Check for at least [1] approval** box. Recommended: set more than 1 approval.

.. Check the **Prevent a merge with unresolved risks** box.


