== Defense Information Systems Agency (DISA) STIG Support for Prisma Cloud Compute Edition

Security Technical Implementation Guides (STIGs) contain technical guidance on how to lock down systems that might otherwise be vulnerable to attack. This document provides the different options for deploying and operating Prisma Cloud Compute Edition (self-hosted) within environments that adhere to public-sector and Department of Defense guidance.

=== DISA STIG: Application Security and Development Findings

Prisma Cloud Compute has been assessed to the https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=app-security%2Capp-security-dev[Application Security and Development Security Technical Implementation Guide Version 4, Release: 11 Benchmark Date: 24 Jul 2020].

The findings based upon the vulnerability severity category codes can be found xref:STIG_ASD_v4_r11/STIG_ASD_v4_r11.adoc[here].

=== DISA STIG Scan Findings and Justifications for Software Releases

Every release of Prisma Cloud Compute Edition we perform an https://csrc.nist.gov/projects/security-content-automation-protocol/[SCAP] scan of the Console and Defender images.
The scan is performed with https://www.open-scap.org/[OpenSCAP] using the https://github.com/ComplianceAsCode[Compliance as Code] benchmark checks:

- Benchmark URL: scap-security-guide-<latest>/ssg-rhel8-ds.xml
- Benchmark ID: xccdf_org.ssgproject.content_benchmark_RHEL-8
- Profile ID: xccdf_org.ssgproject.content_profile_stig

All Prisma Cloud Compute findings are posted xref:../Release_Findings/Release_Findings.adoc[here.]

=== DISA STIG Compliance Template
Release v21_04_412 include the Docker Enterprise 2.x Linux/UNIX STIG compliance checks into the https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-04/prisma-cloud-compute-edition-admin/compliance/disa_stig_docker_enterprise.html[“DISA STIG” compliance template.]
When you create a new compliance policy and select the DISA STIG compliance template, you will automatically receive alerts based on the checks aligned with the STIG.
The mapping of the STIG_ID to Prisma Cloud Compute Compliance Check ID can be found xref:DISA_STIG_Compliance_Template/mapping.adoc[here].

=== DISA STIG for Prisma Cloud Compute (self-hosted)

The Defense Information Systems Agency has released the Prisma Cloud Compute STIG.
This STIG provides guidance for the configuration and operation of Prisma Cloud Compute (self-hosted).
It includes technical recommendations for deployment within isolated environments.
The Prisma Cloud Compute STIG can be downloaded from the https://cyber.mil/stigs/downloads/[DoD Cyber Exchange website].
