== Ensure MFA is enabled for root account
Bridgecrew
Prisma Cloud
*MFA is not enabled for root account* 



=== Description 


The Root Account is the most privileged user in an AWS account.
Multi-Factor Authentication (MFA) provides increased security to a user name and password.
Users must possess a registered device that emits a time-sensitive key and have knowledge of a credential to authenticate successfully.
When a user with MFA enabled signs in to an AWS website, they will be prompted for their user name, password and an authentication code from their AWS MFA device.
We recommend enabling MFA for the Root Account.

[NOTE]
====
When virtual MFA is used for a Root Account, we recommended that the device used is NOT a personal device, but rather a dedicated mobile device (tablet or phone) that is managed, kept charged and secured independently of any individual personal devices. This is known as a non-personal virtual MFA.
 This reduces the risk of losing access to the MFA due to device loss, device trade-in or if the individual owning the device is no longer employed at the company.
====

=== Fix - Runtime


*AWS Console* 


To establish MFA for the root account, follow these steps:

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the *https://console.aws.amazon.com/IAM/[Amazon IAM console]*.

. Select *Dashboard* and under *Security Status* on your *root account* expand *Activate MFA*.

. Select *Activate MFA*.

. In the wizard, select a virtual MFA device, then select *Next Step*.

. IAM generates and displays configuration information for the virtual MFA device, including a QR code graphic.
+
The graphic is a representation of the *secret configuration key*, available for manual entry on devices that do not support QR codes.

. Open your virtual MFA application.
+
See *Virtual MFA Applications* for a list of apps that you can use for hosting virtual MFA devices.
+
If the virtual MFA application supports multiple accounts (multiple virtual MFA devices), select the option to create a new account (a new virtual MFA device).

. Determine whether the MFA app supports QR codes, then do one of the following.
+
a) Use the app to scan the QR code.
+
For example, you might choose the camera icon or choose an option similar to Scan code, and then use the device's camera to scan the code.
+
b) In the *Manage MFA Device **wizard, select **Show secret key for manual configuration*, then enter the *secret configuration key* into your MFA application.

. The virtual MFA device starts generating one-time passwords.
+
a) In the *Manage MFA Device **wizard **Authentication Code 1* box, enter the one-time password that currently appears in the virtual MFA device.
+
b) Wait up to 30 seconds for the device to generate a new one-time password.
+
c) In the *Authentication Code 2* box, enter the second one-time password.
+
d) Select *Active Virtual MFA*.
