== Agentless Scanning

Agentless scanning lets you inspect the risks and vulnerabilities of a cloud workloads without having to install an agent or affecting the execution of your workload.
Prisma Cloud gives you the flexibility to choose between agentless and agent-based security using Defenders.
Prisma Cloud supports agentless scanning cloud workloads on AWS, Azure, GCP, and OCI for vulnerabilities and compliance.

In AWS, Azure, and GCP you can also use agentless scanning for container images as well as xref:../vulnerability_management/serverless_functions.adoc[Serverless functions].

Continue reading this page to learn about the agentless scanning modes, architecture, and results.

Follow the in xref:./onboard-accounts/onboard-accounts.adoc[step-by-step instructions to configure agentless scanning] and start scanning your AWS, Azure, GCP, and OCI accounts for vulnerabilities and configuration risks with agentless scanning.

=== How Agentless Scanning Works

There are two ways you can set up agentless scanning with Prisma Cloud.

* Scan all hosts of a cloud account within the same cloud account, or
* Scan all hosts of a cloud account, called _target account_, from another dedicated cloud account, called _hub account_. 

[#scanning-modes]
=== Agentless Scanning Modes

==== Same Account Mode

Scan the workloads and container images of a cloud account using the same cloud account.
This mode spins up temporary scanning instances in the account.

ifdef::compute_edition[]
. xref:./onboard-accounts/onboard-accounts.adoc[Onboard cloud accounts] inside Prisma Cloud Compute with specific permissions required for agentless setup.
endif::compute_edition[]

ifdef::prisma_cloud[]
. xref:./onboard-accounts/onboard-accounts.adoc[Onboard your cloud account to Prisma Cloud].
endif::prisma_cloud[]

. Prisma Cloud lists instances in each account and creates snapshots for each instance.
. Prisma Cloud starts spot instances, called _scanners_, within the same account, attaches snapshots, and performs the analysis.
. Scanners send results to the Prisma Cloud Console.
. Scanners and snapshots created by Prisma Cloud are deleted.
. Process repeats for periodic scans.

==== Hub Account Mode

Scan the workloads and container images of a cloud account (the target) using another cloud account (the hub).
This mode spins up temporary scanning instances in the hub rather than in the target(s).

ifdef::compute_edition[]
. Onboard accounts with different permissions for hub account, which perform the scan, and target accounts, which the hub account scans. Follow the step-by-step instructions to xref:./onboard-accounts/onboard-accounts.adoc[configure the permissions].
endif::compute_edition[]

ifdef::prisma_cloud[]
. xref:./onboard-accounts/onboard-accounts.adoc[Onboard your cloud account to Prisma Cloud].
endif::prisma_cloud[]

. Prisma Cloud only spins up scanners in the dedicated hub account and attaches snapshots of instances from other accounts to the scanners in the hub account. 
. Scanners send results to the Prisma Cloud Console
. Scanners then get deleted along with the snapshots that Prisma Cloud creates.
. Process repeats for periodic scans.





