== Credentials exposure actions return credentials in an API response


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 010fa450-e1b9-4890-a14e-b6062e709a9f

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/data/aws/IAMCredentialsExposure.py[CKV_AWS_107]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


AWS IAM users access AWS resources using different types of credentials, such as passwords or access keys.
Credentials Exposure actions return credentials as part of the API response, such as ecr:GetAuthorizationToken, iam:UpdateAccessKey, and others.
For more info, visit cloudsplaning documentation https://cloudsplaining.readthedocs.io/en/latest/glossary/credentials-exposure/

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_iam_policy_document
* *Arguments:* effect + actions


[source,go]
----
data "aws_iam_policy_document" "example" {
  statement {
    sid = "1"
    effect = "Allow"
    actions = [
      "lambda:CreateFunction",
      "lambda:CreateEventSourceMapping",
      "dynamodb:CreateTable",
    ]
    resources = [
      "*",
    ]
  }
}
----


*CloudFormation* 


* *Resource:* AWS::IAM::Policy / AWS::IAM::ManagedPolicy / AWS::IAM::Group / AWS::IAM::Role / AWS::IAM::User
* *Arguments:* Effect + Actions


[source,yaml]
----
Resources:
  AdminDeny:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ...
      PolicyDocument:
        ...
        Statement:
          - Effect: Allow
            Action: 
            -   'lambda:CreateFunction'
                    -   'lambda:CreateEventSourceMapping'
                -   'dynamodb:CreateTable'
            Resource: '*'
----
