== Search and Investigate 

Your cloud security teams perform in-depth analysis and investigation of security issues within your cloud applications and infrastructure. Using *Investigate* you can get answers to questions related to security risks and incidents from *Code to Cloud* with a simple and intuitive point-and-click interface that is powered by a Natural Language Processing (NLP) engine. The keyword search provides a curated list of results with rich visualization. You can then drill down the results to explore data, modify and save the query, create custom policies and receive alerts within minutes of a policy violation.

//check if 'NLP' needs to be replaced with 'Keyword'
//search-and-investigate.gif

Use *Investigate > Search* to find the latest security incidents identified in your cloud environment and explore what risk factors could have contributed to the incident, for example:

* Which are the EC2 instances that have risky ports open to the internet, have overly permissive IAM permissions, and contain critical vulnerabilities?
* Are there any S3 buckets with encryption disabled?
* Are there any virtual machines that are directly accessible from the internet?
* Which cloud resources have exploitable vulnerabilities that need to be patched?
* Which assets in your cloud environment are impacted by the latest log5j vulnerability?


[cols="30%a,70%a"]
|===
|*What do you want to do?*
|*Start here*

|Launch your query and search using natural language 
|xref:launch-your-query.adoc[Launch Your Query]

|Review query types
|xref:query-types.adoc[Query Types]

|Build and modify your query using simple or advanced modes
|xref:build-modify-queries.adoc[Build and Modify Queries]

|Explore data and findings in graph and table views and create custom policies
|xref:explore-data.adoc[Explore Data and Create Custom Policies]

|Save your query for future use after exploring data and run background jobs
|xref:query-library.adoc[Query Library and Background Jobs]

|What's next? 

Review attributes and examples for the query types using advanced mode
|* xref:asset-queries/asset-queries.adoc[Asset]
* xref:asset-config-queries/asset-config-queries.adoc[Asset Configuration]
* xref:application-asset-queries/application-asset-queries.adoc[Application Asset]
* xref:vulnerability-queries/vulnerability-queries.adoc[Vulnerability]
//[Application=AppDNA?]
* xref:permissions-queries/permissions-queries.adoc[Permissions]
* xref:network-queries/network-config-queries.adoc[Network Configuration]
* xref:network-queries/network-flow-queries.adoc[Network]
* xref:audit-event-queries/audit-event-queries.adoc[Audit Event]

* Built a query you think would be useful to other customers?
Contribute using *Edit on Github* link provided on each page!

|===