== Features Introduced in November 2023

Learn what's new on Prisma® Cloud in November 2023.

[#new-features-nov]
=== New Features Introduced in November 2023

* <<announcement>>
* <<new-features>>
* <<api-ingestions>>
* <<new-policies>>
* <<policy-updates>>
* <<new-compliance-benchmarks-and-updates>>
* <<changes-in-existing-behavior>>
* <<rest-api-updates>>
//* <<deprecation-notices>>


[#announcement]
=== Announcement

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Prisma Cloud Darwin Release*
//received the blurb on Slack from Matangi. No Jira ticket for this.
 
|The *Prisma Cloud Darwin Release* is here for Prisma Cloud environments on app.ind, app.ca, app.uk, and app.fr except app.gov. With the  Code to Cloud™ intelligence capabilities in this release, your security and development teams can work together to reduce application risks and prevent breaches.

With this change, your tenant will be updated with the new intuitive user interface and https://live.paloaltonetworks.com/t5/prisma-cloud-customer-videos/prisma-cloud-evolution-amp-transformation/ta-p/556596[rich set of security capabilities]. 

Connect with your Customer Success team for more details.

When you are upgraded to the Darwin release, refer to the https://docs.prismacloud.io/en/enterprise-edition/content-collections/[Enterprise Edition documentation].

|===


[#new-features]
=== New Features

New Attack Path policies are available. Log in to the Prisma Cloud console and filter for the list of available policies.

[#api-ingestions]
=== API Ingestions

[cols="50%a,50%a"]
|===
|SERVICE
|API DETAILS

|*Amazon EC2*

tt:[23.11.1]

//RLP-117703
|*aws-ec2-launch-template-data*

Additional permissions required:

* `ec2:GetLaunchTemplateData`
* `ec2:DescribeInstances`

The Security Audit role only includes the `ec2:DescribeInstances` permission. You must manually add the `ec2:GetLaunchTemplateData` permission to the CFT template to enable the permission.

|*AWS Audit Manager*

tt:[23.11.1]

//RLP-117743
|*aws-audit-manager-assessment*

Additional permissions required:

* `auditmanager:ListAssessments`
* `auditmanager:GetAssessment`

The Security Audit role only includes the `auditmanager:ListAssessments` permission. You must manually add the `auditmanager:GetAssessment` permission to the CFT template to enable the permission.

|*AWS Audit Manager*

tt:[23.11.1]

//RLP-117712
|*aws-audit-manager-control*

Additional permissions required:

* `auditmanager:ListControls`
* `auditmanager:GetControl`

The Security Audit role only includes the `auditmanager:ListControls` permission. You must manually add the `auditmanager:GetControl` permission to the CFT template to enable the permission.

|*AWS Application Migration Service*

tt:[23.11.1]

//RLP-117706
|*aws-mgn-launch-configuration-template*

Additional permission required:

* `mgn:DescribeLaunchConfigurationTemplates`

You must manually add the `mgn:DescribeLaunchConfigurationTemplates` permission to the CFT template to enable the permission.

|tt:[Update] *Azure Key Vault*

tt:[23.11.1]

//RLP-116796

|*azure-key-vault-list*

This API has been updated to support Key rotation data. The resource JSON for this API has been updated to include the `keys[*].keyRotationPolicy` field.

|*Azure Synapse Analytics*

tt:[23.11.1]

//RLP-117493
|*azure-synapse-workspace-managed-sql-server-blob-auditing-policies*

Additional permissions required:

* `Microsoft.Synapse/workspaces/read`
* `Microsoft.Synapse/workspaces/auditingSettings/read`

The Reader role includes the permissions.

|*Azure Synapse Analytics*

tt:[23.11.1]

//RLP-115881
|*azure-synapse-workspace-ip-firewall-rules*

Additional permissions required:

* `Microsoft.Synapse/workspaces/read`
* `Microsoft.Synapse/workspaces/firewallRules/read`

The Reader role includes the permissions.


|*Google AlloyDB for PostgreSQL*

tt:[23.11.1]

//RLP-117228
|*gcloud-alloydb-cluster*

Additional permissions required:

* `alloydb.locations.list`
* `alloydb.clusters.list`

The Viewer role includes the permissions.

|*Google AlloyDB for PostgreSQL*

tt:[23.11.1]

//RLP-117227
|*gcloud-alloydb-cluster-user*

Additional permissions required:

* `alloydb.locations.list`
* `alloydb.clusters.list`
* `alloydb.users.list`

The Viewer role includes the permissions.

|*Google AlloyDB for PostgreSQL*

tt:[23.11.1]

//RLP-117226
|*gcloud-alloydb-cluster-instance*

Additional permissions required:

* `alloydb.locations.list`
* `alloydb.clusters.list`
* `alloydb.instances.list`

The Viewer role includes the permissions.

|*Google AlloyDB for PostgreSQL*

tt:[23.11.1]

//RLP-117225
|*gcloud-alloydb-backup*

Additional permissions required:

* `alloydb.locations.list`
* `alloydb.backups.list`

The Viewer role includes the permissions.

|*OCI Cloud Guard*

tt:[23.11.1]

//RLP-117502
|*oci-cloudguard-configuration*

Additional permissions required:

* `CG_CONFIG_INSPECT`
* `CG_CONFIG_READ`

You must update the Terraform template to enable the permissions.

|===

[#new-policies]
=== New Policies

[cols="50%a,50%a"]
|===
|NEW POLICIES
|DESCRIPTION

|*AWS EC2 instance that is internet reachable with unrestricted access (0.0.0.0/0) on ports 80/443*

tt:[23.11.1]

//RLP-119529
|Identifies AWS EC2 instances that are internet reachable with unrestricted access (0.0.0.0/0) to HTTP/HTTPS ports (80 / 443). EC2 instances with unrestricted access to the internet for HTTP/HTTPS ports may enable bad actors to use brute force on a system to gain unauthorized access to the entire network. As a best practice, restrict traffic from unknown IP addresses and limit access to known hosts, services, or specific entities.

*Policy Type—* Network Configuration

*Policy Severity—* Informational

----
config from network where source.network = '0.0.0.0/0' and address.match.criteria = 'full_match' and dest.resource.type = 'Instance' and dest.cloud.type = 'AWS' and protocol.ports in ( 'tcp/80' , 'tcp/443' )
----

|*Azure Virtual Machine that is internet reachable with unrestricted access (0.0.0.0/0) on ports 80/443*

tt:[23.11.1]

//RLP-119531
|Identifies Azure Virtual Machines that are internet reachable with unrestricted access (0.0.0.0/0) to HTTP/HTTPS ports (80 / 443). Azure Virtual Machines with unrestricted access to the internet for HTTP/HTTPS ports may enable bad actors to use brute force on a system to gain unauthorized access to the entire network. As a best practice, restrict traffic from unknown IP addresses and limit access to known hosts, services, or specific entities.

*Policy Type—* Network Configuration

*Policy Severity—* Informational

----
config from network where source.network = '0.0.0.0/0' and address.match.criteria = 'full_match' and dest.resource.type = 'Instance' and dest.cloud.type = 'AZURE' and protocol.ports in ( 'tcp/80' , 'tcp/443' )
----

|*Azure Virtual Machine (Linux) does not authenticate using SSH keys*

tt:[23.11.1]

//RLP-118461
|Identifies Azure Virtual Machines that have basic authentication, not authenticating using SSH keys. Azure Virtual Machines with basic authentication could allow attackers to brute force and gain unauthorized access, which might lead to potential data leaks. It is recommended to use SSH keys for authentication to avoid brute force attacks on virtual machines.

*Policy Type—* Config

*Policy Severity—* Low

----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-vm-list' AND json.rule = powerState equal ignore case "PowerState/running" and (['properties.osProfile'].['linuxConfiguration'] exists and ['properties.osProfile'].['linuxConfiguration'].['disablePasswordAuthentication'] is false) 
----


|*GCP VM instance that is internet reachable with unrestricted access (0.0.0.0/0) on ports 80/443*

tt:[23.11.1]

//RLP-119530
|Identifies GCP VM instances that are internet reachable with unrestricted access (0.0.0.0/0) to HTTP/HTTPS ports (80 / 443). GCP VM instances with unrestricted access to the internet for HTTP/HTTPS ports may enable bad actors to use brute force on a system to gain unauthorized access to the entire network. As a best practice, restrict traffic from unknown IP addresses and limit access to known hosts, services, or specific entities.

*Policy Type—* Network Configuration

*Policy Severity—* Informational

----
config from network where source.network = '0.0.0.0/0' and address.match.criteria = 'full_match' and dest.resource.type = 'Instance' and dest.cloud.type = 'GCP' and protocol.ports in ( 'tcp/80' , 'tcp/443' )
----

|===


[#policy-updates]
=== Policy Updates

[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION

2+|*Policy Updates—RQL*

|*Azure Application Gateway is configured with SSL policy having TLS version 1.1 or lower*

tt:[23.11.1]

//RLP-115351
|*Changes—* The RQL willl be updated to not report Application gateways with default policy created using API versions 2023-02-01 or higher as the minimum protocol version is set to 1.2.

*Current RQL—*

----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-application-gateway' AND json.rule = ['properties.sslPolicy'] does not exist or (['properties.sslPolicy'].['policyType'] equal ignore case Predefined and (['properties.sslPolicy'].['policyName'] equal ignore case AppGwSslPolicy20150501 or ['properties.sslPolicy'].['policyName'] equal ignore case AppGwSslPolicy20170401)) or (['properties.sslPolicy'].['policyType'] equal ignore case Custom and (['properties.sslPolicy'].['minProtocolVersion'] equal ignore case TLSv1_0 or ['properties.sslPolicy'].['minProtocolVersion'] equal ignore case TLSv1_1))
----

*Updated RQL—*

----
config from cloud.resource where cloud.type = 'azure' AND api.name = 'azure-application-gateway' AND json.rule = (['properties.sslPolicy'] does not exist and ['properties.defaultPredefinedSslPolicy'] does not equal ignore case AppGwSslPolicy20220101) or (['properties.sslPolicy'].['policyType'] equal ignore case Predefined and (['properties.sslPolicy'].['policyName'] equal ignore case AppGwSslPolicy20150501 or ['properties.sslPolicy'].['policyName'] equal ignore case AppGwSslPolicy20170401)) or (['properties.sslPolicy'].['policyType'] equal ignore case Custom and (['properties.sslPolicy'].['minProtocolVersion'] equal ignore case TLSv1_0 or ['properties.sslPolicy'].['minProtocolVersion'] equal ignore case TLSv1_1))
----

*Severity—* Low

*Policy Type—* Config

*Impact—* Low. Existing alerts where the application gateways were created with default policy using API versions 2023-02-01 or higher will be resolved as *Policy_Updated*.


|===

[#new-compliance-benchmarks-and-updates]
=== New Compliance Benchmarks and Updates

[cols="50%a,50%a"]
|===
|COMPLIANCE BENCHMARK
|DESCRIPTION

|*Support for CMMC v2 Level 2 standard*

tt:[23.11.1]

//RLP-109609
|Prisma Cloud now supports the Cybersecurity Maturity Model Certification (CMMC) v2 Level 2 compliance standard. This framework includes cybersecurity practices, standards, and processes published by the Department of Defense (DoD) as part of the CMMC program, which aims to protect national security by standardizing how Defense contractors and subcontractors handle Federal Contract Information (FCI) and Controlled Unclassified Information (CUI).

You can now view this built-in standard and the associated policies on the *Compliance > Standards* page with this support. You can also generate reports for immediate viewing or download, or schedule recurring reports to track this compliance standard over time.

|===

[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

| *Checkov CLI upgrade*

tt:[Secure the Source]

tt:[23.11.1]

//RLP-112353
| The Checkov CLI has been upgraded to Checkov 3.0. The upgrade impacts a few known changes:

* *Level Up*: This capability has been removed. This change is non-disruptive and affects only Bridgecrew standalone sign ups.
* *Multi-Signatures*: Multi-signatures in Python checks are being removed. This will only impact custom Python policies using this method.
* *Deprecating flags for Suppression and Fix*: CLI command of `--skip-fixes` and `--skip-suppressions` are being deprecated. Instead `--skip-download` is a recommended command.
* *API Key Restriction and Repo-ID Parameter*: Scans with  API keys will now require the --repo-id parameter for repository scans allowing for easier platform mapping.
* *Enhanced Argument Handling*: The way to specify frameworks and skip frameworks will align to other flags where multiple values can be listed (like --check). For example: `--framework terraform,arm`..
* *Pyston Docker Build Deprecation*: The Pyston Docker build has been depreciated due to increasing complexities in support. The regular Checkov image will still be available for use.

|===

[#rest-api-updates]
=== REST API Updates

[cols="37%a,63%a"]
|===
|CHANGE
|DESCRIPTION

|*New SSO APIs*

tt:[23.11.1]

//RLP-119318

|The following new endpoints are available for configuring SAML:

* Get SAML Configuration - https://pan.dev/prisma-cloud/api/cspm/get-saml-config/[GET /authn/v1/saml/config]
* Update SAML Configuration - https://pan.dev/prisma-cloud/api/cspm/update-saml-config/[PUT /authn/v1/saml/config]
* Create SAML Configuration -  https://pan.dev/prisma-cloud/api/cspm/create-saml-config/[POST /authn/v1/saml/config]


|*New Cloud Account API*

tt:[23.11.1]

//RLP-119223

|The following new endpoint is available to enable or disable a feature for a set of members of an organization:

* Enable a Feature for Members - https://pan.dev/prisma-cloud/api/cspm/save-bulk-cloud-account-feature/[PUT /cas/api/v1/org/{id}/features]

|*New Alerts APIs*

tt:[23.11.1]

//RLP-108851

|The following new endpoints are available for the Alerts API:

* Get Alert Count of Policies - https://pan.dev/prisma-cloud/api/cspm/alert-policy-list/[POST /alert/v1/policy]
* Get Alert Count by Policy Groups - https://pan.dev/prisma-cloud/api/cspm/alert-aggregation/[POST /alert/v1/aggregate]
* Get Alert Evidence Graph -  https://pan.dev/prisma-cloud/api/cspm/get-alert-evidence-graph/[GET /alert/v1/{id}/graph]

|*Updates to Alerts API*

tt:[23.11.1]

//RLP-113035

|The https://pan.dev/prisma-cloud/api/cspm/get-alerts-remediation/[List Alert Remediation Commands] API and https://pan.dev/prisma-cloud/api/cspm/perform-remediation-for-alert/[Remediate Alert] API will have an additional optional parameter, `findingId`. This parameter is used to remediate the findings of an attack path alert. 

|===

