== Features Introduced in December 2023
// @Divya and @Rodrigo need to add their issues that are in docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-december-2023.adoc to this file as well. 

Learn what's new on Prisma® Cloud in December 2023.

[#new-features-nov]
=== New Features Introduced in December 2023

* <<announcement>>
* <<new-features>>
* <<api-ingestions>>
* <<new-policies>>
* <<policy-updates>>
* <<new-compliance-benchmarks-and-updates>>
* <<changes-in-existing-behavior>>
* <<rest-api-updates>>
* <<deprecation-notices>>
* <<end-of-support>>


[#announcement]
=== Announcement

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Prisma Cloud Darwin Release*
//received the blurb on Slack from Matangi. No Jira ticket for this.
 
|The *Prisma Cloud Darwin Release* is here for Prisma Cloud environments on app, app3, app.eu, app2.eu except app.gov. With the Code to Cloud™ intelligence capabilities in this release, your security and development teams can work together to reduce application risks and prevent breaches.

With this change, your tenant will be updated with the new intuitive user interface and https://live.paloaltonetworks.com/t5/prisma-cloud-customer-videos/prisma-cloud-evolution-amp-transformation/ta-p/556596[rich set of security capabilities]. 

Connect with your Customer Success team for more details.

When you are upgraded to the Darwin release, refer to the https://docs.prismacloud.io/en/enterprise-edition/content-collections/[Enterprise Edition documentation].

|===


[#new-features]
=== New Features

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*IAM Policy Scanner Enhancement*

tt:[*_Secure the Infrastructure_*]

tt:[*23.12.1*]

//RLP-123079

|IAM Policy Scanner now includes enhancements to improve alert accuracy. This may result in some alerts briefly closing and reopening. 

|===

[#api-ingestions]
=== API Ingestions

The 23.12.1 release does not include any API Ingestions.


[#new-policies]
=== New Policies

[cols="50%a,50%a"]
|===

|NEW POLICIES
|DESCRIPTION

| *New Policies to Configuration Build Policies*
|Starting from this release 2 new policies are added to Config policies of subtype Build. 
Here are the policies:

* AWS CloudFront attached WAFv2 WebACL is not configured with AMR for Log4j Vulnerability
* Software Composition Analysis (SCA) findings

In addition, 6 new policies integrated with CI/CD Risks are added by default to Prisma Cloud console and visible Governance.

* BitBucket private repository made public.
* Unrotated organization secrets in GitHub Actions.
* Unrotated repository secrets in GitHub Actions.
* CircleCI pipeline uses an unpinned container image.
* Azure Pipelines uses an unpinned container image.
* Secrets found in logs of a GitLab CI pipeline.

*Impact*- Impact- You will view policy violations for these policies on Prisma Cloud switcher  *Application Security > Projects* in CI/CD Risks with CI/CD module enabled on *Application Security > Settings*.

| *Azure Virtual Machine (Linux) does not authenticate using the SSH keys*
|*Changes* - The policy name is being updated to reflect the latest changes. 

*Current Policy Name* - Azure instance does not authenticate using the SSH keys

*Impact*- No impact on alerts.


|===

[#policy-updates]
=== Policy Updates


[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION

// 2+|*Policy Updates—RQL*

|*Enhancements to Terraform GitHub and GitLab policies for Configuration Build Policies*
|*Changes* - The policy name is being updated to reflect the latest changes. 

*Current Policy Name* -
* GitHub Actions Environment Secrets not Encrypted
* GitHub repository doesn't have vulnerabilities alerts enabled
* Gitlab project commits are not signed
* Gitlab project does not prevent secrets
* Gitlab project has less than 2 approvals

*Impact*- No impact on alerts.

|*New domain for Application Security Policy Reference Guide*
|*Changes* - Starting from this release all policy documentation will be available on https://docs.prismacloud.io/en/enterprise-edition/policy-reference[Prisma Cloud Application Security Policy Reference].

*Impact*- No impact on alerts.

|*Azure Virtual Machine (Linux) does not authenticate using the SSH keys*

| *Changes* - The policy name is being updated to reflect the latest changes.

*Current Policy Name* - Azure instance does not authenticate using the SSH keys

*Impact*- No impact on alerts.

2+|*Policy Deletions*

|*Docker GitHub repository is not private*

|*Changes* - This policy is deleted because the GitHub policies are modified in GitHub Policies.

*Impact* - No impact on alerts.

|===

=== IAM Policy Updates

The following IAM out-of-the-box (OOTB) policies are updated in Prisma Cloud:
//RLP-120492

[cols="30%a,35%a,35%a"]
|===

|POLICY NAME
|Current RQL
|Updated RQL

|*Azure VM instance associated managed identity with Azure built-in roles of Contributor/Owner permissions*

|*Changes—* The policy name will be updated.

*Current Name—* Azure VM instance associated managed identity with Azure built-in roles of Contributor/Owner permissions

*Updated Name—* Azure VM instance associated managed identity with Azure built-in roles of Owner permissions

|NA


|*AWS IAM policy allows Privilege escalation via PassRole & CodeBuild permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codebuild:CreateProject', 'codebuild:StartBuild', 'codebuild:StartBuildBatch') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codebuild:CreateProject', 'codebuild:StartBuild', 'codebuild:StartBuildBatch') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & CodeStar project permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codestar:CreateProject' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'codestar:CreateProject' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Data Pipeline permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'datapipeline:ActivatePipeline', 'datapipeline:CreatePipeline', 'datapipeline:PutPipelineDefinition') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'datapipeline:ActivatePipeline', 'datapipeline:CreatePipeline', 'datapipeline:PutPipelineDefinition') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & EC2 permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'ec2:RunInstances' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'ec2:RunInstances' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Glue create job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Glue development endpoint permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateDevEndpoint', 'glue:GetDevEndpoint') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:CreateDevEndpoint', 'glue:GetDevEndpoint') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Glue update job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:UpdateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'glue:UpdateJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Lambda create & invoke Function permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:InvokeFunction', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:InvokeFunction', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Lambda create Function & Event source mapping permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:CreateEventSourceMapping', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:CreateEventSourceMapping', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & Lambda create Function & add permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:AddPermission', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'lambda:AddPermission', 'lambda:CreateFunction') AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & SageMaker create processing job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateProcessingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateProcessingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|*AWS IAM policy allows Privilege escalation via PassRole & SageMaker create training job permissions*

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateTrainingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist 
---- 

|----
config from iam where action.name CONTAINS ALL ( 'iam:PassRole', 'sagemaker:CreateTrainingJob' ) AND dest.cloud.wildcardscope = true and grantedby.cloud.policy.condition ('iam:PassedToService') does not exist and source.cloud.resource.id DOES NOT END WITH ':root'
----

|===

[#new-compliance-benchmarks-and-updates]
=== New Compliance Benchmarks and Updates

[cols="50%a,50%a"]
|===
|COMPLIANCE BENCHMARK
|DESCRIPTION

|*Support for MITRE ATT&CK Cloud IaaS v13 & v14*

tt:[23.12.1]

//RLP-121584, RLP-120363

|Prisma Cloud now supports the MITRE ATT&CK Cloud IaaS v13 & v14 compliance standard. This framework includes Att&ck Tactics, Techniques and sub-techniques that attackers can leverage to compromise cloud applications and infrastructure.

You can now view this built-in standard and the associated policies on the *Compliance > Standards* page. You can also generate reports for immediate viewing or download, or schedule recurring reports to track this compliance standard over time.

|===

[#changes-in-existing-behavior]
=== Changes in Existing Behavior

[cols="50%a,50%a"]
|===
|FEATURE
|DESCRIPTION

|*Checkov update for SCA Security scanning*

tt:[Secure the Source]

tt:[23.12.1]

//RLP-112353
|Ensure Checkov or Bridgecrew CLI is updated to version 2.2.234 or later. Support for earlier versions is no longer supported.

| *Checkov CLI upgrade*

tt:[Secure the Source]

tt:[23.12.1]

//RLP-112353
| The Checkov CLI has been upgraded to Checkov 3.0. The upgrade impacts a few known changes:

* *Level Up*: This capability has been removed. This change is non-disruptive and affects only Bridgecrew standalone sign ups.
* *Multi-Signatures*: Multi-signatures in Python checks are being removed. This will only impact custom Python policies using this method.
* *Deprecating flags for Suppression and Fix*: CLI command of `--skip-fixes` and `--skip-suppressions` are being deprecated. Instead `--skip-download` is a recommended command.
* *API Key Restriction and Repo-ID Parameter*: Scans with  API keys will now require the --repo-id parameter for repository scans allowing for easier platform mapping.
* *Enhanced Argument Handling*: The way to specify frameworks and skip frameworks will align to other flags where multiple values can be listed (like --check). For example: `--framework terraform,arm`..
* *Pyston Docker Build Deprecation*: The Pyston Docker build has been depreciated due to increasing complexities in support. The regular Checkov image will still be available for use.

|===

[#rest-api-updates]
=== REST API Updates

[cols="37%a,63%a"]
|===
|CHANGE
|DESCRIPTION

|*Compliance Posture APIs*

tt:[23.12.1]

//RLP-120514

|The following new endpoints are available for the Compliance Posture API:

* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-v-2/[get /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-v-2/[post /v2/compliance/posture]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-v-2/[get /v2/compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-v-2/[post /compliance/posture/trend]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-standard-v-2/[get /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-standard-v-2/[post /v2/compliance/posture/trend/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-trend-for-requirement-v-2/[get /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-trend-for-requirement-v-2/[post /v2/compliance/posture/trend/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-standard-v-2/[get /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-standard-v-2/[post /v2/compliance/posture/{complianceId}]
* https://pan.dev/prisma-cloud/api/cspm/get-compliance-posture-for-requirement-v-2/[get /v2/compliance/posture/{complianceId}/{requirementId}]
* https://pan.dev/prisma-cloud/api/cspm/post-compliance-posture-for-requirement-v-2/[post /v2/compliance/posture/{complianceId}/{requirementId}]

|*Asset Explorer and Reports APIs*

tt:[23.12.1]

//RLP-120514

|The following new endpoints are available for the Asset Explorer and Reports API:

* https://pan.dev/prisma-cloud/api/cspm/save-report-v-2/[post /v2/report]
* https://pan.dev/prisma-cloud/api/cspm/get-resource-scan-info-v-2/[get /v2/resource/scan_info]
* https://pan.dev/prisma-cloud/api/cspm/post-resource-scan-info-v-2/[post /v2/resource/scan_info]

|*Asset Inventory APIs*

tt:[23.12.1]

//RLP-120514

|The following new endpoints are available for the AAsset Inventory APIs:

* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-v-3/[get /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/post-method-for-asset-inventory-v-3/[post /v3/inventory]
* https://pan.dev/prisma-cloud/api/cspm/asset-inventory-trend-v-3/[get /v3/inventory/trend]
* https://pan.dev/prisma-cloud/api/cspm/post-method-asset-inventory-trend-v-3/[post /v3/inventory/trend]

|===

[#deprecation-notices]
=== Deprecation Notices
[cols="30%a,70%a"]
|===
//CWP-48467
|Deprecate the `aggregated` and `rest` fields 
|The `aggregated` and `rest` macros from the webhook custom JSON alerts are being deprecated and replaced by `AggregatedAlerts` and `Dropped` macros respectively.

//CWP-40710
|Deprecate `AccountID` macro from the Alerts payload
to be verified by PM
|The `AccountID` macro in the Alerts payload is deprecated and replaced by the `AccountIDs` macro.

|===

[#end-of-support]
=== End of Support Notifications
[cols="40%a,60%a"]
|===
//CWP-49461
|Support for Cloud Native Network Segmentation (CNNS)
|The ability to create CNNS policies that Defenders use to limit traffic from containers and hosts is being removed. The configuration settings on the console (*Runtime Security > Defend > CNNS*) and the corresponding APIs for CNNS will be removed in `v32.00`.
Radar has a container and a host view, where you can view the network topology for your containerized apps and hosts respectively, and this will continue to be available.

|===