== Overview

This section contains guidance for the implementation of Prisma Cloud Compute in public-sector organizations.
Please check up on this site as guidance may change over time.


== Document revisions

[cols="1,3", options="header"]
|===
|Date
|Comment

|20201012
|Initial release of this guidance

|20210209
|xref:../Release_STIG_Findings/release_stig.adoc[DISA STIG scan findings and justifications for every release]

|20210401
|xref:../isolated_upgrades/isolated_upgrades.adoc[Upgrade process for deployments within isolated environment in which only the images were provided]

|20210412
|xref:../Implementation_Guides/implementations.adoc[Update FedRAMP information]

|20210428
|xref:../Release_STIG_Findings/v21_04_412/scan_results_21_04_412.adoc[v21_04_412 release]

|20210607
|xref:../Release_STIG_Findings/v21_04_421/scan_results_21_04_421.adoc[v21_04_421 release]

|20210623
|xref:../Implementation_Guides/implementations.adoc[Implementation Guides]

|20210715
|xref:../Release_STIG_Findings/v21_04_439/scan_results_21_04_439.adoc[v21_04_439 release]

|20210805
|xref:../Implementation_Guides/implementations.adoc[DISA STIG for Prisma Cloud Compute Update]

|20210831
|xref:../Release_STIG_Findings/v21_08_514/scan_results_21_08_514.adoc[v21_08_514 release]

|20211022
|xref:../Release_STIG_Findings/v21_08_520/scan_results_21_08_520.adoc[v21_08_520 release]

|===


== Implementation Guides

=== FedRAMP
https://docs.paloaltonetworks.com/prisma/prisma-cloud/20-09/prisma-cloud-compute-edition-admin/welcome/pcee_vs_pcce.html[Prisma Cloud Enterprise Edition] is https://marketplace.fedramp.gov/#!/products?sort=productName&productNameSearch=Palo%20Alto%20Networks[FedRAMP Moderate authorized].
The Prisma Cloud Compute module is not within the boundaries of this certification but is available within the FedRAMPed Prisma Cloud Console.
Customers can make the determination if they want to use the Compute module.
Customers requiring FedRAMP certification should use the https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/welcome/pcee_vs_pcce.html[self-hosted version].

GSA has published guidance for the https://www.fedramp.gov/2021-03-16-Vulnerability-Scanning-doc/[FedRAMP Vulnerability Scanning Requirements for Containers].
Customers offering their own FedRAMP services can use Prisma Cloud Compute to facilitate in their service's FedRAMP certification.
The configuration settings for Prisma Cloud Compute's features and functions to support an organization's FedRAMP certification can be found xref:../Implementation_Guides/fedramp.adoc[here].

=== Defense Information Systems Agency (DISA) Security Technical Implementation Guides (STIGs)
Palo Alto Networks is in the process of developing a xref:../Implementation_Guides/stig.adoc[DISA STIG for the configuration of a Prisma Cloud Compute implementation.]
We have decided to post the draft STIG settings here to facilitate collaboration.
Please note this is a work in progress.
If you would like to contribute to the formulation of these settings please see https://github.com/twistlock/docs[this guidance.]


== DISA STIG: Application Security and Development Findings

Prisma Cloud Compute has been assessed to the https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=app-security%2Capp-security-dev[Application Security and Development Security Technical Implementation Guide Version 4, Release: 11 Benchmark Date: 24 Jul 2020].

The findings based upon the vulnerability severity category codes can be found xref:../STIG_ASD_v4_r11/ASD_v4_r11_overview.adoc[here].

== DISA STIG scan findings and justifications for every Prisma Cloud Compute release

Every release of Prisma Cloud Compute we perform an https://csrc.nist.gov/projects/security-content-automation-protocol/[SCAP] scan of the Console and Defender images.
The scan is performed with https://www.open-scap.org/[OpenSCAP] using the https://github.com/ComplianceAsCode[Compliance as Code] benchmark checks:

- Benchmark URL: scap-security-guide-<latest>/ssg-rhel8-ds.xml
- Benchmark ID: xccdf_org.ssgproject.content_benchmark_RHEL-8
- Profile ID: xccdf_org.ssgproject.content_profile_stig

All Prisma Cloud Compute findings are posted xref:../Release_STIG_Findings/release_stig.adoc[here.]

== DISA STIG Compliance Template
Release v21_04_412 include the Docker Enterprise 2.x Linux/UNIX STIG compliance checks into the https://docs.prismacloudcompute.com/docs/compute_edition_21_04/compliance/disa_stig_docker_enterprise.html[“DISA STIG” compliance template.]
When you create a new compliance policy and select the DISA STIG compliance template, you will automatically receive alerts based on the checks aligned with the STIG.
The mapping of the STIG_ID to Prisma Cloud Compute Compliance Check ID can be found xref:../Docker_Enterprise_DISA_STIG/docker_stig.adoc[here.]

== Upgrade Process for deployments in isolated environments

Some deployments of Prisma Cloud Compute are only provided the updated container images.
The supported and documented https://docs.twistlock.com/docs/compute_edition/upgrade/upgrade_process_self_hosted.html[upgrade process] requires the generation of new Console Deployment and Defender daemonSet yamls.
The tools to perform the required upgrade tasks are posted xref:../isolated_upgrades/isolated_upgrade.adoc[here.]
