== 31.xx Known Issues

Review the list of known issues on the 31.xx release.

// Note that when we add a known issue, you have to then update this page to include the "Fixed in xx.xx.xxx" for the known issue when it is fixed subsequently. Fixed issues in a given release are documented in the 31.xx adoc file and indicated as fixed on this page (if it was identified as a known issue earlier).

//CWP-52736
* In 31.02.133, the new 81 out-of-box admission control rules in Rego are not available by default. 
+
This issue is targeted to be addressed in the next release (32.00.xxx).

//CWP-50923
* AKS clusters with an underscore "_" in the resource group name are detected as vanilla Kubernetes clusters instead of AKS clusters in the host scan results.

//CWP-51013
* tt:[Fixed in 31.02.133] Fixed an issue where Defender failed to block containers and generated too many audit events with containers restarting frequently. This was fixed by decreasing the number of requests sent to the Console.

//CWP-51616
* tt:[Fixed in 31.02.133] The Prisma scanner may fail to retrieve image details for Docker registries and may fail with `HTTP 429: Too Many Requests` error when you try to scan more than one Docker registry at a time.

//CWP-50733 //PCSUP-18095
* tt:[Fixed in 31.01.123] Fixed an error in deploying and upgrading the Host Defenders on Windows Server 2019 installed on AWS. 
