:toc: macro
== 31.03 Update 3 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|31.03.103

|Code name
|Newton, 31.03 Update 3

|Release date
|November 12, 2023

|Type
|Maintenance Release

|SHA-256
|94a61e85569bc58571df1c906e399fca8c3d93a9aab50e24b5ac59cad8934999
|===

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/31/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

// link

toc::[]

//[#cve-coverage-update]
//=== CVE Coverage Update

[#enhancements]
=== Enhancements
//CWP-52214
==== Agentless Azure Regions

Added new regions "Israel Central" and "Italy North" in Azure agentless configuration.

// [#new-features-core]
// === New Features in Core

//[#new-features-host-security]
//=== New Features in Host Security

//[#new-features-serverless]
//=== New Features in Serverless

//[#new-features-waas]
//=== New Features in WAAS

// [#api-changes]
// === API Changes and New APIs



//[#breaking-api-changes]
//=== Breaking Changes in API

//[#end-support]
//=== End of Support Notifications

[#addressed-issues]
=== Addressed Issues

//CWP-52647
* Fixed a bug in agentless scanning that in some cases did not discover all hosts deployed in the cloud environment.

//CWP-52324
* Fixed a bug for AWS accounts configured to scan in hub mode. The bug caused a permissions error to appear in the UI during the cleanup stage, while no actual permissions issues were present and the scan was completed successfully.

//CWP-47278
* Fixed an issue wherein the alerts were pending in the immediate alerts queue and causing logging errors. 

//CWP-52046
* Fixed an issue with a broken Jenkins CI link that incorrectly pointed to the Console with filter “true” and no relevant results. The Jenkins output log link now correctly shows the relevant filter for the Jenkins job under *Monitor > Vulnerabilities > Images > CI*.

//CWP-52169
* Fixed an issue wherein the Tanzu apps were missing under *Monitor > Vulnerabilities* scan results for the deployed images on the Diego cells and the image scanning for TAS applications mounted on the external system took extremely long.
To fix this issue, the Defender scan now ignores scanning the images of TAS applications mounted on the external file system.



