== Large deployments

//'''
//
//title: Large deployments
//type: single
//url: "/3.14/start/control-plane/large-deployments/"
//weight: 30
//menu:
//  3.14:
//    parent: "control-plane"
//    identifier: "large-deployments"
//on-prem-only: true
//
//'''

==== About large deployments

For medium and larger deployments, we recommended hosting it in a Kubernetes cluster.

This installation procedure uses a tool named *voila*.

[#_about-voila]
==== About voila

Voila is a toolbox container that allows you to:

* Manage a *voila environment* that wraps all your resources and targets a specific Kubernetes cluster.
* Prepares all the values and certificates that will be injected in the Helm charts to deploy the control plane
* Secure your certificates and other secrets
* Once activated, wraps Kubernetes and Helm commands to target your Kubernetes cluster

The structure of your voila environment contains the following:

* `activate` is a script to activate your voila environment
* `aporeto.yaml` is a file that contains all the settings used for the deployment.
* `certs` is a folder that contains all generated certificates.
* `conf.d` is a folder that contains services configurations.
* `conf.voila` is a file that will contains the voila settings.

[TIP]
====
By default, `aporeto.yaml` and all certificates are encrypted when the environment is not `activated`.
====

==== Next steps

Check out the xref:requirements.adoc[requirements] as a next step.
