== AWS resources that support tags do not have Tags



=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 3c8e89b8-5f3f-41a5-996e-f2b6083c3605

|Checkov ID 
|CKV_AWS_CUSTOM_1

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Many AWS resources support tags. Without tags, it is difficult to organize, manage and track resources. 
Tags allow you to add metadata to a resource to help identify ownership, perform cost / billing analysis, and to enrich a resource with other valuable information, such as descriptions and environment names. 

While there are many ways that tags can be used, we recommend you follow a tagging practice.
View AWS's recommended tagging best practices https://d1.awsstatic.com/whitepapers/aws-tagging-best-practices.pdf[here].

////
=== Fix - Runtime


*AWS Console* 


The procedure varies by resource type.
Tags can be added in the AWS console by navigating to the specific resource.
There is usually a "tags" tab in the resource view that can be used to view and modify tags.
Example to edit tags for a Security Group:

. Navigate to the https://console.aws.amazon.com/ec2/v2/home#Home: [Amazon EC2 console].

. Select Security groups

. Select a security group to edit, then click the Tags tab.

. Click Manage tags, then Add new tag to add a tag.

. Click Save changes.


CLI Command


The following command shows how to add tags for any resource associated with the EC2 service (in this case, a security group).
The specific command varies by resource type for non-EC2 services (e.g., RDS).
`aws ec2 create-tags --resources sg-000b51bf43c710838 --tags Key=Environment,Value=Dev`
////

=== Fix - Buildtime


*Terraform* 


The example below shows how to tag a security group in Terraform.
The syntax is generally the same for any taggable resource type.


[source,go]
----
resource "aws_security_group" "sg" {
  name = "my-sg"
  ...
+ tags = {
+   Environment = "dev"
+   Owner = "apps-team"
+ }
}
----
