== Workspace user volumes are not encrypted


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 49aadf6f-fff8-4b93-afe7-14fb0e8e1c51

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/WorkspaceUserVolumeEncrypted.py[CKV_AWS_155]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Encrypting your Workspace user volumes helps protect your data from unauthorized access or tampering.
That way, you can ensure that only authorized users can access and modify the contents of your volumes.
Such action can help protect against external threats such as hackers or malware, as well as internal threats such as accidental or unauthorized access.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_workspaces_workspace
* *Arguments:*  user_volume_encryption_enabled, volume_encryption_key


[source,go]
----
resource "aws_workspaces_workspace" "pass" {
    ...
+ user_volume_encryption_enabled = true
+ volume_encryption_key          = var.volume_encryption_key
    ...
}
----
----
----


*CloudFormation* 


* *Resource:* AWS::WorkSpaces::Workspace
* *Arguments:*  Properties.UserVolumeEncryptionEnabled


[source,yaml]
----
----
----
Type: AWS::WorkSpaces::Workspace
    Properties: 
      ...
+     UserVolumeEncryptionEnabled: true]
}
----
