== Azure Monitor log profile does not capture all activities
// Azure Monitor log profile not configured to collect logs for all categories


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 64f0ec41-cdcb-42e4-b556-eb66946a62ff

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/arm/checks/resource/MonitorLogProfileCategories.py[CKV_AZURE_38]

|Severity
|LOW

|Subtype
|Build
//, Run

|Frameworks
|ARM,Terraform,Bicep,TerraformPlan

|=== 



=== Description 


A log profile controls how the activity log is exported.
Configuring the log profile to collect logs for the categories *Write*, *Delete* and *Action* ensures that all control/management plane activities performed on the subscription are exported.
We recommend you configure the log profile to export all activities from the control/management plane.
////
=== Fix - Runtime


* Azure Portal The Azure portal currently has no provision to check or set categories.* 




* CLI Command* 


To update an existing default log profile, use the following command: `az monitor log-profiles update --name default`
////
=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_monitor_log_profile
* *Arguments:* categories


[source,go]
----
resource "azurerm_monitor_log_profile" "example" {
    ...
    categories = [
 +   "Action",
 +   "Delete",
 +   "Write",
    ]
}
----
