## Overview

This article describes how to upgrade Openshift platform (with CRI-O configuration - 4.x) if you have Compute Defenders deployed. 
Compute Defenders modify crio.conf file outside of Machine Config Operator and this can result in Openshift upgrade to fail if proper steps are not followed as documented below.  

Please contact your support team for any questions or concerns prior to following these steps.

NOTE: It is important to note the version of Compute when your Defenders were **first deployed** in your Openshift environment.

### Defenders deployed prior to 20.09.xx versions

In releases prior to 20.09.xx, Compute did not revert the original copy of crio.conf and hence the following steps must be followed manually prior to upgrading Openshift platform.

==== Procedure for restoring crio.conf files PRIOR to Openshift upgrade

**Step 1:**

Connect to the Openshift cluster and inspect the Machine Config objects (https://docs.openshift.com/container-platform/4.5/architecture/architecture-rhcos.html)

```
$ oc get machineconfig
NAME                      GENERATEDBYCONTROLLER       IGNITIONVERSION    CREATED
...
rendered-master-xxxx            1234                     2.2.0             199d
rendered-worker-xxxx            1234                     2.2.0             199d
```

"rendered-..." files contain the final configuration that is applied to nodes (after merging all the Machine Configs and ContainerRuntimeConfig objects).  

**Step 2:**

Make a copy of the relevant configuration files. 
For both master and worker nodes, download the relevant configuration files: 
Ex: 

```
$ oc get MachineConfig/rendered-worker-xxxx -o yaml > rendered-worker-xxxx.yaml
```

Make sure the managed crio.conf is present (it may not be present for master nodes if you do not run containers and do not have CRI-O)

```
$ grep -B4 crio.conf rendered-worker-xxxx.yaml
      - contents:
          source: data:..."the content of crio.conf, URI encoded"...
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/crio/crio.conf
```

The content of crio.conf, stored in the Machine Config is URI encoded.
To extract the content and to decode it, you can use the following command 
(Reference: https://www.redhat.com/en/blog/red-hat-openshift-container-platform-4-now-defaults-cri-o-underlying-container-engine)

```
$python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.argv[1]))" $(cat rendered-worker-xxxx.yaml | grep -B4 crio.conf | grep source | tail -n 1 | cut -d, -f2) > crio.conf
```
**Step 3:**

Manually copy the extracted crio.conf file to /etc/crio/crio.conf on all the affected cluster nodes
 
**Step 4:**

Uninstall Compute Defenders on openshift cluster that require upgrade

**Step 5:**

Upgrade Openshift cluster

**Step 6:**

Install Compute Defenders on the upgraded Openshift cluster.


### Defenders deployed after 20.09.xx versions PRIOR to Openshift upgrade

In releases starting 20.09.xx version, Compute creates a copy of original crio.conf file and reverts back to it if all crio rules are disabled on console side.
Thus no manual steps are needed in order to restore original crio.conf file.

**Step 1:**

Uninstall Compute Defenders on openshift cluster that require upgrade

**Step 2:**

Upgrade Openshift cluster

**Step 3:**

Install Compute Defenders again



