== Onboard AWS Accounts

When you click the *Download* button, multiple permission templates are downloaded as JSON files.
These templates support the various permissions required by each of the cloud accounts for each of the scanning modes.

=== Same Account Mode

To scan accounts using this mode, download and apply the permission template that ends in `_target_user_permissions.json` to the AWS cloud account.

=== Hub Account Mode

You first configure and select a cloud account to serve as the hub account.
You apply permissions templates from the hub account in Prisma Cloud to the hub account in AWS, and apply permissions templates from both the hub account and the target account in Prisma Cloud to the target account in AWS.

==== Hub Account

To use an account as a hub account, first add it to Cloud Accounts, downloading and applying the permission template that ends in  `_hub_user_permissions.json` to that hub account in AWS.

==== Target Account

Download and apply the permission template that ends in  `_hub_target_user_permissions.json` to that target account in AWS..
