== Azure Function app configured with public network access
// Ensure that Azure Function App public network access is disabled.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 1f120b65-1350-4f7c-aadb-e9d8b6a52910

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/FunctionAppPublicAccessDisabled.py[CKV_AZURE_221]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Functions is a serverless compute service that enables you to run event-driven code without having to explicitly provision or manage infrastructure. It's essential to restrict public access to such applications to mitigate potential risks. This policy ensures that the public network access to Azure Function Apps is disabled. 

=== Fix - Buildtime

*Terraform*

*Resources:* 
- azurerm_linux_function_app 
- azurerm_linux_function_app_slot 
- azurerm_windows_function_app 
- azurerm_windows_function_app_slot 

*Arguments:* 
- public_network_access_enabled

[source,terraform]
----
resource "azurerm_linux_function_app" "example" {
  name                = "example-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  # ... other configurations ...

+ public_network_access_enabled = false
}

resource "azurerm_windows_function_app" "example" {
  name                = "example-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  # ... other configurations ...

+ public_network_access_enabled = false
}
# ... Similar configurations for other supported resources ...
----
