== VNET Using External DNS Addresses
// Ensure that VNET uses local DNS addresses

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| c2d65566-f018-4792-941c-0ce29164639a

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/VnetLocalDNS.py[CKV_AZURE_183]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Virtual Networks (VNETs) play a critical role in routing network traffic and facilitating domain name resolution via DNS servers. However, relying on external DNS servers for local communications, especially those deployed on-premises, can introduce unnecessary complexity, potential security risks, and additional latency. 

To avoid taking a dependency on external DNS servers, it is advisable to use local DNS addresses within the VNET's address range. This can be achieved by deploying Azure Private DNS Zones, a platform-as-a-service (PaaS) DNS service designed for VNETs.

This policy ensures that any DNS server addresses specified for a VNET are within the VNET's address space, thereby promoting the use of local DNS addresses.

=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_virtual_network

*Arguments:* 
- dns_servers
- address_space

[source,terraform]
----
resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  address_space       = ["10.0.0.0/16"]
  
  # ... other configurations ...

+ dns_servers = ["10.0.0.5"]  // Ensure DNS servers are within the VNET's address space
}
----
