== Azure Event Grid Topic Public Network Access
// Ensure public network access is disabled for Azure Event Grid Topic.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 60431b3d-838c-483e-a4f2-6d0f82d75516

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/EventgridTopicNetworkAccess.py[CKV_AZURE_193]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Event Grid is a fully managed intelligent event-routing service that allows for uniform event consumption using a publish-subscribe model. The service is commonly used to trigger workflows, build richer app-to-app communication, and enable event-based architectures in the cloud.

For security and compliance purposes, it is recommended to disable public network access to Azure Event Grid Topics. Disabling public network access ensures that the Event Grid Topic is only accessible within the virtual network, enhancing the security by reducing exposure to potential threats from the public internet.

This policy ensures that public network access is disabled for Azure Event Grid Topics.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_eventgrid_topic 

*Arguments:* 
- public_network_access_enabled

[source,terraform]
----
resource "azurerm_eventgrid_topic" "example" {
  name                  = "example-topic"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name

  # ... other configurations ...

+ public_network_access_enabled = false

  # ... other configurations ...
}
----

