== API management services do not use virtual networks
// Azure API Management services do not use virtual networks


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2fe7b111-9608-48a5-8062-7878f8ca9c2e

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/APIServicesUseVirtualNetwork.py[CKV_AZURE_107]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan

|=== 



=== Description 


A virtual network is a logical network in Azure that is isolated from other networks.
When you configure your API management service to use a virtual network, you can control the inbound and outbound network traffic to and from your service using network security groups (NSGs) and service endpoints.
This can help to improve the security of your service and protect it from unauthorized access or attacks.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_api_management
* *Arguments:*  virtual_network_configuration


[source,go]
----
resource "azurerm_api_management" "example" {
                  ...
 +                virtual_network_configuration {
                    subnet_id = azure_subnet.subnet_not_public_ip.id 
                  }
                  ....
                }
----

