== Azure application gateway does not have WAF enabled
// Web Application Firewall (WAF) for Azure Application Gateway disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ff7f6448-42a0-47fd-9e00-cb8b3cf21f0a

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/common/graph/checks_infra/base_check.py[CKV_AZURE_120]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan

|=== 



=== Description 


WAF is a security feature that provides protection for web applications by inspecting incoming traffic and blocking malicious requests before they reach the application.
When WAF is enabled on an Azure application gateway, it analyzes incoming traffic to the gateway and blocks requests that are determined to be malicious based on a set of rules.
This can help to protect your application from a variety of threats, such as SQL injection attacks, cross-site scripting (XSS) attacks, and other types of attacks.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_application_gateway
* *Arguments:* waf_configuration.enabled


[source,go]
----
resource "azurerm_application_gateway" "network" {
              ...
+             waf_configuration {
+               enabled = true
              }
            }
----

