== Azure cognitive search does not disable public network access
// Azure Cognitive Search enables public network access


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 32e96093-7c64-4618-86e2-832848acbd92

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/AzureSearchPublicNetworkAccessDisabled.py[CKV_AZURE_124]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan

|=== 



=== Description 


It is generally a good security practice to ensure that your Azure Cognitive Search instance does not have public network access enabled, as this means that it is only accessible from within your private network.
This can help to protect your search instance from unauthorized access, as external parties will not be able to connect to it over the internet.
It is especially important to ensure that public network access is disabled if your Azure Cognitive Search instance contains sensitive or confidential data.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_search_service
* *Arguments:* public_network_access_enabled


[source,go]
----
resource "azurerm_search_service" "example" {
              ...
 +            public_network_access_enabled = false
}
----

