== Telemetry

To drive product improvements, Prisma Cloud captures anonymous data about how our product is used.
By default, telemetry is enabled.

NOTE: No information that is collected can be used to uniquely identify you or your deployment.

NOTE: Telemetry can be disabled any time.

We never collect IP addresses, host names, user names, container labels, or image tags.

Our telemetry is designed to help us understand how customers use our product at an aggregate level.
For example, we detect which features are enabled, the number of containers and images in an environment, and so on.

The legal terms governing telemetry can be found in the Prisma Cloud License Agreement.
The Prisma Cloud License Agreement is included with the installation package.


[.task]
=== Disabling telemetry

Disable telemetry in Console's settings page.

[.procedure]
. Open Console.

. Go to *Manage* > *System* > *General*.

. Under *Telemetry*, set *Share telemetry on product usage with Palo Alto Networks* to *Off*.
