== DISA STIG

=== DISA STIG: Application Security and Development Findings

Prisma Cloud Compute has been assessed to the https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=app-security%2Capp-security-dev[Application Security and Development Security Technical Implementation Guide Version 4, Release: 11 Benchmark Date: 24 Jul 2020].

The findings based upon the vulnerability severity category codes can be found xref:../STIG_ASD_v4_r11/ASD_v4_r11.adoc[here].

=== DISA STIG scan findings and justifications for every Prisma Cloud Compute release

Every release of Prisma Cloud Compute we perform an https://csrc.nist.gov/projects/security-content-automation-protocol/[SCAP] scan of the Console and Defender images.
The scan is performed with https://www.open-scap.org/[OpenSCAP] using the https://github.com/ComplianceAsCode[Compliance as Code] benchmark checks:

- Benchmark URL: scap-security-guide-<latest>/ssg-rhel8-ds.xml
- Benchmark ID: xccdf_org.ssgproject.content_benchmark_RHEL-8
- Profile ID: xccdf_org.ssgproject.content_profile_stig

All Prisma Cloud Compute findings are posted xref:../Release_STIG_Findings/release_stig.adoc[here.]

=== DISA STIG Compliance Template
Release v21_04_412 include the Docker Enterprise 2.x Linux/UNIX STIG compliance checks into the https://docs.prismacloudcompute.com/docs/compute_edition_21_04/compliance/disa_stig_docker_enterprise.html[“DISA STIG” compliance template.]
When you create a new compliance policy and select the DISA STIG compliance template, you will automatically receive alerts based on the checks aligned with the STIG.
The mapping of the STIG_ID to Prisma Cloud Compute Compliance Check ID can be found xref:../Docker_Enterprise_DISA_STIG/mapping.adoc[here].

=== DISA STIG for Prisma Cloud Compute Edition Configuration

Palo Alto Networks is in the process of developing a DISA STIG for the configuration of your Prisma Cloud Compute implementation. 
For details, see xref:../Implementation_Guides/stig.adoc[here].
