== Certificate not verified by Azure Pipelines pipeline command 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|0948afba-1a3d-40d1-a692-26623ed3156a 

|Severity
|Medium
// add severity level

|Category
|Dependency Chains 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Azure Pipelines

|=== 

=== Description

Not verifying certificates through pipeline commands allows attackers to plant their own certificate and impersonate a server in order to perform a man-in-the-middle attack to intercept, tamper with and/or steal information, to possibly run code in the build system and to reach the production environment.

=== Recommended Solution - Buildtime

Remove flags from the commands found in the pipeline that disable the certificate check.

* For *wget* command, remove `--no-check-certificate`
* For *curl* command, remove `--insecure` or `-k` flags	

Consider removing the command entirely from the pipeline if the server certificate cannot be authenticated.

