==  Secrets found in logs of an Azure Pipelines pipeline

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|05229ef5-da68-4cdf-aee5-1ffe396b3c00 

|Severity
|Medium
// add severity level

|Category
|Credential Hygiene
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Azure Pipelines

|=== 

=== Description

Secrets exposed in build log files can be used by an attacker who has taken over an account with system access to move laterally throughout the organization. 
Exposed secrets can be caused by not taking the appropriate safeguards to protect credentials or by printing credentials in a manner that bypasses the feature’s ability to detect credentials.

=== Recommended Solution - Buildtime

It is recommended to rotate all exposed credentials when they are detected.

By default, Azure DevOps masks variables that are designated as secrets when they are printed to the log. However, this feature has limitations. Therefore it is necessary to modify the pipeline manifest to protect exposed credentials.
    
For more on Azure’s instructions on how to mask a value printed to the log refer to https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash.

