== Pull request reviews not required in Azure Repos before merging to the default branch

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|d108910f-8d5c-4b41-a9f7-723894897c17

|Severity
|Medium
// add severity level

|Category
|Flow Control Mechanisms
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Azure Repos

|=== 

=== Description

User accounts with "write" permissions on an actively used repository `*` can push code directly to the default branch without requiring pull request reviews before the code is merged, potentially allowing malicious code to flow through the pipeline to production systems.

* An actively used repository is defined as having at least two contributors, over 50 commits, and has been updated in the last 90 days.


=== Recommended Solution - Buildtime

[.task]

It is recommended to restrict direct pushes to the default branch, and to require a minimum number of reviewers to approve pull requests in order to ensure that code is reviewed before merged.

[.procedure]

. In Azure DevOps, browse to *Repositories* under 'Project Settings'.
. Select a repository and enter its policies.
. Choose the default branch and toggle *ON* the *Require a minimum number of reviewers* policy.
. Set the *Minimum number of reviewers* to 1 or more.

=== Best Practice

It is good practice to enable the following policies:

* Check 'Prohibit the most recent pusher from approving their own changes'

* Check *When new changes are pushed* and select an option:
** Require at least one approval on the last iteration
** Reset all approval votes (does not reset votes to reject or wait)
** Reset all code reviewer votes

