== Default Service Account is used at project level


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6c154645-4580-48e4-a136-30612b5da14f

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/GoogleProjectMemberDefaultServiceAccount.py[CKV_GCP_46]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 

////
Bridgecrew
Prisma Cloud
* Default Service Account is used at project level* 



=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6c154645-4580-48e4-a136-30612b5da14f

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/GoogleProjectMemberDefaultServiceAccount.py [CKV_GCP_46]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 
////


=== Description 


A service account is a special Google account that belongs to an application or a VM, not to an individual end-user.
The application uses the service account to call the service's Google API so that users are not directly involved.
Service accounts represent service-level security of application or VM Resources, determined by the roles assigned to them.
The use of Default service accounts should be avoided, see below for details.
We recommend you do not set IAM role bindings using the default Compute Engine and App Engine service account.

* *Default Compute Engine Service Account*: Used by GKE, Compute, DataProc, DataFlow, Composer.
* *project-number-compute@developer.gserviceaccount.com*
* *Default Appspot Service Account*: Used by App Engine, Cloud Functions, App Engine based services.
* *project-id@appspot.gserviceaccount.com*

=== Fix - Buildtime


*Terraform*


* *Resource:*  google_project_iam_member  google_project_iam_binding
* *Arguments:* member


[source,text]
----
resource "google_project_iam_member" "project" {
  project = "project/1234567"
  role    = "roles/owner"
- member  = "project-number-compute@developer.gserviceaccount.com"
- member  = "project-id@appspot.gserviceaccount.com"
}
----

[source,text]
----
resource "google_project_iam_member" "project" {
  project = "project/1234567"
  role    = "roles/owner"
- members  = [
      "project-number-compute@developer.gserviceaccount.com",
      "project-id@appspot.gserviceaccount.com"
     ]
}
----