[#xdr]
== Cortex XDR alerts

https://www.paloaltonetworks.com/cortex/cortex-xdr[Cortex XDR] is a detection and response app that natively integrates network, endpoint and cloud data to stop sophisticated attacks. Prisma Cloud can send runtime alerts to XDR when your policies are violated. Prisma Cloud can be configured to send data when an entire policy, or even specific rules, are violated.

Prisma Cloud uses webhooks to send the alerts to Cortex XDR. When an event occurs, Prisma Cloud notifies the web service with an HTTP POST request that contains a JSON body.

// === Configuring alert frequency
//
// Reusable content fragment.
include::frag-config-rate.adoc[leveloffset=0]


=== Send alerts to XDR

// === Send alerts
//
// Reusable content fragment.
:xdr_alerts:
include::frag-send-alerts.adoc[leveloffset=0]


[.task]
=== Create a new alert channel

[.procedure]
. In *Manage > Alerts*, click *Add profile*.

. Enter a *Profile name*.

. In *Provider*, select *Cortex*.

. In *Application*, select *XDR*.

. Click *Next*.

// === Configure the triggers
//
// Reusable content fragment.
:cortex_xdr_alerts:
include::frag-config-triggers.adoc[leveloffset=0]

[.task]
=== Configure the channel

[.procedure]
. Under *Settings*, in *Incoming webhook URL* enter the Cortex XDR endpoint where Prisma Cloud should submit the alerts.

. (Optional) In *Credential*, specify a basic auth credential if your endpoint requires authentication.

. (Optional) In *CA Certificate*, enter a CA cert in PEM format.
+
NOTE: When using a CA cert to secure communication, only one-way SSL authentication is supported. If two-way SSL authentication is configured, alerts will not be sent.

. Click *Next*.

. Review the *Summary* and test the configuration by selecting *Send test alert*.

. Click *Save*.
