== DISA STIG Compliance Template

Prisma Cloud offers a compliance template for DISA STIGs.
In many cases, DISA STIG checks map to checks already supported in the product.
In some cases, we’ve implemented checks specifically to support STIGs.

Release v21_04_412 include the Docker Enterprise 2.x Linux/UNIX STIG compliance checks into the https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-04/prisma-cloud-compute-edition-admin/compliance/disa_stig_docker_enterprise.html[“DISA STIG” compliance template.]
When you create a new compliance policy and select the DISA STIG compliance template, you will automatically receive alerts based on the checks aligned with the STIG.
The mapping of the STIG_ID to Prisma Cloud Compute Compliance Check ID can be found xref:mapping.adoc[here.]

=== Release STIG findings
Every release of Prisma Cloud Compute we perform an https://csrc.nist.gov/projects/security-content-automation-protocol/[SCAP] scan of the Console and Defender images.
The scan is performed with https://www.open-scap.org/[OpenSCAP] using the https://github.com/ComplianceAsCode[Compliance as Code] benchmark checks:

- Benchmark URL: scap-security-guide-<latest>/ssg-rhel8-ds.xml
- Benchmark ID: xccdf_org.ssgproject.content_benchmark_RHEL-8
- Profile ID: xccdf_org.ssgproject.content_profile_stig

All Prisma Cloud Compute findings are posted xref:../../Release_Findings/Release_Findings.adoc[here.]

=== Isolated upgrades
Some deployments of Prisma Cloud Compute are only provided the updated container images.
The supported and documented https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-08/prisma-cloud-compute-edition-admin/upgrade.html[upgrade process] requires the generation of new Console Deployment and Defender daemonSet yamls.
The tools to perform the required upgrade tasks are posted xref:../../isolated_upgrades/isolated_upgrades.adoc[here.]

=== Document revisions

[cols="1,3", options="header"]
|===
|Date
|Comment

|20201012
|Initial release of this guidance

|20210209
|xref:../../Release_Findings/Release_Findings.adoc[DISA STIG scan findings and justifications for every release]

|20210401
|xref:../../isolated_upgrades/isolated_upgrades.adoc[Upgrade process for deployments within isolated environment in which only the images were provided]

|20210428
|xref:../../Release_Findings/v21_04_412/scan_results_21_04_412.adoc[v21_04_412 release]

|20210607
|xref:../../Release_Findings/v21_04_421/scan_results_21_04_421.adoc[v21_04_421 release]

|20210715
|xref:../../Release_Findings/v21_04_439/scan_results_21_04_439.adoc[v21_04_439 release]

|20210831
|xref:../../Release_Findings/v21_08_514/scan_results_21_08_514.adoc[v21_08_514 release]

|20211022
|xref:../../Release_Findings/v21_08_520/scan_results_21_08_520.adoc[v21_08_520 release]

|===
