== Mapping

Prisma Cloud offers a compliance template for DISA STIGs.
In many cases, DISA STIG checks map to checks already supported in the product.
In some cases, we’ve implemented checks specifically to support STIGs.
When configuring your compliance policy, simply select the DISA STIG template to enable all relevant checks to Alert.

[cols="1,1", options="header"]
|===
|STIG Severity
|Compute Severity


|CAT I
|High & Critical

|CAT II
|Medium

|CAT III
|Low

|===

As new DISA STIGs are finalized and published they will be incorporated into the DISA STIG temaplate.

=== DISA STIG_ID mapping to Prisma Cloud Compute Compliance Check ID

Eight new compliance checks have been specifically added for the DISA STIG checks, in addition to 49 existing checks that already align with the STIG checks.
The remaining 43 STIG checks are not applicable.
For example, STIG ID: DKER-EE-002180, SAML integration, must be enabled in Docker Enterprise Universal Control Plane.

See the spreadsheet https://docs.google.com/spreadsheets/d/1bhrzwBErrqqIW4xUEpOQQ07_JGwK_fxIh56JhEEJZDQ/edit?usp=sharing[here].
