== Code Reviews and PR Comments

Prisma Cloud Application Security monitors code security in real time across diverse categories. As code scans unfold, the platform offers clear visibility into potential vulnerabilities, coding errors, and security weaknesses. These findings are categorized and conveniently presented on a dashboard, empowering both developers and security experts to swiftly pinpoint critical areas in need of attention. By enabling Code Reviews and PR (Pull Request) Comments, you will receive immediate alerts on various scan issues such as Vulnerabilities, Licenses, IaC, and Secrets throughout the code development process.

=== Code Reviews

On Prisma Cloud view insights into misconfigurations and vulnerabilities identified by default policies using xref:../../risk-management/monitor-and-manage-code-build/enforcement.adoc[Enforcement], a configuration parameter that enables you to set a custom threshold for code reviews performed on your integrated repositories. The insights to your scan are time based; that is, you can view the latest scans or choose to navigate across the scan result history to investigate and identify any misconfigurations or violations in your repository. In addition, these insights enable you to prioritize new and existing issues identified in your repository through a graphical representation of the scan results you can search, sort and customize.

Code Reviews display the global view of all the scan results from your integrated VCS (Version Control System) repositories and CI/CD repositories on the Prisma Cloud console. The graphical representation of the insights from the scan results helps you identify the total number of issues in a code review with the total number of failed, passed and suppressed issues. You can view up to 1000 latest scans and get insights into 20 code reviews that include all scan parameters of failed, passed and suppressed issues. In addition, using Enforcement, a configuration for your CI/CD and VCS repositories, you are customizing your scan results to fail or pass at a specific threshold for each repository. The tabulated insights are structured to list the latest scan first, thus enabling you to prioritize critical issues. You can also choose to re-configure the Enforcement corresponding to the repository using Manage Enforcement.

To know more see xref:../../../dashboards/dashboards-application-security.adoc[Dashboard - Code Security]

=== PR Comments

PR (Pull Request) Comments promptly alerts you on various types of scan issues like Vulnerabilities, Licenses, IaC, and Secrets during the code development phase. PR comments support interactive comments, suggested fixes, and variable rendering support. Prisma Cloud supports PR comments across VCS platforms like GitHub, GitHub Server, GitLab, GitLab self-manages, Bitbucket, Bitbucket Server, and Azure Repos.

In addition, for GitLab, GitLab Self Managed and Azure Repos you can see license compliance errors in the PR. For Bitbucket and Bitbucket Enterprise support for variable rendering scan results, IaC and Secrets  reports, as well as support for licenses and vulnerabilities reports are generated in the PR.
