== Healthcheck instructions have not been added to container images


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2457c548-1ac6-4f6e-a6e5-d6a1ad318720

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/dockerfile/checks/HealthcheckExists.py[CKV_DOCKER_2]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Description 


We recommend that you add the HEALTHCHECK instruction to your Docker container images  to ensure that health checks are executed against running containers.
An important security control is that of availability.
Adding the HEALTHCHECK instruction to your container image ensures that the Docker engine periodically checks the running container instances against that instruction to ensure that containers are still operational.
Based on the results of the health check, the Docker engine could terminate containers which are not responding correctly, and instantiate new ones.

=== Fix - Buildtime


*Docker* 




[source,dockerfile]
----
{
 "FROM base

LABEL foo="bar baz
USER  me
HEALTHCHECK CMD curl --fail http://localhost:3000 || exit 1",
}
----

