== Base image uses a latest version tag


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4a5d5094-4d50-4844-8ebe-d0dbda6f607a

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/dockerfile/checks/ReferenceLatestTag.py[CKV_DOCKER_7]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Docker

|=== 



=== Description 


When possible, it is recommended to pin the version for the base image in your Dockerfiles.
There are a number of potential issues that may be caused when using the `latest` tag.
Since `latest` is the default tag when a tag is not specified, it does not automatically refer to the latest version of the image.
This can lead to the use of outdated images and in the case of production deployments, using a dynamic version can cause unexpected behavior and difficulty in determining which version is being currently used.
It is best practice to be specific as possible about what is running to make operations predictable and reliable

=== Fix - Buildtime


*Dockerfile* 


[,Dockerfile]
----
- FROM alpine:latest
----

