
== Overview

This section contains configuration guidance for Prisma Cloud Compute within public-sector organizations.
Please check up on this site as guidance may change over time.

=== FedRAMP

https://docs.paloaltonetworks.com/prisma/prisma-cloud/20-09/prisma-cloud-compute-edition-admin/welcome/pcee_vs_pcce.html[Prisma Cloud Enterprise Edition] is https://marketplace.fedramp.gov/#!/products?sort=productName&productNameSearch=Palo%20Alto%20Networks[FedRAMP Moderate authorized].
The Prisma Cloud Compute module is not within the boundaries of this certification but is available within the FedRAMPed Prisma Cloud Console.
Customers can make the determination if they want to use the Compute module.
Customers requiring FedRAMP certification should use the https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/welcome/pcee_vs_pcce.html[self-hosted version].

GSA has published guidance for the https://www.fedramp.gov/2021-03-16-Vulnerability-Scanning-doc/[FedRAMP Vulnerability Scanning Requirements for Containers].
Customers offering their own FedRAMP services can use Prisma Cloud Compute to facilitate in their service's FedRAMP certification.
The configuration settings for Prisma Cloud Compute's features and functions to support an organization's FedRAMP certification can be found xref:fedramp.adoc[here].

=== Defense Information Systems Agency (DISA) Security Technical Implementation Guides (STIGs)
Palo Alto Networks is in the process of developing a xref:stig.adoc[DISA STIG for the configuration of a Prisma Cloud Compute implementation.]
We have decided to post the draft STIG settings here to facilitate collaboration.
Please note this is a work in progress.
If you would like to contribute to the formulation of these settings please see https://github.com/twistlock/docs[this guidance.]
