== Setting up SSH controls

//'''
//
//title: Setting up SSH controls
//type: single
//url: "/3.14/secure/ssh/setup/"
//weight: 20
//menu:
//  3.14:
//    parent: "ssh"
//    identifier: "ssh-setup"
//canonical: https://docs.aporeto.com/3.14/secure/ssh/setup/
//aliases: [
//  "../setup/ssh/setup/"
//]
//
//'''

=== About setting up SSH controls

This section guides you through how to set up Aporeto's SSH controls.
Complete these procedures in sequence.

. <<_accepting-aporeto-certificates,Accepting Aporeto certificates>>: configure the remote host to accept Aporeto SSH certificates.
. <<_allowing-users-access,Allowing users access>>: give yourself and a test user access to the remote host using Aporeto SSH certificates.
. <<_allowing-sudo-commands,Allowing sudo commands>>: provide yourself with the ability to issue `sudo` commands.
. <<_adding-a-fallback-user,Adding a fallback user>>: in the unlikely event that the enforcer goes down, you'll need a way to access the host.
. <<_validating-your-setup,Validating your setup>>: make sure that you and the test user can log in as expected.
. <<_requiring-aporeto-certificates,Requiring Aporeto certificates>>: remove the ability to access the host without an Aporeto SSH certificate.

After completing these procedures, you should have a good understanding of how Aporeto's SSH controls work and how to roll them out across your organization.

=== Requirement

Remote hosts must have https://www.openssh.com/txt/release-7.4[OpenSSH 7.4p1] or later.

[TIP]
====
The following distributions include the required version of OpenSSH:

* https://access.redhat.com/blogs/766093/posts/3051131[RedHat Enterprise Linux (RHEL) and CentOS 7.4 and later]
* https://launchpad.net/ubuntu/bionic/+source/openssh[Ubuntu 18.04 and later]
====

=== Prerequisites

* *An identity provider*:
Aporeto supports OpenID Connect (OIDC), Lightweight Directory Access Protocol (LDAP), and Security Assertion Markup Language (SAML) identity providers.
For more information on OIDC identity providers and configuration instructions, refer to xref:../../setup/idp/idp.adoc[integrating with OIDC identity providers] and xref:../../setup/idp/ssh-ctrl-plane.adoc[for SSH and control plane users].
* *A test user account in your identity provider*:
to learn how to provision SSH access to users other than yourself, you'll need a test user account in your chosen identity provider.
* *Aporeto enforcer installed on the remote host as a Linux service*:
for instructions, refer to one of the following.
** xref:../../start/enforcer/k8s.adoc[Kubernetes/OpenShift hosts]
** xref:../../start/enforcer/linux.adoc[Other hosts]
* *A local host with xref:../../start/apoctl/apoctl.adoc[`apoctl` installed]*:
we'll use Aporeto's command-line client in the following exercises.
Ensure that it's installed and that you are logged in as a *Namespace administrator* in the namespace of the remote host.
* *SSH access to the remote host with `sudo` privileges*:
make sure you can SSH into the remote host and execute `sudo` commands.

[#_accepting-aporeto-certificates]
=== Accepting Aporeto certificates

[.task]
==== Setting environment variables

Let's first set a few environment variables to make our subsequent commands a lot easier.

[.procedure]
. On your local host, set an `SSH_HOST` environment variable containing the address of the SSH host.
You can use its fully qualified domain name, IP address, or name from your local https://en.wikipedia.org/wiki/Hosts_(file)[hosts file].
An example follows.
+
----
export SSH_HOST=ec2-19-284-69-53.us-east-2.compute.amazonaws.com
----

. Set an `SSH_PRIVATE_KEY` environment variable containing the name (and location, if necessary) of the local private key that allows you to SSH into the target remote host.
An example follows.
+
----
export SSH_PRIVATE_KEY="~/.ssh/id_rsa"
----

. Set a `LINUX_ACCOUNT` environment variable containing the name of the user account you have on the remote host.
This account must have `sudo` privileges.
An example follows.
+
----
export LINUX_ACCOUNT=ubuntu
----

[.task]
==== Configuring the host to accept Aporeto certificates

[.procedure]
. Obtain a secure shell with `sudo` privileges on the target remote host.
+
[,console]
----
ssh -i $SSH_PRIVATE_KEY $LINUX_ACCOUNT@$SSH_HOST
----

. Confirm that the enforcer automatically downloaded the public key of the Aporeto SSH certificate authority.
+
[,console]
----
sudo ls -la /usr/share/aporeto/sshca.pub
----
+
It should return something like the following.
+
----
-rw-r----- 1 root root 215 Aug  8 20:46 /usr/share/aporeto/sshca.pub
----
+
WARNING: If the public key is missing, you must <<_public-key-of-aporeto-ssh-certificate-authority-missing,manually populate this file as described in Troubleshooting>> before continuing to the next step.

. Use the following commands to append a series of lines to the `/etc/ssh/sshd_config` file.
+
[,console]
----
printf '\n%s\n' "TrustedUserCAKeys /usr/share/aporeto/sshca.pub" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s\n' "AuthorizedPrincipalsCommand /usr/share/aporeto/authorizedprincipals %k %u" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s\n' "AuthorizedPrincipalsCommandUser root" \
  | sudo tee -a /etc/ssh/sshd_config
sudo cat /etc/ssh/sshd_config
----
+
You should see the following lines at the bottom of the file.
+
----
TrustedUserCAKeys /usr/share/aporeto/sshca.pub
AuthorizedPrincipalsCommand /usr/share/aporeto/authorizedprincipals %k %u
AuthorizedPrincipalsCommandUser root
----
+
[TIP]
====
Refer to the https://man.openbsd.org/sshd_config[OpenBSD documentation] for more details about the `sshd_config` file.
====

. Restart the OpenSSH SSH daemon and confirm that it comes back up.
+
systemd:
+
----
sudo systemctl restart sshd
sudo systemctl status sshd
----
+
upstart:
+
----
sudo service ssh restart
sudo service ssh status
----
+
initd:
+
----
sudo /etc/init.d/sshd restart
sudo /etc/init.d/sshd status
----

. Create a new Linux account named `test-user` that doesn't have `sudo` privileges.
+
[,console]
----
sudo useradd -m test-user
sudo passwd test-user
----

. Close your SSH session on the remote host.
+
[,console]
----
exit
----

. Confirm that you can still log on.
+
[,console]
----
ssh -i $SSH_PRIVATE_KEY $LINUX_ACCOUNT@$SSH_HOST
----

. Close your SSH session on the remote host.
+
[,console]
----
exit
----
+
Continue to the <<_allowing-users-access,next section>>.

[#_allowing-users-access]
=== Allowing users access

[.task]
==== Setting environment variables

[.procedure]
. Back on your local host, issue the following command.
+
[,console]
----
apoctl auth verify
----

. Review the claims in your token and locate the key-value pair that you want to use to identify yourself.
. Log into `apoctl` as your test user.
Refer to the xref:../../start/apoctl/apoctl.adoc[`apoctl` set up section] for details and options.
+
[TIP]
====
If you authenticate using OIDC, consider using the `--open-with` flag to open the authentication prompt in a different browser.
That way you can keep the token of your main user cached in your normal browser and cache your test user's token in a different browser.
====

. Take a look at your test user's token.
+
[,console]
----
apoctl auth verify
----

. Examine the claims in the test user's token and locate the key-value pair that you want to use to identify the test user.
. Log back into `apoctl` using your regular account, using `apoctl auth verify` to verify this.
. Set `ME` and `TEST_USER` environment variables containing the identifying claims using the following syntax: `<key>=<value>`, where `<key>` is the key in the Aporeto token and `<value>` is its value.
Some examples follow.
+
|====
|Identity provider | Key in token | Value in token | Expression

|Any | `email` | `+you@example.com+` | `+email=you@example.com+`
|https://developers.google.com/identity/protocols/OpenIDConnect#hd-param[Google] | `hd` | `+example.com+` | `+hd=example.com+`
|Microsoft Azure Active Directory | `groups:1e94a453-2727-47f6-b59e-d86df3494312` | `true` | `groups:1e94a453-2727-47f6-b59e-d86df3494312=true`
|Microsoft Azure Active Directory | `tid:9188040d-6c67-4c5b-b112-36a304b66dad` | `true` | `tid:9188040d-6c67-4c5b-b112-36a304b66dad=true`
|Okta | `groups:your-org` | `true` | `groups:your-org=true`
|====
+
In the following commands, we use email addresses.
+
[,console]
----
export ME=email=you@example.com
export TEST_USER=email=test-user@example.com
----

. Set an `AUTH_METHOD` environment variable containing one of the following tags, according to the system that you and your test user authenticate against: `@auth:realm=oidc`, `@auth:realm=ldap`, or `@auth:realm=vince` (for company account administrators only).
+
[,console]
----
export AUTH_METHOD=@auth:realm=oidc
----

. Set a `NAMESPACE` environment variable containing the namespace of the enforcer on the target host.
In the following example, we set it to `/acme/team-a/linux-hosts`.
+
[,console]
----
export NAMESPACE=/acme/team-a/linux-hosts
----

. Set an `ENFORCER` environment variable containing the Aporeto tag that selects the enforcer on the host that the user should be allowed to execute `sudo` commands on.
In the following example, we select all of the enforcers in the target namespace.
+
[,console]
----
export ENFORCER=\$identity=enforcer
----
+
[TIP]
====
Notice how we've escaped the bash control character `$` by adding `\` in front of it.
====

==== Enabling audit logs

Let's enable logging of all the commands issued on the host as root.

Propagated to child namespaces:

----
    cat <<EOF | apoctl api create auditprofilemappingpolicy -n "$NAMESPACE" -f -
    name: enable-ssh-audit-logs
    propagate: true
    subject:
    - - "$ENFORCER"
    object:
    - - "auditprofile:rule=execve"
    EOF
----

Not propagated to child namespaces:

----
    cat <<EOF | apoctl api create auditprofilemappingpolicy -n "$NAMESPACE" -f -
    name: enable-ssh-audit-logs
    propagate: false
    subject:
    - - "$ENFORCER"
    object:
    - - "auditprofile:rule=execve"
    EOF
----

==== Allowing users to access the internet during SSH sessions

Aporeto recognizes SSH sessions as processing units and blocks all network communications by default.
At a minimum, you must enable DNS queries from SSH sessions.
But we imagine you'll also want to allow other communications to and from SSH sessions.

Use the following command to create an external network that represents the internet.

Propagated to child namespaces:

----
    cat <<EOF | apoctl api create externalnetwork -n "$NAMESPACE" -f -
    name: internet
    propagate: true
    associatedTags:
    - "ext:net=internet"
    entries:
    - "0.0.0.0/0"
    protocols:
    - udp
    - tcp
    - icmp
    ports:
    - "1:65535"
    EOF
----

Not propagated to child namespaces:

----
    cat <<EOF | apoctl api create externalnetwork -n "$NAMESPACE" -f -
    name: internet
    propagate: false
    associatedTags:
    - "ext:net=internet"
    entries:
    - "0.0.0.0/0"
    protocols:
    - udp
    - tcp
    - icmp
    ports:
    - "1:65535"
    EOF
----

Now, create a network policy that allows any SSH session to initiate connections to and accept connections from the internet.

Propagated to child namespaces:

----
    cat <<EOF | apoctl api create networkaccesspolicy -n "$NAMESPACE" -f -
    name: allows-internet-access-from-ssh-sessions
    propagate: true
    action: "Allow"
    logsEnabled: true
    propagate: true
    subject:
    - - "$identity=processingunit"
      - "$type=SSHSession"
    - - "ext:net=internet"
    object:
    - - "$identity=processingunit"
      - "$type=SSHSession"
    - - "ext:net=internet"
    EOF
----

Not propagated to child namespaces:

----
    cat <<EOF | apoctl api create networkaccesspolicy -n "$NAMESPACE" -f -
    name: allows-internet-access-from-ssh-sessions
    propagate: false
    action: "Allow"
    logsEnabled: true
    propagate: true
    subject:
    - - "$identity=processingunit"
      - "$type=SSHSession"
    - - "ext:net=internet"
    object:
    - - "$identity=processingunit"
      - "$type=SSHSession"
    - - "ext:net=internet"
    EOF
----

[TIP]
====
Observe how we've escaped the Aporeto tags that begin with `$`, a control character in bash.
====

Your SSH sessions can now initiate and accept most connections.
Should you wish to establish some restrictions, refer to xref:../netpol/netpol.adoc[Defining network policies].
Since reject policies take precedence over allow, you can layer more restrictive policies on top of this one as desired.

==== Allowing users to request SSH certificates

Use one of the following commands to create an API authorization that allows both you and the test user to request certificates.

Propagated to child namespaces:

----
    cat <<EOF | apoctl api create apiauthorizationpolicy -n "$NAMESPACE" -f -
    name: allow-ssh-certificate-requests
    action: Allow
    propagate: true
    subject:
    - - "$AUTH_METHOD"
      - "@auth:$ME"
    - - "$AUTH_METHOD"
      - "@auth:$TEST_USER"
    authorizedNamespace: "$NAMESPACE"
    authorizedIdentities:
    - "@auth:role=sshidentity.requester"
    EOF
----

Not propagated to child namespaces:

----
    cat <<EOF | apoctl api create apiauthorizationpolicy -n "$NAMESPACE" -f -
    name: allow-ssh-certificate-requests
    action: Allow
    propagate: false
    subject:
    - - "$AUTH_METHOD"
      - "@auth:$ME"
    - - "$AUTH_METHOD"
      - "@auth:$TEST_USER"
    authorizedNamespace: "$NAMESPACE"
    authorizedIdentities:
    - "@auth:role=sshidentity.requester"
    EOF
----


==== Allowing yourself to SSH into the host

While Aporeto provides a wealth of options for controlling users' SSH access, the following authorization should cover most use cases.
Use the following command to authorize yourself to login to the remote host via SSH.

Propagated to child namespaces:

----
    cat <<EOF | apoctl api create sshauthorizationpolicy -n "$NAMESPACE" -f -
    name: allow-myself-ssh-access
    propagate: true
    subject:
    - - "$AUTH_METHOD"
      - "@auth:$ME"
    object:
    - - "$ENFORCER"
    extensions:
    - permit-pty
    principals:
    - fallback
    EOF
----

Not propagated to child namespaces:

----
    cat <<EOF | apoctl api create sshauthorizationpolicy -n "$NAMESPACE" -f -
    name: allow-myself-ssh-access
    propagate: false
    subject:
    - - "$AUTH_METHOD"
      - "@auth:$ME"
    object:
    - - "$ENFORCER"
    extensions:
    - permit-pty
    principals:
    - fallback
    EOF
----

[TIP]
====
Observe how we've added `fallback` under `principals`.
We're going to need this later on, when we <<_adding-a-fallback-user,add a fallback user>>.
====

We encourage you to refer to xref:../../reference/resources/ssh-auth.adoc[SSH authorization] in the reference section and explore the opportunities for customizing SSH authorizations.

==== Allowing the test user to SSH into the host

Use the following command to authorize the test user to login to the remote host via SSH.

Propagated to child namespaces:

----
    cat <<EOF | apoctl api create sshauthorizationpolicy -n "$NAMESPACE" -f -
    name: allow-test-user-ssh-access
    propagate: true
    subject:
    - - "$AUTH_METHOD"
      - "@auth:$TEST_USER"
    object:
    - - "$ENFORCER"
    extensions:
    - permit-pty
    EOF
----

Not propagated to child namespaces:

----
    cat <<EOF | apoctl api create sshauthorizationpolicy -n "$NAMESPACE" -f -
    name: allow-test-user-ssh-access
    propagate: false
    subject:
    - - "$AUTH_METHOD"
      - "@auth:$TEST_USER"
    object:
    - - "$ENFORCER"
    extensions:
    - permit-pty
    EOF
----

[#_allowing-sudo-commands]
=== Allowing sudo commands

==== About allowing sudo commands

You should allow only trusted users to issue `sudo` commands.
Users with `sudo` privileges can tamper with Aporeto's SSH controls and subvert the system.
However, as long as they use an Aporeto certificate, you can identify malicious actors and unwanted activities.

==== Creating a sudo authorization

Use one of the following commands to create a `sudo` authorization for yourself.

Propagated to child namespaces:

----
    cat <<EOF | apoctl api create useraccesspolicy -n "$NAMESPACE" -f -
    name: allow-sudo-users
    action: Allow
    propagate: true
    subject:
    - - "@user:ssh:auth:$ME"
    object:
    - - "$ENFORCER"
    allowedSudoUsers:
    - root
    EOF
----

Not propagated to child namespaces:

----
    cat <<EOF | apoctl api create useraccesspolicy -n "$NAMESPACE" -f -
    name: allow-sudo-users
    action: Allow
    propagate: false
    subject:
    - - "@user:ssh:auth:$ME"
    object:
    - - "$ENFORCER"
    allowedSudoUsers:
    - root
    EOF
----

==== Installing the sudo plugin

Log into the remote host.

[,console]
----
ssh -i $SSH_PRIVATE_KEY $LINUX_ACCOUNT@$SSH_HOST
----

Issue the command appropriate to your distribution to install Aporeto's `sudo` plugin.

Ubuntu/Debian:
----
    sudo apt install -y enforcerd-sshplugin
----

CentOS/RedHat/OpenSuSE:
----
    sudo yum install -y enforcerd-sshplugin
----

[TIP]
====
On Ubuntu, you can use the following command to verify that that package installed correctly: `apt list --installed enforcerd-sshplugin`
====

Great job! Now, let's <<_adding-a-fallback-user,add a fallback user>> to be used in case the enforcer ever goes down.

[#_adding-a-fallback-user]
[.task]
=== Adding a fallback user

To ensure that you don't get locked out of the host in the unlikely event that the enforcer goes down, you can hardcode your user name and the value of the claim you're using to identify yourself in a file on the host.

[.procedure]
. Create a new user account on the remote host named `fallback`.
+
[,console]
----
sudo useradd -m fallback
sudo passwd fallback
----

. Give the fallback user `sudo` privileges.
+
[,console]
----
usermod -aG sudo fallback
----

. Use the following command to edit the `/etc/ssh/sshd_config` file to use an `authorized_principals` file if the user is `fallback`.
If the user is not `fallback`, it uses Aporeto's `authorizedprincipals` binary.
+
[,console]
----
tac /etc/ssh/sshd_config | sed "1,3d" | tac | sudo tee /etc/ssh/sshd_config
printf '\n%s\n' "TrustedUserCAKeys /usr/share/aporeto/sshca.pub" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s\n' "Match User fallback" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s\n' "  AuthorizedPrincipalsFile /usr/share/aporeto/authorized_principals" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s' "Match User *,!" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s\n' "fallback" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s\n' "  AuthorizedPrincipalsCommand /usr/share/aporeto/authorizedprincipals %k %u" \
  | sudo tee -a /etc/ssh/sshd_config
printf '%s\n' "  AuthorizedPrincipalsCommandUser root" \
  | sudo tee -a /etc/ssh/sshd_config
sudo cat /etc/ssh/sshd_config
----
+
Confirm that the following lines were added to the bottom of the file.
+
[,console]
----
TrustedUserCAKeys /usr/share/aporeto/sshca.pub
Match User fallback
  AuthorizedPrincipalsFile /usr/share/aporeto/authorized_principals
Match User *,!fallback
  AuthorizedPrincipalsCommand /usr/share/aporeto/authorizedprincipals %k %u
  AuthorizedPrincipalsCommandUser root
----
+
[TIP]
====
Refer to the https://man.openbsd.org/sshd_config[OpenBSD documentation] for more details about the `sshd_config` file.
====

. Use the following command to create a new file in `/usr/share/aporeto/` called `authorized_principals` containing: the value of the claim that you are using to identify yourself and `fallback`.
The following example shows `+you@example.com+` as the identifying claim.
Replace `+you@example.com+` with the actual expected value before issuing the command.
+
[,console]
----
printf '%s\n' "you@example.com" \
  | sudo tee -a /usr/share/aporeto/authorized_principals
printf '%b\n' "fallback" \
  | sudo tee -a /usr/share/aporeto/authorized_principals
sudo cat /usr/share/aporeto/authorized_principals
----

. Confirm that the `authorized_principals` file contains the correct values.
+
[,console]
----
you@example.com
fallback
----

. Restart the OpenSSH SSH daemon and confirm that it comes back up.
+
systemd:
+
----
 sudo systemctl restart sshd
 sudo systemctl status sshd
----
+
upstart:
+
----
 sudo service ssh restart
 sudo service ssh status
----
+
initd:
+
----
 sudo /etc/init.d/sshd restart
 sudo /etc/init.d/sshd status
----

. Exit the SSH session.
+
[,console]
----
exit
----
+
Great job!
Now, let's <<_validating-your-setup,validate our setup>>.

[#_validating-your-setup]
=== Validating your setup

[#_generating-a-new-public-private-key-pair]
[.task]
==== Generating a new public-private key pair

To ensure the security of your account, complete the following steps to generate a new public-private key pair.
This ensures that:

* No one else has a copy. For example, if you use a cloud provider for your remote host, the cloud provider may have a copy of the private key of the existing pair.
* The private key is properly protected with a password.
* The key pair uses a newer, more secure algorithm.

You can use any number of tools to generate a public-private key pair.
The procedure below uses the OpenSSH `ssh-keygen` utility.
Because the Aporeto SSH certificates require https://www.openssh.com/txt/release-7.4[OpenSSH 7.4p1] or later, we can go ahead and use the newer and more secure ECDSA algorithm at the 521-bit key size.

[.procedure]
. Create a new public-private key pair named `aporeto-ecdsa`.
+
[,console]
----
ssh-keygen -f ~/.ssh/aporeto-ecdsa -t ecdsa -b 521
----

. Set a passphrase to protect the private key at the prompt.
. Confirm that the keys were created.
+
[,console]
----
ls -la ~/.ssh/aporeto-ecdsa*
----

. Your response should look something like the following.
+
----
-rw-------  1 your-user  staff  756 May 28 14:58 /Users/your-user/.ssh/aporeto-ecdsa
-rw-r--r--  1 your-user  staff  284 May 28 14:58 /Users/your-user/.ssh/aporeto-ecdsa.pub
----

. Before proceeding further, let's take a moment to make sure our private key is well formed.
+
[,console]
----
ssh-keygen -l -f ~/.ssh/aporeto-ecdsa
----
+
It should return something like the following.
+
----
521 SHA256:1IG25xehpVg74172DicbNpUuz89u43i0ZV8JNUj172c your-user@your-host.local (ECDSA)
----

. Let's check our public key as well.
+
[,console]
----
ssh-keygen -l -f ~/.ssh/aporeto-ecdsa.pub
----
+
It should return something like the following.
`console output
521 SHA256:1IG25xehpVg74172DicbNpUuz89u43i0ZV8JNUj172c your-user@your-host.local (ECDSA)
`

[.task]
==== Logging into the remote host as the test user

[.procedure]
. Log into `apoctl` using your test user account.
Refer to the xref:../../start/apoctl/apoctl.adoc[`apoctl` install and configuration section] for details and options.
. Verify that you're logged in as the test user.
+
[,console]
----
apoctl auth verify
----

. Request an SSH certificate from the Aporeto control plane for inspection, passing in the public key you <<_generating-a-new-public-private-key-pair,created just above>>.
+
[,console]
----
apoctl ssh cert --public-key ~/.ssh/aporeto-ecdsa.pub \
--namespace $NAMESPACE | apoctl ssh inspect
----
+
You should get back something like the following.
+
----
Type: ecdsa-sha2-nistp521-cert-v01@openssh.com
Key ID: Aporeto SSH Identity Certificate test-user@example.com
Serial: 6179686033339819869
Valid: from 2019-08-13T13:23:43-07:00 to 2019-08-13T15:23:43-07:00 remaining 1h0m13.997572s
Principals:

 ** test-user@example.com
Critical Options: (none)
Extensions:
 ** permit-pty
Aporeto Namespace: /acme/team-a/linux-hosts
Identity Claims:
 ** @auth:at_hash=iOCl4fjadk3CfdvUupbeOw
 ** @auth:idp=00o10euxkcI8w1s4o357
 ** @auth:iss=https://dev-740803.okta.com/oauth2/default
 ** @auth:jti=ID.DCfZkM7ps5jpxmg-a1y_9Fh6_H4uViXx6kEUWlztqZg
 ** @auth:namespace=/acme/team-a/linux-hosts
 ** @auth:organization=/acme/team-a/linux-hosts
 ** @auth:provider=okta
 ** @auth:amr:pwd=true
 ** @auth:aud=0oa10evug9AN9V6Rj357
 ** @auth:email=test-user@example.com
 ** @auth:realm=oidc
 ** @auth:sub=00u13r4f1zVELYtpH357
 ** @auth:subject=test-user@example.com
----
+
[TIP]
====
We need to use `apoctl ssh inspect` to view the Aporeto SSH certificate because it includes custom extensions: `Aporeto Namespace` and `Identity Claims`.
====

. Request an SSH certificate again, this time saving it to a file.
+
[,console]
----
apoctl ssh cert --public-key ~/.ssh/aporeto-ecdsa.pub \
--namespace $NAMESPACE > ~/.ssh/aporeto-ssh-cert.crt
----

. Set the permissions of the file so that only you can write to it.
+
[,console]
----
sudo chmod 700 ~/.ssh/aporeto-ssh-cert.crt
----

. Issue the following command to access the host, passing in the Aporeto SSH certificate and your private key.
+
[,console]
----
ssh -i ~/.ssh/aporeto-ssh-cert.crt -i ~/.ssh/aporeto-ecdsa test-user@$SSH_HOST
----
+
[TIP]
====
Your SSH client does not send its private key to the remote host, just its certificate.
During the SSH handshake, the remote host uses the public key in the certificate to encrypt a challenge message.
Your SSH client uses its local private key to decrypt the challenge message, thereby proving its identity.
====

. You should get a secure shell on the remote host. Issue any `sudo` command, such as the following.
+
[,console]
----
sudo cat /etc/ssh/sshd_config
----
+
It should return the following message, confirming that Aporeto is blocking `sudo` commands from unauthorized users.
+
----
Invalid request : Request rejected Policy does not allow SSH session to sudo to user root
+
sudo: unable to initialize policy plugin
----

. Open the Aporeto web interface and select the *Platform* pane.
Click on the processing unit representing your SSH session.
Observe that the *Operational status* is *Running*.
+
[TIP]
====
It should be a yellow octagon named something like `/acme.ip-172-31-29-81.us-west-2.compute.internal`.
====

. Click the *Policies* tab.
You should see the network policy we set up earlier to allow users to initiate connections to the internet.
. Click the *Audit* tab and review the commands issued with root privileges on the host.
. Expand *Logs* and select *Access logs*.
You should see an *SSH Login* event and a *Sudo Exit* event.
Note the reason for the *Sudo Exit* is *missing policy*.
. Expand *Cloud PAM* and select *SSH Sessions*.
Click to expand the top entry.
Then click the *Details* button.
Scroll down to review the *List of Commands*.
. Return to your terminal and close the SSH session.
+
[,console]
----
exit
----

. Open the Aporeto web interface and select the *Platform* pane.
Click on the processing unit representing your SSH session.
Observe that its *Operational status* is now *Terminated*.

[.task]
==== Logging into the remote host as yourself

[.procedure]
. Log into `apoctl` with your normal user account and type `apoctl auth verify` to make sure.
. Use the following command to access the remote host with an Aporeto certificate.
+
[,console]
----
apoctl ssh connect --public-key ~/.ssh/aporeto-ecdsa.pub \
--namespace $NAMESPACE -- $LINUX_ACCOUNT@$SSH_HOST
----
+
You should get a shell on the remote host.
+
[NOTE]
====
While we used a longer method of accessing the host in the previous section, you can also access the remote host in a single command as shown above.
This works as long as your identity provider is the default.
Issuing a single command is convenient, but the longer method provides more options, such as the ability to log into the remote host from a jump server/bastion host and issue `scp` or `sftp` commands.
====

. Issue a `sudo` command, such as the following.
+
[,console]
----
sudo ls -la /root
----

. As you did for the test user, click on the processing unit representing your SSH session in the Aporeto web interface and review its details.
Also take a look at *Logs* > *Access logs* and *Cloud PAM* > *SSH sessions*.

[.task]
==== Logging into the remote host as the fallback user

Only highly trusted people should have the ability to log in as the fallback user.
This option should be used only in the unexpected event of an enforcer going down.
Though the fallback user logs in with an Aporeto SSH certificate, their commands and activities are not logged.

[.procedure]
. Still logged in as your regular user, stop the enforcer.
+
systemd:
+
----
 sudo systemctl stop enforcerd
----
+
upstart:
+
----
 sudo stop enforcerd
----
+
initd:
+
----
 sudo /etc/init.d/enforcerd stop
----

. Exit the secure shell session.
+
[,console]
----
exit
----

. Try to log back in again.
+
[,console]
----
apoctl ssh connect --public-key ~/.ssh/aporeto-ecdsa.pub \
--namespace $NAMESPACE -- $LINUX_ACCOUNT@$SSH_HOST
----
+
You won't be able to because the enforcer is down.
+
----
Permission denied (publickey).
error: exit status 255
----

. Use the following command to access the remote host as the fallback user.
+
[,console]
----
apoctl ssh connect --public-key ~/.ssh/aporeto-ecdsa.pub \
--namespace $NAMESPACE -- fallback@$SSH_HOST
----
+
[TIP]
====
Observe that the only change to your command is the name of the Linux account.
====

. You should get a secure shell on the remote host.
Confirm that you can issue `sudo` commands by checking the status of the enforcer.
+
systemd:
+
----
 sudo systemctl status enforcerd
----
+
upstart:
+
----
 sudo status enforcerd
----
+
initd:
+
----
 sudo /etc/init.d/enforcerd status
----

. After confirming that the enforcer is down, start it up again.
+
systemd:
+
----
 sudo systemctl enable --now enforcerd
 sudo systemctl status enforcerd
----
+
upstart:
+
----
 sudo start enforcerd
 sudo status enforcerd
----
+
initd:
+
----
 sudo /etc/init.d/enforcerd start
 sudo /etc/init.d/enforcerd status
----
+
Congratulations!
You're almost done.
All that's left now is to <<_requiring-aporeto-certificates,disable the ability to log in without an Aporeto SSH certificate>>.

[#_requiring-aporeto-certificates]
[.task]
=== Requiring Aporeto certificates

Now that you have verified that you can gain `sudo` access to the remote host even when the enforcer is down, you should disable the ability to log in without an Aporeto SSH certificate.

[.procedure]
. Open the `sshd_config` file in your favorite editor.
+
[,console]
----
sudo vi /etc/ssh/sshd_config
----

. Scroll through the file and look for an existing `AuthorizedKeysFile` line.
It may be commented out.
If so, uncomment it.
If it is missing completely, go ahead and add this line.
Set the value of `AuthorizedKeysFile` to `/dev/null`.
+
[,console]
----
AuthorizedKeysFile /dev/null
----

. Restart the OpenSSH SSH daemon.
+
[,console]
----
sudo systemctl restart sshd
sudo systemctl status sshd
----

. Close your SSH session.
+
[,console]
----
exit
----

. Attempt to access the host using the certificate that wasn't issued by Aporeto.
+
[,console]
----
ssh -i $SSH_PRIVATE_KEY $LINUX_ACCOUNT@$SSH_HOST
----
+
You should receive the following response.
+
[,console]
----
Permission denied (publickey).
----

. Now try to gain access using an Aporeto-issued certificate.
+
[,console]
----
apoctl ssh connect --public-key ~/.ssh/aporeto-ecdsa.pub \
--namespace $NAMESPACE -- $LINUX_ACCOUNT@$SSH_HOST
----
+
You should get a shell with `sudo` privileges on the remote host.
Great job!
You've secured the remote host and prevented anyone from accessing it with certificates not issued by Aporeto.

=== Next steps

We hope you have learned enough to deploy SSH controls across your organization.

[TIP]
====
You may wish to delete the `test-user` account from the remote host and from your identity provider.
====

=== Troubleshooting

==== Increase the client logging level

When experiencing a failure to connect to a remote host, try adding one to three `v` flags to your `ssh` command.
This can give you some insight into the cause.
In the following example, we include three ``v``s for maximum logging.

[,console]
----
ssh -i ~/.ssh/aporeto-ssh-cert.crt -i ~/.ssh/aporeto-ecdsa test-user@$SSH_HOST -vvvv
----

==== Increase the Aporeto enforcer logging level

To increase the amount of logs generated by the Aporeto enforcer, open its configuration file in your favorite editor.

[,console]
----
sudo vi /etc/enforcerd.conf
----

Locate the `ENFORCERD_LOG_LEVEL` line and modify its value to `debug`.
Save and close the file.
Restart the enforcer.

[,console]
----
sudo systemctl restart enforcerd
sudo systemctl status enforcerd
----

The service should return to `active (running)`.
Try again to authorize from your client and then use the following command to list the log files in sorted order.

[,console]
----
ls -lart /var/log/enforcerd
----

The most recent log file will be at the bottom.
Open this file and review its contents.
An example follows.

[,console]
----
cat /var/log/enforcerd/enforcer-14829.log
----

==== Increase the OpenSSH SSH daemon logging level

To increase the logging level for the OpenSSH SSH daemon, open its configuration file in your favorite editor.

[,console]
----
sudo vi /etc/ssh/sshd_config
----

Locate the `LogLevel` line and edit its value to `DEBUG3` for maximum logs.
Save and close the file.
Restart the OpenSSH SSH daemon.

[,console]
----
sudo systemctl restart sshd
sudo systemctl status sshd
----

The service should return to `active (running)`.
Try again to authorize from your client and then review the logs as follows.

Ubuntu:

----
sudo cat /var/log/auth.log
----

RedHat Enterprise Linux:

----
sudo cat /var/log/messages
----

[#_public-key-of-aporeto-ssh-certificate-authority-missing]
[.task]
==== Public key of Aporeto SSH certificate authority missing

The enforcer should download the public key of the Aporeto SSH certificate authority automatically, unless you opened your account before the release of 3.11.
If the enforcer fail to download the certificate, you can manually obtain this file using the following steps.

[NOTE]
====
This procedure requires https://stedolan.github.io/jq/download/[jq] on your local host. If you haven't already installed it, go ahead and do so now.
====

[.procedure]
. On your local host equipped with `apoctl`, set a `NAMESPACE` environment variable containing the Aporeto namespace of the target remote host.
An example follows.
+
----
export NAMESPACE=/acme/team-a/linux-hosts
----

. Issue the following command to download the public key of the Aporeto SSH certificate authority for the target namespace and save it to a file named `aporeto-sshca.pub`.
+
[,console]
----
apoctl api list trustedcas -n $NAMESPACE \
| jq -r '.[1] | .certificate' \
> sshca.pub
----

. Copy the public key of the certificate authority to the `/etc/ssh` directory on the remote host using the method of your choice.
The following example combines `tar` and `ssh` to copy the file to the root-owned `/etc/ssh` directory in a single command.
+
[,console]
----
tar -c aporeto-sshca.pub \
  | ssh -i $SSH_PRIVATE_KEY $LINUX_ACCOUNT@$SSH_HOST \
    "sudo tar -x --no-same-owner -C /usr/share/aporeto"
----

. SSH into the target remote host.
. Confirm that the file was successfully copied to the `/etc/ssh` directory.
+
[,console]
----
sudo ls -la /usr/share/aporeto/sshca.pub
----

. It should return something like the following.
+
----
-rw-r--r-- 1 root root 198 Aug  7 21:20 /usr/share/aporeto/sshca.pub
----

. Set the permissions of the file so that only the root user can write to it.
+
[,console]
----
sudo chmod 640 /usr/share/aporeto/sshca.pub
----

. Confirm that the file has the correct permissions.
+
[,console]
----
sudo ls -la /usr/share/aporeto/sshca.pub
----

. It should return something like the following.
+
----
-rw-r----- 1 root root 198 Aug  7 21:20 /usr/share/aporeto/sshca.pub
----
+
Good job!
//You can resume <<_continue-setup,Configuring the host at step 3>>.
