== Jobs are allowed to run on the Jenkins Controller

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|b648dc46-e31b-45f1-aa1e-aa5f685bcb3b 

|Severity
|High
// add severity level

|Category
|Pipeline Based Access Control (PBAC)
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|Jenkins

|=== 

=== Description 

The Jenkins instance allows jobs to run on the Jenkins Controller.
The Jenkins Controller is the original node in the Jenkins installation, responsible for administration operations on the Jenkins instance such as job orchestration, node management, and authentication.

Jenkins jobs can be run on the Jenkins Controller or on dedicated agents. Jobs are processes which can access the file system of the underlying execution environment, with the permissions of the operating system user account running the Jenkins process.

Jobs that run on the Jenkins Controller can access the Controller’s file system. Attackers executing a malicious build that runs on the Controller can perform impactful malicious actions on the Jenkins instance, such as getting stored credentials, managing authorization configurations and executing jobs.

For information regarding isolating the Jenkins Controller refer to the Jenkins documentation: https://www.jenkins.io/doc/book/security/controller-isolation/.

=== Recommended Solution - Buildtime

Prevent Jenkins jobs from running on the Controller:
 
. On the Jenkins instance, under **Manage Jenkins**, browse to **Configure System**.
. Set **# of executors** to **0**.

NOTE: Ensure that agents that fit the builds’ needs are configured on the instance.




