:topic_type: task
[.task]
== Set up OIDC on Azure

Complete the steps below to configure OIDC on Azure AD. Begin by first adding an OpenID application on Azure.

[.procedure]

. On the Azure portal, select *Azure Active Directory*.
. Select *Enterprise applications > All applications*.
. Select *New application* from the dialog box.
. Create the Prisma Cloud Config using the values listed below:
.. Client ID config element: Find this under AAD Registered Application → Overview. Use value of *Application (client) ID* under *Essentials* section.
.. Client Secret config element: Find this under AAD Registered Application → Secrets and Certificates. Generate a new Client Secret and use this value. Make sure you note the expiration date and set up a scheduled refresh.
.. Issuer config element: Find this here https://login.microsoftonline.com/
.. Auth URI config element: Find this here https://login.microsoftonline.com/common/oauth2/v2.0/authorize 
.. Token URI config element: Find this here https://login.microsoftonline.com/common/oauth2/v2.0/token 
.. JWK Set URI config element: https://login.microsoftonline.com/common/discovery/keys