== Prisma Cloud Application Security Policy Reference

Prisma Cloud Application Security offers a comprehensive scanning mechanism for detecting potential security issues that may arise in various aspects of software development. The scanning process is designed to cover a wide range of areas such as infrastructure as code, open source packages, and secrets security.

On Prisma Cloud, a policy is a set of one or more constraints or conditions that must be adhered to. Prisma Cloud provides predefined policies for configurations and access controls that adhere to established security best practices. These Prisma Cloud policies are shipped out-of-the-box and cannot be modified.
If you want to create custom policies for build-time checks, see https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-code-security/get-started/code-repositories-policy-management/code-editor[custom build policies].

This documentation includes information about the specific reasons for a policy violation, as well as actionable suggestions for resolving any issues that were detected during the code scanning process. The documentation also provides links to the Checkov repository for the code that represents the policy.
While some of the configuration policies in this document enable you to perform checks in the run and build phase of your resource deployment, the details in this documentation are only for the build phase of the policy.
On the Prisma Cloud management console, if you want to find all policies available for the build phase set the search filter for *Policy Sub Type* to *Build*. See https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/prisma-cloud-policies/manage-prisma-cloud-policies.html[manage policies] for details.
