== Prisma Cloud Reports

Keep your stakeholders updated on your organization's progress in securing your cloud environment, by sharing timely data on the status of your cloud assets, with Prisma Cloud *Reports*. Easily discover,create, and share reports on data such as compliance and configuration status, resources with open alerts, and more from one centralized location. You can now create a new report and access previously created reports from the top navigation panel on the Prisma Cloud administrative console. 

Focus in on the metrics that matter to you and your team.

The table below provides an at a glance look at the various types of *Reports* you can currently generate in Prisma Cloud. 

[cols="30%a,70%a"]
|===

|Report Type
|Description

|Alerts 
|You can generate two types of alerts reports:
* Cloud Security Assessment report: A PDF report that summarizes the risks from open alerts in monitored cloud accounts for any given cloud. 
* Business Unit report: A .csv file that lists all resources with open alerts trigerred by policies based on a compliance standard. Generate the report on an on-demand basis or set up a recurring schedule. 

|Compliance  
|Create reports based on a cloud compliance standard for immediate viewing or download, or schedule recurring reports to monitor compliance over time.  

|Cloud Security
|

|Command Center
|Share Command Center reports with stakeholders to keep them abreast of the security and compliance status of your cloud assets, as displayed on the Command Center dashboard. Select the *Generate Report* button to create and download a report. This generates the Top Cloud Risks and Incidents Report for that specific time range and selected account group(s).

|CloudLens 360
|

|===

=== Next Steps

* Create a Custom Report
* View Generated Reports
* Schedule a Report 
* .CSV Reports 
