== Alibaba Cloud RDS Instance SQL Collector Retention Period is less than 180


=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 466bb5f2-164f-40be-a59d-33c71d435be8

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RDSRetention.py[CKV_ALI_25]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description


SQL Collector is a feature of Alibaba Cloud RDS that allows you to collect and analyze SQL performance data for your instance. The SQL Collector Retention Period determines the length of time that SQL performance data is retained in the RDS instance. To maintain a longer history of SQL performance data, which is useful for troubleshooting and performance optimization, set the SQL Collector Retention Period to a value greater than 180 (180 days). 

=== Fix - Buildtime


*Terraform* 

To modify the SQL Collector Retention Period, add the following code to your Terraform file during buildtime.



[source,go]
----
resource "alicloud_db_instance" "pass" {
  engine                     = "MySQL"
  engine_version             = "5.6"
  instance_type              = "rds.mysql.t1.small"
  instance_storage           = "10"
  sql_collector_status       = "Enabled"
  sql_collector_config_value = 180
  parameters = [{
    name  = "innodb_large_prefix"
    value = "ON"
    }, {
    name  = "connect_timeout"
    value = "50"
    }, {
    name  = "log_connections"
    value = "ON"
  }]
}
----

