== Onboard Your Alibaba Cloud Account

Connect your Alibaba Cloud accounts to Prisma® Cloud to monitor the resources on your Alibaba cloud infrastructure. 

Use Prisma® Cloud for monitoring your Alibaba Cloud infrastructure in Mainland China and International regions.

To begin monitoring the resources on your cloud infrastructure, you must first create a role on Alibaba Cloud and then connect your Alibaba Cloud account to Prisma Cloud. When you add your account to Prisma Cloud, the API integration between your cloud infrastructure provider and Prisma Cloud is established, enabling you to monitor the resources and identify potential security risks in your infrastructure.

[cols="30%a,40%a"]
|===
|*What do you want to do?*
|*Start here*

|*First time onboarding of your cloud accounts*

Begin monitoring the resources on your Alibaba accounts
 
|* xref:set-up-your-alibaba-account.adoc[Set Up Your Alibaba Account]

* xref:add-alibaba-cloud-account-to-prisma-cloud.adoc[Add an Alibaba Cloud Account on Prisma Cloud]



|*Managing your cloud accounts*

Manage your onboarded Alibaba accounts

|* xref:manage-alibaba-account.adoc[Manage an Onboarded Alibaba Account]


|*Additional Resources*

Verify supported APIs

|* xref:alibaba-apis-ingested-by-prisma-cloud.adoc[Alibaba APIs Ingested by Prisma Cloud]

|===




