== GCP PostgreSQL instance database flag log_min_messages is not set


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 86150e32-f69c-400b-9bc2-444b03795545

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogMinMessage.py[CKV_GCP_55]

|Severity
|LOW

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


The *log_min_error_statement* database flag defines the minimum message severity level that is considered to be an error statement.
Messages for error statements are logged with the SQL statement.
Valid values include: DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1, INFO, NOTICE, WARNING, ERROR, LOG, FATAL, and PANIC.
Each severity level includes subsequent levels.
Deadlock timeout defines the time to wait on a lock before checking for any conditions.
Frequent runovers on deadlock timeout can be an indication of an underlying issue.
Log these waits on locks using the *log_lock_waits* database flag and use the information to identify poor performance due to locking delays, or if a specially-crafted SQL is attempting to starve resources through holding locks for excessive amounts of time.
We recommend you set the *log_min_error_statement* flag for PostgreSQL database instances in accordance with your organization's logging policy for auditing purposes.
Auditing helps you troubleshoot operational problems, and also permits forensic analysis.
If *log_min_error_statement* is not set to the correct value, messages may not be classified as error messages appropriately.
Considering general log messages as error messages would make it difficult to find actual errors, while considering only stricter severity levels as error messages may skip actual errors to log their SQL statements.

NOTE: To effectively turn off logging failing statements, set this parameter to PANIC.
ERROR is considered the best practice setting.
Changes should only be made in accordance with the organization's logging policy.


////
=== Fix - Runtime


* GCP Console To change the policy using the GCP Console, follow these steps:* 



. Log in to the GCP Console at https://console.cloud.google.com.

. Navigate to https://console.cloud.google.com/sql/instances [Cloud SQL Instances].

. Select the * PostgreSQL instance* where the database flag needs to be enabled.

. Click * Edit*.

. Scroll down to the * Flags* section.

. To set a flag that has not been set on the instance before, click * Add item*.

. Select the flag * log_min_error_statement* from the drop-down menu, and set an appropriate value.

. Click * Save*.

. Confirm the changes in the * Flags* section on the * Overview* page.


* CLI Command* 



. List all Cloud SQL database Instances using the following command: `gcloud sql instances list`

. Configure the log_min_error_statement database flag for every Cloud SQL PosgreSQL database instance using the below command.
+
`gcloud sql instances patch INSTANCE_NAME --database-flags  log_min_error_statement=& lt;DEBUG5|DEBUG4|DEBUG3|DEBUG2|DEBUG1|INFO|NOTICE|WARNI NG|ERROR|LOG|FATAL|PANIC>`
+
NOTE: This command will overwrite all database flags previously set. To keep those and add new ones, include the values for all flags to be set on the instance;
any flag not specifically included is set to its default value.
For flags that do not take a value, specify the flag name followed by an equals sign (*= *).

////

=== Fix - Buildtime


*Terraform* 


* *Resource:* google_sql_database_instance
* *Arguments:*  database_version = "POSTGRES_* " settings::database_flags: key:"log_min_messages", value:  by default set to "ERROR" Argument value can be one of the following: `DEBUG5`, `DEBUG4`, `DEBUG3`, `DEBUG2`, `DEBUG1`, `INFO`, `NOTICE`, `WARNING`, `ERROR`, `LOG`, `FATAL`, and `PANIC`


[source,go]
----
resource "google_sql_database_instance" "default" {
  name             = "master-instance"
  database_version = "POSTGRES_11"
  region           = "us-central1"

  settings {
+         database_flags {
+            name  = "log_min_messages"
+            value = "DEBUG5"
          }
  }
}
----
