== GCP PostgreSQL instance database flag log_temp_files is not set to 0


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2b9b082c-7e83-4695-92ab-8eca4c5dd4fd

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogTemp.py[CKV_GCP_56]

|Severity
|LOW

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


PostgreSQL can create a temporary file for actions such as sorting, hashing and temporary query results when these operations exceed *work_mem*.
The *log_temp_files* flag controls logging names and the file size when it is deleted.
Configuring *log_temp_files* to zero (*0*) causes all temporary file information to be logged, while positive values log only files whose size are greater than or equal to the specified number of kilobytes.
A value of *-1* disables temporary file information logging.
We recommend you set the *log_temp_files* database flag for Cloud SQL PostgreSQL instances is set to zero (*0*).
If temporary files are not logged, it may be difficult to identify potential performance issues caused by either poor application coding, or deliberate resource starvation attempts.

////
=== Fix - Runtime


* GCP Console To change the policy using the GCP Console, follow these steps:* 



. Log in to the GCP Console at https://console.cloud.google.com.

. Navigate to https://console.cloud.google.com/sql/instances [Cloud SQL Instances].

. Select the * PostgreSQL instance* where the database flag needs to be enabled.

. Click * Edit*.

. Scroll down to the * Flags* section.

. To set a flag that has not been set on the instance before, click * Add item*.

. Select the flag * log_temp_files* from the drop-down menu, and set its value to * 0*.

. Click * Save*.

. Confirm the changes in the * Flags* section on the * Overview* page.


* CLI Command* 



. List all Cloud SQL database instances using the following command: `gcloud sql instances list`

. Configure the log_temp_files database flag for every Cloud SQL PosgreSQL database instance using the below command.
+
``gcloud sql instances patch INSTANCE_NAME --database-flags log_temp_files=``0``

NOTE: This command will overwrite all database flags previously set.
+
To keep those and add new ones, include the values for all flags to be set on the instance;
+
any flag not specifically included is set to its default value.
+
For flags that do not take a value, specify the flag name followed by an equals sign ("=").
////
=== Fix - Buildtime


*Terraform* 


* *Resource:* google_sql_database_instance
* *Arguments:* database_version = "POSTGRES_* " settings::database_flags: key:"log_temp_files", value:  by default set to "-1"


[source,go]
----
resource "google_sql_database_instance" "default" {
  name             = "master-instance"
  database_version = "POSTGRES_11"
  region           = "us-central1"

  settings {
+         database_flags {
+            name  = "log_temp_files"
+            value = "0"
          }
  }
}
----

