== Gitlab branch protection rules allows force pushes


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7e633620-4449-47f6-8b20-42f125002d68

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/gitlab/checks/merge_requests_approvals.py[CKV_GITLAB_1]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|VCS

|=== 



=== Description 


In GitLab, permissions are fundamentally defined around the idea of having read or write permission to the repository and branches.
To impose further restrictions on certain branches, they can be protected.
When you perform more complex operations, for example, squash commits, reset or rebase your branch, you must force an update to the remote branch.
These operations imply rewriting the commit history of the branch.
Forcing an update is not recommended when you're working on shared branches.
You can enable force push on a protected branch, but this is ill-advised.

=== Fix - Buildtime


*Terraform* 


* *Resource:* gitlab_branch_protection
* *Attribute:* allow_force_push


[source,go]
----
resource "gitlab_branch_protection" "BranchProtect" {
...
-  allow_force_push             = true
+  allow_force_push             = false
...
}
----

