== Prisma Cloud on Pivotal Cloud Foundry: PAS and PKS

Prisma Cloud can be used to secure applications on both Pivotal Application
Service (PAS) and Pivotal Container Service (PKS).

=== Prisma Cloud on Pivotal Application Service (PAS)

The PCF Defender is delivered as a tile. Initially, Prisma Cloud supports
scanning droplets and blobstores. To use Prisma Cloud on PAS, go to the PCF
Ops Manager Installation Dashboard to install the tile.

For more complete details, see the support article on PAS
https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-guide-compute/vulnerability_management/pcf_blobstore.html[here].

=== Prisma Cloud on Pivotal Container Service (PKS)

PKS provides on-demand deployment of Kubernetes clusters with the
command line (CLI) and API using BOSH. Prisma Cloud supports the deployment
of both Console and Defender containers on your PKS nodes.

For more complete details, see the support article on PKS
https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-guide-compute/install/install_kubernetes.html[here].
