:topic_type: task
[.task]
[#_acs]
== Azure Container Service (ACS) with Kubernetes

Use the following procedure to install Prisma Cloud in an ACS Kubernetes cluster.

[NOTE]
====
https://azure.microsoft.com/en-us/updates/azure-container-service-will-retire-on-january-31-2020/[Microsoft will retire ACS] as a standalone service on January 31, 2020.
====

*Prerequisites*

* You have deployed an https://docs.microsoft.com/en-us/azure/container-service/kubernetes/[Azure Container Service with Kubernetes] cluster.

* You have installed https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest[Azure CLI 2.0.22] or later on a Linux system.

* You have <<_download_twistlock,downloaded the Prisma Cloud software>>.


[.procedure]
. Create a persistent volume for your Kubernetes cluster.
ACS uses Azure classic disks for the persistent volume.
Within the same Resource Group as the ACS instance, create a classic storage group.

. On a Windows based system use Disk Manager to create an unformatted, 100GB Virtual Hard Disk (VHD).

. Use https://azure.microsoft.com/en-us/features/storage-explorer/[Azure Storage Explorer] to upload the VHD to the classic storage group.

. Make sure the disk is 'released' from a 'lease'.

. On your Linux host with Azure CLI installed, attach to your ACS Kubernetes Master.

  $ az acs kubernetes get-credentials --resource-group pfoxacs --name pfox-acs
  Merged "pfoxacsmgmt" as current context in /Users/paulfox/.kube/config

  $ kubectl config use-context pfoxacsmgmt

. Confirm connectivity to the ACS Kubernetes cluster.
+
[source,bash]
----
$ kubectl get nodes
NAME                    STATUS    ROLES     AGE       VERSION
k8s-agent-e32fd1a6-0    Ready     agent     4m        v1.7.7
k8s-agent-e32fd1a6-1    Ready     agent     5m        v1.7.7
k8s-master-e32fd1a6-0   Ready     master    4m        v1.7.7
----

. Create a file named _persistent-volume.yaml_, and open it for editing.
+
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: twistlock-console
  labels:
    app: twistlock-console
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    diskName: pfox-classic-tl-console.vhd
    diskURI: https://pfoxacs.blob.core.windows.net/twistlock-console/pfox-classic-tl-console.vhd
    cachingMode: ReadWrite
    fsType: ext4
    readOnly: false
----
+
[horizontal]
`diskName`:: Name of the persistent disk created in the previous steps.
`labels`:: Label for the persistent volume.
`diskURI`:: Azure subscription path to the disk created in the previous steps.

. Create the persistent volume:
+
[source,bash]
----
  $ kubectl create -f ./persistent-volume.yaml
----

. Generate the Console YAML configuration file:
+
[source,bash]
----
  $ /linux/twistcli console export kubernetes \
    --persistent-volume-labels app:twistlock-console \
    --storage-class default
----
+
[horizontal]
`--persistent-volume-labels`:: _app:twistlock-console_ label defined in the persistent-volume.yaml.
`--storage-class`:: _default_ must match the storage class of the Azure Disk.

. Deploy the Prisma Cloud Console in your cluster.
+
[source,bash]
----
  $ kubectl create -f ./twistlock-console.yaml
----

. Wait for the service to come up completely.
+
[source,bash]
----
  $ kubectl get service -w -n twistlock
----

. Continue with the rest of the install <<_configure_console,here>>.