:topic_type: task
[.task]
[#id3d308e0b-921e-4cac-b8fd-f5a48521aa03]
== Access Prisma Cloud

Prisma Cloud offers two different experiences for first time access, based on whether you are a System Administrator or a User. Review the steps for your designated access level:

*Prisma Cloud System Administrators*

* Your Welcome Email from Palo Alto Networks (noreply@prismacloud.paloaltonetworks.com) includes a link to where you can access your instance of Prisma Cloud.
* Log into Prisma Cloud directly and view dashboards and complete other recommended workflows as mentioned in the xref:get-going.adoc[Get Started] section.
* Set up users manually or with xref:../administration/setup-sso-integration-on-prisma-cloud.adoc[SSO] or JIT provisioning.

*Prisma Cloud Users*

* If you are the first registered user, a Palo Alto Networks Customer Support Portal (CSP) account is created for you and you can log in to Prisma Cloud to start securing your cloud deployments.
* If a System Administrator added you to a tenant you will receive two emails. Use the _Welcome to Palo Alto Networks Support_ email to activate the CSP account and set a password to access the Palo Alto Networks Support portal. Select Get Started in the _Welcome to Palo Alto Networks Support_ email to log in to your Prisma Cloud instance.
* If your Prisma Cloud tenant is set up to authenticate using a third-party identity provider (IdP) for Single Sign-On (SSO), the login URL on Prisma Cloud redirects you to your IdP and you can log in using your IdP credentials. However, if the login URL is not configured on Prisma Cloud, you must navigate to your IdP and log in using your IdP credentials.

*Status Updates*—Use the https://status.paloaltonetworks.com[Prisma Cloud status] page to view operational status and subscribe to updates about the service.

[.procedure]
. Launch a web browser to access Prisma Cloud.
+
Go to the Palo Alto Networks https://apps.paloaltonetworks.com/[hub] to access the app.To access the Prisma Cloud administrator console, Chrome version 118 or later provides the optimal user experience. The Prisma Cloud console is not explicitly tested on other browsers and, though we expect it to perform with graceful degradation, it is not guaranteed to work on other browsers.
+
* https://app.prismacloud.io
* https://app2.prismacloud.io
* https://app3.prismacloud.io
* https://app4.prismacloud.io
* https://app5.prismacloud.io
* https://app.anz.prismacloud.io
* https://app.ca.prismacloud.io
* https://app.eu.prismacloud.io
* https://app2.eu.prismacloud.io
* https://app.fr.prismacloud.io
* https://app.gov.prismacloud.io
* https://app.ind.prismacloud.io
* https://app.jp.prismacloud.io
* https://app.sg.prismacloud.io
* https://app.prismacloud.cn
* https://app.uk.prismacloud.io
+
[NOTE]
====
On the hub, if you can see the Prisma Cloud tile in to the app because of a SAML error, it likely means that you do not have an account on that Prisma cloud instance. Contact your system administrator for an account to access that instance.
====

. Accept the EULA.
+
After you accept the terms and conditions of use, use the get started guide to learn the basics.

. Select *Licensing* and verify that you have the correct license type.

. Switch between Prisma Cloud instances.
+
If you are responsible for monitoring clouds belonging to different organizations (tenants), you can use your Palo Alto Networks login credentials to access all tenants from the https://apps.paloaltonetworks.com[hub]. To enable multitenant login access, your system administrator must add your email address on each Prisma Cloud tenant. You will then receive an email from Palo Alto Networks to get started. By default, an administrator on Prisma cloud is designated as an Instance Administrator for that tenant only on the hub. If you want to change a role or enable access to other apps, see xref:../administration/create-prisma-cloud-roles.adoc[roles].
+
With Palo Alto Networks CSP credentials, you can click the app switcher on the hub and then select a different tenant to which to switch between instances.
+
[NOTE]
====
If you see the serial number for your instance and want to change it to a descriptive label, navigate to *Settings > Applications*. Click directly on the serial number and rename it. This new name displays only on the hub and it does not automatically apply to your Prisma Cloud instance name.
====


[.task]
[#id3c964e17-24c6-4e7c-9a47-adae096cc88d]
=== Log in Using the Prisma Cloud URL

If you have accepted the EULA and have a Palo Alto Networks CSP account, you can access the Prisma Cloud app directly.

[.procedure]
. Access the Prisma Cloud App.
+
Enter your username and password. The URL is *<Prisma Cloud URL>*/auth/signin*

. *Sign in*.
+
If you have more than one tenant, select your *Tenant* to sign in.
+
If you have forgotten your password and are not using a third-party IdP, use the *Forgot Password* link to receive an email for resetting your password.
