== Code owners reviews are not required in GitHub before merging to the default branch

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|673480f9-613d-4a7a-af4f-e0f223e81334 

|Severity
|Medium 
// add severity level

|Category
|Flow Control Mechanisms 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

An actively used repository '*' does not require code owners reviews before merging to the default branch.
The *Code owners* feature enables repository owners to assign responsible individuals or teams for reviewing and approving changes to critical files or directories, ensuring that proposed modifications are assessed by knowledgeable developers. This helps reduce the risk of introducing vulnerabilities into the codebase by attackers or mistakes.

* An "actively used repository" is defined as having at least 2 contributors, over 50 commits, and having been updated in the last 90 days.

[.task]
=== Recommended Solution - Buildtime

Require code owners reviews before merging to the default branch: 

[.procedure]
. Create a `CODEOWNERS` file. 
+
The file location must be as specified in the link below. 
.. In the `CODEOWNERS` file, list the file patterns and the GitHub usernames of the code owners responsible for reviewing and approving changes to the designated files. 
+
For more information refer to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners.

.Create a branch protection rule. 
.. Navigate to the main page of the repository > *Settings* > click *Branches* under 'Code and automation'.
.. Select *Add branch protection rule* > Check the *Require pull request reviews before merging* section and select *Require review from Code Owners* from the dropdown.
+
For more information refer to https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule.

