==  Default branch does not require signed commits in GitHub

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|36e13064-e6d6-44ba-bed9-e55843504a91 

|Severity
|Low 
// add severity level

|Category
|Identity and Access Management 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Unsigned commits in GitHub present significant risks, including compromising code integrity and introducing uncertainty regarding authorship. If an attacker gains unauthorized access to a developer's account, they could impersonate the developer and make malicious code commits undetected. The absence of signed commits makes it exceedingly difficult to distinguish between fraudulent and legitimate commits.

=== Recommended Solution - Buildtime

It is recommended configuring a rule requiring the use of signed commits on the default branch:
. In GitHub, browse to the repository *Settings* > select *Branches* under *Code and automation*.
. Select *Add a branch protection rule* (or edit an existing one) on the relevant branch > Check the *Require signed commits* under *Protect matching branches* > *Create*.

To create a branch protection rule refer to https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule.

For additional information about signed commits refer to https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-signed-commits.
