== Forking of a private GitHub repository is allowed 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|76b4267b-e40b-45ed-aa6f-295b5c06f2ac 

|Severity
|Medium
// add severity level

|Category
|Data Protection
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 


=== Description 

Forking is allowed on private repositories, allowing user accounts with ‘read’ permissions only to fork a repository to another organization or user account.

This could lead to a decrease in security as SAML SSO may not be mandatory for authentication when accessing a forked repository.


Another security concern is that pull requests can be generated from forked repositories, which may result in a PPE attack.



=== Recommended Solution - Buildtime

We recommend preventing forking of repositories at the highest possible level (organization or enterprise, as applicable). Refer to the following instructions:
https://docs.github.com/en/organizations/managing-organization-settings/managing-the-forking-policy-for-your-organization

If the company policy allows forking repositories at the organization level, consider disabling forking of specific repositories.
To restrict forking of a private repository, refer to:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-forking-policy-for-your-repository


