== Forking of private repositories in the GitHub organization is allowed 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|ec963458-c440-469e-9637-d759e3148e55 

|Severity
|Medium
// add severity level

|Category
|Data Protection
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 


=== Description 

Forking is permitted on private repositories within an organization, enabling users with 'read' permissions to fork a repository to another organization or user account.

This could lead to a decrease in security as SAML SSO may not be mandatory for authentication when accessing a forked repository.

Another security concern is that pull requests can be generated from forked repositories, which may result in a https://www.cidersecurity.io/top-10-cicd-security-risks/poisoned-pipeline-execution-ppe/[PPE attack].


=== Recommended Solution - Buildtime

It is recommended to prevent forking of repositories at the highest possible level (organization or enterprise, as applicable). Refer to the following instructions: https://docs.github.com/en/organizations/managing-organization-settings/managing-the-forking-policy-for-your-organization.


