== Merging to default branch with outdated code allowed in GitHub  

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|38d0b93-e92a-4524-a891-2c95af81186f 

|Severity
|Low
// add severity level

|Category
|Flow Control Mechanisms 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Merging branches into the default branch without ensuring that they are up-to-date can present a security risk. This is because merging outdated code may omit the latest patches and updates from the main stream, including critical security fixes. As a result, potential vulnerabilities may persist, exposing the system to security threats.

=== Recommended Solution - Buildtime

Add branch protection rules to your repository, requiring that all branches must be up-to-date before being merged into the default branch.

For additional instructions, refer to https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging.

