== GitHub organization secret not scoped  

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|ad206bb2-23f5-4a21-bc6f-5b6cc9e89d5f 

|Severity
|Medium
// add severity level

|Category
|Credential Hygiene 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 


=== Description 

In GitHub organizations where secrets are not scoped to specific repositories and GitHub Actions is enabled, a malicious actor who has access to the organization could access these secrets by creating a workflow or modifying an existing workflow.
This creates a security risk, as sensitive information could be exposed to unauthorized parties.

=== Recommended Solution - Buildtime

It's important to scope organization secrets to specific repositories and grant permission on a need-to-access basis only, following the principle of least privilege.

To change the scope of a GitHub organization secret:

. Browse to the *Settings* tab of your GitHub organization's repository where the secret is located.
. Click on the *Secrets* menu located in the left-hand side of the page.
. Select the required secret and click on its name to open the details page.
. Click on the *Edit* button on the top right-hand corner of the page.
. Under *Repository access*, select the repositories that should have access to the secret.
. Click on the *Update secret* button to save the changes.

For more information refer to https://docs.github.com/en/enterprise-cloud@latest/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-organization.


