== GitHub organization’s identity not confirmed with a verified badge 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|cbadaed7-2b2e-4e0a-a33d-1487e1ba406d 

|Severity
|Info
// add severity level

|Category
|Flow Control Mechanisms 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

GitHub does not display a Verified Badge for the organization because the domain name associated with it has not been verified.

Verifying a domain name with GitHub provides an additional layer of integrity to your organization by displaying a Verified Badge on the organization’s profile, building trust and confidence both inside and outside of the organization.

=== Recommended Solution - Buildtime

Ensure that your organization verifies its domain name. 

For more information on how to approve your domains refer to https://docs.github.com/en/enterprise-cloud@latest/admin/configuration/configuring-your-enterprise/verifying-or-approving-a-domain-for-your-enterprise.
