== Unrestricted usage of GitHub Actions allowed in the repository

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|68fb2614-60c8-48aa-9aa1-4a0c7c02db44

|Severity
|High
// add severity level

|Category
|3rd Party Services
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Allowing all GitHub Actions to be used in the repository regardless of their author exposes the organization to the risk of a malicious actor taking control over an Action's repository. When using a hijacked Action in your pipeline, it can potentially execute malicious code, reaching the production environment.

=== Recommended Solution - Buildtime

Enforce policies to control how the repository can use GitHub Actions:

 
. Select repository **Settings** > **Actions** > **General** tab.
. If only using Actions defined in repositories within the enterprise, select the **Allow enterprise actions and reusable workflows** policy setting.

NOTE: If the above policy is too restrictive, consider allowing specific actions, actions created by GitHub and/or actions by Marketplace verified creators.

Prisma Cloud recommends configuring permissions at the highest level possible, that is Enterprise, if your license supports it, otherwise at organization level, as all child entities will by default inherit the parent permissions.

For more information refer to: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-git