== Required reviews can be bypassed using GitHub Actions   

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|f938aeb0-39fd-423f-ab6f-508f226eaa11

|Severity
|High
// add severity level

|Category
|Flow Control Mechanisms
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

NOTE: If the GitHub Actions setting which allows GitHub Actions reviews to count towards required approval is enabled in the GitHub organization, this should be considered a risk. Otherwise, it can be ignored.

Pushing unreviewed code to sensitive repository branches can be restricted by requiring users to create pull requests and receive approvals from other organization members before merging the code to the target branch. 
With GitHub Actions enabled, any user with **write** permissions on a repository can create and run GitHub Actions workflows, and grant the workflow Write permissions on the repository. 
The author of the workflow can then leverage this to instruct the Github Actions workflow to approve their pull request.
This vulnerability enables the author to approve their own pull request and merge unreviewed code to the target branch, effectively bypassing the multiple reviews security control.



=== Recommended Solution - Buildtime

If GitHub Actions is not used to approve pull requests, disallow it at the organization level:
 
. Browse to the **Actions** page under the GitHub organization settings.

. Clear the **Allow GitHub Actions reviews to count towards required approval** setting.

+
This will protect all organization repositories against the bypass.

If GitHub Actions is used to approve pull requests, ensure required reviews cannot be bypassed by following the guidelines below:
 
. Disable Actions in repositories where it is not in use:

.. Browse to **Organization Settings**.

.. Click Actions, and under Policies, restrict to specific repositories.

. For repositories where GitHub Actions is enabled:

.. Require a review approval in pull requests from Code Owners. This can be done by checking the **Require review from Code Owners** setting in the repository branch protection rule.

.. In cases where requiring approval from code owners is not possible, increase the required number of approvals to two or more, under the branch protection rule settings. 

+
This will prevent a single author from pushing unreviewed code to the target branch.







