== App-specific network intelligence

Prisma Cloud can learn about the settings for your apps from their configuration files, and use this knowledge to detect runtime anomalies.
No special configuration is required to enable this feature.

In addition to identifying ports that are exposed via the EXPOSE directive in a Dockerfile, or the -p argument passed to docker run, Prisma Cloud can identify port settings from an app’s configuration file.
This enables Prisma Cloud to detect, for example, if the app has been commandeered to listen on an unexpected port, or if a malicious process has managed to listen on the app’s port to steal data.

Consider the following scenario:

. You create an Apache image.
The default port for httpd, specified in _/etc/apache2/apache2.conf_, is 80.
In your _Dockerfile_, you use `EXPOSE` to bind port 80 in the container to port 80 on the host.

. A user runs your Apache image with the `-P` option, mapping port 80 in the container to a random ephemeral port on the host.

. The running container is compromised.
An attacker kills the Apache process, spawns a new process that listens on that port, and harvests data from other containers on the same subnet.

. Prisma Cloud detects the runtime anomaly, and either alerts you or blocks the container.

Prisma Cloud protects your containers by combining static analysis of the image with runtime analysis of the container.
The Prisma Cloud Intelligence Stream delivers app-specific knowledge so that Defender can inspect an image and:

* Identify processes that the container will execute.
* Correlate the processes with their configuration files.
* Parse the configuration files to extract information such as port assignments.

Runtime analysis completes the picture.
Some information can only be determined at runtime.
For example, MongoDB might be deployed to a container without a configuration file.
At runtime, MongoDB is launched with the `--port` parameter, dynamically specifying the port it will listen on.
Static analysis tells us that MongoDB is part of the container image, but in this case, only dynamic analysis tells us which port it listens on.

Additional apps will be added periodically, and your installation will be automatically updated via the Prisma Cloud Intelligence Stream.


=== Supported Apps

Prisma Cloud Intelligence Stream currently delivers app-specific knowledge for:

* Apache
* Elasticsearch
* HAProxy
* Kibana
* MariaDB
* MongoDB
* MySQL
* Nginx
* PostgreSQL
* RabbitMQ
* Redis
* Tomcat
* WordPress
* BusyBox

If you would like to see coverage for a specific app, open a support ticket and make a request.
