[#idf024bb91-d347-4f55-a407-f0b091d549a5]
== Governance

Learn about the different types of Prisma Cloud policies and how to manage them.

In Prisma Cloud, a policy is a set of one or more constraints or conditions that must be adhered to. Prisma Cloud provides predefined policies for configurations and access controls that adhere to established security best practices such as PCI, GDPR, ISO 27001:2013,and NIST, and a larger set of policies that enable you to validate security best practices with an impact beyond regulatory compliance. These Prisma Cloud default policies cannot be modified.

In addition to these predefined policies, you can create custom policies to monitor for violations and enforce your own organizational standards. You can use the Default policies as templates to create custom policies. After you set up the policies, any new or existing resources that violate these policies are automatically detected.

Prisma Cloud includes out-of-the-box (OOTB) policies that are part of the Prisma Cloud Recommended Policies Pack.

=== Governance at a Glance

[cols="60%a,30%a"]
|===

|*What do you want to do?*
|*Start here*

|Monitor your resource configurations for potential policy violations
|xref:create-a-policy.adoc#create-a-config-policy[Create a Configuration Policy]

|Monitor and flag audit events in your environment for potential policy violations
|xref:create-a-policy.adoc#create-an-audit-event-policy[Create an Audit Event Policy]

|Assess the possible attack paths that exploit your environment in a graphical representation when an attack path policy is violated
|xref:attack-path-policies.adoc[Create an Attack Path Policy]

|Enforce IAM policies to your resources and regulate access to only authorized users
|xref:create-an-iam-policy.adoc[Create an IAM Policy]

|Enforce network rules to govern the behaviors of network devices
|xref:create-a-network-policy.adoc[Create a Network Policy]

|Identify unusual user activity in your environment
|xref:anomaly-policies.adoc[Create an Anomaly Policies]

|Detect misconfigurations and provide automated fixes for security issues seen across your integrated code repositories and pipelines.
|xref:custom-build-policies/custom-build-policies.adoc[Custom Build Policies]

|Workload Protection policies

* Create vulnerability policies for hosts and create host rules to apply these policies on

* Create vulnerability policies for containers and create container rules to apply these policies on

* Create vulnerability policies for Serverless functions

|xref:workload-protection-policies.adoc[Workload Protection Policies]

xref:../runtime-security/vulnerability-management/vulnerability-management-policies.adoc[Vulnerability Management Policies]

|Detect potential threats across your environment
|xref:prisma-cloud-threat-detection.adoc[Prisma Cloud Threat Detection]

|===