#!/bin/bash
# Must set GITHUB_TOKEN and have access to private apoctl repo in aporeto-inc org
# Requires GNU sed, expects to use gsed
# Requires GNU csplit, expects to call it as gcsplit

export BRANCH=master


echo "Getting concepts"
curl --silent -o concepts.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/concepts/_index.md"
curl --silent -o enforcer-policy-pcc.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/diagrams/enforcer-policy-pcc.png"
curl --silent -o enforcer-tcp-pcc.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/diagrams/enforcer-tcp-pcc.png"
curl --silent -o pus.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/diagrams/pus.png"

echo "Splitting file"
gcsplit --prefix='concepts' --suffix-format='%03d.md' concepts.md '/^##\s/' "{*}"

rm concepts000.md

echo "Saving concepts: Segment Console"
pandoc concepts001.md -o concepts-console.adoc
mv concepts-console.adoc concepts/concepts-console.adoc
rm concepts001.md

echo "Saving concepts: Tags and identity"
pandoc concepts002.md -o concepts-tags.adoc
mv concepts-tags.adoc concepts/concepts-tags.adoc
rm concepts002.md

echo "Saving concepts: authn"
pandoc concepts003.md -o concepts-authn.adoc
mv concepts-authn.adoc concepts/concepts-authn.adoc
rm concepts003.md

echo "Saving concepts: authz"
pandoc concepts004.md -o concepts-authz.adoc
mv concepts-authz.adoc concepts/concepts-authz.adoc
rm concepts004.md

echo "Saving concepts: defender"
pandoc concepts005.md -o concepts-def.adoc
gsed -i -e 's/\/img\/diagrams\//:/g' concepts-def.adoc
mv concepts-def.adoc concepts/concepts-def.adoc
rm concepts005.md

echo "Saving concepts: pus"
pandoc concepts006.md -o concepts-pus.adoc
gsed -i -e 's/\/img\/diagrams\//:/g' concepts-pus.adoc
mv concepts-pus.adoc concepts/concepts-pus.adoc
rm concepts006.md

rm concepts.md

mv enforcer-tcp-pcc.png concepts/images/enforcer-tcp-pcc.png
mv enforcer-policy-pcc.png concepts/images/enforcer-policy-pcc.png
mv pus.png concepts/images/pus.png

###############
###############
###############

echo "Getting concepts: namespaces"
curl --silent -o namespaces.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/setup/namespaces/_index.md"
curl --silent -o ns-simple.svg -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/svgs/ns-simple.svg"
curl --silent -o ns-multi-tenant.svg -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/svgs/ns-multi-tenant.svg"

gsed -i -e 's/^{{< svg file="ns-simple\.svg" >}}/image::ns-simple\.png\[]\n/g' namespaces.md
gsed -i -e 's/^{{< svg file="ns-multi-tenant\.svg" >}}/image::ns-multi-tenant\.png\[]/g' namespaces.md

pandoc namespaces.md -o namespaces.adoc

gsed -i -e 's/^==/===/g' namespaces.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Namespaces\n' \
  namespaces.adoc

rm -f namespaces.md
rm -f concepts/namespaces.adoc
mv namespaces.adoc concepts/namespaces.adoc
mv ns-simple.svg concepts/images/ns-simple.svg
mv ns-multi-tenant.svg concepts/images/ns-multi-tenant.svg

###############
###############
###############

echo "Getting start: console"
curl --silent -o install-console.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/start/control-plane/small-deployments/_index.md"

pandoc install-console.md -o install-console.adoc

gsed -i -e 's/`kubectl -n segment exec console-0 -- pcc-binding https:\/\/54\.190\.67\.151:8083 acme`/`+kubectl -n segment exec console-0 -- pcc-binding https:\/\/54\.190\.67\.151:8083 acme+`/g' \
  install-console.adoc
gsed -i -e 's/`docker exec -it segment-console pcc-binding https:\/\/54\.190\.67\.151:8083 acme`/`+docker exec -it segment-console pcc-binding https:\/\/54\.190\.67\.151:8083 acme+`/g' \
  install-console.adoc

gsed -i -e 's/^==/===/g' install-console.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Install Segment Console\n' \
  install-console.adoc

rm -f install-console.md
rm -f start/install-console.adoc
mv install-console.adoc start/install-console.adoc

###############
###############
###############

echo "Getting start: apoctl"
curl --silent -o install-apoctl.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/start/apoctl/mac-linux/_index.md"
curl --silent -o create.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/create.png"

pandoc install-apoctl.md -o install-apoctl.adoc

gsed -i -e 's/^==/===/g' install-apoctl.adoc
gsed -i -e 's/\/img\/screenshots\///g' install-apoctl.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Install apoctl\n' \
  install-apoctl.adoc

rm -f install-apoctl.md
rm -f start/install-apoctl.adoc
mv install-apoctl.adoc start/install-apoctl.adoc
mv create.png start/images/create.png

###############
###############
###############

echo "Getting start: namespaces"
curl --silent -o create-ns.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/start/create-ns/_index.md"

pandoc create-ns.md -o create-ns.adoc

gsed -i -e 's/^==/===/g' create-ns.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Create namespaces\n' \
  create-ns.adoc

rm -f create-ns.md
rm -f start/create-ns.adoc
mv create-ns.adoc start/create-ns.adoc

###############
###############
###############

echo "Getting start: defender sys reqs"
curl --silent -o defender-reqs.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/start/enforcer/reqs/_index.md"

pandoc defender-reqs.md -o defender-reqs.adoc

gsed -i -e 's/^==/===/g' defender-reqs.adoc
gsed -i -e 's/\* _Y/pass:\[\*] _Y/g' defender-reqs.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== System requirements\n' \
  defender-reqs.adoc

rm -f defender-reqs.md
rm -f start/defender/defender-reqs.adoc
mv defender-reqs.adoc start/defender/defender-reqs.adoc

###############
###############
###############

echo "Getting start: defender linux"
curl --silent -o defender-linux.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/start/enforcer/linux/_index.md"

pandoc defender-linux.md -o defender-linux.adoc

gsed -i -e 's/^==/===/g' defender-linux.adoc
gsed -i -e 's/\* _Y/pass:\[\*] _Y/g' defender-linux.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Linux host\n' \
  defender-linux.adoc

rm -f defender-linux.md
rm -f start/defender/defender-linux.adoc
mv defender-host.adoc start/defender/defender-linux.adoc

###############
###############
###############

echo "Getting configure: trusted certs"
curl --silent -o trusted-certs.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/setup/trusted-certs/_index.md"

pandoc trusted-certs.md -o trusted-certs.adoc

gsed -i -e 's/^==/===/g' trusted-certs.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Using trusted certificates\n' \
  trusted-certs.adoc

rm -f trusted-certs.md
rm -f configure/trusted-certs.adoc
mv trusted-certs.adoc configure/trusted-certs.adoc


###############
###############
###############

echo "Getting secure: about"
curl --silent -o secure-about.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/secure/netpol/_index.md"
curl --silent -o net-pol-illustration2.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/net-pol-illustration2.png"

pandoc secure-about.md -o secure-about.adoc

gsed -i -e 's/^==/===/g' secure-about.adoc
gsed -i -e 's/\/img\/screenshots\//:/g' secure-about.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== About network policies\n' \
  secure-about.adoc

rm -f secure-about.md
rm -f secure/secure-about.adoc
mv secure-about.adoc secure/secure-about.adoc
mv net-pol-illustration2.png secure/images/net-pol-illustration2.png

###############
###############
###############

echo "Getting secure: malicious ips"
curl --silent -o secure-malips.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/secure/netpol/block-malicious-ips/_index.md"

pandoc secure-malips.md -o secure-malips.adoc

gsed -i -e 's/^==/===/g' secure-malips.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Blocking malicious IPs\n' \
  secure-malips.adoc

rm -f secure-malips.md
rm -f secure/secure-malips.adoc
mv secure-malips.adoc secure/secure-malips.adoc

###############
###############
###############

echo "Getting secure: allow web server"
curl --silent -o secure-web-server.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/secure/netpol/allow-web-server/_index.md"
curl --silent -o net-pol-web-server-reject.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/net-pol-web-server-reject.png"
curl --silent -o net-pol-web-server-allow.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/net-pol-web-server-allow.png"

pandoc secure-web-server.md -o secure-web-server.adoc

gsed -i -e 's/^==/===/g' secure-web-server.adoc
gsed -i -e 's/\/img\/screenshots\//:/g' secure-web-server.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Allowing access to web servers\n' \
  secure-web-server.adoc

rm -f secure-web-server.md
rm -f secure/secure-web-server.adoc
mv secure-web-server.adoc secure/secure-web-server.adoc
mv net-pol-web-server-reject.png secure/images/net-pol-web-server-reject.png
mv net-pol-web-server-allow.png secure/images/net-pol-web-server-allow.png

###############
###############
###############

echo "Getting secure: oidc"

curl --silent -o secure-oidc1.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/setup/idp/_index.md"
curl --silent -o secure-oidc2.md -H"Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/setup/idp/app/_index.md" 

gsed -i -e '1,12d' secure-oidc2.md

cat secure-oidc2.md >> secure-oidc1.md

curl --silent -o oidc-app-success-3.11.gif -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/oidc-app-success-3.11.gif"
curl --silent -o recursive-off2.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/recursive-off2.png"
curl --silent -o oidc-app-idp-allowed.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/oidc-app-idp-allowed.png"
curl --silent -o oidc-auth-app.svg -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/svgs/oidc-auth-app.svg"

gsed -i -e 's/^{{< svg file="oidc-auth-app\.svg" >}}/image::oidc-auth-app\.png\[]\n/g' secure-oidc1.md

pandoc secure-oidc1.md -o secure-oidc.adoc

gsed -i -e 's/^==/===/g' secure-oidc.adoc
gsed -i -e 's/\/img\/screenshots\//:/g' secure-oidc.adoc
gsed -i -e 's/`https:\/\/www\.example\.com`/`+https:\/\/www\.example\.com+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/www\.example\.com\/aporeto\/oidc\/callback`/`+https:\/\/www\.example\.com\/aporeto\/oidc\/callback+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/www\.example\.com:1443`/`+https:\/\/www\.example\.com:1443+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/www\.example\.com:1443\/aporeto\/oidc\/callback`/`+https:\/\/www\.example\.com:1443\/aporeto\/oidc\/callback+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/35\.193\.206\.162\.xip\.io`/`+https:\/\/35\.193\.206\.162\.xip\.io+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/dev-bzp6k6-2\.auth0\.com\/`/`+https:\/\/dev-bzp6k6-2\.auth0\.com\/+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/sts\.windows\.net\/cd629cb5-2826-4126-82fd-3f2df5f5bc7b\/`/`+https:\/\/sts\.windows\.net\/cd629cb5-2826-4126-82fd-3f2df5f5bc7b\/+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/sts\.windows\.net\/`/`+https:\/\/sts\.windows\.net\/+`/g' secure-oidc.adoc
gsed -i -e 's/`https:\/\/accounts\.google\.com`/`+https:\/\/accounts\.google\.com+`/g' secure-oidc.adoc
gsed -i -e 's/`https:\/\/dev-289699\.okta\.com\/oauth2\/default`/`+https:\/\/dev-289699\.okta\.com\/oauth2\/default+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/dev-289699\.okta\.com`/`+https:\/\/dev-289699\.okta\.com+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`https:\/\/dev-289699-admin\.okta\.com`/`+https:\/\/dev-289699-admin\.okta\.com+`/g' \
  secure-oidc.adoc
gsed -i -e 's/`email=bjoliet@email\.com`/`+email=bjoliet@email\.com+`/g' \
  secure-oidc.adoc
gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Authenticating users with OIDC\n' \
  secure-oidc.adoc

rm -f secure-oidc1.md
rm -f secure-oidc2.md
rm -f secure/secure-oidc.adoc
mv secure-oidc.adoc secure/secure-oidc.adoc
mv oidc-app-success-3.11.gif secure/images/oidc-app-success-3.11.gif
mv recursive-off2.png secure/images/recursive-off2.png
mv oidc-app-idp-allowed.png secure/images/oidc-app-idp-allowed.png
mv oidc-auth-app.svg secure/images/oidc-auth-app.svg

###############
###############
###############

echo "Getting scale: migrate"
curl --silent -o scale-migrate.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/scale/multi-node/_index.md"

pandoc scale-migrate.md -o scale-migrate.adoc

gsed -i -e 's/^==/===/g' scale-migrate.adoc
gsed -i -e 's/`https:\/\/segment.acme.com`/`+https:\/\/segment.acme.com+`/g' scale-migrate.adoc
gsed -i -e 's/`https:\/\/ui.segment.acme.com`/`+https:\/\/ui.segment.acme.com+`/g' scale-migrate.adoc
gsed -i -e 's/`https:\/\/api.segment.acme.com`/`+https:\/\/api.segment.acme.com+`/g' scale-migrate.adoc
gsed -i -e 's/`https:\/\/monitor.segment.acme.com`/`+https:\/\/monitoring.segment.acme.com+`/g' scale-migrate.adoc
gsed -i -e 's/`https:\/\/tracing.segment.acme.com`/`+https:\/\/tracing.segment.acme.com+`/g' scale-migrate.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Deploy Segment Console across multiple nodes\n' \
  scale-migrate.adoc

rm -f scale-migrate.md
rm -f scale/scale-migrate.adoc
mv scale-migrate.adoc scale/scale-migrate.adoc

###############
###############
###############

echo "Getting scale: pods nodes"
curl --silent -o scale-nodes-pods.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/scale/single-ctrl-plane/_index.md"

pandoc scale-nodes-pods.md -o scale-nodes-pods.adoc

gsed -i -e 's/^==/===/g' scale-nodes-pods.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Autoscale nodes and pods\n' \
  scale-nodes-pods.adoc

rm -f scale-nodes-pods.md
rm -f scale/scale-nodes-pods.adoc
mv scale-nodes-pods.adoc scale/scale-nodes-pods.adoc

###############
###############
###############

echo "Getting scale: add consoles"
curl --silent -o scale-add-consoles.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/scale/multi-ctrl-plane/_index.md"
curl --silent -o fed-initial.gif -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/fed-initial.gif"
curl --silent -o fed-cp-copy-cert.gif -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/fed-cp-copy-cert.gif"
curl --silent -o fed-cp-paste-cert.gif -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/fed-cp-paste-cert.gif"
curl --silent -o fed-cp-cert-repeat.gif -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/fed-cp-cert-repeat.gif"
curl --silent -o fed-trusted.gif -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/fed-trusted.gif"
curl --silent -o fed-allowed.gif -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/fed-allowed.gif"

pandoc scale-add-consoles.md -o scale-add-consoles.adoc

gsed -i -e 's/^==/===/g' scale-add-consoles.adoc
gsed -i -e 's/\/img\/screenshots\//:/g' scale-add-consoles.adoc
gsed -i -e 's/\[Replace me\]/\[width=800\]/g' scale-add-consoles.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Add Segment Consoles\n' \
  scale-add-consoles.adoc

rm -f scale-add-consoles.md
rm -f scale/scale-add-consoles.adoc
mv scale-add-consoles.adoc scale/scale-add-consoles.adoc
mv fed-initial.gif scale/images/fed-initial.gif
mv fed-cp-copy-cert.gif scale/images/fed-cp-copy-cert.gif
mv fed-cp-paste-cert.gif scale/images/fed-cp-paste-cert.gif
mv fed-cp-cert-repeat.gif scale/images/fed-cp-cert-repeat.gif
mv fed-trusted.gif scale/images/fed-trusted.gif
mv fed-allowed.gif scale/images/fed-allowed.gif

###############
###############
###############

echo "Getting monitoring"
curl --silent -o monitor.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/monitor/_index.md"
curl --silent -o ctrl-plane-grafana-main.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-main.png"
curl --silent -o ctrl-plane-grafana-operational.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-operational.png"
curl --silent -o ctrl-plane-grafana-resources-usage.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-resources-usage.png"
curl --silent -o ctrl-plane-grafana-aporeto-overview.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-aporeto-overview.png"
curl --silent -o ctrl-plane-grafana-aporeto-details.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-aporeto-details.png"
curl --silent -o ctrl-plane-grafana-resources-allocation.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-resources-allocation.png"
curl --silent -o ctrl-plane-grafana-mongodb.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-mongodb.png"
curl --silent -o ctrl-plane-grafana-traces.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-grafana-traces.png"

pandoc monitor.md -o monitor.adoc

gsed -i -e 's/^==/===/g' monitor.adoc
gsed -i -e 's/\/img\/screenshots\//:/g' monitor.adoc
gsed -i -e 's/\[Grafana\]/\[width=900\]/g' monitor.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Monitor\n' \
  monitor.adoc

rm -f monitor.md
rm -f maintain/monitor.adoc
mv monitor.adoc maintain/monitor.adoc
mv ctrl-plane-grafana-main.png maintain/images/ctrl-plane-grafana-main.png
mv ctrl-plane-grafana-operational.png maintain/images/ctrl-plane-grafana-operational.png
mv ctrl-plane-grafana-resources-usage.png maintain/images/ctrl-plane-grafana-resources-usage.png
mv ctrl-plane-grafana-aporeto-overview.png maintain/images/ctrl-plane-grafana-aporeto-overview.png
mv ctrl-plane-grafana-aporeto-details.png maintain/images/ctrl-plane-grafana-aporeto-details.png
mv ctrl-plane-grafana-resources-allocation.png maintain/images/ctrl-plane-grafana-resources-allocation.png
mv ctrl-plane-grafana-mongodb.png maintain/images/ctrl-plane-grafana-mongodb.png
mv ctrl-plane-grafana-traces.png maintain/images/ctrl-plane-grafana-traces.png

###############
###############
###############

echo "Getting back up"
curl --silent -o backup.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/backup/_index.md"

pandoc backup.md -o backup.adoc

gsed -i -e 's/^==/===/g' backup.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Back up\n' \
  backup.adoc

rm -f backup.md
rm -f maintain/backup.adoc
mv backup.adoc maintain/backup.adoc

###############
###############
###############

echo "Getting maintenance mode"
curl --silent -o maintenance-mode.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/scale/maintenance-mode/_index.md"
curl --silent -o ctrl-plane-clad-maintenance.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/screenshots/ctrl-plane-clad-maintenance.png"

pandoc maintenance-mode.md -o maintenance-mode.adoc

gsed -i -e 's/^==/===/g' maintenance-mode.adoc
gsed -i -e 's/\/img\/screenshots\//:/g' maintenance-mode.adoc
gsed -i -e 's/\[clad-maintenance\]/\[width=900\]/g' maintenance-mode.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Maintenance mode\n' \
  maintenance-mode.adoc

rm -f maintenance-mode.md
rm -f maintain/maintenance-mode.adoc
mv maintenance-mode.adoc maintain/maintenance-mode.adoc
mv ctrl-plane-clad-maintenance.png maintain/images/ctrl-plane-clad-maintenance.png

###############
###############
###############

echo "Getting troubleshooting: defender"
curl --silent -o defender.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/troubleshoot/defender/_index.md"

pandoc defender.md -o defender.adoc

gsed -i -e 's/^==/===/g' defender.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Defender\n' \
  defender.adoc

rm -f defender.md
rm -f troubleshoot/defender.adoc
mv defender.adoc troubleshoot/defender.adoc

###############
###############
###############

echo "Getting troubleshooting: console"
curl --silent -o console.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/troubleshoot/segment-console/_index.md"

pandoc console.md -o console.adoc

gsed -i -e 's/^==/===/g' console.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Segment Console\n' \
  console.adoc

rm -f console.md
rm -f troubleshoot/console.adoc
mv console.adoc troubleshoot/console.adoc

###############
###############
###############

echo "Getting API overview"
curl --silent -o api-overview.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/README.md"

pandoc api-overview.md -o api-overview.adoc

cat << EOF > about.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/gaia
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.

== About the Segment Console API

=== Overview

Segment Console exposes a RESTful API.
Clients of the Segment Console API include the Segment Console web interface and apoctl.

This section provides information about how to access the API, as well as full reference documentation.

We also provide an open-source Golang SDK in the following GitHub repositories.

- link:https://github.com/PaloAltoNetworks/gaia[gaia]: contains the model
- link:https://github.com/PaloAltoNetworks/manipulate[manipulate]: a library that performs create, read, update, and delete (CRUD) operations

$(sed -e '1,7d' < api-overview.adoc)
EOF

rm -f api-overview.md
rm -f api-overview.adoc
rm -f segment_console_api/about.adoc
mv about.adoc segment_console_api/about.adoc

###############
###############
###############

echo "Getting API reference"
curl --silent -o api-ref.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/documentation.md"
echo "Splitting file"
gcsplit --prefix='api-ref' --suffix-format='%03d.md' api-ref.md '/^##\s/' "{*}"

rm api-ref000.md
echo "Saving core"
pandoc api-ref001.md -o api-core.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core.adoc
mv api-core.adoc segment_console_api/api-core.adoc
rm api-ref001.md
echo "Saving core/account"
pandoc api-ref002.md -o api-core-account.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-account.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-account.adoc
mv api-core-account.adoc segment_console_api/api-core-account.adoc
rm api-ref002.md
echo "Saving core/authentication"
pandoc api-ref003.md -o api-core-authentication.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-authentication.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-authentication.adoc
mv api-core-authentication.adoc segment_console_api/api-core-authentication.adoc
rm api-ref003.md
echo "Saving core/billing"
pandoc api-ref004.md -o api-core-billing.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-billing.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-billing.adoc
mv api-core-billing.adoc segment_console_api/api-core-billing.adoc
rm api-ref004.md
echo "Saving core/enforcer"
pandoc api-ref005.md -o api-core-enforcer.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-enforcer.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-enforcer.adoc
mv api-core-enforcer.adoc segment_console_api/api-core-enforcer.adoc
rm api-ref005.md
echo "Saving core/monitoring"
pandoc api-ref006.md -o api-core-monitoring.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-monitoring.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-monitoring.adoc
mv api-core-monitoring.adoc segment_console_api/api-core-monitoring.adoc
rm api-ref006.md
echo "Saving core/namespace"
pandoc api-ref007.md -o api-core-namespace.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-namespace.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-namespace.adoc
mv api-core-namespace.adoc segment_console_api/api-core-namespace.adoc
rm api-ref007.md
echo "Saving core/policy"
pandoc api-ref008.md -o api-core-policy.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-policy.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-policy.adoc
mv api-core-policy.adoc segment_console_api/api-core-policy.adoc
rm api-ref008.md
echo "Saving core/processingunit"
pandoc api-ref009.md -o api-core-processingunit.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-processingunit.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-processingunit.adoc
mv api-core-processingunit.adoc segment_console_api/api-core-processingunit.adoc
rm api-ref009.md
echo "Saving core/tag"
pandoc api-ref010.md -o api-core-tag.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-tag.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-tag.adoc
mv api-core-tag.adoc segment_console_api/api-core-tag.adoc
rm api-ref010.md
echo "Saving core/workflow"
pandoc api-ref011.md -o api-core-workflow.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-core-workflow.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-core-workflow.adoc
mv api-core-workflow.adoc segment_console_api/api-core-workflow.adoc
rm api-ref011.md
echo "Saving debug"
pandoc api-ref012.md -o api-debug.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-debug.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-debug.adoc
mv api-debug.adoc segment_console_api/api-debug.adoc
rm api-ref012.md
echo "Saving ext/documentation"
pandoc api-ref013.md -o api-ext-documentation.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-ext-documentation.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-ext-documentation.adoc
mv api-ext-documentation.adoc segment_console_api/api-ext-documentation.adoc
rm api-ref013.md
echo "Saving integration/apiproxy"
pandoc api-ref014.md -o api-integration-apiproxy.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-integration-apiproxy.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-integration-apiproxy.adoc
mv api-integration-apiproxy.adoc segment_console_api/api-integration-apiproxy.adoc
rm api-ref014.md
echo "Saving integration/app"
pandoc api-ref015.md -o api-integration-app.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-integration-app.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-integration-app.adoc
mv api-integration-app.adoc segment_console_api/api-integration-app.adoc
rm api-ref015.md
echo "Saving integration/automation"
pandoc api-ref016.md -o api-integration-automation.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-integration-automation.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-integration-automation.adoc
mv api-integration-automation.adoc segment_console_api/api-integration-automation.adoc
rm api-ref016.md
echo "Saving internal/token"
pandoc api-ref017.md -o api-internal-token.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-internal-token.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-internal-token.adoc
mv api-internal-token.adoc segment_console_api/api-internal-token.adoc
rm api-ref017.md
echo "Saving internal/x509"
pandoc api-ref018.md -o api-internal-x509.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-internal-x509.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-internal-x509.adoc
mv api-internal-x509.adoc segment_console_api/api-internal-x509.adoc
rm api-ref018.md
echo "Saving policy/access"
pandoc api-ref019.md -o api-policy-access.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-access.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-access.adoc
mv api-policy-access.adoc segment_console_api/api-policy-access.adoc
rm api-ref019.md
echo "Saving policy/audit"
pandoc api-ref020.md -o api-policy-audit.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-audit.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-audit.adoc
mv api-policy-audit.adoc segment_console_api/api-policy-audit.adoc
rm api-ref020.md
echo "Saving policy/authorization"
pandoc api-ref021.md -o api-policy-authorization.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-authorization.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-authorization.adoc
mv api-policy-authorization.adoc segment_console_api/api-policy-authorization.adoc
rm api-ref021.md
echo "Saving policy/dns"
pandoc api-ref022.md -o api-policy-dns.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-dns.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-dns.adoc
mv api-policy-dns.adoc segment_console_api/api-policy-dns.adoc
rm api-ref022.md
echo "Saving policy/enforcerconfig"
pandoc api-ref023.md -o api-policy-enforcerconfig.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-enforcerconfig.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-enforcerconfig.adoc
mv api-policy-enforcerconfig.adoc segment_console_api/api-policy-enforcerconfig.adoc
rm api-ref023.md
echo "Saving policy/files"
pandoc api-ref024.md -o api-policy-files.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-files.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-files.adoc
mv api-policy-files.adoc segment_console_api/api-policy-files.adoc
rm api-ref024.md
echo "Saving policy/hooks"
pandoc api-ref025.md -o api-policy-hooks.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-hooks.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-hooks.adoc
mv api-policy-hooks.adoc segment_console_api/api-policy-hooks.adoc
rm api-ref025.md
echo "Saving policy/hosts"
pandoc api-ref026.md -o api-policy-hosts.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-hosts.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-hosts.adoc
mv api-policy-hosts.adoc segment_console_api/api-policy-hosts.adoc
rm api-ref026.md
echo "Saving policy/networking"
pandoc api-ref027.md -o api-policy-networking.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-networking.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-networking.adoc
mv api-policy-networking.adoc segment_console_api/api-policy-networking.adoc
rm api-ref027.md
echo "Saving policy/processingunits"
pandoc api-ref028.md -o api-policy-processingunits.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-processingunits.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-processingunits.adoc
mv api-policy-processingunits.adoc segment_console_api/api-policy-processingunits.adoc
rm api-ref028.md
echo "Saving policy/quota"
pandoc api-ref029.md -o api-policy-quota.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-quota.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-quota.adoc
mv api-policy-quota.adoc segment_console_api/api-policy-quota.adoc
rm api-ref029.md
echo "Saving policy/services"
pandoc api-ref030.md -o api-policy-services.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-services.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-services.adoc
gsed -i -e 's/`https:\/\/<hosts\[0\]|IPs\[0]>\/aporeto\/oidc\/callback`/`+https:\/\/<hosts\[0\]|IPs\[0]>\/aporeto\/oidc\/callback+`/g' api-policy-services.adoc
mv api-policy-services.adoc segment_console_api/api-policy-services.adoc
rm api-ref030.md
echo "Saving policy/ssh"
pandoc api-ref031.md -o api-policy-ssh.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-ssh.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-ssh.adoc
mv api-policy-ssh.adoc segment_console_api/api-policy-ssh.adoc
rm api-ref031.md
echo "Saving policy/token"
pandoc api-ref032.md -o api-policy-token.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-policy-token.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-policy-token.adoc
mv api-policy-token.adoc segment_console_api/api-policy-token.adoc
rm api-ref032.md
echo "Saving visualization/depmaps"
pandoc api-ref033.md -o api-visualization-depmaps.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-visualization-depmaps.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-visualization-depmaps.adoc
gsed -i -e 's/`map\[string]graphedge`/`+map\[string]graphedge+`/g' api-visualization-depmaps.adoc
gsed -i -e 's/`map\[string]graphgroup`/`+map\[string]graphgroup+`/g' api-visualization-depmaps.adoc
gsed -i -e 's/`map\[string]graphnode`/`+map\[string]graphnode+`/g' api-visualization-depmaps.adoc
mv api-visualization-depmaps.adoc segment_console_api/api-visualization-depmaps.adoc
rm api-ref033.md
echo "Saving visualization/statsquery"
pandoc api-ref034.md -o api-visualization-statsquery.adoc
gsed -i -e 's/\[`\[\]/\[`/g' api-visualization-statsquery.adoc
gsed -i -e 's/`format=\^\[\^\\\*\\=]\*\$`/`+format=\^\[\^\\\*\\=]\*\$+`/g' api-visualization-statsquery.adoc
mv api-visualization-statsquery.adoc segment_console_api/api-visualization-statsquery.adoc
rm api-ref034.md

rm api-ref.md

###############
###############
###############

echo "Getting apoctl usage"
curl --silent -o apoctl-ref.md -H "Authorization: token ${GITHUB_TOKEN}" "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/apoctl.md"

pandoc apoctl-ref.md -o apoctl-ref.adoc

cat << EOF > usage.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

== Usage

$(sed -e '1,2d' < apoctl-ref.adoc)
EOF

rm -f apoctl-ref.md
rm -f apoctl-ref.adoc
rm -f apoctl/usage.adoc
mv usage.adoc apoctl/usage.adoc

###############
###############
###############

echo "Getting apoctl api command"

curl --silent -o apoctl-api.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api.md"

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-all.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-count.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-create.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-delete.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-delete-many.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-describe.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-export.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-get.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-import.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-info.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-list.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-listen.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-search.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-stub.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-update.md" >> apoctl-api.md

echo >> apoctl-api.md

pandoc apoctl-api.md -o apoctl-api.adoc

cat << EOF > api.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-api.adoc)

EOF

rm -f apoctl-api.md
rm -f apoctl-api.adoc
rm -f apoctl/api.adoc
mv api.adoc apoctl/api.adoc

###############
###############
###############

echo "Getting apoctl appcred command"

curl --silent -o apoctl-appcred.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred.md"

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-create.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-delete.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-disable.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-enable.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-list.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-renew.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-roles.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-subnets.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

pandoc apoctl-appcred.md -o apoctl-appcred.adoc

cat << EOF > appcred.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-appcred.adoc)

EOF

rm -f apoctl-appcred.md
rm -f apoctl-appcred.adoc
rm -f apoctl/appcred.adoc
mv appcred.adoc apoctl/appcred.adoc

###############
###############
###############

echo "Getting apoctl auth command"

curl --silent -o apoctl-auth.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth.md"

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-appcred.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-cert.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-pcc.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-pcc-token.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-token.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-verify.md" >> apoctl-auth.md

echo >> apoctl-auth.md

pandoc apoctl-auth.md -o apoctl-auth.adoc

cat << EOF > auth.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-auth.adoc)

EOF

rm -f apoctl-auth.md
rm -f apoctl-auth.adoc
rm -f apoctl-auth.adoc
mv auth.adoc apoctl/auth.adoc

###############
###############
###############

echo "Getting apoctl defender command"

curl --silent -o apoctl-defender.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer.md"

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-coredump.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-counters.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-logs.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-packets.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-pcap.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-pustate.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-download.md" >> apoctl-defender.md

echo >> apoctl-defender.md

pandoc apoctl-defender.md -o apoctl-defender.adoc

cat << EOF > defender.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-defender.adoc)

EOF

rm -f apoctl-defender.md
rm -f apoctl-defender.adoc
rm -f apoctl-defender.adoc
mv defender.adoc apoctl/defender.adoc

###############
###############
###############

echo "Getting apoctl oam command"

curl --silent -o apoctl-oam.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/oam.md"

echo >> apoctl-oam.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/oam-ping.md" >> apoctl-oam.md

echo >> apoctl-oam.md

pandoc apoctl-oam.md -o apoctl-oam.adoc

cat << EOF > oam.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-oam.adoc)

EOF

rm -f apoctl-oam.md
rm -f apoctl-oam.adoc
rm -f apoctl-oam.adoc
mv oam.adoc apoctl/oam.adoc

###############
###############
###############

echo "Getting apoctl stats command"

curl --silent -o apoctl-stats.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/stats.md"

echo >> apoctl-stats.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/stats-info.md" >> apoctl-stats.md

echo >> apoctl-stats.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/stats-query.md" >> apoctl-stats.md

echo >> apoctl-stats.md

pandoc apoctl-stats.md -o apoctl-stats.adoc

cat << EOF > stats.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-stats.adoc)

EOF

rm -f apoctl-stats.md
rm -f apoctl-stats.adoc
rm -f apoctl-stats.adoc
mv stats.adoc apoctl/stats.adoc

###############
###############
###############

echo "Getting apoctl reports command"

curl --silent -o apoctl-reports.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/reports.md"

echo >> apoctl-reports.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/compliance.md" >> apoctl-reports.md

echo >> apoctl-reports.md

pandoc apoctl-reports.md -o apoctl-reports.adoc

cat << EOF > reports.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-reports.adoc)

EOF

rm -f apoctl-reports.md
rm -f apoctl-reports.adoc
rm -f apoctl-reports.adoc
mv reports.adoc apoctl/reports.adoc
