== 5.0.10 Release Notes

//'''
//
//title: 5.0.10
//type: list
//url: "/5.0/release-notes/5.0.10/"
//menu:
//  5.0:
//    parent: "release-notes"
//    identifier: 5.0.10
//    weight: 97
//
//'''

July 9, 2021

=== New Features

==== Duplicate option in the UI

You can now duplicate objects in the UI such as Rulesets and Network List. +
This can be helpful if you want to move an object from one level in the heirarchy to another.

==== Support for SuSE Linux

You can now deploy Enforcers on Linux hosts running the SuSE Linux 12.5 distribution.

==== IPV6 Support

IPv6 Support is now generally available (GA). If you use IPv6 and wish to monitor and control these connections using the Enforcer, pass the `--enable-ipv6` flag in the Enforcer configuration options.

=== Resolved issues

* *CNS-2277*: For already connected Enforcers, connectivity to the Microsegmentation Console is not lost when the TUF repository is unreacheable.
* *CNS-2263*: Traffic from Network list object are no longer rejected with drop reason "`missing token`".

=== Known issues

* *CNS-2469*: Invalid token error is reported for Enforcer versions 3.14.10 or lower.
* *CNS-2259*: On occasion, the App Dependency map times out when the volume of flows is high.

=== Deprecation notices

* *Namespace Editor role*: If you have any API authorizations using this role, migrate them to the Namespace Administrator role. We will remove the Namespace Editor role in a future release.
* *Host services*: If you are using host services, migrate to external networks and network rulesets. We will remove host services in a future release.
