== 5.06 Release Notes

The following table outlines the release particulars:

[cols="1,2"]
|===
|Version
|5.06

|Release date
|7 April 2021

|===

// LINK


=== New features

* Terminology changes
We have renamed the product, backend, commands, and files as follows.

[cols="1,2"]
|===
|Previous
|New
|Aporeto
|Prisma Cloud Identity-Based Microsegmentation (Microsegmentation)
|control plane
|Microsegmentation Console
|/etc/enforcer.conf	/var/lib/prisma-enforcer/prisma-enforcer.conf
|apoctl protect	apoctl enforcer install
|enforcerd
|prisma-enforcer.service

|===

// #17678
* Adds support for Istio 1.4 and later.
Starting with Istio 1.4, https://istio.io/latest/zh/docs/reference/config/security/istio.rbac.v1alpha1/[RBAC] was end-of-lifed in favor of https://istio.io/latest/docs/reference/config/security/authorization-policy/[Authorization Policy].

[.section]
==== Web-Application and API Security (WAAS)

This release substantianally advances CNAF's capabilities.
CNAF has been renamed to WAAS.
WAAS integrates web application and API protection capabilities into a single framework.


===Fixed Issues

* APO-146: You no longer have to manually issue the following commands before installing the enforcer on RHEL 8 and RHEL CoreOS 8 (used by OpenShift 4) hosts:
+
----
modprobe ip_tables
modprobe iptable_nat 
----

* CNS-126: Decommissioning an enforcer now removes all of its iptables rules.

=== Known issues

* CNS-153: When using relative time values with apoctl, the values must be in relation to Pacific Standard Time (PST). For example, if you are in France and want to retrieve the last five minues of flow logs, you could use -9h5m. Another workaround for this issue is to use absolute time values.

* CNS-1343: The enforcer fails to program external networks that use the ! operator on Red Hat Enterprise Linux 6.

* CNS-1356: You must use an enforcer profile to manually add the URL of the Microsegmentation Console API to as an excluded network for Red Hat Enterprise Linux 6 hosts. Failing to do so before installing the enforcer causes a complete lack of access to the host.

* CNS-1651: The enforcer fails to recover after a third party removes some of its iptables rules.

* CNS-1730: Traffic to the domain in an external network occasionally goes to Somewhere instead.

* CNS-1733: Deselecting Show policed flows in the Platform pane produces unexpected results.

* CNS-1755: Fonts in the web interface vanish on external monitors with a devicePixelRatio of 1.25.


=== Deprecation Notices

A future release will remove support for the following. Please plan accordingly.

* CoreOS, Oracle Enterprise Linux (OEL), and Red Hat Enterprise Linux (RHEL) 6: upgrade to CoreOS/OEL/RHEL 7 or later.

* Host services: migrate to external networks and network rulesets.

* Namespace Editor role: If you have any API authorizations using this role, migrate them to the Namespace Administrator role. We will remove the Namespace Editor role in a future release.
