== 5.0.14 Release Notes

//'''
//
//title: 5.0.14
//type: list
//url: "/5.0/release-notes/5.0.14/"
//menu:
//  5.0:
//    parent: "release-notes"
//    identifier: 5.0.14
//    weight: 91
//
//'''

Dec 1, 2021

=== New Features

==== TCP Services & Proxy Protocol

This release introducsed support for TCP services and proxy protocol. TCP services have to be configured when the destination processing unit (PU) in a rule-set is exposed through a TCP terminating load balancer. More details on this feature is covered in our https://docs.paloaltonetworks.com/content/dam/techdocs/en_US/pdf/prisma/prisma-cloud/5-0/tcp-services.pdf[TCP services docs]. 

=== Resolved Issues

* *CNS-2715*: 5.0.x enforcer continues to hold connections to inactive control plane after failover
* *CNS-3018*: Validation errors after upgrade from 3.14 to 5.0.12 enforcers, V1 network rules

=== Known Issues

* *CNS-3228*: Incomplete certificate cleanup during yum or apt uninstallation of the enforcer.
* *CNS-3830*: UI fails to update enforcer profiles from other namespaces
* *CNS-3651*: Inline tag prefix update/edit fails
* *CNS-3557*: Specific ICMP rules between PUs allow other traffic
