== Prisma Cloud on AWS China
//Review what is supported on Prisma Cloud on AWS China

To use Prisma Cloud to monitor and protect your deployments in the China regions of Ningxia and Beijing, you require a Prisma Cloud instance in China. 

The Prisma Cloud instance in China (app.cn) supports your AWS China deployments. For getting started, see xref:onboard-aws-org.adoc[Onboard Your AWS Organization] and xref:onboard-aws-account.adoc[Onboard Your AWS Account]

The following capabilities are not currently supported and are not available for the AWS China deployments:

* Prisma Cloud Compute, which enables you to secure containers and serverless functions is not available on the Prisma Cloud instance in China.

* Prisma Cloud Data Security, which enables you to discover and classify data stored in AWS S3 buckets and protect accidental exposure, misuse, or sharing of sensitive data is not available on the Prisma Cloud instance in China.

* Prisma Cloud does not support the following services:
+
** Amazon GuardDuty

** Amazon Translate

** Amazon QLDB

** AWS DataSync

** AWS Inspector

** AWS Organization

* AWS does not support the https://www.amazonaws.cn/en/about-aws/regional-product-services/[regional services].