== Access to resources on the GitLab server from GitLab services is not restricted

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|c22dc1ff-86ea-4de5-b10b-5759bc9f34ca

|Severity
|Low
// add severity level

|Category
|System Configuration
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitLab

|=== 

=== Description

The self-managed GitLab system is vulnerable to exploitation via webhooks. User accounts can create webhooks in the system, whose events are sent from the GitLab server. Malicious user accounts can abuse this webhook mechanism to send requests to services on the local GitLab server, or to addresses on the internal network that are accessible from the GitLab server. These requests can expose data and perform operations on the services.

=== Recommended Solution - Buildtime

Secure the self-managed GitLab server from malicious webhooks through the console or GitLab API.

==== Modify settings through the console
 
. In the **Admin Area**, browse to the **Settings** page. 

. Disable the following settings under Outbound Requests:
+

* **Allow requests to the local network from webhooks and services**

* **Allow requests to the local network from system hooks**


==== Modify settings through the API
 
. Refer to the instructions in the GitLab API documentation: https://docs.gitlab.com/ee/api/settings.html#change-application-settings.

. Set the following settings to **False**:
+
* **Allow_local_requests_from_system_hooks**
* **Allow_local_requests_from_web_hooks_and_services**
* **Allow_local_requests_from_web_hooks_and_services** 

If required, allow system hooks access to specific resources on the GitLab server or the internal network by setting an **allowlist** through the console or GitLab API:

==== Set an allowlist through the console
 
. In the **Admin Area**, browse to the **Settings** page > **Network** and expand the **Outbound Requests* section.
. Insert the allowed entries in the text box.
+

NOTE: 

* Separate entries by semicolons, commas or whitespaces (including newlines)
* Entries can take different formats, such as hostnames, IP addresses, and IP ranges, including IPv6. Ports can be included.

==== Set an allowlist through the API
 
. Follow the instructions on the GitLab API documentation:https://docs.gitlab.com/ee/api/settings.html#change-application-settings.

. Set the **outbound_local_requests_whitelist** setting to contain an array of allowed domains and/or addresses.

For additional information refer to the GitLab documentation: https://docs.gitlab.com/ee/security/webhooks.html#webhooks-and-insecure-internal-web-services.

