== GitLab repository missing NPM lock file 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|e47b4d62-ae9d-49cd-8b98-1be0a36a0ee0 

|Severity
|Medium
// add severity level

|Category
|Dependency Chains
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

The `package-lock.json` file includes information about the dependencies of a package, as well as the hashes of the downloaded packages and the source URLs. This information can be used to verify the integrity of the package installation. If a `package-lock.json` file is not used when running `npm ci` during the package build process, the packages will be installed without undergoing integrity checks provided by the `package-lock.json` file. This may lead to the package being tampered, which could potentially result in malicious code being executed in the pipeline or delivered to production.

=== Recommended Solution - Buildtime

It is recommended to store the `package-lock.json` file in the repository. If the lock file already exists in the local repository, make sure it’s not listed in the `.gitignore` file. If the file doesn’t exist you can generate it by issuing the `npm install --package-lock` command.



