== Prisma Cloud Compute Console Release Information

This section contains release notes and upgrade announcements for Compute Console in Prisma Cloud Enterprise Edition.
As we roll out upgrades, we will update this page with new announcements and information.
To prepare for upcoming upgrades, please carefully review the breaking changes highlighted for each release.


=== Upgrade plan for 20.09

This section highlights the upgrade schedule and plan for the upcoming 20.09 Compute release. 

**Date of Upgrade:** Tuesday, Sept. 29, 2020

All Compute Consoles in Prisma Cloud Enterprise Edition are scheduled to be automatically upgraded on Tuesday, September 29th between 12-3am PST. You may experience intermittent service interruptions during this time, due to the upgrade.


==== Major features and changes to Compute Console in Prisma Cloud Enterprise Edition

Please read through the following important updates and changes corresponding to the Prisma Cloud Integration of 20.09 Compute release.

**1. CNNF Deprecation**

Cloud Native Network Firewall will be deprecated in this release in favor of the future Identity-Based Microsegmentation feature, which will be made available in the platform for networking policies. Hence, effective this release, the Compute CNNF feature will no longer be available in Prisma Cloud Enterprise Edition (Compute SaaS)

**2. Non-Onboarded Cloud Account Resources**

Read-Only users will now have the ability to view data in Compute from Defenders that are deployed on Hosts that are outside of onboarded Prisma Cloud accounts. This data will also be available for viewing in the Licensing tab.

NOTE: As the upgrade progresses across our various regions (through September 23), this functionality may be available to certain customers sooner than others. However, it can only be used for Compute User Roles mapping after all regions are updated with that option and Compute is fully upgraded across all stacks on September 29. 

**3. Cloud Account Credential Share**

We’ve added the ability to import onboarded Cloud Account credentials from Prisma Cloud into the Compute Console. Credentials can be surfaced and used for registry scanning, cloud discovery, and other third party integrations.  

NOTE: As part of this feature, Cloud Account permissions in Prisma Cloud CFT and TFT templates will include Compute permissions by default on October 7th. You can check out the new permissions added for Compute on this page, once the release is published , here - https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloudrelease-notes/prisma-cloud-release-information/look-aheadplanned-updates-prisma-cloud.html

**4. Unified Licensing**

The Licensing tab will now display Credits (formerly known as Workloads) consumption across all resources, including Compute, in a single place with cloud account association. 

More Compute specific breaking changes and feature updates are available for viewing in our release notes page https://docs.paloaltonetworks.com/prisma/prisma-cloud/20-09/prisma-cloud-compute-edition-release-notes/release-information/release-notes-20-09[here].
