#%RAML 1.0
queryParameters:
  collections:
    type: string
    required: false
    description:
      "
      Retrieves objects (events, incidents, etc) from the specified collections.
      This query parameter accepts a comma-delimited list of collections.
      When no collections are specified, objects in the default collection 'All' are returned.
      In other words, all objects would be returned.
      "
