#%RAML 1.0

queryParameters:
  from:
    type: date-only
    required: false
    description:
      "
      Return objects (events, incidents, etc) starting from the specified date.
      Use full-date notation, as specified in [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
      The format for full-date notation is YYYY-MM-DD.
      Use the 'from' parameter with the 'to' parameter to select all objects in a date range.
      "
  to:
    type: date-only
    required: false
    description:
      "
      Return objects (events, incidents, etc) up until, and including, the specified date.
      Use full-date notation, as specified in [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14).
      The format for full-date notation is YYYY-MM-DD.
      Use the 'to' parameter with the 'from' parameter to select all objects in a date range.
      "
  offset:
    type: number
    required: false
    description:
      "
      Specifies the index of the first object (event, incident, etc) to return.
      The default value is 0.
      Use the 'offset' parameter with the 'limit' parameter to select specific objects in the collection.
      For example, to retrieve the second oldest object in the collection:\n\n
      GET https://<CONSOLE>/api/v1/audits/runtime/container?offset=1&limit=1
      "
  limit:
    type: number
    required: false
    description:
      "
      Specifies the maximum number of objects (events, incidents, etc) to return.
      If left unspecified, all objects are returned (optionally constrained by the 'offset' parameter).
      Use the 'limit' parameter with the 'offset' parameter to select specific objects in the collection.
      For example, to retrieve a single object (the oldest object in the collection):\n\n
      GET https://<CONSOLE>/api/v1/audits/runtime/container?offset=0&limit=1
      "
  sort:
    type: string
    required: false
    description:
      "
      Specifies the key in the JSON response object by which the returned results should be sorted.
      Any key in the JSON response object can be used.
      By default, objects are sorted in chronological order (most recent object first).
      Use the 'sort' parameter along with the 'reverse' parameter to specify a sort order.
      For example, to sort events alphabetically by hostname:\n\n
      GET https://<CONSOLE>/api/v1/audits/runtime/container?sort=hostname
      "
  reverse:
    type: boolean
    required: false
    description:
      "
      Specifies the sort order of the returned objects (events, incidents, etc).
      By default, reverse is false.
      The 'reverse' parameter is ignored if not passed with the 'sort' parameter.
      When false, results are sorted in the following order, depending on the sort key selected: oldest to newest (time); a to z (strings).
      When true, results are sorted in the following order, depending on the sort key selected: newest to oldest (time); z to a (strings).
      "
  search:
    type: string
    required: false
    description:
      "
      Retrieves all objects (events, incidents, etc) where the search string matches the value of msg in the response object.
      The value in msg provides a description of the event.
      Partial matches are supported.
      Therefore, the search string 'thor-1' would match 'thor-1.example.com'.
      The search parameter may match other fields, depending on the endpoint.
      "
  collections:
    type: string
    required: false
    description:
      "
      Retrieves objects (events, incidents, etc) from the specified collections.
      This query parameter accepts a comma-delimited list of collections.
      When no collections are specified, objects in the default collection 'All' are returned.
      In other words, all objects would be returned.
      "
