#%RAML 1.0
queryParameters:
 offset:
    type: number
    required: false
    description: !include descriptions/offset.md
 limit:
   type: number
   required: false
   description: !include descriptions/limit.md
