== GCP PostgreSQL instance database flag log_lock_waits is disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9570d08f-1795-493f-b88d-7a7a68078ff6

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/GoogleCloudPostgreSqlLogLockWaits.py[CKV_GCP_54]

|Severity
|LOW

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Deadlock timeout defines the time to wait on a lock before checking for any conditions.
Frequent runovers on deadlock timeout can be an indication of an underlying issue.
Log these waits on locks using the *log_lock_waits* database flag and use the information to identify poor performance due to locking delays, or if a specially-crafted SQL is attempting to starve resources through holding locks for excessive amounts of time.
We recommended you set the *log_lock_waits* flag for a PostgreSQL instance to *On*.
This will create a log for any session and allow you to identify waits that take longer than the allotted *deadlock_timeout* time to acquire a lock.

////
=== Fix - Runtime
Remediation


* GCP Console To change the policy using the GCP Console, follow these steps:* 



. Log in to the GCP Console at https://console.cloud.google.com.

. Navigate to https://console.cloud.google.com/sql/instances [Cloud SQL Instances].

. Select the * PostgreSQL instance* where the database flag needs to be enabled.

. Click * Edit*.

. Scroll down to the * Flags* section.

. To set a flag that has not been set on the instance before, click * Add item*.

. Select the flag * log_lock_waits* from the drop-down menu, and set its value to * On*.

. Click * Save*.

. Confirm the changes in the * Flags* section on the * Overview* page.


* CLI Command* 



. List all Cloud SQL database instances using the following command: `gcloud sql instances list`

. Configure the log_lock_waits database flag for every Cloud SQL PosgreSQL database instance using the below command: `gcloud sql instances patch INSTANCE_NAME --database-flags log_lock_waits=on`
+
NOTE: This command will overwrite all database flags previously set. To keep these flags, and add new ones, include the values for all flags to be set on the instance.
Any flag not specifically included is set to its default value.
For flags that do not take a value, specify the flag name followed by an equals sign (*=*).

////

=== Fix - Buildtime


*Terraform* 


* *Resource:* google_sql_database_instance
* *Arguments:*  database_version = "POSTGRES_* " settings::database_flags: key:"log_lock_waits", value:  by default set to "off"


[source,go]
----
resource "google_sql_database_instance" "default" {
  name             = "master-instance"
  database_version = "POSTGRES_11"
  region           = "us-central1"

  settings {
+         database_flags {
+            name  = "log_lock_waits"
+            value = "on"
          }
  }
}
----

