== MariaDB servers do not have public network access enabled set to False
// Azure MariaDB servers public network access enabled  


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| c9a786ca-5dc6-4a66-a303-3f9c0a863b52

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/MariaDBPublicAccessDisabled.py[CKV_AZURE_48]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Terraform, TerraformPlan

|=== 



=== Description 


It is generally a good security practice to ensure that your MariaDB servers do not have public network access enabled, as this means that they are only accessible from within your private network.
This can help to protect your database servers from unauthorized access, as external parties will not be able to connect to them over the internet.
It is especially important to ensure that public network access is disabled if your MariaDB servers contain sensitive or confidential data.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_mariadb_server
* *Arguments:* public_network_access_enabled is set to False.


[source,go]
----
resource "azurerm_mariadb_server" "example" {
   ...
+  public_network_access_enabled = false

}
----

