== Linux hosts

//'''
//
//title: Linux hosts
//type: single
//url: "/5.0/start/enforcer/linux/"
//weight: 40
//menu:
//  5.0:
//    parent: "deploy-enforcer"
//    identifier: "linux-enforcer"
//canonical: https://docs.aporeto.com/saas/start/enforcer/linux/
//
//'''

=== About Linux host installs

To deploy the enforcer to a Linux host not orchestrated by Kubernetes or OpenShift, use one of the following procedures.

|===
| Procedure | Installation method | Install authentication | Registration and connection authentication | Discussion

| *<<_cloud-install,Cloud>>*
| `apoctl`
| Short-lived token from AWS, GCP, or Azure
| Short-lived token from AWS, GCP, or Azure
| Requires no credentials saved on the host. You can run the procedure once, make an image of the host with the enforcer installed, and distribute the image.

| *<<_on-premise-install,On-premise>>*
| `apoctl`
| xref:../../concepts/app-cred-token.adoc[Microsegmentation token]
| Least-privilege xref:../../concepts/app-cred-token.adoc[app credential]
| The short-lived Microsegmentation token can include various restrictions to make it more comfortable to pass around.

| *<<_advanced-on-premise-install,Advanced on-premise>>*
| Manual
| xref:../../concepts/app-cred-token.adoc[Microsegmentation token]
| Least-privilege xref:../../concepts/app-cred-token.adoc[app credential]
| Does not require `apoctl` to be installed on the target host. Suitable for air-gapped environments.
|===

[.task]
[#_cloud-install]
=== Cloud install

[.procedure]
. Make sure you meet the following prerequisites.
+
[cols="1,3a"]
|===
|Entity |Requirement

|Target host(s)
|
* xref:reqs.adoc[Meets the system requirements]
* Set up to synchronize time with authoritative sources: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[AWS], https://cloud.google.com/compute/docs/instances/configure-ntp[GCP], https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync[Azure]
* Can connect to any subdomain of `aporeto.com`{domain-connectivity}

|Local host
|
* xref:../install-apoctl.adoc[`apoctl` installed]
* SSH access to target host(s)

|Privileges
|
* `namespace.administrator` privileges in the Microsegmentation namespace of the target host

|Cloud credentials
|
* _AWS_: https://aws.amazon.com/blogs/security/easily-replace-or-attach-an-iam-role-to-an-existing-ec2-instance-by-using-the-ec2-console/[an IAM role attached to the target host] with read-only access to tags (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policy-structure.html[`ec2:DescribeTags`])
* _GCP_: https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[GCP service account attached to the target host]
* _Azure_: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vmss[target host assigned a managed identity]
|===

. Construct a xref:../../concepts/tags-and-identity.adoc[Microsegmentation tag] that identifies your cloud account, project, tenant, or organization.
+
The tag must begin with `@auth:` followed by a key-value pair.
Refer to the table below for some common examples.
+
[cols="1,1,1,1"]
|===
|Cloud provider |Value |Microsegmentation tag syntax |Microsegmentation tag example

|AWS            | AWS account ID^1^                    | `@auth:account=<AWS_ACCOUNT_ID>`    | `@auth:account=942613894219`
|GCP            | GCP project ID                     | `@auth:projectid=<GCP_PROJECT_ID>`  | `@auth:projectid=acme-dev`
|Azure          | Microsoft tenant ID^2^ | `@auth:tenantid=<TENANT_ID>`        | `@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7`
|GCP and Azure  | Name of organization               | `@auth:organization=<ORGANIZATION>` | `@auth:organization=acme`
|===
+
^1^ You can find your AWS account ID under *My security credentials* in the AWS Management Console.
+
^2^ To learn how to find your tenant ID, refer to the https://techcommunity.microsoft.com/t5/Office-365/How-do-you-find-the-tenant-ID/td-p/89018[Microsoft documentation].

. On your local host, set a `CLOUD_ID_TAG` environment variable containing the Microsegmentation tag you've constructed to identify authorized enforcers.
+
If the target virtual machine is hosted on AWS, also set an `AWS_IAM_ROLE` environment variable containing the name of the IAM role attached to the instance prepended with `@auth:rolename=`.
For examples, see below.
+
AWS
+
[,console]
----
export CLOUD_ID_TAG="@auth:account=942613894219"
export AWS_IAM_ROLE="@auth:rolename=aporeto"
----
+
GCP
+
[,console]
----
export CLOUD_ID_TAG="@auth:projectid=acme-dev"
----
+
Azure
+
[,console]
----
export CLOUD_ID_TAG="@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7"
----

. Set a `TARGET_NS` environment variable containing the Microsegmentation namespace that this enforcer should register in.
+
It should be a grandchild namespace.
+
[,console,subs="+attributes"]
----
export TARGET_NS=/{parent-ns}/{child-ns}/vm1
----

. Use one of the following commands to create an API authorization that allows the enforcer to access the Microsegmentation Console.
+
Select the tab that corresponds to the cloud provider of the target host.
+
AWS
+
[,console]
----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: ec2-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $TARGET_NS
     authorizedSubnets: []
     name: Authorize EC2 enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=awssecuritytoken"
         - "$AWS_IAM_ROLE"
         - "$CLOUD_ID_TAG"
EOF
----
+
GCP
+
[,console]
----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: gcp-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $TARGET_NS
     authorizedSubnets: []
     name: Authorize GCP enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=gcpidentitytoken"
         - "$CLOUD_ID_TAG"
EOF
----
+
Azure
+
[,console]
----
cat << EOF | apoctl api import -f -
APIVersion: 0
label: azure-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $TARGET_NS
     authorizedSubnets: []
     name: Authorize Azure enforcer to access Microsegmentation Console
     propagate: true
     subject:
       - - "@auth:realm=azureidentitytoken"
         - "$CLOUD_ID_TAG"
EOF
----

. Retrieve the URL of your Microsegmentation Console API.
+
[,console]
----
echo $MICROSEG_API
----

. Access the target host, such as via SSH.

. Set a `MICROSEG_API` environment variable on the target host containing the URL of the Microsegmentation Console API you just echoed on your local host.
+
[,console,subs="+attributes"]
----
export MICROSEG_API=https://{ctrl-plane-api-url}
----

. Confirm that the host can connect to the Microsegmentation Console API and trusts its certificate.
+
[,console]
----
curl -fsL $MICROSEG_API
----

. Set a `TARGET_NS` environment variable containing the Microsegmentation namespace that this enforcer should register in.
+
It should be a grandchild namespace.
+
[,console,subs="+attributes"]
----
export TARGET_NS=/{parent-ns}/{child-ns}/vm1
----

. Install `apoctl` using the following command.
+
[,console,subs="+attributes"]
----
sudo curl -o /usr/local/bin/apoctl \
      {download-url}{version}/apoctl/linux/apoctl && \
sudo chmod 755 /usr/local/bin/apoctl
----

. Select the tab that corresponds to the init system of the host and run the provided commands to ensure that any local firewalls are disabled and stopped, as xref:reqs.adoc[required].
+
systemd
+
[,console]
----
sudo systemctl disable ufw
sudo systemctl stop ufw
sudo systemctl disable iptables
sudo systemctl stop iptables
sudo systemctl disable firewalld
sudo systemctl stop firewalld
----
+
upstart
+
[,console]
----
sudo disable ufw
sudo stop ufw
sudo disable iptables
sudo stop iptables
sudo disable firewalld
sudo stop firewalld
----
+
initd
+
[,console]
----
sudo /etc/init.d/ufw disable
sudo /etc/init.d/ufw stop
sudo /etc/init.d/iptables disable
sudo /etc/init.d/iptables stop
sudo /etc/init.d/firewalld disable
sudo /etc/init.d/firewalld stop
----

. Use the following command to install the enforcer.
+
[,console,subs="+attributes"]
----
 sudo apoctl enforcer install linux --auth-mode cloud \
                                    --namespace $TARGET_NS \
                                    --api $MICROSEG_API \
                                    --repo {repo-url}{version}
----
+
[TIP]
====
Refer to <<_enforcer-configuration-options,Enforcer configuration options>> if you wish to modify the enforcer's default settings.
You can also run `apoctl enforcer install linux -h` to review its flags.
You can find more information about the `enforcer install linux` command in the xref:../../apoctl/apoctl.adoc[`apoctl` reference page].
====

. Open the {console-web-interface}, select {agent-enforcer} under *Manage*, and navigate to the enforcer's namespace.
+
You should find your enforcer listed with a status of *connected*.
Click the enforcer and review its metadata.

. Select {platform-app-dep-map} in the side navigation menu.
+
You should see your host as a processing unit, with a dashed green line to a `Somewhere` external network.
Your host is in discovery mode.

. Return to your terminal on the target host.

. Remove `apoctl`.
+
[,console]
----
sudo rm /usr/local/bin/apoctl
----

. Refer to xref:../../secure/hosts.adoc[Securing host communications] to learn how to allow the desired traffic and disable discovery mode.

[.task]
[#_on-premise-install]
=== On-premise install

[.procedure]
. Ensure that you meet the following prerequisites.
+
[cols="1,3"]
|===
|Entity |Requirement

|Target host(s)
|
* xref:reqs.adoc[Meets the system requirements]
* https://linux.die.net/man/8/ntpd[Set up to synchronize time with authoritative sources]
* https://curl.haxx.se/[curl] installed
* Can connect to the Microsegmentation Console API without TLS interception
* Can connect to any subdomain of `aporeto.com`{domain-connectivity}

|Local host
|
* xref:../install-apoctl.adoc[`apoctl` installed]
* SSH access to target host(s)

|Privileges
|
* `namespace.administrator` privileges in the Microsegmentation namespace of the target host +
* User account on target host can `sudo` to gain root privileges without entering a password
|===

. From your local host, generate a short-lived Microsegmentation token that the enforcer can exchange for an app credential.
+
You can set a variety of restrictions on this token.
If you're in a hurry, just copy and paste the minimally restricted example below.
The other tabs illustrate optional additional restrictions, such as requiring the enforcer to register in a specified namespace or make its request from a specific subnet.
+
Minimally restricted example
+
[,console]
----
apoctl auth appcred --path ~/.apoctl/default.creds \
                    --restrict-role @auth:role=enforcer \
                    --restrict-role @auth:role=enforcer-installer \
                    --validity 60m
----
+
Fully restricted example
+
[,console,subs="+attributes"]
----
apoctl auth appcred --path ~/.apoctl/default.creds \
                    --restrict-role @auth:role=enforcer \
                    --restrict-role @auth:role=enforcer-installer \
                    --validity 60m \
                    --restrict-namespace /{parent-ns}/{child-ns}/vm1 \
                    --restrict-network 10.0.0.0/8
----
+
Syntax
+
[,console]
----
apoctl auth appcred --path <app-credential-file> \
                    --restrict-role @auth:role=enforcer \
                                    @auth:role=enforcer-installer \
                    --validity <golang-duration> \
                    [--restrict-namespace <namespace>] \
                    [--restrict-network <cidr>]
----

. Retrieve the URL of your Microsegmentation Console API.
+
[,console]
----
echo $MICROSEG_API
----

. Access the target host, such as via SSH.

. Set a `TOKEN` environment variable containing the token you just generated.
+
We've truncated the example token value below for readability.
+
[,console]
----
export TOKEN=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsbSI6IkNlcnRpZmljYXRlIiwiZGF0YSI6eyJjb21tb25O....
----

. Set a `MICROSEG_API` environment variable containing the URL of the Microsegmentation Console API you just retrieved.
+
[,console,subs="+attributes"]
----
export MICROSEG_API=https://{ctrl-plane-api-url}
----

. Confirm that the host can connect to the Microsegmentation Console API and trusts its certificate.
+
[,console]
----
curl -fsL $MICROSEG_API
----

. Set a `TARGET_NS` environment variable containing the Microsegmentation namespace of this enforcer.
+
It should be a grandchild namespace.
+
[,console,subs="+attributes"]
----
export TARGET_NS=/{parent-ns}/{child-ns}/vm1
----

. Install `apoctl` using the following command.
+
[,console,subs="+attributes"]
----
sudo curl -o /usr/local/bin/apoctl \
      {download-url}{version}/apoctl/linux/apoctl && \
sudo chmod 755 /usr/local/bin/apoctl
----

. Select the tab that corresponds to the init system of the host and run the provided commands to ensure that any local firewalls are disabled and stopped, as xref:reqs.adoc[required].
+
systemd
+
[,console]
----
sudo systemctl disable ufw
sudo systemctl stop ufw
sudo systemctl disable iptables
sudo systemctl stop iptables
sudo systemctl disable firewalld
sudo systemctl stop firewalld
----
+
upstart
+
[,console]
----
sudo disable ufw
sudo stop ufw
sudo disable iptables
sudo stop iptables
sudo disable firewalld
sudo stop firewalld
----
+
initd
+
[,console]
----
sudo /etc/init.d/ufw disable
sudo /etc/init.d/ufw stop
sudo /etc/init.d/iptables disable
sudo /etc/init.d/iptables stop
sudo /etc/init.d/firewalld disable
sudo /etc/init.d/firewalld stop
----

. Use the following command to install the enforcer.
+
[,console,subs="+attributes"]
----
 sudo apoctl enforcer install linux --token $TOKEN \
                                    --auth-mode appcred \
                                    --namespace $TARGET_NS \
                                    --api $MICROSEG_API \
                                    --repo {repo-url}{version}
----
+
[TIP]
====
Refer to <<_enforcer-configuration-options,Enforcer configuration options>> if you wish to modify the enforcer's default settings.
You can also run `apoctl enforcer install linux -h` to review its flags.
You can find more information about the `enforcer install linux` command in the xref:../../apoctl/apoctl.adoc[`apoctl` reference page].
====

. Open the {console-web-interface}, select {agent-enforcer} under *Manage*, and navigate to the enforcer's namespace.
+
You should find your enforcer listed with a status of *connected*.
Click the enforcer and review its metadata.

. Select {platform-app-dep-map} in the side navigation menu.
+
You should see your host as a processing unit, with a dashed green line to a `Somewhere` external network.
Your host is in discovery mode.

. Return to your terminal on the target host.

. Remove `apoctl` and clear `TOKEN`.
+
[,console]
----
 sudo rm /usr/local/bin/apoctl
 export TOKEN=""
----

. Refer to xref:../../secure/hosts.adoc[Securing host communications] to learn how to allow the desired traffic and disable discovery mode.

[.task]
[#_advanced-on-premise-install]
=== Advanced on-premise install

[.procedure]
. Ensure that you meet the following prerequisites.
+
[cols="1,3a"]
|===
|Entity |Requirement

|Target host(s)
|
* xref:reqs.adoc[Meets the system requirements]
* https://linux.die.net/man/8/ntpd[Set up to synchronize time with authoritative sources]
* https://curl.haxx.se/[curl] installed
* Can connect to the Microsegmentation Console API without TLS interception
* Can connect to any subdomain of `aporeto.com`{domain-connectivity}

|Local host
|
* xref:../install-apoctl.adoc[`apoctl` installed]
* SSH access to target host(s)

|Privileges
|
* `namespace.administrator` privileges in the Microsegmentation namespace of the target host
* User account on target host can `sudo` to gain root privileges without entering a password
|===

. From your local host, generate a short-lived Microsegmentation token that the enforcer can exchange for an app credential.
+
You can set a variety of restrictions on this token.
If you're in a hurry, just copy and paste the minimally restricted example below.
The other tabs illustrate optional additional restrictions, such as requiring the enforcer to register in a specified namespace or make its request from a specific subnet.
+
Minimally restricted example
+
[,console]
----
apoctl auth appcred --path ~/.apoctl/default.creds \
                    --restrict-role @auth:role=enforcer \
                    --validity 60m
----
+
Fully restricted example
+
[,console,subs="+attributes"]
----
apoctl auth appcred --path ~/.apoctl/default.creds \
                    --restrict-role @auth:role=enforcer \
                    --validity 60m \
                    --restrict-namespace /{parent-ns}/{child-ns}/vm1 \
                    --restrict-network 10.0.0.0/8
----
+
Syntax
+
[,console]
----
apoctl auth appcred --path <app-credential-file> \
                    --restrict-role @auth:role=enforcer \
                    --validity <golang-duration> \
                    [--restrict-namespace <namespace>] \
                    [--restrict-network <cidr>]
----

. Retrieve the URL of your Microsegmentation Console API.
+
[,console]
----
echo $MICROSEG_API
----

. Access the target host, such as via SSH.

. Set a `TOKEN` environment variable containing the token you just generated.
+
We've truncated the example token value below for readability.
+
[,console]
----
export TOKEN=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsbSI6IkNlcnRpZmljYXRlIiwiZGF0YSI6eyJjb21tb25O....
----

. Set a `MICROSEG_API` environment variable containing the URL of the Microsegmentation Console API you just retrieved.
+
[,console,subs="+attributes"]
----
export MICROSEG_API=https://{ctrl-plane-api-url}
----

. Confirm that the host can connect to the Microsegmentation Console API and trusts its certificate.
+
[,console]
----
curl -fsL $MICROSEG_API
----

. We will pull the images from your Microsegmentation Console.
+
You can review the metadata at `$MICROSEG_API/_meta/config`.
Use the following commands to set environment variables containing the paths to your TUF repository, the RPM/DEB repository, and the GPG key used to sign the packages.
+
[,console]
----
TUF_REPO="$(curl -sfSL $MICROSEG_API/_meta/config | sed -n 's/"//g;s/,//;s/.*tuf: //p;')"
RPM_DEB_REPO="$(curl -sfSL $MICROSEG_API/_meta/config | sed -n 's/"//g;s/,//;s/.*repo: //p;')"
GPG_KEY="$(curl -sfSL $MICROSEG_API/_meta/config | sed -n 's/"//g;s/,//;s/.*repo-signing-key: //p;')"
----

. Set a `TARGET_NS` environment variable containing the Microsegmentation namespace of this enforcer.
+
It should be a grandchild namespace.
+
[,console,subs="+attributes"]
----
export TARGET_NS=/{parent-ns}/{child-ns}/vm1
----

. Select the tab that corresponds to the init system of the host and run the provided commands to ensure that any local firewalls are disabled and stopped, as xref:reqs.adoc[required].
+
systemd
+
[,console]
----
sudo systemctl disable ufw
sudo systemctl stop ufw
sudo systemctl disable iptables
sudo systemctl stop iptables
sudo systemctl disable firewalld
sudo systemctl stop firewalld
----
+
upstart
+
[,console]
----
sudo disable ufw
sudo stop ufw
sudo disable iptables
sudo stop iptables
sudo disable firewalld
sudo stop firewalld
----
+
initd
+
[,console]
----
sudo /etc/init.d/ufw disable
sudo /etc/init.d/ufw stop
sudo /etc/init.d/iptables disable
sudo /etc/init.d/iptables stop
sudo /etc/init.d/firewalld disable
sudo /etc/init.d/firewalld stop
----

. Use the command that corresponds to the operating system of the target host to download and install the enforcer.
+
Ubuntu
+
[,console]
----
 curl -fsL $GPG_KEY | sudo apt-key add -
 echo "deb [arch=$(dpkg --print-architecture)] \
 $RPM_DEB_REPO/ubuntu/$(lsb_release -cs) aporeto main" \
 | sudo tee /etc/apt/sources.list.d/aporeto.list
 sudo apt update
 sudo apt install -y prisma-enforcer
----
+
Debian
+
[,console]
----
 sudo apt install -y apt-transport-https
 curl -fsL $GPG_KEY | sudo apt-key add -
 echo "deb [arch=$(dpkg --print-architecture)] \
 $RPM_DEB_REPO/debian/$(lsb_release -cs) aporeto main" \
 | sudo tee /etc/apt/sources.list.d/aporeto.list
 sudo apt update
 sudo apt install -y prisma-enforcer
----
+
CentOS
+
[,console]
----
 cat << EOF | sudo tee /etc/yum.repos.d/Aporeto.repo
 [Aporeto]
 name=aporeto
 baseurl=$RPM_DEB_REPO/centos/\$releasever/
 gpgkey=$GPG_KEY
 gpgcheck=1
 repo_gpgcheck=1
 enabled=1
 EOF
 sudo yum install -y prisma-enforcer
----
+

RedHat
+
[,console]
----
 cat << EOF | sudo tee /etc/yum.repos.d/Aporeto.repo
 [Aporeto]
 name=aporeto
 baseurl=$RPM_DEB_REPO/rhel/\$releasever/
 gpgkey=$GPG_KEY
 gpgcheck=1
 repo_gpgcheck=1
 enabled=1
 EOF
 sudo yum install -y prisma-enforcer
----
+
Amazon Linux 2
+
[,console]
----
 cat << EOF | sudo tee /etc/yum.repos.d/Aporeto.repo
 [Aporeto]
 name=aporeto
 baseurl=$RPM_DEB_REPO/nodist/yum/
 gpgkey=$GPG_KEY
 gpgcheck=1
 repo_gpgcheck=1
 enabled=1
 EOF
 sudo yum install -y prisma-enforcer
----

. Issue the command that corresponds to your desired configuration and the init system of the target host.
+
systemd
+
[,console]
----
echo "CNS_AGENT_TOKEN=$TOKEN" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "CNS_AGENT_ENFORCER_FIRST_INSTALL_VERSION=" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_PERSIST_CREDENTIALS=true" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_API=$MICROSEG_API" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_ENABLE_HOST_MODE=true" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_NAMESPACE=$TARGET_NS" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "CNS_AGENT_TUF_REPO=$TUF_REPO" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
sudo systemctl enable --now prisma-enforcer
sudo systemctl status prisma-enforcer
----
+
upstart
+
[,console]
----
echo "CNS_AGENT_TOKEN=$TOKEN" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "CNS_AGENT_ENFORCER_FIRST_INSTALL_VERSION=" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_PERSIST_CREDENTIALS=true" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_API=$MICROSEG_API" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_ENABLE_HOST_MODE=true" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_NAMESPACE=$TARGET_NS" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "CNS_AGENT_TUF_REPO=$TUF_REPO" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
sudo start prisma-enforcer
sudo status prisma-enforcer
----
+
initd
+
[,console]
----
echo "CNS_AGENT_TOKEN=$TOKEN" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "CNS_AGENT_ENFORCER_FIRST_INSTALL_VERSION=" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_TOKEN=$TOKEN" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_PERSIST_CREDENTIALS=true" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_API=$MICROSEG_API" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_ENABLE_HOST_MODE=true" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "ENFORCERD_NAMESPACE=$TARGET_NS" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
echo "CNS_AGENT_TUF_REPO=$TUF_REPO" | sudo tee -a /var/lib/prisma-enforcer/prisma-enforcer.conf
sudo /etc/init.d/prisma-enforcer start
sudo /etc/init.d/prisma-enforcer status
----
+
[TIP]
====
* For versions of `systemctl` prior to 220, you may need to start and enable the service in two commands.
* Refer to <<_enforcer-configuration-options,Enforcer configuration options>> for other environment variables you can set to modify the enforcer's default settings.
====

. Open the {console-web-interface}, select {agent-enforcer} under *Manage*, and navigate to the enforcer's namespace.
+
You should find your enforcer listed with a status of *connected*.
Click the enforcer and review its metadata.

. Select {platform-app-dep-map} in the side navigation menu.
+
You should see your host as a processing unit, with a dashed green line to a `Somewhere` external network.
Your host is in discovery mode.

. Return to your terminal on the target host.

. Clear `TOKEN`.
+
[,console]
----
 export TOKEN=""
----

. Refer to xref:../../secure/hosts.adoc[Securing host communications] to learn how to allow the desired traffic and disable discovery mode.

[#_enforcer-configuration-options]
=== Enforcer configuration options

The enforcer exposes the following configuration options at startup.
To modify the configuration of a running enforcer, you must restart it.
To modify the enforcer's tags, using the `--tag` flag, you have to also delete the enforcer object from the Microsegmentation Console.

You can modify the default configuration by passing one or more of the enforcer flags below as the value of `--raw-flags`.
Example: `apoctl enforcer install linux --raw-flags "--log-level=debug --log-format=human --log-to-console=true"`

|===
|enforcer flag |enforcerd.conf option |Description

| `--activate-control-plane-pus`
|
| Pass this flag if you wish to recognize the Microsegmentation Console as a processing unit, allowing its communications to be monitored and controlled. By default, the enforcer ignores them.

| `--api`
| `ENFORCERD_API`
| The URL of the Microsegmentation Console API.

| `--api-cacert`
|
| Path to CA certificate.

| `--api-skip-verify`
|
| Disables check on certificate signature as trusted.

| `--appcreds`
| `ENFORCERD_APPCREDS`
| Path to application credentials.

| `--application-proxy-port`
|
| Start of the port range for ports used by the enforcer application proxy. Defaults to 20992. You may adjust this if you experience conflicts.

| `--cloud-probe-timeout`
|
| The enforcer can determine if it is running in a cloud environment, such as AWS, GCP, or Azure. This is the maximum amount of time to wait for these internal probes to complete. Defaults to two seconds: `2s`

| `--disable-dns-proxy`
|
| Pass this flag to disable the enforcer DNS proxy, which allows policies to be written based on FQDN, in cases where an exact IP address may be unpredictable.

| `--dns-server-address`
|
| DNS server address or CIDR that is observed by the enforcer DNS proxy. Defaults to `0.0.0.0/0`.

| `--enable-ebpf`
|
| (*Beta*) Pass this flag to gain performance improvements by using extended Berkeley Packet Filter (eBPF) on systems that support it.

| `--enable-ipv6`
| `ENFORCERD_ENABLE_IPV6=1`
| The enforcer ignores IPv6 communications by default. If you have IPv6 enabled and wish to monitor and control these connections, pass this flag.

| `--log-level`
| `ENFORCERD_LOG_LEVEL=<value>`
| Quantity of logs that the enforcer should generate. Defaults to `info`. Alternatively, you can set it to `debug`, `trace`, or `warn`.

| `--log-to-console`
|
| Controls whether the enforcer's logs are written to stdout. Boolean that defaults to `false`.

| `--namespace`
| `ENFORCERD_NAMESPACE`
| The Microsegmentation namespace the enforcer should register in.

| `--tag`
|
| Microsegmentation tag for this enforcer

| `--token`
| `ENFORCERD_TOKEN`
| Microsegmentation token for the enforcer to use to register to the Microsegmentation Console.

| `--working-dir`
|
| A persistent working directory with write, read, and execute permissions. Files such as logs are stored here. Defaults to `/var/lib/enforcerd`
|===
