[#id9f10d8f9-7bdf-4ce7-a97d-6dfa71d27856]
== Config Query
Use Config Query to dig in to the configuration of the resources deployed in public cloud environments.

Prisma Cloud ingests various services and associated configuration data from the supported public cloud environments, such as AWS, Azure, GCP, and OCI. Use Config Query to retrieve resource information and identify misconfigurations, compliance violations, and password management policies, and for visibility into cloud identity and IAM permissions so that you can monitor risky and unused privileges in your cloud environments. To investigate configuration issues, use the `config from cloud.resource where` query, or to detect IAM security issues use `config from iam where` query in the search box on the *Investigate* tab of the Prisma Cloud administrator console. The `config from iam where` query is available only if you have subscribed to the IAM Security module on Prisma Cloud.

* xref:config-query-attributes.adoc#id192IG0J098M[Config Query Attributes] 

* xref:config-query-examples.adoc#id192IG0L0KSS[Config Query Examples] 




