== Intelligence Stream—Breaking Changes or Changes with Significant Impact

The Prisma Cloud https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/vulnerability_management/prisma_cloud_vulnerability_feed[Intelligence Stream(IS)] feed provides information on threat intelligence and vulnerability data, and this is available to all Prisma Cloud Compute Edition and Prisma Cloud Enterprise Edition customers who use the Cloud Workload Protection capabilities. This document captures the fairly rare breaking changes or significant changes to the Intelligence Stream (IS) that impact your deployments and scan results.

The IS is constantly updated and improved to include the latest changes in security vulnerabilities, and new vulnerabilities are frequently added when detected by the Palo Alto Networks threat research teams and official data from third-party feeds such as NVD. All such updates are not captured in this document.

The items in this list are intended to keep you informed of only the last 7 breaking changes or changes with significant impact, and the items will be rolled out after they have gone into effect.

[width="90%",cols="1,1,2",options="header"]
|=========================================================
|Date Announced |Date Taking Effect |Description of Change


| 31 October, 2022 | Lagrange, early December 2022 | The Intelligence stream is being updated to include additional and enhanced risk factor data. with the Kepler Update 3 release slated for Nov 6, 2022.

With this update, if you are on v22.06, you must upgrade to Kepler Update 3 (22.06.xxx) before November 20, 2022. 
If you do not upgrade, the IS will no longer be able to get the latest vulnerability information from the Palo Alto Networks CDN with the release of the upcoming feature release (code named Lagrange) .

|25 July, 2022 |31 July, 2022  | As part of the 22.06 update 1 release, the Intelligence Stream will not include CVE information for Debian 9 (Stretch). This is because Stretch has reached End of Life (EOL), and all CVE security vulnerabilities associated with this version are being removed from IS.

|29 June, 2022 |26 June, 2022  | As part of the 22.06 release, the Intelligence Stream now supports vulnerabilities from GitHub Security Advisories including Go, Java, and Python. 

|=========================================================
