== GitHub Actions artifact build do not have cosign - sign execution in pipeline
// GitHub Actions artifact build does not use 'cosign' to sign pipeline artifacts

Cosign can be used to sign pipeline artifacts, such as container images, to ensure their integrity and prevent tampering prior to and after deployment.
Violating this policy means a signable artifact was discovered but there is no evidence of signing that artifact in your pipeline.

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 3281171a-ff12-4591-a28d-51d888aa58c7

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/github_actions/checks/job/CosignArtifacts.py[CKV_GHA_5]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|GithubAction

|=== 

=== Description 
Cosign can be used to sign pipeline artifacts, such as container images, to ensure their integrity and prevent tampering prior to and after deployment.
Violating this policy means a signable artifact was discovered but there is no evidence of signing that artifact in your pipeline.

=== Fix - Buildtime
*Example Fix Add `cosign sign` to sign artifacts.* 


There are many ways to do this as a job or step in a GitHub Actions pipeline.
Below is one example for signing a container image.
[source,yaml]
----
----
----
----
