:toc: macro
== 30.01 Update 1 (Build 30.01.153)

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|30.01.153

|Code name
|Maxwell, 30.01

|Release date
|May 30, 2023

|Type
|Maintenance Release

|SHA-256
|921301ed6b871608b70f0b91ff08f4d7a14d52e3ae71675a62b948677ed4dcf4
|===

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN: 
//
// LINK

toc::[]

[#addressed-issues]
=== Addressed Issues

* Addressed an issue that failed to create, update, and delete cloud accounts with names starting with non-standard alphanumeric characters such as `(*, (/)$)`. You can now create cloud accounts with any name, including names that start with a special character.

//[#change-in-behavior]
//=== Change in Behavior

//==== Breaking fixes compare with SaaS RN
