== Set Up Administrator Access for Code Security

You need to enable administrative access for all the DevSecOps and Security teams who need to add code repositories or pipelines, create policies and review scan results on Prisma Cloud.
To know more see https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-administrators/prisma-cloud-administrator-roles.html[add Prisma Cloud Administrators] and https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-administrators/prisma-cloud-admin-permissions.html[role permissions]. You can also see https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-administrators/add-prisma-cloud-users.html[add administrative users].

=== Add a Custom Permission Group

Administrators can create a custom permission group for Code Security on the Prisma Cloud console. Using the parameters for permissions, you can limit or enhance the responsibilities of the users.

* *Suppression Management*: You can enable user permissions to view, create, update and delete resources on *Repositories* (Settings > Repositories). These parameters enable suppression management for vulnerabilities found in resources. In addition, configuring view permission for all Code Security functions allows you to see the resource vulnerabilities to make informed decisions.

* *Code Security Configuration*: Enabling permissions for Code Security Configuration helps you manage Code Security licenses, Enforcement thresholds, notifications, developer suppressions and creating rules to exclude paths for scans.

For further details see, https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-administrators/create-custom-prisma-cloud-roles[Create Custom Prisma Cloud Roles].


=== View Audit Logs

Audit Logs record administrator activities on the console to help you proactively track configuration actions that impact security outcomes such as modifying Enforcement parameters and adding suppression rules which impact the scan results, or actions on *Repositories* (Settings > Repositories), like adding, deleting or updating the repository selection, which what is being scanned and monitored using Primsa Cloud.

For further details on managing audit logs, see https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-administrators/view-audit-logs[View Audit Logs].
