== ELBs allow insecure SSL protocols or ciphers

*Policy Details* 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
|

|Checkov Check ID 
|

|Severity
|MEDIUM

|Subtype
|

|Frameworks
|

|=== 

*Description*


Using older SSL protocols or ciphers that are no longer considered secure could result in the connection between load balancer and server being exploited.
Elastic Load Balancers (ELB).

The following predefined security policies are acceptable for classic load balancers:

* ELBSecurityPolicy-2016-08
* ELBSecurityPolicy-TLS-1-2-2017-01
* ELBSecurityPolicy-TLS-1-1-2017-01

Application load balancers can use the above policies, but have other acceptable policies as follows:

* ELBSecurityPolicy-TLS-1-2-Ext-2018-06
* ELBSecurityPolicy-FS-2018-06
* ELBSecurityPolicy-FS-1-1-2019-08
* ELBSecurityPolicy-FS-1-2-2019-08
* ELBSecurityPolicy-FS-1-2-Res-2019-08
* ELBSecurityPolicy-2015-05

For classic ELBs you can review the AWS documentation which highlights the recommended SSL ciphers https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-ssl-security-policy.html[here].

////
=== Fix - Runtime


*AWS Console* 



[NOTE]
====
Ensure you are in the correct region.
====
*Classic Load Balancer Procedure*

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the http://console.aws.amazon.com/ec2/home[Amazon EC2 console].

. On the left menu, click** Load Balancers**.

. Select the _load balancer_ for review.

. Select the *Listeners* tab.

. On the *HTTPS listener*, select the **Cipher **column.

. Select *Change*.

. Navigate to the *Select a Cipher* panel and select one of the acceptable predefined security policies (listed above).
+
Alternatively, create a custom security policy based on the recommended ciphers listed in https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-ssl-security-policy.html#ssl-ciphers[AWS documentation].

. Scroll down and click *Save*.
+
*Application Load Balancer Procedure*

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the http://console.aws.amazon.com/ec2/home[Amazon EC2 console].

. On the left menu, click** Load Balancers**.

. Select the _load balancer_ for review.

. Select the *Listeners* tab.

. Select the *HTTPS listener*, click *Edit*.

. Navigate to *Security Policy* and select one of the acceptable predefined security policies (listed above).

. Click *Update*.
////