== AWS S3 bucket RestrictPublicBucket is not set to True


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ed4af42c-c3fc-4857-aca8-3b254a141465

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/S3RestrictPublicBuckets.py[CKV_AWS_56]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


The S3 Block Public Access configuration enables specifying whether S3 should restrict public bucket policies for buckets in this account.
Setting  RestrictPublicBucket to TRUE restricts access to buckets with public policies to only AWS services and authorized users within this account.
Enabling this setting does not affect previously stored bucket policies.
Public and cross-account access within any public bucket policy, including non-public delegation to specific accounts, is blocked.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_s3_bucket_public_access_block
* *Arguments:* restrict_public_buckets


[source,go]
----
resource "aws_s3_bucket_public_access_block" "artifacts" {
  ...
+ restrict_public_buckets = true
}
----


*CloudFormation* 


* *Resource:* AWS::S3::Bucket
* *Arguments:* Properties.PublicAccessBlockConfiguration.RestrictPublicBuckets


[source,yaml]
----
Type: 'AWS::S3::Bucket'
    Properties:
      ...
      PublicAccessBlockConfiguration:
        ...
+       RestrictPublicBuckets: true
----
