== AWS S3 bucket ACL grants READ permission to everyone


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4a060a93-6f25-418d-9f08-472f62d5ba3c

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/S3PublicACLRead.py[CKV_AWS_20]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 

////
Bridgecrew
Prisma Cloud
* AWS S3 bucket ACL grants READ permission to everyone* 



=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4a060a93-6f25-418d-9f08-472f62d5ba3c

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/S3PublicACLRead.py [CKV_AWS_20]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 
////


=== Description 


Unprotected S3 buckets are one of the major causes of data theft and intrusions.
An S3 bucket that allows *READ* access to everyone can provide attackers the ability to read object data within the bucket, which can lead to the exposure of sensitive data.
The only S3 buckets that should be globally accessible for unauthenticated users or for *Any AWS Authenticate Users* are those used for hosting static websites.A bucket ACL helps manage access to S3 bucket data. We recommend ensuring AWS S3 buckets are not publicly accessible for *READ* actions to protect S3 data from unauthorized users and exposing sensitive data to public access.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_s3_bucket, aws_s3_bucket_acl
* *Arguments:* acl


[source,terraform]
----
resource "aws_s3_bucket_acl" "data" {
  bucket = aws_s3_bucket.private_acl_v4.id
-  acl    = "public-read"
+  acl    = "private"
}
----



*CloudFormation* 


* *Resource:* AWS::S3::Bucket.data
* *Arguments:* Properties.AccessControl


[source,yaml]
----
Type: AWS::S3::Bucket
    Properties:
        ...
-     AccessControl: PublicReadWrite / PublicRead
----
