== Related Documentation

Refer to the following documentation on the https://docs.paloaltonetworks.com.html[Technical Documentation portal] or https://docs.paloaltonetworks.com/search.html[search] the documentation for more information on our products:

* *Prisma Cloud Administrator's Guide (Compute)* --
Provides the concepts and workflows to get the most out of the Compute service in Prisma Cloud Enterprise Edition.
The http://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-guide-compute/[Prisma Cloud Administrator’s Guide (Compute)] also takes you through the initial onboarding and basic set up for securing your hosts, containers, and serverless functions.

* *Prisma Cloud Compute Edition Administrator's Guide* --
Provides the concepts and workflows to get the most out of the Prisma Cloud Compute Edition, the self-hosted version of Prisma Cloud's workload protection solution.
The http://docs.paloaltonetworks.com/prisma/prisma-cloud/19-11/prisma-cloud-compute-edition-admin/[Prisma Cloud Administrator’s Guide (Compute)] also takes you through the initial onboarding and basic set up for securing your hosts, containers, and serverless functions.*

* *Prisma Cloud Administrator's Guide* --
Provides the concepts and workflows to get the most out of the Prisma Cloud service.
The https://docs.paloaltonetworks.com/redlock/redlock-admin.html[Prisma Cloud Administrator’s Guide] also takes you through the initial onboarding and basic set up for securing your public cloud deployments.

* *Prisma Cloud RQL Reference* -- 
Describes how to use the https://docs.paloaltonetworks.com/redlock/redlock-rql-reference.html[Resource Query Language (RQL)] investigate incidents and then create policies based on the findings.

* *VM-Series Deployment Guide* --
Use the https://docs.paloaltonetworks.com/vm-series.html[VM-Series Deployment Guide] to set up your VM-Series firewall for inline security policy enforcement of east-west and north-south traffic to your workloads in a virtualized or cloud environment.

* *Prisma Access Getting Started Guide* --
Use the https://docs.paloaltonetworks.com/prisma/prisma-access/prisma-access-cloud-managed-admin/get-started-with-prisma-access/prisma-access[Prisma Access from the Panorama Plugin Getting Started Guide] to set up Prisma Access and realize the flexibility, convenience, and rapid time to value in securing your branch offices and mobile users.
This guide includes information on how to use the Cortex Data Lake with Prisma Access.
