== Public and private repositories connected to shared CI system

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|52d503c5-4449-4d3d-abd5-1459ee568e8b 

|Severity
|Info 
// add severity level

|Category
|System Configuration 
// add category+link

|Subtype
|Build 
// add subtype-build/runtime

|Frameworks
|Cross Systems

|=== 


=== Description 

A CI system is connected with both private and public repositories. Any CI system that runs code from public repositories is potentially vulnerable to a variety of attacks, from execution of malicious code in a build, to credential theft, through abuse of webhooks. Private repositories and their pipelines tend to be more sensitive, and attackers that gain any type of control on the shared CI system might be able to access restricted resources, view application code, or exfiltrate stored credentials.

=== Recommended Solution - Buildtime

Consider splitting builds to separate CI instances, by the level of their exposure and sensitivity. For example, one instance to handle public repositories, and another one for private repositories.

If both public and private repositories should be built on the same CI instance, follow these general recommended guidelines:

* Validate that only reviewed code can be run in a build.

* Create segregation for secrets, so each pipeline can only access the credentials it needs.

* Harden the build environment to run with a low-privileged user.

* Harden the build environment so each build cannot access other build environments.

* Keep the CI software and any plugin in use updated and patched.


