== Windows hosts

//'''
//
//title: Windows hosts
//type: single
//url: "/3.14/start/enforcer/windows/"
//weight: 40
//menu:
//  3.14:
//    parent: "enforcer"
//    identifier: "windows"
//canonical: https://docs.aporeto.com/saas/start/enforcer/windows/
//
//'''

=== About Windows host installs

To deploy Aporeto to a Windows host not orchestrated by Kubernetes or OpenShift, use one of the following procedures.

* <<_quick-install,Quick install>>: the fastest way to install an enforcer on any Windows host.
Appropriate for those just getting started with Aporeto.
You can also use it for on-premise hosts in production.
* <<_production-cloud-install,Production cloud install>>: recommended for production instances hosted on AWS, GCP, or Azure.
The enforcer uses short-lived tokens from the cloud provider to authenticate to the Aporeto control plane.
* <<_advanced-on-premise-install,Advanced on-premise install>>: more secure than the quick install.
The enforcer exchanges a restricted token for an app credential.
It uses least privilege credentials to access the control plane, which won't allow it to re-register itself if it goes down for more than twenty-four hours.

[TIP]
====
Our Windows commands work in PowerShell.
====

[#_quick-install]
=== Quick install

==== Prerequisites

[cols="1,3a"]
|===
|Entity |Requirement

|Target host 
|
* xref:reqs.adoc[Meets the system requirements]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[Set up to synchronize time with authoritative sources]

|Local host
|xref:../apoctl/apoctl.adoc[`apoctl` installed]

|Privileges
|
* `namespace.editor` privileges in Aporeto
* Root access to the target instance
|===

WARNING: For security reasons, we do not recommend installing `apoctl` on the enforcer host.

==== 1. Create an app credential

From the `apoctl` host, create an app credential with the `enforcer` role.

[,console]
----
apoctl appcred create enforcerd --role @auth:role=enforcer > enforcerd.creds
----

==== 2. Copy the app credential to the target host

You can accomplish this in several ways.
In the following example, we use `scp`.

[,console]
----
scp -i <private-key.pem> enforcerd.creds <linux-user-name>@<target-host>:~
----

==== 3. Access the target host

Access the host, such as via SSH, and confirm that the app credential file was copied.
An example follows.

[,console]
----
ssh -i <private-key.pem> ec2-user@ec2-52-17-109-41.us-west-2.compute.amazonaws.com
ls
----

==== 4. Download the enforcer installer

Use curl to download the enforcer installer package.

[,powershell,subs="+attributes"]
----
curl {download-url}{version}/enforcerd/windows/enforcer.msi -o enforcer.msi
----

==== 5. Install and start the enforcer

Use the following command to install and start the enforcer.

[,powershell,subs="+attributes"]
----
msiexec /i enforcer.msi ENFORCERD_API=https://{ctrl-plane-api-url} `
ENFORCERD_APPCREDS=C:\Users\$($env:USERNAME)\enforcerd.creds ATTESTMETHOD=1 /qn ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{$values = Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment"
$values += "ENFORCERD_COMPRESSED_TAGS=1"
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment" -Type "MultiString" -Value $values} ; if ($?)
{& sc.exe qc "Aporeto Enforcer"} ; if ($?)
{& sc.exe start "Aporeto Enforcer"} ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{& sc.exe query "Aporeto Enforcer"}
----

[TIP]
====
You can use Windows Event Viewer to see certain status messages. To see more logs, you can set `ENFORCERD_DISABLE_LOG_WRITE=false` in our service's environment to log to disk.
====

Open the Aporeto web interface at {ctrl-plane-api-url}/app, switch to the mapped namespace, and select **Enforcers**.
You should find your enforcer listed with a status of **connected**.
Click the enforcer and review its metadata.

Congratulations!
Aporeto now recognizes the containers on the host as processing units, allowing you to control and monitor their traffic.
If you have containers running on the host, select **Platform** in the Aporeto web interface.
The containers and their traffic should appear.

**Next steps**

* xref:../../setup/idp/idp.adoc[Configure an identity provider]: if you haven't already, you should configure an identity provider to allow other users in your organization to access the Aporeto control plane.
* xref:../../setup/namespaces.adoc[Design your namespace scheme]: create namespaces to help you establish security zones and multi-tenancy.
* xref:../../secure/secure-hosts/secure-hosts.adoc[Enable host protection]: to control and monitor communications to and from any process on the host, not just containers, enable host protection.
* xref:../../secure/ssh/ssh.adoc[Control SSH sessions] consider using Aporeto to manage, control, and monitor SSH sessions on your hosts.
* xref:../../secure/netpol/netpol.adoc[Define network policies]: Aporeto currently denies all traffic to and from the containers on the host.
You must create network policies to allow the desired traffic.

[#_production-cloud-install]
=== Production cloud install

==== Prerequisites

[cols="1,3a"]
|===
|Entity |Requirement

|Target host
|
* xref:reqs.adoc[Meets the system requirements]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[Set up to synchronize time with authoritative sources]

|Local host
|xref:../apoctl/apoctl.adoc[`apoctl` installed]

|Privileges
|
* `namespace.editor` privileges in Aporeto
* Root access to the target instance

|Cloud credentials
|
* _AWS_: https://aws.amazon.com/blogs/security/easily-replace-or-attach-an-iam-role-to-an-existing-ec2-instance-by-using-the-ec2-console/[an IAM role attached to the target host] with read-only access to tags (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policy-structure.html[`ec2:DescribeTags`])
* _GCP_: https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[GCP service account attached to the target host]
* _Azure_: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vmss[target host assigned a managed identity]
|===

==== 1. Set environment variables on your local host

Construct an xref:../../concepts/key-concepts.adoc#_tags-and-identity[Aporeto tag] that includes metadata from the cloud instance to identify enforcers authorized to register with Aporeto.
The tag must begin with `@auth:` followed by a key-value pair.
Refer to the table below for some common examples.

|===
|Cloud provider | Value                              | Aporeto tag syntax                  |  Aporeto tag example

|AWS            | AWS account ID^1^                    | `@auth:account=<AWS_ACCOUNT_ID>`    | `@auth:account=942613894219`
|GCP            | GCP project ID                     | `@auth:projectid=<GCP_PROJECT_ID>`  | `@auth:projectid=acme-dev`
|Azure          | Microsoft tenant ID^2^ | `@auth:tenantid=<TENANT_ID>`        | `@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7`
|GCP and Azure  | Name of organization               | `@auth:organization=<ORGANIZATION>` | `@auth:organization=acme`
|===

* ^1^You can find your AWS account ID under *My security credentials* in the AWS Management Console.
* ^2^To learn how to find your tenant ID, refer to the https://techcommunity.microsoft.com/t5/Office-365/How-do-you-find-the-tenant-ID/td-p/89018[Microsoft documentation].

On your `apoctl` host, set two environment variables.

* `CLOUD_ID_TAG` containing the Aporeto tag you've constructed to identify authorized enforcers.
* `AWS_IAM_ROLE` (AWS only) containing the name of the IAM role attached to the instance prepended with `@auth:rolename=`.

For example commands, select the tab that corresponds to the cloud provider of the target host.

AWS

[,powershell]
----
$env:CLOUD_ID_TAG="@auth:account=942613894219"
$env:AWS_IAM_ROLE="@auth:rolename=aporeto"
----

GCP

[,powershell]
----
$env:CLOUD_ID_TAG="@auth:projectid=acme-dev"
----

Azure

[,powershell]
----
$env:CLOUD_ID_TAG="@auth:tenantid=cd629cb5-2826-4126-82fd-3f2df5f5bc7"
----

==== 2. Create an API authorization

Create an API authorization that allows the Aporeto enforcer to access the Aporeto control plane.
For the command, select the tab that corresponds to the cloud provider of the target host.

AWS

[,powershell]
----
Set-Content -Path enf-api-auth.yml -Value @"
APIVersion: 0
label: ec2-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $($env:APOCTL_NAMESPACE)
     authorizedSubnets: []
     name: Authorize EC2 enforcer to access Aporeto control plane
     propagate: true
     subject:
       - - "@auth:realm=awssecuritytoken"
         - "$($env:AWS_IAM_ROLE)"
         - "$($env:CLOUD_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f enf-api-auth.yml }
----

GCP

[,powershell]
----
Set-Content -Path enf-api-auth.yml -Value @"
APIVersion: 0
label: gcp-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $($env:APOCTL_NAMESPACE)
     authorizedSubnets: []
     name: Authorize GCP enforcer to access Aporeto control plane
     propagate: true
     subject:
       - - "@auth:realm=gcpidentitytoken"
         - "$($env:CLOUD_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f enf-api-auth.yml }
----

Azure

[,powershell]
----
Set-Content -Path enf-api-auth.yml -Value @"
APIVersion: 0
label: azure-enforcerd-auth
data:
 apiauthorizationpolicies:
   - authorizedIdentities:
       - '@auth:role=enforcer'
     authorizedNamespace: $($env:APOCTL_NAMESPACE)
     authorizedSubnets: []
     name: Authorize Azure enforcer to access Aporeto control plane
     propagate: true
     subject:
       - - "@auth:realm=azureidentitytoken"
         - "$($env:CLOUD_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f enf-api-auth.yml }
----

==== 3. Create a namespace mapping (optional)

Once an enforcer registers, you cannot change its namespace.
If you don't want the enforcers to register in your current namespace, complete this step to map them into a child instead.
Set the following environment variables.

* `CHILD_NAMESPACE`: the name of the target child namespace.
It may or may not exist.
* `ENFORCER_ID_TAG`: an Aporeto tag that uniquely identifies the enforcer(s) to be mapped.
Note that all enforcers with the designated tag will be mapped.

For example commands, select the tab that corresponds to the cloud provider of the target host.

AWS

[,powershell]
----
$env:CHILD_NAMESPACE="ec2"
$env:ENFORCER_ID_TAG="@cloud:aws:type=ec2"
----

GCP

[,powershell]
----
$env:CHILD_NAMESPACE="central-usa"
$env:ENFORCER_ID_TAG="@cloud:gcp:zone=us-central1-a"
----

Azure

[,powershell]
----
$env:CHILD_NAMESPACE="central-usa"
$env:ENFORCER_ID_TAG="@cloud:azure:location=centralus"
----

If it does not already exist, create the child namespace.

[,powershell]
----
apoctl api create ns -k name $($env:CHILD_NAMESPACE)
----

Create the namespace mapping.
For the command, select the tab that corresponds to the cloud provider of the target host.

AWS

[,powershell]
----
Set-Content -Path ns-map.yml -Value @"
APIVersion: 0
label: ec2-namespace-map
data:
 namespacemappingpolicies:
   - mappedNamespace: $($env:APOCTL_NAMESPACE)/$($env:CHILD_NAMESPACE)
     metadata: []
     name: Map $($env:ENFORCER_ID_TAG) instance to $($env:APOCTL_NAMESPACE)/$($env:CHILD_NAMESPACE) namespace
     subject:
       - - "`$identity=enforcer"
         - "$($env:ENFORCER_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f ns-map.yml }
----

GCP

[,powershell]
----
Set-Content -Path ns-map.yml -Value @"
APIVersion: 0
label: gcp-namespace-map
data:
 namespacemappingpolicies:
   - mappedNamespace: $($env:APOCTL_NAMESPACE)/$($env:CHILD_NAMESPACE)
     metadata: []
     name: Map $($env:ENFORCER_ID_TAG) instance to $($env:APOCTL_NAMESPACE)/$($env:CHILD_NAMESPACE) namespace
     subject:
       - - "`$identity=enforcer"
         - "$($env:ENFORCER_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f ns-map.yml }
----

Azure

[,powershell]
----
Set-Content -Path ns-map.yml -Value @"
APIVersion: 0
label: azure-namespace-map
data:
 namespacemappingpolicies:
   - mappedNamespace: $($env:APOCTL_NAMESPACE)/$($env:CHILD_NAMESPACE)
     metadata: []
     name: Map $($env:ENFORCER_ID_TAG) instance to $($env:APOCTL_NAMESPACE)/$($env:CHILD_NAMESPACE) namespace
     subject:
       - - "`$identity=enforcer"
         - "$($env:ENFORCER_ID_TAG)"
"@ ; if ($?)
{ apoctl api import -f ns-map.yml }
----

==== 4. Copy the base namespace

Issue the following command to obtain your base namespace.

[,powershell]
----
echo $($env:APOCTL_NAMESPACE)
----

Copy the value returned.

==== 5. Set an environment variable on the target host

Access your target instance, such as via Microsoft Remote Desktop, and paste the value into an environment variable named `ENFORCERD_NAMESPACE`.
Replace `<paste-value>` in the command below with the value copied from your `apoctl` host in the previous step.

[,powershell]
----
$env:ENFORCERD_NAMESPACE="<paste-value>"
----

==== 6. Download the enforcer installer

Use curl to download the enforcer installer package.

[,powershell,subs="+attributes"]
----
curl {download-url}{version}/enforcerd/windows/enforcer.msi -o enforcer.msi
----

==== 7. Install and start the enforcer

Use the following command to install and start the enforcer.

[,powershell,subs="+attributes"]
----
msiexec /i enforcer.msi ENFORCERD_API=https://{ctrl-plane-api-url} `
ENFORCERD_NAMESPACE=$($env:ENFORCERD_NAMESPACE) ATTESTMETHOD=0 /qn ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{$values = Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment"
$values += "ENFORCERD_COMPRESSED_TAGS=1"
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment" -Type "MultiString" -Value $values} ; if ($?)
{& sc.exe qc "Aporeto Enforcer"} ; if ($?)
{& sc.exe start "Aporeto Enforcer"} ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{& sc.exe query "Aporeto Enforcer"}
----

[TIP]
====
You can use Windows Event Viewer to see certain status messages. To see more logs, you can set `ENFORCERD_DISABLE_LOG_WRITE=false` in our service's environment to log to disk.
====

Open the Aporeto web interface at {ctrl-plane-api-url}/app, switch to the mapped namespace, and select **Enforcers**.
You should find your enforcer listed with a status of **connected**.
Click the enforcer and review its metadata.

Congratulations!
Aporeto now recognizes the containers on the host as processing units, allowing you to control and monitor their traffic.
If you have containers running on the host, select **Platform** in the Aporeto web interface.
The containers and their traffic should appear.

**Next steps**

* xref:../../setup/idp/idp.adoc[Configure an identity provider]: if you haven't already, you should configure an identity provider to allow other users in your organization to access the Aporeto control plane.
* xref:../../setup/namespaces.adoc[Design your namespace scheme]: create namespaces to help you establish security zones and multi-tenancy.
* xref:../../secure/secure-hosts/secure-hosts.adoc[Enable host protection]: to control and monitor communications to and from any process on the host, not just containers, enable host protection.
* xref:../../secure/ssh/ssh.adoc[Control SSH sessions]: consider using Aporeto to manage, control, and monitor SSH sessions on your hosts.
* xref:../../secure/netpol/netpol.adoc[Define network policies]: Aporeto currently denies all traffic to and from the containers on the host.
You must create network policies to allow the desired traffic.

[#_advanced-on-premise-install]
=== Advanced on-premise install

==== Prerequisites

|===
|Entity |Requirement

|Target host 
|
* xref:reqs.adoc[Meets the system requirements]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html[Set up to synchronize time with authoritative sources]

|Local host  
|xref:../apoctl/apoctl.adoc[`apoctl` installed]

|Privileges
|
* `namespace.editor` privileges in Aporeto
* Root access to the target instance
|===

WARNING: For security reasons, we do not recommend installing `apoctl` on the enforcer host.

==== 1. Create an app credential

From the `apoctl` host, create an app credential with the `enforcer` role.

[,console]
----
apoctl appcred create enforcerd --role @auth:role=enforcer > enforcerd.creds
----

==== 2. Generate a token from the app credential

Use the app credential to generate an enforcer registration token with the desired restrictions.
At a minimum, we recommend restricting the length of its validity and role.
You can also require the enforcer to register in a specified namespace or make its request from a specific subnet.

Syntax

[,powershell]
----
apoctl auth appcred --path enforcerd.creds \
  --restrict-role @auth:role=enforcer \
  --validity <golang-duration> \
  [--restrict-namespace <namespace>] \
  [--restrict-network <cidr>]
----

Fully restricted example

[,powershell]
----
apoctl auth appcred --path enforcerd.creds \
  --restrict-namespace /acme/team-a/dev \
  --restrict-role @auth:role=enforcer \
  --restrict-network 10.0.0.0/8 \
  --validity 10m
----

Minimally restricted example

[,powershell]
----
apoctl auth appcred --path enforcerd.creds \
  --restrict-role @auth:role=enforcer --validity 10m
----

This should return a base64-encoded token.
Copy the value.

==== 3. Store the enforcer token on the target host

Access the target host, such as via a remote desktop client.
Set an environment variable called `TOKEN` containing the value copied in the previous step.

[,powershell]
----
$env:TOKEN="<paste-token-value>"
----

==== 4. Download the enforcer installer

Use curl to download the enforcer installer package.

[,powershell,subs="+attributes"]
----
curl {download-url}{version}/enforcerd/windows/enforcer.msi -o enforcer.msi
----

==== 5. Install and start the enforcer

You can configure the enforcer to store its app credential only in memory and not on disk. While more secure, this option requires someone to manually reprovision enforcer with a token following a reboot of the host. You can also configure the enforcer to store its app credential on disk, ensuring that it can reconnect to the Aporeto control plane after a reboot without manual intervention.

* Store app credential on disk
+
[,powershell,subs="+attributes"]
----
msiexec /i enforcer.msi ENFORCERD_API=https://{ctrl-plane-api-url} `
ENFORCERD_TOKEN=$($env:TOKEN) ATTESTMETHOD=2 /qn ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{$values = Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment"
$values += "ENFORCERD_COMPRESSED_TAGS=1"
$values += "ENFORCERD_PERSIST_CREDENTIALS=true"
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment" -Type "MultiString" -Value $values} ; if ($?)
{& sc.exe qc "Aporeto Enforcer"} ; if ($?)
{& sc.exe start "Aporeto Enforcer"} ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{& sc.exe query "Aporeto Enforcer"}
----

* Store app credential only in memory
+
[,powershell,subs="+attributes"]
----
msiexec /i enforcer.msi ENFORCERD_API=https://{ctrl-plane-api-url} `
ENFORCERD_TOKEN=$($env:TOKEN) ATTESTMETHOD=2 /qn ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{$values = Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment"
$values += "ENFORCERD_COMPRESSED_TAGS=1"
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Aporeto Enforcer\" -Name "Environment" -Type "MultiString" -Value $values} ; if ($?)
{& sc.exe qc "Aporeto Enforcer"} ; if ($?)
{& sc.exe start "Aporeto Enforcer"} ; if ($?)
{Start-Sleep -s 10} ; if ($?)
{& sc.exe query "Aporeto Enforcer"}
----

[TIP]
====
You can use Windows Event Viewer to see certain status messages. To see more logs, you can set `ENFORCERD_DISABLE_LOG_WRITE=false` in our service's environment to log to disk.
====

Open the Aporeto web interface at {ctrl-plane-api-url}/app, switch to the mapped namespace, and select **Enforcers**.
You should find your enforcer listed with a status of **connected**.
Click the enforcer and review its metadata.

Congratulations!
Aporeto now recognizes the containers on the host as processing units, allowing you to control and monitor their traffic.
If you have containers running on the host, select **Platform** in the Aporeto web interface.
The containers and their traffic should appear.

**Next steps**

* xref:../../setup/idp/idp.adoc[Configure an identity provider]: if you haven't already, you should configure an identity provider to allow other users in your organization to access the Aporeto control plane.
* xref:../../setup/namespaces.adoc[Design your namespace scheme]: create namespaces to help you establish security zones and multi-tenancy.
* xref:../../secure/secure-hosts/secure-hosts.adoc[Enable host protection]: to control and monitor communications to and from any process on the host, not just containers, enable host protection.
* xref:../../secure/ssh/ssh.adoc[Control SSH sessions]: consider using Aporeto to manage, control, and monitor SSH sessions on your hosts.
* xref:../../secure/netpol/netpol.adoc[Define network policies]: Aporeto currently denies all traffic to and from the containers on the host.
You must create network policies to allow the desired traffic.
