== Alibaba Cloud RAM password policy does not expire in 90 days


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 00a4e900-ca63-470f-9607-b7ad5cdd3ab3

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/RAMPasswordPolicyExpiration.py[CKV_ALI_16]

|Severity
|LOW

|Subtype
|Build
//, Run

|Frameworks
|Terraform

|=== 



=== Description 


As a best practice, it is important to change passwords after 90 days as a security measure to reduce the risk of unauthorized access to an account, as it reduces the window of opportunity for attackers to use stolen or compromised passwords. This policy identifies Alibaba Cloud RAM accounts (account)that do not have password expiration set to 90 days or more.


////
=== Fix - Runtime
Alibaba Cloud Portal
. Log in to Alibaba Cloud Portal
. Go to Resource Access Management (RAM) service
. In the left-side navigation pane, click on 'Settings'
. In the 'Security Settings' tab, In the 'Password Strength Settings' Section, Click on 'Edit Password Rule'
. In the 'Password Validity Period' field, enter 90 or less based on your requirement.
. Click on 'OK'
. Click on 'Close'
////
 



=== Fix - Buildtime


*Terraform* 

To identify accounts which have passwords that do not expire within 90 days, add the following code to your Terraform file during buildtime.


[source,go]
----
{
 "TBD"
}
----
