== Secrets found in console output of a CircleCI pipeline

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|5d0b721f-1428-4eda-a8f2-4e8d71eaed1a 

|Severity
|Medium
// add severity level

|Category
|Credential Hygiene
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|CircleCI

|=== 

=== Description 

Secrets exposed in build log files can be used by an attacker that has taken over an account with access to the system in order to move laterally in the organization. 

Exposed secrets can be caused by not using the relevant feature to protect credentials or by printing credentials in a way that bypasses the feature’s ability to detect credentials.


=== Recommended Solution - Buildtime

When exposed credentials are found, it is recommended to: 

* Rotate all exposed credentials
* If the environment variables masking feature was disabled in the past with the help of CircleCI support, make sure to contact support to enable it
* The secret masking feature* has limitations, hence some exposed credentials should be resolved by modifying the pipeline manifest to prevent exposure

^*^Secret masking is not available on self-hosted CircleCI server. To prevent exposure of secrets make sure to modify the pipeline manifest.







