== 31.00 Known Issues

Review the list of known issues on the 31.00 release.

=== Fixed Issues

* Fixed an issue limiting the support of Prisma Cloud Compute as a pluggable scanner in Harbor.
The support is now extended to instances where the Defenders operate in a CRI environment.

* Fixed an issue that caused missing version detection for jar packages when the version name included a date, for example, 20171018.

* Fixed an issue preventing agentless scanning of onboarded Azure government accounts

* Fixed an issue caused when listing container details of containers on hosts using Docker as the CRI. 
+
With this fix agentless scanning successfully  discovers containers on the specified host. It also the scan process tolerance to errors during the retrieval of container metadata.

* Fixed missing OS labels of hosts scanned using agentless scanning. 
+
With this fix missing OS labels, both `osDistro` and `osVersion`, are added to hosts scanned by agentless scanning.

* Fixed an issue where AKS cluster names were not properly processed and the cluster was incorrectly classified as a generic Kubernetes cluster instead of an AKS cluster.
Now, the cluster names and their type are  properly parsed as AKS clusters.
