== 22.12 Known Issues

Review the list of known issues on the 22.12 release.

//PCSUP-12197/CWP-41449
* For an application that originates from an OS package, the vulnerability data for CVEs is sourced from the relevant feed for the OS package. In some cases, like with Amazon Linux and Photon OS, this CVE information is provided in security advisories such as Amazon Linux Security Advisories (ALAS) for Amazon, and PHSA for Photon. In such cases, the correlation for the relevant vulnerabilities is limited.
As an example, when the application “python” is sourced from an Amazon Python package, CVEs found for the python application (as a binary) will not be correlated with the relevant Amazon CVEs from the ALAS.

//GH#39394 PCSUP-9241
* tt:[22.12.415 or later] Prisma Cloud integration with AWS Security Hub fails on US Gov regions.

//GH#42826
* tt:[22.12.415 or later] A `404 Not Found error` is displayed when performing a sandbox image analysis using older version of twistcli, such as v22.06, with the 22.12 console. 

//CWP-39278
* Compliance check 6361 fails for hosts running RedHat Enterprise Linux (RHEL) 9.
The check to ensure the `iptables` package is installed fails because `iptables` was deprecated in RHEL 9 and replaced with the `nftables` package.
