== 22.12 Known Issues

Review the list of known issues on the 22.12 release.

//PCSUP-12197/CWP-41449
* For an application that originates from an OS package, the vulnerability data for CVEs is sourced from the relevant feed for the OS package. In some cases, like with Amazon Linux and Photon OS, this CVE information is provided in security advisories such as Amazon Linux Security Advisories (ALAS) for Amazon, and PHSA for Photon. In such cases, the correlation for the relevant vulnerabilities is limited.
As an example, when the application “python” is sourced from an Amazon Python package, CVEs found for the python application (as a binary) will not be correlated with the relevant Amazon CVEs from the ALAS.

//CWP-43836 GH##41137
* The console displays an expired certificate warning for Defenders even if the certificate is not in use. This issue only occurs when you have certificates that are more than 3 years old.
+
Confirm that the Defenders are connected and ignore the UI notification banner.
+
*Workaround*: Delete the `*.pem.old` certficate to remove this UI notification banner.

//GH#39394 PCSUP-9241
* Prisma Cloud integration with AWS Security Hub fails on US Gov regions.

//GH#42826
* A `404 Not Found error` is displayed when performing a sandbox image analysis using older version of twistcli, such as v22.06, with the 22.12 console. 
