== 31.xx Known Issues

Review the list of known issues on the 31.xx release.

// Note that when we add a known issue, you have to then update this page to include the "Fixed in xx.xx.xxx" for the known issue when it is fixed subsequently. Fixed issues in a given release are documented in the 31.xx adoc file and indicated as fixed on this page (if it was identified as a known issue earlier).

//CWP-50923
* AKS clusters with an underscore "_" in the resource group name are detected as vanilla Kubernetes clusters instead of AKS clusters in the host scan results.

//CWP-51616
* tt:[Fixed in 31.02.xxx] The Prisma scanner may potentially fail to retrieve image details for Docker registries and may fail with 429 connection error when you try to scan more than one Docker registry at a time.
To avoid this error, set the `REGISTRY_SCANNERS` value to 1 in the `twistlock.cfg` config file.

//CWP-50733 //PCSUP-18095
* tt:[Fixed in 31.01.123] Fixed an error in deploying and upgrading the Host Defenders on Windows Server 2019 installed on AWS. 
