== 19.11 Update 1 Release Notes

This section provides a snapshot of the fixes in Prisma(TM) Cloud Compute Edition 19.11 Update 1 (19.11.506).

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|19.11.506

|Code name
|Dirac, 19.11 update 1

|Release date
|23 December 2019

|Type
|Maintenance release

|SHA-256 digest
|1617633fa36626a5e96f4cd9c215bc9e6b981950000e27edd909e57cdeecea90
|===


=== Improvements, fixes, and performance enhancements

// #17813
* Adds support for embedding Serverless Defender with a Lambda layer.
// #17564
* Adds full support for runtime defense on CoreOS, including block and prevent actions.
// #16303
* Adds coverage for VMware Photon OS vulnerabilities.
Photon is a host OS optimized for containers.
// #17743
* Improves registry scan performance for very large registries.
// #17722
* Fixes an issue with registry scanning when in the middle of an upgrade.
Defenders selected to scan registry images must have the same version as Console.
// #17653
* Fixes an issue with container images not being properly deleted from the host after being scanned.
// #16948
* Renames "RASP Defender" to "Container Defender - app embedded".
// #17924
* [Prisma Cloud Enterprise Edition] Fixes navigation links in the Console UI.
// #17800
* [Prisma Cloud Enterprise Edition] Fixes Console's contextual help system to properly link to individual articles on the doc site.
// #17836
* Fixes some false negatives for vulnerabilities in Java JARs.
// #17884
* Fixes security issues.


=== Upcoming breaking changes

In the next major release of Prisma Cloud Compute, we will deprecate the following endpoints.
These endpoints are used internally by the UI to get a list of table filters.
For sorting and filtering results, retrieve the full data set (e.g. /api/v1/containers), and use tools like jq and Python to filter and sort.

* _/api/v1/containers/filters_
* _/api/v1/hosts/filters_
* _/api/v1/scans/filters_
* _/api/v1/profiles/container/filters_
* _/api/v1/audits/mgmt/filters_
* _/api/v1/audits/incidents/filters_
* _/api/v1/audits/access/filters_
