:toc: macro
== 22.06 Update 3 Release Notes

The following table provides the release details:

[cols="1,4"]
|===
|Build
|22.06.224

|Codename
|Kepler, 22.06 Update 3
|Release date
|Nov 7, 2022

|Type
|Maintenance release

|SHA-256 digest
|f0451f05951ab28811f99ebc68adcdf58d17fd332f68290d03eab023d4510495
|===

//Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic download (e.g., curl, wget) of the release directly from our CDN:

// LINK

toc::[]

=== Addressed Issues

//GH#42308 PCSUP-11825
* Fixed an issue with incorrect health state for a Defender deployed on a container.

//GH#42233, GH#42161, and GH#42715
* Addressed the following issues:

** CVE-2020-7711 vulnerability detected in a vendor package - `goxmldsig.`
** CVE-2022-40674 vulnerability detected in a vendor package - `expat`
** CVE-2022-41716 vulnerability detected in Google Go Windows environment variable - `exec.cmd` syscall
** Go update to version 1.18.8. The version includes security fixes.

// GH#41077 PCSUP-11119
* Improved the reconnection time for multi-tenant deployments when some tenants are disconnected from the central Console.

// GH#40865	PCSUP-10977	
* Fixed a DNS resolution error when running a twistcli image scan with the `--tarball` option.

//GH#40694	PCSUP-10618	
//* Fixed an issue where errors were reported in scan results when the cloud service provider APIs are disabled.
//+
//Now when the APIs for the service are disabled on the CSP, cloud discovery or registry scanning do not display these as errors in scan results. 
//The messages are added to the console logs.
* Fixed an issue where errors were reported in Google cloud discovery scan when the scanned service APIs are disabled.
+
Now when such APIs are disabled on the Google cloud, cloud discovery do not display these as errors in the results. The messages are added to the console logs.

//GH#40533	PCSUP-10621	
* Fixed an issue with incorrect cluster information in image scan results on "Monitor > Vulnerabilities > Deployed".

//GH#38960		
* Fixed the rule scope selection for Out-of-Band WAAS rule.
+
When adding a new Out-of-Band WAAS rule, you were unable to choose a container name in the rule scope, or save an Out-of-Band WAAS rule with a scope that included a namespace selection, or did not include an image selection. These issues are now fixed.

=== Upcoming Breaking Changes

* *Alert Profile*—as announced in xref:release-notes-22-06-update2.adoc[Kepler Update 2].

