:toc: macro
== 22.12 Release Notes

The following table provides the release details:

[cols="1,4"]
|===
|Build
|22.12.692

|Codename
|Lagrange, 22.12 Update 3
|Release date
|Mar 12, 2023

|Type
|Maintenance release

|SHA-256 digest
|fa6974a4466915ac58165bdf2296434c31a5c65c0a04ee7d87ed7cae071ead71
|===
//Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic  download (e.g., curl, wget) of the release directly from our CDN:

// LINK

toc::[]

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-12/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn more details about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.


[#upgrade-path]
=== Upgrade Path to 22.12.692

If you are running a Prisma Cloud console version 22.06 or earlier, you must first upgrade the console to 22.12.585 and then to 22.12.692.

[#cve-coverage-update]
=== CVE Coverage Update

//CWP-46080

* Fixed https://nvd.nist.gov/vuln/detail/CVE-2023-25173[CVE-2023-25173] and https://nvd.nist.gov/vuln/detail/CVE-2023-25153[CVE-2023-25153] (Severity - Moderate): `containerd` vulnerability seen in <compute and/or defender>, <impacting this> are addressed by upgrading to `containerd` version v1.6.18 and v1.5.18.
* Fixed https://nvd.nist.gov/vuln/detail/CVE-2022-1996[CVE-2022-1996] (Severity - Critical) is included in the Intelligence Stream feed. The Go-Restful package is a transitive dependency that is pulled with http://k8s.io/client-go[k8s.io/client-go] and http://k8s.io/kube-openapi[k8s.io/kube-openapi] and is not being used directly in the Compute Defender and Console, thus it is suppressed.

[#enhancements]
=== Enhancements

//CWP-45310

* Defender Upgrade All Improvements- When you select to Upgrade all Defenders ("Manage > Defenders > Deployed Defenders"), you can only upgrade the Defenders that are eligible for upgrade and for which you have the permissions to upgrade, based on the collections that are assigned to your Prisma Cloud role. A confirmation dialog displays to confirm the upgrade. This change applies to upgrades for Host and Single Container Defenders on Linux and Windows.

//CWP-45932 | Rodrigo | Needs approval

* Improved testing to support the automatic updates of GKE Autopilot clusters.
The latest three Prisma Cloud releases are tested daily using the latest GKE Autopilot version for continued support.

[#bug-fixes]
=== Fixed Issues

//CWP-46005 CWP-46353
* The count of events for WAAS agentless did not correspond to the actual number of attack requests sent, this is now fixed.

//CWP-45194
* Fixed an API Discovery issue where https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-12/prisma-cloud-compute-edition-admin/waas/waas_api_discovery#_inspect_discovered_endpoints[API endpoints discovered] on app-embedded deployments were missing workload value and were showing zero vulnerabilities when the protected workload had vulnerabilities.

//CWP-46099 | Divya | Needs validation on the ticket
* On upgrading from 22.06 to 22.12.415, the compliance policy rules configured to "Block" effect fail the creation and edition of policies. This issue is fixed in 22.12.692, the "Block" effect for these complaince policies is disabled and set to "Alert" effect under *Defend > Compliance > Containers and images > Deployed > Add rule*.

[#upcoming-breaking-change]
=== Breaking Change
//CWP-45510 | on-prem only | Divya
On upgrading to 22.12.692, the Out-of-Band events are only supported if you first upgrade the Console to 22.12.585 and then upgrade to 22.12.692.

[#end-of-support]
=== End of Support Notifications

There are no end of support notifications for this update.
