:toc: macro
== 22.12 Update 1 Release Notes

The following table provides the release details:

[cols="1,4"]
|===
|Build
|22.12.xxx

|Codename
|Lagrange, 22.12 Update 1
|Release date
|Jan 9, 2023

|Type
|Maintenance release

|SHA-256 digest
|TBD
|===

//Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic download (e.g., curl, wget) of the release directly from our CDN:

// LINK

toc::[]

=== Addressed Issues

//CWP-41281
==== ARM64 bit twistcli for MacOS platforms
Download ARM64 Mac compatible version of twistcli under *Manage > System > Utilities*, or via */util/osx/arm64/twistcli* API.

//CWP-42853
==== /api/vVERSION/scans/vms API route changed
Use the API route */api/vVERSION/vms/scan* to scan VM images.
The API route */api/vVERSION/scans/vms* route is not supported anymore. 

//CWP-43836
=== UI shows incorrect warning regarding expired certificate in defender page
Fixed an issue that showed an incorrect expired certificate warning for Defenders even if the certificate was not in use.

//CWP-42673
WAAS Agentless Observers will now automatically upgrade to match the Console's version.

//CWP-42646
WAAS events will now be mapped to the appropriate OWASP Top 10 risk and OWASP API Top 10 risk.
In addition, WAAS Explorer displays event summaries for each of the OWASP Top 10 and OWASP API Top 10 risks.
