:toc: macro
== 30.00 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|30.00.140

|Code name
|Maxwell

|Release date
|Apr 23, 2023

|Type
|Major release

|SHA-256
|6d9412c019e0ad16624657285493e8d4f610556b0c8b4a7cace2fe33f2d99f96
|===

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

// You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:
//
// LINK

toc::[]

[#cve-coverage-update]
=== CVE Coverage Update

As part of the 30.00 release, Prisma Cloud has rolled out updates to its vulnerability data for Common Vulnerabilities and Exposures (CVEs) in the Intelligence Stream. The new additions are as follows:

*

[#new-features-agentless-security]
=== New Features in Agentless Security

[#new-features-core]
=== New Features in Core

[#new-features-host-security]
=== New Features in Host Security

[#new-features-serverless]
=== New Features in Serverless

[#new-features-waas]
=== New Features in WAAS

[#api-changes]
=== API Changes and New APIs

//CWP-25813
==== Adds Cache-control header for all API responses
Adds a header Cache-control: no-store in the API response to control storing of cache for all API requests.

//CWP-42671
==== Supports Amazon EC2 Auto Scaling in WAAS agentless deployment
WAAS agentless deployment now supports automatic scaling of WAAS observers to  handle a large amount of network traffic or sudden increase of traffic volume.

By default, the feature is disabled. You can enable the feature by using the PUT method in the following API endpoint:

*/api/vVERSION/policies/firewall/app/agentless*

    * autoScalingEnabled: Enables the auto scaling using Amazon EC2 Auto Scaling feature for a VPC observer handling multiple network instances. 

    Default: False

    * autoScalingMaxInstances: Specifies the maximum deployed instances for autoscaling deployment.

    Values: 1 - 10. Default: 0

[#addressed-issues]
=== Addressed Issues

*

[#backward-compatibility]
=== Backward Compatibility for New Features

*

[#end-of-support]
=== End of Support Notifications

//CWP-46784
==== Ends support for the serverless scan API endpoint
The */api/vVERSION/settings/serverless-scan* API route is no longer supported.

=== Change in Behavior
//CWP-42899
==== Supports pagination for Cloud Discovery API endpoint
The *GET, /api/vVERSION/cloud/discovery* API endpoint now displays a paginated response instead of displaying all results on a single page.

Use the query parameters such as *limit* and *offset* to view the paginated response.

//CWP-45310
==== Upgrade Defender based on a collection filter
The API endpoint */api/vVERSION/defenders/upgrade* supports upgrading to all the eligible Defenders by filtering based on the query parameter *collections* that are assigned to your user role.

This change was introduced in 22.12.694 build. If you are upgrading from a version earlier than 22.12.694 to 30.00, this behavior will now be in effect.
