:toc: macro
== 31.00 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|31.00.129

|Code name
|Maxwell

|Release date
|August 20, 2023

|Type
|Major release

|SHA-256
|989ad4e38e32de192f9545e4070175555d88038a402f2639e93f3383b8e1dc1d
|===

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

//LINK

toc::[]

[#defender-upgrade]
=== Upgrade Defender Versions 22.06 and Earlier
With the 30.00.xxx release, https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/welcome/support_lifecycle[Defender versions supported (n, n-1, and n-2)] are v31.xx.xxx, v30.xx.xxx, and v22.12.xxx.

To prepare for this update,  you must upgrade your Defenders from version v22.06.xx.xxx (Kepler) or earlier to a later version.
Failure to upgrade Defenders will result in disconnection of any Defender version below 22.12 such as 22.06.

[#cve-coverage-update]
=== CVE Coverage Update

[#enhancements]
=== Enhancements

==== Expanded Support for Red Hat's Non-RPM Content

The Prisma Cloud Intelligence Stream now includes vulnerability data on non-RPM content from Red Hat, including binaries, Python scripts, JavaScript files, and Java JAR files within layered products like OpenShift.
Rather than just flagging these as vulnerable, Prima Cloud can now leverage Red Hat's own detailed image analysis, enhancing precision in threat detection.

==== Support of Registry Tags directly in Compute Collections

Added support for registry labels under collections to enable role-based access control (RBAC).
The scan results for deployed images are now segregated with a *Custom label* within collections.
This enhancement facilitates the association between the registry and the scanned images pertaining to that registry, along with registry-based role-based access control (RBAC) for improved security and management.

==== Support for Continuous Integration (CI) Scanning of Images on Linux Using Containerd

Added the ability for users to run CI scans on Linux using the containerd runtime. This change benefits customers using Kubernetes environments, which no longer support Docker as they need to perform CI scans without Docker.

==== GKE CIS Compliance Checks for Worker Nodes

CIS Benchmark for Google Kubernetes Engine (GKE) version 1.4.0 is now supported.
This update includes compliance checks for worker nodes.

// [#new-features-agentless-security]
// === New Features in Agentless Security

// [#new-features-core]
// === New Features in Core

// [#new-features-host-security]
// === New Features in Host Security

// [#new-features-serverless]
// === New Features in Serverless

// [#new-features-waas]
// === New Features in WAAS

[#api-changes]
=== API Changes and New APIs

==== Support and Identification of Registry Asset in Registry Scan
// CWP-41710
Starting with 31.00, the value in the field *type* for an object returned in the API endpoint response *GET, api/vVERSION/registry* is now *registry* instead of *image*.

*31.00 and onwards:*
type shared.ScanType
Possible values: [registry,ciImage,container,host,agentlessHost,registry,serverlessScan,ciServerless,vm,tas,ciTas,cloudDiscovery,serverlessRadar,serverlessAutoDeploy,hostAutoDeploy,codeRepo,ciCodeRepo]

*30.03 and earlier:*
type shared.ScanType
Possible values: [image,ciImage,container,host,agentlessHost,registry,serverlessScan,ciServerless,vm,tas,ciTas,cloudDiscovery,serverlessRadar,serverlessAutoDeploy,hostAutoDeploy,codeRepo,ciCodeRepo]


[#end-of-support]
=== End of Support Notifications

==== End of Support for Cloud Native Network Segmentation (CNNS)

The ability to create CNNS policies that Defenders use to limit traffic from containers and hosts is being deprecated. The configuration settings on the console (*Compute > Defend > CNNS*) and the corresponding APIs for CNNS will be removed in the next major release.

Radar has a container and a host view, where you can view the network topology for your containerized apps and hosts respectively, and this will continue to be available.

List of API endpoints that are no longer supported:

* PUT, `{{/api/v<VERSION>/policies/firewall/network/container}}`
* GET, `{{/api/v<VERSION>/policies/firewall/network}}`
* GET, `{{/api/v<VERSION>/audits/firewall/network/container/download}}`
* GET, `{{/api/v<VERSION>/audits/firewall/network/container}}`
* GET, `{{/api/v<VERSION>/audits/firewall/network/host/download}}`
* GET, `{{/api/v<VERSION>/audits/firewall/network/host}}`

==== End of Support for Docker Access Control

The Docker Access Control at *Defend > Access > Docker* and Access User role at *Manage > Authentication > Roles* were planned for End of Support in Newton (v31.00.129) as announced in https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-release-notes/release-information/release-notes-22-06#:~:text=Upcoming%20Deprecation%20Notifications[22.06 Release Notes].
The deprecation is now extended until the next release Newton Update 1 (v31.01.xxx), when the feature will be no longer supported.

==== Support for Code Repo Scanning

Scanning your code repositories from the Prisma Cloud Compute console at *Compute > Monitor> Vulnerabilities > Code repositories* and use of Twistcli for code repo scanning was planned for End of Support in this release v31.00.129. The deprecation notice is now  extended until the next major release code named O'Neal (v32.0.xxx), when the support will be dropped.

You must now use the *Code Security* capabilities on Prisma Cloud to scan IaC templates, code repositories, and CI pipelines for misconfigurations and vulnerabilities.