:toc: macro
== 22.12 Update 2 Release Notes

The following table provides the release details:

[cols="1,4"]
|===
|Build
|22.12.xxx

|Codename
|Lagrange, 22.12 Update 2
|Release date
|Feb 12, 2023

|Type
|Maintenance release

|SHA-256 digest
|TBD
|===

//Besides hosting the download on the Palo Alto Networks Customer Support Portal, we also support programmatic download (e.g., curl, wget) of the release directly from our CDN:

// LINK

toc::[]

=== Added Support

[NOTE]
====
- From Rodrigo: I've included all the added OSes here but I don't have details on any limitations, caveats, or whether container Defenders were deployed and worked on hosts running them.
====

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-12/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn more details about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

CWP- 29653

* Added support for Oracle Enterprise Linux (OEL) 8 and 9.
You can now run Defenders on OEL 8 and 9 hosts.
Prisma Cloud now also protects containers and images running in OEL 8 and 9 hosts.
Agentless scanning is not supported for OEL 9.
Currently, vulnerabilities are matched by architecture, which leads to ARM images showing x86 relevant vulnerabilities and vice versa.

CWP- 39278

* Added support for Red Hat Enterprise Linux 9 on X86 architecture.
You can now run Defenders on RHEL 9 hosts.
Prisma Cloud now also protects containers and images running in RHEL 9 hosts.
RHEL 9 on ARM is not supported.

CWP- 39331

* Added support for Rocky Linux 8 and 9.
You can now run Defenders on hosts running Rocky Linux 8 and 9.
Prisma Cloud now also protects containers and images running in Rocky Linux 8 and 9 hosts.
Until a vulnerabilities feed is published for Rocky Linux, no operating system vulnerabilities are displayed for Rocky Linux.
Once the feed for Rocky Linux is published, the vulnerabilities will display automatically.

CWP- 39473

* Added support for Windows Server 2022. Prisma Cloud doesn't support Windows Server 2022 on AKS Windows nodes and on Tanzu Application Service.

** Container Defenders support the following features for Windows Server 2022.

*** Windows compliance scans
*** Vulnerability scans
*** Registry scans
*** Runtime scans
*** CNNS
*** Windows metadata scans

** Host Defenders support the following features for Windows Server 2022.

*** Windows compliance scans
*** Vulnerability scans
*** WAAS scans
*** Windows metadata scans

=== CVE Coverage Update

CWP- 45155 and CWP- 45090

* Fixed https://pkg.go.dev/vuln/GO-2022-1144[CVE-2022-41717] and https://pkg.go.dev/vuln/GO-2022-0969[CVE-2022-27664]: WAAS deployments were affected if you have a HTTP2 applications and have deployed WAAS to inspect HTTP2 traffic.
Upgrade your Prisma Cloud console and deployed Defenders if you use WAAS to inspect HTTP2 traffic.

* https://pkg.go.dev/vuln/GO-2023-1495[CVE-2022-41721] is included in the Intelligence Stream feed. Prisma Cloud doesn't use `MaxBytesHandler` and this vulnerability doesn't impact Prisma Cloud components.
You can continue to run any of the supported Prisma Cloud releases without risk from this vulnerability.
To remove the vulnerability alert, upgrade to the latest 22.12 release.
If you are not ready to upgrade right away, add an exception in the default *Ignore Twistlock Components* rule.
Go to *Defend > Vulnerabilities > Images > Deployed* to add the exception to suppress the vulnerability alerts for CVE-2022-41721.


=== Enhancements

[NOTE]
====
- From Rodrigo: We have a single section with all enhancements since we are not shipping a lot of features. Is the "Enhancements" heading agreeable to all?
====

CWP- 44845 - Divya's comments: No documentation required as per the comments on the ticket

//* Change default settings for newly created rules and apps

CWP- 44839 - Editing as per the comments on the ticket - this is an enhancement

* Improved registry scan logs by adding details about the registry that failed to be scanned in case no available defender was found for scanning the registry.

CWP- 44663

* Registry scan stop in the middle if one of the settings don't have a scanner

CWP- 44659

* Customer bug - API Definition Scan error when trying to display non printable characters in code editor

CWP- 44498

* Added WAAS support for whitespace in https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-12/prisma-cloud-compute-edition-admin/waas/waas_app_firewall#firewall_exceptions[JSON (body) Firewall exception].

CWP- 44161

* Added support for custom tagging agentless scanners and resources spun up within your accounts.
You can specify up to ten tags as a part of the advanced agentless configuration.
These tags don't replace any system-generated tags - they are simply added.
Tags are added to all existing resources and for new resources in your account.

CWP- 43791

* Add log when package manager files are missing in the scan

Added a log in cases when during image scan, the package manager folders required for the scan (e.g, /var/lib/dpkg) don't exist. The log will appear either in the Defender logs or twistcli stdout.
In these cases, the scan might end with 0 vulnerabilities for this image.

CWP- 41561

* Updated the agentless scanning onboarding instructions for AWS and GCP to include setting up agentless using hub and target accounts.

CWP-42648

* [API Discovery] Flag for APIs that has changed

Introduced a new column "Last changed" to API Discovery with the date of the latest change to the API.
The discovered API change history log is shown in the details pan.
Screenshot

=== Fixed Issues

CWP- 42771

* Fixed crypto miner check issue that adversely impacted the performance of the host runtime protection and of the host.
Enabling this check allows you to prevent crypto miners in your deployment.

CWP-44668 - to be validated by Elad/Matangi. + Add this as a known issue in 22.12 file

* Fixed an issue in grouping the columns under *Monitor > Events*. The events grouped by any field now display relevant results.

CWP- 44496

* Fixed `security group is malformed` error causing the VM image scans to fail in AWS EC2 environments.

CWP- 45095

* Fixed issue where the wrong type was show in the *Image details* window.

//CWP-44755

// [PCEE Only] * Fixed issue where GCP accounts onboarded to Prisma Cloud that were used as hub accounts. If the account had a master service account, the account was not imported to Compute.

CWP- 31538

* Fixed an issue where adding or updating collections in large deployments took a significant amount of time to show in Prisma Cloud.

CWP- 42596 PCSUP-12236

* Fixed an issue where the *Refresh* action on the Vulnerability Explorer page/API failed in cases where some images in the environment had a large number of containers running (~10-20K containers per image).

=== End of Support Notifications

