:toc: macro
== 30.03 Update 3 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|30.03.122

|Code name
|Maxwell, 30.03 Update 3

|Release date
|July 16, 2023

|Type
|Maintenance Release

|SHA-256
|552f167c250e7bba0a1c7402951a9b240b269c88c7ac55a0c4ee109cdc5676c3
|===

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN: 
//
// LINK

toc::[]

[#cve-coverage-update]
=== CVE Coverage Update

[#new-features-agentless-security]
=== New Features in Agentless Security

//CWP-44086
==== Scan errors visibility improvements - accounts/ region error scope

Introducing Enhanced Issue Visibility: To get the most out of agentless scanning, this update categorizes issues during the https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/agentless-scanning[agentless scan process], provides detailed information on their nature, source, and troubleshooting steps, and offers a seamless user interface experience. Easily understand and resolve issues, improving scan coverage and streamlining your scanning process.
Go to *Compute > Monitor > Vulnerabilities or Compliance* and select the *Hosts or Images* tab to check the prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/agentless-scanning-results[agentless scan results].

As a side effect, this update might display erroneous scan details, that would be auto-remediated by a maximum of 2 agentless scan cycles.

//CWP-48291
==== Added Support for Parallel Agentless Scans of Accounts and Regions

Updated the https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/agentless-scanning#scanning-process[agentless scanning process] to scan accounts and regions within those accounts in parallel.

[#new-features-core]
=== New Features in Core

//CWP-43053
==== Improved the Syslog output to Align with the API Output

Added fields to enhance the https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/audit/logging[syslog output] in alignment with the the API call responses. Fields were added for container runtime audits, host runtime audits, container incidents, and host incidents.

[#new-features-host-security]
=== New Features in Host Security

//[#new-features-serverless]
//=== New Features in Serverless

//[#new-features-waas]
//=== New Features in WAAS

[#api-changes]
=== API Changes and New APIs

[#breaking-api-changes]
=== Breaking Changes in API

[#deprecation-notice]
=== Deprecation Notice

[#addressed-issues]
=== Addressed Issues

//[#backward-compatibility]
//=== Backward Compatibility for New Features

//[#change-in-behavior]
//=== Change in Behavior

//==== Breaking fixes compare with SaaS RN
