== Control plane

//'''
//
//title: Control plane
//type: single
//url: "/3.14/upgrade/control-plane/"
//menu:
//  3.14:
//    parent: upgrade
//    identifier: upgrade-control-plane
//    weight: 100
//on-prem-only: true
//
//'''

In order to upgrade the control plane, use your xref:../start/control-plane/large-deployments/large-deployments.adoc#_about-voila[Voila] environment.

Run the upgrade script within your Voila environment:

[,console,subs="+attributes"]
----
cd $HOME/aporeto && ./activate upgrade {version-container}
----

The upgrade scripts starts and ask you to validate the changes.
Proceed to the upgrade which will perform a rolling update on all the microservices.

Once done it will wait one minute and issue an `apostate` command to check the health of your setup.

[NOTE]
====
`apostate` command may return at first that some services are degraded. If that's the case, give the Aporeto control plane a few minute to converge into a stable state, and issue the command again.
====
