== AWS Security Hub

AWS Security Hub aggregates, organizes, and prioritizes security alerts from multiple AWS services and AWS Partner Network solutions, including Prisma Cloud, to give you a comprehensive view of security across your environment.


=== Permissions

The minimum required permissions policy to integrate Prisma Cloud with AWS Security Hub is *AWSSecurityHubFullAccess*.
Whether using IAM users, groups, or roles, be sure the entity Prisma Cloud uses to access AWS Security Hub has this minimum permissions policy.

This procedure shows you how to set up integration with an IAM user (configured as a service account).
In AWS IAM, create a service account that has the *AWSSecurityHubFullAccess* permissions policy.
You will need the service account's access key ID and secret access key to integrate with Prisma Cloud.


[.task]
=== Enabling AWS Security Hub

[.procedure]
. Log into your AWS tenant and enter *Security Hub* in the *Find services* search, then select *Security Hub*.

. Click *Enable Security Hub*.

. Enable the Prisma Cloud integration.
.. Choose Integrations from the Security Hub menu.
.. Accept findings from Palo Alto Networks: Prisma Cloud Compute.
+
See https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-integrations-managing.html[AWS documentation]


// == Configuring alerts
//
// Reusable content fragment.
include::frag_config_rate.adoc[leveloffset=0]


=== Sending alerts to Security Hub

// Reusable content fragment
:aws_security_hub:
include::frag_send_alerts.adoc[leveloffset=0]


[.task]
=== Create new alert profile

Create a new alert profile.

[.procedure]
. In *Manage > Alerts*, click *Add profile*.

. Enter a name for your alert profile.

. In *Provider*, select *AWS Security Hub*.


[.task]
=== Configure the channel

Configure the channel.

[.procedure]
. In *Region*, select your region.

. Enter your *Account ID*, which can be found in the AWS Management Console under *My Account > Account Settings*.

. Select or create xref:../authentication/credentials_store.adoc#_aws[credentials], which Prisma Cloud uses to integrate with AWS Security Hub.
+
You can use an IAM user, IAM role, or AWS STS.

. Click *Send Test Alert* to test the connection.
An alert is sent immediately.

// Reusable content fragment.
include::frag_config_triggers.adoc[leveloffset=0]
