
== Superuser port is set

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 968f825e-4d62-49f9-b018-3c97e71bc6ba

|Checkov ID 
|CKV3_SAST_36

|Severity
|MEDIUM

|Subtype
|Build

|Language
|javascript

|CWEs
|https://cwe.mitre.org/data/definitions/289.html[CWE-289: Authentication Bypass by Alternate Name]

|OWASP Categories
|

|=== 

=== Description

This policy detects if a superuser port is set in the code. Superuser ports are reserved for privileged services and should not be used by regular applications. Using a superuser port could potentially lead to an authentication bypass vulnerability.

Vulnerable code example:

[source,javascript]
----
const app = express();
app.listen(80);
----

The above code is vulnerable because it sets the port to a superuser port (port 80), which is reserved for privileged services. This could allow an attacker to bypass authentication and gain unauthorized access to the application.

=== Fix - Buildtime

To fix the issue, the application should use a non-superuser port for communication.

Secure code example:

[source,javascript]
----
const app = express();
app.listen(3000);
----

The above code is no longer vulnerable because it sets the port to a non-superuser port (port 3000). Using a non-privileged port ensures that the application follows best practices and mitigates the risk of an authentication bypass.
    