== Encryption algorithm not using secure modes and padding

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4bee9e41-e34d-4de1-b9e9-2adbea88ab8d

|Checkov ID 
|CKV3_SAST_75

|Severity
|HIGH

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
a|https://owasp.org/www-project-top-ten/2017/A2_2017-Broken_Authentication[A2:2021 - Cryptographic Failures]

https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration[A6:2017 - Security Misconfiguration]

|=== 

=== Description

For cryptographic operations, it is crucial to use encryption modes and padding schemes that ensure the confidentiality, integrity, and authenticity of the data. When insecure modes or schemes are employed, it compromises the security of the encrypted data, leading to vulnerabilities that attackers can exploit.

Two common pitfalls are:

1. **Use of ECB mode:** ECB (Electronic Codebook) mode for block cipher encryption algorithms doesn’t provide adequate message confidentiality. The same plaintext block will always produce the same ciphertext block, making it unsuitable for most applications.
2. **Use of CBC with padding:** CBC (Cipher Block Chaining) with padding is vulnerable to padding oracle attacks.

For RSA encryption, the OAEP padding scheme is recommended over older padding schemes like PKCS#1 v1.5.

Vulnerable code might look like:

[source,javascript]
----
const cipher = crypto.createCipheriv('aes-128-cbc', key, iv);
const encrypted = cipher.update(plaintext);
----

=== Fix - Buildtime

To enhance the security of encryption:

1. Avoid using ECB mode for block cipher encryption algorithms.
2. Avoid CBC mode with padding because of its vulnerability to padding oracle attacks.
3. Use modes like GCM, CCM, CWC, EAX, IAPM, or OCB, which are designed to provide both data authenticity and confidentiality.
4. For RSA encryption, prefer the OAEP padding scheme.

A secure encryption example:

[source,javascript]
----
const cipher = crypto.createCipheriv('aes-128-gcm', key, iv);
const encrypted = cipher.update(plaintext);
----

By following these practices, you can ensure that your cryptographic operations remain secure against potential attacks and vulnerabilities.
