== Encryption Keys are less than 16 bytes

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| b7e4aa6e-583d-4930-b966-1ad5151fa377

|Checkov ID 
|CKV3_SAST_33

|Severity
|MEDIUM

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/326.html[CWE-326: Inadequate Encryption Strength]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects the use of encryption keys with inadequate size in JavaScript. Encryption keys with a size less than 16 bytes may pose a risk of being brute-forced, leading to vulnerabilities like unauthorized access or data breaches.

Some common patterns this policy checks for include the usage of:
- `nacl.randomBytes`
- `randomBytes` from either the `randombytes` module or `node:crypto`
- `getBytesSync` from `node-forge`
- `cryptoRandomString` and `cryptoRandomStringAsync`
- `brorand.Rand` instances

Example of violating code:

[source,javascript]
----
const nacl = require('tweetnacl');
const key = nacl.randomBytes(8);
----

=== Fix - Buildtime

To mitigate this issue, always use encryption keys that are at least 16 bytes in length. This ensures a higher degree of encryption strength, making brute-force attacks significantly more challenging.

Example of corrected code:

[source,javascript]
----
const nacl = require('tweetnacl');
const key = nacl.randomBytes(16);
----

In this example, an encryption key of the recommended size (16 bytes) is generated, ensuring adequate cryptographic strength.
