
== Incorrect regular expression

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4ce2c1ac-fefe-4288-a56b-bbd3f9504e50

|Checkov ID 
|CKV3_SAST_159

|Severity
|MEDIUM

|Subtype
|Build

|Language
|javascript, typescript

|CWEs
|https://cwe.mitre.org/data/definitions/185.html[CWE-185: Incorrect Regular Expression]


|=== 

=== Description

This SAST policy detects the usage of the `RegExp` constructor with a non-literal variable, which can lead to a Regular Expression Denial of Service (ReDoS) vulnerability. If an adversary is able to supply a malicious regex, it can cause the application to become unresponsive, potentially affecting the availability of the application for other users.

Vulnerable code example:

[source,javascript]
```
var userInput = prompt("Enter a regular expression:");
var regex = new RegExp(userInput);
```

In the above code, the `RegExp` constructor is used with the `userInput` variable, which comes from user input. This allows an adversary to supply a malicious regex that can potentially cause the application to perform excessive and inefficient matching, resulting in a DoS condition.

=== Fix - Buildtime

To fix this issue, user-supplied regular expressions should never be allowed. Instead, the regular expression should be hardcoded or generated from a trusted source. If user input is necessary for building regular expressions, it is recommended to validate and sanitize the input to prevent any malicious patterns.

Secure code example:

[source,javascript]
```
var userInput = prompt("Enter a regular expression:");
var regex = /^([a-z]+)\d+$/;
```

In the above code, a hardcoded regular expression `/^([a-z]+)\d+$/` is used instead of the user-supplied input. This ensures that only specific patterns are matched, mitigating the risk of excessive matching and potential DoS.

By using a hardcoded regular expression, the application no longer relies on user input for generating regular expressions, eliminating the potential for malicious patterns and ReDoS vulnerabilities.
    