== Escape markup is removed leading to risk for XSS

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a295bfe7-0c4f-4804-ac43-ecb31479e2ec

|Checkov ID 
|CKV3_SAST_27

|Severity
|LOW

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/79.html[CWE-79: Improper Neutralization of Input During Web Page Generation ("Cross-site Scripting")]

|OWASP Categories
a|https://owasp.org/Top10/A7_2017-Cross-Site_Scripting_(XSS)/[A7:2017 - Cross-Site Scripting (XSS)]

https://owasp.org/Top10/A03_2021-Injection/[A03:2021 - Injection]

|=== 

=== Description

This policy aims to flag instances where the `escapeMarkup` option is explicitly set to `false`. In some template engines, setting `escapeMarkup` to `false` would disable the escaping of HTML entities, making the application vulnerable to Cross-site Scripting (XSS) attacks.

Example of violating code:

[source,javascript]
----
let template = new TemplateEngine();
// Disabling escapeMarkup
template.escapeMarkup = false;
----

This code is problematic because it disables the HTML escaping feature, making it susceptible to XSS attacks.

=== Fix - Buildtime

To resolve this issue, do not set `escapeMarkup` to `false` or leave it at its default value, which is typically `true`. If needed, handle special cases more securely.

Example of corrected code:

[source,javascript]
----
let template = new TemplateEngine();
// Leave escapeMarkup at its default value (typically true)
// Or explicitly set it to true
template.escapeMarkup = true;
----

By setting `escapeMarkup` to its default value or explicitly setting it to `true`, the code ensures that HTML entities are escaped properly, mitigating the risk of XSS attacks.

