== Detection of XSS vulnerability

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e003de26-7669-485a-9686-4a672d69cf89

|Checkov ID 
|CKV3_SAST_92

|Severity
|LOW

|Subtype
|Build

|Language
|javascript

|CWEs
|https://cwe.mitre.org/data/definitions/554.html[CWE-554: ASP.NET Misconfiguration: Not Using Input Validation Framework]

|OWASP Categories
|

|=== 

=== Description

This SAST policy detects the usage of the Express framework without the Helmet framework for protection against XSS (Cross-Site Scripting) attacks.

Vulnerable code example:

[source,javascript]
----
const express = require('express');
----

The above code is vulnerable because it initializes the Express framework without using the Helmet framework for securing against XSS attacks.

=== Fix - Buildtime

To fix the issue, the code should be modified to include the Helmet framework for XSS protection. 

Secure code example:

[source,javascript]
----
const express = require('express');
const helmet = require('helmet');

app.use(helmet());
----

The secure code includes the Helmet framework by requiring it and using it with the Express framework. This way, the application is protected against XSS attacks.
    