
== Insecure SSL Server Identity Verification Disabled

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8802ca75-6b56-4d9b-80da-87c32bc84673

|Checkov ID 
|CKV3_SAST_101

|Severity
|MEDIUM

|Subtype
|Build

|Language
|javascript

|CWEs
|https://cwe.mitre.org/data/definitions/297.html[CWE-297: Insecure SSL Server Identity Verification Disabled]

|OWASP Categories
|

|=== 

=== Description

This policy detects when the SSL server identity verification is disabled in JavaScript code. Disabling SSL/TLS certificate validation can lead to insecure communication and authentication failures.

Vulnerable code example:

[source,javascript]
----
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0";
----

The above code sets the environment variable "NODE_TLS_REJECT_UNAUTHORIZED" to 0, disabling SSL server identity verification. This means that the code will accept any SSL certificate, even if it is not valid or cannot be trusted.

=== Fix - Buildtime

To fix the issue, you should remove or disable the code that sets "NODE_TLS_REJECT_UNAUTHORIZED" to 0. Instead, use proper SSL server identity verification to ensure secure communication.

Secure code example:

[source,javascript]
----
// Enable SSL server identity verification
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = "1";
----

In the secure version of the code, the environment variable "NODE_TLS_REJECT_UNAUTHORIZED" is set to 1, enabling SSL server identity verification. This ensures that the code will only accept valid and trusted SSL certificates.

Note: Disabling SSL server identity verification should only be used for debugging purposes and not in production code.
    