== Use of insecure HTTP Connections with Axios

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8d02cbdd-d8a0-4a19-84b7-cb703fe313f8

|Checkov ID 
|CKV3_SAST_40

|Severity
|LOW

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/319.html[CWE-319: Cleartext Transmission of Sensitive Information]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects instances in JavaScript where Axios, a popular HTTP client, is used with an unsecured HTTP connection. Such unencrypted connections, which start with "http://", can expose sensitive data to potential eavesdroppers or malicious entities. For data protection, it's essential to always use HTTPS, which encrypts data transmitted between the client and server.

The policy specifically checks for direct Axios requests where the `url` option is set to an unsecured URL.

Example of violating code:

[source,javascript]
----
axios({
  method: 'get',
  url: 'http://example.com/data'
});
----

=== Fix - Buildtime

To address this security concern, ensure that Axios requests are made over HTTPS. Convert "http://" URLs to "https://" to secure data transmission through encryption.

Example of corrected code:

[source,javascript]
----
axios({
  method: 'get',
  url: 'https://example.com/data'
});
----

In the corrected example, a secure HTTPS connection is utilized, ensuring data is encrypted during transit, safeguarding it from potential threats.
