== Insecure use of weak hashing algorithms

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| c3153658-27bf-455a-aed7-8684bcf86d6b

|Checkov ID 
|CKV3_SAST_38

|Severity
|HIGH

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/328.html[CWE-328: Use of Weak Hash]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects instances in JavaScript where weak hashing algorithms are used. Leveraging weak algorithms can expose applications to vulnerabilities like hash collisions, making it easier for attackers to deduce the original input. 

Specifically, this policy checks for the use of the `createHash` and `createHmac` functions with algorithms such as:
- sha1
- md2
- md4
- md5
- ripemd160

Example of violating code:

[source,javascript]
----
const crypto = require('crypto');
const hash = crypto.createHash('md5').update('password').digest('hex');
----

=== Fix - Buildtime

To address this issue, replace weak hashing algorithms with stronger ones, such as SHA-256 or SHA-3. Strengthening the hashing algorithm helps ensure the security of hashed data, making it more resistant to attacks.

Example of corrected code:

[source,javascript]
----
const crypto = require('crypto');
const hash = crypto.createHash('sha256').update('password').digest('hex');
----

In the corrected example, a stronger hashing algorithm (SHA-256) is utilized, ensuring better cryptographic security for the hashed data.
