== Insecure use of `eval` with non-string parameters

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 3b887b72-01c4-4b3a-ac10-91ed37ef9284

|Checkov ID 
|CKV3_SAST_41

|Severity
|MEDIUM

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/94.html[CWE-94: Improper Control of Generation of Code ("Code Injection")]

|OWASP Categories
|https://owasp.org/www-project-top-ten/2021/A03_2021-Injection/[A03:2021 - Injection]

|=== 

=== Description

This policy detects the use of the `eval` function in JavaScript with parameters that are not strings. The use of `eval` can introduce significant security risks, especially when it is used with non-string parameters, as this can easily lead to code injection attacks.

For a deeper understanding of the risks associated with `eval`, refer to the [Mozilla Developer Network documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!) and the [ESLint Community Plugin](https://github.com/eslint-community/eslint-plugin-security/blob/main/rules/detect-eval-with-expression.js).

Example of violating code:

[source,javascript]
----
let userCode = getUserInput();  // Potentially unsafe user input
eval(userCode);
----

=== Fix - Buildtime

To mitigate this vulnerability, avoid using the `eval` function. If dynamic code execution is necessary, consider safer alternatives, validate all inputs rigorously, and ensure that only string parameters are passed to `eval`.

Example of a safer approach:

[source,javascript]
----
let userCode = String(getUserInput());  // Convert to string and sanitize input
// ... additional validations ...
if(isValid(userCode)) {
    eval(userCode);
}
----

However, even with stringent validations, the use of `eval` is generally discouraged. It's best to seek alternative methods to achieve the required functionality without dynamic code execution.

