== Complex/formatted SQL query

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a48a5fcb-1e50-4f82-9096-9105a84aecf9

|Checkov ID 
|CKV3_SAST_83

|Severity
|HIGH

|Subtype
|Build

|Language
|javascript

|CWEs
a|https://cwe.mitre.org/data/definitions/20.html[CWE-20: Improper Input Validation]

https://cwe.mitre.org/data/definitions/89.html[CWE-89: Improper Neutralization of Special Elements used in an SQL Command]

|=== 

=== Description

This policy detects complex or formatted SQL queries that increase the risk of SQL injection. It advises avoiding these and opting for safer alternatives like parameterized queries, prepared statements, or ORM frameworks. It ensures that no query uses direct concatenation of untrusted values.

Vulnerable code example:

[source,javascript]
----
const query = 'SELECT * FROM users WHERE id = ' + req.params.id;
db.query(query, (err, result) => {
  // handle result
});
----

=== Fix - Buildtime

To fix the issue, you should use parameterized queries or prepared statements instead of direct concatenation. It helps to prevent SQL injection attacks by separating the SQL code from the user input.

Secure code example:

[source,javascript]
----
const query = 'SELECT * FROM users WHERE id = ?';
db.query(query, [req.params.id], (err, result) => {
  // handle result
});
----
    