
== Sensitive Data Logging

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| dcb4c387-6425-4c67-8bb0-b533d1c23ce2

|Checkov ID 
|CKV3_SAST_153

|Severity
|MEDIUM

|Subtype
|Build

|Language
|javascript

|CWEs
|https://cwe.mitre.org/data/definitions/532.html[CWE-532: Insertion of Sensitive Information into Log File]

|OWASP Categories
|

|=== 

=== Description

This policy detects sensitive data logging in JavaScript code. It ensures that web applications do not log sensitive data, including credit card numbers and personal details. Logging mechanisms should be configured to mask or remove sensitive data from logs to comply with regulations and protect user privacy.

Vulnerable code example:

[source,javascript]
```
const name = document.getElementById('name').value;
console.log('User name: ' + name);
```

The above code is vulnerable because it logs the user's name without any masking or removal of sensitive data.

=== Fix - Buildtime

To fix the issue, you should configure the logging mechanism to mask or remove sensitive data. Here's an example of secure code:

[source,javascript]
```
const name = document.getElementById('name').value;
console.log('User name: ' + maskSensitiveData(name));
```

In the secure code example, the sensitive data (user's name) is passed to a function called `maskSensitiveData` before being logged. This function ensures that the sensitive data is properly masked or removed, preventing it from being logged in plaintext.
    