== Weak SSL/TLS protocols

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8188789a-90fa-4e7e-acba-942e682f8c4d

|Checkov ID 
|CKV3_SAST_77

|Severity
|MEDIUM

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Inadequate Encryption Strength]

|OWASP Categories
a|https://owasp.org/www-project-top-ten/2021/A02_2021-Cryptographic_Failures[A2:2021 - Cryptographic Failures]

https://owasp.org/www-project-top-ten/2021/A07_2021-Identification_and_Authentication_Failures[A7:2021 - Identification and Authentication Failures]

https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure[A3:2017 - Sensitive Data Exposure]

https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration[A6:2017 - Security Misconfiguration]

|=== 

=== Description

To ensure the confidentiality and integrity of data during transmission, it's imperative to use secure SSL/TLS protocol versions. Outdated or insecure versions, such as TLSv1.0 or TLSv1.1, contain vulnerabilities that attackers can exploit.

Relying on system defaults for selecting the protocol version may lead to non-compliance with industry standards and best practices. To safeguard against potential attacks, you should always explicitly set your protocol versions in configurations.

Vulnerable code example:

[source,javascript]
----
const serverOptions = {
  secureProtocol: 'TLSv1_0_method'
};
const server = https.createServer(serverOptions, app);
----

=== Fix - Buildtime

To achieve secure data transmission:

1. Review configurations and ensure that the protocol versions are set to at least TLSv1.2.
2. Avoid using insecure protocol versions.
3. Do not rely on system or library defaults. Be explicit in your configurations.
4. Periodically review and update configurations to match evolving security best practices and standards.

Secure encryption example:

[source,javascript]
----
const serverOptions = {
  secureProtocol: 'TLSv1_2_method'
};
const server = https.createServer(serverOptions, app);
----

By adhering to these guidelines, you ensure secure communication channels, reducing the risk of data breaches and man-in-the-middle attacks.
