
== Ensure Usage of JWT Algo

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4feb0029-74b0-430c-b2af-289cebac84fd

|Checkov ID 
|CKV3_SAST_146

|Severity
|MEDIUM

|Subtype
|Build

|Language
|javascript

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects the usage of JWT (JSON Web Token) with a non-secure algorithm.

Vulnerable code example:

[source,javascript]
----
const jwt = require('jsonwebtoken');

const payload = {
  user: 'admin',
  role: 'admin'
};

const token = jwt.sign(payload, 'secret', { algorithm: 'none' });

console.log(token);
----

In the above code, the `algorithm` option for JWT signing is set to `'none'`. This means that the JWT token is not encrypted and can be easily tampered with or read by unauthorized parties.

=== Fix - Buildtime

To fix the issue, you should ensure that a secure algorithm is used for JWT signing, such as HMAC SHA256 or RSA.

Secure code example:

[source,javascript]
----
const jwt = require('jsonwebtoken');

const payload = {
  user: 'admin',
  role: 'admin'
};

const token = jwt.sign(payload, 'secret', { algorithm: 'HS256' });

console.log(token);
----

In the fixed code, the `algorithm` option is set to `'HS256'`, which uses HMAC SHA256 for JWT encryption. This ensures that the JWT token is securely encrypted and protected from tampering or unauthorized access.
    