== GitHub branch protection not enforced on administrators

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|8284c802-c8b5-48eb-a911-4731b675b0e1

|Severity
|Low
// add severity level

|Category
|Flow Control Mechanism
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Branch protection rules are not enforced on administrators in an actively used repository*. These rules are a mechanism to enforce a set of requirements before code can be pushed to a repository branch. These rules can apply to organization and repository administrators or to exclude them.
Despite the fact that administrators can modify branch protection rules, it is recommended to apply these rules even for administrators, to assist with restricting push of unreviewed code to a branch.
* An actively used repository has at least two contributors, over 50 commits, and was updated in the last 90 days.

=== Recommended Solution - Buildtime

To enforce branch protection on administrators:
 
. Browse to the repository settings.
. Under **Branches**, edit the rule that applies to the repository default branch.
. Check the **Include Administrators** setting.

