== GitHub deploy key has a weak SSH signature

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|72410992-631e-4a37-a229-7626310c1049

|Severity
|Low
// add severity level

|Category
|Identity and Access Management
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Repository deploy keys created with weak signature algorithms can allow attackers to perform a man-in-the-middle- attack and compromise the integrity and confidentiality of the communications with the version control system. 
A deploy key created with the deprecated **ssh-dss** algorithm is in use in the GitHub organization. This algorithm was deprecated in **OpenSSH 7.0**. For more on deploy keys refer to http://www.openssh.com/legacy.html.

=== Recommended Solution - Buildtime

Revoke all **ssh-dss keys** in use. Instead, use any of the following supported **OpenSSH** key types:

* ecdsa
* ecdsa-sk
* ed25519
* ed25519-sk
* rsa

To replace a deploy key:

. Create a new private key on the server intended to use it, using one of the recommended algorithms.
. Create a new deploy key using the matching public key in the same repository that the current key was created on.
. Direct the server to use the new deploy key.
. Delete the older deploy key from the GitHub repository.

==== Create and delete access keys

* Create and delete deploy keys through the console: Browse to the **Deploy Keys** tab under the repository settings.

* Create and delete deploy keys through the API: Refer to the GitHub API documentation: https://docs.github.com/en/rest/reference/repos#deploy-keys.
