== GitHub inactive user account programmatic credentials   

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|647b1914-4001-4b65-8ec7-c6f7dd57c0a8

|Severity
|Medium
// add severity level

|Category
|Identity and Access Management
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

GitHub user account programmatic credentials including personal access tokens (PAT) and SSH keys authorized by SAML SSO are inactive for more than 90 days. Although not in use, these credentials are still valid, enlarging the attack surface. 

=== Recommended Solution - Buildtime

Minimize potential risks by deleting user account programmatic credentials that are not in use: 

* Request the users to de-authorize or delete PATs and SSH Keys that are not in use
* Admins can delete credentials through the GitHub API 

==== Delete Credentials

* **Delete Credentials from the GitHub web interface**

** **SSH Keys**: In your GitHub account select **Settings** > **SSH and GPG keys** > deauthorize or delete the SSH key

** **PAT**: In your GitHub account select **Settings** > **Developer Settings** > **Personal access tokens** > deauthorize or delete the personal access token

* **Delete Credentials using the Admin API**: Refer to the Admin API: https://docs.github.com/en/rest/orgs/orgs#remove-a-saml-sso-authorization-for-an-organizatio◊n







