== Unrotated GitHub deploy keys

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID 
|aa752dd5-6f92-41b5-9313-ac82e2b05590

|Severity
|Low
// add severity level

|Category
|Identity and Access Management
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

Deploy keys created on GitHub repositories were not rotated for more than 180 days. 
As long as a deploy key exists, the greater the potential for an attacker to gain access to the key. 
An attacker who obtains access to a deploy key will have direct access to the repository code and will be able to edit the code if the key is assigned **write** permissions.

=== Recommended Solution - Buildtime

To minimize the risk of a stolen deploy key being used by an attacker, it is recommended to rotate deploy keys within a maximum period of 180 days after creating the key.

. Create a private key on the server that will consume the key.
. Create a deploy key using the matching public key in the same repository the current key was created on.
. Direct the server to use the new key.
. Delete the old deploy key from the GitHub repository.

There are two options for creating and deploying keys: 

* Through the console: browse to the **Deploy Keys** tab under the repository **Settings** and select **Add Deploy Key**.

* Through the API: refer to the GitHub API documentation: https://docs.github.com/en/rest/reference/repos#deploy-keys




