==  

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 

|Prisma Cloud Policy ID
|eee07e5f-52dc-41cc-b703-27bc8159e5a5

|Severity
| Info
// add severity level

|Category
|System Configuration 
// add category+link

|Subtype
|Build
// add subtype-build/runtime

|Frameworks
|GitHub

|=== 

=== Description 

GitHub Actions is the CI solution offered by GitHub, allowing to execute code within the context of GitHub repositories. Actions is enabled by default in any GitHub organization, and in any repository.
As any organization member can run workflows execute actions against repository code, and interact with the GitHub API from within the workflow, including API actions that require **write** permissions, GitHub Actions serves as a surface for potential attacks against the repository and organization, even if the service is not in use in the organization or repository.

=== Recommended Solution - Buildtime

If GitHub Actions is not in use in the organization, disable it completely at the organization level. If it is in use in the organization, restrict it to the specific repositories in which it is used:
[.procedure]
. Browse to the organization **Settings**.
. Select **Actions**, and under **Policies**, disable **GitHub Actions**, or restrict to specific repositories.



