== Integrate with secrets stores

To inject secrets into your containers, you must first integrate Prisma Cloud with your secrets manager, and then set up rules for injecting specific secrets into specific containers.

Prisma Cloud can integrate with the following secrets managers:

* xref:../secrets/secrets-stores/aws-secrets-manager.adoc#[AWS Secrets Manager]
* xref:../secrets/secrets-stores/aws-systems-manager-parameters-store.adoc#[AWS Systems Manager Parameters Store]
* xref:../secrets/secrets-stores/azure-key-vault.adoc#[Azure Key Vault]
* xref:../secrets/secrets-stores/cyberark-enterprise-password-vault.adoc#[CyberArk Enterprise Password Vault]
* xref:../secrets/secrets-stores/hashicorp-vault.adoc#[HashiCorp Vault] (versions 0.9.x and older, and versions 0.10 and later)


=== Refresh interval

By default, the refresh interval is disabled.
That means if you change a secret’s value in the secrets store, you must force Prisma Cloud to update its list of values.
In Console, go to *Defend > Access > Secrets* and click *Refresh secrets* to force Prisma Cloud to fetch the latest values of all secrets from their configured stores.

You can also configure Prisma Cloud to periodically retrieve the latest values of all the secrets from their stores.
In Console, go to *Manage > Authentication > Secrets*, click *Edit* next to the *Secrets refresh interval* field, and specify an integer value in hours.
Setting the refresh interval to 0 disables automatic periodic refreshes.
