[#idde117f54-0bc9-497a-a8d3-fe6cac849b65]
== Prisma Cloud Resource Query Language (RQL)
Learn what RQL is and how to use this powerful tool to investigate issues in real-time in your cloud environments.

Prisma Cloud Resource Query Language (RQL) is a powerful and flexible tool that helps you gain security and operational insights about your deployments in public cloud environments. You can use RQL to perform configuration checks on resources deployed on different cloud platforms and to gain visibility and insights into user and network events. You can use these security insights to create policy guardrails that secure your cloud environments.

RQL is a structured query language that resembles Structured Query Language (SQL). RQL supports the following types of queries:

* *Config*—Use xref:config-query/config-query.adoc#id9f10d8f9-7bdf-4ce7-a97d-6dfa71d27856[Config Query] to search for the configuration of the cloud resources.

* *Event*—Use xref:event-query/event-query.adoc#id7f21ba55-c711-4996-be59-3e6ce80ea9e4[Event Query] to search and audit all the console and API access events in your cloud environment.

* *Network*—Use xref:network-query/network-query.adoc#id6e80b7a7-43a3-4f93-baf6-45604a8fe54f[Network Query] to search real-time network events in your environment.

Use RQL to find answers to fundamental questions that help you understand what is happening on your network. For example, you can find answers to the following questions:

* Do I have S3 buckets with encryption disabled?

* Do I have databases that are directly accessible from the internet?

* Who uses a root account to manage day-to-day administrative activities on my network?

* Which cloud resources are missing critical patches that make them exploitable?




