== YAML


=== Description 


YAML is a digestible data serialization language often used to create configuration files with any programming language.
Designed for human interaction, YAML is a strict superset of JSON, another data serialization language.
But because it's a strict superset, it can do everything that JSON can and more.
One major difference is that newlines and indentation actually mean something in YAML, as opposed to JSON, which uses brackets and braces.


*Package Managers* 




*GitHub Actions GitHub Actions is a continuous integration and delivery (CI/CD) platform that allows you to automate your build, test and deployment pipeline.* 


You can create workflows that build and test every pull request to your repository, or deploy merged pull requests to production.
GitHub Actions goes beyond DevOps-only and lets you run workflows while other events happen in your repository.
For example, you can run a workflow to automatically add the appropriate labels whenever someone creates a new issue in your repository.
GitHub provides Linux, Windows and macOS virtual machines to run your workflows, or you can host your own self-hosted runners in your own data center or cloud infrastructure.
A workflow is a configurable automated process that runs one or more tasks.
Workflows are defined by a YAML file checked in to your repository and run when triggered by an event in your repository.
They can also be triggered manually or on a pre-configured schedule.
Workflows are defined in the _.github/workflows_ directory in a repository.
A repository can have multiple workflows, each of which can perform a different set of tasks.
For example, you can have one workflow to build and test pull requests, another workflow to deploy your application every time a release is created, and a third workflow that adds a label every time someone opens a new issue.
Files:  `workflow.yaml`


....
{
    "data": {
        "h-0": "Package manager",
        "0-0": "GitHub Actions",
        "h-1": "Scan",
        "h-2": "Fix",
        "h-3": "Dependency tree",
        "h-4": "Licenses",
        "0-1": "\u2714\ufe0f"
    },
    "cols": 5,
    "rows": 1
}
....
