== Kotlin


*Description* 


Kotlin is a general purpose, free, open source, statically typed "`pragmatic`" programming language initially designed for the JVM (Java Virtual Machine) and Android that combines object-oriented and functional programming features.
It is focused on interoperability, safety, clarity, and tooling support.
Versions of Kotlin targeting JavaScript ES5.1 and native code (using LLVM) for a number of processors are in production as well.
Kotlin originated at JetBrains, the company behind IntelliJ IDEA, in 2010, and has been open source since 2012.
The Kotlin team currently has more than 90 full-time members from JetBrains, and the Kotlin project on GitHub has more than 300 contributors.
JetBrains uses Kotlin in many of its products including its flagship IntelliJ IDEA.


*Package Managers* 




*Gradle Gradle is a fully-open source build automation system that uses the concepts you see on Apache Maven and Apache Ant.* 


It uses a domain-specific language based on the programming language Groovy, differentiating it from Apache Maven - which uses XML for its project configuration.
It also determines the order of tasks run by using a directed acyclic graph.
Files:  `build.gradle.kts`


....
{
    "data": {
        "h-0": "Package manager",
        "h-1": "Scan",
        "h-2": "Fix",
        "h-3": "Dependency tree",
        "h-4": "License",
        "0-0": "Gradle",
        "0-1": "\u2714\ufe0f",
        "0-2": "\u2714\ufe0f",
        "0-3": "\u2714\ufe0f",
        "0-4": "\u2714\ufe0f"
    },
    "cols": 5,
    "rows": 1
}
....
