== Python


*Description* 


Python is an interpreted, object-oriented, high-level programming language with dynamic semantics.
Due to its high-level, built-in data structures, combined with dynamic typing and dynamic binding, is is a preferred language for Rapid Application Development, as well as for use as a scripting or glue language to connect existing components together.
Python's simple, easy to learn syntax emphasizes readability and therefore reduces the cost of program maintenance.
Python supports modules and packages, which encourages program modularity and code reuse.
The Python interpreter and the extensive standard library are readily available in source or binary form for all major platforms, and can be freely distributed.


*Package Managers* 




*pip pip is the standard package manager for Python.* 


It allows you to install and manage additional packages that are not part of the Python standard library.
The importance of package management is expressed by the fact that Python's installers have included pip since versions 3.4 and 2.7.9, for Python 3 and Python 2, respectively.
Files:  `pipfile.lock` `requirements.txt`


*Poetry Poetry is a tool for dependency management and packaging in Python.* 


It allows you to choose the libraries your project depends on and manages them for you via installations and updates.


....
{
    "data": {
        "h-0": "Package manager",
        "h-1": "Scan",
        "h-2": "Fix",
        "h-3": "Dependency tree",
        "h-4": "Licenses",
        "0-4": "\u2714\ufe0f",
        "0-3": "\u2714\ufe0f",
        "0-2": "\u2714\ufe0f",
        "0-1": "\u2714\ufe0f",
        "0-0": "pip",
        "1-0": "Poetry",
        "1-1": "\u2714\ufe0f",
        "1-2": "\u2714\ufe0f",
        "1-3": "\u2714\ufe0f",
        "1-4": "\u2714\ufe0f"
    },
    "cols": 5,
    "rows": 2
}
....
