== Ruby


=== Description 


Ruby is a general purpose programming language that you can use to write all sorts of programs.
It is the base language of the popular web applications framework called *Ruby on Rails*.
Ruby is designed to feel "natural": Ruby programs often read like conversations, so they can easily be understood by non-Ruby programmers, or even non-programmers.
Unlike many other programming languages, Ruby offers several different ways to do the same thing;
therfore, it is considered the programming language "with the human touch".


*Package Managers* 




*Bundler RubyGems deals with the creation, distribution, and versioning of individual Gems.* 


Bundler deals with a collection of Gems required by a project.
Bundler tracks all the Gems used in a Ruby project in a file called "Gemfile".
An engineer who starts working on an existing project for the first time will use Bundler to install all the Gems defined in the Gemfile.
Of note, Bundler is also a Gem itself: you can install or update Bundler using RubyGem command line tools.
Files:  `gemfile` `gemfile.lock`


....
{
    "data": {
        "h-0": "Package manager",
        "h-1": "Scan",
        "h-2": "Fix",
        "h-3": "Dependency tree",
        "h-4": "Licenses",
        "0-0": "Bundler",
        "0-1": "\u2714\ufe0f",
        "0-2": "\u2714\ufe0f",
        "0-3": "\u2714\ufe0f",
        "0-4": "\u2714\ufe0f"
    },
    "cols": 5,
    "rows": 1
}
....
