:toc: macro
== 32.00 Release Notes

The following table outlines the release particulars:

[cols="1,4"]
|===
|Build
|32.00.159

|Code name
|O'Neal

|Release date
|December 3, 2023

|Type
|Major release

|SHA-256
|39d1f808550f7491dcc63e392b5eb55e8f9068494b4f49c07c71da17433f7396
|===

Review the https://docs.paloaltonetworks.com/prisma/prisma-cloud/31/prisma-cloud-compute-edition-admin/install/system_requirements[system requirements] to learn about the supported operating systems, hypervisors, runtimes, tools, and orchestrators.

//You can download the release image from the Palo Alto Networks Customer Support Portal, or use a program or script (such as curl, wget) to download the release image directly from our CDN:

//LINK

toc::[]

[#upgrade]
=== Upgrade from Previous Releases

[#upgrade-defender]
==== Upgrade Defender Versions 22.06 and Earlier

With the `v32.00` release, https://docs.paloaltonetworks.com/prisma/prisma-cloud/32/prisma-cloud-compute-edition-admin/welcome/support_lifecycle[Defender versions supported (n, n-1, and n-2)] are `v32.00`, `v31.00`, and `v30.00`.

To prepare for this update, you must upgrade your Defenders from version `v22.06` (Kepler) or earlier to a later version.
Failure to upgrade Defenders will result in disconnection of any Defender version below `v22.12` such as `v22.06`.

[#upgrade-console]
==== Upgrade the Prisma Cloud Console

With the `v32.00` release, the https://docs.paloaltonetworks.com/prisma/prisma-cloud/32/prisma-cloud-compute-edition-admin/welcome/support_lifecycle[supported Console versions (n, n-1, and n-2)] are `v32.00`, `v31.00`, and `v30.00`.

You can upgrade the Prisma Cloud console directly from any version for n-1 to n.
With `v30.00` as n-1 and `v31.00` as n, you can for example go directly from `v30.01.153` to `v31.00.129`.

You have to upgrade any version of `v22.00` to `v30.00` before upgrading to `v31.00`.
For example, you can upgrade from `v22.12.693` to `v30.02.123` and then upgrade to `v32.00.159`.

//[#cve-coverage-update]
//=== CVE Coverage Update

[#enhancements]
=== Enhancements

//CWP-47397
==== Added the Agentless Scanning Report

The agentless scanning report is now available under *Runtime Security > Cloud Accounts*.
This report provides you with complete visibility of all hosts in your cloud account at the account and regional level.
It includes clear reporting of each host, the corresponding scan status, and further details.


//CWP-52883
==== Added the Ability to Scan all Supported Binaries

Agentless malware scanning detects all supported binaries and shared libraries on both Linux and Windows operating systems.
For example, malicious ELF files on Windows machines are now detected.

//[#new-features-agentless-security]
// === New Features in Agentless Security

// [#new-features-core]
// === New Features in Core

// [#new-features-host-security]
// === New Features in Host Security

// [#new-features-serverless]
// === New Features in Serverless

// [#new-features-waas]
// === New Features in WAAS

[#api-changes]
=== API Changes and New APIs


[#addressed-issues]
=== Addressed Issues

//CWP-52436
* Fixed an issue with agentless scanning that in some conditions failed scanning encrypted volumes when using hub mode in AWS.

//CWP-52777 CWP-52736
* In `v31.02.133`, the new 81 out-of-box admission control rules in Rego were not available by default. This is now fixed. With the `v32.00` Console, you now get all the 81 OOB admission control rules.

//CWP-51754
* Fixed an issue where "sourceType" field was missing for Splunk alert messages. Users can now add "sourceType" field to the custom alert JSON of Splunk and prisma cloud will define the external field based on the custom one.

//CWP-50983
* Fixed an issue where the progress bar while scanning deployed images was not reported correctly.

//CWP-50312
* Fixed an issue where Nuget vulnerabilities of same the package with different path appear with the same path.

// CWP-48205, PCSUP-15977
* Fixed an issue that stopped the registry scan due to an invalid credentials error. The registry scan now completes on credential fetch errors.

// CWP-45971
* Custom rule names are now populated for runtime custom rule incidents. Also, labels are reported for when the incident occurred in a Kubernetes cluster.

[#end-of-support]
=== End of Support Notifications

//CWP-49461
==== Ended Support for Cloud Native Network Segmentation (CNNS)

The ability to create CNNS policies that Defenders use to limit traffic from containers and hosts is being removed.
The configuration settings on the console (*Runtime Security > Defend > CNNS*) and the corresponding APIs for CNNS are removed in `v32.00.159`.
Radar has a container and a host view, where you can view the network topology for your containerized apps and hosts respectively, and this continues to be available.

[#deprecation-notices]
=== Deprecation Notices

//CWP-48467
==== Deprecated the `aggregated` and `rest` fields

The `aggregated` and `rest` macros from the webhook custom JSON alerts are being deprecated and replaced by `AggregatedAlerts` and `Dropped` macros respectively.

//CWP-40710
==== Deprecated `AccountID` macro from the Alerts payload

The `AccountID` macro in the Alerts payload is deprecated and replaced by the `AccountIDs` macro.
