
== DocumentDB is not encrypted at rest


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 08e1e43c-e9e3-40a2-8201-65147b3a9dfd

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/DocDBEncryption.py[CKV_AWS_74]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 



AWS DocumentDB clusters encryption at rest provides an additional layer of data protection by helping secure your data against unauthorized access to the underlying storage. On a cluster running with Amazon DocumentDB encryption, data stored at rest in the underlying storage is encrypted, as are its automated backups, snapshots, and replicas in the same cluster. We recommend enabling encryption at rest.

////
=== Fix - Runtime


Procedure



. Create an Amazon DocumentDB cluster.

. Under the Authentication section, choose Show advanced settings.

. Scroll down to the Encryption-at-rest section.

. Choose the option that you want for encryption at rest.
+
Whichever option you choose, you can't change it after the cluster is created.
+
To encrypt data at rest in this cluster, choose Enable encryption.


CLI Command




[source,go]
----
{
 "aws docdb create-db-cluster \\
      --db-cluster-identifier sample-cluster \\
      --port 27017 \\
      --engine docdb \\
      --master-username yourMasterUsername \\
      --master-user-password yourMasterPassword \\
      --storage-encrypted",
}
----

////

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_docdb_cluster
* *Arguments:* storage_encrypted - Specifies whether the DB cluster is encrypted.


[source,go]
----
resource "aws_docdb_cluster" "example" {
  ...
  cluster_identifier = "docdb-cluster-demo"
+ storage_encrypted  = true
  ...
}
----
