== Backup Vault is not encrypted at rest using KMS CMK


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ff405a6a-563e-41ba-995b-37769ea7fb8b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/BackupVaultEncrypted.py[CKV_AWS_166]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Encrypting your data and resources with KMS helps protect your data from unauthorized access or tampering.
By encrypting your data, you can ensure that only authorized users can access and decrypt the data, and that the data is protected while in storage or in transit.
Such action can help protect against external threats such as hackers or malware, as well as internal threats such as accidental or unauthorized access.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_backup_vault
* *Arguments:*  kms_key_arn


[source,go]
----
resource "aws_backup_vault" "backup_with_kms_key" {
    ...
  + kms_key_arn = aws_kms_key.example.arn
}
----


*CloudFormation* 


* *Resource:* AWS::Backup::BackupVault
* *Arguments:*  Properties.EncryptionKeyArn


[source,yaml]
----
Type: AWS::Backup::BackupVault
    Properties:
      ...
+     EncryptionKeyArn: example.arn/aws_kms_key
----
