== QLDB ledger permissions mode is not set to STANDARD


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| b1c558e0-ec7d-4c9f-8705-b1f3ec5e8ad0

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/QLDBLedgerPermissionsMode.py[CKV_AWS_170]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Amazon Quantum Ledger Database (Amazon QLDB) is a fully managed ledger database for cryptographically verifiable transaction logging.
You can use the QLDB API or the AWS Command Line Interface (AWS CLI) to create, update, and delete ledgers in Amazon QLDB.
You can also list all the ledgers in your account, or get information about a specific ledger.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_qldb_ledger
* *Arguments:*  permissions_mode


[source,go]
----
resource "aws_qldb_ledger" "standard" {
  ...
+ permissions_mode = "STANDARD"
}
----


*CloudFormation* 


* *Resource:* AWS::QLDB::Ledger
* *Arguments:*  Properties.PermissionsMode


[source,yaml]
----
Resources:
  Default:
    Type: "AWS::QLDB::Ledger"
    Properties:
      ...
+     PermissionsMode: "STANDARD"
----
