== AWS RDS cluster delete protection is disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e058fabb-cc5c-4c19-88ed-b5d599044a92

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/RDSDeletionProtection.py[CKV_AWS_139]

|Severity
|LOW

|Subtype
|Build
//Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Enabling deletion protection on Amazon Relational Database Service (RDS) clusters and instances can help to prevent accidental deletion.
When deletion protection is enabled, you cannot delete the RDS cluster or instance using the AWS Management Console, the AWS CLI, or the RDS API.
This can be helpful if you want to ensure that your RDS resources are not deleted accidentally, either by yourself or by someone else with access to your AWS account.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_rds_cluster
* *Arguments:* deletion_protection


[source,go]
----
resource "aws_rds_cluster" "default" {
  ...
+ deletion_protection = true
}
----
