== Amazon ElastiCache Redis clusters do not have automatic backup turned on


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 903c9178-b240-45a1-ae2c-59f998b44918

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/ElasticCacheAutomaticBackup.py[CKV_AWS_134]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Amazon ElastiCache clusters running Redis can back up their data.
Using automated backup, you can restore a cluster or seed a new cluster.
The backup consists of the cluster's metadata, along with all of the data in the cluster.
You can enable or disable automatic backups on an existing Redis cluster or replication group by modifying it using the ElastiCache console, the AWS CLI, or the ElastiCache API.
For any Redis cluster, you can enable automatic backups.
When automatic backups are enabled, ElastiCache creates a backup of the cluster on a daily basis.
There is no impact on the cluster and the change is immediate.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_elasticache_cluster
* *Arguments:* snapshot_retention_limit


[source,go]
----
resource "aws_elasticache_cluster" "example" {
  ...
+ snapshot_retention_limit = 5
}
----
