== Unencrypted ECR repositories


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 69480017-0ad0-4127-8b39-4bab0a463f84

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/ECRRepositoryEncrypted.py[CKV_AWS_136]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


Encrypting your ECR repositories helps protect your data from unauthorized access or tampering.
That way, you can ensure that only authorized users can access and modify the contents of your repositories.
Such action can help protect against external threats such as hackers or malware, as well as internal threats such as accidental or unauthorized access.

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_ecr_repository
* *Arguments:* encryption_configuration.encryption_type


[source,go]
----
resource "aws_ecr_repository" "example" {
  ...
  name                 = "bar"
+ encryption_configuration {
+   encryption_type = "KMS"
+ }
}
----


*CloudFormation* 


* *Resource:* AWS::ECR::Repository
* *Arguments:* Properties.EncryptionConfiguration.EncryptionType


[source,yaml]
----
Resources:
  KMSEncryption:
    Type: AWS::ECR::Repository
    Properties: 
      ...
+     EncryptionConfiguration:
+       EncryptionType: "KMS"
        ...
----
