== Not all data stored in the EBS snapshot is securely encrypted


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 1757fd25-6c31-4c7a-9899-8838150e108f

|Checkov ID 
|CKV_AWS_CUSTOM_3

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 


EBS snapshots must be encrypted, as they often include sensitive information, customer PII or CPNI.
Amazon EBS encryption uses AWS Key Management Service (AWS KMS) customer master keys (CMK) when creating encrypted volumes and snapshots.
With EBS encryption enabled, you no longer have to build, maintain, and secure your own key management infrastructure.

////
=== Fix - Runtime


* AWS Console* 


To change the policy using the AWS Console, follow these steps:

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the * https://console.aws.amazon.com/ec2/ [Amazon EC2 console]*.

. From the navigation bar, select * Region*.

. From the navigation pane, select * EC2 Dashboard*.

. In the upper-right corner of the page, click * Account Attributes*, then * EBS encryption*.

. click * Manage*.

. For Default encryption key, select a symmetric customer managed CMK.

. Click * Update EBS encryption*.


* CLI Command* 


To enable EBS encryption by default:


[source,shell]
----
{
 "aws ec2 enable-ebs-encryption-by-default",
}
----
----
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_ebs_snapshot
* *Arguments:* encrypted - Whether the snapshot is encrypted.

Example fix:


[source,go]
----
{
 "resource "aws_ebs_snapshot" "example" {
  volume_id = "${aws_ebs_volume.example.id}"
+ encrypted = true
  ...
}
}
----
