== Prisma Cloud Compute Console upgrade announcements

This section contains release notes and upgrade announcements for Compute Console in Prisma Cloud Enterprise Edition.
As we roll out upgrades, we will update this page with new announcements and information.
To prepare for upcoming upgrades, please carefully review the breaking changes highlighted for each release.

NOTE: In 2H2021 (second half of calendar year 2021 release) we are adding major changes to Defender - Console backward compatibility. Please refer to this doc for more details: https://docs.twistlock.com/docs/compute_edition/welcome/upcoming_support_lifecycle_changes.html 

=== Upgrade plan for 20.12 update 1

**Date of Upgrade:** Sunday, January 31, 2021

All Compute Consoles in Prisma Cloud Enterprise Edition are scheduled to be automatically upgraded on Sunday, January 31st between 12am - 5am PST. You may experience intermittent service interruptions during this time, due to the upgrade.

Please read through the important updates and breaking changes corresponding to the Prisma Cloud Compute 20.12 release.

**Some important links to review in preparation of the upgrade:**

* Upgrade considerations and breaking changes: https://docs.twistlock.com/docs/releases/release-information/release-notes-20-12.html#upgrade-considerations
* 20.12 API breaking changes and porting guide: https://docs.twistlock.com/docs/compute_edition/api/porting_guide.html#overview
* 20.12 Update 1 release notes: https://docs.twistlock.com/docs/releases/release-information/latest.html

=== Upgrade plan for 20.09 update 1

**Date of Upgrade:** Sunday, November 1, 2020

All Compute Consoles in Prisma Cloud Enterprise Edition are scheduled to be automatically upgraded on Sunday, November 1st between 12-3am PST. You may experience intermittent service interruptions during this time, due to the upgrade.

Release notes are available here: https://docs.twistlock.com/docs/releases/release-information/latest.html


=== Upgrade plan for 20.09

This section highlights the upgrade schedule and plan for the upcoming 20.09 Compute release. 

**Date of Upgrade:** Tuesday, Sept. 29, 2020

All Compute Consoles in Prisma Cloud Enterprise Edition are scheduled to be automatically upgraded on Tuesday, September 29th between 12-3am PST. You may experience intermittent service interruptions during this time, due to the upgrade.


==== Major features and changes to Compute Console in Prisma Cloud Enterprise Edition

Please read through the following important updates and changes corresponding to the Prisma Cloud Integration of 20.09 Compute release.

**1. CNNF Deprecation**

Cloud Native Network Firewall will be deprecated in this release in favor of the future Identity-Based Microsegmentation feature, which will be made available in the platform for networking policies. Hence, effective this release, the Compute CNNF feature will no longer be available in Prisma Cloud Enterprise Edition (Compute SaaS)

**2. Non-Onboarded Cloud Account Resources**

Read-Only users will now have the ability to view data in Compute from Defenders that are deployed on Hosts that are outside of onboarded Prisma Cloud accounts. This data will also be available for viewing in the Licensing tab.

NOTE: As the Prisma Cloud platform upgrade progresses across our various regions (starting September 23 till October 5), this checkbox in RBAC may be visible to certain customers sooner than others. However, it can only be used for Compute User Roles mapping after all regions are updated with that option and Compute Console is also fully upgraded across all stacks. 

**3. Cloud Account Credential Share**

We’ve added the ability to import onboarded Cloud Account credentials from Prisma Cloud into the Compute Console. Credentials can be surfaced and used for registry scanning, cloud discovery, and other third party integrations.  

NOTE: As part of this feature, Cloud Account permissions in Prisma Cloud CFT and TFT templates will include Compute permissions by default on October 7th. You can check out the new permissions added for Compute on this page, once the release is published , here - https://docs.twistlock.com/docs/enterprise_edition/authentication/credentials_store.html#using-onboarded-accounts

**4. Unified Licensing**

The Licensing tab will now display Credits (formerly known as Workloads) consumption across all resources, including Compute, in a single place with cloud account association. 

More Compute specific breaking changes and feature updates are available for viewing in our release notes page https://docs.paloaltonetworks.com/prisma/prisma-cloud/20-09/prisma-cloud-compute-edition-release-notes/release-information/release-notes-20-09[here].
