== NAT gateway IP addresses

Prisma Cloud tenant to Compute SaaS Console mappings.

NOTE: This document is for Compute Consoles within Prisma Cloud platform.
For information on Prisma Cloud tenants' URL and NAT gateways associated with them, see https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/get-started-with-prisma-cloud/nat-gateway-ip-address-whitelist-for-prisma-cloud[here].

Prisma Cloud Compute uses the following NAT gateway IP addresses and tenant/region mappings.
To ensure that you can access Prisma Cloud Compute and the APIs for any integrations that you enabled between Prisma Cloud and your incidence response workflows, or for your Prisma Cloud Defenders to communicate with the Prisma Cloud Compute Console, review the list and update the IP addresses in your allow lists.

NOTE: Depending on when the PCEE tenant and Compute SaaS Console was created, will determine which region the Console resides in. (You can always double check by going to **Compute > Manage > System > Downloads** and then look at the **Path to Console**)

In the URL bar of your browser after logging into Prisma Cloud, corresponding the "app" with the following table.
Or within the Compute Console, under **Manage > System > Downloads**, find the region in the URL for **Path to Console**.
Use that region to identify the destination IP address, which you must allow or add as trusted to access the Prisma Cloud Compute console.

[cols="14%,30%,30%,13%,13%", options="header"]
|===
|Prisma Cloud App Stack
|Prisma Cloud Tenant Region	(AWS)
|Compute SaaS Console Region (GCP)
|Console Egress Connections +
(Ex: From Defenders to Console)
|Console Ingress Connections +
(Ex: From Console into your environment for alerts)

|App
|us-east-1 (N. Virginia)
|us-east1 (South Carolina)
|34.75.54.101
|34.74.84.51

|App2
|us-east-2 (Ohio)
|us-east1 (South Carolina)
|34.75.54.101
|34.74.84.51

|App3
|us-west-2 (Oregon)
|us-west1 (Oregon)
|34.82.51.12
|104.198.109.73

|App4
|us-west-1 (N. California)
|us-west1 (Oregon)
|34.82.51.12
|104.198.109.73

|App5
|us-east-2 (Ohio)
|us-east1 (South Carolina)
|34.75.54.101
|34.74.84.51

|App.eu	
|eu-central-1 (Frankfurt)
|europe-west3 (Frankfurt, Germany)
|34.107.65.220
|34.107.91.105

|App2.eu
|eu-west-1 (Ireland)
|europe-west3 (Frankfurt, Germany)
|34.107.65.220
|34.107.91.105

|App.anz	
|ap-southeast-2 (Sydney)	
|asia-northeast1 (Tokya, Japan) +
OR +
australia-southeast1 (Sydney, Australia)
|35.194.113.255 +
OR +
35.244.121.190
|35.200.123.236 +
OR +
35.189.44.184

|App.gov
|us-gov-west-1 (AWS GovCloud US-West)
|us-west1 (Oregon)
|34.82.51.12
|104.198.109.73

|App.cn
|cn-northwest-1 (Ningxia)
|Compute SaaS not supported
| N/A
| N/A

|App.ca
|ca-central-1 (Canada - Central)
|northamerica-northeast1 (Montréal, Québec)
|35.203.59.190
|35.203.31.67

|App.sg
|ap-southeast-1 (Singapore)
|asia-southeast1 (Singapore)
|35.198.194.238
|34.87.137.141

|===


OR


App
[cols="14%,30%,30%,13%,13%", options="header"]
|===
|Prisma Cloud Tenant Region	(AWS)
|Compute SaaS Console Region (GCP)
|Console Egress Connections +
(Ex: From Defenders to Console)
|Console Ingress Connections +
(Ex: From Console into your environment for alerts)

|us-east-1 (N. Virginia)
|us-east1 (South Carolina)
|34.75.54.101
|34.74.84.51
|===

App2

App3

App4

App5

App.eu

App2.eu

App.anz

App.cn

App.ca

App.sg