== NAT gateway IP addresses

Prisma Cloud Compute uses the following NAT gateway IP addresses.
To ensure that you can access Prisma Cloud Compute and the APIs for any integrations that you enabled between Prisma Cloud and your incidence response workflows, or for your Prisma Cloud Defenders to communicate with the Prisma Cloud Compute Console, review the list and update the IP addresses in your allow lists.

NOTE: This document is for Compute Consoles within Prisma Cloud platform.
For information on Prisma Cloud tenants' URL and NAT gateways associated with them, see https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/get-started-with-prisma-cloud/nat-gateway-ip-address-whitelist-for-prisma-cloud[here].

On the Compute Console, under **Manage > System > Downloads**, find the region in the URL for **Path to Console**.
Use that region to identify the destination IP address, which you must allow or add as trusted to access the Prisma Cloud Compute console.

[cols="20%,40%,40%", options="header"]
|===
|Prisma Cloud Compute Console region
|Egress Connections (Ex: From Defenders to Console)
|Ingress Connections (Ex: From Console into your environment for alerts)

|us-east1
|34.75.54.101
|34.74.84.51

|us-west1
|34.82.51.12
|104.198.109.73

|asia-northeast1
|35.194.113.255
|35.200.123.236

|europe-west3
|34.107.65.220
|34.107.91.105

|northamerica-northeast1
|35.203.59.190
|35.203.31.67

|australia-southeast1
|35.244.121.190
|35.189.44.184

|asia-southeast1
|35.198.194.238
|34.87.137.141

|===

Prisma Cloud tenant to Compute SaaS Console mappings.

NOTE: Depending on when the PCEE tenant and Compute SaaS Console was created, will determine which region the Console resides in. (You can always double check by going to **Compute > Manage > System > Downloads** and then look at the **Path to Console**)

[cols="20%,40%,40%", options="header"]
|===
|Prisma Cloud Application Stack
|Prisma Cloud Tenant Region	
|Compute SaaS Console Region

|App
|us-east-1 (N. Virginia)
|us-east1 (South Carolina)

|App2
|us-east-2 (Ohio)
|us-east1 (South Carolina)

|App3
|us-west-2 (Oregon)
|us-west1 (Oregon)

|App4
|us-west-1 (N. California)
|us-west1 (Oregon)

|App5
|us-east-2 (Ohio)
|us-east1 (South Carolina)

|App.eu	
|eu-central-1 (Frankfurt)
|europe-west3 (Frankfurt, Germany)

|App2.eu
|eu-west-1 (Ireland)
|europe-west3 (Frankfurt, Germany)

|App.anz	
|ap-southeast-2 (Sydney)	
|asia-northeast1 (Tokya, Japan) +
OR +
australia-southeast1 (Sydney, Australia)

|App.gov
|us-gov-west-1 (AWS GovCloud US-West)
|us-west1 (Oregon)

|App.cn
|cn-northwest-1 (Ningxia)
|Compute SaaS not supported

|App.ca
|ca-central-1 (Canada - Central)
|northamerica-northeast1 (Montréal, Québec)

|App.sg
|ap-southeast-1 (Singapore)
|asia-southeast1 (Singapore)

|===