== Compute SaaS maintenance updates

This article contains maintenance updates and technical details surrounnding it for Compute Console in Prisma Cloud Enterprise Edition. 
To ensure you get notifications of such updates automatically in your email, please subscribe to our status page at: https://status.paloaltonetworks.com/

=== Upcoming Scheduled Maintenance
During scheduled maintenances, customers may experience intermittent failures across Compute services as they get updated.

**Date of Maintenance:** Sunday, May 2, 2021

**Time Window:** 12AM to 3AM PST

**Details:**
// GH fix: https://github.com/twistlock/twistlock/issues/29235

Fixing errors with AWS credentials in Compute Consoles regarding a failure to retrieve AWS functions/metadata. 


The issue is caused by the console using credentials that use the EC2 IAM role .
This type of credential queries the instance metadata service for the EC2 instance role when used and because Compute Consoles run in GCP, the credentials fail with error below -

EC2RoleRequestError: no EC2 instance role found

**Action Items:**
No specific action items to take except general upgrade process related tasks: https://docs.twistlock.com/docs/enterprise_edition/upgrade/upgrade_process_saas.html


**Date of Maintenance:** Sunday, November 8, 2020 

**Time Window:** 11PM to 5AM PST

**Details:**
// GH fix: https://github.com/twistlock/twistlock/issues/23159

Currently Compute Consoles have dynamic public ips associated with them for egress connections (access from Console into your environment).
Features such as Cloud Discovery that require Compute Console to connect to user's environment for API calls, need whitelisting of the Compute Console IP address in order for the scans to work.
With this maintenance, we will be migrating all Compute Consoles behind NAT gateways so that users can have static IP addresses to whitelist as documented here: xref:../welcome/nat_gateway_ip_addresses.adoc[NAT gateway IP addresses for Compute].

**Action Items:**

Please ensure you have whitelisted the new Compute Console IPs for Egress and Ingress connections. 
The **old IPs will be deleted after the migration**, hence failure to whitelist the new IPs can result in disconnects from Defenders / twistcli etc. 
