== Overview
This section contains maintenance updates and technical details surrounnding it for Compute Console in Prisma Cloud Enterprise Edition. 
To ensure you get notifications of such updates automatically in your email, please subscribe to our status page at: https://status.paloaltonetworks.com/

=== Upcoming Scheduled Maintenance
During scheduled maintenances, customers may experience intermittent failures across Compute services as they get updated.


**Date of Maintenance:** Sunday, October 25, 2020 

**Time Window:** 11PM to 5AM PST

**Details:**
// GH fix: https://github.com/twistlock/twistlock/issues/23159

Currently Compute Consoles have dynamic public ips associated with them for egress connections (access from Console into your environment).
Features such as Cloud Discovery that require Compute Console to connect to user's environment for API calls, need whitelisting of the Compute Console IP address in order for the scans to work.
With this maintenance, we will be migrating all Compute Consoles behind NAT gateways so that users can have static IP addresses to whitelist as documented here: xref:/admin_guide/welcome/nat_gateway_ip_addresses.adoc[NAT gateway IP addresses for Compute]

**Action Items:**

Please ensure you have whitelisted the new Compute Console IPs for Egress and Ingress connections. 
The **old IPs will be deleted after the migration**, hence failure to whitelist the new IPs can result in disconnects from Defenders / twistcli etc. 
