== Azure SQL Server threat detection alerts are not enabled for all threat types


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| cb84d42b-5935-4c37-a769-b2ec6c4c7995

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/SQLServerThreatDetectionTypes.py[CKV_AZURE_25]

|Severity
|HIGH

|Subtype
|Build
// ,Runtime
|Frameworks
|ARM,Terraform,Bicep,TerraformPlan

|=== 



=== Description 


Enabling all *Threat Detection Types* protects against SQL injection, database vulnerabilities, and any other anomalous activities.
We recommend you enable all types of threat detection on SQL servers.

////
=== Fix - Runtime


* Azure Portal To change the policy using the Azure Portal, follow these steps:* 



. Log in to the Azure Portal at https://portal.azure.com.

. Navigate to * SQL servers*.

. For each server instance:  a) Click * Advanced Data Security*.
+
b) Navigate to * Threat Detection Settings* section.
+
c) Set * Threat Detection Types * to* * All*.


* CLI Command* 


To set each server's * ExcludedDetectionTypes* to * None*, use the following command:
----
Set-AzureRmSqlServerThreatDetectionPolicy
-ResourceGroupName & lt;resource group name>
-ServerName & lt;server name>
-ExcludedDetectionType "None"
----
////
=== Fix - Buildtime


*ARM* 


* *Resource:* Microsoft.Sql/servers/databases


[source,json]
----
{
    "type": "Microsoft.Sql/servers/databases",
    "apiVersion": "2020-08-01-preview",
    "name": "[variables('dbName')]",
    "location": "[parameters('location')]",
    "sku": {
        "name": "[parameters('sku')]"
    },
    "kind": "v12.0,user",
    "properties": {
        "collation": "SQL_Latin1_General_CP1_CI_AS",
        "maxSizeBytes": "[mul(parameters('maxSizeMB'), 1048576)]",
        "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
        "zoneRedundant": false,
        "readScale": "Disabled",
        "storageAccountType": "GRS"
    },
    "resources": [
        {
            "type": "Microsoft.Sql/servers/databases/securityAlertPolicies",
            "apiVersion": "2014-04-01",
            "name": "[concat(variables('dbName'), '/current')]",
            "location": "[parameters('location')]",
            "dependsOn": [
                "[resourceId('Microsoft.Sql/servers/databases', parameters('serverName'), parameters('databaseName'))]"
            ],
            "properties": {
+               "state": "Enabled",
+               "disabledAlerts": "",
                "emailAddresses": "[variables('emailAddresses')[copyIndex()]]",
                "emailAccountAdmins": "Enabled"
            }
        }
    ]
}
----


*Terraform* 


* *Resource:* azurerm_mssql_server_security_alert_policy
* *Arguments:* disabled_alerts


[source,go]
----
resource "azurerm_mssql_server_security_alert_policy" "example" {
    ...
+   disabled_alerts = []
    }
----
