== Azure App Services FTP deployment is All allowed


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7fa164f0-fb0d-40a1-8293-8192f64eed81

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/AppServiceFTPSState.py[CKV_AZURE_78]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


FTPS (Secure FTP) is used to enhance security for Azure web application using App Service as it adds an extra layer of security to the FTP protocol, and help you to comply with the industry standards and regulations.
For enhanced security, it is highly advices to use FTP over TLS/SSL only.
You can also disable both FTP and FTPS if you don't use FTP deployment.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_app_service
* *Arguments:* ftps_state - (Optional) State of FTP / FTPS service for this App Service.

Possible values include: AllAllowed, FtpsOnly and Disabled.


[source,go]
----
{
 "resource "azurerm_app_service" "example" {
  ...
+ ftps_state = "FtpsOnly"
}

",
}
----
