== Azure Microsoft Defender for Cloud is set to Off for Storage
// Azure Microsoft Defender for Cloud disabled for Storage


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5436f3cc-3815-44f4-ac09-b8418e1f8e1d

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/AzureDefenderOnStorage.py[CKV_AZURE_84]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Azure Defender is a cloud workload protection service that utilizes and agent-based deployment to analyze signals from Azure network fabric and the service control plane, to detect threats across all Azure resources.
It can also analyze non-Azure resources, utilizing Azure Arc, including those on-premises and in both AWS and GCP (once they've been onboarded).
Azure Defender for Storage detects unusual and potentially harmful attempts to access or exploit storage accounts.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_security_center_subscription_pricing
* *Arguments:* resource_type - (Required) The resource type this setting affects.

Ensure that `StorageAccounts` is declared to pass this check.


[source,go]
----
resource "azurerm_security_center_subscription_pricing" "example" {
  tier          = "Standard"
  resource_type = "AppServices,ContainerRegistry,KeyVaults,KubernetesService,SqlServers,SqlServerVirtualMachines,StorageAccounts,VirtualMachines,ARM,DNS"
}
----
