== Azure App Services Remote debugging is enabled
// Azure App Services Remote debugging enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6fd5eaee-2e6d-419b-b380-2fa1a67feaf3

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/RemoteDebggingNotEnabled.py[CKV_AZURE_72]

|Severity
|LOW

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Remote debugging allows you to remotely connect to a running app and debug it from a different location.
While this can be useful for developers who need to troubleshoot issues with their app, it also introduces a potential security risk because it allows someone to remotely access your app and potentially modify its code or behavior.
If remote debugging is enabled for your app services, it could potentially be exploited by an attacker to gain unauthorized access to your app and potentially compromise it.
This could result in data loss, financial damage, or other negative consequences.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_app_service
* *Arguments:* remote_debugging_enabled


[source,go]
----
resource "azurerm_app_service" "example" {
                   ...
+                  remote_debugging_enabled = false
            }
----
