== Key vault does not enable soft-delete
// Key Vault does not enable soft-delete


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 01fb7eb5-26d1-4cfa-8c8e-eae7d5fa5683

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/KeyVaultEnablesSoftDelete.py[CKV_AZURE_111]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Deleting a key vault without soft delete enabled permanently deletes all secrets, keys, and certificates stored in the key vault.
Accidental deletion of a key vault can lead to permanent data loss.
Soft delete allows you to recover an accidentally deleted key vault for a configurable retention period.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_key_vault
* *Arguments:* soft_delete_retention_days - (Optional) The number of days that items should be retained for once soft-deleted.

This value can be between 7 and 90 (the default) days.


[source,go]
----
resource "azurerm_key_vault" "example" {
  ...
+   soft_delete_retention_days  = 7
}
----
