== Azure data factories are not encrypted with a customer-managed key


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 76436a36-e177-400f-8a7b-9d116f4d9340

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/azure/AzureDataFactoriesEncryptedWithCustomerManagedKey.yaml[CKV2_AZURE_15]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Use customer-managed keys to manage the encryption at rest of your Azure Data Factory.
By default, customer data is encrypted with service-managed keys, but customer-managed keys are commonly required to meet regulatory compliance standards.
Customer-managed keys enable the data to be encrypted with an Azure Key Vault key created and owned by you.
You have full control and responsibility for the key lifecycle, including rotation and management.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_data_factory, azurerm_data_factory_linked_service_key_vault
* *Arguments:* data_factory_name (of _azurerm_data_factory_linked_service_key_vault_ )


[source,go]
----
resource "azurerm_data_factory" "data_factory_good" {
  name                = "example"
  location            = "location"
  resource_group_name = "group"
}

resource "azurerm_data_factory_linked_service_key_vault" "factory_good" {
  name                = "example"
  resource_group_name = "example"
  data_factory_name   = azurerm_data_factory.data_factory_good.name
  key_vault_id        = "123456"
}
----
