== Azure Storage Accounts Without Proper Replication
// Ensure that Storage Accounts use replication.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4434ebc4-9580-410d-9409-9cbedc070e7e

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/StorageAccountsUseReplication.py[CKV_AZURE_206]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Storage Account provides scalable and secure storage for a wide range of data solutions. A key feature of the Storage Account service is its ability to replicate data, ensuring data durability and availability. Replication copies your data, either within the same data center, to a second data center, or across regions, providing protection against unexpected hardware failures, datacenter outages, or even large-scale events like natural disasters.

The following replication types are recommended for ensuring high durability and availability of data:
- GRS (Geo-Redundant Storage): Cross-regional replication to protect against regional unavailability.
- RAGRS (Read-Access Geo-Redundant Storage): Similar to GRS, but also provides read-only access to the data in the secondary location.
- GZRS (Geo-Zone-Redundant Storage): Combines the high availability provided by replication across availability zones with protection from regional outages.
- RAGZRS (Read-Access Geo-Zone-Redundant Storage): Provides read-only access to the data in the secondary location, and combines the advantages of GZRS.

This policy ensures that Azure Storage Accounts are configured to use one of the recommended replication methods, safeguarding your data against local and regional disruptions.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_storage_account

*Arguments:* 
- account_replication_type

[source,terraform]
----
resource "azurerm_storage_account" "example" {
  name                     = "examplestoracc"
  # ... other configurations ...

+ account_replication_type = "GRS"  # Or use RAGRS, GZRS, or RAGZRS as per your requirement.

  # ... other configurations ...
}
----
