== Virtual machine scale sets do not have encryption at host enabled
// Virtual Machine scale sets 'encryption at host' disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| eb556c1a-e906-4172-a30f-8c342fc7e4c3

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/azure/VMEncryptionAtHostEnabled.py[CKV_AZURE_97]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Use encryption at host to get end-to-end encryption for your virtual machine and virtual machine scale set data.
Encryption at host enables encryption at rest for your temporary disk and OS/data disk caches.
Temporary and ephemeral OS disks are encrypted with platform-managed keys when encryption at host is enabled.
OS/data disk caches are encrypted at rest with either customer-managed or platform-managed key, depending on the encryption type selected on the disk.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_windows_virtual_machine_scale_set
* *Arguments:* encryption_at_host_enabled


[source,go]
----
resource "azurerm_windows_virtual_machine_scale_set" "example" {
                  ...
  +               encryption_at_host_enabled = true
                  ...
                  }
----
