== Geo-Replicated Not Enabled for Azure Container Registry (ACR)
// Ensure geo-replicated container registries to match multi-region container deployments.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 57fd8398-2883-4bbb-bfa2-37e6d949ac10

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/main/checkov/terraform/checks/resource/azure/ACRGeoreplicated.py[CKV_AZURE_165]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Geo-replication is an important feature for container registries that operate in a multi-region context. It allows for container images and artifacts to be available closer to where they are run, reducing latency and increasing reliability.

This policy ensures that if you're using a Premium SKU for your Azure Container Registry, geo-replication is enabled.

=== Fix - Buildtime

*Terraform*

* *Resource:* azurerm_container_registry
* *Arguments:* sku, georeplications

[source,terraform]
----
resource "azurerm_container_registry" "example" {
  name                     = "exampleContainerRegistry"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
+ sku                      = "Premium"
  admin_enabled            = false
  
+ georeplications {
+    location                = "East US"
+    zone_redundancy_enabled = true
+    tags                    = {}
+ }
}
----