== Azure CDN Doesn't Disable HTTP Endpoint
// Ensure the Azure CDN disables the HTTP endpoint.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0e1e8786-06c7-4ff0-978d-a33593afcb6a

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/CDNDisableHttpEndpoints.py[CKV_AZURE_197]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Terraform, Terraform Plan

|=== 

*Description*

Azure Content Delivery Network (CDN) allows for the caching and acceleration of web traffic. It's essential to secure the CDN endpoints to ensure that your content is not tampered with while in transit.

Enabling only HTTPS traffic ensures encrypted transmission, reducing the chances of a Man-in-the-Middle (MitM) attack or data being sent in clear text.

This policy checks that Azure CDN endpoints have disabled the HTTP endpoint, ensuring all connections are made over HTTPS.


=== Fix - Buildtime

*Terraform*

*Resource:* 
- azurerm_cdn_endpoint

*Arguments:* 
- is_http_allowed

[source,terraform]
----
resource "azurerm_cdn_endpoint" "example" {
  name                = "example-cdn-endpoint"
  # ... other configurations ...

+ is_http_allowed = false

  # ... other configurations ...
}
----

