== Storage Accounts without Secure transfer enabled
// Azure Storage Accounts without Secure transfer enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| bc4e467f-10fa-471e-aa9b-28981dc73e93

|Checkov ID 
| https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/azure/StorageAccountsTransportEncryption.py[CKV_AZURE_3]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform, TerraformPlan

|=== 



=== Description 


The secure transfer option enhances the security of a storage account by only allowing requests to the storage account by a secure connection.
For example, when calling REST APIs to access storage accounts, the connection must use HTTPS.
Any requests using HTTP will be rejected when 'secure transfer required' is enabled.
When using the Azure files service, connection without encryption will fail, including scenarios using SMB 2.1, SMB 3.0 without encryption, and some flavors of the Linux SMB client.
Because Azure storage doesn't support HTTPS for custom domain names, this option is not applied when using a custom domain name.

=== Fix - Buildtime


*Terraform* 


* *Resource:* azurerm_storage_account
* *Arguments:*  enable_https_traffic_only


[source,go]
----
resource "azurerm_storage_account" "example" {
              ...
           +  enable_https_traffic_only = true
            }
----

