== Shopify Private App Token


=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
|TBD

|Checkov Check ID
|CKV_SECRET_97

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|===



=== Description

A Shopify Private App Token, also known as API password, is used for making authenticated requests to the Shopify API on behalf of a private app. Private apps are created for specific stores and give you access to Shopify's powerful e-commerce APIs, allowing you to add custom functionality to your store. The Private App Token should be kept secure as it grants significant access to your store's data.


=== Fix - Buildtime


*Shopify*

To revoke a Private App Token, you need to delete the private app. Here's how:

1. From your Shopify admin, go to 'Apps'.
2. Click on 'Manage private apps' at the bottom of the page.
3. Click on the name of the private app you want to delete.
4. Scroll down and click on 'Delete app'.
5. A dialog box will appear for confirmation. Click on 'Delete'.
+
When you delete the private app, the associated API password (token) is revoked and any services depending on this app will stop working. Be careful, before you proceed as you cannot undo the action.
