== Heroku Platform Key


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ab6c1821-7b25-43d6-9ff0-ba300479c1ac

|Checkov ID 
|CKV_SECRET_48

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


Heroku is a cloud platform as a service (PaaS) supporting several programming languages.
The Heroku network runs the customer's apps in virtual containers which execute on a reliable runtime environment.
Heroku calls these containers "Dynos".
These Dynos can run code written in Node, Ruby, PHP, Go, Scala, Python, Java, or Clojure.
Heroku also provides custom buildpacks with which the developer can deploy apps in any other language.
Heroku lets the developer scale the app instantly just by either increasing the number of dynos or by changing the type of dyno the app runs in.

=== Fix - Buildtime


*Heroku* 



.  Revoke the Key

. In Heroku, click on Account Settings

. Click on API Key

. Find the compromised key and click on Revoke

.  Monitor for abuse
