
== Look Ahead—Planned Updates on Prisma Cloud

Review any deprecation notices and policy changes planned in the next Prisma Cloud Code Security release.

Read this section to learn about what is planned in the upcoming release. The Look Ahead announcements are for an upcoming or next release and it is not a cumulative list of all announcements.

NOTE: The details and functionality listed below are a preview and the actual release date is subject to change.

* <<new-policies>>

[#new-policies]
=== New Policies and Policy Updates

Learn about the new policies and upcoming policy changes for new and existing Prisma Cloud System policies.


[cols="50%a,50%a"]
|===
|POLICY UPDATES
|DESCRIPTION

|*Terraform Cloud Run Tasks*
// Issue ID due from Dganit/Taylor
|For Terraform Cloud Run Tasks, the Enforcement Settings for IaC Scans are currently enforced only when you have enabled the checkbox to *Make Prisma Cloud's run tasks mandatory*.
*Make Prisma Cloud's run tasks mandatory* is being removed, to make this behavior consistent with other VCS, IDE, and CI/CD pipeline integrations for Code Security.

Impact: If you have an existing Terraform Cloud Run Task integration on Prisma Cloud that was previously not set to mandatory, and have set the Enforcement Settings threshold for Hard Fail to anything other than *Off* such as Low or above for IaC Scan, the run tasks will now be mandatory. Builds that were passing earlier will now fail when there is a violation above the severity threshold detected in your IaC files.

|*CVE Severity*
// RLP-87265
|Currently CVEs with severity of Moderate and Important are mapped as Low severity.
In the next release in January 2023, CVEs with Moderate severity will be mapped as Medium and Important will be mapped as High severity.

Impact: With this change, if you have set the Enforcement Settings threshold to Medium or above for detecting violations or failing the build for CVEs in your source code, the volume of violations will be higher than before.

Any VCS or CI/CD integrations where the hard fail is implemented for CVEs that are Medium or above in severity, the builds that were passing earlier will now fail.


|*GitHub VCS Integration*

|To help ensure that your GitHub organization and repository and GitLab repository configurations are using proper branch protection and build integrity guidelines, Prisma Cloud is adding Build Integrity policies in the upcoming release. These permissions are required to pull organization and repository configurations and scan them for Supply Chain policy violations.
The following additional read-only permissions are being requested:

* administration: read-only
* actions: read-only
* repository_hooks: read-only
* organization_hooks: read-only

Impact: If you opt to reject or ignore the request for the additional permissions, there will be no impact on existing scans; however, you will not be able to detect violations of the build integrity policies.

|===
