== Containers wishing to share host IPC namespace admitted
// Containers allowed to share host IPC namespace

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 02c6acab-8581-41b5-922c-91ba79eb0f01

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/kubernetes/ShareHostIPCPSP.py[CKV_K8S_3]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


The host IPC namespace controls whether a pod's containers can be shared.
You can administer cluster-level restrictions to ensure that containers remain isolated using *PodSecurityPolicy* and ensuring *hostIPC* is set to *False*.
Preventing sharing of host *PID/IPC* namespace, networking, and ports ensures proper isolation between Docker containers and the underlying host.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* PodSecurityPolicy
* *Arguments:* hostIPC  Determines if the policy allows the use of HostIPC in the pod spec.


[source,yaml]
----
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: <policy name>
spec:
+ hostIPC: false
----


To use a **PodSecurityPolicy** resource, the requesting user or target pod's service account must be authorized to use the policy.
The preferred method is to grant access to the service account.

In the following example we use **RBAC**, a standard Kubernetes authorization mode.

A *Role* or *ClusterRole* must grant access to *use* the desired policies.

*Kind*: ClusterRole


[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <role name>
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - <policy name>
----

The **ClusterRole **is then bound to the authorized service(s):

*Kind*: ClusterRoleBinding


[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <binding name>
roleRef:
  kind: ClusterRole
  name: <role name>
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: <authorized service account name>
  namespace: <authorized pod namespace>
----
