== Seccomp is not set to Docker/Default or Runtime/Default


=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID 
| fd6729ef-efdb-4fff-9afa-dc005f192ea5

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/Seccomp.py[CKV_K8S_31]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Helm, Kustomize

|===



=== Description


Secure computing mode (seccomp) is a Linux kernel feature used to restrict actions available within the container.
The seccomp() system call operates on the seccomp state of the calling process.
The default seccomp profile provides a reliable setting for running containers with seccomp and disables non-essential system calls.

=== Fix - Buildtime


*Kubernetes*


* *Resource:* Pod / Deployment / DaemonSet / StatefulSet / ReplicaSet / ReplicationController / Job / CronJob
* *Arguments:* securityContext: seccompProfile: type: (Optional: Kubernetes > v1.19)  Addition of seccompProfile type: RuntimeDefault or DockerDefault


[source,pod]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
  containers:
  - name: <container name>
    image: <image>
  securityContext:
+    seccompProfile:
+      type: RuntimeDefault
       or
+      type: DockerDefault
----


[source,cronjob]
----
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <name>
spec:
  schedule: <>
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
+            seccompProfile:
+              type: RuntimeDefault
               or
+              type: DockerDefault
----

[source,text]
----
apiVersion: <>
kind: <kind>
metadata:
  name: <name>
spec:
  template:
    spec:
      securityContext:
+        seccompProfile:
+          type: RuntimeDefault
           or
+          type: DockerDefault
----