== Containers share host IPC namespace


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 10cf6234-c41e-409f-bbcb-536327f091b9

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/kubernetes/ShareHostIPC.py[CKV_K8S_18]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


Pods share many resources, so it could make sense to share a process namespace.
Some container images may expect to be isolated from other containers.
Not sharing IPC namespaces  helps ensure isolation.
Containers in different pods have distinct IP addresses and will need special configuration to communicate by IPC.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Pod / Deployment / DaemonSet / StatefulSet / ReplicaSet / ReplicationController / Job / CronJob
* *Arguments:* hostIPC (Optional)  If true, the Pod uses the host's IPC namespace.
Default to false.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
+ hostIPC: false # or do not include hostIPC
----


[source,cronjob]
----
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <name>
spec:
  schedule: <>
  jobTemplate:
    spec:
      template:
        spec:
+          hostIPC: false # or do not include hostIPC
----

[source,text]
----
apiVersion: <>
kind: <kind>
metadata:
  name: <name>
spec:
  template:
    spec:
+       hostIPC: false # or do not include hostIPC
----
