== Containers run with AllowPrivilegeEscalation
// Containers run with 'AllowPrivilegeEscalation' Pod Security Policy
//Suggest: Containers allow a process to can gain more privileges than its parent process 

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 3aa8f043-3853-4c9e-ae3a-8d3a70d69d4b

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/AllowPrivilegeEscalation.py[CKV_K8S_20]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


The *AllowPrivilegeEscalation* Pod Security Policy controls whether or not a user is allowed to set the security context of a container to *True*.
Setting it to *False* ensures that no child process of a container can gain more privileges than its parent.
We recommend you to set *AllowPrivilegeEscalation* to *False*, to ensure *RunAsUser* commands cannot bypass their existing sets of permissions.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Container
* *Arguments:* allowPrivilegeEscalation (Optional) If false, the pod can not request to allow privilege escalation.
Default to true.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <Pod name>
spec:
  containers:
  - name: <container name>
    image: <image>
    securityContext:
+      allowPrivilegeEscalation: false
----

