== Liveness probe is not configured
// Liveness probe not configured

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0ac8c8e1-3382-43da-90bb-9d4b5b54a624

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/LivenessProbe.py[CKV_K8S_8]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


The kubelet uses liveness probes to know when to schedule restarts for containers.
Restarting a container in a deadlock state can help to make the application more available, despite bugs.
If a container is unresponsive, either to a deadlocked application or a multi-threading defect, restarting the container can make the application more available, despite the defect.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Container
* *Field:* livenessProbe (Optional)  The probe describes a health check to be performed against a container to determine whether it is alive or not.
Its arguments may include: exec, failureThreshold, httpGet, initialDelaySeconds, periodSeconds, successThreshold, tcpSocket and timeoutSeconds.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
  containers:
  - name: <container name>
    image: <image>
+   livenessProbe:
      <Probe arguments>
----
