== OpenAPI If the security scheme is not of type 'oauth2', the array value must be empty
 


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| d9145ac2-c2bf-416b-97c6-a05ec8668827

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/openapi/checks/resource/v2/Oauth2SecurityRequirement.py[CKV_OPENAPI_2]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|OpenAPI

|=== 



=== Description 


Restrict the security section of OpenAPI documents to only include OAuth 2.0 authorization schemes defined in the security definitions section to prevent unauthorized access to the API. This is achieved by ensuring that only OAuth 2.0 schemes defined in the security section have a value.

=== Fix - Buildtime

Restrict the security section of OpenAPI documents to only include OAuth 2.0 authorization schemes, add the following code to your Terraform file during buildtime. 


*OpenAPI* 


Ensure that your generated OpenAPI document does not include a security section for authentication types that are not OAuth 2.0.
Below is an example:

[source,yaml]
----
securityDefinitions:
some_auth:
type: basic
- security:
-  - some_auth:
-      - write: some
-      - read: some
----
