[#deploy-defender]
== Deploy Prisma Cloud Defenders

To take advantage of the agent-based security features of Prisma Cloud, you must deploy the Defender agent.

You can deploy single Defenders for containers, hosts, and serverless functions or deploy Defenders on entire clusters using an orchestrator.
There are several xref:./defender-types.adoc[Defender types] based on the assets they protect and how you wish to deploy them.

=== Defender capabilities

The following table summarizes the key functional differences between Defender types.

[cols="3,2,1,1,1,1", frame="topbot"]
|====
2+^|Capabilities 4+^|Defender type

2+|
|Container^1^
|Host
|Serverless
|App-Embedded

.3+|*Deployment methods*
|*Console UI*
|Y
|Y
|Y
|Y

|*API*
|Y
|Y
|Y
|Y

|*twistcli*
|Y
|
|
|Y

|*Vulnerability management*
|
|Y
|Y
|Y^2^
|Y^3^

|*Compliance*
|
|Y
|Y
|Y^2^
|Y^4^

.5+|*Runtime defense*
|*Behavioral modeling*
|Y
|
|
|

|*Process*
|Y
|Y
|Y
|Y

|*Networking*
|Y
|Y
|Y
|Y

|*File system*
|Y
|Y
|Y
|Y

|*Forensics*
|Y
|Y
|
|Y

.2+|*Access control*
|*Kubernetes auditing*
|Y^5^
|
|
|Y^5^

|*Admission control*
|Y
|
|
|

.2+|*Firewalls*
|*WAAS*
|Y
|Y
|Y
|Y

|*CNNS*
|Y
|Y
|
|

.1+|*Radar (visualization)*
|*Radar*
|Y
|Y
|Y
|

|====

^1^
Container Defender supports all Host Defender capabilities.
You can deploy single container and host Defenders or deploy container and host Defenders using an xref:./kubernetes/kubernetes.adoc[orchestrator].

^2^
Normally Defender scans workloads for vulnerabilities and compliance issues.
For serverless functions, Console does the scanning.
In the Console, create a configuration that points to your repository of functions in your cloud provider.

^3^
Vulnerability management for deployed images only.
Registry scanning by app-embedded Defenders is not supported.

^4^
Image compliance and custom compliance checks only.
The trusted images feature isn't supported.

^5^
Kubernetes auditing is done by the Console, and not by the Defenders.
In the Console, enable Kubernetes auditing and create a configuration that points to your cluster.

=== Connectivity

Defender must be able to communicate with Prisma Cloud over the network because it pulls policies down and sends data (alerts, events, etc) back to the Prisma Cloud console.

If you are using a certificate authority through a proxy, add the `--proxy-cacert` flag to the curl command https://curl.se/docs/manpage.html#--proxy-cacert[as described in the curl documentation].
