== GCP Kubernetes Engine Clusters have Network policy disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 6ddbfdfe-3936-43d0-8157-97a7899beae6

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/GKENetworkPolicyEnabled.py[CKV_GCP_12]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Defining a network policy helps ensure that a compromised front-end service in your application cannot communicate directly with an external interface, for example, a billing or an accounting service several levels down.
Network policy rules can ensure that Pods and Services in a given namespace cannot access other Pods or Services in a different namespace.
We recommend you enable Network Policy on kubernetes engine clusters to determine which Pods and Services can access one another inside your cluster.
This ensures only the required services are communicating and no explicitly indicated traffic is able to reach private clusters.

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "google_container_cluster" "pass" {
  name = "google_cluster"
  network_policy {
    enabled = true
  }
}
----

