== Connect Cloud Accounts

Prisma Cloud provides comprehensive security and compliance coverage to secure your cloud accounts and comply with various industry standards. With a simplified onboarding experience you can adapt to your organization's security priorities in a streamlined manner with the security capabilities grouped as *Foundational* and *Advanced* (with a few enabled by default). Use the *Foundational* capabilities during the start of your organization's cloud adoption journey to effectively manage assets in the cloud and on-premises. Use the *Advanced* capabilities to proactively control your cloud operations and identify and remediate issues before they manifest within your runtime environments.

To get the most out of your investment in Prisma Cloud and to begin monitoring the resources on your cloud infrastructure, you must first connect your public cloud accounts to Prisma Cloud. The onboarding process requires that you have the correct permissions on Prisma Cloud and your cloud accounts to authenticate and authorize the connection and retrieval of data. Prisma Cloud administrators with the System Administrator and Cloud Provisioning Administrator roles can use the cloud account onboarding process for a good first-run experience with the supported cloud platforms—Alibaba Cloud, Amazon Web Services, Microsoft Azure, Google Cloud Platform, and Oracle Cloud Infrastructure. 

* xref:onboard-aws/onboard-aws.adoc[Onboard Your Amazon Web Services Account]
* xref:onboard-your-azure-account/onboard-your-azure-account.adoc[Onboard Your Microsoft Azure Account]
* xref:onboard-gcp/onboard-gcp.adoc[Onboard Your Google Cloud Platform Account]
* xref:onboard-your-oci-account/onboard-your-oci-account.adoc[Onboard Your Oracle Cloud Infrastructure Account]
* xref:onboard-your-alibaba-account/onboard-your-alibaba-account.adoc[Onboard Your Alibaba Cloud Account]