== Readiness probe is not configured


=== Policy Details 

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID 
| b5b36b9a-68f5-4825-9d1b-bcd3dcea2141

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/ReadinessProbe.py[CKV_K8S_9]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|===



=== Description


Readiness Probe is a Kubernetes capability that enables teams to make their applications more reliable and robust.
This probe regulates under what circumstances the pod should be taken out of the list of service endpoints so that it no longer responds to requests.
In defined circumstances the probe can remove the pod from the list of available service endpoints.
Using the Readiness Probe ensures teams define what actions need to be taken to prevent failure and ensure recovery in case of unexpected errors.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/[Kubernetes.io Documentation]

=== Fix - Buildtime


*Kubernetes*

*Resource*: Container
*Field:* readinessProbe (Optional)

The probe describes a health check to be performed against a container to determine whether it is ready for traffic or not.
Its configurations may include: exec, failureThreshold, httpGet, initialDelaySeconds, periodSeconds, successThreshold, tcpSocket and timeoutSeconds.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
  containers:
  - name: <container name>
    image: <image>
+   readinessProbe:
      <Probe configurations>
----
