== Memory limits are not set
// Memory limits not set

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 267d86e3-7066-4e25-822d-57680e66dcb7

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/kubernetes/MemoryRequests.py[CKV_K8S_13]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


The scheduler uses resource request information for containers in a pod to decide which node to place the pod on.
The kubelet enforces the resource limits set, so that the running container is not allowed to use more resource than the limit set.
If a process in the container tries to consume more than the allowed amount of memory, the system kernel terminates the process that attempted the allocation, with an out of memory (OOM) error.
With no limit set, kubectl allocates more and more memory to the container until it runs out.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:* Container
* *Arguments:* resources:limits:memory (Optional)

Defines the memory limit for the container.


[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
  containers:
  - name: <container name>
    image: <image>
    resources:
      limits:
+       memory: <memory limit>
----
