== The --profiling argument for controller managers is not set to False
// '-profiling' argument for controller managers not set to False

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7a042645-57fd-45ed-a17e-fed49c8333e9

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/KubeControllerManagerBlockProfiles.py[CKV_K8S_107]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Kubernetes,Helm,Kustomize

|=== 



=== Description 


Disable profiling, if not needed.
Profiling allows for the identification of specific performance bottlenecks.
It generates a significant amount of program data that could potentially be exploited to uncover system and program details.
If you are not experiencing any bottlenecks and do not need the profiler for troubleshooting purposes, it is recommended to turn it off to reduce the potential attack surface.

=== Fix - Buildtime


*Kubernetes* 


* *Kind:* Pod


[source,yaml]
----
{
 "  apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    labels:
      component: kube-controller-manager
      tier: control-plane
    name: kube-controller-manager
    namespace: kube-system
  spec:
    containers:
    - command:
      - kube-controller-manager
+     -  --profiling=false
      image: gcr.io/google_containers/kube-controller-manager-amd64:v1.6.0",
}
----

