== The --rotate-certificates argument is set to false
// '--rotate-certificates' argument set to False

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 82c6e27a-d022-4cd7-a277-49945c706c14

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/KubletRotateCertificates.py[CKV_K8S_149]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Kubernetes,Helm,Kustomize

|=== 



=== Description 


Enable kubelet client certificate rotation.
The --rotate-certificates setting causes the kubelet to rotate its client certificates by creating new CSRs as its existing credentials expire.
This automated periodic rotation ensures that the there is no downtime due to expired certificates and thus addressing availability in the CIA security triad.

NOTE: This recommendation only applies if you let kubelets get their certificates from the API server. In case your kubelet certificates come from an outside authority/tool (e.g.Vault) then you need to take care of rotation yourself.


=== Fix - Buildtime


*Kubernetes *Kind* Pod* 




[source,yaml]
----
{
 "apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
 +  - kubelet
 +  - --rotate-certificates=true
    image: gcr.io/google_containers/kube-scheduler-amd64:v1.6.0
    ...",
}
----

