== The --use-service-account-credentials argument for controller managers is not set to True
// '--use-service-account-credentials' argument for controller managers not set to True

=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| e74ba43b-4375-4df3-93c1-f9b5858d9b8d

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/kubernetes/checks/resource/k8s/KubeControllerManagerServiceAccountCredentials.py[CKV_K8S_108]

|Severity
|HIGH

|Subtype
|Build

|Frameworks
|Kubernetes,Helm,Kustomize

|=== 



=== Description 


Use individual service account credentials for each controller.
The controller manager creates a service account per controller in the kube-system namespace, generates a credential for it, and builds a dedicated API client with that service account credential for each controller loop to use.
Setting the --use-service-account- credentials to true runs each control loop within the controller manager using a separate service account credential.
When used in combination with RBAC, this ensures that the control loops run with the minimum permissions required to perform their intended tasks.

=== Fix - Buildtime


*Kubernetes* 


* *Kind:* Pod


[source,yaml]
----
{
 "  apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    labels:
      component: kube-controller-manager
      tier: control-plane
    name: kube-controller-manager
    namespace: kube-system
  spec:
    containers:
    - command:
      - kube-controller-manager
+     -  --use-service-account-credentials=true
      image: gcr.io/google_containers/kube-controller-manager-amd64:v1.6.0",
}
----

