== securityContext is not applied to pods and containers
// securityContext not applied to pods and containers


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9cc81c69-dc64-48fc-ad1f-d9c07ff85051

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/kubernetes/PodSecurityContext.py[CKV_K8S_29]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Kubernetes, Terraform, Helm, Kustomize

|=== 



=== Description 


*securityContext* defines privilege and access control settings for your pod or container, and holds security configurations that will be applied to a container.
Some fields are present in both *securityContext* and *PodSecurityContext*,  when both are set, *securityContext* takes precedence.
Well-defined privilege and access control settings will enhance assurance that your pod is running with the properties it requires to function.

=== Fix - Buildtime


*Kubernetes* 


* *Resource:*  Container / Pod / Deployment / DaemonSet / StatefulSet / ReplicaSet / ReplicationController / Job / CronJob
* *Arguments:* securityContext (Optional)  A field that defines privilege and access control settings for your Pod or Container.


[source,container]
----
apiVersion: v1
kind: Pod
metadata:
  name: <Pod name>
spec:
  containers:
  - name: <container name>
    image: <image>
+   securityContext:
----

[source,pod]
----
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
+  securityContext:
----

[source,cronjob]
----
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <name>
spec:
  schedule: <>
  jobTemplate:
    spec:
      template:
        spec:
+          securityContext:
----

[source,text]
----
apiVersion: <>
kind: <kind>
metadata:
  name: <name>
spec:
  template:
    spec:
+       securityContext:
----