== Asset Query Attributes

Learn about Asset query attributes.

Review your options when using userinput:[asset where]. Each attribute allows you to narrow your search criteria. As you use these attributes, the auto-suggestion feature shows the available expressions and the operators that are applicable for each attribute.

*  userinput:[asset.name] 
+
Use the userinput:[asset.name] attribute to view asset details on the *Investigate* tab.
+
For example, you can <details>.
+
screen:[example]


*  userinput:[asset.class] 
+
Use the userinput:[asset.class] attribute to view .
+
For example, you can <details>.
+
screen:[example]


*  userinput:[asset.type] 
+
Use the userinput:[asset.type] attribute to view .
+
For example, you can <details>.
+
screen:[example]


*  userinput:[asset.category] 
+
Use the userinput:[asset.category] attribute to view .
+
For example, you can <details>.
+
screen:[example]


*  userinput:[asset.service] 
+
Use the userinput:[asset.service] attribute to view .
+
For example, you can <details>.
+
screen:[example]



//- cloud.type
//- cloud.region
//- cloud.service
//- cloud.account
//- cloud.accountgroup