== `+oam+` command

The `+oam+` command holds operations, administration, and maintenance tools.

=== `+ping+` subcommand

The `+ping+` command is used for network connectivity troubleshooting. Running the command will cause the specified processing unit to initiate a flow towards the specified destination IP and port. A successful ping will return the status code `+0+` and write a report to `+stdout+`. Otherwise, the status code will be `+1+` and errors will be written to `+stderr+`. The report will contain information about the source and destination. The operation of the command and report will differ depending on whether the destination is a processing unit or not.

If the destination is not a processing unit then the destination must be listening on the specified port for a successful response. The connection will be set up and then immediately dropped. The report will include detailed information about the source but only the IP and port of the destination.

If the destination is a processing unit then the destination enforcer will handle the flow. Hence it is not necessary for the destination to be actively listening to the destination port. Even if it is listening on the port the enforcer will consume the flow. The report will include detailed information about both the source and destination.

Examples:

 Consider the situation where there are two processing units and the admin suspects that there may be a network device within the path that is blocking traffic on port 9000. The admin knows that SSH (port 22) is working so they run the command
 
  ```apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:22```
  
 The command is successful so they run the command
  
 ```apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:9000```
  
 The command fails. Now the admin knows the problem is with the network.
 
 apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:900
 apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:900 --verbose
