== `+oam+` command

The `+oam+` command holds operations, administration, and maintenance tools.

=== `+ping+` subcommand

Use the `+ping+` command to troubleshoot network connectivity. The command starts a flow from the specified processing unit to the destination IP and port. A successful ping returns the status code `+0+`, and writes a report to `+stdout+`. An unsuccessful ping returns the status code `+1+`, and writes a report the errors to `+stderr+`. The reports contain information about the source and destination. How the command and reports operate depends on whether the destination is a processing unit.

A destination that is not a processing unit must listen to the specified port for a successful response. The connection is immediately set up and then dropped. The report includes detailed information about the source, but only the IP and port of such a destination.

If the destination is a processing unit then the destination enforcer will handle the flow. Hence it is not necessary for the destination to be actively listening to the destination port. Even if it is listening on the port the enforcer will consume the flow. The report will include detailed information about both the source and destination.

Examples:

 Consider the situation where there are two processing units and the admin suspects that there may be a network device within the path that is blocking traffic on port 9000. The admin knows that SSH (port 22) is working so they run the command
 
  ```apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:22```
  
 The command is successful so they run the command
  
 ```apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:9000```
  
 The command fails. Now the admin knows the problem is with the network.
 
 apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:900
 apoctl oam ping 5ee5a29939483e4c01a20d7b 192.168.100.101:900 --verbose
