== `+profiles+` command

The `+profiles+` command is used to manage multiple `+apoctl+` profiles.
Without additional commands, it will print the list of available profiles,
and which one is currently used.

Example:

 $ apoctl profiles
 CURRENT   NAME      API                               NAMESPACE            APPCRED
 >         saas      https://api.console.aporeto.com   /jean                true
 *         internal  https://api.aporeto.acme.com      /michel (appcred)    true

You can switch the current profile by using `+apoctl profile use [profile name]+`.

The symbols in the `+CURRENT+` column means the following:

* `+*+`: default profile to use when nothing else is configured
* `+>+`: the profile currently in use if `+APOCTL_CONFIG_NAME+` is set

=== `+set+` subcommand

The `+set+` subcommand is used to switch the current profile.
You can also use the alias `+use+`.

Example:

 $ apoctl profiles use preprod
 current profile set to preprod

You can switch the current profile by using `+apoctl profile use [profile name]+`.

The current profile will be overridden in the following cases:

* you have defined `+APOCTL_CONFIG_NAME+`
* you have passed the flag `+--config+`
