
== Server-Side Request Forgery (SSRF)

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5612303b-cb42-492d-a710-fd44b8f4856b

|Checkov ID 
|CKV3_SAST_145

|Severity
|HIGH

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/918.html[CWE-918: Server-Side Request Forgery (SSRF)]

|OWASP Categories
|https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/[A10:2021 - Server-Side Request Forgery (SSRF)]

|=== 

=== Description

This SAST policy detects potential Server-Side Request Forgery (SSRF) vulnerabilities in Java code. SSRF exploits backend systems that initiate requests to third parties. If user input is used in constructing or sending these requests, an attacker could supply malicious data to force the request to other systems or modify request data to cause unwanted actions. 

Vulnerable code example:

[source,java]
----
String url = request.getParameter("url");
new URL(url);
----

The above code is vulnerable because it directly uses user input (retrieved from the "url" parameter) in constructing the URL object. An attacker could maliciously supply a different URL, potentially targeting internal or restricted systems.

=== Fix - Buildtime

To fix this issue, it is important to ensure that user input is properly validated and sanitized before using it to construct URLs or URIs for making requests to third-party systems. 

Secure code example:

[source,java]
----
String url = request.getParameter("url");
String validatedUrl = validateAndSanitizeUrl(url);
new URL(validatedUrl);
----

In the secure code example, the user input is first passed through a validateAndSanitizeUrl() method, which applies appropriate validation and sanitization techniques to ensure the URL is safe before constructing the URL object. This helps prevent any malicious or unauthorized access to sensitive systems.
    