
== Inadequate encryption strength

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| dd068fb3-4674-4c51-987d-d4618d7f4013

|Checkov ID 
|CKV3_SAST_131

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/326.html[CWE-326: Inadequate Encryption Strength]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects when an application enables insecure TLS protocol versions. The recommended TLS protocol versions that should be allowed are TLSv1.2, TLSv1.3, DTLSv1.2, and DTLSv1.3. Older versions such as TLSv1.0 should be disallowed to mitigate potential security risks.

Vulnerable code example:

[source,java]
----
SSLContext context = SSLContext.getInstance("TLSv1.0");
context.createSSLEngine().setEnabledProtocols(new String[]{"TLSv1.0"});
----

The above code example is vulnerable because it enables the insecure TLSv1.0 protocol version.

=== Fix - Buildtime

To fix the issue, the code should be updated to enforce TLS 1.2 as the minimum protocol version and disallow older versions. 

Secure code example:

[source,java]
----
SSLContext context = SSLContext.getInstance("TLSv1.2");
context.createSSLEngine().setEnabledProtocols(new String[]{"TLSv1.2", "TLSv1.3", "DTLSv1.2", "DTLSv1.3"});
----

The above code example is no longer vulnerable as it enforces TLS 1.2 as the minimum protocol version and allows only secure versions (TLSv1.2, TLSv1.3, DTLSv1.2, DTLSv1.3).
    