
== Use of a broken or risky cryptographic algorithm

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 579db273-3999-4a29-97d1-be68c618620e

|Checkov ID 
|CKV3_SAST_148

|Severity
|HIGH

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects the use of a broken or risky cryptographic algorithm in Java code. The use of these algorithms can introduce vulnerabilities that could be exploited by attackers to tamper with ciphertext and compromise the security of the system.

Vulnerable code example:

[source,java]
----
Cipher.getInstance("DES");
----

The above code example uses the "DES" cryptographic algorithm, which is considered weak and vulnerable to attack. It does not provide built-in message integrity, making it easier for an adversary to tamper with the ciphertext and potentially decrypt the data.

=== Fix - Buildtime

To address this issue, you should use a more secure cryptographic algorithm that has built-in message integrity. For example, "ChaCha20Poly1305" or "AES-256-GCM" are recommended algorithms.

Secure code example:

[source,java]
----
Cipher.getInstance("ChaCha20Poly1305");
----

The above code example demonstrates the use of the "ChaCha20Poly1305" algorithm, which provides both encryption and message integrity. By using this algorithm, the ciphertext is protected against tampering, ensuring the security of the encrypted data.
    