
== Sensitive Cookie in HTTPS Session Without 'Secure' Attribute

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| b1b7b5b2-d4ea-4370-88f1-8a8b5de74b5b

|Checkov ID 
|CKV3_SAST_142

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/614.html[CWE-614: Sensitive Cookie in HTTPS Session Without 'Secure' Attribute]

|OWASP Categories
|https://owasp.org/Top10/A05_2021-Security_Misconfiguration/[A05:2021 - Security Misconfiguration]

|=== 

=== Description

This SAST policy detects the use of a sensitive cookie in an HTTPS session without the 'Secure' attribute set. This vulnerability can allow an attacker to intercept the sensitive information stored in the cookie if the connection is not secure.

Vulnerable code example:

[source,java]
----
Cookie userCookie = new Cookie("username", "admin");
response.addCookie(userCookie);
----

In the above code, a sensitive cookie called "username" is created without setting the 'Secure' attribute. This means that the cookie can be transmitted over an insecure connection, making it vulnerable to interception by an attacker.

=== Fix - Buildtime

To fix this issue, the 'Secure' attribute should be set when creating the cookie.

Secure code example:

[source,java]
----
Cookie userCookie = new Cookie("username", "admin");
userCookie.setSecure(true);
response.addCookie(userCookie);
----

In the secure code example, the 'Secure' attribute is set to true using the `setSecure(true)` method before adding the cookie to the response. This ensures that the cookie will only be transmitted over a secure connection.

By setting the 'Secure' attribute, the sensitive cookie can only be transmitted over HTTPS, making it more secure and protecting the sensitive information from interception by attackers.
    