
== Improper certificate validation

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ff0d9327-c3c3-4eea-a01e-85ab4d0b837e

|Checkov ID 
|CKV3_SAST_111

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/295.html[CWE:295 - Improper Certificate Validation]

|OWASP Categories
|https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/[A07:2021 - Identification and Authentication Failures]

|=== 

=== Description

The SAST policy detects improper certificate validation in Java code. This occurs when the `HostnameVerifier` is overridden to always return `true` or when the `X509TrustManager` is configured to return `null`, effectively disabling the validation of server or client certificates.

Vulnerable code example:

[source,java]
----
class MyHostnameVerifier implements HostnameVerifier {
  // Other methods
  public boolean verify(String hostname, SSLSession session) {
    return true;
  }
  // Other methods
}
----

The above code is vulnerable because it overrides the `verify` method of the `HostnameVerifier` interface and always returns `true`. This means that any hostname would be considered valid, bypassing certificate validation.

=== Fix - Buildtime

To fix this issue, you should not override the default `HostnameVerifier`. Use the default implementation or provide a custom implementation that performs proper certificate validation.

Secure code example:

[source,java]
----
// Use the default implementation
HostnameVerifier verifier = HttpsURLConnection.getDefaultHostnameVerifier();
----

The above code is no longer vulnerable because it uses the default `HostnameVerifier` implementation, which performs proper certificate validation. By using the default implementation, the code ensures that the server's identity is verified against the certificate provided.

Note: The fix may vary depending on the specific use case and requirements, but the key point is to ensure proper certificate validation is performed.
    