
== Cross-Site Request Forgery (CSRF)

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 212f075a-5c17-46a6-a094-9c24a06cc66c

|Checkov ID 
|CKV3_SAST_104

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/352.html[CWE:352 - Cross-Site Request Forgery (CSRF)]

|OWASP Categories
|https://owasp.org/Top10/A01_2021-Broken_Access_Control/[A01:2021 - Broken Access Control]

|=== 

=== Description

This SAST policy detects instances where Cross-Site Request Forgery (CSRF) protections are disabled or cookies are set with the SameSite attribute to values other than "Strict". These configurations can expose apps to attacks.

Vulnerable code example:

[source,java]
----
CSRF.disable();
----

The above code is vulnerable because it disables CSRF protections, allowing potential CSRF attacks to occur.

=== Fix - Buildtime

To fix the issue, you need to enable CSRF protections and set the SameSite attribute of cookies to "Strict".

Secure code example:

[source,java]
----
http.csrf().csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse().withSameSite(CookieSameSite.STRICT));
----

The above code is no longer vulnerable because it enables CSRF protections and sets the SameSite attribute of cookies to "Strict", preventing potential CSRF attacks.
    