
== URL Redirection to Untrusted Site ('Open Redirect')

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4e134365-0ef9-46f3-a9d4-24ced1413339

|Checkov ID 
|CKV3_SAST_147

|Severity
|HIGH

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/601.html[CWE-601: URL Redirection to Untrusted Site ('Open Redirect')]

|OWASP Categories
|https://owasp.org/Top10/A01_2021-Broken_Access_Control/[A01:2021 - Broken Access Control]

|=== 

=== Description

This SAST policy detects the URL Redirection to Untrusted Site vulnerability. This vulnerability occurs when an application redirects a user to a destination URL that is specified by a user-supplied parameter that is not properly validated. This can be exploited by attackers to perform phishing attacks.

Vulnerable code example:

[source,java]
----
String redirectUrl = request.getParameter("url");
response.sendRedirect(redirectUrl);
----

In the above code example, the application retrieves the value of the "url" parameter from the user's request and directly uses it as the destination URL for redirection. This can allow an attacker to craft a malicious URL and redirect the user to an untrusted site.

=== Fix - Buildtime

To fix this issue, it is important to validate and sanitize any user-supplied URL parameters before using them for redirection. 

Secure code example:

[source,java]
----
String redirectUrl = request.getParameter("url");
if (isValidUrl(redirectUrl)) {
    response.sendRedirect(redirectUrl);
} else {
    // Handle invalid URL error
}
----

In the secure code example, the application first checks if the user-supplied URL is valid using a custom validation function (isValidUrl). Only if the URL passes the validation, it is then used for redirection. This ensures that only trusted URLs are used for redirection and prevents attackers from manipulating the URL parameter to redirect users to untrusted sites.
    