== CSRF is Disabled

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| d3118387-d460-4806-82b6-0559a8fe2545

|Checkov ID 
|CKV3_SAST_25

|Severity
|MEDIUM

|Subtype
|Build

|Language
|Java

|CWEs
|https://cwe.mitre.org/data/definitions/352.html[CWE-352: Cross-Site Request Forgery (CSRF)]

|OWASP Categories
|https://owasp.org/Top10/A01_2021-Broken_Access_Control/[A01:2021 - Broken Access Control]

|=== 

=== Description

This policy aims to prevent the disabling of Cross-Site Request Forgery (CSRF) protection in web applications. CSRF is an attack that tricks the victim into submitting a malicious request. Since web browsers automatically include cookies, the actions can be authenticated and sensitive if CSRF protection is disabled.

Example of violating code:

[source,java]
----
import org.springframework.security.config.annotation.web.builders.HttpSecurity;

public class SecurityConfig {
    public void configure(HttpSecurity http) throws Exception {
        http.csrf().disable();
        // OR
        http.csrf().ignoringAntMatchers("/api/*");
    }
}
----

This code is problematic because it disables CSRF protection entirely or for specific URL patterns, leaving the application vulnerable to CSRF attacks.

=== Fix - Buildtime

To fix this violation, CSRF protection should not be disabled. If you have specific endpoints that require disabling CSRF, it's crucial to understand the risks involved and consider other forms of protection.

Example of revised code:

[source,java]
----
import org.springframework.security.config.annotation.web.builders.HttpSecurity;

public class SecurityConfig {
    public void configure(HttpSecurity http) throws Exception {
        http.csrf().enable();
    }
}
----

In this revised code, CSRF protection is enabled for all endpoints, making it more difficult for attackers to exploit the vulnerability.
