
== Utilizing a class that isn't primitive in Java RMI could lead to a vulnerability associated with insecure deserialization.

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 9c7bd352-b20c-450f-a946-81fe42edd0ee

|Checkov ID 
|CKV3_SAST_125

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/502.html[CWE-502: Deserialization of Untrusted Data]

|OWASP Categories
|https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/[A08:2021 - Software and Data Integrity Failures]

|=== 

=== Description

This policy detects instances in Java Remote Method Invocation (RMI) code where a non-primitive class is used as a parameter, which can lead to a vulnerability associated with insecure deserialization.

Vulnerable code example:

[source,java]
----
public interface MyInterface extends Remote {
    void myMethod(MyClass param) throws RemoteException;
}
----

The above code is vulnerable because it utilizes a non-primitive class (MyClass) as a parameter in the RMI method. This can introduce a security risk as deserialization of untrusted data can be exploited.

=== Fix - Buildtime

To fix the issue, you should avoid using non-primitive classes as parameters in RMI methods. Instead, consider using primitive data types or validated and trusted classes.

Secure code example:

[source,java]
----
public interface MyInterface extends Remote {
    void myMethod(int param) throws RemoteException;
}
----

The above code is no longer vulnerable as it uses the primitive data type int as the parameter in the RMI method. This eliminates the risk of insecure deserialization.
    