
== Incorrect permission assignment for critical resource

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| d4449e9a-21f7-4d61-9ce9-9ebc41822f06

|Checkov ID 
|CKV3_SAST_134

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/732.html[CWE-732: Incorrect Permission Assignment for Critical Resource]

|OWASP Categories
|

|=== 

=== Description

This SAST policy detects instances where the application sets file permissions to overly permissive values, which can lead to security vulnerabilities. 

Vulnerable code example:

[source,java]
----
PosixFilePermissions.fromString("rwxrwxrwx");
Files.setPosixFilePermissions(file, perms);
----

In the above code, the file permissions are set to "rwxrwxrwx", which allows read, write, and execute access for all users. This is overly permissive and can potentially allow unauthorized access to the file.

=== Fix - Buildtime

To fix this issue, the file permissions should be set to more restrictive values. 

Secure code example:

[source,java]
----
PosixFilePermissions.fromString("rw-------");
Files.setPosixFilePermissions(file, perms);
----

In the secure code example, the file permissions are set to "rw-------", which allows read and write access only for the application user. This ensures that only the application user has access to the file, reducing the risk of unauthorized access.
    