
== Improper certificate validation

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2025e1ef-4b0d-44a2-b7fc-ee9c7d776f1e

|Checkov ID 
|CKV3_SAST_110

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/295.html[CWE-295: Improper Certificate Validation]

|OWASP Categories
|https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/[A07:2021 - Identification and Authentication Failures]

|=== 

=== Description

This policy detects the use of the "DefaultHttpClient" class from the "org.apache.http.impl.client" package and the "SSLContext.getInstance" method with specific insecure protocols in Java code. These insecure methods do not properly validate SSL/TLS certificates, leaving the application vulnerable to data interception or malicious transmission.

Vulnerable code example:

[source,java]
----
DefaultHttpClient client = new DefaultHttpClient();
----

The above code is vulnerable because it uses the deprecated "DefaultHttpClient" class, which does not perform proper certificate validation, potentially allowing for Man-in-the-Middle attacks or data interception.

=== Fix - Buildtime

To fix this issue, you should avoid using the deprecated "DefaultHttpClient" class and instead opt for the "java.net.http.HttpClient" class introduced in Java 9, which provides automatic TLS validation for secure connections.

Secure code example:

[source,java]
----
HttpClient client = HttpClient.newBuilder().build();
----

The above code is no longer vulnerable because it uses the modern "HttpClient" class, which performs automatic TLS validation, ensuring secure connections.
    