
== Unencrypted payload with JWT

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| a9f4cb36-1f70-4ac9-a6aa-498ce2c59f40

|Checkov ID 
|CKV3_SAST_151

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This SAST policy detects the usage of unencrypted payloads with JSON Web Tokens (JWTs). 

Vulnerable code example:

[source,java]
----
com.auth0.jwt.algorithms.Algorithm.none()
----
                
The above code is vulnerable because it uses the `com.auth0.jwt.algorithms.Algorithm.none()` method to create a JWT algorithm that does not encrypt the payload. This means that the contents of the token can be easily read and manipulated by attackers.

=== Fix - Buildtime

To fix this issue, the payload of the JWT should be encrypted using a secure cryptographic algorithm.

Secure code example:

[source,java]
----
com.auth0.jwt.algorithms.Algorithm.HMAC256("your-secret")
----
                
The above code is no longer vulnerable because it uses the `HMAC256` algorithm to encrypt the JWT payload with a secure secret key. This ensures that the payload is protected and cannot be easily tampered with by attackers.
    