
== Improper Handling of Unicode Encoding

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5be19861-94a7-423a-8053-4e5463f05cce

|Checkov ID 
|CKV3_SAST_114

|Severity
|HIGH

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/176.html[CWE-176: Improper Handling of Unicode Encoding]

|OWASP Categories
|

|=== 

=== Description

This policy detects the improper handling of Unicode encoding in Java code. This vulnerability can occur when the input containing Unicode encoding is not properly handled, leading to potential security vulnerabilities.

Vulnerable code example:

[source,java]
----
args[$0].toLowerCase();
----

In the above code, the input value from the "args" array is converted to lowercase without properly handling Unicode encoding. This can lead to security vulnerabilities such as Unicode-based homograph attacks or bypassing input validation.

=== Fix - Buildtime

To fix this issue, you should use appropriate methods to handle Unicode encoding. In this case, you can use the `java.text.Normalizer.normalize()` method to ensure proper handling of Unicode characters.

Secure code example:

[source,java]
----
Normalizer.normalize(args[$0], Normalizer.Form.NFKC).toLowerCase();
----

In the secure code example, the `Normalizer.normalize()` method is used to normalize the input string and convert it to lowercase. This ensures proper handling of Unicode encoding and reduces the risk of security vulnerabilities.

By using the `Normalizer.normalize()` method with the appropriate normalization form, the code mitigates the risk of Unicode-based attacks and ensures the proper handling of Unicode characters in the input.
    