
== Information exposure through an error message

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 110bb667-2ba9-4bc3-a7a6-5299d73a40f9

|Checkov ID 
|CKV3_SAST_137

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/209.html[CWE-209: Generation of Error Message Containing Sensitive Information]

|OWASP Categories
|https://owasp.org/Top10/A04_2021-Insecure_Design/[A04:2021 - Insecure Design]

|=== 

=== Description

This policy detects instances where an application prints stack trace information to the default system output. Printing stack trace data to the default system output can expose sensitive information to potential attackers.

Vulnerable code example:

[source,java]
----
try {
  // Some code
}
catch(Exception e) {
  // Some code
  e.printStackTrace();
  // Some code
}
----

In the above code, the exception stack trace is printed to the console using the `printStackTrace()` method. This can reveal sensitive information about the application's internal workings and potentially aid attackers in exploiting vulnerabilities.

=== Fix - Buildtime

To fix this issue, it is recommended to log the stack trace information using a secure logging framework. This ensures that sensitive information is not leaked to the default system output.

Secure code example:

[source,java]
----
try {
  // Some code
}
catch(Exception e) {
  // Some code
  logger.error("An error occurred", e);  // Logging the error with a secure logging framework
  // Some code
}
----

In the secure code example, the stack trace is logged using a secure logging framework (represented by `logger`). This ensures that sensitive information is stored securely in the log files and not exposed to the default system output.
    