
== Deserialization of untrusted data

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4abf3efc-186d-4ae7-a32e-23487eee7649

|Checkov ID 
|CKV3_SAST_105

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/502.html[CWE-502: Deserialization of Untrusted Data]

|OWASP Categories
|https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/[A08:2021 - Software and Data Integrity Failures]

|=== 

=== Description

This SAST policy detects the vulnerability of deserialization of untrusted data in Java code. This vulnerability can be exploited by malicious actors to inject code or manipulate data. The policy recommends using JSON for serialization, specifying allowed deserialization objects, and avoiding base types.

Vulnerable code example:

[source,java]
----
XMLDecoder decoder = new XMLDecoder(inputStream);
Object obj = decoder.readObject();
----

The above code is vulnerable because it uses an XMLDecoder to deserialize data from an inputStream. This allows for the possibility of deserializing malicious or untrusted data, leading to code injection or data manipulation.

=== Fix - Buildtime

To fix the issue, it is recommended to use JSON for serialization instead of XML. JSON provides a safer and more secure way of transferring and deserializing data. Additionally, it is important to specify and validate the allowed deserialization objects to prevent arbitrary code execution.

Secure code example:

[source,java]
----
JsonDecoder decoder = new JsonDecoder(inputStream, AllowedClass.class);
AllowedClass obj = decoder.readObject();
----

The above code is no longer vulnerable because it uses a JsonDecoder, which is a safer alternative to XMLDecoder for deserializing data. The code also specifies the allowed deserialization class (AllowedClass), ensuring that only trusted objects are deserialized.
    