
== External Control of System or Configuration Setting

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 2dbd84ea-38c7-4c26-95fd-87bc3ac2fc70

|Checkov ID 
|CKV3_SAST_107

|Severity
|HIGH

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/15.html[CWE:15 - External Control of System or Configuration Setting]

|OWASP Categories
|https://owasp.org/Top10/A05_2021-Security_Misconfiguration/[A05:2021 - Security Misconfiguration]

|=== 

=== Description

This policy detects potential vulnerabilities where external inputs, such as request parameters or headers, are used to control system or configuration settings. This can lead to security misconfigurations and allow attackers to manipulate the system behavior.

Vulnerable code example:

[source,java]
----
String[] values = req.getParameterValues("input");
String arg = args[0];
String header = req.getHeader("header");
----
In the above code, the values of the `input` parameter, the first element of the `args` array, and the value of the `header` HTTP header are directly used without any validation or sanitization. This can allow an attacker to control these values and potentially manipulate the system or configuration settings.

=== Fix - Buildtime

To fix this issue, you should always validate and sanitize any input received from request parameters or headers before using them to control system or configuration settings.

Secure code example:

[source,java]
----
String[] values = req.getParameterValues("input");
String arg = validateAndSanitize(args[0]);
String header = validateAndSanitize(req.getHeader("header"));

public String validateAndSanitize(String value) {
    // Implement validation and sanitization logic here
    // ...
    return validatedAndSanitizedValue;
}
----
In the above fixed code, the `validateAndSanitize` method is used to validate and sanitize the input values before using them. This helps prevent any potential security misconfigurations and ensures that only safe and trusted values are used to control system or configuration settings.
    