
== Collapse of data into unsafe value

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ae2d0b52-3a63-4c44-bc75-d899129c6317

|Checkov ID 
|CKV3_SAST_103

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/20.html[CWE:20 - Improper Input Validation]

|OWASP Categories
|https://owasp.org/Top10/A03_2021-Injection/[A03:2021 - Injection]

|=== 

=== Description

This policy detects the use of the replace, replaceAll, and replaceFirst methods in Java without proper input validation, which can lead to code injection vulnerabilities.

Vulnerable code example:

[source,java]
----
String input = request.getParameter("input");
String unsafeValue = "Hello, World!".replaceAll("World", input);
----

In the above code, the input parameter is directly passed into the replaceAll method without any validation or sanitization. An attacker can potentially manipulate the input value to execute malicious code and perform code injection attacks.

=== Fix - Buildtime

To fix this issue, you should properly validate and sanitize the input before using replace or its variants. One way to do this is to use input validation techniques such as input whitelisting or input encoding.

Secure code example:

[source,java]
----
String input = request.getParameter("input");
String sanitizedInput = sanitizeInput(input);
String safeValue = "Hello, World!".replaceAll("World", sanitizedInput);
----

In the above code, the input parameter is first sanitized using a sanitizeInput() function. This function ensures that any potentially harmful characters are removed or properly encoded. The sanitized input is then used in the replaceAll method, ensuring that only safe values are manipulated.

By validating and sanitizing the input, we prevent the possibility of code injection attacks by ensuring that only valid and safe values are processed.
    