== Cookie created without HttpOnly flag


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 513cd937-b96d-40f8-aa4b-f4cb1573e5a7

|Checkov ID 
|CKV3_SAST_16

|Severity
|LOW

|Subtype
|Build

|Language
|Java

|CWEs
|https://cwe.mitre.org/data/definitions/1004.html[CWE-1004: Sensitive Cookie Without 'HttpOnly' Flag]

|OWASP Categories
|https://owasp.org/Top10/A05_2021-Security_Misconfiguration[A05:2021 - Security Misconfiguration]

|=== 



=== Description


This policy is targeting the creation of HTTP cookies without the "HttpOnly" flag in Java code. The HttpOnly flag is an important security feature that prevents client-side scripts from reading the contents of the cookie. When this flag is not set, it could potentially lead to disclosure of the cookie's contents in the event of a Cross-Site Scripting (XSS) attack.

Here's an example of violating code:

[source,java]
----
import javax.servlet.http.Cookie;

public class CookieHandler {
    public void createCookie(String name, String value) {
        Cookie cookie = new Cookie(name, value);
        // Other code
    }
}
----

In this example, a new cookie is created with a provided name and value, but the HttpOnly flag is not set.

=== Fix - Buildtime

The fix for this would be to call the `setHttpOnly` method on the cookie object with `true` as the argument, like so:

[source,java]
----
import javax.servlet.http.Cookie;

public class CookieHandler {
    public void createCookie(String name, String value) {
        Cookie cookie = new Cookie(name, value);
        cookie.setHttpOnly(true);
        // Other code
    }
}
----

This updated code sets the HttpOnly flag on the cookie, preventing it from being accessed by client-side scripts.

