
== Sensitive cookie without 'HttpOnly' flag

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| ac4a1353-274f-4add-a0ba-84148a5a0f50

|Checkov ID 
|CKV3_SAST_144

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/1004.html[CWE-1004: Sensitive Cookie Without 'HttpOnly' Flag]

|OWASP Categories
|https://owasp.org/Top10/A05_2021-Security_Misconfiguration/[A05:2021 - Security Misconfiguration]

|=== 

=== Description

This policy detects sensitive cookies that are created without the 'HttpOnly' flag set. When the 'HttpOnly' flag is set to true, it prevents client-side JavaScript from accessing the cookie value. This provides protection against cross-site scripting (XSS) attacks, as malicious scripts will not be able to read the cookie values.

Vulnerable code example:

[source,java]
----
Cookie sessionCookie = new Cookie("session", "12345");
----

In the above code, a cookie named "session" is created without setting the 'HttpOnly' flag to true. This makes it vulnerable to XSS attacks, as client-side scripts can access the value of this cookie using `document.cookie`.

=== Fix - Buildtime

To fix this issue, set the 'HttpOnly' flag of the cookie to true. 

Secure code example:

[source,java]
----
Cookie sessionCookie = new Cookie("session", "12345");
sessionCookie.setHttpOnly(true);
----

In the secure version of the code, the 'HttpOnly' flag of the cookie is set to true using the `setHttpOnly(true)` method. This ensures that the cookie value cannot be accessed by client-side JavaScript, providing protection against XSS attacks.
    