
== Use of a broken or risky cryptographic algorithm (SHA1/MD5)

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 7cf1e887-03d8-4c5a-bc8f-400c3b23be6c

|Checkov ID 
|CKV3_SAST_149

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/327.html[CWE-327: Use of a Broken or Risky Cryptographic Algorithm]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects the use of insecure or risky cryptographic algorithms, specifically MD5 and SHA1. Both MD5 and SHA1 hash algorithms have been found to be vulnerable to producing collisions, meaning that two different values can lead to the same hash value. The use of these algorithms weakens the security of the application.

Vulnerable code example:

[source,java]
----
MessageDigest.getInstance("SHA1")
----

The above code is vulnerable because it uses the SHA1 algorithm, which is considered insecure and risk-prone due to its vulnerability to collisions.

=== Fix - Buildtime

To fix the issue, you should use a secure cryptographic algorithm instead. For example:

Secure code example:

[source,java]
----
MessageDigest.getInstance("SHA-256")
----

The above code is no longer vulnerable because it uses the more secure SHA-256 algorithm instead of SHA1. SHA-256 is not vulnerable to collision attacks and offers better security.
    