
== Sensitive Cookie in HTTPS Session Without 'Secure' Attribute

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8508558d-371b-4b47-b7b1-12376fd7c81e

|Checkov ID 
|CKV3_SAST_143

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/614.html[CWE-614: Sensitive Cookie in HTTPS Session Without 'Secure' Attribute]

|OWASP Categories
|https://owasp.org/Top10/A05_2021-Security_Misconfiguration/[A05:2021 - Security Misconfiguration]

|=== 

=== Description

This policy detects the presence of a sensitive cookie in an HTTPS session that does not have the 'Secure' attribute set. Storing sensitive data in a persistent cookie without the 'Secure' attribute can lead to a breach of confidentiality or account compromise.

Vulnerable code example:

[source,java]
----
Cookie cookie = new Cookie("sessionId", sessionId);
cookie.setMaxAge(3600);
response.addCookie(cookie);
----

The above code is vulnerable because it creates a cookie named "sessionId" and sets its max age to 3600 seconds, but it does not set the 'Secure' attribute. Without the 'Secure' attribute, the cookie can be sent over an insecure HTTP connection, potentially exposing sensitive data.

=== Fix - Buildtime

To fix the issue, the 'Secure' attribute should be set when creating the cookie. This ensures that the cookie will only be sent over secure HTTPS connections.

Secure code example:

[source,java]
----
Cookie cookie = new Cookie("sessionId", sessionId);
cookie.setMaxAge(3600);
cookie.setSecure(true);
response.addCookie(cookie);
----

The above code is no longer vulnerable because it sets the 'Secure' attribute to true when creating the cookie. This ensures that the cookie will only be sent over secure HTTPS connections, mitigating the risk of data exposure.
    