
== Inadequate encryption strength

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| b9e3a78b-f81c-40c2-99c8-6e26d6568af2

|Checkov ID 
|CKV3_SAST_132

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/326.html[CWE-326: Inadequate Encryption Strength]

|OWASP Categories
|https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[A02:2021 - Cryptographic Failures]

|=== 

=== Description

This policy detects instances where the network communications for Hazelcast is configured to use a deprecated symmetric cipher, leading to inadequate encryption strength.

Vulnerable code example:

[source,java]
----
NC.setSymmetricEncryptionConfig(SEC);
----

The code above sets the symmetric encryption configuration for the network communications in Hazelcast. However, it uses a deprecated symmetric cipher, which is considered to have inadequate encryption strength.

=== Fix - Buildtime

To fix the issue, you should consider using TLS/SSL when establishing communications across the Hazelcast cluster, instead of the deprecated symmetric cipher.

Secure code example:

[source,java]
----
NC.setSSLConfig(SSL);
----

By setting the SSL configuration (using TLS/SSL) for the network communications in Hazelcast, you ensure a stronger and more secure encryption mechanism. This eliminates the use of the deprecated symmetric cipher and improves the encryption strength.
    