
== Use of externally-controlled format string

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 5908a865-c88e-4405-aaf4-6fd85decfab3

|Checkov ID 
|CKV3_SAST_150

|Severity
|HIGH

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/134.html[CWE-134: Use of Externally-Controlled Format String]

|OWASP Categories
|

|=== 

=== Description

This policy detects the use of externally-controlled format strings in Java code. An externally-controlled format string is a format string that is provided by a user or from an external source. Manipulating format string parameters can potentially cause exceptions or data leaks based on the application's logic.

Vulnerable code example:

[source,java]
----
String input = request.getParameter("input");
String formatStr = "%" + input;
String output = String.format(formatStr, "some value");
----

The above code is vulnerable because it takes user input from the "input" parameter and directly uses it in the format string without proper validation or sanitization. An attacker can manipulate the format string parameter, leading to unexpected behavior, such as format string vulnerabilities or information disclosure.

=== Fix - Buildtime

To fix this issue, never use user-supplied input directly in format strings. Instead, use hardcoded strings containing the required specifiers. Here is an example of secure code:

[source,java]
----
String formatStr = "%s"; // Assuming string format
String output = String.format(formatStr, "some value");
----

In the secure code example, the format string is hardcoded as "%s" which specifies a string format. This eliminates the potential for user input to manipulate the format string parameter.
    