
== Improper neutralization of special elements used in a command

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| c5b0321c-fe2d-44fb-afe0-7ccbb42c8676

|Checkov ID 
|CKV3_SAST_121

|Severity
|HIGH

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/77.html[CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection')]

|OWASP Categories
|https://owasp.org/Top10/A03_2021-Injection/[A03:2021 - Injection]

|=== 

=== Description

This SAST policy detects instances where special elements used in a command are not properly neutralized. Specifically, it looks for cases where `MimeMessage` methods are called without encoding new line characters.

Vulnerable code example:

[source,java]
```
MimeMessage message = new MimeMessage(session);
message.setSubject("User input");
message.addHeader("X-Header", userValue);
```

In the above code, the user-provided value for `userValue` is directly passed to the `addHeader` method of the `MimeMessage` object. This can lead to command injection vulnerabilities if the `userValue` contains special characters that could be interpreted as commands or malicious input.

=== Fix - Buildtime

To fix this issue, the `userValue` should be properly encoded before being passed to the `addHeader` method. This can be done using methods such as `StringEscapeUtils.escapeJava()` or `URLEncoder.encode()`. 

Secure code example:

[source,java]
```
MimeMessage message = new MimeMessage(session);
message.setSubject("User input");
message.addHeader("X-Header", StringEscapeUtils.escapeJava(userValue));
```

In the secure version of the code, the `userValue` is first escaped using `StringEscapeUtils.escapeJava()` to ensure that any special characters are properly encoded. This prevents command injection vulnerabilities by ensuring that the value is treated as plain text and not interpreted as commands or malicious input.
    