
== External control of system or configuration setting

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| dbc76faa-c1b4-453c-b5f2-fcd37ba94c9c

|Checkov ID 
|CKV3_SAST_108

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/15.html[CWE:15 - External Control of System or Configuration Setting]

|OWASP Categories
|https://owasp.org/Top10/A05_2021-Security_Misconfiguration/[A05:2021 - Security Misconfiguration]

|=== 

=== Description

This SAST policy detects instances where user input is used in the `java.sql.Connection`'s `setCatalog` call. This can be a potential issue as it may allow attackers to change the database during a connection, leading to disruptions or unexpected behaviors.

Vulnerable code example:

[source,java]
----
String userInput = request.getParameter("catalogName");
connection.setCatalog(userInput);
----

In the above code, the `setCatalog` method uses user input `catalogName` directly without any validation or sanitization. This allows an attacker to manipulate the `catalogName` parameter and potentially change the database being accessed.

=== Fix - Buildtime

To fix this issue, it is important to properly validate and sanitize the user input before using it in the `setCatalog` call. This can be done by implementing input validation and only allowing certain values or ensuring the input matches specific patterns.

Secure code example:

[source,java]
----
String userInput = request.getParameter("catalogName");
if(isValidCatalogName(userInput)) {
    connection.setCatalog(userInput);
}
----

In the secure code example, a function `isValidCatalogName` is used to validate the `userInput`. Only if the `userInput` passes the validation, it is used in the `setCatalog` call. This prevents malicious input from being used to change the database during the connection.

By implementing proper input validation and sanitization, the risk of external control of system or configuration settings is mitigated.
    