
== Missing authentication for critical function (database)

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 0cafe32d-6f7f-473f-ae55-7a96c3464acd

|Checkov ID 
|CKV3_SAST_139

|Severity
|MEDIUM

|Subtype
|Build

|Language
|java

|CWEs
|https://cwe.mitre.org/data/definitions/306.html[CWE-306: Missing Authentication for Critical Function]

|OWASP Categories
|https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/[A07:2021 - Identification and Authentication Failures]

|=== 

=== Description

This SAST policy detects the presence of missing authentication for a critical function (database) in Java code. It looks for two specific patterns:
1. `DriverManager.getConnection($URI, $USR, "");`
2. `$DS.setPassword("")`

Vulnerable code example:

[source,java]
----
DriverManager.getConnection("jdbc:mysql://localhost:3306/myDB", "root", "");
----

The above code is vulnerable because it establishes a connection to a MySQL database without providing any authentication credentials. This means that anyone with access to the code can execute queries on the database without authentication.

=== Fix - Buildtime

To fix this issue, proper authentication should be implemented when communicating with the database server. This can be done by providing valid username and password credentials when establishing the connection.

Secure code example:

[source,java]
----
DriverManager.getConnection("jdbc:mysql://localhost:3306/myDB", "root", "password");
----

In the secure version of the code, a secure password (e.g., "password") is provided as an argument to the `getConnection` method. This ensures that only authorized users with the correct credentials can access and execute queries on the database.
    