== RDS database does not have IAM authentication enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 174e5082-331c-4cb7-9643-0d53e96a485f

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/resource/aws/RDSIAMAuthentication.py[CKV_AWS_161]

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


IAM authentication uses AWS Identity and Access Management (IAM) to authenticate users and applications that connect to your RDS database.
This can be more secure than traditional password-based authentication, as it allows you to use IAM policies and multi-factor authentication to control access to your database.

=== Fix - Buildtime


*Terraform* 


* *Resource:* "aws_db_instance
* *Arguments:* iam_database_authentication_enabled


[source,go]
----
resource "aws_db_instance" "test" {
    ...
+ iam_database_authentication_enabled = true
}
----


*CloudFormation* 


* *Resource:* "AWS::RDS::DBInstance
* *Arguments:* Properties.EnableIAMDatabaseAuthentication


[source,yaml]
----
Resources:
  DB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: 'mysql' # or 'postgres'
      ...
+     EnableIAMDatabaseAuthentication: true
----
