== AWS IAM password policy does not have an uppercase character


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 31626ca9-f659-4d25-9d88-fa32262bbba7

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/PasswordPolicyUppercaseLetter.py[CKV_AWS_15]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Password policies are used to enforce the creation and use of password complexity.
Your IAM password policy should be set for passwords to require the inclusion of different character types.
The password policy should enforce passwords contain at least one uppercase letter, this increases security, especially from a brute force attack.

////
=== Fix - Runtime


* AWS Console* 


To change the password policy in the AWS Console you will need appropriate permissions to View Identity Access Management Account Settings.
To manually set the password policy with a minimum length, follow these steps:

. Log in to the AWS Management Console as an * IAM user* at https://console.aws.amazon.com/iam/.

. Navigate to * IAM Services*.

. On the Left Pane click * Account Settings*.

. Select * Requires at least one uppercase letter*.

. Click * Apply password policy*.


* CLI Command* 


To change the password policy, use the following command:
[,bash]
----
aws iam update-account-password-policy --require-uppercase-characters
----
////

=== Fix - Buildtime


*Terraform* 




* *Resource:* 
* *Argument: require_uppercase_characters* 



////
[source,go]
----
{
 "",

}
----
////

NOTE: All commands starting with *aws iam update-account-password-policy* can be combined into a single command.
