== AWS IAM password policy does not have a symbol


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| fd4dae57-509e-4374-96d3-e136821fc3f3

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/PasswordPolicySymbol.py[CKV_AWS_14]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Password policies are used to enforce the creation and use of password complexity.
Your IAM password policy should be set for passwords to require the inclusion of different character types.
The password policy should enforce passwords contain at least one symbol, this increases security, especially from a brute force attack.

////
=== Fix - Runtime


* AWS Console* 


To change the password policy in the AWS Console you will need appropriate permissions to View Identity Access Management Account Settings.
go To manually set the password policy with a minimum length, follow these steps:

. Log in to the AWS Management Console as an * IAM user* at https://console.aws.amazon.com/iam/.

. Navigate to * IAM Services*.

. On the Left Pane click * Account Settings*.

. Select * Require at least one non-alphanumeric character*.

. Click * Apply password policy*.


* CLI Command* 


To change the password policy, use the following command:
[,bash]
----
aws iam update-account-password-policy --require-symbols
----
////

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "aws_iam_account_password_policy" "strict" {
  minimum_password_length        = 8
  require_lowercase_characters   = true
  require_numbers                = true
  require_uppercase_characters   = true
  require_symbols                = true
  allow_users_to_change_password = true
}
----

NOTE: All commands starting with *aws iam update-account-password-policy* can be combined into a single command.
