== Google Cloud Pub/Sub

https://cloud.google.com/pubsub/[Google Cloud Pub/Sub] is a durable, scalable event ingestion and delivery system.
It provides asynchronous messaging that decouples senders from receivers, and enables highly available communication between independently written applications.

Prisma Cloud can send alerts to Google Cloud Pub/Sub https://cloud.google.com/pubsub/architecture[topics], where a topic is a message feed.


// == Configuring alerts
//
// Reusable content fragment.
include::frag-config-rate.adoc[leveloffset=0]


=== Sending alerts to Google Cloud Pub/Sub

// Reusable content fragment
:google_cloud_pub_sub:
include::frag-send-alerts.adoc[leveloffset=0]


[.task]
=== Create new alert profile

Create a new alert profile.

*Prerequisite:* You've set up a Cloud Pub/Sub topic.

[.procedure]
. In *Manage > Alerts*, click *Add profile*.

. Enter a name for your alert profile.

. In *Provider*, select *GCP Pub/Sub*.


[.task]
=== Configure the channel

Configure the channel.

[.procedure]
. In *Credential*, click *Add new* or select an existing service account.
+
Create a new xref:~/authentication/credentials-store/gcp-credentials.adoc[GCP credential] as needed.

. Enter a Cloud Pub/Sub topic.

. Click *Send Test Alert* to test the connection.

// Reusable content fragment.
include::frag-config-triggers.adoc[leveloffset=0]
