== Default VPC is planned to be provisioned


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 85866910-4a92-4a99-b71c-fd309a49b3de

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/aws/VPCDefaultNetwork.py[CKV_AWS_148]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


A default VPC is a VPC that is created for your AWS account when you create an AWS account.
It includes a default security group and a default network access control list (NACL).
Default VPCs have some limitations that might not be suitable for all use cases.
Therefore, if you have specific requirements for your VPC, such as custom IP address ranges, support for PrivateLink or Transit Gateway, or the ability to delete the VPC, it might be more appropriate to create a custom VPC instead of using the default VPC.

=== Fix - Buildtime


*Terraform* 


It is recommended for this resource to not be configured


[source,go]
----
resource "aws_default_vpc" "default" {
            tags = {
                Name = "Default VPC"
            }
        }
----
