== Alibaba Cloud OSS bucket has access logging enabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| da426a37-d689-4d72-8362-7596f8576a0f

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/OSSBucketAccessLogs.py[CKV_ALI_12]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description 


Enabling 'Access Logging' for an Alibaba Cloud OSS bucket allows you to record information about each request made to the bucket, including the request type, the source IP address, the object accessed, and the response status. This feature is beneficial for tracking and monitoring access to the bucket, identifying potential security risks or unauthorized access, and enhancing overall security and management of the bucket. In addition, access logging serves as a useful tool for auditing purposes, as it provides a comprehensive record of all requests made to the bucket.



=== Fix - Buildtime


*Terraform* 
To enable 'Access Logging' for an Alibaba Cloud OSS bucket, add the following code to your Terraform file during buildtime.




[source,go]
----
resource "alicloud_oss_bucket" "pass" {
  bucket = "bucket-170309-logging"

  logging {
    target_bucket = alicloud_oss_bucket.bucket-target.id
    target_prefix = "log/"
  }
}
Footer
----

