== Visibility

Today's engineering ecosystem consists of multiple teams and developers creating diverse applications using various technologies, operating at different stages of the development life cycle. These complexities create challenges, as organizations lack the visibility required to protect sensitive data, leaving it vulnerable to accidental leakage and intentional exfiltration by careless or malicious insiders. 

The Application Security module addresses these challenges by providing comprehensive visibility into  your engineering environment across code repositories, contributors, technologies and connected pipelines. With this insight you can identify specific code risks and issues, allowing you to understand and prioritize remediation, and safeguard your engineering environment. 

Application Security offers comprehensive visibility through the following features:

* xref:repositories.adoc[Repositories]

* xref:technologies.adoc[Technologies]

* xref:supply-chain.adoc[Supply Chain]

* xref:sbom.adoc[SBOM]

* xref:code-security-dashboard.adoc[Application Security Dashboard]
