== Typeform API Token


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 4d0f2321-6866-4fa9-b57c-1d7db2801acb

|Checkov ID 
|CKV_SECRET_70

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


To use the Typeform Create, Responses, and Webhooks APIs, you need to pass your personal access token in the Authorization header of your requests.
Access tokens are long strings of random characters that look something like this: tfp_943af478d3ff3d4d760020c11af102b79c440513.
The access token is unique per developer.
It is used to identify a given user and make sure that only you can access your typeforms and results.

=== Fix - Buildtime


*Typeform* 



. Log in to your account at Typeform.

. In the upper-left corner, in the drop-down menu next to your username, click Account.

. In the left menu, click Personal tokens or here.

. Identify the token you want to delete.

. Click ..., the three dots button in the right-side of the list.

. Click Delete this token.
