== Sumo Logic Keys


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| b5ba4ba2-8e01-4055-8086-e97a5ef5b598

|Checkov ID 
|CKV_SECRET_67

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


The Sumo Logic Access Keys Management API allows developers to securely register new Collectors or access Sumo Logic APIs.
This API was built with OpenAPI.
Developers can generate client libraries in many languages and explore automated testing.

=== Fix - Buildtime


*Sumo Logic* 



. If you have the Create Access Keys role capability, you can use the Preferences page to create access keys.
+
You can use the Preferences page to edit, activate, deactivate, and delete your access keys.

. When you mouse over an access key on the Preferences page, several controls appear.

. Use the trash can icon to permanently remove the access key.
+
The key will no longer be usable for API calls.
+
However, deleting a key used to register a Collector does not affect the Collector, as the only time a Collector uses the access key is at installation.
