== PubNub Subscription Key


=== Policy Details

[width=45%]
[cols="1,1"]
|===
|Prisma Cloud Policy ID
|TBD

|Checkov Check ID
|CKV_SECRET_92

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|===



=== Description

A PubNub Subscription Key is used to receive or subscribe to messages on the PubNub Data Stream Network (DSN). It is part of a key pair, the Publish Key and the Subscribe Key, which identifies your unique PubNub application and channel for transmitting and receiving real-time messages. It's important to keep these keys secure as they can be used to access your PubNub channels.


=== Fix - Buildtime


*PubNub*

There isn't a direct method to revoke or regenerate a PubNub Subscription Key. If a key is compromised, you generally need to create a new key set (Publish Key, Subscribe Key) in the PubNub Admin Dashboard and replace the old keys in your application code. In some situations, you might need to create a new PubNub project and move your application over to the new project with a new set of keys. Always refer to the latest PubNub documentation for current practices.
