== Airtable API Key


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 8058279d-25be-4115-bd84-6b830faa3c5d

|Checkov ID 
|CKV_SECRET_21

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


Airtable is a spreadsheet-database hybrid, with the features of a database but applied to a spreadsheet.
The fields in an Airtable table are similar to cells in a spreadsheet, but have types such as 'checkbox', 'phone number', and 'drop-down list', and can reference file attachments like images.
Users can create a database, set up column types, add records, link tables to one another, collaborate, sort records and publish views to external websites.
The Airtable Airtable API key allows users to use our public API to create, fetch, update, and delete records in the bases you have access to in Airtable.
API keys follow the same permissions that an account has in the Airtable UI.

=== Fix - Buildtime


*Airtable If you accidentally reveal your API key, you should regenerate your API key as soon as possible at https://airtable.com/account.* 


To delete your key, click the Delete key option.
This will bring up a warning that deleting your key will break your API integrations.
Click the red Yes, delete key button to confirm your key deletion.
