== Stripe Access Key


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 53b697f8-bac9-4c27-8d37-ca29e62f7af5

|Checkov ID 
|CKV_SECRET_17

|Severity
|MEDIUM

|Subtype
|Build

|Frameworks
|Git

|=== 



=== Description 


Stripe authenticates your API requests using your account's API keys.
If you do not include your key when making an API request, or use one that is incorrect or outdated, Stripe returns an error.
Secret API keys should be kept confidential and only stored on your own servers.
Your account's secret API key can perform any API request to Stripe without restriction.

=== Fix - Buildtime


*Stripe* 



.  Revoke the exposed secret.
+
Users with Administrator permissions can access a Stripe account's API keys by navigating to the Developers section of the Stripe dashboard and clicking on API Keys.
+
If you no longer need a restricted key (or you suspect it has been compromised), you can revoke it at any time.
+
You can also edit the key to change its level of access.

.  Clean the git history.
