== GCP Kubernetes Engine private cluster has private endpoint disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 1478c66d-2911-4a19-80fb-ddc36ab2a270

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/GKEPrivateClusterConfig.py[CKV_GCP_25]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|Terraform,TerraformPlan

|=== 



=== Description 


Private clusters enable isolation of nodes from any inbound and outbound connectivity to the public internet.
This is achieved as the nodes have internal RFC 1918 IP addresses only.
In private clusters, the cluster master has private and public endpoints.
You can configure which endpoint should be enabled or disabled to control access to the public internet.
We recommend you enable private cluster when creating Kubernetes clusters.
By creating a private cluster, the nodes will have a reserved set of IP addresses, ensuring their workloads are isolated from the public internet.

=== Fix - Buildtime


*Terraform* 


Add Block: *private_cluster_config* with attribute  *enable_private_nodes* set to _true_.


[source,go]
----
resource "google_container_cluster" "cluster" {
...
+ private_cluster_config {
+   enable_private_nodes=true
+ }
...
}
----

