== 3.14.12

//'''
//
//title: 3.14.12
//type: list
//url: "/3.14/release-notes/3.14.12/"
//menu:
//  3.14:
//    parent: "release-notes"
//    identifier: 3.14.12
//    weight: 11
//
//'''

May 3, 2021

=== What's new

The enforcer now keeps count of dropped packets in a file on each host.
This allows you to retrieve the data closer to real time, rather than waiting for it to reach the Microsegmentation Console.

=== Resolved issues

* *CNS-1899*: Windows host enforcers no longer occasionally drop packets when the network policy IP address range exceeds that of the target network.
* *CNS-1978*: Windows host enforcers no longer log spurious `Enforcerd crashed during the last run` messages each time they start up.
* *CNS-1988*: Stopping and restarting a host with more than 8.5K host-networked containers no longer causes some packets to be dropped.

=== Known issues

* *APO-146*: RHEL 8 and RHEL CoreOS 8 (used by OpenShift 4) have deprecated `iptables` in favor of `nftables`.
Before installing Aporeto in these environments, you must enable `iptables`, such as via the following commands:
+
[,console]
----
modprobe ip_tables
modprobe iptable_nat
----

* *CNS-153*: When using relative time values with `apoctl`, the values must be in relation to Pacific Standard Time (PST).
For example, if you are in France and want to retrieve the last five minues of flow logs, you could use `-9h5m`.
Another workaround for this issue is to use absolute time values.
* *CNS-614*: The prebuilt CentOS 7.0 images distributed by OpenStack prefixed with `CentOS-7-x86_64-GenericCloud-2014` do not include the `xt_cgroups.ko` kernel module xref:../start/enforcer/reqs.adoc#_kernel-modules[required by the enforcer].
* *CNS-121*: When multiple clients attempt to connect to the same HTTP service on a Windows host, some may experience timeouts.
* *CNS-126*: After decommissioning an enforcer, you may find some of its iptables rules still in place.
* *CNS-1343*: The enforcer fails to program external networks that use the `!` operator on Red Hat Enterprise Linux 6.
* *CNS-1356*: You must use an enforcer profile to manually add the URL of the Microsegmentation Console API to as an excluded network for Red Hat Enterprise Linux 6 hosts.
Failing to do so before installing the enforcer causes a complete lack of access to the host.

=== Deprecation notices

A future release will remove support for the following.
Please plan accordingly.

* *App integrations*: 5.0 will not include the Clair vulnerability scanner or any other app integrations.
* *CoreOS, Oracle Enterprise Linux (OEL), and Red Hat Enterprise Linux (RHEL) 6*: upgrade to CoreOS/OEL/RHEL 7 or later.
* *Custom resource definitions*: Aporeto won't create https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[custom resource definitions (CRDs)] in Kubernetes/OpenShift.
* *Enforcer as standalone container*: you must install the 5.0 enforcer as a Linux/Windows service or Kubernetes/OpenShift `DaemonSet`.
* *Enforcer audit logging capabilities*: due to a lack of adoption.
* *Host services*: migrate to external networks and network policies.
* *`kubenet` support*: migrate to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/[CNI plugins] if necessary.
For example, GKE clusters use `kubenet` by default.
Pass the `--enable-network-policy` flag to modify GKE clusters to use CNI plugins instead.
* *xref:../start/control-plane/multi-region.adoc[Multi-region control planes]*: migrate to xref:../scale/multi-ctrl-plane.adoc[federated control planes].
* *Namespace editor and namespace auditor roles*: migrate users to equivalent roles.
For example, migrate users with the *Namespace editor* role to *Namespace administrator*.
* *Namespace mapping for enforcers*: 5.0 removes support. If you require this, contact us.
* *xref:../secure/ssh/ssh.adoc[SSH controls]*: ignored by the 5.0 enforcer.
