== 3.14.13

//'''
//
//title: 3.14.13
//type: list
//url: "/3.14/release-notes/3.14.13/"
//menu:
//  3.14:
//    parent: "release-notes"
//    identifier: 3.14.13
//    weight: 10
//
//'''

July 1, 2021

=== Resolved issues

* *CNS-2396*: Host mode processsing units (PUs) may experience issues when trying to connect to other VMs within a target network.
* *CNS-2395*: No support for port 0 in discovery mode.
* *CNS-2345*: Upstream UBI changes cause segfault for the iptables binary in 3.14.
* *CNS-2313*: Windows 3.14.12 enforcer upgrade installation initiates a reboot.

=== End of Life notices (EoL)

* *3.14 release*: The 3.14 release train will go End of Life in Oct 2021. Prior to EoL we will only provide patch releases for critical severity bug fixes. Afer EoL we will no longer offer bug fixes for the 3.14 release.
* *Host services*: This feature is now End of Life. For reference we announced deprecation of this feature back in 3.14.10. Please install enforcer for Linux hosts or Windows hosts and migrate to external networks and network policies.
