[#permissions]
== Permissions by feature

When you set up Prisma Cloud Compute to secure your cloud workloads, you'll need to ensure you've granted Prisma Cloud the right permissions.
The following tables list the permissions required for each of Compute's protection capabilities.

You can review the permissions needed for agentless scanning in each cloud service provider:

* <<#aws-agentless,AWS>>
* <<#azure-agentless,Azure>>
* <<#gcp-agentless,GCP>>

[#aws]
=== AWS

The following table shows the required permissions needed if you are using AWS.
You can also review the <<#aws-agentless,permissions needed for agentless scanning in AWS>>.

[format=csv, options="header"]
|===
include::https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?output=csv&gid=338970097[]
|===

[#aws-agentless]
==== Agentless Permissions

The following table shows the required permissions, conditions, and resources for agentless scanning.

[format=csv, options="header"]
|===
include::https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?gid=1092315741&output=csv[]
|===

Go to the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#ebs-encryption-requirements[AWS documentation for the official list of permissions needed to support EBS encryption].

[#gcp]
=== GCP

The following table shows the required permissions needed if you are using GCP.
You can also review the <<#gcp-agentless,permissions needed for agentless scanning in GCP>>.

[format=csv, options="header"]
|===
include::https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?output=csv&gid=942713996[]
|===

[#gcp-agentless]
==== Agentless Permissions

The following table shows the required permissions for agentless scanning.

[format=csv, options="header"]
|===
include::https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?gid=1171299197&output=csv[]
|===

[#azure]
=== Azure

The following table shows the required permissions needed if you are using Azure.
You can also review the <<#azure-agentless,permissions needed for agentless scanning in Azure>>.

[format=csv, options="header"]
|===
include::https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?output=csv&gid=0[]
|===

[#azure-agentless]
==== Agentless Permissions

The following table shows the required permissions for agentless scanning.

[format=csv, options="header"]
|===
include::https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?gid=1554693542&output=csv[]
|===

Use these link to download the permissions as a text file for the https://docs.paloaltonetworks.com/content/dam/techdocs/en_US/pdf/prisma/prisma-cloud/prerelease/azure-commercial-permissions-security-coverage.txt[Azure Commercial] | https://docs.paloaltonetworks.com/content/dam/techdocs/en_US/pdf/prisma/prisma-cloud/prerelease/azure-government-permissions-security-coverage.txt[Azure Government] environments
