---
kind: book
title: Prisma® Cloud Application Security
author: Prisma Cloud Tech Docs
ditamap: prisma-cloud-application-security
dita: techdocs/en_US/dita/prisma/prisma-cloud/prisma-cloud-application-security
graphics: techdocs/en_US/dita/_graphics/uv/prisma/prisma-cloud/prisma-cloud-application-security
github:
  owner: PaloAltoNetworks
  repo: prisma-cloud-docs
  bookdir: application-security
  branch: application-security
---
kind: chapter
name: Application Security
dir: application-security
topics:
  - name: Application Security
    file: application-security.adoc
  - name: Familiarize Yourself with Application Security
    file: familiarize-application-security.adoc
  - name: Supported Technologies
    file: supported-technologies.adoc
  - name: Get Started with Application Security
    dir: get-started
    topics:
      - name: Get Started with Application Security
        file: get-started.adoc
      - name: Enable Application Security
        file: enable-application-security.adoc
      - name: Application Security License Types
        file: application-security-license-types.adoc
      - name: Manage Roles and Permissions
        file: manage-roles-permissions.adoc
      - name: Connect Code and Build Providers
        dir: connect-code-and-build-providers
        topics:
          - name: Connect Code and Build Providers
            file: connect-code-and-build-providers.adoc
          - name: Code Repositories
            dir: code-repositories
            topics:
              - name: Code Repositories
                file: code-repositories.adoc
              - name: Azure Repos
                file: add-azurerepos.adoc
              - name: Bitbucket
                file: add-bitbucket.adoc
              - name: Bitbucket Server
                file: add-bitbucket-server.adoc
              - name: GitHub
                file: add-github.adoc
              - name: Github Server
                file: add-github-server.adoc
              - name: GitLab
                file: add-gitlab.adoc
              - name: Gitlab Self-managed
                file: add-gitlab-selfmanaged.adoc
          - name: CI/CD Runs
            dir: ci-cd-runs
            topics:
              - name: CI/CD Runs
                file: ci-cd-runs.adoc
              - name: Azure Pipelines
                file: add-azure-pipelines.adoc
              - name: AWS Code Build
                file: add-aws-codebuild.adoc
              - name: Checkov
                file: add-checkov.adoc
              - name: CircleCI
                file: add-circleci.adoc
              - name: GitHub Actions
                file: add-github-actions.adoc
              - name: GitLab Runner
                file: add-gitlab-runner.adoc
              - name: Jenkins Server
                file: add-jenkins.adoc
              - name: Terraform Cloud (Run Tasks)
                file: add-terraform-run-tasks.adoc
              - name: Terraform Cloud (Sentinel)
                file: add-terraform-cloud-sentinel.adoc
              - name: Terraform Enterprise (Run Tasks)
                file: add-terraform-enterprise-run-tasks.adoc
              - name: Terraform Enterprise (Sentinel)
                file: add-terraform-enterprise.adoc
          - name: CI/CD Systems
            dir: ci-cd-systems
            topics:
              - name: CI/CD Systems
                file: ci-cd-systems.adoc
              - name: CircleCI
                file: add-circleci-cicd-system.adoc
              - name: Jenkins Server
                file: add-jenkins-cicd-system.adoc
          - name: Package Registries
            file: add-private-registries.adoc
          - name: IDEs
            dir: ides
            topics:
              - name: IDEs
                file: ides.adoc
              - name: VS Code
                file: connect-vscode.adoc             
              - name: Jetbrains
                file: connect-jetbrains.adoc
      - name: Manage Transporter (Network Tunnels)
        dir: manage-network-tunnel
        topics:
          - name: Manage Transporter (Network Tunnels)
            file: manage-network-tunnel.adoc
          - name: Transporter Connectivity Overview
            file: transporter-connectivity-overview.adoc
          - name: Set Up Transporter Network Tunnels using Docker Containers
            file: deploy-transporter-docker.adoc
          - name: Set Up Transporter Network Tunnels using Helm Charts
            file: deploy-transporter-helmcharts.adoc
          - name: Select Transporter and ensure Domain Name Consistency
            file: select-transporter-domain-consistency.adoc
      - name: Application Security Settings
        dir: application-security-settings
        topics:
          - name: Application Security Settings
            file: application-security-settings.adoc
          - name: Enable Notifications
            file: enable-notifications.adoc
          - name: Exclude Paths
            file: exclude-paths.adoc
#          - name: Code Reviews and PR Comments
#            file: code-reviews-pr-comments.adoc
      - name: Add Prisma Cloud Code Security Scanner as a Pre-Receive Hook
        file: add-pre-receive-hooks.adoc
  - name: Visibility
    dir: visibility
    topics:
      - name: Visibility
        file: visibility.adoc
      - name: Repositories
        file: repositories.adoc
      - name: Technologies
        dir: technologies
        topics:
          - name: Technologies
            file: technologies.adoc
          - name: Technology Overview
            file: technology-overview.adoc
          - name: VCS 3rd Parties
            file: vcs-third-parties.adoc
          - name: Jenkins Plugins
            file: jenkins-plugins.adoc
          - name: Pipeline Tools
            file: pipeline-tools.adoc
      - name: SBOM
        file: sbom.adoc
  - name: Risk Management
    dir: risk-management
    topics:
      - name: Risk Management
        file: risk-management.adoc
      - name: Monitor and Manage Code Build Issues
        dir: monitor-and-manage-code-build
        topics:
          - name: Monitor and Manage Code Build Issues
            file: monitor-and-manage-code-build.adoc
          - name: Monitor Code Build Issues
            file: monitor-code-build-issues.adoc
          - name: Enforcement
            file: enforcement.adoc
          - name: Drift Detection
            file: drift-detection.adoc
          - name: Software Composition Analysis (SCA)
            dir: software-composition-analysis
            topics:
              - name: Software Composition Analysis (SCA)
                file: software-composition-analysis.adoc
              - name: License Compliance in Software Composition Analysis (SCA)
                file: license-compliance-in-sca.adoc
              - name: Supported Package Managers
                file: supported-package-managers.adoc
          - name: Secrets Scanning
            file: secrets-scanning.adoc
          - name: Fix Code Issues
            file: fix-code-issues.adoc
          - name: Suppress Code Issues
            file: suppress-code-issues.adoc
          - name: Traceability and Tagging
            file: traceability-and-tagging.adoc
      - name: CI/CD Risks
        file: ci-cd-risks.adoc
---

