#%RAML 1.0 SecurityScheme
description: Authenticate each request with an access token.
             Request authorization and retrieve an access token using the /api/v1/authenticate endpoint.
type: x-jwt
describedBy:
  headers:
    Authorization:
      description: When sending the access token in the Authorization header field, use the Bearer authentication scheme
                   to transmit the access token.
      type: string
      example: |
        Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImF1dGhUeXBlIjoiYmFzaWMiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTQ3NzQ5MTU4MywiZXhwIjoxNDc3NTc3OTgzfQ.X4ExX7bFWa4m_WXKImmLO9rYDmxnLrBnoAHAA-vulik
  responses:
    401:
      description: |
        Unauthorized. Bad parameters.
        Either the provided access token is invalid, the token is expired, or the user is not
        allowed to access the content provided by the requested URL.
