#%RAML 1.0
title: Prisma Cloud Compute
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: https://{CONSOLE}:{PORT}/api/{version}
baseUriParameters:
  CONSOLE:
    description:
      "
      Hostname or IP address where Console can be accessed.
      "
  PORT:
    description:
      "
      Use port 8081 to access the API over HTTP.
      Use port 8083 to access the API over HTTPS.
      You can configure Twistlock to use alternative ports at install time in *twistlock.cfg*.
      "
mediaType: application/json
securitySchemes:
  basicAuth: !include ../securitySchemes/basic-auth.raml
  jwtAccessToken: !include ../securitySchemes/jwt-access-token.raml
# TODO: Provide an intro to the API
documentation: !include ../documentation.raml
traits: !include ../traits/all.raml

# Resources
# Additional resources can be added via _build/add_endpoints.json
