== Alibaba Cloud KMS Key Rotation is disabled


=== Policy Details
[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 57146ef0-2467-4e9c-a474-7f99dc771640

|Checkov ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/alicloud/KMSKeyRotationIsEnabled.py[CKV_ALI_27]

|Severity
|LOW

|Subtype
|Build

|Frameworks
|Terraform

|=== 



=== Description

A key is a named object representing a cryptographic key used for a specific purpose, including data protection.
The key material, the actual bits used for encryption, can change over time as new key versions are created.
A collection of files could be encrypted with the same key and people with decrypt permissions on that key would be able to decrypt those files.
We recommend you set a key rotation period.
A key can be created with a specified rotation period, which is the time when new key versions are generated automatically.
A key can also be created with a specified next rotation time.

=== Fix - Buildtime


*Terraform* 




[source,go]
----
resource "alicloud_kms_key" "pass" {
  description             = "Hello KMS"
  pending_window_in_days  = "7"
  status                  = "Enabled"
  automatic_rotation      = "Enabled"
}
----
