== Get Started with Prisma Cloud Application Security

During the stage of development to deployment the agile teams typically are focused on working on Infrastructure-as-Code (IaC), where the team branch their work from the main branch and implement changes to resources, check for dependency, implement change provisioning, and eventually merge and deploy the changes. During this process however, security checks are missed. Prisma Cloud's Code Security provides these teams with features to add security checks to their existing IaC model, ensuring security throughout the build lifecycle.
Code Security integrates with a wide variety of code repositories and continuous integration and continuous delivery (CI/CD) workflows to secure cloud infrastructure, and applications early in development. You can scan Infrastructure-as-Code (IaC) templates in Terraform, CloudFormation, ARM,and Kubernetes to identify and fix misconfigurations in code, and for continuous governance to enforce policies.

If you are looking to use the APIs, see https://pan.dev/prisma-cloud/api/code/[Cloud Application Security API documentation].
