== What is Prisma Cloud Code Security?

Prisma Cloud Code Security helps address cloud infrastructure misconfigurations in code before they become alerts or incidents that security teams then need to triage.
It enables you to embed your existing DevOps resources and operates within the DevSecOps model, to provide developer-friendly feedback so that they can fix configuration issues before the code is released to be deployed into your environments.
You have additional option to create custom policies or include multiple out-of-the-box security policies all in your existing IaC environment. Code Security on Prisma Cloud gives you instant feedback and options for immediate resolutions to your scanned misconfigurations.

The Code Security will be available for Prisma Cloud tenants in the following environments:

* app.prismacloud.io
* app2.prismacloud.io
* app3.prismacloud.io
* app4.prismacloud.io
* app.anz.prismacloud.io
* app.ca.prismacloud.io
* app.eu.prismacloud.io
* app2.eu.prismacloud.io
* app2.ind.prismacloud.io
* app.sg.prismacloud.io
* app.uk.prismacloud.io
* app.jp.prismacloud.io
* app.fr.prismacloud.io
