== Insecure use of `new Buffer()`

=== Policy Details

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| TBD

|Checkov ID 
|CKV3_SAST_42

|Severity
|LOW

|Subtype
|Build

|Language
|JavaScript

|CWEs
|https://cwe.mitre.org/data/definitions/119.html[CWE-119: Improper Restriction of Operations within the Bounds of a Memory Buffer]

|OWASP Categories
|https://owasp.org/www-project-top-ten/2004/A5-buffer-overflows/[A5:2004 - Buffer Overflows]

|=== 

=== Description

This policy identifies instances in JavaScript where the `new Buffer()` constructor is used with non-literal values. Such usage can lead to potential memory leaks. The `new Buffer()` constructor is considered unsafe when used with non-literal arguments, and it's recommended to use safer alternatives such as `Buffer.from()` or `Buffer.alloc()`.

For more information about the risks and deprecation of the `new Buffer()` constructor, refer to the [Node.js documentation](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/), the [Node.js GitHub issue](https://github.com/nodejs/node/issues/4660), and the [ESLint Community Plugin](https://github.com/eslint-community/eslint-plugin-security/blob/main/rules/detect-new-buffer.js).

Example of violating code:

[source,javascript]
----
let userSize = getUserInput();  // Potentially unsafe user input
let buffer = new Buffer(userSize);
----

=== Fix - Buildtime

To mitigate this issue, replace the use of the `new Buffer()` constructor with safer alternatives. Preferably use `Buffer.from()` or `Buffer.alloc()` based on your specific requirements.

Example of corrected code:

[source,javascript]
----
let userSize = getUserInput();
let buffer = Buffer.alloc(parseInt(userSize, 10));
----

In the corrected example, the safer `Buffer.alloc()` method is utilized, ensuring controlled memory allocation and reducing potential risks.
