== AWS S3 Object Versioning is disabled


=== Policy Details 

[width=45%]
[cols="1,1"]
|=== 
|Prisma Cloud Policy ID 
| 89ea62c1-3845-4134-b337-cc82203b8ff9

|Checkov Check ID 
| https://github.com/bridgecrewio/checkov/tree/master/checkov/common/graph/checks_infra/base_check.py[CKV_AWS_21]

|Severity
|MEDIUM

|Subtype
|Build
//, Run

|Frameworks
|CloudFormation,Terraform,TerraformPlan,Serverless

|=== 



=== Description 


S3 versioning is a managed data backup and recovery service provided by AWS.
When enabled it allows users to retrieve and restore previous versions of their buckets.
S3 versioning can be used for data protection and retention scenarios such as recovering objects that have been accidentally/intentionally deleted or overwritten.

////
=== Fix - Runtime


* AWS Console* 


To change the policy using the AWS Console, follow these steps:

. Log in to the AWS Management Console at https://console.aws.amazon.com/.

. Open the https://console.aws.amazon.com/s3/ [Amazon S3 console].

. Select the bucket that you want to configure.

. Select the * Properties* tab.

. Navigate to the * Permissions* section.

. Select * Edit bucket policy*.
+
If the selected bucket does not have an _access policy_, click * Add bucket policy*.

. Select the * Versioning* tab from the * Properties* panel, and expand the * feature configuration* section.

. To activate object versioning for the selected bucket, click * Enable Versioning*, then click * OK*.
+
The * feature status* should change to * versioning is currently enabled on this bucket*.
////

=== Fix - Buildtime


*Terraform* 


* *Resource:* aws_s3_bucket
* *Attribute:* version/enabled


[source,go]
----
{
 "resource "aws_s3_bucket" "state_bucket" {
  bucket        = "${data.aws_caller_identity.current.account_id}-terraform-state"
  acl           = var.acl
  force_destroy = var.force_destroy

+  versioning {
+    enabled    = true
+  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = var.sse_algorithm
      }

    }
  }


  tags = var.common_tags
}",


}
----
